"""Acceptance-focused tests for the ADR-008 shared Lean slot controller."""

from __future__ import annotations

import json
import os
import subprocess
from types import SimpleNamespace
from pathlib import Path

import pytest

from scripts.lean_slots.controller import Controller
from scripts.lean_slots.proxy import LeaseGate
from scripts.lean_slots.state import Inventory, SlotError
from scripts.lean_slots.state import atomic_json, process_start_signature
from scripts.lean_slots.supervisor import Supervisor


def run(cwd: Path, *command: str) -> str:
    return subprocess.run(
        list(command), cwd=cwd, check=True, capture_output=True, text=True
    ).stdout.strip()


@pytest.fixture()
def slot_repo(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> tuple[Controller, Path, list[Path]]:
    repo = tmp_path / "primary"
    repo.mkdir()
    run(repo, "git", "init", "-b", "main")
    run(repo, "git", "config", "user.name", "Slot Test")
    run(repo, "git", "config", "user.email", "slot@example.invalid")
    (repo / "lean").mkdir()
    (repo / "lean" / "lean-toolchain").write_text("leanprover/lean4:v4.test\n")
    (repo / "lean" / "lakefile.toml").write_text("name = 'Test'\n")
    (repo / "lean" / "lake-manifest.json").write_text("{}\n")
    (repo / "README.md").write_text("slot fixture\n")
    (repo / ".gitignore").write_text("lean/.lake/\n")
    run(repo, "git", "add", ".")
    run(repo, "git", "commit", "-m", "initial")
    worktrees = []
    for number in (1, 2, 3):
        worktree = tmp_path / f"wt{number}"
        run(
            repo,
            "git",
            "worktree",
            "add",
            "-b",
            f"worktree-wt{number}",
            str(worktree),
            "main",
        )
        worktrees.append(worktree)
    lake_build = repo / "lean" / ".lake" / "build"
    lake_build.mkdir(parents=True)
    (lake_build / "artifact").write_text("built\n")
    (repo / "config").mkdir()
    inventory = {
        "schema_version": 1,
        "repo_role": "public",
        "repo_root": "..",
        "max_active_slots": 3,
        "lease_timeout_seconds": 0,
        "slots": {
            str(number): {
                "worktree": f"../wt{number}",
                "branch": f"worktree-wt{number}",
                "endpoint_name": f"test_wt{number}",
                "proxy_port": 29000 + number,
                "backend_port": 29100 + number,
            }
            for number in (1, 2, 3)
        },
        "server": {
            "host": "127.0.0.1",
            "command": ["false"],
            "disabled_tools": ["lean_build"],
            "probe_file": "Test.lean",
            "instructions": "no builds",
            "startup_timeout_seconds": 1,
        },
        "build": {
            "cwd": "lean",
            "command": ["/usr/bin/true"],
            "fingerprint_files": [
                "lean/lean-toolchain",
                "lean/lakefile.toml",
                "lean/lake-manifest.json",
            ],
        },
    }
    inventory_path = repo / "config" / "lean-slots.public.json"
    inventory_path.write_text(json.dumps(inventory))
    (repo / ".codex" / "agents").mkdir(parents=True)
    (repo / ".codex" / "hooks").mkdir()
    (repo / ".codex" / "config.template.toml").write_text(
        "# GENERATED by scripts/slotctl.py config render.\n"
        "# source-digest = {{SOURCE_DIGEST}}\n"
        'repo = "{{REPO_ROOT}}"\n'
        'agent_dir = "{{AGENT_CONFIG_DIR}}"\n'
        "{{MCP_CLIENT_AUTH}}\n"
    )
    (repo / ".codex" / "agents" / "worker.toml").write_text(
        "name = 'worker'\nurl = 'http://127.0.0.1:29001/mcp'\n"
    )
    (repo / ".codex" / "hooks" / "pre_tool_use_policy.py").write_text("# policy\n")
    run(repo, "git", "add", "config", ".codex")
    run(repo, "git", "commit", "-m", "add slot infrastructure")
    monkeypatch.setenv("LEAN_SLOT_STATE_DIR", str(tmp_path / "state"))
    monkeypatch.setenv("LEAN_SLOT_SKIP_SUPERVISOR", "1")
    monkeypatch.setenv("LEAN_SLOT_OWNER_PID", str(os.getpid()))
    controller = Controller(Inventory.load(inventory_path))
    return controller, repo, worktrees


@pytest.fixture()
def downstream_repo(
    slot_repo, tmp_path: Path
) -> tuple[Controller, Controller, Path, list[Path]]:
    public_controller, public_repo, public_worktrees = slot_repo
    public_head = run(public_repo, "git", "rev-parse", "main")
    for number, worktree in enumerate(public_worktrees, 1):
        run(worktree, "git", "checkout", "-B", f"worktree-wt{number}", public_head)

    repo = tmp_path / "downstream"
    repo.mkdir()
    run(repo, "git", "init", "-b", "main")
    run(repo, "git", "config", "user.name", "Slot Test")
    run(repo, "git", "config", "user.email", "slot@example.invalid")
    (repo / "lean").mkdir()
    (repo / "lean" / "lean-toolchain").write_text("leanprover/lean4:v4.test\n")
    (repo / "lean" / "lakefile.toml").write_text(
        "name = 'Downstream'\n"
        "[[require]]\n"
        "name = 'Primary'\n"
        "path = '../../primary/lean'\n"
    )
    (repo / "lean" / "lake-manifest.json").write_text("{}\n")
    (repo / ".gitignore").write_text("lean/.lake/\n")
    run(repo, "git", "add", ".")
    run(repo, "git", "commit", "-m", "initial downstream")

    worktrees: list[Path] = []
    for number, public_worktree in enumerate(public_worktrees, 1):
        pair = tmp_path / "pairs" / f"wt{number}"
        pair.mkdir(parents=True)
        (pair / "primary").symlink_to(public_worktree, target_is_directory=True)
        worktree = pair / "downstream"
        run(
            repo,
            "git",
            "worktree",
            "add",
            "-b",
            f"worktree-wt{number}",
            str(worktree),
            "main",
        )
        worktrees.append(worktree)

    lake_build = repo / "lean" / ".lake" / "build"
    lake_build.mkdir(parents=True)
    (lake_build / "artifact").write_text("downstream built\n")
    (repo / "config").mkdir()
    inventory = {
        "schema_version": 1,
        "repo_role": "downstream",
        "repo_root": "..",
        "max_active_slots": 3,
        "lease_timeout_seconds": 0,
        "paired_dependency": {
            "inventory": "../../primary/config/lean-slots.public.json",
            "base_ref": "main",
            "lake_dependency_name": "Primary",
            "path_from_primary_lean": "../../primary/lean",
            "path_from_slot_lean": "../../primary/lean",
        },
        "config": {"manage_workspace": False},
        "slots": {
            str(number): {
                "worktree": f"../pairs/wt{number}/downstream",
                "branch": f"worktree-wt{number}",
                "endpoint_name": f"downstream_wt{number}",
                "proxy_port": 29200 + number,
                "backend_port": 29300 + number,
            }
            for number in (1, 2, 3)
        },
        "server": {
            "host": "127.0.0.1",
            "command": ["false"],
            "disabled_tools": ["lean_build"],
            "probe_file": "Test.lean",
            "instructions": "no builds",
            "startup_timeout_seconds": 1,
            "backend_policy": "leased",
        },
        "build": {
            "cwd": "lean",
            "command": ["/usr/bin/true"],
            "fingerprint_files": [
                "lean/lean-toolchain",
                "lean/lakefile.toml",
                "lean/lake-manifest.json",
            ],
        },
    }
    inventory_path = repo / "config" / "lean-slots.downstream.json"
    inventory_path.write_text(json.dumps(inventory))
    (repo / ".codex" / "agents").mkdir(parents=True)
    (repo / ".codex" / "hooks").mkdir()
    (repo / ".codex" / "config.template.toml").write_text(
        "# GENERATED by scripts/slotctl.py config render.\n"
        "# source-digest = {{SOURCE_DIGEST}}\n"
        'repo = "{{REPO_ROOT}}"\n'
    )
    (repo / ".codex" / "agents" / "worker.toml").write_text("name = 'worker'\n")
    (repo / ".codex" / "hooks" / "pre_tool_use_policy.py").write_text("# policy\n")
    run(repo, "git", "add", "config", ".codex")
    run(repo, "git", "commit", "-m", "add downstream slot infrastructure")
    controller = Controller(Inventory.load(inventory_path))
    return controller, public_controller, repo, worktrees


def prepare(controller: Controller, number: int, *, client: str = "codex") -> None:
    controller.acquire(number, client=client, base_ref="main")
    controller.prepare(number)


def commit(worktree: Path, filename: str, content: str) -> str:
    (worktree / filename).write_text(content)
    run(worktree, "git", "add", filename)
    run(worktree, "git", "commit", "-m", f"add {filename}")
    return run(worktree, "git", "rev-parse", "HEAD")


def test_inventory_is_exactly_three_global_slots(slot_repo) -> None:
    controller, _, _ = slot_repo
    assert set(controller.inventory.raw["slots"]) == {"1", "2", "3"}
    assert controller.inventory.raw["max_active_slots"] == 3
    with pytest.raises(SlotError, match="one of 1, 2, 3"):
        controller.acquire(4, client="codex", base_ref="main")


def test_cross_client_collision_fails_closed(slot_repo) -> None:
    controller, _, _ = slot_repo
    controller.acquire(1, client="codex", base_ref="main")
    with pytest.raises(SlotError, match="already leased by codex"):
        controller.acquire(1, client="claude", base_ref="main")


def test_trusted_local_lease_needs_no_client_token(slot_repo) -> None:
    controller, _, _ = slot_repo
    lease = controller.acquire(1, client="codex", base_ref="main")
    assert lease["client_auth"] == "trusted-local"
    assert "token_hash" not in lease
    assert not controller.inventory.client_token_path("codex").exists()


def test_bearer_lease_retains_client_token_binding(slot_repo) -> None:
    controller, _, _ = slot_repo
    controller.inventory.raw["server"]["client_auth"] = "bearer"
    lease = controller.acquire(1, client="codex", base_ref="main")
    assert lease["client_auth"] == "bearer"
    assert lease["token_hash"]
    assert controller.inventory.client_token_path("codex").exists()


def test_client_auth_mode_cannot_change_under_an_existing_lease(slot_repo) -> None:
    controller, _, _ = slot_repo
    controller.acquire(1, client="codex", base_ref="main")
    controller.inventory.raw["server"]["client_auth"] = "bearer"
    with pytest.raises(SlotError, match="client-auth mode mismatch"):
        controller.heartbeat(1)


def test_trusted_local_mode_rejects_non_loopback_binding(slot_repo) -> None:
    controller, _, _ = slot_repo
    controller.inventory.raw["server"]["host"] = "0.0.0.0"
    with pytest.raises(SlotError, match="requires a loopback"):
        _ = controller.inventory.client_auth_mode


def test_three_distinct_slots_can_be_leased(slot_repo) -> None:
    controller, _, _ = slot_repo
    for number in (1, 2, 3):
        controller.acquire(number, client="codex", base_ref="main")
    assert [item["lease"]["state"] for item in controller.status()["slots"]] == [
        "ACQUIRED",
        "ACQUIRED",
        "ACQUIRED",
    ]


def test_dirty_acquire_quarantines_without_deleting_work(slot_repo) -> None:
    controller, _, worktrees = slot_repo
    protected = worktrees[0] / "protected.lean"
    protected.write_text("theorem keep : True := by trivial\n")
    with pytest.raises(SlotError, match="quarantined"):
        controller.acquire(1, client="codex", base_ref="main")
    assert protected.exists()
    assert controller.inventory.lease(1)["state"] == "QUARANTINED"
    protected.unlink()
    controller.release(1)
    assert controller.inventory.lease(1, required=False) is None


def test_build_epoch_and_atomic_cache_prepare(slot_repo) -> None:
    controller, _, worktrees = slot_repo
    epoch = controller.build()
    prepare(controller, 2)
    lease = controller.inventory.lease(2)
    assert lease["state"] == "ACTIVE"
    assert lease["prepared_epoch"] == epoch["epoch_id"]
    assert (
        worktrees[1] / "lean" / ".lake" / "build" / "artifact"
    ).read_text() == "built\n"


def test_epoch_invalidates_when_dependency_fingerprint_changes(slot_repo) -> None:
    controller, repo, _ = slot_repo
    controller.build()
    (repo / "lean" / "lake-manifest.json").write_text('{"changed": true}\n')
    run(repo, "git", "add", "lean/lake-manifest.json")
    run(repo, "git", "commit", "-m", "change manifest")
    controller.acquire(1, client="codex", base_ref="main")
    with pytest.raises(SlotError, match="no successful-build epoch"):
        controller.prepare(1)


def test_ready_requires_clean_committed_work(slot_repo) -> None:
    controller, _, worktrees = slot_repo
    controller.build()
    prepare(controller, 1)
    (worktrees[0] / "draft.lean").write_text("draft\n")
    with pytest.raises(SlotError, match="quarantined"):
        controller.ready(1)
    assert controller.inventory.lease(1)["state"] == "QUARANTINED"


def test_absorb_refuses_a_head_changed_after_ready(slot_repo) -> None:
    controller, _, worktrees = slot_repo
    controller.build()
    prepare(controller, 1)
    commit(worktrees[0], "reviewed.txt", "reviewed\n")
    controller.ready(1)
    commit(worktrees[0], "late.txt", "late\n")
    with pytest.raises(SlotError, match="HEAD changed after ready"):
        controller.absorb(1)
    assert controller.inventory.lease(1)["state"] == "QUARANTINED"


def test_lake_clone_fallback_removes_partial_copy(
    slot_repo, monkeypatch: pytest.MonkeyPatch
) -> None:
    controller, _, worktrees = slot_repo

    def failed_clone(command, **kwargs):
        destination = Path(command[-1])
        destination.mkdir(parents=True)
        (destination / "partial").write_text("partial\n")
        return SimpleNamespace(returncode=1)

    monkeypatch.setattr("scripts.lean_slots.controller.subprocess.run", failed_clone)
    controller._replace_lake(3)
    destination = worktrees[2] / "lean" / ".lake"
    assert not (destination / "partial").exists()
    assert (destination / "build" / "artifact").read_text() == "built\n"


def test_two_sibling_workers_absorb_by_rebase_and_fast_forward(slot_repo) -> None:
    controller, repo, worktrees = slot_repo
    base_count = int(run(repo, "git", "rev-list", "--count", "main"))
    controller.build()
    prepare(controller, 1)
    prepare(controller, 2)
    first = commit(worktrees[0], "first.txt", "first\n")
    second_before_rebase = commit(worktrees[1], "second.txt", "second\n")
    controller.ready(1)
    controller.ready(2)
    first_result = controller.absorb(1)
    second_result = controller.absorb(2)
    assert first_result["integrated_head"] == first
    assert second_result["integrated_head"] != second_before_rebase
    assert (repo / "first.txt").read_text() == "first\n"
    assert (repo / "second.txt").read_text() == "second\n"
    assert int(run(repo, "git", "rev-list", "--count", "main")) == base_count + 2
    assert controller.inventory.lease(1, required=False) is None
    assert controller.inventory.lease(2, required=False) is None


def test_stale_reclaim_is_safe_or_quarantines(slot_repo, monkeypatch) -> None:
    controller, _, worktrees = slot_repo
    monkeypatch.setenv("LEAN_SLOT_OWNER_PID", "999999")
    controller.acquire(1, client="codex", base_ref="main")
    controller.reclaim(1)
    assert controller.inventory.lease(1, required=False) is None

    controller.acquire(2, client="codex", base_ref="main")
    protected = worktrees[1] / "uncommitted.txt"
    protected.write_text("keep\n")
    with pytest.raises(SlotError, match="quarantined"):
        controller.reclaim(2)
    assert protected.exists()
    assert controller.inventory.lease(2)["state"] == "QUARANTINED"


def test_session_owned_reclaim_requires_explicit_owner_confirmation(
    slot_repo, monkeypatch
) -> None:
    controller, _, _ = slot_repo
    monkeypatch.delenv("LEAN_SLOT_OWNER_PID")
    monkeypatch.setenv("CODEX_THREAD_ID", "test-thread")
    controller.acquire(1, client="codex", base_ref="main")
    lease = controller.inventory.lease(1)
    assert lease["owner_kind"] == "session"
    assert "test-thread" not in json.dumps(lease)
    with pytest.raises(SlotError, match="confirm-owner-gone"):
        controller.reclaim(1)
    controller.reclaim(1, confirm_owner_gone=True)


def test_released_lease_cannot_dispatch_on_existing_session_in_trusted_local_mode(
    slot_repo,
) -> None:
    controller, _, _ = slot_repo
    controller.build()
    prepare(controller, 1)
    gate = LeaseGate(controller.inventory, 1)
    client, supplied_hash = gate.identify(None, "codex")
    call = json.dumps(
        {
            "jsonrpc": "2.0",
            "id": 1,
            "method": "tools/call",
            "params": {"name": "lean_diagnostic_messages"},
        }
    ).encode()
    gate.authorize(client, supplied_hash, call)
    wrong_client, _ = gate.identify(None, "claude")
    with pytest.raises(SlotError, match="another client"):
        gate.authorize(wrong_client, None, call)
    unidentified, _ = gate.identify(None)
    with pytest.raises(SlotError, match="another client"):
        gate.authorize(unidentified, None, call)
    controller.release(1)
    with pytest.raises(SlotError, match="no active lease"):
        gate.authorize(client, supplied_hash, call)


def test_lean_build_is_denied_even_with_active_lease(slot_repo) -> None:
    controller, _, _ = slot_repo
    controller.build()
    prepare(controller, 1)
    gate = LeaseGate(controller.inventory, 1)
    client, supplied_hash = gate.identify(None, "codex")
    build = json.dumps(
        {
            "jsonrpc": "2.0",
            "id": 1,
            "method": "tools/call",
            "params": {"name": "lean_build"},
        }
    ).encode()
    with pytest.raises(SlotError, match="disabled"):
        gate.authorize(client, supplied_hash, build)


def test_trusted_local_discovery_needs_no_credential(slot_repo) -> None:
    controller, _, _ = slot_repo
    gate = LeaseGate(controller.inventory, 3)
    client, supplied_hash = gate.identify(None)
    listing = json.dumps({"jsonrpc": "2.0", "id": 1, "method": "tools/list"}).encode()
    gate.authorize(client, supplied_hash, listing)


def test_bearer_mode_requires_known_credential(slot_repo) -> None:
    controller, _, _ = slot_repo
    controller.inventory.raw["server"]["client_auth"] = "bearer"
    token = controller.inventory.token("codex")
    gate = LeaseGate(controller.inventory, 3)
    assert gate.identify(f"Bearer {token}", "codex")[0] == "codex"
    with pytest.raises(SlotError, match="does not match"):
        gate.identify(f"Bearer {token}", "claude")
    with pytest.raises(SlotError, match="unknown or expired"):
        gate.identify("Bearer wrong")


def test_generated_trusted_local_config_has_no_bearer_dependency_and_drift_is_fail_closed(
    slot_repo,
) -> None:
    controller, _, _ = slot_repo
    [path] = controller.render_config(scope="repo")
    assert path.stat().st_mode & 0o077 == 0
    original = path.read_text()
    assert "bearer_token_env_var" not in original
    assert str(controller.repo / ".codex" / "agents") in original
    path.write_text(original + "# local edit\n")
    with pytest.raises(SlotError, match="refusing to overwrite"):
        controller.render_config(scope="repo")


def test_trusted_local_mode_rejects_meaningless_token_rotation(slot_repo) -> None:
    controller, _, _ = slot_repo
    with pytest.raises(SlotError, match="only in bearer"):
        controller.render_config(scope="repo", rotate_token=True)


def test_bearer_config_and_token_rotation_are_available_but_fail_closed(
    slot_repo,
) -> None:
    controller, _, _ = slot_repo
    controller.inventory.raw["server"]["client_auth"] = "bearer"
    [path] = controller.render_config(scope="repo")
    assert 'bearer_token_env_var = "LEAN_SLOT_CODEX_TOKEN"' in path.read_text()
    generated_agent = (
        controller.repo / ".codex" / "generated" / "agents" / "worker.toml"
    )
    assert (
        'bearer_token_env_var = "LEAN_SLOT_CODEX_TOKEN"' in generated_agent.read_text()
    )
    controller.acquire(1, client="codex", base_ref="main")
    with pytest.raises(SlotError, match="while slots are leased"):
        controller.render_config(scope="repo", rotate_token=True)


def test_two_scope_render_preflights_before_writing(slot_repo) -> None:
    controller, _, _ = slot_repo
    [repo_config] = controller.render_config(scope="repo")
    stale = repo_config.read_text() + "# stale generated copy\n"
    repo_config.write_text(stale)
    workspace_config = controller.inventory.workspace_root / ".codex" / "config.toml"
    workspace_config.parent.mkdir(exist_ok=True)
    workspace_config.write_text("# operator-owned\n")
    with pytest.raises(SlotError, match="refusing to overwrite"):
        controller.render_config(scope="both", force=True)
    assert repo_config.read_text() == stale
    assert workspace_config.read_text() == "# operator-owned\n"


def test_global_backend_limit_counts_other_repository_roles(slot_repo) -> None:
    controller, _, _ = slot_repo
    process_root = controller.inventory.state_root / "processes"
    signature = process_start_signature(os.getpid())
    assert signature
    for number in (1, 2, 3):
        atomic_json(
            process_root / f"other-wt{number}-backend.json",
            {
                "schema_version": 1,
                "repo_role": "other",
                "slot": number,
                "kind": "backend",
                "pid": os.getpid(),
                "signature": signature,
            },
        )
    supervisor = Supervisor(controller.inventory)
    assert supervisor.global_backend_count() == 3
    with pytest.raises(SlotError, match="global heavy-backend limit"):
        supervisor.start_backend(1)


def test_one_physical_slot_cannot_have_two_repository_backends(slot_repo) -> None:
    controller, _, _ = slot_repo
    signature = process_start_signature(os.getpid())
    assert signature
    atomic_json(
        controller.inventory.state_root / "processes" / "other-wt2-backend.json",
        {
            "schema_version": 1,
            "repo_role": "other",
            "slot": 2,
            "kind": "backend",
            "pid": os.getpid(),
            "signature": signature,
        },
    )
    with pytest.raises(SlotError, match="physical wt2 already has"):
        Supervisor(controller.inventory).start_backend(2)


def test_proxy_runtime_fingerprint_changes_with_client_auth_mode(slot_repo) -> None:
    controller, _, _ = slot_repo
    supervisor = Supervisor(controller.inventory)
    trusted_local = supervisor._runtime_fingerprint("proxy", 1)
    controller.inventory.raw["server"]["client_auth"] = "bearer"
    assert supervisor._runtime_fingerprint("proxy", 1) != trusted_local


def test_downstream_lease_pins_clean_paired_dependency(downstream_repo) -> None:
    controller, public_controller, _, _ = downstream_repo
    epoch = controller.build()
    lease = controller.acquire(2, client="codex", base_ref="main")
    public_sha = run(public_controller.repo, "git", "rev-parse", "main")
    assert lease["public_dependency_sha"] == public_sha
    assert epoch["fingerprint"]["public_dependency_sha"] == public_sha
    controller.prepare(2)
    assert controller.inventory.lease(2)["state"] == "ACTIVE"


def test_downstream_acquire_refuses_dirty_or_unpinned_dependency(
    downstream_repo,
) -> None:
    controller, _, _, _ = downstream_repo
    paired = controller.inventory.paired_inventory()
    assert paired is not None
    protected = paired.worktree(1) / "protected.lean"
    protected.write_text("keep\n")
    with pytest.raises(SlotError, match="paired dependency wt1 is dirty"):
        controller.acquire(1, client="codex", base_ref="main")
    assert protected.exists()
    assert controller.inventory.lease(1, required=False) is None


def test_active_downstream_gate_rechecks_dependency_pin(downstream_repo) -> None:
    controller, _, _, _ = downstream_repo
    controller.build()
    prepare(controller, 3)
    gate = LeaseGate(controller.inventory, 3)
    client, supplied_hash = gate.identify(None, "codex")
    call = json.dumps(
        {
            "jsonrpc": "2.0",
            "id": 1,
            "method": "tools/call",
            "params": {"name": "lean_goal"},
        }
    ).encode()
    gate.authorize(client, supplied_hash, call)
    paired = controller.inventory.paired_inventory()
    assert paired is not None
    (paired.worktree(3) / "changed.lean").write_text("changed\n")
    with pytest.raises(SlotError, match="paired dependency became dirty"):
        gate.authorize(client, supplied_hash, call)


def test_downstream_lakefile_path_must_match_pair_inventory(downstream_repo) -> None:
    controller, _, repo, _ = downstream_repo
    lakefile = repo / "lean" / "lakefile.toml"
    lakefile.write_text(
        lakefile.read_text().replace("../../primary/lean", "../wrong/lean")
    )
    run(repo, "git", "add", "lean/lakefile.toml")
    run(repo, "git", "commit", "-m", "misdirect dependency")
    with pytest.raises(SlotError, match="Lake dependency path mismatch"):
        controller.acquire(2, client="codex", base_ref="main")


def test_foreign_repository_cannot_reclaim_stale_lease(
    downstream_repo, monkeypatch: pytest.MonkeyPatch
) -> None:
    controller, public_controller, _, _ = downstream_repo
    monkeypatch.setenv("LEAN_SLOT_OWNER_PID", "999999")
    controller.acquire(2, client="codex", base_ref="main")
    with pytest.raises(SlotError, match="repository-role mismatch"):
        public_controller.reclaim(2)
    assert controller.inventory.lease(2)["repo_role"] == "downstream"


def test_trusted_local_session_environment_exports_only_shared_state_root(
    slot_repo,
) -> None:
    controller, _, _ = slot_repo
    environment = controller.session_environment(client="codex")
    assert "LEAN_SLOT_CODEX_TOKEN" not in environment
    assert (
        f"export LEAN_SLOT_STATE_DIR={controller.inventory.state_root}" in environment
    )


def test_bearer_session_environment_exports_token(slot_repo) -> None:
    controller, _, _ = slot_repo
    controller.inventory.raw["server"]["client_auth"] = "bearer"
    environment = controller.session_environment(client="codex")
    assert "export LEAN_SLOT_CODEX_TOKEN=" in environment
    assert (
        f"export LEAN_SLOT_STATE_DIR={controller.inventory.state_root}" in environment
    )


def test_backend_pair_handoff_is_ordered_and_rolls_back(
    downstream_repo, monkeypatch: pytest.MonkeyPatch
) -> None:
    controller, public_controller, _, _ = downstream_repo
    target = Supervisor(controller.inventory)
    counterpart = Supervisor(public_controller.inventory)
    running = {"target": False, "counterpart": True}
    events: list[str] = []

    monkeypatch.setattr(
        target,
        "_running",
        lambda kind, number: running["target"] if kind == "backend" else True,
    )
    monkeypatch.setattr(
        counterpart,
        "_running",
        lambda kind, number: running["counterpart"] if kind == "backend" else True,
    )
    monkeypatch.setattr(
        target, "_start_proxy_unlocked", lambda number: events.append("proxy")
    )
    monkeypatch.setattr(target, "_assert_backend_owned_or_stopped", lambda number: None)
    monkeypatch.setattr(
        counterpart, "_assert_backend_owned_or_stopped", lambda number: None
    )
    monkeypatch.setattr(
        target, "assert_healthy", lambda number: events.append("healthy")
    )

    def start_target(number: int) -> None:
        running["target"] = True
        events.append("start-target")

    def stop_target(number: int) -> None:
        running["target"] = False
        events.append("stop-target")

    def start_counterpart(number: int) -> None:
        running["counterpart"] = True
        events.append("start-counterpart")

    def stop_counterpart(number: int) -> None:
        running["counterpart"] = False
        events.append("stop-counterpart")

    monkeypatch.setattr(target, "_start_backend_unlocked", start_target)
    monkeypatch.setattr(target, "_stop_backend_unlocked", stop_target)
    monkeypatch.setattr(counterpart, "_start_backend_unlocked", start_counterpart)
    monkeypatch.setattr(counterpart, "_stop_backend_unlocked", stop_counterpart)

    with target.activating_from(2, counterpart):
        assert not running["target"] and not running["counterpart"]
        events.append("cache-transition")
    assert events == [
        "proxy",
        "stop-counterpart",
        "cache-transition",
        "start-target",
        "healthy",
    ]

    events.clear()
    running.update(target=False, counterpart=True)
    with pytest.raises(RuntimeError, match="copy failed"):
        with target.activating_from(2, counterpart):
            raise RuntimeError("copy failed")
    assert events == ["proxy", "stop-counterpart", "start-counterpart"]
    assert not running["target"] and running["counterpart"]


def test_doctor_json_shape_is_stable(slot_repo) -> None:
    controller, _, _ = slot_repo
    first = controller.doctor()
    second = controller.doctor()
    assert first == second
    assert first["schema_version"] == 1
    assert {item["name"] for item in first["checks"]} >= {
        "wt1.identity",
        "wt1.clean",
        "wt1.integrated",
        "build_epoch",
        "config.repo",
        "heavy_backend_limit",
    }


def test_doctor_fails_closed_for_quarantine_and_unabsorbed_commits(slot_repo) -> None:
    controller, _, worktrees = slot_repo
    protected = worktrees[0] / "protected.lean"
    protected.write_text("keep\n")
    with pytest.raises(SlotError, match="quarantined"):
        controller.acquire(1, client="codex", base_ref="main")
    first = {item["name"]: item for item in controller.doctor()["checks"]}
    assert not first["wt1.lease"]["ok"]
    assert "QUARANTINED" in first["wt1.lease"]["detail"]

    commit(worktrees[1], "unabsorbed.txt", "keep\n")
    second = {item["name"]: item for item in controller.doctor()["checks"]}
    assert not second["wt2.integrated"]["ok"]
    assert "1 unabsorbed commit" in second["wt2.integrated"]["detail"]
