"""Acceptance-focused tests for the ADR-008 shared Lean slot controller."""

from __future__ import annotations

import json
import os
import subprocess
from types import SimpleNamespace
from pathlib import Path

import pytest

from scripts.lean_slots.controller import Controller
from scripts.lean_slots.proxy import LeaseGate
from scripts.lean_slots.state import Inventory, SlotError
from scripts.lean_slots.state import atomic_json, process_start_signature
from scripts.lean_slots.supervisor import Supervisor


def run(cwd: Path, *command: str) -> str:
    return subprocess.run(
        list(command), cwd=cwd, check=True, capture_output=True, text=True
    ).stdout.strip()


@pytest.fixture()
def slot_repo(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> tuple[Controller, Path, list[Path]]:
    repo = tmp_path / "primary"
    repo.mkdir()
    run(repo, "git", "init", "-b", "main")
    run(repo, "git", "config", "user.name", "Slot Test")
    run(repo, "git", "config", "user.email", "slot@example.invalid")
    (repo / "lean").mkdir()
    (repo / "lean" / "lean-toolchain").write_text("leanprover/lean4:v4.test\n")
    (repo / "lean" / "lakefile.toml").write_text("name = 'Test'\n")
    (repo / "lean" / "lake-manifest.json").write_text("{}\n")
    (repo / "README.md").write_text("slot fixture\n")
    (repo / ".gitignore").write_text("lean/.lake/\n")
    run(repo, "git", "add", ".")
    run(repo, "git", "commit", "-m", "initial")
    worktrees = []
    for number in (1, 2, 3):
        worktree = tmp_path / f"wt{number}"
        run(
            repo,
            "git",
            "worktree",
            "add",
            "-b",
            f"worktree-wt{number}",
            str(worktree),
            "main",
        )
        worktrees.append(worktree)
    lake_build = repo / "lean" / ".lake" / "build"
    lake_build.mkdir(parents=True)
    (lake_build / "artifact").write_text("built\n")
    (repo / "config").mkdir()
    inventory = {
        "schema_version": 1,
        "repo_role": "public",
        "repo_root": "..",
        "max_active_slots": 3,
        "lease_timeout_seconds": 0,
        "slots": {
            str(number): {
                "worktree": f"../wt{number}",
                "branch": f"worktree-wt{number}",
                "endpoint_name": f"test_wt{number}",
                "proxy_port": 29000 + number,
                "backend_port": 29100 + number,
            }
            for number in (1, 2, 3)
        },
        "server": {
            "host": "127.0.0.1",
            "command": ["false"],
            "disabled_tools": ["lean_build"],
            "probe_file": "Test.lean",
            "instructions": "no builds",
            "startup_timeout_seconds": 1,
        },
        "build": {
            "cwd": "lean",
            "command": ["/usr/bin/true"],
            "fingerprint_files": [
                "lean/lean-toolchain",
                "lean/lakefile.toml",
                "lean/lake-manifest.json",
            ],
        },
    }
    inventory_path = repo / "config" / "lean-slots.public.json"
    inventory_path.write_text(json.dumps(inventory))
    (repo / ".codex" / "agents").mkdir(parents=True)
    (repo / ".codex" / "hooks").mkdir()
    (repo / ".codex" / "config.template.toml").write_text(
        "# GENERATED by scripts/slotctl.py config render.\n"
        "# source-digest = {{SOURCE_DIGEST}}\n"
        'repo = "{{REPO_ROOT}}"\n'
        'agent_dir = "{{AGENT_CONFIG_DIR}}"\n'
        "{{MCP_CLIENT_AUTH}}\n"
    )
    (repo / ".codex" / "agents" / "worker.toml").write_text(
        "name = 'worker'\nurl = 'http://127.0.0.1:29001/mcp'\n"
    )
    (repo / ".codex" / "hooks" / "pre_tool_use_policy.py").write_text("# policy\n")
    run(repo, "git", "add", "config", ".codex")
    run(repo, "git", "commit", "-m", "add slot infrastructure")
    monkeypatch.setenv("LEAN_SLOT_STATE_DIR", str(tmp_path / "state"))
    monkeypatch.setenv("LEAN_SLOT_SKIP_SUPERVISOR", "1")
    monkeypatch.setenv("LEAN_SLOT_OWNER_PID", str(os.getpid()))
    controller = Controller(Inventory.load(inventory_path))
    return controller, repo, worktrees


@pytest.fixture()
def downstream_repo(
    slot_repo, tmp_path: Path
) -> tuple[Controller, Controller, Path, list[Path]]:
    public_controller, public_repo, public_worktrees = slot_repo
    public_head = run(public_repo, "git", "rev-parse", "main")
    for number, worktree in enumerate(public_worktrees, 1):
        run(worktree, "git", "checkout", "-B", f"worktree-wt{number}", public_head)

    repo = tmp_path / "downstream"
    repo.mkdir()
    run(repo, "git", "init", "-b", "main")
    run(repo, "git", "config", "user.name", "Slot Test")
    run(repo, "git", "config", "user.email", "slot@example.invalid")
    (repo / "lean").mkdir()
    (repo / "lean" / "lean-toolchain").write_text("leanprover/lean4:v4.test\n")
    (repo / "lean" / "lakefile.toml").write_text(
        "name = 'Downstream'\n"
        "[[require]]\n"
        "name = 'Primary'\n"
        "path = '../../primary/lean'\n"
    )
    (repo / "lean" / "lake-manifest.json").write_text("{}\n")
    (repo / ".gitignore").write_text("lean/.lake/\n")
    run(repo, "git", "add", ".")
    run(repo, "git", "commit", "-m", "initial downstream")

    worktrees: list[Path] = []
    for number, public_worktree in enumerate(public_worktrees, 1):
        pair = tmp_path / "pairs" / f"wt{number}"
        pair.mkdir(parents=True)
        (pair / "primary").symlink_to(public_worktree, target_is_directory=True)
        worktree = pair / "downstream"
        run(
            repo,
            "git",
            "worktree",
            "add",
            "-b",
            f"worktree-wt{number}",
            str(worktree),
            "main",
        )
        worktrees.append(worktree)

    lake_build = repo / "lean" / ".lake" / "build"
    lake_build.mkdir(parents=True)
    (lake_build / "artifact").write_text("downstream built\n")
    (repo / "config").mkdir()
    inventory = {
        "schema_version": 1,
        "repo_role": "downstream",
        "repo_root": "..",
        "max_active_slots": 3,
        "lease_timeout_seconds": 0,
        "paired_dependency": {
            "inventory": "../../primary/config/lean-slots.public.json",
            "base_ref": "main",
            "lake_dependency_name": "Primary",
            "path_from_primary_lean": "../../primary/lean",
            "path_from_slot_lean": "../../primary/lean",
        },
        "config": {"manage_workspace": False},
        "slots": {
            str(number): {
                "worktree": f"../pairs/wt{number}/downstream",
                "branch": f"worktree-wt{number}",
                "endpoint_name": f"downstream_wt{number}",
                "proxy_port": 29200 + number,
                "backend_port": 29300 + number,
            }
            for number in (1, 2, 3)
        },
        "server": {
            "host": "127.0.0.1",
            "command": ["false"],
            "disabled_tools": ["lean_build"],
            "probe_file": "Test.lean",
            "instructions": "no builds",
            "startup_timeout_seconds": 1,
            "backend_policy": "leased",
        },
        "build": {
            "cwd": "lean",
            "command": ["/usr/bin/true"],
            "fingerprint_files": [
                "lean/lean-toolchain",
                "lean/lakefile.toml",
                "lean/lake-manifest.json",
            ],
        },
    }
    inventory_path = repo / "config" / "lean-slots.downstream.json"
    inventory_path.write_text(json.dumps(inventory))
    (repo / ".codex" / "agents").mkdir(parents=True)
    (repo / ".codex" / "hooks").mkdir()
    (repo / ".codex" / "config.template.toml").write_text(
        "# GENERATED by scripts/slotctl.py config render.\n"
        "# source-digest = {{SOURCE_DIGEST}}\n"
        'repo = "{{REPO_ROOT}}"\n'
    )
    (repo / ".codex" / "agents" / "worker.toml").write_text("name = 'worker'\n")
    (repo / ".codex" / "hooks" / "pre_tool_use_policy.py").write_text("# policy\n")
    run(repo, "git", "add", "config", ".codex")
    run(repo, "git", "commit", "-m", "add downstream slot infrastructure")
    controller = Controller(Inventory.load(inventory_path))
    return controller, public_controller, repo, worktrees


def prepare(controller: Controller, number: int, *, client: str = "codex") -> None:
    controller.acquire(number, client=client, base_ref="main")
    controller.prepare(number)


def commit(worktree: Path, filename: str, content: str) -> str:
    (worktree / filename).write_text(content)
    run(worktree, "git", "add", filename)
    run(worktree, "git", "commit", "-m", f"add {filename}")
    return run(worktree, "git", "rev-parse", "HEAD")


def test_inventory_is_exactly_three_global_slots(slot_repo) -> None:
    controller, _, _ = slot_repo
    assert set(controller.inventory.raw["slots"]) == {"1", "2", "3"}
    assert controller.inventory.raw["max_active_slots"] == 3
    with pytest.raises(SlotError, match="one of 1, 2, 3"):
        controller.acquire(4, client="codex", base_ref="main")


def test_cross_client_collision_fails_closed(slot_repo) -> None:
    controller, _, _ = slot_repo
    controller.acquire(1, client="codex", base_ref="main")
    with pytest.raises(SlotError, match="already leased by codex"):
        controller.acquire(1, client="claude", base_ref="main")


def test_trusted_local_lease_needs_no_client_token(slot_repo) -> None:
    controller, _, _ = slot_repo
    lease = controller.acquire(1, client="codex", base_ref="main")
    assert lease["client_auth"] == "trusted-local"
    assert "token_hash" not in lease
    assert not controller.inventory.client_token_path("codex").exists()


def test_bearer_lease_retains_client_token_binding(slot_repo) -> None:
    controller, _, _ = slot_repo
    controller.inventory.raw["server"]["client_auth"] = "bearer"
    lease = controller.acquire(1, client="codex", base_ref="main")
    assert lease["client_auth"] == "bearer"
    assert lease["token_hash"]
    assert controller.inventory.client_token_path("codex").exists()


def test_client_auth_mode_cannot_change_under_an_existing_lease(slot_repo) -> None:
    controller, _, _ = slot_repo
    controller.acquire(1, client="codex", base_ref="main")
    controller.inventory.raw["server"]["client_auth"] = "bearer"
    with pytest.raises(SlotError, match="client-auth mode mismatch"):
        controller.heartbeat(1)


def test_trusted_local_mode_rejects_non_loopback_binding(slot_repo) -> None:
    controller, _, _ = slot_repo
    controller.inventory.raw["server"]["host"] = "0.0.0.0"
    with pytest.raises(SlotError, match="requires a loopback"):
        _ = controller.inventory.client_auth_mode


def test_three_distinct_slots_can_be_leased(slot_repo) -> None:
    controller, _, _ = slot_repo
    for number in (1, 2, 3):
        controller.acquire(number, client="codex", base_ref="main")
    assert [item["lease"]["state"] for item in controller.status()["slots"]] == [
        "ACQUIRED",
        "ACQUIRED",
        "ACQUIRED",
    ]


def test_dirty_acquire_quarantines_without_deleting_work(slot_repo) -> None:
    controller, _, worktrees = slot_repo
    protected = worktrees[0] / "protected.lean"
    protected.write_text("theorem keep : True := by trivial\n")
    with pytest.raises(SlotError, match="quarantined"):
        controller.acquire(1, client="codex", base_ref="main")
    assert protected.exists()
    assert controller.inventory.lease(1)["state"] == "QUARANTINED"
    protected.unlink()
    controller.release(1)
    assert controller.inventory.lease(1, required=False) is None


def test_build_epoch_and_atomic_cache_prepare(slot_repo) -> None:
    controller, _, worktrees = slot_repo
    epoch = controller.build()
    prepare(controller, 2)
    lease = controller.inventory.lease(2)
    assert lease["state"] == "ACTIVE"
    assert lease["prepared_epoch"] == epoch["epoch_id"]
    assert (
        worktrees[1] / "lean" / ".lake" / "build" / "artifact"
    ).read_text() == "built\n"


def test_epoch_invalidates_when_dependency_fingerprint_changes(slot_repo) -> None:
    controller, repo, _ = slot_repo
    controller.build()
    (repo / "lean" / "lake-manifest.json").write_text('{"changed": true}\n')
    run(repo, "git", "add", "lean/lake-manifest.json")
    run(repo, "git", "commit", "-m", "change manifest")
    controller.acquire(1, client="codex", base_ref="main")
    with pytest.raises(SlotError, match="no successful-build epoch"):
        controller.prepare(1)


def test_ready_requires_clean_committed_work(slot_repo) -> None:
    controller, _, worktrees = slot_repo
    controller.build()
    prepare(controller, 1)
    (worktrees[0] / "draft.lean").write_text("draft\n")
    with pytest.raises(SlotError, match="quarantined"):
        controller.ready(1)
    assert controller.inventory.lease(1)["state"] == "QUARANTINED"


def test_absorb_refuses_a_head_changed_after_ready(slot_repo) -> None:
    controller, _, worktrees = slot_repo
    controller.build()
    prepare(controller, 1)
    commit(worktrees[0], "reviewed.txt", "reviewed\n")
    controller.ready(1)
    commit(worktrees[0], "late.txt", "late\n")
    with pytest.raises(SlotError, match="HEAD changed after ready"):
        controller.absorb(1)
    assert controller.inventory.lease(1)["state"] == "QUARANTINED"


def test_lake_clone_fallback_removes_partial_copy(
    slot_repo, monkeypatch: pytest.MonkeyPatch
) -> None:
    controller, _, worktrees = slot_repo

    def failed_clone(command, **kwargs):
        destination = Path(command[-1])
        destination.mkdir(parents=True)
        (destination / "partial").write_text("partial\n")
        return SimpleNamespace(returncode=1)

    monkeypatch.setattr("scripts.lean_slots.controller.subprocess.run", failed_clone)
    controller._replace_lake(3)
    destination = worktrees[2] / "lean" / ".lake"
    assert not (destination / "partial").exists()
    assert (destination / "build" / "artifact").read_text() == "built\n"


def test_two_sibling_workers_absorb_by_rebase_and_fast_forward(slot_repo) -> None:
    controller, repo, worktrees = slot_repo
    base_count = int(run(repo, "git", "rev-list", "--count", "main"))
    controller.build()
    prepare(controller, 1)
    prepare(controller, 2)
    first = commit(worktrees[0], "first.txt", "first\n")
    second_before_rebase = commit(worktrees[1], "second.txt", "second\n")
    controller.ready(1)
    controller.ready(2)
    first_result = controller.absorb(1)
    second_result = controller.absorb(2)
    assert first_result["integrated_head"] == first
    assert second_result["integrated_head"] != second_before_rebase
    assert (repo / "first.txt").read_text() == "first\n"
    assert (repo / "second.txt").read_text() == "second\n"
    assert int(run(repo, "git", "rev-list", "--count", "main")) == base_count + 2
    assert controller.inventory.lease(1, required=False) is None
    assert controller.inventory.lease(2, required=False) is None


def test_stale_reclaim_is_safe_or_quarantines(slot_repo, monkeypatch) -> None:
    controller, _, worktrees = slot_repo
    monkeypatch.setenv("LEAN_SLOT_OWNER_PID", "999999")
    controller.acquire(1, client="codex", base_ref="main")
    controller.reclaim(1)
    assert controller.inventory.lease(1, required=False) is None

    controller.acquire(2, client="codex", base_ref="main")
    protected = worktrees[1] / "uncommitted.txt"
    protected.write_text("keep\n")
    with pytest.raises(SlotError, match="quarantined"):
        controller.reclaim(2)
    assert protected.exists()
    assert controller.inventory.lease(2)["state"] == "QUARANTINED"


def test_session_owned_reclaim_requires_explicit_owner_confirmation(
    slot_repo, monkeypatch
) -> None:
    controller, _, _ = slot_repo
    monkeypatch.delenv("LEAN_SLOT_OWNER_PID")
    monkeypatch.setenv("CODEX_THREAD_ID", "test-thread")
    controller.acquire(1, client="codex", base_ref="main")
    lease = controller.inventory.lease(1)
    assert lease["owner_kind"] == "session"
    assert "test-thread" not in json.dumps(lease)
    with pytest.raises(SlotError, match="confirm-owner-gone"):
        controller.reclaim(1)
    controller.reclaim(1, confirm_owner_gone=True)


def test_released_lease_cannot_dispatch_on_existing_session_in_trusted_local_mode(
    slot_repo,
) -> None:
    controller, _, _ = slot_repo
    controller.build()
    prepare(controller, 1)
    gate = LeaseGate(controller.inventory, 1)
    client, supplied_hash = gate.identify(None, "codex")
    call = json.dumps(
        {
            "jsonrpc": "2.0",
            "id": 1,
            "method": "tools/call",
            "params": {"name": "lean_diagnostic_messages"},
        }
    ).encode()
    gate.authorize(client, supplied_hash, call)
    wrong_client, _ = gate.identify(None, "claude")
    with pytest.raises(SlotError, match="another client"):
        gate.authorize(wrong_client, None, call)
    unidentified, _ = gate.identify(None)
    with pytest.raises(SlotError, match="another client"):
        gate.authorize(unidentified, None, call)
    controller.release(1)
    with pytest.raises(SlotError, match="no active lease"):
        gate.authorize(client, supplied_hash, call)


def test_lean_build_is_denied_even_with_active_lease(slot_repo) -> None:
    controller, _, _ = slot_repo
    controller.build()
    prepare(controller, 1)
    gate = LeaseGate(controller.inventory, 1)
    client, supplied_hash = gate.identify(None, "codex")
    build = json.dumps(
        {
            "jsonrpc": "2.0",
            "id": 1,
            "method": "tools/call",
            "params": {"name": "lean_build"},
        }
    ).encode()
    with pytest.raises(SlotError, match="disabled"):
        gate.authorize(client, supplied_hash, build)


def test_trusted_local_discovery_needs_no_credential(slot_repo) -> None:
    controller, _, _ = slot_repo
    gate = LeaseGate(controller.inventory, 3)
    client, supplied_hash = gate.identify(None)
    listing = json.dumps({"jsonrpc": "2.0", "id": 1, "method": "tools/list"}).encode()
    gate.authorize(client, supplied_hash, listing)


def test_bearer_mode_requires_known_credential(slot_repo) -> None:
    controller, _, _ = slot_repo
    controller.inventory.raw["server"]["client_auth"] = "bearer"
    token = controller.inventory.token("codex")
    gate = LeaseGate(controller.inventory, 3)
    assert gate.identify(f"Bearer {token}", "codex")[0] == "codex"
    with pytest.raises(SlotError, match="does not match"):
        gate.identify(f"Bearer {token}", "claude")
    with pytest.raises(SlotError, match="unknown or expired"):
        gate.identify("Bearer wrong")


def test_generated_trusted_local_config_has_no_bearer_dependency_and_drift_is_fail_closed(
    slot_repo,
) -> None:
    controller, _, _ = slot_repo
    [path] = controller.render_config(scope="repo")
    assert path.stat().st_mode & 0o077 == 0
    original = path.read_text()
    assert "bearer_token_env_var" not in original
    assert str(controller.repo / ".codex" / "agents") in original
    path.write_text(original + "# local edit\n")
    with pytest.raises(SlotError, match="refusing to overwrite"):
        controller.render_config(scope="repo")


def test_trusted_local_mode_rejects_meaningless_token_rotation(slot_repo) -> None:
    controller, _, _ = slot_repo
    with pytest.raises(SlotError, match="only in bearer"):
        controller.render_config(scope="repo", rotate_token=True)


def test_bearer_config_and_token_rotation_are_available_but_fail_closed(
    slot_repo,
) -> None:
    controller, _, _ = slot_repo
    controller.inventory.raw["server"]["client_auth"] = "bearer"
    [path] = controller.render_config(scope="repo")
    assert 'bearer_token_env_var = "LEAN_SLOT_CODEX_TOKEN"' in path.read_text()
    generated_agent = (
        controller.repo / ".codex" / "generated" / "agents" / "worker.toml"
    )
    assert (
        'bearer_token_env_var = "LEAN_SLOT_CODEX_TOKEN"' in generated_agent.read_text()
    )
    controller.acquire(1, client="codex", base_ref="main")
    with pytest.raises(SlotError, match="while slots are leased"):
        controller.render_config(scope="repo", rotate_token=True)


def test_two_scope_render_preflights_before_writing(slot_repo) -> None:
    controller, _, _ = slot_repo
    [repo_config] = controller.render_config(scope="repo")
    stale = repo_config.read_text() + "# stale generated copy\n"
    repo_config.write_text(stale)
    workspace_config = controller.inventory.workspace_root / ".codex" / "config.toml"
    workspace_config.parent.mkdir(exist_ok=True)
    workspace_config.write_text("# operator-owned\n")
    with pytest.raises(SlotError, match="refusing to overwrite"):
        controller.render_config(scope="both", force=True)
    assert repo_config.read_text() == stale
    assert workspace_config.read_text() == "# operator-owned\n"


def test_global_backend_limit_counts_other_repository_roles(slot_repo) -> None:
    controller, _, _ = slot_repo
    process_root = controller.inventory.state_root / "processes"
    signature = process_start_signature(os.getpid())
    assert signature
    for number in (1, 2, 3):
        atomic_json(
            process_root / f"other-wt{number}-backend.json",
            {
                "schema_version": 1,
                "repo_role": "other",
                "slot": number,
                "kind": "backend",
                "pid": os.getpid(),
                "signature": signature,
            },
        )
    supervisor = Supervisor(controller.inventory)
    assert supervisor.global_backend_count() == 3
    with pytest.raises(SlotError, match="global heavy-backend limit"):
        supervisor.start_backend(1)


def test_one_physical_slot_cannot_have_two_repository_backends(slot_repo) -> None:
    controller, _, _ = slot_repo
    signature = process_start_signature(os.getpid())
    assert signature
    atomic_json(
        controller.inventory.state_root / "processes" / "other-wt2-backend.json",
        {
            "schema_version": 1,
            "repo_role": "other",
            "slot": 2,
            "kind": "backend",
            "pid": os.getpid(),
            "signature": signature,
        },
    )
    with pytest.raises(SlotError, match="physical wt2 already has"):
        Supervisor(controller.inventory).start_backend(2)


def test_proxy_runtime_fingerprint_changes_with_client_auth_mode(slot_repo) -> None:
    controller, _, _ = slot_repo
    supervisor = Supervisor(controller.inventory)
    trusted_local = supervisor._runtime_fingerprint("proxy", 1)
    controller.inventory.raw["server"]["client_auth"] = "bearer"
    assert supervisor._runtime_fingerprint("proxy", 1) != trusted_local


def test_downstream_lease_pins_clean_paired_dependency(downstream_repo) -> None:
    controller, public_controller, _, _ = downstream_repo
    epoch = controller.build()
    lease = controller.acquire(2, client="codex", base_ref="main")
    public_sha = run(public_controller.repo, "git", "rev-parse", "main")
    assert lease["public_dependency_sha"] == public_sha
    assert epoch["fingerprint"]["public_dependency_sha"] == public_sha
    controller.prepare(2)
    assert controller.inventory.lease(2)["state"] == "ACTIVE"


def test_downstream_acquire_refuses_dirty_or_unpinned_dependency(
    downstream_repo,
) -> None:
    controller, _, _, _ = downstream_repo
    paired = controller.inventory.paired_inventory()
    assert paired is not None
    protected = paired.worktree(1) / "protected.lean"
    protected.write_text("keep\n")
    with pytest.raises(SlotError, match="paired dependency wt1 is dirty"):
        controller.acquire(1, client="codex", base_ref="main")
    assert protected.exists()
    assert controller.inventory.lease(1, required=False) is None


def test_active_downstream_gate_rechecks_dependency_pin(downstream_repo) -> None:
    controller, _, _, _ = downstream_repo
    controller.build()
    prepare(controller, 3)
    gate = LeaseGate(controller.inventory, 3)
    client, supplied_hash = gate.identify(None, "codex")
    call = json.dumps(
        {
            "jsonrpc": "2.0",
            "id": 1,
            "method": "tools/call",
            "params": {"name": "lean_goal"},
        }
    ).encode()
    gate.authorize(client, supplied_hash, call)
    paired = controller.inventory.paired_inventory()
    assert paired is not None
    (paired.worktree(3) / "changed.lean").write_text("changed\n")
    with pytest.raises(SlotError, match="paired dependency became dirty"):
        gate.authorize(client, supplied_hash, call)


def test_downstream_lakefile_path_must_match_pair_inventory(downstream_repo) -> None:
    controller, _, repo, _ = downstream_repo
    lakefile = repo / "lean" / "lakefile.toml"
    lakefile.write_text(
        lakefile.read_text().replace("../../primary/lean", "../wrong/lean")
    )
    run(repo, "git", "add", "lean/lakefile.toml")
    run(repo, "git", "commit", "-m", "misdirect dependency")
    with pytest.raises(SlotError, match="Lake dependency path mismatch"):
        controller.acquire(2, client="codex", base_ref="main")


def test_foreign_repository_cannot_reclaim_stale_lease(
    downstream_repo, monkeypatch: pytest.MonkeyPatch
) -> None:
    controller, public_controller, _, _ = downstream_repo
    monkeypatch.setenv("LEAN_SLOT_OWNER_PID", "999999")
    controller.acquire(2, client="codex", base_ref="main")
    with pytest.raises(SlotError, match="repository-role mismatch"):
        public_controller.reclaim(2)
    assert controller.inventory.lease(2)["repo_role"] == "downstream"


def test_trusted_local_session_environment_exports_only_shared_state_root(
    slot_repo,
) -> None:
    controller, _, _ = slot_repo
    environment = controller.session_environment(client="codex")
    assert "LEAN_SLOT_CODEX_TOKEN" not in environment
    assert (
        f"export LEAN_SLOT_STATE_DIR={controller.inventory.state_root}" in environment
    )


def test_bearer_session_environment_exports_token(slot_repo) -> None:
    controller, _, _ = slot_repo
    controller.inventory.raw["server"]["client_auth"] = "bearer"
    environment = controller.session_environment(client="codex")
    assert "export LEAN_SLOT_CODEX_TOKEN=" in environment
    assert (
        f"export LEAN_SLOT_STATE_DIR={controller.inventory.state_root}" in environment
    )


def test_backend_pair_handoff_is_ordered_and_rolls_back(
    downstream_repo, monkeypatch: pytest.MonkeyPatch
) -> None:
    controller, public_controller, _, _ = downstream_repo
    target = Supervisor(controller.inventory)
    counterpart = Supervisor(public_controller.inventory)
    running = {"target": False, "counterpart": True}
    events: list[str] = []

    monkeypatch.setattr(
        target,
        "_running",
        lambda kind, number: running["target"] if kind == "backend" else True,
    )
    monkeypatch.setattr(
        counterpart,
        "_running",
        lambda kind, number: running["counterpart"] if kind == "backend" else True,
    )
    monkeypatch.setattr(
        target, "_start_proxy_unlocked", lambda number: events.append("proxy")
    )
    monkeypatch.setattr(target, "_assert_backend_owned_or_stopped", lambda number: None)
    monkeypatch.setattr(
        counterpart, "_assert_backend_owned_or_stopped", lambda number: None
    )
    monkeypatch.setattr(
        target, "assert_healthy", lambda number: events.append("healthy")
    )

    def start_target(number: int) -> None:
        running["target"] = True
        events.append("start-target")

    def stop_target(number: int) -> None:
        running["target"] = False
        events.append("stop-target")

    def start_counterpart(number: int) -> None:
        running["counterpart"] = True
        events.append("start-counterpart")

    def stop_counterpart(number: int) -> None:
        running["counterpart"] = False
        events.append("stop-counterpart")

    monkeypatch.setattr(target, "_start_backend_unlocked", start_target)
    monkeypatch.setattr(target, "_stop_backend_unlocked", stop_target)
    monkeypatch.setattr(counterpart, "_start_backend_unlocked", start_counterpart)
    monkeypatch.setattr(counterpart, "_stop_backend_unlocked", stop_counterpart)

    with target.activating_from(2, counterpart):
        assert not running["target"] and not running["counterpart"]
        events.append("cache-transition")
    assert events == [
        "proxy",
        "stop-counterpart",
        "cache-transition",
        "start-target",
        "healthy",
    ]

    events.clear()
    running.update(target=False, counterpart=True)
    with pytest.raises(RuntimeError, match="copy failed"):
        with target.activating_from(2, counterpart):
            raise RuntimeError("copy failed")
    assert events == ["proxy", "stop-counterpart", "start-counterpart"]
    assert not running["target"] and running["counterpart"]


def test_doctor_json_shape_is_stable(slot_repo) -> None:
    controller, _, _ = slot_repo
    first = controller.doctor()
    second = controller.doctor()
    assert first == second
    assert first["schema_version"] == 1
    assert {item["name"] for item in first["checks"]} >= {
        "wt1.identity",
        "wt1.clean",
        "wt1.integrated",
        "build_epoch",
        "config.repo",
        "config.claude",
        "heavy_backend_limit",
    }


def test_doctor_fails_closed_for_quarantine_and_unabsorbed_commits(slot_repo) -> None:
    controller, _, worktrees = slot_repo
    protected = worktrees[0] / "protected.lean"
    protected.write_text("keep\n")
    with pytest.raises(SlotError, match="quarantined"):
        controller.acquire(1, client="codex", base_ref="main")
    first = {item["name"]: item for item in controller.doctor()["checks"]}
    assert not first["wt1.lease"]["ok"]
    assert "QUARANTINED" in first["wt1.lease"]["detail"]

    commit(worktrees[1], "unabsorbed.txt", "keep\n")
    second = {item["name"]: item for item in controller.doctor()["checks"]}
    assert not second["wt2.integrated"]["ok"]
    assert "1 unabsorbed commit" in second["wt2.integrated"]["detail"]


# --- ADR-008 Phase 4: Claude MCP configuration (spec P4-1..P4-3) ---------------------


#: The shape the production artifact actually has: the per-slot stdio servers this block
#: replaces, interleaved with servers owned by other projects that must survive untouched.
def _workspace_mcp(tmp_path: Path) -> Path:
    path = tmp_path / ".mcp.json"
    path.write_text(
        json.dumps(
            {
                "mcpServers": {
                    "lean-lsp": {"command": "uvx", "args": ["--lean-project-path", "/x/lean"]},
                    "lean-lsp-other": {"command": "uvx", "args": ["--lean-project-path", "/y"]},
                    "lean-lsp-wt1": {"command": "uvx", "args": ["--repl"]},
                    "lean-lsp-wt2": {"command": "uvx", "args": ["--repl"]},
                    "lean-lsp-wt3": {"command": "uvx", "args": ["--repl"]},
                    "other-client": {"command": "other"},
                }
            },
            indent=2,
        )
        + "\n"
    )
    return path


def test_claude_render_swaps_stdio_slots_for_lease_gated_http(slot_repo, tmp_path) -> None:
    controller, _, _ = slot_repo
    target = _workspace_mcp(tmp_path)
    controller.render_claude_config()
    servers = json.loads(target.read_text())["mcpServers"]
    assert not [key for key in servers if key.startswith("lean-lsp-wt")]
    for number in (1, 2, 3):
        entry = servers[f"test_wt{number}"]
        assert entry["type"] == "http"
        # The query parameter is what `proxy.py` matches against the lease's own client
        # field; without it trusted-local dispatch fails closed.
        assert entry["url"] == f"http://127.0.0.1:{29000 + number}/mcp?client=claude"


def test_claude_render_leaves_other_projects_servers_and_their_order_alone(
    slot_repo, tmp_path
) -> None:
    controller, _, _ = slot_repo
    target = _workspace_mcp(tmp_path)
    before = json.loads(target.read_text())["mcpServers"]
    unrelated = {k: v for k, v in before.items() if not k.startswith("lean-lsp-wt")}
    controller.render_claude_config()
    after = json.loads(target.read_text())["mcpServers"]
    assert {k: v for k, v in after.items() if k in unrelated} == unrelated
    assert [k for k in after if k in unrelated] == list(unrelated)


def test_claude_render_ports_come_from_the_inventory_not_a_second_list(
    slot_repo, tmp_path
) -> None:
    controller, repo, _ = slot_repo
    target = _workspace_mcp(tmp_path)
    path = repo / "config" / "lean-slots.public.json"
    inventory = json.loads(path.read_text())
    inventory["slots"]["2"]["proxy_port"] = 29777
    path.write_text(json.dumps(inventory))
    moved = Controller(Inventory.load(path))
    moved.render_claude_config()
    servers = json.loads(target.read_text())["mcpServers"]
    assert servers["test_wt2"]["url"].startswith("http://127.0.0.1:29777/")


def test_a_drifted_port_in_the_live_file_is_reported_not_overwritten(
    slot_repo, tmp_path
) -> None:
    controller, _, _ = slot_repo
    target = _workspace_mcp(tmp_path)
    controller.render_claude_config()
    document = json.loads(target.read_text())
    document["mcpServers"]["test_wt2"]["url"] = "http://127.0.0.1:29999/mcp?client=claude"
    target.write_text(json.dumps(document, indent=2))
    check = {item["name"]: item for item in controller.doctor()["checks"]}["config.claude"]
    assert not check["ok"]
    assert check["detail"].startswith("drifted")
    assert "test_wt2" in check["detail"]
    # Reporting, never writing: doctor left the operator's file exactly as it found it.
    assert json.loads(target.read_text()) == document


def test_a_missing_slot_entry_is_partial_not_current(slot_repo, tmp_path) -> None:
    controller, _, _ = slot_repo
    target = _workspace_mcp(tmp_path)
    controller.render_claude_config()
    document = json.loads(target.read_text())
    del document["mcpServers"]["test_wt3"]
    target.write_text(json.dumps(document, indent=2))
    check = {item["name"]: item for item in controller.doctor()["checks"]}["config.claude"]
    assert not check["ok"]
    assert check["detail"].startswith("partial")
    assert "test_wt3" in check["detail"]


def test_a_legacy_stdio_slot_left_beside_the_http_block_is_drift(slot_repo, tmp_path) -> None:
    """Coexistence is the process multiplication this change exists to remove."""
    controller, _, _ = slot_repo
    target = _workspace_mcp(tmp_path)
    controller.render_claude_config()
    document = json.loads(target.read_text())
    document["mcpServers"]["lean-lsp-wt1"] = {"command": "uvx", "args": ["--repl"]}
    target.write_text(json.dumps(document, indent=2))
    check = {item["name"]: item for item in controller.doctor()["checks"]}["config.claude"]
    assert not check["ok"]
    assert "lean-lsp-wt1" in check["detail"]


def test_pre_activation_and_rolled_back_states_are_healthy_not_broken(
    slot_repo, tmp_path
) -> None:
    controller, _, _ = slot_repo
    target = _workspace_mcp(tmp_path)
    pre = json.loads(target.read_text())
    before = {item["name"]: item for item in controller.doctor()["checks"]}["config.claude"]
    assert before["ok"] and before["detail"].startswith("not activated")

    controller.render_claude_config()
    controller.render_claude_config(rollback=True)
    assert json.loads(target.read_text())["mcpServers"] == pre["mcpServers"]
    after = {item["name"]: item for item in controller.doctor()["checks"]}["config.claude"]
    assert after["ok"] and after["detail"].startswith("not activated")


def test_a_second_render_cannot_destroy_the_pre_activation_snapshot(
    slot_repo, tmp_path
) -> None:
    """Otherwise the snapshot records an already-activated block and rollback is a no-op."""
    controller, _, _ = slot_repo
    target = _workspace_mcp(tmp_path)
    pre = json.loads(target.read_text())["mcpServers"]
    controller.render_claude_config()
    controller.render_claude_config()
    from scripts.lean_slots import claude_config

    snapshot = json.loads(claude_config.rollback_path(controller.inventory).read_text())
    assert snapshot == pre


def test_render_refuses_an_absolute_claude_config_path(slot_repo, tmp_path) -> None:
    controller, repo, _ = slot_repo
    path = repo / "config" / "lean-slots.public.json"
    inventory = json.loads(path.read_text())
    inventory["config"] = {"claude_mcp": str(tmp_path / ".mcp.json")}
    path.write_text(json.dumps(inventory))
    with pytest.raises(SlotError, match="workspace-relative"):
        Controller(Inventory.load(path)).render_claude_config()


def test_the_live_workspace_mcp_config_classifies_without_raising() -> None:
    """Production-seeded: run the classifier over the operator's real file, if present."""
    from scripts.lean_slots import claude_config

    inventory = Inventory.load()
    live = Controller(inventory).claude_mcp_path()
    if not live.exists():
        pytest.skip("no workspace Claude MCP configuration on this host")
    state, _ = claude_config.block_state(json.loads(live.read_text()), inventory)
    assert state in {"current", "not activated", "partial", "drifted"}


def test_a_session_owned_lease_survives_separate_cli_invocations(
    slot_repo, monkeypatch
) -> None:
    """A lease outlives the shell that acquired it, or every second command fails closed."""
    controller, repo, _ = slot_repo
    monkeypatch.delenv("LEAN_SLOT_OWNER_PID", raising=False)
    monkeypatch.setenv("CLAUDE_CODE_SESSION_ID", "session-abc")
    lease = controller.acquire(1, client="claude", base_ref="main")
    assert lease["owner_kind"] == "session"
    # A distinct invocation: same session, different parent process.
    reloaded = Controller(Inventory.load(repo / "config" / "lean-slots.public.json"))
    assert reloaded.heartbeat(1)["slot"] == 1


def test_a_different_session_cannot_drive_another_sessions_lease(
    slot_repo, monkeypatch
) -> None:
    controller, repo, _ = slot_repo
    monkeypatch.delenv("LEAN_SLOT_OWNER_PID", raising=False)
    monkeypatch.setenv("CLAUDE_CODE_SESSION_ID", "session-abc")
    controller.acquire(1, client="claude", base_ref="main")
    monkeypatch.setenv("CLAUDE_CODE_SESSION_ID", "session-xyz")
    other = Controller(Inventory.load(repo / "config" / "lean-slots.public.json"))
    with pytest.raises(SlotError, match="owner"):
        other.heartbeat(1)


def test_the_neutral_owner_variable_outranks_the_client_specific_ones(
    slot_repo, monkeypatch
) -> None:
    controller, _, _ = slot_repo
    monkeypatch.delenv("LEAN_SLOT_OWNER_PID", raising=False)
    monkeypatch.setenv("CODEX_THREAD_ID", "codex-thread")
    monkeypatch.setenv("CLAUDE_CODE_SESSION_ID", "claude-session")
    monkeypatch.setenv("LEAN_SLOT_OWNER_SESSION", "explicit-owner")
    import hashlib

    lease = controller.acquire(1, client="claude", base_ref="main")
    assert (
        lease["owner_session_hash"]
        == hashlib.sha256(b"explicit-owner").hexdigest()
    )


def test_activate_rollback_reactivate_preserves_the_original_snapshot(
    slot_repo, tmp_path
) -> None:
    """The rollback path is ADR-008 item 7 — retaining legacy stdio as recoverable state.

    render->render is guarded elsewhere; this is the sequence that actually breaks write-once,
    because after a rollback the file legitimately holds the legacy block again and a naive
    snapshot-on-render would rewrite it, silently making the NEXT rollback restore an
    already-activated block instead.
    """
    controller, _, _ = slot_repo
    target = _workspace_mcp(tmp_path)
    pre = json.loads(target.read_text())["mcpServers"]

    controller.render_claude_config()
    controller.render_claude_config(rollback=True)
    assert json.loads(target.read_text())["mcpServers"] == pre
    controller.render_claude_config()

    servers = json.loads(target.read_text())["mcpServers"]
    assert "test_wt1" in servers and "lean-lsp-wt1" not in servers

    from scripts.lean_slots import claude_config

    snapshot = json.loads(claude_config.rollback_path(controller.inventory).read_text())
    assert snapshot == pre, (
        "the snapshot no longer holds the pre-activation block, so a further rollback "
        "would restore an activated config and the legacy path would be unrecoverable")


# --- ADR-008 Phase 4: declared host kernel limits (portable across machines) -----------


def _with_limits(repo: Path, entries: list) -> Controller:
    path = repo / "config" / "lean-slots.public.json"
    inventory = json.loads(path.read_text())
    inventory["host_limits"] = entries
    path.write_text(json.dumps(inventory))
    return Controller(Inventory.load(path))


def test_a_knob_below_its_declared_minimum_fails_with_a_runnable_remedy(
    slot_repo, monkeypatch
) -> None:
    from scripts.lean_slots import host_limits

    controller, repo, _ = slot_repo
    monkeypatch.delenv(host_limits.SKIP_ENV, raising=False)
    monkeypatch.setattr(platform := __import__("platform"), "system", lambda: "TestOS")
    monkeypatch.setattr(host_limits, "read_sysctl", lambda name: 1000)
    moved = _with_limits(repo, [{"platform": "TestOS", "sysctl": "test.knob",
                                 "minimum": 5000, "remedy": "sudo sysctl -w test.knob=5000"}])
    name, ok, detail = host_limits.evaluate(moved.inventory)[0]
    assert name == "host_limit.test.knob" and not ok
    assert "1000" in detail and "5000" in detail
    assert "sudo sysctl -w test.knob=5000" in detail
    assert "lost on reboot" in detail


def test_a_remedy_that_drifted_from_the_minimum_is_replaced_not_printed(
    slot_repo, monkeypatch
) -> None:
    """A remedy naming a stale value would send the operator to run a command that
    leaves the check red — the exact defect the live output exposed."""
    from scripts.lean_slots import host_limits

    controller, repo, _ = slot_repo
    monkeypatch.delenv(host_limits.SKIP_ENV, raising=False)
    monkeypatch.setattr(__import__("platform"), "system", lambda: "TestOS")
    monkeypatch.setattr(host_limits, "read_sysctl", lambda name: 1000)
    moved = _with_limits(repo, [{"platform": "TestOS", "sysctl": "test.knob",
                                 "minimum": 9999,
                                 "remedy": "sudo sysctl -w test.knob=5000"}])
    _, ok, detail = host_limits.evaluate(moved.inventory)[0]
    assert not ok
    assert "test.knob=9999" in detail
    assert "test.knob=5000" not in detail


def test_a_platform_with_no_declared_limit_passes(slot_repo, monkeypatch) -> None:
    """A public repo must not fail a clone on a machine whose kernel has no such knob."""
    from scripts.lean_slots import host_limits

    controller, repo, _ = slot_repo
    monkeypatch.delenv(host_limits.SKIP_ENV, raising=False)
    monkeypatch.setattr(__import__("platform"), "system", lambda: "Linux")
    moved = _with_limits(repo, [{"platform": "Darwin", "sysctl": "kern.maxvnodes",
                                 "minimum": 786432}])
    name, ok, detail = host_limits.evaluate(moved.inventory)[0]
    assert name == "host_limits" and ok
    assert "Linux" in detail


def test_a_knob_this_kernel_does_not_expose_passes(slot_repo, monkeypatch) -> None:
    """Absent is not misconfigured."""
    from scripts.lean_slots import host_limits

    controller, repo, _ = slot_repo
    monkeypatch.delenv(host_limits.SKIP_ENV, raising=False)
    monkeypatch.setattr(__import__("platform"), "system", lambda: "TestOS")
    monkeypatch.setattr(host_limits, "read_sysctl", lambda name: None)
    moved = _with_limits(repo, [{"platform": "TestOS", "sysctl": "test.knob",
                                 "minimum": 5000}])
    _, ok, detail = host_limits.evaluate(moved.inventory)[0]
    assert ok and "not exposed" in detail


def test_the_skip_variable_opts_a_machine_out_without_a_repo_diff(
    slot_repo, monkeypatch
) -> None:
    from scripts.lean_slots import host_limits

    controller, repo, _ = slot_repo
    monkeypatch.setenv(host_limits.SKIP_ENV, "1")
    monkeypatch.setattr(__import__("platform"), "system", lambda: "TestOS")
    monkeypatch.setattr(host_limits, "read_sysctl", lambda name: 1)
    moved = _with_limits(repo, [{"platform": "TestOS", "sysctl": "test.knob",
                                 "minimum": 5000}])
    name, ok, detail = host_limits.evaluate(moved.inventory)[0]
    assert name == "host_limits" and ok and host_limits.SKIP_ENV in detail


def test_doctor_surfaces_the_host_limit_check(slot_repo) -> None:
    controller, _, _ = slot_repo
    names = {c["name"] for c in controller.doctor()["checks"]}
    assert any(n == "host_limits" or n.startswith("host_limit.") for n in names)


def test_the_shipped_public_inventory_declares_a_darwin_vnode_floor() -> None:
    """The committed default must actually carry the limit this ADR added."""
    from scripts.lean_slots import host_limits

    inventory = Inventory.load()
    entries = [e for e in (inventory.raw.get("host_limits") or [])
               if e.get("platform") == "Darwin"]
    assert entries, "public inventory lost its Darwin host limit"
    entry = entries[0]
    assert entry["sysctl"] == "kern.maxvnodes"
    assert int(entry["minimum"]) >= 786432
    assert str(entry["minimum"]) in entry.get("remedy", "")


# --- ADR-008 Phase 4: leased backends are reclaimed on every lease-exit path ------------


def _leased(repo: Path) -> Controller:
    path = repo / "config" / "lean-slots.public.json"
    inventory = json.loads(path.read_text())
    inventory["server"]["backend_policy"] = "leased"
    path.write_text(json.dumps(inventory))
    # `build()` refuses a dirty primary checkout, so the policy switch must be committed
    # like any other inventory change.
    run(repo, "git", "add", "config/lean-slots.public.json")
    run(repo, "git", "commit", "-m", "switch to leased backends")
    return Controller(Inventory.load(path))


def test_a_leased_slot_expects_no_backend_once_released(slot_repo) -> None:
    controller, repo, _ = slot_repo
    leased = _leased(repo)
    leased.build()
    assert not leased.inventory.backend_expected(1)
    prepare(leased, 1, client="claude")
    assert leased.inventory.backend_expected(1)
    leased.release(1)
    assert not leased.inventory.backend_expected(1)


def test_release_reconciles_the_backend_after_the_lease_is_gone(
    slot_repo, monkeypatch
) -> None:
    """Ordering is the whole point: `backend_expected` reads the lease, so a reconcile
    that ran before the unlink would still see the slot leased and keep ~4.4 GB warm."""
    controller, repo, _ = slot_repo
    leased = _leased(repo)
    leased.build()
    prepare(leased, 1, client="claude")
    seen: list[tuple[str, bool]] = []
    monkeypatch.delenv("LEAN_SLOT_SKIP_SUPERVISOR", raising=False)

    class FakeSupervisor:
        def __init__(self, inventory):
            self.inventory = inventory

        def stop_backend(self, number):
            seen.append(("stop", leased.inventory.lease_path(number).exists()))

    import scripts.lean_slots.supervisor as sup

    monkeypatch.setattr(sup, "Supervisor", FakeSupervisor)
    leased.release(1)
    assert seen == [("stop", False)], (
        "the backend must be stopped exactly once, AFTER the lease file is removed")


def test_a_default_policy_slot_keeps_its_backend_on_release(slot_repo, monkeypatch) -> None:
    """`default` must remain a no-op — this change reclaims memory, it does not
    quietly change the other policy's behaviour."""
    controller, repo, _ = slot_repo
    controller.build()
    prepare(controller, 1, client="claude")
    calls: list[int] = []
    monkeypatch.delenv("LEAN_SLOT_SKIP_SUPERVISOR", raising=False)

    class FakeSupervisor:
        def __init__(self, inventory):
            pass

        def stop_backend(self, number):
            calls.append(number)

    import scripts.lean_slots.supervisor as sup

    monkeypatch.setattr(sup, "Supervisor", FakeSupervisor)
    controller.release(1)
    assert calls == []


def test_a_supervisor_failure_never_fails_an_already_successful_release(
    slot_repo, monkeypatch, capsys
) -> None:
    controller, repo, _ = slot_repo
    leased = _leased(repo)
    leased.build()
    prepare(leased, 1, client="claude")
    monkeypatch.delenv("LEAN_SLOT_SKIP_SUPERVISOR", raising=False)

    class ExplodingSupervisor:
        def __init__(self, inventory):
            pass

        def stop_backend(self, number):
            raise SlotError("supervisor is wedged")

    import scripts.lean_slots.supervisor as sup

    monkeypatch.setattr(sup, "Supervisor", ExplodingSupervisor)
    leased.release(1)  # must not raise
    assert not leased.inventory.lease_path(1).exists()
    assert "could not be stopped" in capsys.readouterr().err


def test_the_shipped_public_inventory_reclaims_idle_backends() -> None:
    inventory = Inventory.load()
    assert inventory.raw["server"].get("backend_policy") == "leased"


# --- ADR-008: a backendless slot must still complete the MCP handshake ------------------


def test_initialize_is_answered_when_the_slot_has_no_backend() -> None:
    """Connect-time handshake must not fail for a DISPATCH-time resource.

    Regression: `leased` backends made every unleased endpoint answer 503 to `initialize`.
    codex-cli 0.145.0 (rmcp) treats that as a fatal transport error and the whole session
    dies with no answer, `required = false` notwithstanding.
    """
    from scripts.lean_slots.proxy import offline_handshake

    reply = offline_handshake([{
        "jsonrpc": "2.0", "id": 7, "method": "initialize",
        "params": {"protocolVersion": "2025-06-18"}}])
    assert reply is not None
    assert reply["id"] == 7
    assert reply["result"]["protocolVersion"] == "2025-06-18"
    assert "no active lease" in reply["result"]["instructions"]


def test_a_backendless_slot_advertises_no_tools() -> None:
    """An empty tool list is what keeps the offline handshake from weakening the gate."""
    from scripts.lean_slots.proxy import offline_handshake

    reply = offline_handshake([{"jsonrpc": "2.0", "id": 1, "method": "tools/list"}])
    assert reply["result"]["tools"] == []


def test_the_offline_reply_never_covers_tool_dispatch() -> None:
    """`tools/call` must fall through to the 503/lease-gate path, never be answered here."""
    from scripts.lean_slots.proxy import offline_handshake

    for method in ("tools/call", "resources/read", "prompts/get"):
        assert offline_handshake([{"jsonrpc": "2.0", "id": 1, "method": method}]) is None


def test_notifications_are_recognised_so_they_take_202_not_503() -> None:
    from scripts.lean_slots.proxy import is_notification_only

    assert is_notification_only([{"jsonrpc": "2.0", "method": "notifications/initialized"}])
    assert not is_notification_only([{"jsonrpc": "2.0", "id": 1, "method": "initialize"}])
    assert not is_notification_only([])


def test_a_lease_is_disk_state_so_it_survives_an_endpoint_restart(slot_repo) -> None:
    """Gate test 3: the proxy holds no lease state, so a restart preserves rather than
    reacquires. Pinned because moving lease state into the proxy would silently turn a
    transparent reconnect into a lost lease."""
    controller, _, _ = slot_repo
    controller.build()
    prepare(controller, 1, client="claude")
    before = controller.inventory.lease(1)
    # A restart replaces processes; it must not touch the lease record at all.
    reloaded = Controller(Inventory.load(controller.inventory.source))
    after = reloaded.inventory.lease(1)
    assert after == before, "restarting the endpoints must not alter the lease"
    assert after["state"] == "ACTIVE"
    # Owner identity is what makes it a *preserved* lease rather than a reacquired one.
    owner_key = (
        "owner_session_hash" if after.get("owner_kind") == "session" else "owner_pid"
    )
    assert after[owner_key] == before[owner_key]


def test_the_backend_command_pins_the_slot_worktree_as_project_root(slot_repo) -> None:
    """`--lean-project-path` must name THIS slot's lean dir, never the primary checkout.

    A same-content comparison cannot catch a wrong root: `prepare` resets the slot to the
    base, so slot and primary hold identical files and both resolve every read.
    """
    controller, repo, worktrees = slot_repo
    command = Supervisor(controller.inventory).backend_command(1)
    assert "--lean-project-path" in command
    root = Path(command[command.index("--lean-project-path") + 1]).resolve()
    assert root == (worktrees[0] / "lean").resolve()
    assert root != (repo / "lean").resolve()


def test_quarantining_does_not_reset_the_clock_reclaim_reads(slot_repo) -> None:
    """A failed reclaim must not make the next reclaim fail too.

    `heartbeat_at` means "the owner is alive" and `reclaim` gates on it. When the
    CONTROLLER writes a quarantine, refreshing it would reset the staleness clock, so a
    genuinely stale lease could never be reclaimed by retry — each attempt resets what the
    next one reads. Observed on a three-week-old lease: one failed reclaim rewrote
    `heartbeat_at` to now, and the retry was refused for staleness instead of the real cause.
    """
    controller, _, _ = slot_repo
    lease = controller.acquire(1, client="claude", base_ref="main")
    _ = lease["heartbeat_at"]
    lease["heartbeat_at"] = "2026-07-23T19:32:03Z"          # a genuinely stale owner
    controller.inventory.save_lease(1, lease, touch_heartbeat=False)

    stale = controller.inventory.lease(1)
    assert stale["heartbeat_at"] == "2026-07-23T19:32:03Z"

    controller._quarantine(1, stale, "simulated audit failure")
    after = controller.inventory.lease(1)
    assert after["state"] == "QUARANTINED"
    assert after["heartbeat_at"] == "2026-07-23T19:32:03Z", (
        "quarantining refreshed the heartbeat, so retrying reclaim can never succeed")
    # The quarantine still records ITS own time — suppressing the heartbeat must not
    # suppress the audit trail. The audit stamp advances while the liveness stamp does not.
    assert after["quarantined_at"] > after["heartbeat_at"]


def test_an_owner_heartbeat_still_refreshes(slot_repo) -> None:
    """The fix must not disable the real heartbeat — that would let live leases expire."""
    controller, _, _ = slot_repo
    lease = controller.acquire(1, client="claude", base_ref="main")
    lease["heartbeat_at"] = "2026-07-23T19:32:03Z"
    controller.inventory.save_lease(1, lease, touch_heartbeat=False)
    refreshed = controller.heartbeat(1)
    assert refreshed["heartbeat_at"] != "2026-07-23T19:32:03Z"


# --- Absorption is containment in the INTEGRATION ref, not in a recorded SHA ------------


def test_a_slot_whose_base_branch_was_deleted_is_still_freeable(
    slot_repo, monkeypatch
) -> None:
    """The wt2 trap, 2026-08-14: lease a feature branch, merge it, delete it.

    Every controller verb was closed and the only exit was deleting runtime state by hand —
    which S-C tells operators not to do. Ordinary hygiene must not create an unrecoverable
    state.
    """
    controller, repo, worktrees = slot_repo
    run(repo, "git", "branch", "feature/tmp-base", "main")
    controller.build()
    lease = controller.acquire(1, client="claude", base_ref="feature/tmp-base")
    assert lease["base_ref"] == "feature/tmp-base"
    # The slot's work lands on main the way `absorb` would, then the branch is deleted.
    run(repo, "git", "branch", "-D", "feature/tmp-base")

    worktree = worktrees[0]
    absorbed, why = controller._is_absorbed(worktree, controller.inventory.lease(1))
    assert absorbed, f"a slot contained in main must be freeable; got: {why}"
    assert "integration ref" in why
    controller.release(1)
    assert controller.inventory.lease(1, required=False) is None


def test_real_unabsorbed_work_still_blocks(slot_repo) -> None:
    """The audit must stay fail-closed — this is what stops work being lost."""
    controller, repo, worktrees = slot_repo
    controller.build()
    prepare(controller, 1, client="claude")
    commit(worktrees[0], "unmerged.txt", "work nobody has merged\n")
    absorbed, why = controller._is_absorbed(
        worktrees[0], controller.inventory.lease(1)
    )
    assert not absorbed
    assert "merge or rescue" in why
    with pytest.raises(SlotError, match="quarantined"):
        controller.release(1)


def test_an_unresolvable_ref_is_not_evidence_of_absorption(slot_repo) -> None:
    """Fail-closed: if NOTHING resolves, the answer is 'not safe', never 'sure, go ahead'."""
    controller, repo, worktrees = slot_repo
    controller.build()
    prepare(controller, 1, client="claude")
    commit(worktrees[0], "unmerged.txt", "work nobody has merged\n")
    lease = controller.inventory.lease(1)
    lease["base_ref"] = "refs/heads/does-not-exist"
    absorbed, _ = controller._is_absorbed(worktrees[0], lease)
    assert not absorbed


def test_the_integration_ref_is_configurable(slot_repo) -> None:
    controller, repo, _ = slot_repo
    path = repo / "config" / "lean-slots.public.json"
    inventory = json.loads(path.read_text())
    inventory["integration_ref"] = "trunk"
    path.write_text(json.dumps(inventory))
    run(repo, "git", "branch", "trunk", "main")
    moved = Controller(Inventory.load(path))
    assert moved.inventory.raw["integration_ref"] == "trunk"
    _, why = moved._is_absorbed(
        moved.inventory.worktree(1),
        {"base_ref": "does-not-exist"},
    )
    assert "trunk" in why
