"""ADR-018 acceptance tests for the distinct Chat Lean-slot client."""

from __future__ import annotations

import json
import os
from pathlib import Path
import subprocess

import pytest

from scripts.lean_slots.cli import parser as slotctl_parser
from scripts.lean_slots.controller import Controller
from scripts.lean_slots.proxy import LeaseGate
from scripts.lean_slots.state import Inventory, SlotError


def _run(cwd: Path, *command: str) -> str:
    return subprocess.run(
        list(command), cwd=cwd, check=True, capture_output=True, text=True
    ).stdout.strip()


@pytest.fixture()
def adr018_repo(tmp_path: Path, monkeypatch: pytest.MonkeyPatch):
    repo = tmp_path / "primary"
    repo.mkdir()
    _run(repo, "git", "init", "-b", "main")
    _run(repo, "git", "config", "user.name", "ADR018 Test")
    _run(repo, "git", "config", "user.email", "adr018@example.invalid")
    (repo / "lean").mkdir()
    (repo / "lean" / "lean-toolchain").write_text("leanprover/lean4:v4.test\n")
    (repo / "lean" / "lakefile.toml").write_text("name = 'Test'\n")
    (repo / "lean" / "lake-manifest.json").write_text("{}\n")
    (repo / ".gitignore").write_text("lean/.lake/\n")
    _run(repo, "git", "add", ".")
    _run(repo, "git", "commit", "-m", "initial")

    worktrees: list[Path] = []
    for number in (1, 2, 3):
        worktree = tmp_path / f"wt{number}"
        _run(
            repo,
            "git",
            "worktree",
            "add",
            "-b",
            f"worktree-wt{number}",
            str(worktree),
            "main",
        )
        worktrees.append(worktree)

    lake_build = repo / "lean" / ".lake" / "build"
    lake_build.mkdir(parents=True)
    (lake_build / "artifact").write_text("built\n")

    (repo / "config").mkdir()
    inventory = {
        "schema_version": 1,
        "repo_role": "public",
        "repo_root": "..",
        "max_active_slots": 3,
        "lease_timeout_seconds": 900,
        "slots": {
            str(number): {
                "worktree": f"../wt{number}",
                "branch": f"worktree-wt{number}",
                "endpoint_name": f"test_wt{number}",
                "proxy_port": 31000 + number,
                "backend_port": 31100 + number,
            }
            for number in (1, 2, 3)
        },
        "server": {
            "host": "127.0.0.1",
            "client_auth": "trusted-local",
            "allowed_clients": ["codex", "claude", "chat"],
            "backend_policy": "leased",
            "command": ["false"],
            "disabled_tools": ["lean_build"],
            "probe_file": "Test.lean",
            "instructions": "no builds",
            "startup_timeout_seconds": 1,
        },
        "build": {
            "cwd": "lean",
            "command": ["/usr/bin/true"],
            "fingerprint_files": [
                "lean/lean-toolchain",
                "lean/lakefile.toml",
                "lean/lake-manifest.json",
            ],
        },
    }
    inventory_path = repo / "config" / "lean-slots.public.json"
    inventory_path.write_text(json.dumps(inventory))

    (repo / ".codex" / "agents").mkdir(parents=True)
    (repo / ".codex" / "hooks").mkdir()
    (repo / ".codex" / "config.template.toml").write_text(
        "# GENERATED by scripts/slotctl.py config render.\n"
        "# source-digest = {{SOURCE_DIGEST}}\n"
        'repo = "{{REPO_ROOT}}"\n'
        'agent_dir = "{{AGENT_CONFIG_DIR}}"\n'
        "{{MCP_CLIENT_AUTH}}\n"
    )
    (repo / ".codex" / "agents" / "worker.toml").write_text("name = 'worker'\n")
    (repo / ".codex" / "hooks" / "pre_tool_use_policy.py").write_text("# policy\n")
    _run(repo, "git", "add", "config", ".codex")
    _run(repo, "git", "commit", "-m", "add slot infrastructure")

    monkeypatch.setenv("LEAN_SLOT_STATE_DIR", str(tmp_path / "state"))
    monkeypatch.setenv("LEAN_SLOT_SKIP_SUPERVISOR", "1")
    monkeypatch.setenv("LEAN_SLOT_OWNER_PID", str(os.getpid()))
    controller = Controller(Inventory.load(inventory_path))
    return controller, repo, worktrees, inventory_path


def _write_inventory(path: Path, value: dict) -> Inventory:
    path.write_text(json.dumps(value))
    return Inventory.load(path)


def test_shipped_public_inventory_explicitly_admits_chat() -> None:
    inventory = Inventory.load()
    assert inventory.allowed_clients == frozenset({"codex", "claude", "chat"})


def test_schema1_missing_roster_is_exact_legacy_pair(adr018_repo) -> None:
    _, _, _, path = adr018_repo
    value = json.loads(path.read_text())
    del value["server"]["allowed_clients"]
    legacy = _write_inventory(path, value)
    assert legacy.allowed_clients == frozenset({"codex", "claude"})
    with pytest.raises(SlotError, match="not admitted"):
        legacy.require_allowed_client("chat")


@pytest.mark.parametrize(
    "roster,pattern",
    [
        ([], "non-empty"),
        (["codex", "codex"], "duplicates"),
        (["codex", "bad/client"], "invalid client name"),
        (["codex", 7], "entries must be strings"),
    ],
)
def test_inventory_rejects_invalid_client_rosters(adr018_repo, roster, pattern) -> None:
    _, _, _, path = adr018_repo
    value = json.loads(path.read_text())
    value["server"]["allowed_clients"] = roster
    path.write_text(json.dumps(value))
    with pytest.raises(SlotError, match=pattern):
        Inventory.load(path)


def test_programmatic_acquire_rejects_unadmitted_client_before_lease(adr018_repo) -> None:
    controller, _, _, _ = adr018_repo
    controller.inventory.raw["server"]["allowed_clients"] = ["codex", "claude"]
    with pytest.raises(SlotError, match="not admitted"):
        controller.acquire(1, client="chat", base_ref="main")
    assert controller.inventory.lease(1, required=False) is None


def test_session_environment_rejects_before_bearer_token_creation(adr018_repo) -> None:
    controller, _, _, _ = adr018_repo
    controller.inventory.raw["server"]["client_auth"] = "bearer"
    controller.inventory.raw["server"]["allowed_clients"] = ["codex", "claude"]
    token_path = controller.inventory.client_token_path("chat")
    with pytest.raises(SlotError, match="not admitted"):
        controller.session_environment(client="chat")
    assert not token_path.exists()


def test_trusted_local_proxy_identity_is_inventory_owned(adr018_repo) -> None:
    controller, _, _, _ = adr018_repo
    gate = LeaseGate(controller.inventory, 1)
    assert gate.identify(None, "chat") == ("chat", None)
    with pytest.raises(SlotError, match="not admitted"):
        gate.identify(None, "other")


def test_bearer_token_does_not_admit_removed_client(adr018_repo) -> None:
    controller, _, _, _ = adr018_repo
    controller.inventory.raw["server"]["client_auth"] = "bearer"
    token = controller.inventory.token("chat")
    gate = LeaseGate(controller.inventory, 1)
    assert gate.identify(f"Bearer {token}", "chat")[0] == "chat"
    controller.inventory.raw["server"]["allowed_clients"] = ["codex", "claude"]
    with pytest.raises(SlotError, match="not admitted"):
        gate.identify(f"Bearer {token}", "chat")


def test_removal_preflight_reports_live_client_without_mutating_lease(adr018_repo) -> None:
    controller, _, _, _ = adr018_repo
    controller.acquire(1, client="chat", base_ref="main")
    lease_path = controller.inventory.lease_path(1)
    before = lease_path.read_bytes()
    result = controller.removal_preflight(client="chat")
    assert not result["ok"]
    assert result["mismatches"] == [
        {"slot": 1, "client": "chat", "state": "ACQUIRED", "repo_role": "public"}
    ]
    assert lease_path.read_bytes() == before
    controller.release(1)
    assert controller.removal_preflight(client="chat")["ok"]


def test_doctor_reports_current_roster_mismatch_without_mutating_lease(adr018_repo) -> None:
    controller, _, _, _ = adr018_repo
    controller.acquire(1, client="chat", base_ref="main")
    lease_path = controller.inventory.lease_path(1)
    before = lease_path.read_bytes()
    controller.inventory.raw["server"]["allowed_clients"] = ["codex", "claude"]
    checks = {item["name"]: item for item in controller.doctor()["checks"]}
    assert not checks["wt1.lease"]["ok"]
    assert "absent from current admission roster" in checks["wt1.lease"]["detail"]
    assert lease_path.read_bytes() == before


def test_bearer_revoke_is_quiescent_idempotent_and_prevents_token_reuse(adr018_repo) -> None:
    controller, _, _, _ = adr018_repo
    controller.inventory.raw["server"]["client_auth"] = "bearer"
    old = controller.inventory.token("chat")
    controller.acquire(1, client="chat", base_ref="main")
    with pytest.raises(SlotError, match="live lease"):
        controller.revoke_client_token(client="chat")
    assert controller.inventory.client_token_path("chat").exists()
    controller.release(1)
    assert controller.revoke_client_token(client="chat") == {
        "client": "chat",
        "revoked": True,
    }
    assert controller.revoke_client_token(client="chat") == {
        "client": "chat",
        "revoked": False,
    }
    fresh = controller.inventory.token("chat")
    assert fresh != old


def test_trusted_local_revoke_token_is_refused(adr018_repo) -> None:
    controller, _, _, _ = adr018_repo
    with pytest.raises(SlotError, match="only in bearer"):
        controller.revoke_client_token(client="chat")


def test_cli_admission_arguments_accept_chat_but_renderer_does_not() -> None:
    parser = slotctl_parser()
    acquire = parser.parse_args(
        ["acquire", "--slot", "1", "--client", "chat", "--base-ref", "main"]
    )
    assert acquire.client == "chat"
    environment = parser.parse_args(["session", "env", "--client", "chat"])
    assert environment.client == "chat"
    preflight = parser.parse_args(["session", "removal-preflight", "--client", "chat"])
    assert preflight.client == "chat"
    revoke = parser.parse_args(["session", "revoke-token", "--client", "chat"])
    assert revoke.client == "chat"
    with pytest.raises(SystemExit):
        parser.parse_args(["config", "render", "--client", "chat"])


def test_legacy_private_style_inventory_never_inherits_public_chat_admission(
    adr018_repo, tmp_path: Path
) -> None:
    controller, _, _, _ = adr018_repo
    private_path = tmp_path / "private.json"
    raw = json.loads(controller.inventory.source.read_text())
    raw["repo_role"] = "private"
    raw["server"].pop("allowed_clients", None)
    # Loading the standalone schema-1 overlay is enough to pin the compatibility
    # interpretation: the missing field cannot inherit the public explicit roster.
    private_path.write_text(json.dumps(raw))
    private = Inventory.load(private_path)
    assert private.allowed_clients == frozenset({"codex", "claude"})
    assert "chat" not in private.allowed_clients
