"""Acceptance-focused tests for the ADR-008 shared Lean slot controller."""
from __future__ import annotations

import json
import os
import subprocess
from pathlib import Path

import pytest

from scripts.lean_slots.controller import Controller
from scripts.lean_slots.proxy import LeaseGate
from scripts.lean_slots.state import Inventory, SlotError


def run(cwd: Path, *command: str) -> str:
    return subprocess.run(
        list(command), cwd=cwd, check=True, capture_output=True, text=True
    ).stdout.strip()


@pytest.fixture()
def slot_repo(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> tuple[Controller, Path, list[Path]]:
    repo = tmp_path / "primary"
    repo.mkdir()
    run(repo, "git", "init", "-b", "main")
    run(repo, "git", "config", "user.name", "Slot Test")
    run(repo, "git", "config", "user.email", "slot@example.invalid")
    (repo / "lean").mkdir()
    (repo / "lean" / "lean-toolchain").write_text("leanprover/lean4:v4.test\n")
    (repo / "lean" / "lakefile.toml").write_text("name = 'Test'\n")
    (repo / "lean" / "lake-manifest.json").write_text("{}\n")
    (repo / "README.md").write_text("slot fixture\n")
    (repo / ".gitignore").write_text("lean/.lake/\n")
    run(repo, "git", "add", ".")
    run(repo, "git", "commit", "-m", "initial")
    worktrees = []
    for number in (1, 2, 3):
        worktree = tmp_path / f"wt{number}"
        run(
            repo,
            "git",
            "worktree",
            "add",
            "-b",
            f"worktree-wt{number}",
            str(worktree),
            "main",
        )
        worktrees.append(worktree)
    lake_build = repo / "lean" / ".lake" / "build"
    lake_build.mkdir(parents=True)
    (lake_build / "artifact").write_text("built\n")
    (repo / "config").mkdir()
    inventory = {
        "schema_version": 1,
        "repo_role": "public",
        "repo_root": "..",
        "max_active_slots": 3,
        "lease_timeout_seconds": 0,
        "slots": {
            str(number): {
                "worktree": f"../wt{number}",
                "branch": f"worktree-wt{number}",
                "endpoint_name": f"test_wt{number}",
                "proxy_port": 29000 + number,
                "backend_port": 29100 + number,
            }
            for number in (1, 2, 3)
        },
        "server": {
            "host": "127.0.0.1",
            "command": ["false"],
            "disabled_tools": ["lean_build"],
            "instructions": "no builds",
            "startup_timeout_seconds": 1,
        },
        "build": {
            "cwd": "lean",
            "command": ["/usr/bin/true"],
            "fingerprint_files": [
                "lean/lean-toolchain",
                "lean/lakefile.toml",
                "lean/lake-manifest.json",
            ],
        },
    }
    inventory_path = repo / "config" / "lean-slots.public.json"
    inventory_path.write_text(json.dumps(inventory))
    (repo / ".codex" / "agents").mkdir(parents=True)
    (repo / ".codex" / "hooks").mkdir()
    (repo / ".codex" / "config.template.toml").write_text(
        "# GENERATED by scripts/slotctl.py config render.\n"
        "# source-digest = {{SOURCE_DIGEST}}\n"
        'repo = "{{REPO_ROOT}}"\n'
        'bearer_token_env_var = "LEAN_SLOT_CODEX_TOKEN"\n'
    )
    (repo / ".codex" / "agents" / "worker.toml").write_text("name = 'worker'\n")
    (repo / ".codex" / "hooks" / "pre_tool_use_policy.py").write_text("# policy\n")
    run(repo, "git", "add", "config", ".codex")
    run(repo, "git", "commit", "-m", "add slot infrastructure")
    monkeypatch.setenv("LEAN_SLOT_STATE_DIR", str(tmp_path / "state"))
    monkeypatch.setenv("LEAN_SLOT_SKIP_SUPERVISOR", "1")
    monkeypatch.setenv("LEAN_SLOT_OWNER_PID", str(os.getpid()))
    controller = Controller(Inventory.load(inventory_path))
    return controller, repo, worktrees


def prepare(controller: Controller, number: int, *, client: str = "codex") -> None:
    controller.acquire(number, client=client, base_ref="main")
    controller.prepare(number)


def commit(worktree: Path, filename: str, content: str) -> str:
    (worktree / filename).write_text(content)
    run(worktree, "git", "add", filename)
    run(worktree, "git", "commit", "-m", f"add {filename}")
    return run(worktree, "git", "rev-parse", "HEAD")


def test_inventory_is_exactly_three_global_slots(slot_repo) -> None:
    controller, _, _ = slot_repo
    assert set(controller.inventory.raw["slots"]) == {"1", "2", "3"}
    assert controller.inventory.raw["max_active_slots"] == 3
    with pytest.raises(SlotError, match="one of 1, 2, 3"):
        controller.acquire(4, client="codex", base_ref="main")


def test_cross_client_collision_fails_closed(slot_repo) -> None:
    controller, _, _ = slot_repo
    controller.acquire(1, client="codex", base_ref="main")
    with pytest.raises(SlotError, match="already leased by codex"):
        controller.acquire(1, client="claude", base_ref="main")


def test_three_distinct_slots_can_be_leased(slot_repo) -> None:
    controller, _, _ = slot_repo
    for number in (1, 2, 3):
        controller.acquire(number, client="codex", base_ref="main")
    assert [item["lease"]["state"] for item in controller.status()["slots"]] == [
        "ACQUIRED",
        "ACQUIRED",
        "ACQUIRED",
    ]


def test_dirty_acquire_quarantines_without_deleting_work(slot_repo) -> None:
    controller, _, worktrees = slot_repo
    protected = worktrees[0] / "protected.lean"
    protected.write_text("theorem keep : True := by trivial\n")
    with pytest.raises(SlotError, match="quarantined"):
        controller.acquire(1, client="codex", base_ref="main")
    assert protected.exists()
    assert controller.inventory.lease(1)["state"] == "QUARANTINED"
    protected.unlink()
    controller.release(1)
    assert controller.inventory.lease(1, required=False) is None


def test_build_epoch_and_atomic_cache_prepare(slot_repo) -> None:
    controller, _, worktrees = slot_repo
    epoch = controller.build()
    prepare(controller, 2)
    lease = controller.inventory.lease(2)
    assert lease["state"] == "ACTIVE"
    assert lease["prepared_epoch"] == epoch["epoch_id"]
    assert (worktrees[1] / "lean" / ".lake" / "build" / "artifact").read_text() == "built\n"


def test_epoch_invalidates_when_dependency_fingerprint_changes(slot_repo) -> None:
    controller, repo, _ = slot_repo
    controller.build()
    (repo / "lean" / "lake-manifest.json").write_text('{"changed": true}\n')
    run(repo, "git", "add", "lean/lake-manifest.json")
    run(repo, "git", "commit", "-m", "change manifest")
    controller.acquire(1, client="codex", base_ref="main")
    with pytest.raises(SlotError, match="no successful-build epoch"):
        controller.prepare(1)


def test_ready_requires_clean_committed_work(slot_repo) -> None:
    controller, _, worktrees = slot_repo
    controller.build()
    prepare(controller, 1)
    (worktrees[0] / "draft.lean").write_text("draft\n")
    with pytest.raises(SlotError, match="quarantined"):
        controller.ready(1)
    assert controller.inventory.lease(1)["state"] == "QUARANTINED"


def test_two_sibling_workers_absorb_by_rebase_and_fast_forward(slot_repo) -> None:
    controller, repo, worktrees = slot_repo
    base_count = int(run(repo, "git", "rev-list", "--count", "main"))
    controller.build()
    prepare(controller, 1)
    prepare(controller, 2)
    first = commit(worktrees[0], "first.txt", "first\n")
    second_before_rebase = commit(worktrees[1], "second.txt", "second\n")
    controller.ready(1)
    controller.ready(2)
    first_result = controller.absorb(1)
    second_result = controller.absorb(2)
    assert first_result["integrated_head"] == first
    assert second_result["integrated_head"] != second_before_rebase
    assert (repo / "first.txt").read_text() == "first\n"
    assert (repo / "second.txt").read_text() == "second\n"
    assert int(run(repo, "git", "rev-list", "--count", "main")) == base_count + 2
    assert controller.inventory.lease(1, required=False) is None
    assert controller.inventory.lease(2, required=False) is None


def test_stale_reclaim_is_safe_or_quarantines(slot_repo, monkeypatch) -> None:
    controller, _, worktrees = slot_repo
    monkeypatch.setenv("LEAN_SLOT_OWNER_PID", "999999")
    controller.acquire(1, client="codex", base_ref="main")
    controller.reclaim(1)
    assert controller.inventory.lease(1, required=False) is None

    controller.acquire(2, client="codex", base_ref="main")
    protected = worktrees[1] / "uncommitted.txt"
    protected.write_text("keep\n")
    with pytest.raises(SlotError, match="quarantined"):
        controller.reclaim(2)
    assert protected.exists()
    assert controller.inventory.lease(2)["state"] == "QUARANTINED"


def test_session_owned_reclaim_requires_explicit_owner_confirmation(
    slot_repo, monkeypatch
) -> None:
    controller, _, _ = slot_repo
    monkeypatch.delenv("LEAN_SLOT_OWNER_PID")
    monkeypatch.setenv("CODEX_THREAD_ID", "test-thread")
    controller.acquire(1, client="codex", base_ref="main")
    lease = controller.inventory.lease(1)
    assert lease["owner_kind"] == "session"
    assert "test-thread" not in json.dumps(lease)
    with pytest.raises(SlotError, match="confirm-owner-gone"):
        controller.reclaim(1)
    controller.reclaim(1, confirm_owner_gone=True)


def test_released_token_cannot_dispatch_on_existing_session(slot_repo) -> None:
    controller, _, _ = slot_repo
    controller.build()
    prepare(controller, 1)
    token = controller.inventory.token("codex")
    gate = LeaseGate(controller.inventory, 1)
    client, supplied_hash = gate.identify(f"Bearer {token}")
    call = json.dumps(
        {"jsonrpc": "2.0", "id": 1, "method": "tools/call", "params": {"name": "lean_diagnostic_messages"}}
    ).encode()
    gate.authorize(client, supplied_hash, call)
    controller.release(1)
    with pytest.raises(SlotError, match="no active lease"):
        gate.authorize(client, supplied_hash, call)


def test_lean_build_is_denied_even_with_active_lease(slot_repo) -> None:
    controller, _, _ = slot_repo
    controller.build()
    prepare(controller, 1)
    token = controller.inventory.token("codex")
    gate = LeaseGate(controller.inventory, 1)
    client, supplied_hash = gate.identify(f"Bearer {token}")
    build = json.dumps(
        {"jsonrpc": "2.0", "id": 1, "method": "tools/call", "params": {"name": "lean_build"}}
    ).encode()
    with pytest.raises(SlotError, match="disabled"):
        gate.authorize(client, supplied_hash, build)


def test_discovery_allowed_without_lease_but_unknown_token_denied(slot_repo) -> None:
    controller, _, _ = slot_repo
    token = controller.inventory.token("codex")
    gate = LeaseGate(controller.inventory, 3)
    client, supplied_hash = gate.identify(f"Bearer {token}")
    listing = json.dumps({"jsonrpc": "2.0", "id": 1, "method": "tools/list"}).encode()
    gate.authorize(client, supplied_hash, listing)
    with pytest.raises(SlotError, match="unknown or expired"):
        gate.identify("Bearer wrong")


def test_generated_config_drift_and_token_rotation_are_fail_closed(slot_repo) -> None:
    controller, _, _ = slot_repo
    [path] = controller.render_config(scope="repo")
    assert path.stat().st_mode & 0o077 == 0
    original = path.read_text()
    path.write_text(original + "# local edit\n")
    with pytest.raises(SlotError, match="refusing to overwrite"):
        controller.render_config(scope="repo")
    controller.acquire(1, client="codex", base_ref="main")
    with pytest.raises(SlotError, match="while slots are leased"):
        controller.render_config(scope="repo", rotate_token=True)


def test_doctor_json_shape_is_stable(slot_repo) -> None:
    controller, _, _ = slot_repo
    first = controller.doctor()
    second = controller.doctor()
    assert first == second
    assert first["schema_version"] == 1
    assert {item["name"] for item in first["checks"]} >= {
        "wt1.identity",
        "wt1.clean",
        "build_epoch",
        "config.repo",
        "heavy_backend_limit",
    }
