/-
# Phase 5q.E Wave 4 — The anomaly-phase character ℤ₁₆ → μ₁₆

The explicit *finite map* of the "16 convergence" (see `docs/SIXTEEN_CONVERGENCE_STATUS.md`):
the **anomaly phase** `e^{2πiν/16} ∈ μ₁₆`, the concrete 16th-root-of-unity realization of the
ℤ₁₆ that the Kitaev central-charge facet (`KitaevSixteenFold.lean`) and the Dai–Freed/Rokhlin
facets share. This module advances the *enumeration → cited-connection → explicit-finite-maps*
gradient to its endpoint for the buildable facets, with the genuinely-new headline being the
**central-charge → phase relation** (the Vafa form at the label level).

## What is genuine here
  * `anomalyPhase_eq_central_charge_phase` (headline, NEW): the anomaly phase equals
    `e^{2πi·c₋(ν)/8}` for the Kitaev central charge `c₋(ν) = ν/2` — the explicit map from the
    central charge to the 16th-root-of-unity anomaly phase. Falsifiable (a `/8` vs `/16` slip
    breaks it). Backed by a real call to `Kitaev16.kitaevCentralCharge`.
  * `anomalyPhase_faithful`: the 16 anomaly phases are distinct (kernel `= 16ℤ`) — the
    roots-of-unity realization of the Wave-1 central-charge faithfulness (`μ₁₆` codomain).
  * `anomalyPhase_add`: `ν ↦ e^{2πiν/16}` is an additive→multiplicative homomorphism (so the
    16 phases form the cyclic group `μ₁₆`, generated by `ζ₁₆ = anomalyPhase 1`).
  * `sm_anomalyPhase_trivial`: the SM (16 Weyl/gen) sits at the identity phase `1`.

## What is NOT proved (honesty — load-bearing)

The **deep** Gauss-sum statement `p₊ = D · e^{2πi c₋/8}` (Vafa; `p₊ = Σ dᵢ²θᵢ`,
`|p₊| = D = √(global dim)`), which would tie this character to an *actual modular category*,
is NOT proved here. The repo *has* the Ising Gauss sum `p₊ = 2ζ₁₆`
(`WRTComputation.ising_gauss_sum_is_2zeta`) — so the Ising MTC realizes the **ν=1** phase
(`c₋ = 1/2`, `anomalyPhase 1 = ζ₁₆`) — but that theorem is proved by `native_decide` over the
cyclotomic ring `QCyc16`, carrying the `Lean.ofReduceBool` axiom. Importing it would break this
module's kernel purity, so the concrete-MTC link is **purity-blocked** (Phase 5q.E roadmap
§"Walls": a kernel-pure `QCyc16` Gauss-sum computation would unlock it). And, as everywhere in
this facet, a shared ℤ₁₆ **constrains, it does not derive**; the bordism identification of the
facets' ℤ₁₆s (Smith homomorphism) remains Mathlib-absent. The 3-generation headline is
independent.

## References
  - Vafa, Phys. Lett. B 206, 421 (1988) — Gauss-sum / central-charge phase.
  - `KitaevSixteenFold.lean` (the central-charge facet), `WRTComputation.lean` (Ising `p₊`).
  - `docs/SIXTEEN_CONVERGENCE_STATUS.md`, `docs/roadmaps/Phase5qE_SixteenConvergence_Roadmap.md`.
-/

import Mathlib
import SKEFTHawking.KitaevSixteenFold

open Complex

namespace SKEFTHawking.AnomalyPhase

open SKEFTHawking

/-- The anomaly phase of the ν-th phase: `e^{2πiν/16}`, the concrete 16th-root-of-unity
realization of the shared ℤ₁₆ (it lands in `μ₁₆` by `anomalyPhase_pow_sixteen`). -/
noncomputable def anomalyPhase (ν : ℤ) : ℂ := Complex.exp (2 * (Real.pi : ℂ) * Complex.I * ν / 16)

/-- **The values are genuinely 16th roots of unity**: `anomalyPhase ν ^ 16 = 1`. This makes the
`μ₁₆` framing load-bearing (the codomain `ℂ` restricts to `μ₁₆` on the image). Together with
`anomalyPhase_add` and `anomalyPhase_faithful` (16 distinct values), the image is exactly the
cyclic group `μ₁₆` generated by `ζ₁₆ = anomalyPhase 1`. -/
theorem anomalyPhase_pow_sixteen (ν : ℤ) : anomalyPhase ν ^ 16 = 1 := by
  unfold anomalyPhase
  rw [← Complex.exp_nat_mul]
  rw [show (16 : ℕ) * (2 * (Real.pi : ℂ) * Complex.I * ν / 16)
      = (ν : ℂ) * (2 * (Real.pi : ℂ) * Complex.I) from by push_cast; ring]
  exact Complex.exp_int_mul_two_pi_mul_I ν

/-- **Headline (the central-charge → phase relation, Vafa form at label level).** The anomaly
phase equals `e^{2πi·c₋(ν)/8}`, where `c₋(ν) = ν/2` is the Kitaev central charge
(`KitaevSixteenFold`). This is the explicit map from the central charge to the anomaly phase;
the `/8` (not `/16`) is the genuine content — it is falsified by any wrong central-charge slope. -/
theorem anomalyPhase_eq_central_charge_phase (ν : ℤ) :
    anomalyPhase ν =
      Complex.exp (2 * (Real.pi : ℂ) * Complex.I * ((Kitaev16.kitaevCentralCharge ν : ℚ) : ℂ) / 8) := by
  unfold anomalyPhase Kitaev16.kitaevCentralCharge
  congr 1
  push_cast
  ring

/-- `ν ↦ e^{2πiν/16}` is an additive→multiplicative homomorphism, so the 16 anomaly phases form
the cyclic group `μ₁₆` generated by `ζ₁₆ = anomalyPhase 1`. -/
theorem anomalyPhase_add (ν μ : ℤ) : anomalyPhase (ν + μ) = anomalyPhase ν * anomalyPhase μ := by
  unfold anomalyPhase; rw [← Complex.exp_add]; congr 1; push_cast; ring

/-- **Faithfulness (roots-of-unity realization).** `anomalyPhase ν = anomalyPhase μ ↔ 16 ∣ (ν−μ)`:
the 16 anomaly phases are genuinely distinct (kernel `= 16ℤ`). This is the `μ₁₆`-codomain form of
the Wave-1 central-charge faithfulness. -/
theorem anomalyPhase_faithful (ν μ : ℤ) :
    anomalyPhase ν = anomalyPhase μ ↔ (16 : ℤ) ∣ (ν - μ) := by
  unfold anomalyPhase
  rw [Complex.exp_eq_exp_iff_exists_int]
  constructor
  · rintro ⟨n, hn⟩
    refine ⟨n, ?_⟩
    have h : (ν : ℂ) - μ = 16 * n := by
      field_simp at hn
      linear_combination hn
    exact_mod_cast h
  · rintro ⟨n, hn⟩
    refine ⟨n, ?_⟩
    have : (ν : ℂ) = μ + 16 * n := by exact_mod_cast (by linarith : (ν : ℤ) = μ + 16 * n)
    rw [this]; ring

/-- The Standard Model (16 Weyl fermions per generation) sits at the identity anomaly phase `1`:
`anomalyPhase 16 = 1` — the trivial element of `μ₁₆`, consistent with anomaly-freedom. -/
theorem sm_anomalyPhase_trivial : anomalyPhase 16 = 1 := by
  unfold anomalyPhase
  rw [show (2 * (Real.pi : ℂ) * Complex.I * (16 : ℤ) / 16) = 2 * (Real.pi : ℂ) * Complex.I from by
    norm_num]
  rw [show (2 * (Real.pi : ℂ) * Complex.I) = ((1 : ℤ) : ℂ) * (2 * (Real.pi : ℂ) * Complex.I) from by
    norm_num]
  exact Complex.exp_int_mul_two_pi_mul_I 1

/-! ## Module summary

The anomaly-phase character `μ₁₆` (the explicit finite map of the convergence):
  - `anomalyPhase_eq_central_charge_phase` — anomaly phase `= e^{2πi·c₋/8}` (NEW headline).
  - `anomalyPhase_pow_sixteen` — the values are genuine 16th roots of unity (`^16 = 1`).
  - `anomalyPhase_add` + `anomalyPhase_faithful` — `ℤ₁₆ → μ₁₆` is a faithful character.
  - `sm_anomalyPhase_trivial` — SM at the identity phase.

Walls (documented): the deep Gauss-sum `p₊ = D·e^{2πic₋/8}` link to a concrete MTC is
native_decide-purity-blocked (Ising `p₊=2ζ₁₆` would give the ν=1 realization); the bordism
identification (Smith homomorphism) is Mathlib-absent. Kernel-pure; no axiom/sorry/native_decide.
-/

end SKEFTHawking.AnomalyPhase
