/-
# Phase 5q.H (E2) — what a `[FK]`-at-general-`σ` statement layer can and cannot be: the
invariant-triple forcing theorem, and the correct (INTENSIONAL) admissibility criterion

`CharSurfaceFKVacuity` proved that the CharSurface wire's `[FK]` hypothesis `GMrelation σ 0 C.Q` is
*interderivable with its own conclusion* `16 ∣ σ` under the wire's other leaves, and read that
biconditional as circularity. This module asks the obvious next question — **what shape of layer
would NOT be a biconditional?** — and answers it, kernel-purely. The answer changes the design rule:

## §1 The forcing theorem: extensional non-circularity is UNACHIEVABLE

`triple_layer_forcing`: let `P` be *any* predicate on the invariant triple `(σ, F·F, 2β)` which is
(i) a **consequence** of Guillou–Marin (`defect T = 0 → P T`) and (ii) **sufficient** for Rokhlin on
the spin locus. Then `P (σ, 0, 0) ↔ 16 ∣ σ`, for every `σ`. No exceptions, no clever shape.

The reason is structural and unavoidable: at a spin ambient the characteristic surface degenerates
(`F·F = 0`, `β = 0`), so the GM congruence *is* `16 ∣ σ`; hence anything sandwiched between "implied
by GM" and "implies Rokhlin" is squeezed onto exactly that Prop. **Therefore "the hypothesis is
biconditional with the conclusion at spin" is NOT evidence of a bad layer** — it is a property of
every faithful `[FK]` layer, including the true theorem of Guillou and Marin. Using extensional
non-equivalence as the admissibility test would condemn the real theorem, and would send a worker
hunting for a layer that provably does not exist.

## §2 The correct criterion is INTENSIONAL — and the triple level fails it

What actually went wrong with the CharSurface wire is not the biconditional but *what its hypothesis
is a predicate on*: `GMrelation σ 0 C.Q` with `F·F = 0` and `β(C.Q) = 0` forced is a predicate on
`σ`'s residue class and nothing else, so discharging it requires already knowing `σ mod 16`. A
genuine reduction needs a hypothesis decided by data that does **not** determine `σ mod 16` — i.e.
by geometry, discharged by geometric theorems.

`spin_triple_mem_closure_iff_sixteen_dvd` shows the natural next candidate — the
**bordism-by-generators** route, "the characteristic pair's class lies in the subgroup generated by
the verified generators `(ℂP², ℂP¹)` and `(ℝP⁴, ℝP²)`" — **fails this criterion at the triple
level**: membership of `(σ, 0, 0)` in that subgroup is *decided by `σ` alone*, and is again exactly
`16 ∣ σ`. So a bordism route only becomes a reduction once it is typed over MANIFOLDS, with a
characteristic-pair bordism group mapping **non-surjectively** onto triples. That non-surjectivity
is the whole geometric content; the group theory contributes none of it.

## §3 Where the missing data actually lives

Combining §1–§2 with `GMPinTorsorCeiling`: the escape must be finer than the triple, and the only
finer datum in play is the pin⁻ structure on the characteristic surface — which carries exactly
`ℤ/4` (`doubleBrown_stdShift3_injective` + `reduce16to4_doubleBrown_shift`), i.e. exactly the `4→16`
gap, while its torsor-invariant shadow is already subsumed by the lattice's van der Blij `8 ∣ σ`
(`torsor_free_shadow_implied_by_van_der_blij`). So the residual content of the keystone is precisely
the blueprint's `[G2]`/`[Q1]`: **construct `q_F` from the surface's smooth normal data.**

Kernel-pure (`{propext, Classical.choice, Quot.sound}`); no `sorry`/`native_decide`/`maxHeartbeats`/axiom.
-/
import Mathlib
import SKEFTHawking.GMPinTorsorCeiling

namespace SKEFTHawking.GMTripleLayer

open SKEFTHawking.Brown SKEFTHawking.Brown.Z4Quadratic SKEFTHawking.GuillouMarin
open SKEFTHawking.GMTorsor

variable {ι : Type*} [Fintype ι] [DecidableEq ι]

/-- The **invariant triple** of a characteristic pair `(X, F)`: the ambient signature `σ`, the
self-intersection `F·F`, and the Guillou–Marin residue `2·β(q_F) ∈ ℤ/16`. This is exactly the data
the GM congruence constrains — and exactly the data a `PinCharSurface`-plus-signature substrate
records. -/
abbrev GMTriple : Type := ℤ × ℤ × ZMod 16

/-- The ambient signature. -/
def sigma (T : GMTriple) : ℤ := T.1

/-- The characteristic surface's self-intersection `F·F`. -/
def selfInt (T : GMTriple) : ℤ := T.2.1

/-- The Guillou–Marin residue `2·β`. -/
def residue (T : GMTriple) : ZMod 16 := T.2.2

/-- The GM defect `(σ − F·F) − 2β`; the congruence is its vanishing. -/
def defect (T : GMTriple) : ZMod 16 := ((sigma T - selfInt T : ℤ) : ZMod 16) - residue T

/-- The **spin locus**: the characteristic surface is null (`F·F = 0`) with vanishing Brown
invariant — the shape every in-tree GM producer and the whole CharSurface wire lands in. -/
def IsSpin (T : GMTriple) : Prop := selfInt T = 0 ∧ residue T = 0

/-- The invariant triple of a genuinely enhanced characteristic pair. -/
noncomputable def tripleOf (σ F : ℤ) (Q : Z4Quadratic ι) : GMTriple := (σ, F, doubleBrown Q)

/-- The GM congruence is the vanishing of the triple's defect — so the triple really is a faithful
record of what `GMrelation` says. -/
theorem gmrelation_iff_tripleOf_defect {σ F : ℤ} (Q : Z4Quadratic ι) :
    GMrelation σ F Q ↔ defect (tripleOf σ F Q) = 0 := by
  constructor
  · intro h
    have e : ((σ - F : ℤ) : ZMod 16) = doubleBrown Q := h
    simp [defect, sigma, selfInt, residue, tripleOf, e]
  · intro h
    have : ((σ - F : ℤ) : ZMod 16) - doubleBrown Q = 0 := h
    exact sub_eq_zero.mp this

/-! ## §1. The forcing theorem -/

/-- **On the spin locus the GM congruence IS `16 ∣ σ`.** (The triple-level restatement of
`CharSurfaceFKVacuity.gmrelation_null_iff_sixteen_dvd`, and the engine of the forcing theorem.) -/
theorem spin_defect_eq_zero_iff (σ : ℤ) :
    defect ((σ, 0, 0) : GMTriple) = 0 ↔ (16 : ℤ) ∣ σ := by
  show ((σ - 0 : ℤ) : ZMod 16) - 0 = 0 ↔ (16 : ℤ) ∣ σ
  rw [sub_zero, sub_zero]
  exact ZMod.intCast_zmod_eq_zero_iff_dvd σ 16

/-- **THE FORCING THEOREM** (new). Let `P` be *any* predicate on the invariant triple which is

* (i) a **consequence** of Guillou–Marin — every GM-satisfying triple satisfies `P`; and
* (ii) **sufficient** for Rokhlin on the spin locus.

Then `P` is, on the spin locus, *literally* `16 ∣ σ`. There is no shape of triple-level statement
layer — bundled, existential, universal, relational, bordism-flavoured — that escapes this. The
practical consequence is a correction to the admissibility test: a biconditional between a `[FK]`
layer's hypothesis and `16 ∣ σ` at spin is **not** evidence that the layer is circular, because the
true Guillou–Marin theorem has exactly that property too. The real test is *intensional* — what data
the hypothesis is a predicate on (§2). -/
theorem triple_layer_forcing (P : GMTriple → Prop)
    (hconseq : ∀ T : GMTriple, defect T = 0 → P T)
    (hsuff : ∀ T : GMTriple, IsSpin T → P T → (16 : ℤ) ∣ sigma T)
    (σ : ℤ) : P (σ, 0, 0) ↔ (16 : ℤ) ∣ σ := by
  constructor
  · intro hP
    exact hsuff (σ, 0, 0) ⟨rfl, rfl⟩ hP
  · intro hdvd
    exact hconseq (σ, 0, 0) ((spin_defect_eq_zero_iff σ).mpr hdvd)

/-- **No faithful `[FK]` layer is extensionally non-circular** (new — the forcing theorem read as a
no-go on a whole *design space*, not on one candidate). Searching for a triple-level layer whose
spin specialization is strictly weaker than `16 ∣ σ` while still following from GM is searching for
something that provably does not exist. -/
theorem no_triple_layer_escapes_the_biconditional :
    ¬ ∃ P : GMTriple → Prop,
        (∀ T : GMTriple, defect T = 0 → P T) ∧
        (∀ T : GMTriple, IsSpin T → P T → (16 : ℤ) ∣ sigma T) ∧
        (∃ σ : ℤ, ¬ (P (σ, 0, 0) ↔ (16 : ℤ) ∣ σ)) := by
  rintro ⟨P, hconseq, hsuff, σ, hne⟩
  exact hne (triple_layer_forcing P hconseq hsuff σ)

/-- Guillou–Marin at a spin ambient gives `16 ∣ σ` — for an arbitrary triple on the spin locus, not
merely one of the normal form `(σ, 0, 0)`. -/
theorem sixteen_dvd_sigma_of_isSpin_of_defect (T : GMTriple) (hs : IsSpin T) (hd : defect T = 0) :
    (16 : ℤ) ∣ sigma T := by
  obtain ⟨h1, h2⟩ := hs
  rw [defect, h1, h2, sub_zero, sub_zero] at hd
  exact (ZMod.intCast_zmod_eq_zero_iff_dvd _ 16).mp hd

/-- **The collapse is specific to the spin locus — it is NOT a degeneracy of triple-level
predicates in general** (new; this is what gives `triple_layer_forcing` teeth rather than making it
a restatement). Two predicates that both satisfy the forcing hypotheses can still differ freely OFF
the spin locus: `defect = 0` and `defect = 0 ∨ T = (0, 1, 0)` are both consequences of Guillou–Marin
and both Rokhlin-sufficient at spin, yet they disagree at the *non-spin* triple `(0, 1, 0)` — an odd
characteristic surface (`σ = 0`, `F·F = 1`, `β = 0`) which violates GM. So `[FK]` at general `σ`
genuinely carries information that the spin specialization destroys; the forcing theorem localizes
exactly where that information is lost, and `GMPinTorsorCeiling` measures how much of it there
is. -/
theorem forcing_collapse_is_spin_specific :
    ∃ P₁ P₂ : GMTriple → Prop,
      ((∀ T : GMTriple, defect T = 0 → P₁ T) ∧
        (∀ T : GMTriple, IsSpin T → P₁ T → (16 : ℤ) ∣ sigma T)) ∧
      ((∀ T : GMTriple, defect T = 0 → P₂ T) ∧
        (∀ T : GMTriple, IsSpin T → P₂ T → (16 : ℤ) ∣ sigma T)) ∧
      ∃ T : GMTriple, ¬ (P₁ T ↔ P₂ T) := by
  refine ⟨fun T => defect T = 0, fun T => defect T = 0 ∨ T = ((0, 1, 0) : GMTriple),
    ⟨fun _ h => h, fun T hs h => sixteen_dvd_sigma_of_isSpin_of_defect T hs h⟩,
    ⟨fun _ h => Or.inl h, fun T hs h => ?_⟩, ((0, 1, 0) : GMTriple), ?_⟩
  · rcases h with h | h
    · exact sixteen_dvd_sigma_of_isSpin_of_defect T hs h
    · rw [h]; exact ⟨0, rfl⟩
  · have hd : defect ((0, 1, 0) : GMTriple) ≠ 0 := by decide
    exact fun hiff => hd (hiff.mpr (Or.inr rfl))

/-! ## §2. The intensional criterion, and why the bordism-by-generators route fails it at the
triple level -/

/-- The verified generator `(ℂP², ℂP¹)`: `σ = 1`, `F·F = 1`, and `H₁(S²;ℤ/2) = 0` forces `β = 0`
(`CharSurfaceFKVacuity.brown_eq_zero_of_isEmpty`), so the residue is `0`. -/
def cp2 : GMTriple := (1, 1, 0)

/-- The verified generator `(ℝP⁴, ℝP²)`: `σ = 0`, `F·F = −2`, `β(ℝP²) = 1` so the residue is `2`.
This is the in-tree `GuillouMarin.GM_rp4` at the triple level. -/
def rp4 : GMTriple := (0, -2, 2)

/-- Both generators satisfy Guillou–Marin (arithmetic; `rp4` is `GM_rp4`). -/
theorem defect_cp2 : defect cp2 = 0 := by decide

theorem defect_rp4 : defect rp4 = 0 := by decide

/-- The `ℤ`-span of the two generators, computed. -/
private lemma smul_gen_eq (m n : ℤ) :
    m • cp2 + n • rp4 = ((m, m - 2 * n, (n : ZMod 16) * 2) : GMTriple) := by
  have h1 : m • (1 : ℤ) + n • (0 : ℤ) = m := by simp
  have h2 : m • (1 : ℤ) + n • (-2 : ℤ) = m - 2 * n := by
    simp only [smul_eq_mul]; ring
  have h3 : m • (0 : ZMod 16) + n • (2 : ZMod 16) = (n : ZMod 16) * 2 := by
    rw [smul_zero, zero_add, zsmul_eq_mul]
  exact Prod.ext h1 (Prod.ext h2 h3)

/-- `rp4` really is the triple of the in-tree `ℝP⁴` witness — the docstring cross-reference is
backed by a call, not by prose. -/
theorem rp4_eq_tripleOf : rp4 = tripleOf 0 (-2) (stdQuadratic 1) := by
  have h : doubleBrown (stdQuadratic 1) = 2 := by
    rw [show doubleBrown (stdQuadratic 1) = 2 * (((stdQuadratic 1).brown.val : ℕ) : ZMod 16) from rfl,
      brown_stdQuadratic]
    decide
  simp [rp4, tripleOf, h]

/-- **The bordism-by-generators reduction is decided by `σ` alone at the triple level** (new — the
verdict on the natural next candidate). Membership of the spin triple `(σ, 0, 0)` in the subgroup
generated by the two verified generators is *exactly* `16 ∣ σ`. So "reduce `[FK]` to: the
characteristic pair's class is generated by `(ℂP², ℂP¹)` and `(ℝP⁴, ℝP²)`" buys nothing while the
class is recorded as a triple: the hypothesis is a σ-arithmetic statement, hence fails the
intensional criterion exactly as the CharSurface wire's `GMrelation σ 0 C.Q` does.

A genuine bordism route must therefore be typed over MANIFOLDS, with a characteristic-pair bordism
group that maps **non-surjectively** onto invariant triples — the non-surjectivity is the entire
geometric content, and the group theory supplies none of it. -/
theorem spin_triple_mem_closure_iff_sixteen_dvd (σ : ℤ) :
    ((σ, 0, 0) : GMTriple) ∈ AddSubgroup.closure ({cp2, rp4} : Set GMTriple) ↔ (16 : ℤ) ∣ σ := by
  rw [AddSubgroup.mem_closure_pair]
  constructor
  · rintro ⟨m, n, hmn⟩
    rw [smul_gen_eq] at hmn
    have h1 : m = σ := congrArg Prod.fst hmn
    have h2 : m - 2 * n = 0 := congrArg (fun T : GMTriple => T.2.1) hmn
    have h3 : ((n : ZMod 16)) * 2 = 0 := congrArg (fun T : GMTriple => T.2.2) hmn
    have hσ : σ = 2 * n := by omega
    have hz : ((2 * n : ℤ) : ZMod 16) = 0 := by push_cast; linear_combination h3
    rw [hσ]
    exact (ZMod.intCast_zmod_eq_zero_iff_dvd (2 * n) 16).mp hz
  · rintro ⟨k, hk⟩
    refine ⟨σ, 8 * k, ?_⟩
    rw [smul_gen_eq]
    have h3 : (((8 * k : ℤ)) : ZMod 16) * 2 = 0 := by
      have h16 : ((16 * k : ℤ) : ZMod 16) = 0 :=
        (ZMod.intCast_zmod_eq_zero_iff_dvd _ 16).mpr ⟨k, rfl⟩
      push_cast at h16 ⊢
      linear_combination h16
    exact Prod.ext rfl (Prod.ext (show σ - 2 * (8 * k) = 0 by omega) h3)

/-- **The generation layer is an instance of the forcing theorem, not an exception to it** — the
docstring claim of `spin_triple_mem_closure_iff_sixteen_dvd` is exactly what
`triple_layer_forcing` predicts, and this derivation checks that the two agree. (The membership
predicate is a GM-consequence on the spin locus and is Rokhlin-sufficient there.) -/
theorem generation_layer_is_forced (σ : ℤ) :
    (((σ, 0, 0) : GMTriple) ∈ AddSubgroup.closure ({cp2, rp4} : Set GMTriple))
      ↔ defect ((σ, 0, 0) : GMTriple) = 0 :=
  (spin_triple_mem_closure_iff_sixteen_dvd σ).trans (spin_defect_eq_zero_iff σ).symm

end SKEFTHawking.GMTripleLayer
