/-
# Kernel-verified NO-GO fence — the consolidated register (GENERATED)

**DO NOT HAND-EDIT.** This module is regenerated by `scripts/gen_kernel_nogos_module.py`
from the single source of truth `KERNEL_NOGO_REGISTRY` (`src/core/constants.py`) and is kept
fresh by the `sync_manifest` staleness edge (pre-commit + `/sync`). It gathers EVERY
kernel-checked no-go of the project into one place so future work — and fresh-context
workers — see the provably-false forks that must NEVER be re-derived, and so the compiler
itself enforces their presence: if a backing refutation theorem is renamed or removed, this
module fails to build (the fence is down → investigate before proceeding).

Companion registers: the machine `KERNEL_NOGO_REGISTRY` (Python; feeds the atlas negative
frontier + `validate.py --check nogo_substrate_integrity`) and the prose
`docs/dev-loops/SETTLED_FORKS.md` (policy/route bans, not kernel-encodable).

## The register (fork-id → FALSE statement → backing theorem[s])

1. `nonhausdorff-bordism-collapse` [refutation]
   The in-tree `Bordism` relation (BordismGroup.lean:37-42) is a faithful bordism theory usable for a
   completeness/injectivity/bounding Prop. FALSE: `Bordism.W` is required compact/charted/IsManifold but NOT
   Hausdorff, so the non-Hausdorff bug-eyed interval B ([0,1] w/ doubled origin, compact + real-analytic + 3
   boundary points) makes W = s.M × B an admissible bordism (s⊔s)⊔s → ∅ for EVERY closed s; with the in-tree
   2-torsion (3x=0 ∧ 2x=0 ⟹ x=0) BordismGrp X 0 I is the TRIVIAL group ([ℝP⁴]=0, a falsifier — false for
   genuine unoriented bordism), and DataBordismGrp mk p = mk q ↔ grade16 equal (no geometric content). ⇒
   hbound and every DataBordismGrp-quantified Prop (incl. Freeze B `SphereProductBounds := mk = 0`) is
   VACUOUS. FIX: require `[t2W : T2Space W]` — the honest relation is `T2TangentialBordism.IsT2DataBordant`;
   real keystone re-anchors to `hboundT2`. NOTE: even T2 at k=0 is TOPOLOGICAL bordism (KS breaks ℤ/16);
   literature-grade needs the SMOOTH (k=∞) + T2 carrier.
   backing: `bordismGrp_subsingleton`, `bordismGrp_rp4_eq_zero`, `dataBordismGMTied_mk_eq_iff_grade16_eq`

2. `comp-twist-doubling-incompatible` [structural_forcing]
   A tangential datum can carry an H¹-coordinate field `comp` with reversal twist `comp ↦ comp + w₁` (the P
   ↦ P⊗ε coordinate), anchored by a restriction-compatibility Bor condition. FALSE (W-A gate, Fable vacuity
   attack 2026-07-13): the mandatory `negBor` inhabits Bor on the DOUBLING bordism — a product cylinder
   whose two boundary inclusions are homotopic — so any '∃x : H¹(W) restricting to the end-comps' condition
   forces comp(revStr σ) = comp σ, contradicting the twist on any non-orientable s (w₁ ≠ 0); the
   uniformly-twisted variant dies on `cylBor` (shift 0). The datum is JOINTLY UNINSTANTIABLE with the
   TangentialData op interface. FIX space: a per-boundary-component collar/co-orientation datum with a
   w₁(W)-corrected compat (any v2 must evade these theorems' hypotheses), or drop the comp field (KT §5 puts
   the odd-bit content in the w₁-dual 3-manifold V / ψ, not in an H¹ coordinate).
   backing: `no_comp_twist_of_doubling_rigid`, `not_doubling_rigid_of_comp_twist`, `no_uniform_comp_twist_of_cylinder_rigid`

3. `membrane-level-nonhausdorff-collapse` [refutation]
   A manifold-typed WITNESS datum inside a carrier or relation (the membrane/3-manifold Q, the surface Σ,
   any auxiliary manifold field) inherits honesty from the T2 fence on the ambient bordism W. FALSE (W-A
   gate, Fable vacuity attack 2026-07-13): the bug-eyed collapse is dimension-generic —
   `qLevelTripleMembrane` is a compact non-Hausdorff membrane with THREE boundary copies of Σ
   (kernel-checked non-T2), so a T2-less Q-encoding lets ker(H₁(∂Q)→H₁(Q)) be adversarially chosen,
   Taylor-Thm-1.1 extension conditions lose their teeth, and the computed Brown/abk8 invariant fails
   bordism-invariance. RULE: every manifold-typed datum needs its OWN T2 (+ compactness/charted)
   certificate; the W-level fence does not propagate.
   backing: `qLevelTripleMembrane_not_t2`

4. `nogo_lattice_arf_not_sigma8` [refutation]
   The lattice Arf bridge σ/8 ≡ Arf(q̄) mod 2 — deriving Rokhlin mod-16 from the intersection FORM alone.
   FALSE: E₈ has Arf(q̄)=0 but σ/8=1; Rokhlin mod-16 is irreducibly geometric (a characteristic-SURFACE Arf,
   not the lattice Arf). Kills Phase 5q.C and any form-only mod-16 shortcut.
   backing: `lattice_arf_bridge_refuted`

5. `mfd-equals-H1-dead-end` [structural_forcing]
   The `Mfd := H¹` tangential-data construction yields a genuine ℤ/16 / ker=⊥. FALSE: a datum whose
   structure-reversal (revStr) is trivial is FORCED 2-torsion, never order-16.
   backing: `dataBordism_two_torsion_of_revStr_trivial`

6. `synthetic-grade-ker-bot-nogo` [structural_forcing]
   ker(abkGrade)=⊥ / card≤16 UNCONDITIONALLY for ANY free-per-manifold grade. FALSE: the ℝP⁴ grade-0 witness
   (w₂=0, [ℝP⁴]≠0∈Ω₄^O) has no unoriented null-bordism, so the free grade is never injective. ker=⊥ requires
   the grade TIED to the structure (the GM carrier), never a better proof on a free-grade datum.
   backing: `dataBordism_two_torsion_of_revStr_trivial`

7. `synthetic-smith-map-to-tied-carrier` [structural_forcing]
   The Smith map into the 5q.H TIED carrier pinPlusGMTiedData can be built SYNTHETICALLY — map every
   neighbor class [M,σ] to [emptySM, (σ,0)] and transport the grade (the smithDataHom shortcut). FALSE
   (kernel-forced): the tie htie (reduce16to2 grade16 = swTotalNe) forces every tied structure on an EMPTY
   carrier to even grade (gmTiedStr_grade_even_of_isEmpty), so the odd generator grade16 = 1 is
   uninhabitable on emptySM (gmTiedStr_empty_grade16_ne_one) — an odd grade requires a real w₁⁴ = 1
   manifold. The tie that defeats synthetic-grade-ker-bot-nogo simultaneously blocks every synthetic Smith
   map; the geometric Smith map into the tied carrier is irreducibly geometric (N1b).
   backing: `gmTiedStr_grade_even_of_isEmpty`, `gmTiedStr_empty_grade16_ne_one`

8. `5qH-injectivity-routes-all-equal-one-completeness-prop` [structural_forcing]
   The three 5q.H injectivity routes — Thom (hthom: SW-trivial Pin⁺ 4-manifold bounds), KT §5 (hle:
   ker(reduce16to8∘abkGMTied16) ⊆ range(n↦n•g8)), Smith-LES (smith_inflow_z16) — are DISTINCT open nodes
   worth route-shopping between. FALSE (kernel-checked equivalence): all three reduce canonically to the ONE
   completeness prop hbound = grade-0-injectivity on the tied carrier — hbound ⟹ hle
   (spin_range_ge_of_grade0_inj), hthom ⟹ hbound (grade0_bounds_of_thom), and the capstone follows from
   grade-0 alone (omega4PinPlusGMTied_equiv_zmod16_via_kt_of_grade0). Route-shopping or re-deriving "which
   route is closer" is settled-moot; the terminal node is the single geometric completeness input (KT §5
   from-below: N1a+N1b+N1c+N2 per ASSEMBLY_GAP_MAP_20260712).
   backing: `spin_range_ge_of_grade0_inj`, `omega4PinPlusGMTied_equiv_zmod16_via_kt_of_grade0`, `grade0_bounds_of_thom`

9. `5qH-fg-ek-over-Z-blocked` [refutation]
   The mod-2 Erdős–Kaplansky finiteness forcing (SingularUCFinite: self-duality forces finite dimension)
   transports to ℤ — in particular dualization over ℤ stays in the f.g./countable size class, so PD + UCT
   self-duality would force H²(M;ℤ) finitely generated. FALSE: the ℤ-dual of the COUNTABLE free module ℕ →₀
   ℤ is the UNCOUNTABLE, non-f.g. Baer–Specker group ℕ → ℤ (kernel: dual_blowup_not_finite); and the ℤ-EK
   statement itself is refuted in the literature by Specker 1950 — (⊕ℤ) ⊕ ℤ^ℕ is self-dual and not f.g.
   (slenderness of ℤ; Mathlib-absent, formalization queued). Scout-verified vs FNOP arXiv:1910.07372 +
   Blass–Göbel math/9405206; verdict file
   Lit-Search/Phase-5qH/FG_via_PD_duality_forcing_verdict_20260712.md.
   backing: `dual_blowup_not_finite`, `not_finite_baerSpecker`

10. `genuine-gm-carrier-eight-torsion` [refutation]
   The genuine ℤ/16 lives directly on the thin GM carrier: DataBordismGrp(pinPlusGMData) ≃+ ZMod 16. FALSE:
   pinPlusGMData's bordism relation records ONLY the mod-8 Brown grade (q.brown ∈ ZMod 8), so
   cylinder-doubling makes every class 8-torsion (pinPlusGMData_eight_torsion: 8•x=0) ⟹
   IsEmpty(DataBordismGrp(pinPlusGMData) ≃+ ZMod 16). The ℤ/16 odd bit is the Smith-LES EXTENSION onto a
   distinct carrier (the tied/extension carrier, whose mod-8 shadow is abkGM8 via forgetTie), NEVER a
   surface grade on pinPlusGMData itself. Do NOT target `omega4PinPlusGM_equiv_zmod16 :
   DataBordismGrp(pinPlusGMData) ≃+ ZMod 16` as literally stated — reframe to the Smith-LES extension
   carrier (E3) or an enriched (σ,F•F)-carrying GM carrier.
   backing: `pinPlusGMData_not_equiv_zmod16`, `pinPlusGMData_eight_torsion`

-/
import SKEFTHawking.FGDualityNoGo
import SKEFTHawking.NonHausdorffBordismCollapse
import SKEFTHawking.PinPlusCompTorsorNoGo
import SKEFTHawking.PinPlusGMDataZ16
import SKEFTHawking.PinPlusGMWitness
import SKEFTHawking.PinPlusGenuineCarrierIso
import SKEFTHawking.RokhlinArfNoGo
import SKEFTHawking.SyntheticSmithNoGo
import SKEFTHawking.UnorientedThomCapstone

namespace SKEFTHawking.KernelNoGos

/-- NO-GO [`nonhausdorff-bordism-collapse`] — do NOT re-derive. FALSE: The in-tree `Bordism` relation (BordismGroup.lean:37-42) is a faithful bordism theory usable for a completeness/injectivity/bounding Prop. Backing refutation: `SKEFTHawking.NonHausdorffBordismCollapse.bordismGrp_subsingleton`. -/
alias nogo_bordismGrp_subsingleton := SKEFTHawking.NonHausdorffBordismCollapse.bordismGrp_subsingleton

/-- NO-GO [`nonhausdorff-bordism-collapse`] — do NOT re-derive. FALSE: The in-tree `Bordism` relation (BordismGroup.lean:37-42) is a faithful bordism theory usable for a completeness/injectivity/bounding Prop. Backing refutation: `SKEFTHawking.NonHausdorffBordismCollapse.bordismGrp_rp4_eq_zero`. -/
alias nogo_bordismGrp_rp4_eq_zero := SKEFTHawking.NonHausdorffBordismCollapse.bordismGrp_rp4_eq_zero

/-- NO-GO [`nonhausdorff-bordism-collapse`] — do NOT re-derive. FALSE: The in-tree `Bordism` relation (BordismGroup.lean:37-42) is a faithful bordism theory usable for a completeness/injectivity/bounding Prop. Backing refutation: `SKEFTHawking.NonHausdorffBordismCollapse.dataBordismGMTied_mk_eq_iff_grade16_eq`. -/
alias nogo_dataBordismGMTied_mk_eq_iff_grade16_eq := SKEFTHawking.NonHausdorffBordismCollapse.dataBordismGMTied_mk_eq_iff_grade16_eq

/-- NO-GO [`comp-twist-doubling-incompatible`] — do NOT re-derive. FALSE: A tangential datum can carry an H¹-coordinate field `comp` with reversal twist `comp ↦ comp + w₁` (the P ↦ P⊗ε coordinate), anchored by a restriction-compatibility Bor condition. Backing refutation: `SKEFTHawking.PinPlusCompTorsorNoGo.no_comp_twist_of_doubling_rigid`. -/
alias nogo_no_comp_twist_of_doubling_rigid := SKEFTHawking.PinPlusCompTorsorNoGo.no_comp_twist_of_doubling_rigid

/-- NO-GO [`comp-twist-doubling-incompatible`] — do NOT re-derive. FALSE: A tangential datum can carry an H¹-coordinate field `comp` with reversal twist `comp ↦ comp + w₁` (the P ↦ P⊗ε coordinate), anchored by a restriction-compatibility Bor condition. Backing refutation: `SKEFTHawking.PinPlusCompTorsorNoGo.not_doubling_rigid_of_comp_twist`. -/
alias nogo_not_doubling_rigid_of_comp_twist := SKEFTHawking.PinPlusCompTorsorNoGo.not_doubling_rigid_of_comp_twist

/-- NO-GO [`comp-twist-doubling-incompatible`] — do NOT re-derive. FALSE: A tangential datum can carry an H¹-coordinate field `comp` with reversal twist `comp ↦ comp + w₁` (the P ↦ P⊗ε coordinate), anchored by a restriction-compatibility Bor condition. Backing refutation: `SKEFTHawking.PinPlusCompTorsorNoGo.no_uniform_comp_twist_of_cylinder_rigid`. -/
alias nogo_no_uniform_comp_twist_of_cylinder_rigid := SKEFTHawking.PinPlusCompTorsorNoGo.no_uniform_comp_twist_of_cylinder_rigid

/-- NO-GO [`membrane-level-nonhausdorff-collapse`] — do NOT re-derive. FALSE: A manifold-typed WITNESS datum inside a carrier or relation (the membrane/3-manifold Q, the surface Σ, any auxiliary manifold field) inherits honesty from the T2 fence on the ambient bordism W. Backing refutation: `SKEFTHawking.PinPlusCompTorsorNoGo.qLevelTripleMembrane_not_t2`. -/
alias nogo_qLevelTripleMembrane_not_t2 := SKEFTHawking.PinPlusCompTorsorNoGo.qLevelTripleMembrane_not_t2

/-- NO-GO [`nogo_lattice_arf_not_sigma8`] — do NOT re-derive. FALSE: The lattice Arf bridge σ/8 ≡ Arf(q̄) mod 2 — deriving Rokhlin mod-16 from the intersection FORM alone. Backing refutation: `SKEFTHawking.RokhlinArfNoGo.lattice_arf_bridge_refuted`. -/
alias nogo_lattice_arf_bridge_refuted := SKEFTHawking.RokhlinArfNoGo.lattice_arf_bridge_refuted

/-- NO-GO [`mfd-equals-H1-dead-end`] — do NOT re-derive. FALSE: The `Mfd := H¹` tangential-data construction yields a genuine ℤ/16 / ker=⊥. Backing refutation: `SKEFTHawking.PinPlusGenuineCarrierIso.dataBordism_two_torsion_of_revStr_trivial`. -/
alias nogo_dataBordism_two_torsion_of_revStr_trivial := SKEFTHawking.PinPlusGenuineCarrierIso.dataBordism_two_torsion_of_revStr_trivial

/-- NO-GO [`synthetic-grade-ker-bot-nogo`] — do NOT re-derive. FALSE: ker(abkGrade)=⊥ / card≤16 UNCONDITIONALLY for ANY free-per-manifold grade. Backing refutation: `SKEFTHawking.PinPlusGenuineCarrierIso.dataBordism_two_torsion_of_revStr_trivial`. -/
alias nogo_dataBordism_two_torsion_of_revStr_trivial_2 := SKEFTHawking.PinPlusGenuineCarrierIso.dataBordism_two_torsion_of_revStr_trivial

/-- NO-GO [`synthetic-smith-map-to-tied-carrier`] — do NOT re-derive. FALSE: The Smith map into the 5q.H TIED carrier pinPlusGMTiedData can be built SYNTHETICALLY — map every neighbor class [M,σ] to [emptySM, (σ,0)] and transport the grade (the smithDataHom shortcut). Backing refutation: `SKEFTHawking.PinPlusGMTiedData.gmTiedStr_grade_even_of_isEmpty`. -/
alias nogo_gmTiedStr_grade_even_of_isEmpty := SKEFTHawking.PinPlusGMTiedData.gmTiedStr_grade_even_of_isEmpty

/-- NO-GO [`synthetic-smith-map-to-tied-carrier`] — do NOT re-derive. FALSE: The Smith map into the 5q.H TIED carrier pinPlusGMTiedData can be built SYNTHETICALLY — map every neighbor class [M,σ] to [emptySM, (σ,0)] and transport the grade (the smithDataHom shortcut). Backing refutation: `SKEFTHawking.PinPlusGMTiedData.gmTiedStr_empty_grade16_ne_one`. -/
alias nogo_gmTiedStr_empty_grade16_ne_one := SKEFTHawking.PinPlusGMTiedData.gmTiedStr_empty_grade16_ne_one

/-- NO-GO [`5qH-injectivity-routes-all-equal-one-completeness-prop`] — do NOT re-derive. FALSE: The three 5q.H injectivity routes — Thom (hthom: SW-trivial Pin⁺ 4-manifold bounds), KT §5 (hle: ker(reduce16to8∘abkGMTied16) ⊆ range(n↦n•g8)), Smith-LES (smith_inflow_z16) — are DISTINCT open nodes worth route-shopping between. Backing refutation: `SKEFTHawking.PinPlusGMWitness.spin_range_ge_of_grade0_inj`. -/
alias nogo_spin_range_ge_of_grade0_inj := SKEFTHawking.PinPlusGMWitness.spin_range_ge_of_grade0_inj

/-- NO-GO [`5qH-injectivity-routes-all-equal-one-completeness-prop`] — do NOT re-derive. FALSE: The three 5q.H injectivity routes — Thom (hthom: SW-trivial Pin⁺ 4-manifold bounds), KT §5 (hle: ker(reduce16to8∘abkGMTied16) ⊆ range(n↦n•g8)), Smith-LES (smith_inflow_z16) — are DISTINCT open nodes worth route-shopping between. Backing refutation: `SKEFTHawking.PinPlusGMWitness.omega4PinPlusGMTied_equiv_zmod16_via_kt_of_grade0`. -/
alias nogo_omega4PinPlusGMTied_equiv_zmod16_via_kt_of_grade0 := SKEFTHawking.PinPlusGMWitness.omega4PinPlusGMTied_equiv_zmod16_via_kt_of_grade0

/-- NO-GO [`5qH-injectivity-routes-all-equal-one-completeness-prop`] — do NOT re-derive. FALSE: The three 5q.H injectivity routes — Thom (hthom: SW-trivial Pin⁺ 4-manifold bounds), KT §5 (hle: ker(reduce16to8∘abkGMTied16) ⊆ range(n↦n•g8)), Smith-LES (smith_inflow_z16) — are DISTINCT open nodes worth route-shopping between. Backing refutation: `SKEFTHawking.UnorientedThomCapstone.grade0_bounds_of_thom`. -/
alias nogo_grade0_bounds_of_thom := SKEFTHawking.UnorientedThomCapstone.grade0_bounds_of_thom

/-- NO-GO [`5qH-fg-ek-over-Z-blocked`] — do NOT re-derive. FALSE: The mod-2 Erdős–Kaplansky finiteness forcing (SingularUCFinite: self-duality forces finite dimension) transports to ℤ — in particular dualization over ℤ stays in the f.g./countable size class, so PD + UCT self-duality would force H²(M;ℤ) finitely generated. Backing refutation: `SKEFTHawking.FGDualityNoGo.dual_blowup_not_finite`. -/
alias nogo_dual_blowup_not_finite := SKEFTHawking.FGDualityNoGo.dual_blowup_not_finite

/-- NO-GO [`5qH-fg-ek-over-Z-blocked`] — do NOT re-derive. FALSE: The mod-2 Erdős–Kaplansky finiteness forcing (SingularUCFinite: self-duality forces finite dimension) transports to ℤ — in particular dualization over ℤ stays in the f.g./countable size class, so PD + UCT self-duality would force H²(M;ℤ) finitely generated. Backing refutation: `SKEFTHawking.FGDualityNoGo.not_finite_baerSpecker`. -/
alias nogo_not_finite_baerSpecker := SKEFTHawking.FGDualityNoGo.not_finite_baerSpecker

/-- NO-GO [`genuine-gm-carrier-eight-torsion`] — do NOT re-derive. FALSE: The genuine ℤ/16 lives directly on the thin GM carrier: DataBordismGrp(pinPlusGMData) ≃+ ZMod 16. Backing refutation: `SKEFTHawking.PinPlusGMDataZ16.pinPlusGMData_not_equiv_zmod16`. -/
alias nogo_pinPlusGMData_not_equiv_zmod16 := SKEFTHawking.PinPlusGMDataZ16.pinPlusGMData_not_equiv_zmod16

/-- NO-GO [`genuine-gm-carrier-eight-torsion`] — do NOT re-derive. FALSE: The genuine ℤ/16 lives directly on the thin GM carrier: DataBordismGrp(pinPlusGMData) ≃+ ZMod 16. Backing refutation: `SKEFTHawking.PinPlusGMDataZ16.pinPlusGMData_eight_torsion`. -/
alias nogo_pinPlusGMData_eight_torsion := SKEFTHawking.PinPlusGMDataZ16.pinPlusGMData_eight_torsion

end SKEFTHawking.KernelNoGos
