/-
# Kernel-verified NO-GO fence — the consolidated register (GENERATED)

**DO NOT HAND-EDIT.** This module is regenerated by `scripts/gen_kernel_nogos_module.py`
from the single source of truth `KERNEL_NOGO_REGISTRY` (`src/core/constants.py`) and is kept
fresh by the `sync_manifest` staleness edge (pre-commit + `/sync`). It gathers EVERY
kernel-checked no-go of the project into one place so future work — and fresh-context
workers — see the provably-false forks that must NEVER be re-derived, and so the compiler
itself enforces their presence: if a backing refutation theorem is renamed or removed, this
module fails to build (the fence is down → investigate before proceeding).

Companion registers: the machine `KERNEL_NOGO_REGISTRY` (Python; feeds the atlas negative
frontier + `validate.py --check nogo_substrate_integrity`) and the prose
`docs/dev-loops/SETTLED_FORKS.md` (policy/route bans, not kernel-encodable).

## The register (fork-id → FALSE statement → backing theorem[s])

1. `nonhausdorff-bordism-collapse` [refutation]
   The in-tree `Bordism` relation (BordismGroup.lean:37-42) is a faithful bordism theory usable for a
   completeness/injectivity/bounding Prop. FALSE: `Bordism.W` is required compact/charted/IsManifold but NOT
   Hausdorff, so the non-Hausdorff bug-eyed interval B ([0,1] w/ doubled origin, compact + real-analytic + 3
   boundary points) makes W = s.M × B an admissible bordism (s⊔s)⊔s → ∅ for EVERY closed s; with the in-tree
   2-torsion (3x=0 ∧ 2x=0 ⟹ x=0) BordismGrp X 0 I is the TRIVIAL group ([ℝP⁴]=0, a falsifier — false for
   genuine unoriented bordism), and DataBordismGrp mk p = mk q ↔ grade16 equal (no geometric content). ⇒
   hbound and every DataBordismGrp-quantified Prop (incl. Freeze B `SphereProductBounds := mk = 0`) is
   VACUOUS. FIX: require `[t2W : T2Space W]` — the honest relation is `T2TangentialBordism.IsT2DataBordant`;
   real keystone re-anchors to `hboundT2`. NOTE: even T2 at k=0 is TOPOLOGICAL bordism (KS breaks ℤ/16);
   literature-grade needs the SMOOTH (k=∞) + T2 carrier.
   backing: `bordismGrp_subsingleton`, `bordismGrp_rp4_eq_zero`, `dataBordismGMTied_mk_eq_iff_grade16_eq`

2. `comp-twist-doubling-incompatible` [structural_forcing]
   A tangential datum can carry an H¹-coordinate field `comp` with reversal twist `comp ↦ comp + w₁` (the P
   ↦ P⊗ε coordinate), anchored by a restriction-compatibility Bor condition. FALSE (W-A gate, Fable vacuity
   attack 2026-07-13): the mandatory `negBor` inhabits Bor on the DOUBLING bordism — a product cylinder
   whose two boundary inclusions are homotopic — so any '∃x : H¹(W) restricting to the end-comps' condition
   forces comp(revStr σ) = comp σ, contradicting the twist on any non-orientable s (w₁ ≠ 0); the
   uniformly-twisted variant dies on `cylBor` (shift 0). The datum is JOINTLY UNINSTANTIABLE with the
   TangentialData op interface. FIX space: a per-boundary-component collar/co-orientation datum with a
   w₁(W)-corrected compat (any v2 must evade these theorems' hypotheses), or drop the comp field (KT §5 puts
   the odd-bit content in the w₁-dual 3-manifold V / ψ, not in an H¹ coordinate).
   backing: `no_comp_twist_of_doubling_rigid`, `not_doubling_rigid_of_comp_twist`, `no_uniform_comp_twist_of_cylinder_rigid`

3. `membrane-level-nonhausdorff-collapse` [refutation]
   A manifold-typed WITNESS datum inside a carrier or relation (the membrane/3-manifold Q, the surface Σ,
   any auxiliary manifold field) inherits honesty from the T2 fence on the ambient bordism W. FALSE (W-A
   gate, Fable vacuity attack 2026-07-13): the bug-eyed collapse is dimension-generic —
   `qLevelTripleMembrane` is a compact non-Hausdorff membrane with THREE boundary copies of Σ
   (kernel-checked non-T2), so a T2-less Q-encoding lets ker(H₁(∂Q)→H₁(Q)) be adversarially chosen,
   Taylor-Thm-1.1 extension conditions lose their teeth, and the computed Brown/abk8 invariant fails
   bordism-invariance. RULE: every manifold-typed datum needs its OWN T2 (+ compactness/charted)
   certificate; the W-level fence does not propagate.
   backing: `qLevelTripleMembrane_not_t2`

4. `free-membrane-kernel-kills-nonsplit` [refutation]
   The as-built CharPair carrier (Bor with the membrane kernel L carried as a FREE Submodule field, the
   geometric membrane Q deferred) supports the KT §5 non-split content — KTNonSplit (8•[ℝP⁴] ≠ 0) is
   open/dischargeable on it. FALSE (W-D vacuity gate round 3, Fable, 2026-07-13, kernel-checked FOR EVERY
   PROVIDER): with L free, the UN-reversed double σ⊔σ bounds the plain doubling cylinder whenever q⊕q admits
   ANY metabolic Lagrangian (brown ∈ {0,4}); the e₈/extended-Hamming graph of x ↦ x + (Σx)·𝟙 (q∘φ = −q,
   16-point decide) certifies one for [ℝP⁴]⁴ that NO membrane in (ℝP⁴)⁴×I realizes ⟹ 8•[ℝP⁴] = 0, the binder
   pair {KTKernelCard, KTNonSplit} is jointly unsatisfiable, and ⟨[ℝP⁴]⟩ is ≤ ℤ/8. The anti-collapse engine
   protects only Witt-class (brown) equality — exactly the part KT p.217 says cannot see [Kummer]. ROUND-3
   OF THE PATTERN: every deferred geometric tie converts completeness content into falsehood (rounds 1-2:
   comp-twist, membrane-T2, taylor-leg). FIX: CharPairBor must carry the certified membrane Q with L
   COMPUTED as ker(H₁(∂Q)→H₁(Q)) + the item-3 relative characteristic tie (the frozen v4 spec,
   under-implemented by the interim build); acceptance test = the honest cylinder membrane's ANTI-DIAGONAL
   kernel excludes the e₈ graph (doubleKillerBor must break). Also: KTKernelCard quantifies over
   hchar-untethered fake classes (fakeRP4RankZero) — tie (n,q,surf) or restrict the quantifier before
   restating. UPDATE (arm-4 re-gate migration + round-4.5 self-attack, 2026-07-14): the FIX's first half
   LANDED — pinPlusCharPairData's Bor is the membrane-TIED CharPairBorTied in-place (L = ker mem.bInc, all 8
   op witnesses tied, PinPlusCharPairData §9.6; acceptance tests green in PinPlusCharPairMembraneTie). The
   backing refutations PERSIST on the migrated carrier via the SYNTHETIC-bInc replay (doubleKillerBorTied,
   PinPlusKTVacuityGateWD §4.5: GeoMembrane.bInc is still un-tethered, and graphBInc phiLin has kernel
   exactly the e₈ graph) — i.e. the tie NARROWS the hole to precisely the geometric-realization obligation
   without closing it; binders stay FROZEN. Remaining discharge: require realization data on the membrane
   datum (GeoRealizationData/GeoMembrane.ofGeometric, PinPlusCharPairMembraneGeoRealization) + the
   (n,q,surf) tie, then the fresh Fable re-gate. UPDATE 2 (THE FLIP, 2026-07-15): the FIX is COMPLETE —
   pinPlusCharPairData's Bor is CharPairBorRealized (all 8 op witnesses realized via GeoRealizationTied:
   derived bases from the carried (n,q,surf) tie + per-object certs + kernels computed from real membrane
   topology; provider = CharPairWProviderPinned). The instance-level refutations (ktKernelRep_eq_zero,
   ktNonSplit_false, kt_binders_unsatisfiable, ktKummerTarget_unsatisfiable,
   ktRP4Class_addOrderOf_dvd_eight) no longer type-check against the flipped carrier and are REMOVED
   (PinPlusKTVacuityGateWD §5 conversion banner); backing re-pointed to the retained structure-level engines
   (L44_metabolic + doubleKillerBInc_ker — the kernel-checked e₈ record over the algebraic-core structures,
   which persist as the historical exploit shapes). The W-D binders {KTKernelCard, KTNonSplit} are GENUINELY
   OPEN (not refuted, not discharged) — their discharge is W-D's gated work and must pass the round-6
   vacuity gate before consumption.
   backing: `L44_metabolic`, `doubleKillerBInc_ker`

5. `tied-carrier-inhabitation-equiv-free` [structural_forcing]
   The membrane-tied CharPairBorTied (L = ker mem.bInc) is a strictly finer bordism-witness class than the
   refuted free-L CharPairBor — the tie alone filters geometrically-unrealizable Lagrangians. FALSE (W-A
   re-gate round 5, Fable, 2026-07-14, kernel-checked): EVERY submodule of the joint boundary space is the
   computed kernel of a synthetic membrane (GeoMembrane.ofSubmodule via a quotient basis; ofSubmodule_L
   exact), so Nonempty (CharPairBorTied b σ τ) ↔ Nonempty (CharPairBor b σ τ)
   (charPairBorTied_nonempty_iff_free) — the tied carrier is inhabitation-EQUIVALENT to the free one, and
   every round-3/free-form exploit transfers wholesale (round-4.5's doubleKillerBorTied is one instance of
   this general fact). Also: GeoMembrane.top (mid = 0, kernel ⊤) inhabits for ALL end forms and
   JointLagrangian is VACUOUS at ⊤ (jointLagrangian_top) — only the Taylor leg ever blocks a degenerate
   membrane. RULE: the tie is a SHAPE, not a filter, until mem is forced through geometric-realization data
   carrying the (n,q,surf) basis tie. NOTE (THE FLIP, 2026-07-15): the live carrier's Bor is now
   CharPairBorRealized — the strict refinement this fork says the tie alone is not; the fork stays TRUE at
   the tied level (the backing theorems are structure-level and persist) and is the permanent record of WHY
   the realized refinement is load-bearing.
   backing: `charPairBorTied_nonempty_iff_free`, `jointLagrangian_top`
   ⚠ UNRESOLVED backing (not found in-tree — check the registry): `SKEFTHawking.PinPlusCharPairGeoRealizationGate.GeoMembrane.ofSubmodule_L`

6. `realization-seam-basis-gauge-launders-e8` [refutation]
   Topological certificates on GeoRealizationData (T2, compactness, closed-embedding ι, dimension,
   membrane-in-W) suffice to make GeoMembrane.ofGeometric honest — a fully-certified realization cannot
   carry the e₈ kernel. FALSE (W-A re-gate round 5, Fable, 2026-07-14, kernel-checked): the free basis
   fields eσ/eτ admit a gauge action (GeoRealizationData.gaugeσ) that FIXES every topological field
   (gaugeσ_bdry/Q/U/ι all rfl — every space/map certificate is gauge-blind) while moving the computed kernel
   by a block gauge (ker_transportedBInc_gaugeσ); the killerGauge (id ⊞ phiLin through finSumFinEquiv) maps
   the honest doubling anti-diagonal EXACTLY onto the e₈ kernel (map_killerGauge_ker_negBorBInc), so ANY
   realization of negBor's own design-mandatory membrane yields a certified ofGeometric image hosting the
   un-reversed double (doubleKillerBorGeoRealized, conditional on the cylinder realization the roadmap
   itself requires). General engine: the graph of ANY isometry is a block-gauged anti-diagonal
   (map_blockCongr_cylLagrangian) — the half-lives-half-dies geometric signature is NOT gauge-invariant.
   Also kernel-irrelevant: the eQ freedom (ker_transportedBInc_gaugeQ). RULE: the H₁ bases must be DERIVED
   from the carrier's (n,q,surf) tie (hpolar/hchar-anchored identification of the realization's ends with
   the carried surfaces), never free fields; topological certificates are necessary but collectively blind.
   NOTE (THE FLIP, 2026-07-15): the closing mechanism this fork mandates is LIVE — GeoRealizationTied's
   derivedEσ/τ (toData_eσ = rfl, nothing to post-compose) is the Bor consumed by the flipped
   pinPlusCharPairData; the fork stays TRUE over the free GeoRealizationData (backing persists) as the
   record of the gauge exploit the derived bases kill.
   backing: `map_killerGauge_ker_negBorBInc`, `ker_transportedBInc_gaugeσ`, `doubleKillerGeoMem_L`, `map_blockCongr_cylLagrangian`

7. `wadm-sqop-gauge-w2-filter-vacuous` [refutation]
   WAdm/hwu (wuW2 P14 P23 = 0) is a w₂(W) = 0 filter — discharging a CharPairWProvider certifies genuine
   Pin⁺-admissibility of the bordisms it covers. FALSE (W-A re-gate round 5, Fable, 2026-07-14,
   kernel-checked): LefschetzWuDatum.sqOp is a FREE field constrained by neither nondeg nor dimeq; zeroing
   it makes both Wu classes vanish (wuClass_zeroSq) and hwu hold for EVERY W whatever its honest w₂
   (wuW2_zeroSq), so a full CharPairWProvider is dischargeable from bare Lefschetz-duality data with ZERO
   Steenrod input (charPairWProviderOfDuality) — bordisms with genuine w₂(W) ≠ 0 pass. Same
   free-field-plus-self-referential-condition shape as round-3's free L; infects CharPairBorTied.P14/P23/hwu
   directly (the Bor carries copies). RULE: sqOp (and mu/cup) must be PINNED to the substrate's actual
   relative Steenrod tower (relSq1/relSq2) / fundamental-class evaluation / cup product — definitionally or
   via certificate fields — in both WAdm and the Bor's own data; no provider instantiation is acceptable
   without the pin (cylinderP14/P23's sqOp := relSq1/relSq2 is the precedent). UPDATE (arm-4 round 2,
   2026-07-14): the PIN LAYER LANDED (PinPlusWAdmPinned) — certificate pins on ALL THREE fields (the audit
   found cup/mu are a FAITHFULNESS hole even though nondeg blocks zeroing them: a perfect-but-wrong pairing
   decouples wuClass from the manifold's actual w2): LefschetzWuPinned14/23 + WAdmPinned +
   CharPairWProviderPinned + CharPairBorTiedPinned. Discrimination kernel-checked both ways:
   sqOpPinned23_zeroSq_iff (the zeroSq shortcut satisfies the pin IFF the honest relSq = 0),
   not_sqOpPinned23_ofLefschetzNoWu (the F3 provider engine hands out UN-pinnable data wherever relSq2 !=
   0), cylinderP14_pinned/cylinderP23_pinned (honest non-vacuity witnesses),
   CharPairBorTiedPinned.wuFunctional23_honest (a pinned Bor's hwu is the genuine w2-condition). Remaining:
   fold the pinned refinement into the live carrier's Bor consumption (post basis-tie merge), then re-gate.
   UPDATE 2 (arm-4 R1, 2026-07-14): the FAKE-CLASS half is CLOSED — the hchar characteristic-surface tie
   landed on CharPairStrBundled (Guillou-Marin: kroneckerH a (emb-pushforward of surfClass) = mu(a cup a),
   Nonempty-guarded; all four bundle witnesses supply it; RP4 via the DISCHARGED cruxPullbackGen + the mu(a
   cup a) = mu(a cup x^2) bridge), and the fake exhibit is UNINHABITABLE: fakeRP4RankZero no longer
   type-checks and is removed; kernel-checked kill theorems
   RP4CharPairWitness.rp4_bundle_surfClass_pushforward_ne_zero (every RP4 char-pair bundle has nonvanishing
   pushed-forward surface class) + no_empty_surface_bundle_on_rp4. KTKernelCard is no longer honestly-false
   via fake classes. The SOLE remaining discharge item on this fork = the GeoMembrane bInc geometric
   realization (the synthetic-bInc refutations persist; binders stay frozen) + the fresh Fable re-gate.
   UPDATE 3 (THE FLIP, 2026-07-15): the pinned provider is LIVE — pinPlusCharPairData now takes
   CharPairWProviderPinned and its Bor is CharPairBorRealized (P14/P23 carry pin14/pin23 by construction),
   so hwu on every live bordism witness is the HONEST w₂-condition; the bInc realization discharge item is
   COMPLETE. Residual on this fork = the round-6 re-gate.
   backing: `wuW2_zeroSq`, `wuClass_zeroSq`

8. `taylor-leg-end-convention-trap` [structural_forcing]
   The structured-bordism Taylor extension leg ('boundary classes bounding in the membrane Q have vanishing
   enhancement') can be stated as a PLAIN joint sum q_σ ⊕ q_τ, or σ-side-only, vanishing on
   ker(H₁(∂Q)→H₁(Q)). FALSE (W-A re-gate, Fable round 2, 2026-07-13 — both failures fire through the HONEST
   T2 cylinder, no certificate blocks them): plain-joint forces 2q = 0 on cylinder-kernel classes (the
   anti-diagonal), killing every odd enhancement value — the ℝP²/ℝP⁴ witness (q(gen)=1, 1+1=2≠0 in ℤ/4)
   becomes uninstantiable (cylBor totality fails); σ-side-only is vacuous on cylinders, making
   Bor(reflCylinder) relate ARBITRARY structures — the torsor collapses and the Brown/abk8 map is
   ill-defined (1 ≠ −1 in ℤ/8 erased). The ONLY correct form negates the τ-END (per Bor-end, not per
   boundary component): q_σ ⊕ (Z4Quadratic.neg q_τ) vanishes on ker(H₁(∂Q;ℤ/2)→H₁(Q;ℤ/2)). Under that form
   all 12 TangentialData ops instantiate and Brown-invariance is forced (Lagrangian + Gauss factorization).
   backing: `no_plain_end_pairing_of_cylinder`, `not_cylinder_plain_pairing_of_odd_value`, `not_cylinder_bor_of_invariant_ne`

9. `untethered-membrane-factors-relation` [structural_forcing]
   The flipped carrier (Bor = CharPairBorRealized: GeoRealizationTied with derived bases + computed kernels
   + pinned provider) supports the KT non-split content — the abstract compact-T2 membrane suffices; no
   explicit tether of the realization's Q to the bordism's W is needed. FALSE (W-A gate ROUND 6, Fable,
   2026-07-15, kernel-encoded — ROUND 6 OF THE DEFERRED-TIE PATTERN): GeoRealizationTied has NO tether to
   b.W (Q is an arbitrary compact-T2 TopCat — not a manifold, not in W). Consequences, kernel-checked: (1)
   CharPairBorRealized.transport — any realized witness transports VERBATIM to ANY bordism between the same
   ends; (2) isT2DataBordant_pinPlusCharPair_factors — the structured relation FACTORS as (∃ unstructured T2
   bordism) ∧ ends-only HasEndsRealization, so given a provider, hwu filters NOTHING at the relation level;
   (3) ktNonSplit_false_of_e8 — ONE mathematically-TRUE abstract hypothesis (E8MembraneRealization: a
   compact-T2 pair with the e₈-graph H₁-kernel — constructible as 8 RP²'s + an arc tree + four 2-cells, only
   missing CW/MV machinery in-tree) reproduces the ENTIRE pre-flip refutation chain (8•[RP⁴] = 0, binders
   jointly unsatisfiable, addOrderOf ∣ 8). KTNonSplit is mathematically FALSE on the untethered shape; W-D
   binder discharge must NOT open on it (an apparent discharge = an error elsewhere). Positive gate evidence
   retained: idRealizationTied blocked ONLY by hlag (not_jointLagrangian_bot); the un-reversed in-tree
   doubling blocked by htaylor (unreversed_double_diag_not_taylorLeg); in-tree engines reach only
   homeo-graph/block-diagonal kernels (e₈ unreachable at the in-tree horizon) — the exploit needs the
   abstract-Q freedom, which is exactly what the tether removes. FROZEN ROUND-6 SPEC: (1) THE W-TETHER —
   CharPairBorRealized gains ιW : C(Q, b.W) (honest form a closed embedding) with commuting glue (real.ι,
   homσ/homτ, the ends' emb, b's boundary structure); (2) manifold discipline on Q (charted/dimension
   certificates — abstract compact-T2 admits CW pathologies); (3) provider-quantification fix
   (CharPairWProviderPinned's ∀-all-bordisms wadm is likely UNINHABITABLE — pinned hwu is impossible on
   w₂(W) ≠ 0 bordisms — risking vacuity in BOTH directions; restrict to the op-bordism family actually
   consumed or per-op admissibility data). Then round-7 re-gate.
   backing: `isT2DataBordant_pinPlusCharPair_factors`, `ktNonSplit_false_of_e8`
   ⚠ UNRESOLVED backing (not found in-tree — check the registry): `SKEFTHawking.PinPlusCharPairFlipGate.CharPairBorRealized.transport`

10. `nogo_lattice_arf_not_sigma8` [refutation]
   The lattice Arf bridge σ/8 ≡ Arf(q̄) mod 2 — deriving Rokhlin mod-16 from the intersection FORM alone.
   FALSE: E₈ has Arf(q̄)=0 but σ/8=1; Rokhlin mod-16 is irreducibly geometric (a characteristic-SURFACE Arf,
   not the lattice Arf). Kills Phase 5q.C and any form-only mod-16 shortcut.
   backing: `lattice_arf_bridge_refuted`

11. `mfd-equals-H1-dead-end` [structural_forcing]
   The `Mfd := H¹` tangential-data construction yields a genuine ℤ/16 / ker=⊥. FALSE: a datum whose
   structure-reversal (revStr) is trivial is FORCED 2-torsion, never order-16.
   backing: `dataBordism_two_torsion_of_revStr_trivial`

12. `synthetic-grade-ker-bot-nogo` [structural_forcing]
   ker(abkGrade)=⊥ / card≤16 UNCONDITIONALLY for ANY free-per-manifold grade. FALSE: the ℝP⁴ grade-0 witness
   (w₂=0, [ℝP⁴]≠0∈Ω₄^O) has no unoriented null-bordism, so the free grade is never injective. ker=⊥ requires
   the grade TIED to the structure (the GM carrier), never a better proof on a free-grade datum.
   backing: `dataBordism_two_torsion_of_revStr_trivial`

13. `synthetic-smith-map-to-tied-carrier` [structural_forcing]
   The Smith map into the 5q.H TIED carrier pinPlusGMTiedData can be built SYNTHETICALLY — map every
   neighbor class [M,σ] to [emptySM, (σ,0)] and transport the grade (the smithDataHom shortcut). FALSE
   (kernel-forced): the tie htie (reduce16to2 grade16 = swTotalNe) forces every tied structure on an EMPTY
   carrier to even grade (gmTiedStr_grade_even_of_isEmpty), so the odd generator grade16 = 1 is
   uninhabitable on emptySM (gmTiedStr_empty_grade16_ne_one) — an odd grade requires a real w₁⁴ = 1
   manifold. The tie that defeats synthetic-grade-ker-bot-nogo simultaneously blocks every synthetic Smith
   map; the geometric Smith map into the tied carrier is irreducibly geometric (N1b).
   backing: `gmTiedStr_grade_even_of_isEmpty`, `gmTiedStr_empty_grade16_ne_one`

14. `5qH-injectivity-routes-all-equal-one-completeness-prop` [structural_forcing]
   The three 5q.H injectivity routes — Thom (hthom: SW-trivial Pin⁺ 4-manifold bounds), KT §5 (hle:
   ker(reduce16to8∘abkGMTied16) ⊆ range(n↦n•g8)), Smith-LES (smith_inflow_z16) — are DISTINCT open nodes
   worth route-shopping between. FALSE (kernel-checked equivalence): all three reduce canonically to the ONE
   completeness prop hbound = grade-0-injectivity on the tied carrier — hbound ⟹ hle
   (spin_range_ge_of_grade0_inj), hthom ⟹ hbound (grade0_bounds_of_thom), and the capstone follows from
   grade-0 alone (omega4PinPlusGMTied_equiv_zmod16_via_kt_of_grade0). Route-shopping or re-deriving "which
   route is closer" is settled-moot; the terminal node is the single geometric completeness input (KT §5
   from-below: N1a+N1b+N1c+N2 per ASSEMBLY_GAP_MAP_20260712).
   backing: `spin_range_ge_of_grade0_inj`, `omega4PinPlusGMTied_equiv_zmod16_via_kt_of_grade0`, `grade0_bounds_of_thom`

15. `5qH-fg-ek-over-Z-blocked` [refutation]
   The mod-2 Erdős–Kaplansky finiteness forcing (SingularUCFinite: self-duality forces finite dimension)
   transports to ℤ — in particular dualization over ℤ stays in the f.g./countable size class, so PD + UCT
   self-duality would force H²(M;ℤ) finitely generated. FALSE: the ℤ-dual of the COUNTABLE free module ℕ →₀
   ℤ is the UNCOUNTABLE, non-f.g. Baer–Specker group ℕ → ℤ (kernel: dual_blowup_not_finite); and the ℤ-EK
   statement itself is refuted in the literature by Specker 1950 — (⊕ℤ) ⊕ ℤ^ℕ is self-dual and not f.g.
   (slenderness of ℤ; Mathlib-absent, formalization queued). Scout-verified vs FNOP arXiv:1910.07372 +
   Blass–Göbel math/9405206; verdict file
   Lit-Search/Phase-5qH/FG_via_PD_duality_forcing_verdict_20260712.md.
   backing: `dual_blowup_not_finite`, `not_finite_baerSpecker`

16. `genuine-gm-carrier-eight-torsion` [refutation]
   The genuine ℤ/16 lives directly on the thin GM carrier: DataBordismGrp(pinPlusGMData) ≃+ ZMod 16. FALSE:
   pinPlusGMData's bordism relation records ONLY the mod-8 Brown grade (q.brown ∈ ZMod 8), so
   cylinder-doubling makes every class 8-torsion (pinPlusGMData_eight_torsion: 8•x=0) ⟹
   IsEmpty(DataBordismGrp(pinPlusGMData) ≃+ ZMod 16). The ℤ/16 odd bit is the Smith-LES EXTENSION onto a
   distinct carrier (the tied/extension carrier, whose mod-8 shadow is abkGM8 via forgetTie), NEVER a
   surface grade on pinPlusGMData itself. Do NOT target `omega4PinPlusGM_equiv_zmod16 :
   DataBordismGrp(pinPlusGMData) ≃+ ZMod 16` as literally stated — reframe to the Smith-LES extension
   carrier (E3) or an enriched (σ,F•F)-carrying GM carrier.
   backing: `pinPlusGMData_not_equiv_zmod16`, `pinPlusGMData_eight_torsion`

17. `enriques-datum-refuted-as-shaped` [structural_forcing]
   EnriquesDatum as shipped carries independent Enriques-geometry content (w₂ ≠ 0, π₁ = ℤ/2, the line
   bundle) usable as the W-D B-leaf. FALSE-AS-SHAPED (gate round 10, G10-6): its [Ha] fields collapse —
   Nonempty (EnriquesDatum prov) ↔ EmptySigmaRepresentable prov (ktKernelRep prov)
   (enriquesDatum_iff_kummerRep), i.e. it is bare KummerWitness.1 in decorative dressing; the "Enriques"
   content has no formal footprint. Do NOT construct or consume EnriquesDatum as an independent B-leaf. The
   frozen replacement B-target is GeometricSpinRepresentable, absorbed by the C-leaf:
   KTSpinPresentationDatum ⟹ EnriquesDatum (enriquesDatum_of_ktSpinPresentationDatum, via
   emptySigmaRepresentable_of_geometric) — discharge the C-leaf and B follows; a standalone "Enriques wave"
   duplicates work into a vacuous shape.
   backing: `enriquesDatum_iff_kummerRep`, `enriquesDatum_of_ktSpinPresentationDatum`, `emptySigmaRepresentable_of_geometric`

18. `geometric-phi-does-not-close-hfwd-fakeability` [structural_forcing]
   Fixing Φ := spinForgetPhi (the geometric forgetful map) in the dA leaf makes hfwd a genuine geometric
   obligation not derivable from the conclusion. FALSE (gate round 11): given the presentation row {hA, hB,
   hg, hdvd, hΦg, h2}, hfwd on the geometric Φ is DERIVABLE from KTNonSplit with zero geometry (R.generates
   writes x = n•[g]; Φx = n•k₀; nonsplit + 2-torsion force n even ⟹ 32 ∣ σ(x)) — the locating iff
   spinForgetPhi_hfwd_iff_ktNonSplit pins hfwd at exactly KTNonSplit strength. Consequence (binding round-11
   spec): NO statement shape closes the dA/hfwd circularity risk — every hfwd/dA discharge claim requires a
   non-circularity audit BY PROOF INSPECTION (the per-instance Div32BoundingDatum supply is equally
   shape-fakeable, round 10 §3). The audit-friendly honest construction target is the kernel
   characterization ker Φ ⊆ doubles (spinForgetPhi_hfwd_of_ker_sub_doubles — hfwd free from Rokhlin on
   doubles, consuming zero k₀ facts).
   backing: `spinForgetPhi_hfwd_of_ktNonSplit`, `spinForgetPhi_hfwd_iff_ktNonSplit`

19. `dual-spin-opened-construction-conclusion-fakeable` [structural_forcing]
   Opening DualSpinFromW into DualSpinConstruction (Vspace/ιV/Vspin/hcob/hcover fields) makes the dual-spin
   supply a genuine geometric obligation not derivable from the conclusion. FALSE (gate round 12): on an
   unpinned ambient, Nonempty (DualSpinConstruction PUnit sigM) ↔ 32 ∣ sigM — every field including hcob
   inhabits from bare arithmetic (the σ-onto realization engine spinOfSigMul16 supplies genuine
   SmoothSpinManifold4 witnesses for every multiple of 16), and modulo the presentation row the whole opened
   supply ⟺ the hfwd conclusion. The mechanism: amb is a FREE TopCat field. Consequence (binding round-12
   spec 1): dA supply claims pass by DATA INSPECTION only — amb must be TopCat.of b.W of the actual tethered
   witness and edge the geometric ∂E(V); statement-shape audits are insufficient at every opening depth.
   backing: `nonempty_dualSpinConstruction_iff_thirtytwo_dvd`, `nonempty_ktSharpnessSupplyConstr_iff_hfwd`, `spinOfSigMul16_sig`

20. `novikov-substrate-synthetic-inhabitation` [structural_forcing]
   The NovikovRealPairLES substrate (or any of the four equivalent σ-descent atom formulations) constitutes
   progress toward the Thom bordism-invariance of σ beyond the bare hbord statement. FALSE (gate round 12):
   the diagonal Lagrangian + synthetic quotient inhabit the substrate with zero geometry whenever σ agrees
   (nonempty_novikovBoundaryRestriction_iff_sig_eq — the Witt step kernel-encoded via
   exists_lagrangian_of_latticeSig_eq_zero), and novikovLagrangian_iff_hbord proves ALL FOUR formulations
   (classical Lagrangian / boundary-restriction half-dim / Lefschetz co-isotropy / the pair-LES substrate)
   are kernel-equivalent to hbord itself. Consequence (binding round-12 spec 2): a Novikov-atom discharge
   must exhibit a GENUINE bounding-W tower (the relative cap + the geometric restriction data of an actual
   bordism witness) — linear-algebra Lagrangian constructions are zero progress at both grades.
   backing: `nonempty_novikovRealPairLES_diag`, `nonempty_novikovBoundaryRestriction_iff_sig_eq`, `novikovLagrangian_iff_hbord`

21. `novikov-geometric-tower-carrier-conclusion-fakeable` [structural_forcing]
   The NovikovGeometricPairLESData field row (the #196 genuine-tower carrier:
   rest2/delta/pairing/hexact/hnondeg/hadjDot) is a stronger-than-conclusion carrier whose inhabitation
   certifies genuine bounding-W tower progress. FALSE (gate round 13): the substrate rebuilds the carrier
   (novikovGeometricPairLESDataOfRealPairLES — pairing := half the substrate pairing, hadjDot DERIVED from
   hadj via the polar-form symmetry), so carrier ⟺ substrate
   (nonempty_novikovGeometricPairLESData_iff_realPairLES), and at block pairs Nonempty (Data (blockDiag A
   (-B))) ↔ σ(A) = σ(B) — the round-12 Witt step + ofLagrangian + the reverse map populate EVERY field from
   a bare Lagrangian with zero bordism geometry. hadjDot moved the fork-20 perimeter; it did not close it.
   Consequence (binding round-13 spec 1): Novikov-lane carrier populations are progress ONLY if
   rest2/delta/pairing are the tensor-R base-changes of the genuine integral tower maps of an actual
   relative cycle — audited by DATA INSPECTION; a quotient-of-coordinate-space H3rel is zero progress by
   construction.
   backing: `novikovGeometricPairLESDataOfRealPairLES`, `nonempty_novikovGeometricPairLESData_iff_realPairLES`, `nonempty_novikovGeometricPairLESData_iff_sig_eq`, `nonempty_novikovGeometricPairLESData_diag`

22. `seam-transfer-open-support-uninhabitable` [refutation]
   The CapstoneSeamTransfer / shared-cSeam CapstoneSeamTransferSeam consumption shape (the #184-#207
   hasClass route: the top-face/disk-boundary splits with OPEN-complement supports hwOut/hvOut plus the
   literal htransfer equality) is inhabitable for a genuine fundamental cycle z and a proper attaching
   region, and the 3x-circled closed-S co-adaptation barrier (#198/#204/#207) is a machinery gap. FALSE (the
   #210 lead adjudication): htransfer FORCES wAtt into the CLOSED attach image (injective-mapDomain support
   transport + fromCyl_image_compl disjointness — wAtt_mem_subspaceChains_range_phi), char-2 boundary
   algebra then forces BOTH split pieces to be CYCLES (boundary_wAtt_eq_zero via
   subspaceChains_inf_compl_eq_bot), so z@top decomposes as a seam-supported cycle + an off-seam cycle;
   whenever the two regions have null 4-cycle classes (H4(S1xD3;Z/2)=0, H4 of an open 4-region = 0 — the
   genuine consumption) and z@top does not bound (z fundamental), the shape is EMPTY
   (isEmpty_capstoneSeamTransfer_of_null + the Seam corollary). Consequence: the transfer route to hasClass
   is dead AS SHIPPED; the honest repair = CLOSED-complement supports (wOut/vOut in the complement of the
   INTERIOR of the attach region — the classical two-rel-pieces-sharing-the-interface picture), a NEW
   gate-pending consumption shape whose interface terms cancel mod 2.
   backing: `wAtt_mem_subspaceChains_range_phi`, `boundary_wAtt_eq_zero`, `isEmpty_capstoneSeamTransfer_of_null`, `isEmpty_capstoneSeamTransferSeam_of_null`

23. `collar-pair-open-complement-annulus-is-refuted-shape` [structural_forcing]
   houtPair (the collar-annulus weld obligation of the #212 collar-pair row) can be discharged for free by
   reading its three required boundary-supports straight off the in-tree SurgeredEndDatum, whose
   d.topFaceCovered (fromCyl '' (topface \ range phi) subset dW), d.sphereFaceCovered (fromHandle '' (sphere
   \ S) subset dW) and bottom-face fact are exactly the three supports hbd_ofTransfer consumes. FALSE
   (structural forcing, 2026-07-21): a collar-annulus refinement at that OPEN-COMPLEMENT granularity, taken
   on top of the row's own hctrlC/hctrlH, CONSTRUCTS a verbatim inhabitant of CapstoneSeamTransferSeam
   (collarAnnulusOpen_toSeamTransferSeam: the seam core absorbs the annulus at cSeam := cCore + ann, cHa :=
   diskDetectChain, and the two residuals are verbatim its wOut/vOut with verbatim its hwOut/hvOut supports)
   -- i.e. the shape refuted by seam-transfer-open-support-uninhabitable. not_collarAnnulusOpen_of_null then
   turns that refinement into False under the identical null/non-bounding hypotheses backing
   isEmpty_capstoneSeamTransferSeam_of_null. So the free-looking SurgeredEndDatum instantiation of houtPair
   is settled-dead. SCOPE (worker-stated, lead-confirmed -- do not overstate): only the ONE direction
   `open-complement refinement ==> refuted structure` is proved. It is NOT proved that every collar-annulus
   refinement is impossible: a refinement at the strictly COARSER closed-complement granularity the #210
   repair adopted (topface \ phi '' K for a shrunk core K) is excluded by nothing here, and
   houtPair_of_bdMem / houtPair_of_bdImageSubset remain its LIVE route. Cite as 'the free-looking
   d.topFaceCovered instantiation is closed', NEVER as 'the collar-annulus refinement is closed'.
   backing: `collarAnnulusOpen_toSeamTransferSeam`, `not_collarAnnulusOpen_of_null`

24. `collar-pair-maximal-core-reenters-refuted-support` [structural_forcing]
   The CollarPairGeom/CollarPairGeomUnsub row's anti-fake tether hcoreHit can be made free of charge by
   enlarging the #210 shrunk core K toward its limit K = univ, keeping the rest of the collar-pair split
   data intact. FALSE (structural forcing, 2026-07-21): at K = univ the tether IS indeed a consequence of
   the top-face split (coreHit_of_univ - cCore lands in subspaceChains of univ-complement = the empty set,
   hence cCore = 0, so z@top = outC), but at K = univ the remainder support collapses to `(univ x {top}) \
   phi '' univ = (univ x {top}) \ range phi` (houtC_support_univ_eq_refuted), which is VERBATIM the
   OPEN-complement signature refuted by seam-transfer-open-support-uninhabitable. So the maximal-core
   shortcut purchases the tether only by re-entering the settled-dead shape, and hcoreHit must remain a
   genuine obligation of the row. SCOPE (lead-corrected, do not overstate): only the direction `K = univ ==>
   tether free AND support refuted` is proved. There is NO uniqueness/converse theorem - a strictly smaller
   K that still discharges hcoreHit is NOT excluded, merely unexplored. Cite this fence as 'the obvious
   maximal-core shortcut is closed', never as 'every hcoreHit shortcut is closed'.
   backing: `coreHit_of_univ`, `houtC_support_univ_eq_refuted`

25. `k7-seam-cover-interior-fails` [refutation]
   K7SeamCoverHyp (the K7 opener's un-thickened MV cover hypothesis): the INTERIORS of the two closed
   Kummer-weld pieces (the Q-image and the 16 closed E-images) cover the welded K3 carrier, so the
   Mayer-Vietoris assembly can run on the un-thickened pieces directly. FALSE (kernel refutation
   k7SeamCoverHyp_false): a seam point (fiberNorm = 1, the glued RP3 locus) is interior to NEITHER piece -
   E-side, every neighbourhood meets fiber radius < 1 (the inward deform path); Q-side, every neighbourhood
   meets the E-exterior along the outward chart ray (via circle_exp_injOn_one ->
   centeredChartParam_injOn_double, chart injectivity on the doubled ball). Consequence: "discharge
   K7SeamCoverHyp" is settled-dead; the UNIQUE route is the collar-thickened cover (qThick = qImage union
   outer half-collars fiberNorm >= 1/2) whose interior-cover hypothesis IS discharged (k7_hcov,
   KummerK7MVAssembly) and through which the whole K7 accounting now runs unconditionally.
   backing: `k7SeamCoverHyp_false`

26. `gram-literal-equality-is-choice-dependent` [structural_forcing]
   SphereProdGramPin - the LITERAL matrix equality `interMatrix fc B = sphereProdFormDatum` on the computed
   rank-2 basis - is a disclosed GEOMETRIC residual of the S2xS2 intersection form, dischargeable once the
   Kunneth/EZ cross value is pinned. FALSE AS FRAMED (structural forcing, 2026-07-21): the exact
   computed-basis Gram is `!![-(2*s*u*eps), u*eps; u*eps, 0]` (sphereProd_interMatrix_computed_eq), so the
   pin holds IFF `s = 0 AND u*eps = 1` (sphereProdGramPin_iff). Neither conjunct is available: (1) `s` is
   the alpha-coordinate of the Exists.choose split generator `deltaGen`, pinned only modulo `sumInto` whose
   fst_* image is NONZERO (sumInto_prodFst) - so `deltaGen |-> deltaGen + k*sumInto 1` shifts `s` by `k` and
   the (0,0) entry by `-2*k*u*eps`, making the Prop INDEPENDENT of the in-tree data, not merely unproven;
   (2) `u`, `eps` are pinned only as units, an orientation/sign gap. Note this also kills the prior hope
   that normalizing the cross value to literally 1 would suffice - a normalized eps still leaves the
   diagonal free. The GEOMETRIC content the pin stood in for IS in tree and unconditional:
   SphereProdBasisIdInt.sphereProd_interMatrix_intCongr_hyp proves II(S2xS2) integrally CONGRUENT to Hyp
   itself. Every consumer conclusion is congruence-invariant, so the congruence supersedes the equality;
   hypothesis-free replacements are
   SphereProdGramPinRetire.sphereProd_s2s2_{hyp,evenUnimodular,latticeSig,htopo}'. GENERAL RULE (applies to
   every Gram atom incl. the K3/T4 one): state Gram targets as `IntCongr ... <form>`, NEVER as a literal
   matrix equality on a chosen basis - the extra content of an equality over a congruence is basis
   normalization, not geometry, and is generically unreachable whenever any basis vector comes from a
   choice.
   backing: `sphereProd_interMatrix_computed_eq`, `sphereProdGramPin_iff`

-/
import SKEFTHawking.FGDualityNoGo
import SKEFTHawking.KummerK7SeamCoverNoGo
import SKEFTHawking.NonHausdorffBordismCollapse
import SKEFTHawking.PinPlusCharPairFlipGate
import SKEFTHawking.PinPlusCharPairGeoRealizationGate
import SKEFTHawking.PinPlusCompTorsorNoGo
import SKEFTHawking.PinPlusGMDataZ16
import SKEFTHawking.PinPlusGMWitness
import SKEFTHawking.PinPlusGenuineCarrierIso
import SKEFTHawking.PinPlusKTLeafGate
import SKEFTHawking.PinPlusKTStepGate
import SKEFTHawking.PinPlusKTVacuityGateWD
import SKEFTHawking.PinPlusResidualGate
import SKEFTHawking.PinPlusRoundThirteenGate
import SKEFTHawking.PinPlusTaylorConventionNoGo
import SKEFTHawking.PinPlusTraceCapstoneCollarPairCore
import SKEFTHawking.PinPlusTraceCapstoneCollarPairGeom
import SKEFTHawking.PinPlusTraceLeafGate
import SKEFTHawking.PinPlusTraceSeamTransferNoGo
import SKEFTHawking.RokhlinArfNoGo
import SKEFTHawking.SphereProdGramPinRetire
import SKEFTHawking.SyntheticSmithNoGo
import SKEFTHawking.UnorientedThomCapstone

namespace SKEFTHawking.KernelNoGos

/-- NO-GO [`nonhausdorff-bordism-collapse`] — do NOT re-derive. FALSE: The in-tree `Bordism` relation (BordismGroup.lean:37-42) is a faithful bordism theory usable for a completeness/injectivity/bounding Prop. Backing refutation: `SKEFTHawking.NonHausdorffBordismCollapse.bordismGrp_subsingleton`. -/
alias nogo_bordismGrp_subsingleton := SKEFTHawking.NonHausdorffBordismCollapse.bordismGrp_subsingleton

/-- NO-GO [`nonhausdorff-bordism-collapse`] — do NOT re-derive. FALSE: The in-tree `Bordism` relation (BordismGroup.lean:37-42) is a faithful bordism theory usable for a completeness/injectivity/bounding Prop. Backing refutation: `SKEFTHawking.NonHausdorffBordismCollapse.bordismGrp_rp4_eq_zero`. -/
alias nogo_bordismGrp_rp4_eq_zero := SKEFTHawking.NonHausdorffBordismCollapse.bordismGrp_rp4_eq_zero

/-- NO-GO [`nonhausdorff-bordism-collapse`] — do NOT re-derive. FALSE: The in-tree `Bordism` relation (BordismGroup.lean:37-42) is a faithful bordism theory usable for a completeness/injectivity/bounding Prop. Backing refutation: `SKEFTHawking.NonHausdorffBordismCollapse.dataBordismGMTied_mk_eq_iff_grade16_eq`. -/
alias nogo_dataBordismGMTied_mk_eq_iff_grade16_eq := SKEFTHawking.NonHausdorffBordismCollapse.dataBordismGMTied_mk_eq_iff_grade16_eq

/-- NO-GO [`comp-twist-doubling-incompatible`] — do NOT re-derive. FALSE: A tangential datum can carry an H¹-coordinate field `comp` with reversal twist `comp ↦ comp + w₁` (the P ↦ P⊗ε coordinate), anchored by a restriction-compatibility Bor condition. Backing refutation: `SKEFTHawking.PinPlusCompTorsorNoGo.no_comp_twist_of_doubling_rigid`. -/
alias nogo_no_comp_twist_of_doubling_rigid := SKEFTHawking.PinPlusCompTorsorNoGo.no_comp_twist_of_doubling_rigid

/-- NO-GO [`comp-twist-doubling-incompatible`] — do NOT re-derive. FALSE: A tangential datum can carry an H¹-coordinate field `comp` with reversal twist `comp ↦ comp + w₁` (the P ↦ P⊗ε coordinate), anchored by a restriction-compatibility Bor condition. Backing refutation: `SKEFTHawking.PinPlusCompTorsorNoGo.not_doubling_rigid_of_comp_twist`. -/
alias nogo_not_doubling_rigid_of_comp_twist := SKEFTHawking.PinPlusCompTorsorNoGo.not_doubling_rigid_of_comp_twist

/-- NO-GO [`comp-twist-doubling-incompatible`] — do NOT re-derive. FALSE: A tangential datum can carry an H¹-coordinate field `comp` with reversal twist `comp ↦ comp + w₁` (the P ↦ P⊗ε coordinate), anchored by a restriction-compatibility Bor condition. Backing refutation: `SKEFTHawking.PinPlusCompTorsorNoGo.no_uniform_comp_twist_of_cylinder_rigid`. -/
alias nogo_no_uniform_comp_twist_of_cylinder_rigid := SKEFTHawking.PinPlusCompTorsorNoGo.no_uniform_comp_twist_of_cylinder_rigid

/-- NO-GO [`membrane-level-nonhausdorff-collapse`] — do NOT re-derive. FALSE: A manifold-typed WITNESS datum inside a carrier or relation (the membrane/3-manifold Q, the surface Σ, any auxiliary manifold field) inherits honesty from the T2 fence on the ambient bordism W. Backing refutation: `SKEFTHawking.PinPlusCompTorsorNoGo.qLevelTripleMembrane_not_t2`. -/
alias nogo_qLevelTripleMembrane_not_t2 := SKEFTHawking.PinPlusCompTorsorNoGo.qLevelTripleMembrane_not_t2

/-- NO-GO [`free-membrane-kernel-kills-nonsplit`] — do NOT re-derive. FALSE: The as-built CharPair carrier (Bor with the membrane kernel L carried as a FREE Submodule field, the geometric membrane Q deferred) supports the KT §5 non-split content — KTNonSplit (8•[ℝP⁴] ≠ 0) is open/dischargeable on it. Backing refutation: `SKEFTHawking.PinPlusKTVacuityGateWD.L44_metabolic`. -/
alias nogo_L44_metabolic := SKEFTHawking.PinPlusKTVacuityGateWD.L44_metabolic

/-- NO-GO [`free-membrane-kernel-kills-nonsplit`] — do NOT re-derive. FALSE: The as-built CharPair carrier (Bor with the membrane kernel L carried as a FREE Submodule field, the geometric membrane Q deferred) supports the KT §5 non-split content — KTNonSplit (8•[ℝP⁴] ≠ 0) is open/dischargeable on it. Backing refutation: `SKEFTHawking.PinPlusKTVacuityGateWD.doubleKillerBInc_ker`. -/
alias nogo_doubleKillerBInc_ker := SKEFTHawking.PinPlusKTVacuityGateWD.doubleKillerBInc_ker

/-- NO-GO [`tied-carrier-inhabitation-equiv-free`] — do NOT re-derive. FALSE: The membrane-tied CharPairBorTied (L = ker mem.bInc) is a strictly finer bordism-witness class than the refuted free-L CharPairBor — the tie alone filters geometrically-unrealizable Lagrangians. Backing refutation: `SKEFTHawking.PinPlusCharPairGeoRealizationGate.charPairBorTied_nonempty_iff_free`. -/
alias nogo_charPairBorTied_nonempty_iff_free := SKEFTHawking.PinPlusCharPairGeoRealizationGate.charPairBorTied_nonempty_iff_free

/-- NO-GO [`tied-carrier-inhabitation-equiv-free`] — do NOT re-derive. FALSE: The membrane-tied CharPairBorTied (L = ker mem.bInc) is a strictly finer bordism-witness class than the refuted free-L CharPairBor — the tie alone filters geometrically-unrealizable Lagrangians. Backing refutation: `SKEFTHawking.PinPlusCharPairGeoRealizationGate.jointLagrangian_top`. -/
alias nogo_jointLagrangian_top := SKEFTHawking.PinPlusCharPairGeoRealizationGate.jointLagrangian_top

/-- NO-GO [`realization-seam-basis-gauge-launders-e8`] — do NOT re-derive. FALSE: Topological certificates on GeoRealizationData (T2, compactness, closed-embedding ι, dimension, membrane-in-W) suffice to make GeoMembrane.ofGeometric honest — a fully-certified realization cannot carry the e₈ kernel. Backing refutation: `SKEFTHawking.PinPlusCharPairGeoRealizationGate.map_killerGauge_ker_negBorBInc`. -/
alias nogo_map_killerGauge_ker_negBorBInc := SKEFTHawking.PinPlusCharPairGeoRealizationGate.map_killerGauge_ker_negBorBInc

/-- NO-GO [`realization-seam-basis-gauge-launders-e8`] — do NOT re-derive. FALSE: Topological certificates on GeoRealizationData (T2, compactness, closed-embedding ι, dimension, membrane-in-W) suffice to make GeoMembrane.ofGeometric honest — a fully-certified realization cannot carry the e₈ kernel. Backing refutation: `SKEFTHawking.PinPlusCharPairGeoRealizationGate.ker_transportedBInc_gaugeσ`. -/
alias nogo_ker_transportedBInc_gaugeσ := SKEFTHawking.PinPlusCharPairGeoRealizationGate.ker_transportedBInc_gaugeσ

/-- NO-GO [`realization-seam-basis-gauge-launders-e8`] — do NOT re-derive. FALSE: Topological certificates on GeoRealizationData (T2, compactness, closed-embedding ι, dimension, membrane-in-W) suffice to make GeoMembrane.ofGeometric honest — a fully-certified realization cannot carry the e₈ kernel. Backing refutation: `SKEFTHawking.PinPlusCharPairGeoRealizationGate.doubleKillerGeoMem_L`. -/
alias nogo_doubleKillerGeoMem_L := SKEFTHawking.PinPlusCharPairGeoRealizationGate.doubleKillerGeoMem_L

/-- NO-GO [`realization-seam-basis-gauge-launders-e8`] — do NOT re-derive. FALSE: Topological certificates on GeoRealizationData (T2, compactness, closed-embedding ι, dimension, membrane-in-W) suffice to make GeoMembrane.ofGeometric honest — a fully-certified realization cannot carry the e₈ kernel. Backing refutation: `SKEFTHawking.PinPlusCharPairGeoRealizationGate.map_blockCongr_cylLagrangian`. -/
alias nogo_map_blockCongr_cylLagrangian := SKEFTHawking.PinPlusCharPairGeoRealizationGate.map_blockCongr_cylLagrangian

/-- NO-GO [`wadm-sqop-gauge-w2-filter-vacuous`] — do NOT re-derive. FALSE: WAdm/hwu (wuW2 P14 P23 = 0) is a w₂(W) = 0 filter — discharging a CharPairWProvider certifies genuine Pin⁺-admissibility of the bordisms it covers. Backing refutation: `SKEFTHawking.PinPlusCharPairGeoRealizationGate.wuW2_zeroSq`. -/
alias nogo_wuW2_zeroSq := SKEFTHawking.PinPlusCharPairGeoRealizationGate.wuW2_zeroSq

/-- NO-GO [`wadm-sqop-gauge-w2-filter-vacuous`] — do NOT re-derive. FALSE: WAdm/hwu (wuW2 P14 P23 = 0) is a w₂(W) = 0 filter — discharging a CharPairWProvider certifies genuine Pin⁺-admissibility of the bordisms it covers. Backing refutation: `SKEFTHawking.PinPlusCharPairGeoRealizationGate.wuClass_zeroSq`. -/
alias nogo_wuClass_zeroSq := SKEFTHawking.PinPlusCharPairGeoRealizationGate.wuClass_zeroSq

/-- NO-GO [`taylor-leg-end-convention-trap`] — do NOT re-derive. FALSE: The structured-bordism Taylor extension leg ('boundary classes bounding in the membrane Q have vanishing enhancement') can be stated as a PLAIN joint sum q_σ ⊕ q_τ, or σ-side-only, vanishing on ker(H₁(∂Q)→H₁(Q)). Backing refutation: `SKEFTHawking.PinPlusTaylorConventionNoGo.no_plain_end_pairing_of_cylinder`. -/
alias nogo_no_plain_end_pairing_of_cylinder := SKEFTHawking.PinPlusTaylorConventionNoGo.no_plain_end_pairing_of_cylinder

/-- NO-GO [`taylor-leg-end-convention-trap`] — do NOT re-derive. FALSE: The structured-bordism Taylor extension leg ('boundary classes bounding in the membrane Q have vanishing enhancement') can be stated as a PLAIN joint sum q_σ ⊕ q_τ, or σ-side-only, vanishing on ker(H₁(∂Q)→H₁(Q)). Backing refutation: `SKEFTHawking.PinPlusTaylorConventionNoGo.not_cylinder_plain_pairing_of_odd_value`. -/
alias nogo_not_cylinder_plain_pairing_of_odd_value := SKEFTHawking.PinPlusTaylorConventionNoGo.not_cylinder_plain_pairing_of_odd_value

/-- NO-GO [`taylor-leg-end-convention-trap`] — do NOT re-derive. FALSE: The structured-bordism Taylor extension leg ('boundary classes bounding in the membrane Q have vanishing enhancement') can be stated as a PLAIN joint sum q_σ ⊕ q_τ, or σ-side-only, vanishing on ker(H₁(∂Q)→H₁(Q)). Backing refutation: `SKEFTHawking.PinPlusTaylorConventionNoGo.not_cylinder_bor_of_invariant_ne`. -/
alias nogo_not_cylinder_bor_of_invariant_ne := SKEFTHawking.PinPlusTaylorConventionNoGo.not_cylinder_bor_of_invariant_ne

/-- NO-GO [`untethered-membrane-factors-relation`] — do NOT re-derive. FALSE: The flipped carrier (Bor = CharPairBorRealized: GeoRealizationTied with derived bases + computed kernels + pinned provider) supports the KT non-split content — the abstract compact-T2 membrane suffices; no explicit tether of the realization's Q to the bordism's W is needed. Backing refutation: `SKEFTHawking.PinPlusCharPairFlipGate.isT2DataBordant_pinPlusCharPair_factors`. -/
alias nogo_isT2DataBordant_pinPlusCharPair_factors := SKEFTHawking.PinPlusCharPairFlipGate.isT2DataBordant_pinPlusCharPair_factors

/-- NO-GO [`untethered-membrane-factors-relation`] — do NOT re-derive. FALSE: The flipped carrier (Bor = CharPairBorRealized: GeoRealizationTied with derived bases + computed kernels + pinned provider) supports the KT non-split content — the abstract compact-T2 membrane suffices; no explicit tether of the realization's Q to the bordism's W is needed. Backing refutation: `SKEFTHawking.PinPlusCharPairFlipGate.ktNonSplit_false_of_e8`. -/
alias nogo_ktNonSplit_false_of_e8 := SKEFTHawking.PinPlusCharPairFlipGate.ktNonSplit_false_of_e8

/-- NO-GO [`nogo_lattice_arf_not_sigma8`] — do NOT re-derive. FALSE: The lattice Arf bridge σ/8 ≡ Arf(q̄) mod 2 — deriving Rokhlin mod-16 from the intersection FORM alone. Backing refutation: `SKEFTHawking.RokhlinArfNoGo.lattice_arf_bridge_refuted`. -/
alias nogo_lattice_arf_bridge_refuted := SKEFTHawking.RokhlinArfNoGo.lattice_arf_bridge_refuted

/-- NO-GO [`mfd-equals-H1-dead-end`] — do NOT re-derive. FALSE: The `Mfd := H¹` tangential-data construction yields a genuine ℤ/16 / ker=⊥. Backing refutation: `SKEFTHawking.PinPlusGenuineCarrierIso.dataBordism_two_torsion_of_revStr_trivial`. -/
alias nogo_dataBordism_two_torsion_of_revStr_trivial := SKEFTHawking.PinPlusGenuineCarrierIso.dataBordism_two_torsion_of_revStr_trivial

/-- NO-GO [`synthetic-grade-ker-bot-nogo`] — do NOT re-derive. FALSE: ker(abkGrade)=⊥ / card≤16 UNCONDITIONALLY for ANY free-per-manifold grade. Backing refutation: `SKEFTHawking.PinPlusGenuineCarrierIso.dataBordism_two_torsion_of_revStr_trivial`. -/
alias nogo_dataBordism_two_torsion_of_revStr_trivial_2 := SKEFTHawking.PinPlusGenuineCarrierIso.dataBordism_two_torsion_of_revStr_trivial

/-- NO-GO [`synthetic-smith-map-to-tied-carrier`] — do NOT re-derive. FALSE: The Smith map into the 5q.H TIED carrier pinPlusGMTiedData can be built SYNTHETICALLY — map every neighbor class [M,σ] to [emptySM, (σ,0)] and transport the grade (the smithDataHom shortcut). Backing refutation: `SKEFTHawking.PinPlusGMTiedData.gmTiedStr_grade_even_of_isEmpty`. -/
alias nogo_gmTiedStr_grade_even_of_isEmpty := SKEFTHawking.PinPlusGMTiedData.gmTiedStr_grade_even_of_isEmpty

/-- NO-GO [`synthetic-smith-map-to-tied-carrier`] — do NOT re-derive. FALSE: The Smith map into the 5q.H TIED carrier pinPlusGMTiedData can be built SYNTHETICALLY — map every neighbor class [M,σ] to [emptySM, (σ,0)] and transport the grade (the smithDataHom shortcut). Backing refutation: `SKEFTHawking.PinPlusGMTiedData.gmTiedStr_empty_grade16_ne_one`. -/
alias nogo_gmTiedStr_empty_grade16_ne_one := SKEFTHawking.PinPlusGMTiedData.gmTiedStr_empty_grade16_ne_one

/-- NO-GO [`5qH-injectivity-routes-all-equal-one-completeness-prop`] — do NOT re-derive. FALSE: The three 5q.H injectivity routes — Thom (hthom: SW-trivial Pin⁺ 4-manifold bounds), KT §5 (hle: ker(reduce16to8∘abkGMTied16) ⊆ range(n↦n•g8)), Smith-LES (smith_inflow_z16) — are DISTINCT open nodes worth route-shopping between. Backing refutation: `SKEFTHawking.PinPlusGMWitness.spin_range_ge_of_grade0_inj`. -/
alias nogo_spin_range_ge_of_grade0_inj := SKEFTHawking.PinPlusGMWitness.spin_range_ge_of_grade0_inj

/-- NO-GO [`5qH-injectivity-routes-all-equal-one-completeness-prop`] — do NOT re-derive. FALSE: The three 5q.H injectivity routes — Thom (hthom: SW-trivial Pin⁺ 4-manifold bounds), KT §5 (hle: ker(reduce16to8∘abkGMTied16) ⊆ range(n↦n•g8)), Smith-LES (smith_inflow_z16) — are DISTINCT open nodes worth route-shopping between. Backing refutation: `SKEFTHawking.PinPlusGMWitness.omega4PinPlusGMTied_equiv_zmod16_via_kt_of_grade0`. -/
alias nogo_omega4PinPlusGMTied_equiv_zmod16_via_kt_of_grade0 := SKEFTHawking.PinPlusGMWitness.omega4PinPlusGMTied_equiv_zmod16_via_kt_of_grade0

/-- NO-GO [`5qH-injectivity-routes-all-equal-one-completeness-prop`] — do NOT re-derive. FALSE: The three 5q.H injectivity routes — Thom (hthom: SW-trivial Pin⁺ 4-manifold bounds), KT §5 (hle: ker(reduce16to8∘abkGMTied16) ⊆ range(n↦n•g8)), Smith-LES (smith_inflow_z16) — are DISTINCT open nodes worth route-shopping between. Backing refutation: `SKEFTHawking.UnorientedThomCapstone.grade0_bounds_of_thom`. -/
alias nogo_grade0_bounds_of_thom := SKEFTHawking.UnorientedThomCapstone.grade0_bounds_of_thom

/-- NO-GO [`5qH-fg-ek-over-Z-blocked`] — do NOT re-derive. FALSE: The mod-2 Erdős–Kaplansky finiteness forcing (SingularUCFinite: self-duality forces finite dimension) transports to ℤ — in particular dualization over ℤ stays in the f.g./countable size class, so PD + UCT self-duality would force H²(M;ℤ) finitely generated. Backing refutation: `SKEFTHawking.FGDualityNoGo.dual_blowup_not_finite`. -/
alias nogo_dual_blowup_not_finite := SKEFTHawking.FGDualityNoGo.dual_blowup_not_finite

/-- NO-GO [`5qH-fg-ek-over-Z-blocked`] — do NOT re-derive. FALSE: The mod-2 Erdős–Kaplansky finiteness forcing (SingularUCFinite: self-duality forces finite dimension) transports to ℤ — in particular dualization over ℤ stays in the f.g./countable size class, so PD + UCT self-duality would force H²(M;ℤ) finitely generated. Backing refutation: `SKEFTHawking.FGDualityNoGo.not_finite_baerSpecker`. -/
alias nogo_not_finite_baerSpecker := SKEFTHawking.FGDualityNoGo.not_finite_baerSpecker

/-- NO-GO [`genuine-gm-carrier-eight-torsion`] — do NOT re-derive. FALSE: The genuine ℤ/16 lives directly on the thin GM carrier: DataBordismGrp(pinPlusGMData) ≃+ ZMod 16. Backing refutation: `SKEFTHawking.PinPlusGMDataZ16.pinPlusGMData_not_equiv_zmod16`. -/
alias nogo_pinPlusGMData_not_equiv_zmod16 := SKEFTHawking.PinPlusGMDataZ16.pinPlusGMData_not_equiv_zmod16

/-- NO-GO [`genuine-gm-carrier-eight-torsion`] — do NOT re-derive. FALSE: The genuine ℤ/16 lives directly on the thin GM carrier: DataBordismGrp(pinPlusGMData) ≃+ ZMod 16. Backing refutation: `SKEFTHawking.PinPlusGMDataZ16.pinPlusGMData_eight_torsion`. -/
alias nogo_pinPlusGMData_eight_torsion := SKEFTHawking.PinPlusGMDataZ16.pinPlusGMData_eight_torsion

/-- NO-GO [`enriques-datum-refuted-as-shaped`] — do NOT re-derive. FALSE: EnriquesDatum as shipped carries independent Enriques-geometry content (w₂ ≠ 0, π₁ = ℤ/2, the line bundle) usable as the W-D B-leaf. Backing refutation: `SKEFTHawking.PinPlusKTLeafGate.enriquesDatum_iff_kummerRep`. -/
alias nogo_enriquesDatum_iff_kummerRep := SKEFTHawking.PinPlusKTLeafGate.enriquesDatum_iff_kummerRep

/-- NO-GO [`enriques-datum-refuted-as-shaped`] — do NOT re-derive. FALSE: EnriquesDatum as shipped carries independent Enriques-geometry content (w₂ ≠ 0, π₁ = ℤ/2, the line bundle) usable as the W-D B-leaf. Backing refutation: `SKEFTHawking.PinPlusKTLeafGate.enriquesDatum_of_ktSpinPresentationDatum`. -/
alias nogo_enriquesDatum_of_ktSpinPresentationDatum := SKEFTHawking.PinPlusKTLeafGate.enriquesDatum_of_ktSpinPresentationDatum

/-- NO-GO [`enriques-datum-refuted-as-shaped`] — do NOT re-derive. FALSE: EnriquesDatum as shipped carries independent Enriques-geometry content (w₂ ≠ 0, π₁ = ℤ/2, the line bundle) usable as the W-D B-leaf. Backing refutation: `SKEFTHawking.PinPlusKTStepGate.emptySigmaRepresentable_of_geometric`. -/
alias nogo_emptySigmaRepresentable_of_geometric := SKEFTHawking.PinPlusKTStepGate.emptySigmaRepresentable_of_geometric

/-- NO-GO [`geometric-phi-does-not-close-hfwd-fakeability`] — do NOT re-derive. FALSE: Fixing Φ := spinForgetPhi (the geometric forgetful map) in the dA leaf makes hfwd a genuine geometric obligation not derivable from the conclusion. Backing refutation: `SKEFTHawking.PinPlusTraceLeafGate.spinForgetPhi_hfwd_of_ktNonSplit`. -/
alias nogo_spinForgetPhi_hfwd_of_ktNonSplit := SKEFTHawking.PinPlusTraceLeafGate.spinForgetPhi_hfwd_of_ktNonSplit

/-- NO-GO [`geometric-phi-does-not-close-hfwd-fakeability`] — do NOT re-derive. FALSE: Fixing Φ := spinForgetPhi (the geometric forgetful map) in the dA leaf makes hfwd a genuine geometric obligation not derivable from the conclusion. Backing refutation: `SKEFTHawking.PinPlusTraceLeafGate.spinForgetPhi_hfwd_iff_ktNonSplit`. -/
alias nogo_spinForgetPhi_hfwd_iff_ktNonSplit := SKEFTHawking.PinPlusTraceLeafGate.spinForgetPhi_hfwd_iff_ktNonSplit

/-- NO-GO [`dual-spin-opened-construction-conclusion-fakeable`] — do NOT re-derive. FALSE: Opening DualSpinFromW into DualSpinConstruction (Vspace/ιV/Vspin/hcob/hcover fields) makes the dual-spin supply a genuine geometric obligation not derivable from the conclusion. Backing refutation: `SKEFTHawking.PinPlusResidualGate.nonempty_dualSpinConstruction_iff_thirtytwo_dvd`. -/
alias nogo_nonempty_dualSpinConstruction_iff_thirtytwo_dvd := SKEFTHawking.PinPlusResidualGate.nonempty_dualSpinConstruction_iff_thirtytwo_dvd

/-- NO-GO [`dual-spin-opened-construction-conclusion-fakeable`] — do NOT re-derive. FALSE: Opening DualSpinFromW into DualSpinConstruction (Vspace/ιV/Vspin/hcob/hcover fields) makes the dual-spin supply a genuine geometric obligation not derivable from the conclusion. Backing refutation: `SKEFTHawking.PinPlusResidualGate.nonempty_ktSharpnessSupplyConstr_iff_hfwd`. -/
alias nogo_nonempty_ktSharpnessSupplyConstr_iff_hfwd := SKEFTHawking.PinPlusResidualGate.nonempty_ktSharpnessSupplyConstr_iff_hfwd

/-- NO-GO [`dual-spin-opened-construction-conclusion-fakeable`] — do NOT re-derive. FALSE: Opening DualSpinFromW into DualSpinConstruction (Vspace/ιV/Vspin/hcob/hcover fields) makes the dual-spin supply a genuine geometric obligation not derivable from the conclusion. Backing refutation: `SKEFTHawking.PinPlusResidualGate.spinOfSigMul16_sig`. -/
alias nogo_spinOfSigMul16_sig := SKEFTHawking.PinPlusResidualGate.spinOfSigMul16_sig

/-- NO-GO [`novikov-substrate-synthetic-inhabitation`] — do NOT re-derive. FALSE: The NovikovRealPairLES substrate (or any of the four equivalent σ-descent atom formulations) constitutes progress toward the Thom bordism-invariance of σ beyond the bare hbord statement. Backing refutation: `SKEFTHawking.PinPlusResidualGate.nonempty_novikovRealPairLES_diag`. -/
alias nogo_nonempty_novikovRealPairLES_diag := SKEFTHawking.PinPlusResidualGate.nonempty_novikovRealPairLES_diag

/-- NO-GO [`novikov-substrate-synthetic-inhabitation`] — do NOT re-derive. FALSE: The NovikovRealPairLES substrate (or any of the four equivalent σ-descent atom formulations) constitutes progress toward the Thom bordism-invariance of σ beyond the bare hbord statement. Backing refutation: `SKEFTHawking.PinPlusResidualGate.nonempty_novikovBoundaryRestriction_iff_sig_eq`. -/
alias nogo_nonempty_novikovBoundaryRestriction_iff_sig_eq := SKEFTHawking.PinPlusResidualGate.nonempty_novikovBoundaryRestriction_iff_sig_eq

/-- NO-GO [`novikov-substrate-synthetic-inhabitation`] — do NOT re-derive. FALSE: The NovikovRealPairLES substrate (or any of the four equivalent σ-descent atom formulations) constitutes progress toward the Thom bordism-invariance of σ beyond the bare hbord statement. Backing refutation: `SKEFTHawking.PinPlusResidualGate.novikovLagrangian_iff_hbord`. -/
alias nogo_novikovLagrangian_iff_hbord := SKEFTHawking.PinPlusResidualGate.novikovLagrangian_iff_hbord

/-- NO-GO [`novikov-geometric-tower-carrier-conclusion-fakeable`] — do NOT re-derive. FALSE: The NovikovGeometricPairLESData field row (the #196 genuine-tower carrier: rest2/delta/pairing/hexact/hnondeg/hadjDot) is a stronger-than-conclusion carrier whose inhabitation certifies genuine bounding-W tower progress. Backing refutation: `SKEFTHawking.PinPlusRoundThirteenGate.novikovGeometricPairLESDataOfRealPairLES`. -/
alias nogo_novikovGeometricPairLESDataOfRealPairLES := SKEFTHawking.PinPlusRoundThirteenGate.novikovGeometricPairLESDataOfRealPairLES

/-- NO-GO [`novikov-geometric-tower-carrier-conclusion-fakeable`] — do NOT re-derive. FALSE: The NovikovGeometricPairLESData field row (the #196 genuine-tower carrier: rest2/delta/pairing/hexact/hnondeg/hadjDot) is a stronger-than-conclusion carrier whose inhabitation certifies genuine bounding-W tower progress. Backing refutation: `SKEFTHawking.PinPlusRoundThirteenGate.nonempty_novikovGeometricPairLESData_iff_realPairLES`. -/
alias nogo_nonempty_novikovGeometricPairLESData_iff_realPairLES := SKEFTHawking.PinPlusRoundThirteenGate.nonempty_novikovGeometricPairLESData_iff_realPairLES

/-- NO-GO [`novikov-geometric-tower-carrier-conclusion-fakeable`] — do NOT re-derive. FALSE: The NovikovGeometricPairLESData field row (the #196 genuine-tower carrier: rest2/delta/pairing/hexact/hnondeg/hadjDot) is a stronger-than-conclusion carrier whose inhabitation certifies genuine bounding-W tower progress. Backing refutation: `SKEFTHawking.PinPlusRoundThirteenGate.nonempty_novikovGeometricPairLESData_iff_sig_eq`. -/
alias nogo_nonempty_novikovGeometricPairLESData_iff_sig_eq := SKEFTHawking.PinPlusRoundThirteenGate.nonempty_novikovGeometricPairLESData_iff_sig_eq

/-- NO-GO [`novikov-geometric-tower-carrier-conclusion-fakeable`] — do NOT re-derive. FALSE: The NovikovGeometricPairLESData field row (the #196 genuine-tower carrier: rest2/delta/pairing/hexact/hnondeg/hadjDot) is a stronger-than-conclusion carrier whose inhabitation certifies genuine bounding-W tower progress. Backing refutation: `SKEFTHawking.PinPlusRoundThirteenGate.nonempty_novikovGeometricPairLESData_diag`. -/
alias nogo_nonempty_novikovGeometricPairLESData_diag := SKEFTHawking.PinPlusRoundThirteenGate.nonempty_novikovGeometricPairLESData_diag

/-- NO-GO [`seam-transfer-open-support-uninhabitable`] — do NOT re-derive. FALSE: The CapstoneSeamTransfer / shared-cSeam CapstoneSeamTransferSeam consumption shape (the #184-#207 hasClass route: the top-face/disk-boundary splits with OPEN-complement supports hwOut/hvOut plus the literal htransfer equality) is inhabitable for a genuine fundamental cycle z and a proper attaching region, and the 3x-circled closed-S co-adaptation barrier (#198/#204/#207) is a machinery gap. Backing refutation: `SKEFTHawking.PinPlusTraceSeamTransferNoGo.wAtt_mem_subspaceChains_range_phi`. -/
alias nogo_wAtt_mem_subspaceChains_range_phi := SKEFTHawking.PinPlusTraceSeamTransferNoGo.wAtt_mem_subspaceChains_range_phi

/-- NO-GO [`seam-transfer-open-support-uninhabitable`] — do NOT re-derive. FALSE: The CapstoneSeamTransfer / shared-cSeam CapstoneSeamTransferSeam consumption shape (the #184-#207 hasClass route: the top-face/disk-boundary splits with OPEN-complement supports hwOut/hvOut plus the literal htransfer equality) is inhabitable for a genuine fundamental cycle z and a proper attaching region, and the 3x-circled closed-S co-adaptation barrier (#198/#204/#207) is a machinery gap. Backing refutation: `SKEFTHawking.PinPlusTraceSeamTransferNoGo.boundary_wAtt_eq_zero`. -/
alias nogo_boundary_wAtt_eq_zero := SKEFTHawking.PinPlusTraceSeamTransferNoGo.boundary_wAtt_eq_zero

/-- NO-GO [`seam-transfer-open-support-uninhabitable`] — do NOT re-derive. FALSE: The CapstoneSeamTransfer / shared-cSeam CapstoneSeamTransferSeam consumption shape (the #184-#207 hasClass route: the top-face/disk-boundary splits with OPEN-complement supports hwOut/hvOut plus the literal htransfer equality) is inhabitable for a genuine fundamental cycle z and a proper attaching region, and the 3x-circled closed-S co-adaptation barrier (#198/#204/#207) is a machinery gap. Backing refutation: `SKEFTHawking.PinPlusTraceSeamTransferNoGo.isEmpty_capstoneSeamTransfer_of_null`. -/
alias nogo_isEmpty_capstoneSeamTransfer_of_null := SKEFTHawking.PinPlusTraceSeamTransferNoGo.isEmpty_capstoneSeamTransfer_of_null

/-- NO-GO [`seam-transfer-open-support-uninhabitable`] — do NOT re-derive. FALSE: The CapstoneSeamTransfer / shared-cSeam CapstoneSeamTransferSeam consumption shape (the #184-#207 hasClass route: the top-face/disk-boundary splits with OPEN-complement supports hwOut/hvOut plus the literal htransfer equality) is inhabitable for a genuine fundamental cycle z and a proper attaching region, and the 3x-circled closed-S co-adaptation barrier (#198/#204/#207) is a machinery gap. Backing refutation: `SKEFTHawking.PinPlusTraceSeamTransferNoGo.isEmpty_capstoneSeamTransferSeam_of_null`. -/
alias nogo_isEmpty_capstoneSeamTransferSeam_of_null := SKEFTHawking.PinPlusTraceSeamTransferNoGo.isEmpty_capstoneSeamTransferSeam_of_null

/-- NO-GO [`collar-pair-open-complement-annulus-is-refuted-shape`] — do NOT re-derive. FALSE: houtPair (the collar-annulus weld obligation of the #212 collar-pair row) can be discharged for free by reading its three required boundary-supports straight off the in-tree SurgeredEndDatum, whose d.topFaceCovered (fromCyl '' (topface \ range phi) subset dW), d.sphereFaceCovered (fromHandle '' (sphere \ S) subset dW) and bottom-face fact are exactly the three supports hbd_ofTransfer consumes. Backing refutation: `SKEFTHawking.PinPlusTraceCapstoneCollarPairCore.collarAnnulusOpen_toSeamTransferSeam`. -/
alias nogo_collarAnnulusOpen_toSeamTransferSeam := SKEFTHawking.PinPlusTraceCapstoneCollarPairCore.collarAnnulusOpen_toSeamTransferSeam

/-- NO-GO [`collar-pair-open-complement-annulus-is-refuted-shape`] — do NOT re-derive. FALSE: houtPair (the collar-annulus weld obligation of the #212 collar-pair row) can be discharged for free by reading its three required boundary-supports straight off the in-tree SurgeredEndDatum, whose d.topFaceCovered (fromCyl '' (topface \ range phi) subset dW), d.sphereFaceCovered (fromHandle '' (sphere \ S) subset dW) and bottom-face fact are exactly the three supports hbd_ofTransfer consumes. Backing refutation: `SKEFTHawking.PinPlusTraceCapstoneCollarPairCore.not_collarAnnulusOpen_of_null`. -/
alias nogo_not_collarAnnulusOpen_of_null := SKEFTHawking.PinPlusTraceCapstoneCollarPairCore.not_collarAnnulusOpen_of_null

/-- NO-GO [`collar-pair-maximal-core-reenters-refuted-support`] — do NOT re-derive. FALSE: The CollarPairGeom/CollarPairGeomUnsub row's anti-fake tether hcoreHit can be made free of charge by enlarging the #210 shrunk core K toward its limit K = univ, keeping the rest of the collar-pair split data intact. Backing refutation: `SKEFTHawking.PinPlusTraceCapstoneCollarPairGeom.coreHit_of_univ`. -/
alias nogo_coreHit_of_univ := SKEFTHawking.PinPlusTraceCapstoneCollarPairGeom.coreHit_of_univ

/-- NO-GO [`collar-pair-maximal-core-reenters-refuted-support`] — do NOT re-derive. FALSE: The CollarPairGeom/CollarPairGeomUnsub row's anti-fake tether hcoreHit can be made free of charge by enlarging the #210 shrunk core K toward its limit K = univ, keeping the rest of the collar-pair split data intact. Backing refutation: `SKEFTHawking.PinPlusTraceCapstoneCollarPairGeom.houtC_support_univ_eq_refuted`. -/
alias nogo_houtC_support_univ_eq_refuted := SKEFTHawking.PinPlusTraceCapstoneCollarPairGeom.houtC_support_univ_eq_refuted

/-- NO-GO [`k7-seam-cover-interior-fails`] — do NOT re-derive. FALSE: K7SeamCoverHyp (the K7 opener's un-thickened MV cover hypothesis): the INTERIORS of the two closed Kummer-weld pieces (the Q-image and the 16 closed E-images) cover the welded K3 carrier, so the Mayer-Vietoris assembly can run on the un-thickened pieces directly. Backing refutation: `SKEFTHawking.KummerK7SeamCoverNoGo.k7SeamCoverHyp_false`. -/
alias nogo_k7SeamCoverHyp_false := SKEFTHawking.KummerK7SeamCoverNoGo.k7SeamCoverHyp_false

/-- NO-GO [`gram-literal-equality-is-choice-dependent`] — do NOT re-derive. FALSE: SphereProdGramPin - the LITERAL matrix equality `interMatrix fc B = sphereProdFormDatum` on the computed rank-2 basis - is a disclosed GEOMETRIC residual of the S2xS2 intersection form, dischargeable once the Kunneth/EZ cross value is pinned. Backing refutation: `SKEFTHawking.SphereProdGramPinRetire.sphereProd_interMatrix_computed_eq`. -/
alias nogo_sphereProd_interMatrix_computed_eq := SKEFTHawking.SphereProdGramPinRetire.sphereProd_interMatrix_computed_eq

/-- NO-GO [`gram-literal-equality-is-choice-dependent`] — do NOT re-derive. FALSE: SphereProdGramPin - the LITERAL matrix equality `interMatrix fc B = sphereProdFormDatum` on the computed rank-2 basis - is a disclosed GEOMETRIC residual of the S2xS2 intersection form, dischargeable once the Kunneth/EZ cross value is pinned. Backing refutation: `SKEFTHawking.SphereProdGramPinRetire.sphereProdGramPin_iff`. -/
alias nogo_sphereProdGramPin_iff := SKEFTHawking.SphereProdGramPinRetire.sphereProdGramPin_iff

end SKEFTHawking.KernelNoGos
