/-
# Phase 5q.H — the `b₂` residual routed onto the TWO CHARTS of `E`

`KummerCollarPairLESInt` pinned the last open input to `H₂(K3;ℤ) ≅ ℤ²²` to one existential in one
explicit group: `M := H₂(E, {fiberNorm ≥ 1/2}; ℤ)` must be **cyclic**
(`KummerPieceCollarCyclicInt.OuterECyclic`), equivalently the zero-section class must be halvable.
It also established — and this is the honest starting point of this module — that the **pair long
exact sequence cannot decide it**. The LES only says `M` is an extension

> `0 → ℤ --[S²]--> M --∂--> ℤ/2 → 0`,

and `Ext¹(ℤ/2, ℤ) ≅ ℤ/2` has two elements: `M ≅ ℤ` (the truth, the Euler number `−2`) and
`M ≅ ℤ ⊕ ℤ/2` are *both* consistent with every group appearing in that sequence. Deciding it
requires information from **outside** the sequence, i.e. genuine geometry of `E`. Textbook, that
information is Lefschetz duality, the Thom isomorphism, or a Mayer–Vietoris over the two charts.

## The route, and why this one

A relative Mayer–Vietoris with the **ambient split** is absent from the tree and expensive (it needs
the small-simplices theorem twice plus a six-term diagram). Integral **excision** is fully banked
(`SingularExcisionIsoInt.excisionEquivInt`). `SingularRelativeTripleSurjInt` supplies the one piece
that was missing to make excision do MV's job on a two-piece decomposition:

> for a triple `A ⊆ B ⊆ X`, `Hₙ(X, B; ℤ) = 0` ⟹ `Hₙ(B, A ∩ B; ℤ) ↠ Hₙ(X, A; ℤ)`.

Applied here with `A := outerE` and `B := splitB = outerE ∪ chart1Set`, that turns the undecided
extension into two statements *localised on the separate charts*, each of which is an ordinary
homotopy-type computation with no extension problem in it:

* **(C0)** `H₂(E, outerE ∪ chart1Set; ℤ) = 0` — by excision this is the chart-0 pair
  `H₂(chart0Set, (outerE ∪ seam) ∩ chart0Set)`, and `chart0Set ≅ D² × D²` is contractible;
* **(C1)** `H₂(outerE ∪ chart1Set, outerE; ℤ)` is **cyclic** — by excision the chart-1 pair
  `H₂(chart1Set, outerE ∩ chart1Set) ≅ H₁(D² × annulus) ≅ ℤ`, generated by the **fiber disk**.

`outerECyclic_of_splitB` is that reduction, and `kummerK3_b2_target_of_splitB` chains it to the
headline. The Euler number `−2` is not computed anywhere and never has to be: cyclicity of `M` alone
forces the non-split extension (`KummerCollarPairLESInt.cyclic_iff_gen_mem_two_smul`), hence the
halving, hence `PairH2TwoTorsionFree`. That is why the chart route is sign-free and
orientation-free.

## Non-degeneracy of the chosen `B`

A reduction of this shape is only worth anything if `B` is a *proper* enlargement of `outerE`: with
`B = Set.univ` both hypotheses are trivial/circular (`H₂(X, univ) = 0` and `H₂(univ, outerE) ≅ M`),
and with `B = outerE` the first hypothesis *is* `M = 0`, which is false (`M` is infinite,
`KummerPieceCollarCyclicInt.infinite_outerH2`). §1 therefore pins `splitB` between the two:
`outerE ⊆ splitB` (`outerE_subset_splitB`), `splitB ≠ Set.univ` (`splitB_ne_univ`, witnessed by the
zero-section point of chart 0), and `splitB ∪ chart0Set = Set.univ`
(`splitB_union_chart0Set`) — the two-piece decomposition the excision steps of (C0)/(C1) run on.

Kernel-pure (`{propext, Classical.choice, Quot.sound}`); no `sorry`, no new axiom, no
`native_decide`, no `maxHeartbeats`.
-/
import Mathlib
import SKEFTHawking.SingularRelativeTripleSurjInt
import SKEFTHawking.KummerCollarPairLESInt

open SKEFTHawking.SingularHomologyInt (Homology)
open SKEFTHawking.SingularRelHomologyInt (RelHomologyInt)
open SKEFTHawking.SingularExcisionIso (restr)
open SKEFTHawking.KummerResolutionPiece (ResE ResChart chart0 chart1 chart0_eq_chart1_iff)
open SKEFTHawking.KummerPairTransportInt (ResEtop)
open SKEFTHawking.KummerPieceCollarInt (outerE)
open SKEFTHawking.KummerPieceCollarCyclicInt (OuterECyclic kummerK3_b2_target_of_outerE_cyclic)
open SKEFTHawking.SingularRelativeTripleSurjInt (relHomologyInt_cyclic_of_triple)

namespace SKEFTHawking.KummerCollarPairSplitInt

noncomputable section

/-! ## §1. The two chart regions and the splitting subspace `splitB` -/

/-- The **chart-0 region** of `E` — the image of the first `D² × D²` chart. -/
def chart0Set : Set ↑ResEtop := Set.range chart0

/-- The **chart-1 region** of `E` — the image of the second `D² × D²` chart. -/
def chart1Set : Set ↑ResEtop := Set.range chart1

/-- **The two charts cover `E`.** Every point of the glued carrier is a chart-0 or a chart-1 point:
`ResE` is a quotient of `ResChart ⊕ ResChart`. -/
theorem chart0Set_union_chart1Set : chart0Set ∪ chart1Set = Set.univ := by
  refine Set.eq_univ_of_forall fun y => ?_
  obtain ⟨s, rfl⟩ := Quotient.exists_rep (y : ResE)
  cases s with
  | inl p => exact Or.inl ⟨p, rfl⟩
  | inr q => exact Or.inr ⟨q, rfl⟩

/-- **The splitting subspace** `B = outerE ∪ chart1Set`: the outer half-collar together with the
whole chart-1 region. The complement of `B` in `E` is the *inner* part of chart 0 — a `D² × D²`
core — which is why `H₂(E, B; ℤ)` is a chart-local, extension-free computation. -/
def splitB : Set ↑ResEtop := outerE ∪ chart1Set

theorem outerE_subset_splitB : outerE ⊆ splitB := Set.subset_union_left

/-- `splitB` together with the chart-0 region covers `E` — the two-piece decomposition the excision
steps run on. -/
theorem splitB_union_chart0Set : splitB ∪ chart0Set = Set.univ := by
  rw [splitB, Set.union_comm outerE chart1Set, Set.union_assoc,
    Set.union_comm outerE chart0Set, ← Set.union_assoc, Set.union_comm chart1Set chart0Set,
    chart0Set_union_chart1Set, Set.univ_union]

/-- **`splitB` is a proper subspace** — the zero-section point over the chart-0 origin lies outside
it. Without this the reduction below would be satisfiable by `B = Set.univ`, where both hypotheses
degenerate (`H₂(X, univ) = 0` and `H₂(univ, outerE) ≅ H₂(X, outerE)`) and nothing is proved. The
witness is exactly the point the collar is designed to miss: fiber norm `0`, base `0`. -/
theorem splitB_ne_univ : splitB ≠ (Set.univ : Set ↑ResEtop) := by
  intro h
  have hmem : chart0 (⟨0, by simp⟩, ⟨0, by simp⟩) ∈ splitB := by rw [h]; trivial
  rcases hmem with hout | ⟨q, hq⟩
  · have hz : (1 : ℝ) / 2 ≤ ‖((0 : ℂ))‖ := hout
    simp at hz
    norm_num at hz
  · obtain ⟨hseam, -, -⟩ := chart0_eq_chart1_iff.mp hq.symm
    have h0 : ‖((0 : ℂ))‖ = 1 := hseam
    simp at h0

/-! ## §2. The reduction: two chart-local inputs give the `b₂` residual -/

/-- **The chart reduction.** If

* `(C0)` the relative group of the pair `(E, outerE ∪ chart1Set)` vanishes in degree `2`, and
* `(C1)` the relative group of the pair `(outerE ∪ chart1Set, outerE)` is generated by one element,

then `M = H₂(E, {fiberNorm ≥ 1/2}; ℤ)` is generated by one element — the `b₂` residual in the form
`KummerPieceCollarCyclicInt.OuterECyclic`.

Both inputs are chart-local and free of any extension problem: `(C0)` lives on the contractible
chart-0 region and `(C1)` on the contractible chart-1 region. Neither mentions the zero section, an
orientation, a sign, or the Euler number — those are supplied for free by the algebra of
`KummerCollarPairLESInt.cyclic_iff_gen_mem_two_smul` once cyclicity is known. -/
theorem outerECyclic_of_splitB
    (hzero : ∀ y : RelHomologyInt (X := ResEtop) splitB 2, y = 0)
    (hcyc : ∃ a : RelHomologyInt (restr outerE splitB) 2,
      ∀ x : RelHomologyInt (restr outerE splitB) 2, ∃ k : ℤ, x = k • a) :
    OuterECyclic :=
  relHomologyInt_cyclic_of_triple outerE splitB outerE_subset_splitB 2 hzero hcyc

/-- **The zero-section class is halvable from the two chart inputs** — the mission-form statement of
`KummerCollarPairLESInt`, now reduced to the charts. -/
theorem zeroSectionClass_halved_of_splitB
    (hzero : ∀ y : RelHomologyInt (X := ResEtop) splitB 2, y = 0)
    (hcyc : ∃ a : RelHomologyInt (restr outerE splitB) 2,
      ∀ x : RelHomologyInt (restr outerE splitB) 2, ∃ k : ℤ, x = k • a) :
    ∃ x : SKEFTHawking.KummerCollarPairLESInt.CollarH2,
      (2 : ℤ) • x = SKEFTHawking.KummerCollarPairLESInt.zeroSectionClass :=
  SKEFTHawking.KummerCollarPairLESInt.outerECyclic_iff_zeroSectionClass_halved.mp
    (outerECyclic_of_splitB hzero hcyc)

/-- **The headline consumer.** The two chart-local inputs close `kummerK3_b2_target`
(`H₂(K3;ℤ) ≅ ℤ²²`). -/
theorem kummerK3_b2_target_of_splitB
    (hzero : ∀ y : RelHomologyInt (X := ResEtop) splitB 2, y = 0)
    (hcyc : ∃ a : RelHomologyInt (restr outerE splitB) 2,
      ∀ x : RelHomologyInt (restr outerE splitB) 2, ∃ k : ℤ, x = k • a) :
    SKEFTHawking.KummerK7Opener.kummerK3_b2_target :=
  kummerK3_b2_target_of_outerE_cyclic (outerECyclic_of_splitB hzero hcyc)

/-! ## §3. The reduction is not vacuous on the `(C0)` side

`(C0)` is a genuine restriction on `splitB`: taken at `B = outerE` — the smallest admissible choice —
it would assert `M = 0`, which is false. So the enlargement to `outerE ∪ chart1Set` is doing real
work, and `(C0)` cannot be satisfied by shrinking `B` back down. -/

/-- **`(C0)` fails at `B = outerE`.** The degree-`2` relative group of `(E, outerE)` does *not*
vanish: it is infinite (`KummerPieceCollarCyclicInt.infinite_outerH2`, unconditional). -/
theorem not_relHomologyInt_outerE_eq_zero :
    ¬ (∀ y : RelHomologyInt (X := ResEtop) outerE 2, y = 0) := by
  intro h
  haveI := SKEFTHawking.KummerPieceCollarCyclicInt.infinite_outerH2
  have hsub : (Set.univ : Set (RelHomologyInt (X := ResEtop) outerE 2)) ⊆ {0} :=
    fun y _ => h y
  exact (Set.infinite_univ (α := RelHomologyInt (X := ResEtop) outerE 2))
    (Set.Finite.subset (Set.finite_singleton 0) hsub)

end

end SKEFTHawking.KummerCollarPairSplitInt
