/-
# Phase 5q.H — the `b₂` residual as a **two-element extension problem**, then as ONE divisibility

`KummerPieceCollarCyclicInt` reduced the last open input to `kummerK3_b2_target` (`H₂(K3;ℤ) ≅ ℤ²²`)
to a single sign-free statement about one explicit space:

> `OuterECyclic` — `M := H₂(E, {fiberNorm ≥ 1/2}; ℤ)` is generated by one element.

This module runs the **integral pair long exact sequence** on that pair and thereby pins `M`
completely up to the one bit that is left. The three inputs are all banked:

* `KummerCollarRetractInt` — the collar deformation-retracts onto `∂E ≅ ℝP³`, so
  `H₂(collar;ℤ) = 0` and `H₁(collar;ℤ) ≅ ℤ/2`;
* `KummerBaseSphereH2Int.resEH2EquivInt` — `H₂(E;ℤ) ≅ ℤ`;
* `KummerBaseSphereH2Int.resE_homology_one_eq_zero` — **`H₁(E;ℤ) = 0`** (`E` retracts to its `S²`
  zero section).

The pair LES segment `H₂(collar) = 0 → H₂(E) = ℤ → M → H₁(collar) = ℤ/2 → H₁(E) = 0` is therefore a
**short exact sequence** (`zeroSectionInt_injective`, `collarBoundaryInt_surjective`,
`exact_zeroSectionInt_collarBoundaryInt`):

> `0 → ℤ --jz--> M --bd--> ℤ/2 → 0`

so `M` is an extension of `ℤ/2` by `ℤ` — exactly two possibilities, `M ≅ ℤ` (non-split) or
`M ≅ ℤ ⊕ ℤ/2` (split). **The LES does not by itself decide which**: both are consistent with every
group in the sequence, and `Ext¹(ℤ/2, ℤ) ≅ ℤ/2` has two elements. What §2 does instead is *localise*
the undecided bit to a single, completely explicit, sign-free divisibility, and certify the
localisation is an equivalence:

> **`cyclic_iff_gen_mem_two_smul`** (pure algebra, reusable): for any such SES, the middle term is
> cyclic **iff** the image `jz 1` of the `ℤ`-generator is divisible by `2` in `M`.

Instantiated (§3): `pairH2TwoTorsionFree_iff_zeroSection_halved` — the `b₂` residual holds **iff**

> **the zero-section class `[S²] ∈ H₂(E, collar; ℤ)` is `2 · x` for some `x`.**

That *is* the Euler-number `−2` content of the resolution piece (`2·[fiber disk] = [zero section]`),
now with everything else around it discharged: no `EIndex`, no weld, no K3, no torsion-freeness
quantifier, no generator identification beyond the already-banked `resEH2EquivInt`, and — because
the statement is `∃ x, 2 • x = g` rather than an identification of `x` — **no orientation and no
sign**. `kummerK3_b2_target_of_zeroSection_halved` is the headline consumer.

Kernel-pure (`{propext, Classical.choice, Quot.sound}`); no `sorry`, no new axiom, no
`native_decide`, no `maxHeartbeats`.
-/
import Mathlib
import SKEFTHawking.KummerCollarRetractInt
import SKEFTHawking.KummerPieceCollarCyclicInt
import SKEFTHawking.KummerBaseSphereH2Int
import SKEFTHawking.SingularLocalHomologyInt
import SKEFTHawking.SingularSphereHomologyInt
import SKEFTHawking.SingularLineMinusPointInt
import SKEFTHawking.SingularH0PathConnectedInt
import SKEFTHawking.KummerRP3HomologyUnconditional

open SKEFTHawking.SingularHomologyInt (Homology)
open SKEFTHawking.SingularRelHomologyInt (RelHomologyInt homIncl homProjInt connectingInt)
open SKEFTHawking.SingularLocalHomologyInt (exact_homProjInt_connectingInt exact_connectingInt_homIncl)
open SKEFTHawking.SingularSphereHomologyInt (exact_homIncl_homProjInt)
open SKEFTHawking.KummerPairTubeSeparation (PairH2TwoTorsionFree)
open SKEFTHawking.KummerPairTransportInt (ResEtop)
open SKEFTHawking.KummerPieceCollarInt (outerE)
open SKEFTHawking.KummerPieceCollarCyclicInt (OuterECyclic pairH2TwoTorsionFree_iff_outerE_cyclic)
open SKEFTHawking.KummerCollarRetractInt (OuterTop outerH1EquivZMod2 outerE_homology_two_eq_zero
  outerRP3HomologyEquiv)
open SKEFTHawking.KummerBaseSphereH2Int (resEH2EquivInt resE_homology_one_eq_zero
  resE_homology_three_eq_zero resE_homology_four_eq_zero)
open SKEFTHawking.SingularLineMinusPointInt (augHInt homIncl_zero_injective_of_augHInt_injective
  connectingInt_zero_injective_of_acyclic)
open SKEFTHawking.SingularH0PathConnectedInt (augHInt_injective_pathConnected)

namespace SKEFTHawking.KummerCollarPairLESInt

noncomputable section

/-! ## §1. The pair LES segment is a short exact sequence `0 → ℤ → M → ℤ/2 → 0` -/

/-- `M = H₂(E, collar; ℤ)` — the `b₂` residual's carrier. -/
abbrev CollarH2 : Type := RelHomologyInt (X := ResEtop) outerE 2

/-- **The zero-section leg** `ℤ ≅ H₂(E;ℤ) → M`: the pair map `j_*` precomposed with the banked
`resEH2EquivInt : H₂(E;ℤ) ≅ ℤ`. Its value at `1` is the zero-section class in the relative group. -/
def zeroSectionInt : ℤ →ₗ[ℤ] CollarH2 :=
  (homProjInt (X := ResEtop) outerE 2).comp resEH2EquivInt.symm.toLinearMap

/-- **The boundary leg** `M → ℤ/2`: the pair connecting map `δ` followed by the banked
`H₁(collar;ℤ) ≅ ℤ/2` of `KummerCollarRetractInt`. -/
def collarBoundaryInt : CollarH2 →ₗ[ℤ] ZMod 2 :=
  outerH1EquivZMod2.toLinearMap.comp (connectingInt (X := ResEtop) outerE 1)

/-- **`jz` is injective** — exactness at `H₂(E)` plus `H₂(collar;ℤ) = 0`
(`KummerCollarRetractInt.outerE_homology_two_eq_zero`, i.e. `H₂(ℝP³;ℤ) = 0`). -/
theorem zeroSectionInt_injective : Function.Injective zeroSectionInt := by
  have hker : ∀ x : Homology ResEtop 2, homProjInt (X := ResEtop) outerE 2 x = 0 → x = 0 := by
    intro x hx
    obtain ⟨w, rfl⟩ := (exact_homIncl_homProjInt (X := ResEtop) outerE 2 x).mp hx
    rw [outerE_homology_two_eq_zero w, map_zero]
  intro a b hab
  have h0 : homProjInt (X := ResEtop) outerE 2
      (resEH2EquivInt.symm a - resEH2EquivInt.symm b) = 0 := by
    rw [map_sub]
    exact sub_eq_zero.mpr hab
  have h1 : resEH2EquivInt.symm a = resEH2EquivInt.symm b := sub_eq_zero.mp (hker _ h0)
  exact resEH2EquivInt.symm.injective h1

/-- **`bd` is surjective** — exactness at `H₁(collar)` plus `H₁(E;ℤ) = 0`
(`KummerBaseSphereH2Int.resE_homology_one_eq_zero`). -/
theorem collarBoundaryInt_surjective : Function.Surjective collarBoundaryInt := by
  intro k
  obtain ⟨w, hw⟩ : ∃ w : CollarH2, connectingInt (X := ResEtop) outerE 1 w
      = outerH1EquivZMod2.symm k :=
    (exact_connectingInt_homIncl (X := ResEtop) outerE 1 (outerH1EquivZMod2.symm k)).mp
      (resE_homology_one_eq_zero _)
  refine ⟨w, ?_⟩
  show outerH1EquivZMod2 (connectingInt (X := ResEtop) outerE 1 w) = k
  rw [hw, LinearEquiv.apply_symm_apply]

/-- **Exactness in the middle**: `ker bd = im jz`. Directly the pair-LES exactness at `H₂(E, collar)`
(`SingularLocalHomologyInt.exact_homProjInt_connectingInt`), with the two banked isomorphisms
`resEH2EquivInt` / `outerH1EquivZMod2` grafted on either side. -/
theorem exact_zeroSectionInt_collarBoundaryInt :
    Function.Exact zeroSectionInt collarBoundaryInt := by
  intro y
  constructor
  · intro hy
    have hy' : connectingInt (X := ResEtop) outerE 1 y = 0 := by
      have h1 : outerH1EquivZMod2 (connectingInt (X := ResEtop) outerE 1 y) = 0 := hy
      have h2 := congrArg outerH1EquivZMod2.symm h1
      rwa [LinearEquiv.symm_apply_apply, map_zero] at h2
    obtain ⟨x, hx⟩ := (exact_homProjInt_connectingInt (X := ResEtop) outerE 1 y).mp hy'
    exact ⟨resEH2EquivInt x, by
      show homProjInt (X := ResEtop) outerE 2 (resEH2EquivInt.symm (resEH2EquivInt x)) = y
      rw [LinearEquiv.symm_apply_apply]; exact hx⟩
  · rintro ⟨a, rfl⟩
    show outerH1EquivZMod2 (connectingInt (X := ResEtop) outerE 1
      (homProjInt (X := ResEtop) outerE 2 (resEH2EquivInt.symm a))) = 0
    rw [(exact_homProjInt_connectingInt (X := ResEtop) outerE 1 _).mpr ⟨_, rfl⟩, map_zero]

/-! ## §2. The extension problem, solved into ONE divisibility (pure algebra) -/

/-- **The extension lemma.** Let `0 → ℤ --jz--> M --bd--> ℤ/2 → 0` be short exact. Then `M` is
**cyclic** — equivalently (`Ext¹(ℤ/2, ℤ) ≅ ℤ/2`) the extension is non-split, `M ≅ ℤ` — **iff** the
image `jz 1` of the `ℤ`-generator is divisible by `2` in `M`.

Both directions are needed: `←` is the construction (a halving element generates), `→` is the
certificate that asking for the halving loses nothing. No orientation, no sign, no identification of
the halving element: only `∃`. -/
theorem cyclic_iff_gen_mem_two_smul {M : Type*} [AddCommGroup M] [Module ℤ M]
    (jz : ℤ →ₗ[ℤ] M) (bd : M →ₗ[ℤ] ZMod 2) (hj : Function.Injective jz)
    (hb : Function.Surjective bd) (hex : Function.Exact jz bd) :
    (∃ a : M, ∀ m : M, ∃ k : ℤ, m = k • a) ↔ ∃ x : M, (2 : ℤ) • x = jz 1 := by
  have hjz : ∀ k : ℤ, jz k = k • jz 1 := by
    intro k
    rw [← map_zsmul, smul_eq_mul, mul_one]
  have hbin : ∀ y : ZMod 2, y = 0 ∨ y = 1 := by decide
  have hzs : ∀ k : ℤ, k • (1 : ZMod 2) = ((k : ℤ) : ZMod 2) := by
    intro k; rw [zsmul_eq_mul, mul_one]
  constructor
  · rintro ⟨a, hgen⟩
    -- `bd a` generates `ℤ/2`, since `bd` is onto and every element is a multiple of `a`.
    have hba : bd a = 1 := by
      rcases hbin (bd a) with h | h
      · obtain ⟨x, hx⟩ := hb 1
        obtain ⟨k, rfl⟩ := hgen x
        rw [map_zsmul, h, smul_zero] at hx
        exact absurd hx.symm one_ne_zero
      · exact h
    obtain ⟨c, hc⟩ := hgen (jz 1)
    have hbg : bd (jz 1) = 0 := (hex (jz 1)).mpr ⟨1, rfl⟩
    have hc0 : ((c : ℤ) : ZMod 2) = 0 := by
      rw [← hzs c, ← hba, ← map_zsmul, ← hc, hbg]
    obtain ⟨d, rfl⟩ := (ZMod.intCast_zmod_eq_zero_iff_dvd c 2).mp hc0
    refine ⟨d • a, ?_⟩
    rw [hc, smul_smul]
    norm_num
  · rintro ⟨x, hx⟩
    -- `bd x ≠ 0`: otherwise `jz 1 = jz (2k)`, contradicting injectivity of `jz`.
    have hbx : bd x = 1 := by
      rcases hbin (bd x) with h | h
      · exfalso
        obtain ⟨k, hk⟩ := (hex x).mp h
        have h2 : jz (2 * k) = jz 1 := by
          have hmul : (2 : ℤ) * k = (2 : ℤ) • k := (smul_eq_mul (2 : ℤ) k).symm
          rw [hmul, map_zsmul, hk, hx]
        have h3 : (2 : ℤ) * k = 1 := hj h2
        omega
      · exact h
    refine ⟨x, fun m => ?_⟩
    rcases hbin (bd m) with h | h
    · obtain ⟨k, hk⟩ := (hex m).mp h
      refine ⟨2 * k, ?_⟩
      rw [← hk, hjz, ← hx, smul_smul, mul_comm k 2]
    · have hsub : bd (m - x) = 0 := by rw [map_sub, h, hbx, sub_self]
      obtain ⟨k, hk⟩ := (hex (m - x)).mp hsub
      refine ⟨2 * k + 1, ?_⟩
      have hm : m = jz k + x := by rw [hk]; abel
      have hsplit : (2 * k + 1 : ℤ) • x = (2 * k : ℤ) • x + x := by
        rw [add_zsmul, one_zsmul]
      rw [hm, hjz, ← hx, smul_smul, hsplit, mul_comm k 2]

/-! ## §3. The `b₂` residual is exactly "the zero-section class is halvable" -/

/-- **The zero-section class in the relative group** — the image of the generator of `H₂(E;ℤ) ≅ ℤ`
(the class of the `S²` zero section, `resEH2EquivInt`) under the pair map `j_*`. -/
def zeroSectionClass : CollarH2 := zeroSectionInt 1

/-- **The zero-section class is nonzero** — `jz` is injective and `1 ≠ 0` in `ℤ`. Without this the
divisibility below would be satisfiable by `x = 0` and carry no content. -/
theorem zeroSectionClass_ne_zero : zeroSectionClass ≠ 0 := by
  intro h
  have h0 : zeroSectionInt (1 : ℤ) = zeroSectionInt (0 : ℤ) := by rw [map_zero]; exact h
  exact one_ne_zero (zeroSectionInt_injective h0)

/-- The zero-section class dies under the boundary leg — it is the `ℤ` part of the extension. -/
theorem collarBoundaryInt_zeroSectionClass : collarBoundaryInt zeroSectionClass = 0 :=
  (exact_zeroSectionInt_collarBoundaryInt zeroSectionClass).mpr ⟨1, rfl⟩

/-- **The zero-section class does NOT generate `M`** — `bd` kills it but is onto `ℤ/2`. So the
residual really is about a *different* class (geometrically, the relative fiber disk `F` with
`2·[F] = [S²]`), and the divisibility below is not a restatement of "some class generates". -/
theorem zeroSectionClass_not_generating :
    ¬ ∀ m : CollarH2, ∃ k : ℤ, m = k • zeroSectionClass := by
  intro hgen
  obtain ⟨w, hw⟩ := collarBoundaryInt_surjective 1
  obtain ⟨k, rfl⟩ := hgen w
  rw [map_zsmul, collarBoundaryInt_zeroSectionClass, smul_zero] at hw
  exact one_ne_zero hw.symm

/-- **The extension, decided into one divisibility.** `M = H₂(E, collar; ℤ)` is cyclic — the
non-split option `M ≅ ℤ` of the short exact sequence `0 → ℤ → M → ℤ/2 → 0` — **iff** the
zero-section class is twice something. This is `cyclic_iff_gen_mem_two_smul` instantiated at the
banked pair LES of §1; a genuine `↔`, so nothing is lost by aiming the remaining geometry here. -/
theorem outerECyclic_iff_zeroSectionClass_halved :
    OuterECyclic ↔ ∃ x : CollarH2, (2 : ℤ) • x = zeroSectionClass :=
  cyclic_iff_gen_mem_two_smul zeroSectionInt collarBoundaryInt zeroSectionInt_injective
    collarBoundaryInt_surjective exact_zeroSectionInt_collarBoundaryInt

/-- **THE RESIDUAL, in its sharpest form.** The `b₂` residual `PairH2TwoTorsionFree` — the last open
input to `H₂(K3;ℤ) ≅ ℤ²²` — holds **iff** the zero-section class of the Euler-`−2` disk bundle is
divisible by `2` in `H₂(E, {fiberNorm ≥ 1/2}; ℤ)`. No `EIndex`, no weld, no K3, no torsion
quantifier, no orientation, no sign: one explicit element of one explicit group, and an `∃`. -/
theorem pairH2TwoTorsionFree_iff_zeroSection_halved :
    PairH2TwoTorsionFree ↔ ∃ x : CollarH2, (2 : ℤ) • x = zeroSectionClass :=
  pairH2TwoTorsionFree_iff_outerE_cyclic.trans outerECyclic_iff_zeroSectionClass_halved

/-- **The headline consumer** — halving the zero-section class closes `kummerK3_b2_target`. -/
theorem kummerK3_b2_target_of_zeroSection_halved
    (h : ∃ x : CollarH2, (2 : ℤ) • x = zeroSectionClass) :
    SKEFTHawking.KummerK7Opener.kummerK3_b2_target :=
  SKEFTHawking.KummerPieceCollarCyclicInt.kummerK3_b2_target_of_outerE_cyclic
    (outerECyclic_iff_zeroSectionClass_halved.mpr h)

/-! ## §4. The rest of the pair — every other degree is settled

The same LES, run in the remaining degrees, pins `H_*(E, collar; ℤ)` completely: it is `0` in degrees
`1` and `3`, and `ℤ` in degree `4` (the Lefschetz relative fundamental class). So **degree 2 is the
only undetermined slot of the whole pair**, and inside it only the one bit of §3. -/

instance instPathConnectedOuterTop : PathConnectedSpace ↑OuterTop :=
  SKEFTHawking.KummerK7H1Window.instPathConnectedOuterE

/-- `H₀(collar;ℤ) → H₀(E;ℤ)` is injective — the collar is path-connected
(`KummerK7H1Window.instPathConnectedOuterE`: every collar point flows to `∂E ≅ ℝP³`). -/
theorem homIncl_zero_injective : Function.Injective (homIncl (X := ResEtop) outerE 0) :=
  homIncl_zero_injective_of_augHInt_injective outerE augHInt_injective_pathConnected

/-- The bottom connecting map vanishes (its range sits in `ker i_*` = `0`). -/
theorem connectingInt_zero_eq_zero : connectingInt (X := ResEtop) outerE 0 = 0 := by
  apply LinearMap.ext
  intro y
  rw [LinearMap.zero_apply]
  apply homIncl_zero_injective
  rw [map_zero, ← LinearMap.mem_ker,
    (exact_connectingInt_homIncl (X := ResEtop) outerE 0).linearMap_ker_eq]
  exact LinearMap.mem_range_self _ y

/-- **`H₁(E, collar; ℤ) = 0`** — `H₁(E;ℤ) = 0` makes `δ` injective, and `δ` is the zero map because
`H₀(collar) ↪ H₀(E)`. -/
theorem collarPair_homology_one_eq_zero (y : RelHomologyInt (X := ResEtop) outerE 1) : y = 0 := by
  refine connectingInt_zero_injective_of_acyclic (X := ResEtop) outerE resE_homology_one_eq_zero ?_
  rw [map_zero, connectingInt_zero_eq_zero, LinearMap.zero_apply]

/-- **`H₃(E, collar; ℤ) = 0`** — squeezed between `H₃(E;ℤ) = 0` and `H₂(collar;ℤ) = 0`. -/
theorem collarPair_homology_three_eq_zero (y : RelHomologyInt (X := ResEtop) outerE 3) :
    y = 0 := by
  obtain ⟨x, rfl⟩ := (exact_homProjInt_connectingInt (X := ResEtop) outerE 2 y).mp
    (outerE_homology_two_eq_zero _)
  rw [resE_homology_three_eq_zero x, map_zero]

/-- The top connecting map `δ : H₄(E, collar; ℤ) → H₃(collar; ℤ)` is bijective: `H₄(E;ℤ) = 0` on the
left and `H₃(E;ℤ) = 0` on the right. -/
theorem connectingInt_three_bijective :
    Function.Bijective (connectingInt (X := ResEtop) outerE 3) := by
  constructor
  · intro a b hab
    have h0 : connectingInt (X := ResEtop) outerE 3 (a - b) = 0 := by
      rw [map_sub]; exact sub_eq_zero.mpr hab
    obtain ⟨x, hx⟩ := (exact_homProjInt_connectingInt (X := ResEtop) outerE 3 (a - b)).mp h0
    rw [resE_homology_four_eq_zero x, map_zero] at hx
    exact sub_eq_zero.mp hx.symm
  · intro w
    exact (exact_connectingInt_homIncl (X := ResEtop) outerE 3 w).mp
      (resE_homology_three_eq_zero _)

/-- **`H₄(E, collar; ℤ) ≅ ℤ`** — the relative fundamental class of the compact 4-manifold-with-
boundary `(E, ∂E)`, obtained as `δ`-iso onto `H₃(collar;ℤ) ≅ H₃(ℝP³;ℤ) ≅ ℤ`. Together with
`collarPair_homology_one_eq_zero` and `collarPair_homology_three_eq_zero`, degree `2` is the only
slot of the pair still carrying an undetermined bit. -/
def collarPairH4EquivInt : RelHomologyInt (X := ResEtop) outerE 4 ≃ₗ[ℤ] ℤ :=
  ((LinearEquiv.ofBijective _ connectingInt_three_bijective).trans
    (outerRP3HomologyEquiv 2)).trans
      SKEFTHawking.KummerRP3HomologyUnconditional.rp3H3EquivInt_unconditional

end

end SKEFTHawking.KummerCollarPairLESInt
