/-
# The degree-3 puncture crux: 2-saturation of `im ∂₃` from ONE mod-2 non-vanishing

`KummerPunctureH3.thickA_H3_twoTorsionFree_of_delta3_saturated` reduces the 2-torsion-freeness of
`H₃(T⁴°;ℤ) = H₃(thickA;ℤ)` to the 2-saturation of the image of the degree-3 puncture Mayer–Vietoris
connecting map `∂₃ = mvDeltaInt thickA ballsV 3` inside `H₃(collar;ℤ) ≅ ℤ¹⁶`. This module removes ALL
remaining algebra from that residual, leaving a single non-vanishing statement.

The key structural fact is that `H₄(T⁴;ℤ) ≅ ℤ` is **cyclic**, generated by `[T⁴]`
(`torusFourFundamentalClass_generates`). Hence `im ∂₃ = ℤ·v` with `v = ∂₃[T⁴]`, and — `H₃(collar)`
being free (`interH3EquivEIndex : ≅ ℤ¹⁶`, so torsion-free) — a cyclic subgroup `ℤ·v` of a
torsion-free group is 2-saturated **exactly when** `v` is not twice a nonzero vector:

    (`2•w = k•v` and `v ∉ 2·(H₃(collar)∖0)`)  ⟹  `k` even  ⟹  `w = (k/2)•v ∈ ℤ·v`.

The cheapest sufficient certificate for "`v` is not twice anything nonzero" is that `v` survives the
ℤ→ℤ/2 reduction `redHomology`: over a `ZMod 2`-module `k • y = (k : ZMod 2) • y`, so `k•(red v) = 0`
with `red v ≠ 0` forces `k` even directly. That is the whole content of §2.

## What this banks

* **§1** `collarH3_twoTorsionFree` — `H₃(thickA ∩ ballsV;ℤ) ≅ ℤ¹⁶` is torsion-free at `2`.
* **§2** `delta3_saturated_of_red_ne_zero` — `red(∂₃[T⁴]) ≠ 0` ⟹ `im ∂₃` is 2-saturated.
* **§3** `thickA_H3_twoTorsionFree_of_red_delta3_ne_zero` — the headline: `H₃(T⁴°;ℤ)` is
  2-torsion-free as soon as `red(∂₃[T⁴]) ≠ 0`. The residual is now ONE mod-2 class being nonzero.
* **§3** `delta3_saturated_iff_not_two_smul` — the LOSSLESS reading: saturation of `im ∂₃` is
  *equivalent* to `∂₃[T⁴]` not being `2•(nonzero)`. So §2 is not a strengthening artefact: the only
  gap between it and the exact criterion is the (geometrically vacuous, algebraically harmless)
  possibility that `∂₃[T⁴]` is divisible by 2 yet nonzero — which `red ≠ 0` rules out.

Kernel-pure (`{propext, Classical.choice, Quot.sound}`); no `sorry`/`native_decide`/`maxHeartbeats`/axiom.
-/
import Mathlib
import SKEFTHawking.KummerPunctureH3
import SKEFTHawking.IntFundamentalClassOrientation

namespace SKEFTHawking.KummerPunctureH3Saturation

open SKEFTHawking.SingularHomologyInt (Homology redHomology)
open SKEFTHawking.SingularRelativeHomologyMod2 (sub)
open SKEFTHawking.KummerK3Base (TorusFour)
open SKEFTHawking.KummerWeld (EIndex)
open SKEFTHawking.KummerPunctureBalls (ballsV thickA punc_hcov)
open SKEFTHawking.KummerPunctureH3 (interH3EquivEIndex thickA_H3_twoTorsionFree_of_delta3_saturated)
open SKEFTHawking.SingularMayerVietorisLESInt (mvDeltaInt)
open SKEFTHawking.KummerHomologyT4Full (torusFourFundamentalClass
  torusFourFundamentalClass_generates)

noncomputable section

/-- **The degree-3 puncture connecting map** `∂₃ : H₄(T⁴;ℤ) → H₃(collar;ℤ)`, the single geometric
input of the `H₃(T⁴°) ≅ ℤ¹⁹` solve. Written with `(X := …)` pinned — `mvDeltaInt` takes its `TopCat`
implicitly and an unpinned call blows the elaborator's `isDefEq` budget. -/
abbrev puncDelta3 :
    Homology (TopCat.of TorusFour) 4 →ₗ[ℤ]
      Homology (sub (X := TopCat.of TorusFour) (thickA ∩ ballsV)) 3 :=
  mvDeltaInt (X := TopCat.of TorusFour) thickA ballsV 3 punc_hcov

/-! ## §1. `H₃(collar;ℤ) ≅ ℤ¹⁶` is 2-torsion-free -/

/-- **`H₃(thickA ∩ ballsV;ℤ)` is torsion-free** — it is `≅ (EIndex → ℤ)` (`interH3EquivEIndex`), a
free module, and freeness is transported through the iso coordinatewise. -/
theorem collarH3_torsionFree {n : ℤ} (hn : n ≠ 0)
    (w : Homology (sub (X := TopCat.of TorusFour) (thickA ∩ ballsV)) 3)
    (hw : n • w = 0) : w = 0 := by
  refine interH3EquivEIndex.injective ?_
  rw [map_zero]
  have h2 : n • interH3EquivEIndex w = 0 := by rw [← map_smul, hw, map_zero]
  funext i
  have hi := congrFun h2 i
  simp only [Pi.smul_apply, smul_eq_mul, Pi.zero_apply] at hi
  exact (mul_eq_zero.mp hi).resolve_left hn

/-- **`H₃(collar;ℤ)` has no 2-torsion** — the `n = 2` instance of `collarH3_torsionFree`, the shape
the saturation argument consumes. -/
theorem collarH3_twoTorsionFree
    (w : Homology (sub (X := TopCat.of TorusFour) (thickA ∩ ballsV)) 3)
    (hw : (2 : ℤ) • w = 0) : w = 0 :=
  collarH3_torsionFree two_ne_zero w hw

/-! ## §2. A mod-2 surviving `∂₃[T⁴]` saturates the image -/

/-- **In a `ZMod 2`-module, `(2 : ℤ) • y = 0`.** The one arithmetic fact that makes the reduction a
usable parity detector. -/
theorem two_zsmul_eq_zero_mod2 {V : Type*} [AddCommGroup V] [Module (ZMod 2) V] (y : V) :
    (2 : ℤ) • y = 0 := by
  rw [two_smul]
  have h : (2 : ZMod 2) • y = y + y := two_smul (ZMod 2) y
  rw [← h, show (2 : ZMod 2) = 0 by decide, zero_smul]

/-- **An odd multiple of a nonzero class of a `ZMod 2`-module is nonzero.** `k • y = (k : ZMod 2) • y`,
and a nonzero element of `ZMod 2` is `1`. -/
theorem even_of_zsmul_eq_zero_mod2 {V : Type*} [AddCommGroup V] [Module (ZMod 2) V] {y : V}
    (hy : y ≠ 0) {k : ℤ} (hk : k • y = 0) : (2 : ℤ) ∣ k := by
  by_contra hdvd
  have hcast : ((k : ZMod 2)) ≠ 0 := fun h =>
    hdvd ((ZMod.intCast_zmod_eq_zero_iff_dvd k 2).mp h)
  have hone : ((k : ZMod 2)) = 1 := by
    rcases (by decide : ∀ a : ZMod 2, a = 0 ∨ a = 1) ((k : ZMod 2)) with h | h
    · exact absurd h hcast
    · exact h
  have : ((k : ZMod 2)) • y = 0 := by rw [Int.cast_smul_eq_zsmul]; exact hk
  rw [hone, one_smul] at this
  exact hy this

/-- **THE SATURATION, from one mod-2 non-vanishing.** If the ℤ→ℤ/2 reduction of `∂₃[T⁴]` is nonzero
in `H₃(collar;ℤ/2)`, then `im ∂₃` is 2-saturated in `H₃(collar;ℤ)`.

Proof: `H₄(T⁴;ℤ)` is generated by `[T⁴]` (`torusFourFundamentalClass_generates`), so every element of
`im ∂₃` is `k•v` with `v = ∂₃[T⁴]`. From `2•w = k•v`, reducing mod 2 kills the left side
(`two_zsmul_eq_zero_mod2`) and leaves `k•(red v) = 0`, forcing `k = 2m`
(`even_of_zsmul_eq_zero_mod2`). Then `2•(m•v − w) = 0` and `H₃(collar)` is torsion-free (§1), so
`w = m•v = ∂₃(m•[T⁴])`. -/
theorem delta3_saturated_of_red_ne_zero
    (hred : redHomology (sub (X := TopCat.of TorusFour) (thickA ∩ ballsV)) 3
        (puncDelta3 torusFourFundamentalClass) ≠ 0) :
    ∀ w, (2 : ℤ) • w ∈ Set.range puncDelta3 → w ∈ Set.range puncDelta3 := by
  intro w hw
  obtain ⟨a, ha⟩ := hw
  obtain ⟨k, hk⟩ :=
    Submodule.mem_span_singleton.mp
      (show a ∈ Submodule.span ℤ {torusFourFundamentalClass} by
        rw [torusFourFundamentalClass_generates]; trivial)
  -- `∂₃ a = k • v`
  have hav : puncDelta3 a = k • puncDelta3 torusFourFundamentalClass := by
    rw [← hk, map_smul]
  -- reduce mod 2: `k • red v = 0`
  have hzero : k • redHomology (sub (X := TopCat.of TorusFour) (thickA ∩ ballsV)) 3
      (puncDelta3 torusFourFundamentalClass) = 0 := by
    rw [← map_zsmul, ← hav, ha, map_zsmul, two_zsmul_eq_zero_mod2]
  obtain ⟨m, hm⟩ := even_of_zsmul_eq_zero_mod2 hred hzero
  -- `2 • (m • v − w) = 0`, so `w = m • v`
  refine ⟨m • torusFourFundamentalClass, ?_⟩
  have h2 : (2 : ℤ) • (m • puncDelta3 torusFourFundamentalClass - w) = 0 := by
    rw [smul_sub, smul_smul, ← hm, ← hav, ha, sub_self]
  have := collarH3_twoTorsionFree _ h2
  rw [map_smul]
  exact sub_eq_zero.mp this

/-! ## §3. The headline, and the lossless reading of the criterion -/

/-- **`H₃(T⁴°;ℤ)` IS 2-TORSION-FREE once `∂₃[T⁴]` survives mod 2.** Composes the §2 saturation with
the banked reduction `thickA_H3_twoTorsionFree_of_delta3_saturated`. The whole degree-3 puncture
residual is now the single mod-2 class `red(∂₃[T⁴]) ∈ H₃(collar;ℤ/2)` being nonzero. -/
theorem thickA_H3_twoTorsionFree_of_red_delta3_ne_zero
    (hred : redHomology (sub (X := TopCat.of TorusFour) (thickA ∩ ballsV)) 3
        (puncDelta3 torusFourFundamentalClass) ≠ 0)
    (x : Homology (sub (X := TopCat.of TorusFour) thickA) 3) (hx : (2 : ℤ) • x = 0) : x = 0 :=
  thickA_H3_twoTorsionFree_of_delta3_saturated (delta3_saturated_of_red_ne_zero hred) x hx

/-- **THE CRITERION IS LOSSLESS (algebraically exact).** 2-saturation of `im ∂₃` is *equivalent* to
`∂₃[T⁴]` not being `2•(nonzero)`. Together with §2 this pins exactly how much §2's mod-2 criterion
gives away: nothing, except the case "`∂₃[T⁴]` nonzero and divisible by 2", which is precisely the
case the exact criterion also excludes. So `red(∂₃[T⁴]) ≠ 0` is a sufficient certificate for an
equivalent condition, not a strengthening of the target. -/
theorem delta3_saturated_iff_not_two_smul :
    (∀ w, (2 : ℤ) • w ∈ Set.range puncDelta3 → w ∈ Set.range puncDelta3) ↔
      ∀ u, puncDelta3 torusFourFundamentalClass = (2 : ℤ) • u → u = 0 := by
  constructor
  · -- saturation ⟹ `v = 2u` forces `u = 0`: `2u = v ∈ im ∂₃` gives `u = k•v = 2k•u`, so
    -- `(2k − 1)•u = 0` with `2k − 1 ≠ 0`, and `H₃(collar)` is torsion-free.
    intro hsat u hu
    obtain ⟨a, ha⟩ := hsat u ⟨torusFourFundamentalClass, hu⟩
    obtain ⟨k, hk⟩ :=
      Submodule.mem_span_singleton.mp
        (show a ∈ Submodule.span ℤ {torusFourFundamentalClass} by
          rw [torusFourFundamentalClass_generates]; trivial)
    have hu' : (2 * k : ℤ) • u = u := by
      rw [mul_comm, mul_smul, ← hu, ← map_smul, hk, ha]
    refine collarH3_torsionFree (n := 2 * k - 1) (fun hzero => ?_) u ?_
    · omega
    · rw [sub_smul, one_smul, hu', sub_self]
  · -- `v` not `2•(nonzero)` ⟹ saturation: `2w = k•v` with `k` odd forces `v = 2•(w − j•v)`, hence
    -- `v = 0` and `w = 0`; with `k` even it is the direct halving.
    intro hprim w hw
    obtain ⟨a, ha⟩ := hw
    obtain ⟨k, hk⟩ :=
      Submodule.mem_span_singleton.mp
        (show a ∈ Submodule.span ℤ {torusFourFundamentalClass} by
          rw [torusFourFundamentalClass_generates]; trivial)
    have hav : (2 : ℤ) • w = k • puncDelta3 torusFourFundamentalClass := by
      rw [← ha, ← hk, map_smul]
    rcases Int.even_or_odd k with ⟨m, hm⟩ | ⟨j, hj⟩
    · refine ⟨m • torusFourFundamentalClass, ?_⟩
      have h2 : (2 : ℤ) • (m • puncDelta3 torusFourFundamentalClass - w) = 0 := by
        rw [smul_sub, smul_smul, hav, show (2 * m : ℤ) = k by omega, sub_self]
      rw [map_smul]
      exact sub_eq_zero.mp (collarH3_twoTorsionFree _ h2)
    · have hv : puncDelta3 torusFourFundamentalClass
          = (2 : ℤ) • (w - j • puncDelta3 torusFourFundamentalClass) := by
        rw [smul_sub, hav, smul_smul, ← sub_smul, hj]
        norm_num
      have hzero := hprim _ hv
      have hv0 : puncDelta3 torusFourFundamentalClass = 0 := by rw [hv, hzero, smul_zero]
      have hw0 : w = 0 := collarH3_twoTorsionFree w (by rw [hav, hv0, smul_zero])
      exact ⟨0, by rw [map_zero, hw0]⟩

end

end SKEFTHawking.KummerPunctureH3Saturation
