/-
# Phase 5q.H — the Kummer K3 generator, OPENER: decomposition dossier + the T⁴ base

**Program.** The σ-route to `Ω₄^{Pin⁺} ≅ ℤ/16` bottoms out at ONE open geometric residual (see
`SpinSigmaGenerator.lean`, `PinPlusKTSpinSigmaStock.K3RealizingElement`): a genuine smooth closed spin
4-manifold whose E1 intersection form realizes the K3 lattice `k3Form = 2·(−E₈) ⊕ 3·H` (σ = −16),
packaged as a `StrMfd (spinEmptyData prov)` with a `SpinSigmaAtomPkg`. The arithmetic half
(`k3Form_latticeSig = −16`, `k3Form_isEvenUnimodular`) is already PROVEN. The remaining content is the
*smooth realization* of that lattice by an actual manifold. Per the lead-vetted realization verdict
(`Lit-Search/Phase-5qH/K3_generator_realization_verdict_20260717.md`): the generator is an ELEMENTARY
SMOOTH cut-and-paste (the Kummer construction), NOT complex/algebraic geometry — so it is buildable
in-tree from Mathlib's smooth-manifold machinery + the project's surgery/atlas substrate.

This module is the OPENER of that multi-arc program. It ships (§A) the full decomposition dossier — the
Kummer construction as a concrete brick sequence, each brick mapped to reusable in-tree / Mathlib
machinery and its hardest foreseen sub-wall — and (§B) the foundational brick: the flat 4-torus `T⁴`
as a smooth closed 4-manifold.

Kernel-pure (`{propext, Classical.choice, Quot.sound}`); no `sorry`/`native_decide`/`maxHeartbeats`/axiom.

## §A. Decomposition dossier — the Kummer K3 generator as a brick sequence

Kummer K3 = the smooth resolution of `T⁴/±1`. Elementary smooth topology (Benedetti arXiv:1907.10297
§20.2; Kirby–Taylor `Ω₄^{Spin}≅ℤ` generated by Kummer). Target = an inhabitant of
`PinPlusKTSpinSigmaStock.K3RealizingElement a` for the disclosed atom bundle `a`. The bricks:

**K0 — T⁴ base as a smooth closed 4-manifold.**  ← THIS MODULE, §B (DONE below).
`T⁴ = (S¹)⁴`, realized as `TorusFour = Circle × Circle × Circle × Circle` (four copies of Mathlib's
smooth circle `Circle = unit sphere ⊂ ℂ`, which carries `ChartedSpace`/`IsManifold (𝓡 1) ω`/`LieGroup`).
Machinery: Mathlib `Circle` smooth/Lie-group instances + the binary-product `ChartedSpace`/`IsManifold`
instances (`Mathlib.Geometry.Manifold.IsManifold.Basic` `instance prod`). Delivers charts, smoothness,
`T2Space`, `CompactSpace`, `Boundaryless`, `Nonempty`, `finrank = 4`.
Sub-wall (deferred, feeds K9): the product model is `(𝓡 1).prod (𝓡 1).prod …` on
`𝔼¹ × 𝔼¹ × 𝔼¹ × 𝔼¹`, NOT `𝓡 4` on `𝔼⁴`; the ultimate `StrMfd (spinEmptyData prov)` uses `I = 𝓡 4`.
Re-charting T⁴ onto `𝓡 4` (a model identification via the linear isometry `𝔼¹×𝔼¹×𝔼¹×𝔼¹ ≃ₗᵢ 𝔼⁴`)
is a K9 packaging brick.

**K1 — H₂(T⁴) ≅ ℤ⁶, intersection form = 3H.**  (Open; next after K0.)
The flat torus has `H₂(T⁴;ℤ) ≅ ℤ^(4 choose 2) = ℤ⁶`, cup form = 3 hyperbolic planes (`3H`, σ = 0,
even unimodular). Machinery: Mathlib group cohomology of `T⁴` is thin; the project's
`IntersectionMatrixInt.interMatrix` + `SphereWitnessTowerInt` S²×S² Gram template
(`SphereProdHTwoInt`/`SphereProdGramInt`) are the in-tree pattern for a concrete 4-manifold's
intersection form. Sub-wall: no Künneth/cup-product-on-a-product-basis in Mathlib — the `II(T⁴)=3H`
Gram identity is a disclosed geometric atom (same posture as the S²×S² `SphereProdGramPin`).

**K2 — the involution τ(w) = −w on T⁴.**  (Open.)
On `(S¹)⁴`, `τ = ` complex-conjugation on each factor (`z ↦ z̄`, a `Circle` anti-automorphism / the
group inverse composed with nothing — actually `z ↦ z⁻¹ = z̄` on the unit circle). Smooth involution,
`τ² = id`. Machinery: `Circle` group inverse is smooth (`LieGroup`), product of smooth maps
(`ContMDiff.prod_map`). Sub-wall: proving `τ` smooth as an `𝓡 4`-manifold self-map and identifying its
fixed set (below).

**K3 — the 16 fixed points of τ.**  (Open.)
`Fix(τ) = (½ℤ/ℤ)⁴`: on each `S¹` factor `z̄ = z ⟺ z = ±1`, so `Fix = {±1}⁴`, exactly `2⁴ = 16` points.
Machinery: `Circle` elements `1` and `-1` (= the two real points); `Finset`/`Fintype` cardinality on
`(Fin 2)⁴`. Sub-wall: identifying `{z : Circle | z⁻¹ = z} = {1, -1}` (a `Circle`-membership computation)
and transporting to the product.

**⚠ ROUTE SUPERSEDED (lead design pass 2026-07-20): K4–K6 as stated below are replaced by ROUTE B**
(excise-first / free-quotient / boundary-weld — the singular orbifold carrier is never built; van Kampen
is off the critical path since `K3RealizingElement` has no π₁ field). Binding brick sequence
K4′/K5′/K6′a/K6′b + the K8a/K8b split: `docs/dev-loops/Phase5qH/KUMMER_K4K10_DESIGN.md`. The entries
below are retained as the original scoping record.

**K4 — the quotient orbifold T⁴/τ with 16 A₁ (cone-on-ℝP³) singular points.**  (Open, harder.)
`T⁴/τ` is a smooth manifold away from the 16 images of the fixed points; near each, the local model is
`ℝ⁴/±1 = ` cone on `ℝP³` (an A₁ / ordinary double point). Machinery: the project's
`SingularSurgeryManifold` / `SingularEuclideanSphereInt` / `RP4*` (ℝP³ analogues) substrate; quotient
topology in Mathlib (`Quotient`, `MulAction` orbit space). Sub-wall (HARDEST of K2–K4): building the
quotient as a *manifold-with-16-cone-singularities* object in-tree — Mathlib has no orbifold/singular
space type; this needs a project-local "smooth away from a finite set + standard cone chart at each"
carrier. Candidate reuse: `SingularSurgeryCharts` / `SingularSurgeryDatumC0`.

**K5 — the A₁ resolution model (single node): the Euler −2 disk bundle over S².**  (Open.)
Replace one cone-on-ℝP³ neighborhood by the total space of the disk bundle `D(𝒪(−2)) → S²` (Euler
number −2); its boundary is `ℝP³ = S³/±1`, matching the link removed, and it contains one embedded
`(−2)`-sphere (the zero section). Machinery: the project's disk-bundle/handle substrate
(`SingularSurgeryHandleD5`, `PinPlusTraceDiskSphereCycle`, collar/gluing in `PinPlusKTSurgeryTrace`).
Sub-wall: realizing the `−2`-framed disk bundle and its `ℝP³` boundary identification as an in-tree
smooth gluing datum; matching the collar to K4's cone link.

**K6 — 16-fold gluing → the smooth Kummer manifold K3.**  (Open.)
Glue the 16 resolution pieces (K5) into the 16 excised cone neighborhoods (K4). Result: a smooth closed
simply-connected 4-manifold. Machinery: iterate the K5 single-node gluing 16×; disjointness of the 16
neighborhoods (from K3's finite fixed set); `SingularSurgeryManifold` connect/glue operations.
Sub-wall: bookkeeping 16 simultaneous disjoint gluings; establishing simple-connectivity of the result
(van Kampen — Mathlib `π₁` support is thin).

**K7 — H₂(Kummer) ≅ ℤ²².**  (Open.)
`b₂ = 22`: from `H₂(T⁴/τ-smooth-part)` (the τ-invariant part of `H₂(T⁴)=ℤ⁶`, contributing rank 6) plus
the 16 exceptional `(−2)`-spheres (rank 16); `6 + 16 = 22`. Machinery: Mayer–Vietoris over the 16
gluings; the S²×S²/`SphereWitnessTowerInt` rank-computation template; `IntH2Basis`. Sub-wall: the MV /
invariant-subspace rank accounting as an in-tree homology computation (no manifold H_* in Mathlib —
disclosed-atom posture, cf. K1).

**K8 — intersection form = 2(−E₈) ⊕ 3H (σ = −16).**  (Open — the payoff.)
The 16 `(−2)`-spheres contribute `2·(−E₈)` (the E₈ plumbing pattern from the resolution graph), the
descended `T⁴` part contributes `3H`. This is *exactly* the already-proven `SpinSigmaGenerator.k3Form`.
Machinery: `k3Form`, `k3Form_isEvenUnimodular`, `k3Form_latticeSig = −16` (DONE, in-tree);
`IntersectionMatrixInt.interMatrix`; `HyperbolicNormalForm.IntCongr` for the `IntCongr … k3Form`
target. Sub-wall: the geometric Gram identity `II(Kummer) ≅ k3Form` — a disclosed atom (Milnor–Husemoller
uniqueness of the rank-22 even unimodular σ=−16 form pins the lattice; the *manifold*'s realizing it is
the geometric input), the direct analogue of the S²×S² `SphereProdGramPin`.

**K9 — spin structure + `StrMfd` packaging on `𝓡 4`.**  (Open — packaging.)
Kummer K3 is spin (its form is even ⟹ `w₂ = 0`). Package as `SingularManifold X 4 (𝓡 4)` → choose the
spin tangential structure (`spinEmptyData prov`'s `Mfd`) → `StrMfd (spinEmptyData prov)`. Resolves the
K0 sub-wall (re-chart onto `𝓡 4`). Machinery: `TangentialDataBordism.StrMfd`,
`PinPlusKTSpinForgetPhi.spinEmptyData`, the S⁴/`sphereProdSM`/`rp4SM` StrMfd-witness templates.
Sub-wall: constructing the `SingularManifold` bundle on `𝓡 4` and inhabiting the spin `Mfd` slot.

**K10 — `SpinSigmaAtomPkg` (orient / B / pd) + `K3RealizingElement`.**  (Open — the capstone.)
Supply the per-element E1 package: integral orientation (`IntOrientation`, from H₄(K3)≅ℤ), the rank-22
`IntH2Basis` (K7), integral Poincaré duality (`IntPoincareDuality`, unimodularity from K8). Assemble
`K3RealizingElement a` with `hrank : (a.B g).rank = 22` (K7) and `hk3 : IntCongr (interMatrix …) k3Form`
(K8). Machinery: `PinPlusKTSpinSigmaStock` package templates (S⁴ `sphere4IntOrientation`/
`sphere4IntPoincareDuality`; S²×S² Gram-pin discharge). Sub-wall: the `IntOrientation.redCompat` mod-2
comparison (the S²×S² arc's noted per-element-vs-functional gap) at the K3 orientation.

**Critical-path summary.** K0 (done) → K1 → {K2→K3→K4→K5→K6} → K7 → K8 → K9 → K10. The recurring
disclosed-atom pattern (K1, K7, K8: "the manifold's H_*/cup form equals the computed lattice") mirrors
the already-shipped S²×S² witness exactly, so those are *statable-now, geometric-atom* bricks; the
genuine new smooth-topology labor is K4–K6 (the quotient + resolution + gluing). No negative-frontier
no-go lies on this path (it is manifold construction, orthogonal to the lattice-Arf / bordism-collapse
settled forks).

## §B. The T⁴ base — foundational brick K0
-/
import Mathlib

namespace SKEFTHawking.KummerK3Base

open scoped Manifold ContDiff

/-- The **flat 4-torus** `T⁴`, realized as the 4-fold product of the standard smooth circle
`Circle = {z : ℂ | ‖z‖ = 1}` (the unit circle in ℂ, Mathlib's smooth 1-manifold / Lie group), i.e.
`T⁴ = (S¹)⁴`. This is the Kummer construction's base (K0): the flat torus `(ℝ/ℤ)⁴` is diffeomorphic to
`(S¹)⁴`, and the product-of-circles model gives its smooth structure for free from Mathlib. The
substantive content of this brick is precisely this modeling choice; the facts below then follow from
the binary-product manifold/topology instances. -/
abbrev TorusFour : Type := Circle × Circle × Circle × Circle

/-- The **product model-with-corners** for `T⁴`: four copies of the circle's model `𝓡 1` (on
`EuclideanSpace ℝ (Fin 1)`), so `T⁴` is modeled on `𝔼¹ × 𝔼¹ × 𝔼¹ × 𝔼¹` (real dimension 4). -/
noncomputable def torusFourModel :
    ModelWithCorners ℝ (EuclideanSpace ℝ (Fin 1) × EuclideanSpace ℝ (Fin 1) ×
        EuclideanSpace ℝ (Fin 1) × EuclideanSpace ℝ (Fin 1))
      (ModelProd (EuclideanSpace ℝ (Fin 1)) (ModelProd (EuclideanSpace ℝ (Fin 1))
        (ModelProd (EuclideanSpace ℝ (Fin 1)) (EuclideanSpace ℝ (Fin 1))))) :=
  (𝓡 1).prod ((𝓡 1).prod ((𝓡 1).prod (𝓡 1)))

/-- `T⁴` is **nonempty** — a genuine (non-degenerate) manifold. Witnessed by the group identity
`(1,1,1,1)` (each circle factor contains `1 = exp(0)`). -/
theorem torusFour_nonempty : Nonempty TorusFour := ⟨(1, 1, 1, 1)⟩

/-- `T⁴` is **Hausdorff** (`T2Space`) — inherited from the circle's metric topology through the
product. -/
theorem torusFour_t2Space : T2Space TorusFour := inferInstance

/-- `T⁴` is **compact** — the closed half of "closed 4-manifold" (each `S¹` is compact, product of
finitely many compacts is compact). -/
theorem torusFour_compactSpace : CompactSpace TorusFour := inferInstance

/-- `T⁴` is a **charted space** modeled on `𝔼¹ × 𝔼¹ × 𝔼¹ × 𝔼¹` — it has an atlas of charts into
Euclidean space (the binary-product `ChartedSpace` instance, iterated). `ChartedSpace` is data, so this
is a `def` exhibiting the concrete atlas witness. -/
@[reducible] noncomputable def torusFourChartedSpace :
    ChartedSpace (ModelProd (EuclideanSpace ℝ (Fin 1))
      (ModelProd (EuclideanSpace ℝ (Fin 1))
        (ModelProd (EuclideanSpace ℝ (Fin 1)) (EuclideanSpace ℝ (Fin 1))))) TorusFour :=
  inferInstance

/-- `T⁴` is a **smooth (`C^ω`) manifold** on the product model `torusFourModel` — the analytic
smoothness of the circle transfers through the binary-product `IsManifold` instance. Together with
`torusFour_compactSpace` and `torusFourModel_boundaryless` this is "smooth closed 4-manifold". -/
theorem torusFour_isManifold :
    IsManifold ((𝓡 1).prod ((𝓡 1).prod ((𝓡 1).prod (𝓡 1)))) ω TorusFour := inferInstance

/-- `T⁴` is a **Lie group** (`(S¹)⁴`, the compact abelian Lie group `𝕋⁴`) — the group multiplication
and inversion are smooth for `torusFourModel`, from the circle's Lie-group structure through the
binary-product `Prod.instLieGroup`. This is the seed of the K9 spin brick: a Lie group is
parallelizable (its tangent bundle is trivialized by left-invariant frames), hence has `w₂ = 0`, hence
is spin — so `T⁴`, and after resolution the Kummer K3, carry the spin tangential structure the
generator needs. (The parallelizable ⟹ spin chain is not yet in Mathlib; this fact is its foothold.) -/
theorem torusFour_lieGroup :
    LieGroup ((𝓡 1).prod ((𝓡 1).prod ((𝓡 1).prod (𝓡 1)))) ω TorusFour := inferInstance

/-- The product model is **boundaryless** — the no-boundary half of "closed 4-manifold" (`𝓡 1` is
boundaryless; products of boundaryless models are boundaryless). -/
theorem torusFourModel_boundaryless :
    ((𝓡 1).prod ((𝓡 1).prod ((𝓡 1).prod (𝓡 1))) :
      ModelWithCorners ℝ _ _).Boundaryless := inferInstance

/-- **`T⁴` is 4-dimensional**: its model vector space `𝔼¹ × 𝔼¹ × 𝔼¹ × 𝔼¹` has real dimension 4
(`1+1+1+1`). The falsifiable numeric pin that makes `TorusFour` a *4*-manifold. -/
theorem torusFour_model_finrank :
    Module.finrank ℝ (EuclideanSpace ℝ (Fin 1) × EuclideanSpace ℝ (Fin 1) ×
      EuclideanSpace ℝ (Fin 1) × EuclideanSpace ℝ (Fin 1)) = 4 := by
  simp [Module.finrank_prod]

end SKEFTHawking.KummerK3Base
