/-
# Phase 5q.H — the 16 exceptional classes, as actual elements of `H₂(K3;ℤ)`

The `hfam`/geo-datum lanes (`KummerK3GeometricFamily`, `KummerK3CapDualFamily`) reduced the welded
`K3`'s Gram obligation to three tabulations, of which the `⟨−2⟩¹⁶` block is a statement about the 16
exceptional `(−2)`-spheres of the resolution. This module builds those 16 classes on the **actual
welded carrier** — no hypothesis, no `Classical.choice` over an existential, no placeholder.

## What is constructed

* `eCopyC c : C(E, K3)` — the inclusion of the `c`-th resolution piece, from
  `KummerWeld.isClosedEmbedding_eCopy`;
* `eGen : H₂(E;ℤ)` — the zero-section generator, pinned by
  `KummerBaseSphereH2Int.resEH2_generator_pin` (`resEH2EquivInt eGen = 1`);
* **`excClass c : H₂(K3;ℤ)`** — the `c`-th exceptional class, the pushforward of `eGen`.

## What is proved (and why it is not vacuous)

* `span_eGen : span ℤ {eGen} = ⊤` — `H₂(E;ℤ)` really is the cyclic group on `eGen` (so `excClass` is
  the image of a *generator*, not of an arbitrary element);
* `range_eCopy_eq_span_excClass` — the **entire** image of `H₂(E_c;ℤ)` in `H₂(K3;ℤ)` is
  `span ℤ {excClass c}`. This is the substantive statement: the `c`-th resolution piece contributes
  to `H₂(K3;ℤ)` exactly the cyclic subgroup generated by `excClass c`, so no *other* choice of class
  from that piece is available, and the `⟨−2⟩¹⁶` block's 16 classes are (up to sign and up to
  multiples, which the Gram then pins) forced.
* `excClass_mem_range` / `excClass_eq_zero_iff_gen_eq_zero` — the bookkeeping that lets the E-lane
  work with `excClass` rather than with the pushforward map.

What is **not** proved here, and is exactly the E-lane's remaining obligation: the intersection
numbers `excClass c · excClass d = −2 δ_{cd}`. Those are cup-product/cap-dual data on the ambient
`K3`, not intrinsic to `E` (`H₂(E;ℤ) = ℤ` carries no self-intersection number by itself — the `−2` is
the Euler number of the normal bundle, which only the ambient weld sees). Stating the classes is a
prerequisite for that tabulation, not a substitute for it.

Kernel-pure (`{propext, Classical.choice, Quot.sound}`); no `sorry`/`native_decide`/`maxHeartbeats`/
axiom.
-/
import Mathlib
import SKEFTHawking.KummerBaseSphereH2Int
import SKEFTHawking.KummerK7Opener

namespace SKEFTHawking.KummerK3ExceptionalClasses

open SKEFTHawking.SingularHomologyInt (Homology)
open SKEFTHawking.SingularFunctorialityInt (Homology.mapInt)
open SKEFTHawking.KummerResolutionPiece (ResE)
open SKEFTHawking.KummerResolutionPieceH2 (zeroSectionC)
open SKEFTHawking.KummerBaseSphereH2Int (baseS2H2EquivInt resEH2EquivInt resEH2_generator_pin)
open SKEFTHawking.KummerWeld (EIndex KummerK3 weldMk isClosedEmbedding_eCopy)
open SKEFTHawking.KummerK7Opener (KummerK3top)

noncomputable section

/-! ## §1. The `c`-th resolution piece, included into the welded carrier -/

/-- **The `c`-th `E`-copy as a bundled `TopCat`.** -/
abbrev EtopR : TopCat := TopCat.of ResE

/-- **The inclusion `E ↪ K3` of the `c`-th resolution piece**, as a `ContinuousMap`. Continuity is
the `IsClosedEmbedding` of `KummerWeld.isClosedEmbedding_eCopy` — the weld glues no two `E`-points,
so each piece sits inside `K3` as a genuine closed subspace. -/
def eCopyC (c : EIndex) : C(↑EtopR, ↑KummerK3top) :=
  ⟨fun e => weldMk (Sum.inr (c, e)), (isClosedEmbedding_eCopy c).continuous⟩

@[simp] theorem eCopyC_apply (c : EIndex) (e : ResE) : eCopyC c e = weldMk (Sum.inr (c, e)) := rfl

/-! ## §2. The generator of `H₂(E;ℤ)` -/

/-- **The zero-section generator of `H₂(E;ℤ)`** — the pushforward along the zero section of the base
sphere's generator. `KummerBaseSphereH2Int.resEH2_generator_pin` pins it: `resEH2EquivInt eGen = 1`. -/
def eGen : Homology EtopR 2 := Homology.mapInt zeroSectionC 2 (baseS2H2EquivInt.symm 1)

theorem resEH2EquivInt_eGen : resEH2EquivInt eGen = 1 := resEH2_generator_pin

/-- **`H₂(E;ℤ)` is the cyclic group generated by `eGen`.** Not merely "`H₂(E;ℤ) ≅ ℤ`": the named
class `eGen` *is* a generator, so a construction that pushes `eGen` forward pushes forward everything
the piece has to offer in degree 2. -/
theorem span_eGen : Submodule.span ℤ ({eGen} : Set (Homology EtopR 2)) = ⊤ := by
  refine Submodule.eq_top_iff'.mpr fun x => ?_
  refine Submodule.mem_span_singleton.mpr ⟨resEH2EquivInt x, ?_⟩
  refine resEH2EquivInt.injective ?_
  rw [map_smul, resEH2EquivInt_eGen, smul_eq_mul, mul_one]

/-! ## §3. The 16 exceptional classes of the welded `K3` -/

/-- **THE `c`-TH EXCEPTIONAL CLASS `E_c ∈ H₂(K3;ℤ)`** — the image of the zero-section generator of
the `c`-th resolution piece under the weld inclusion. One class per fixed point of `τ`
(`KummerWeld.eIndex_card : Fintype.card EIndex = 16`), and these are the 16 classes whose Gram block
the `⟨−2⟩¹⁶` half of `LatticeSigFullRank.kummerSubForm` asserts. -/
def excClass (c : EIndex) : Homology KummerK3top 2 := Homology.mapInt (eCopyC c) 2 eGen

theorem excClass_def (c : EIndex) : excClass c = Homology.mapInt (eCopyC c) 2 eGen := rfl

/-- `excClass c` lies in the image of the `c`-th piece's `H₂`. -/
theorem excClass_mem_range (c : EIndex) :
    excClass c ∈ LinearMap.range (Homology.mapInt (eCopyC c) 2) :=
  ⟨eGen, rfl⟩

/-- **THE STRUCTURAL STATEMENT: the `c`-th resolution piece contributes exactly `ℤ · E_c`.**

`span ℤ {excClass c}` is the *whole* image of `H₂(E_c;ℤ)` in `H₂(K3;ℤ)`. Consequently the
`⟨−2⟩¹⁶` block of the Kummer geometric family has no freedom in its choice of classes beyond an
integer multiple: any class of `H₂(K3;ℤ)` coming from the `c`-th piece is `n · excClass c`, and the
diagonal entry `−2` then pins `n = ±1`. -/
theorem range_eCopy_eq_span_excClass (c : EIndex) :
    LinearMap.range (Homology.mapInt (eCopyC c) 2) = Submodule.span ℤ {excClass c} := by
  rw [← Submodule.map_top, ← span_eGen, Submodule.map_span, Set.image_singleton]
  rfl

/-- **A class of `H₂(K3;ℤ)` pushed from the `c`-th piece is an integer multiple of `E_c`.** The
usable form of §3's structural statement for the E-lane. -/
theorem exists_smul_excClass (c : EIndex) (x : Homology EtopR 2) :
    ∃ n : ℤ, Homology.mapInt (eCopyC c) 2 x = n • excClass c := by
  have hx : Homology.mapInt (eCopyC c) 2 x ∈ Submodule.span ℤ ({excClass c} : Set _) := by
    rw [← range_eCopy_eq_span_excClass c]
    exact ⟨x, rfl⟩
  obtain ⟨n, hn⟩ := Submodule.mem_span_singleton.mp hx
  exact ⟨n, hn.symm⟩

/-- **`E_c = 0` exactly when the `c`-th piece's `H₂` dies in `K3`.** Records that `excClass` is not
secretly a trivial construction: it vanishes only in the degenerate case in which the whole image of
`H₂(E_c;ℤ) = ℤ` collapses, which the K7 rank-22 accounting rules out for the real weld. -/
theorem excClass_eq_zero_iff (c : EIndex) :
    excClass c = 0 ↔ LinearMap.range (Homology.mapInt (eCopyC c) 2) = ⊥ := by
  rw [range_eCopy_eq_span_excClass c, Submodule.span_singleton_eq_bot]

end

end SKEFTHawking.KummerK3ExceptionalClasses
