/-
# Phase 5q.H — the `b₂` residual, resharpened: **one generator**, not "no 2-torsion"

`KummerPieceCollarInt.pairH2TwoTorsionFree_iff_outerE` made the last open input to
`kummerK3_b2_target` concrete: `M := H₂(E, {fiberNorm ≥ 1/2}; ℤ)` must have no 2-torsion, where `E`
is the two-chart `𝒪(−2)` model. This module replaces that obligation by a **strictly
geometric-shaped, sign-free** one, and certifies the replacement is an *equivalence*, not merely a
sufficient condition:

> **`OuterECyclic`** — `M` is generated by a single element.

**§1 (algebra).** A cyclic `ℤ`-module with an infinite carrier has no 2-torsion
(`eq_zero_of_two_smul_of_cyclic`): the generator must have infinite order, or the module would be a
finite quotient of `ℤ`.

**§2 (`M` is infinite, UNCONDITIONALLY).** `KummerPairTubeSeparation.pairProj_injective` embeds
`H₂(eImage;ℤ) ≅ ℤ¹⁶` into `PairH2`, and `KummerPieceCollarInt.pairH2SplitOuter` identifies
`PairH2 ≅ (EIndex → M)` over a *finite* index, so `M` cannot be finite (`infinite_outerH2`). This is
the half of "`M ≅ ℤ`" that needs no new geometry — it is already banked in the pair SES.

**§3 (the reduction, both directions).** `pairH2TwoTorsionFree_iff_outerE_cyclic` is a genuine `↔`:
cyclicity gives the residual by §1+§2, and conversely a 2-torsion-free `PairH2` is `ℤ¹⁶`
(`pairH2_equiv_of_twoTorsionFree`), which forces the sixteenth-root factor `M` to be `ℤ`, hence
cyclic. `kummerK3_b2_target_of_outerE_cyclic` is the headline consumer.

**Why this is a better target than "no 2-torsion".** The residual's geometric content is the Euler
number `−2`: the relative fiber disk `F` satisfies `2·[F] = [S²]`. Proving *that* identity requires
pinning a generator of `H₂(E;ℤ)`, an orientation and a sign. Cyclicity asks only that *some* class
generate — no generator identification, no orientation convention, no sign. It is what a relative
Mayer–Vietoris over the two charts delivers directly (both chart pairs contribute the same fiber-disk
class), and §3 certifies nothing is lost by asking for it instead.

Kernel-pure (`{propext, Classical.choice, Quot.sound}`); no `sorry`, no new axiom, no
`native_decide`, no `maxHeartbeats`.
-/
import Mathlib
import SKEFTHawking.KummerPieceCollarInt
import SKEFTHawking.KummerPairHalving

open SKEFTHawking.SingularRelHomologyInt
open SKEFTHawking.SingularHomologyInt (Homology)
open SKEFTHawking.KummerWeld (EIndex)
open SKEFTHawking.KummerPairTubeSeparation
  (ESub CollarInE PairH2 PairH2TwoTorsionFree pairProj pairProj_injective
    pairH2TwoTorsionFree_iff_torsion_eq_bot)
open SKEFTHawking.KummerPairTransportInt (ResEtop)
open SKEFTHawking.KummerPieceCollarInt (outerE pairH2SplitOuter pairH2TwoTorsionFree_iff_outerE)

namespace SKEFTHawking.KummerPieceCollarCyclicInt

noncomputable section

/-! ## §1. A cyclic `ℤ`-module with infinite carrier has no 2-torsion -/

/-- In a cyclic `ℤ`-module with an infinite carrier the generator has infinite order: otherwise the
module would be the image of a finite range of multiples. -/
theorem infinite_order_of_cyclic {M : Type*} [AddCommGroup M] [Infinite M] {a : M}
    (hgen : ∀ m : M, ∃ k : ℤ, m = k • a) {j : ℤ} (hj : j • a = 0) : j = 0 := by
  by_contra hj0
  have hN : 0 < j.natAbs := Int.natAbs_pos.mpr hj0
  have hNa : ((j.natAbs : ℤ)) • a = 0 := by
    rcases Int.natAbs_eq j with h | h
    · rw [← h]; exact hj
    · have : ((j.natAbs : ℤ)) = -j := by omega
      rw [this, neg_smul, hj, neg_zero]
  have hNpos : (0 : ℤ) < (j.natAbs : ℤ) := by exact_mod_cast hN
  have hsurj : Function.Surjective (fun r : Fin j.natAbs => ((r : ℕ) : ℤ) • a) := by
    intro m
    obtain ⟨k, rfl⟩ := hgen m
    have hnn : 0 ≤ k % (j.natAbs : ℤ) := Int.emod_nonneg k (ne_of_gt hNpos)
    have hlt : k % (j.natAbs : ℤ) < (j.natAbs : ℤ) := Int.emod_lt_of_pos k hNpos
    refine ⟨⟨(k % (j.natAbs : ℤ)).toNat, by omega⟩, ?_⟩
    have hcast : (((k % (j.natAbs : ℤ)).toNat : ℕ) : ℤ) = k % (j.natAbs : ℤ) :=
      Int.toNat_of_nonneg hnn
    show (((k % (j.natAbs : ℤ)).toNat : ℕ) : ℤ) • a = k • a
    rw [hcast]
    have hdec : k = (k / (j.natAbs : ℤ)) * (j.natAbs : ℤ) + k % (j.natAbs : ℤ) := by
      rw [mul_comm]; exact (Int.mul_ediv_add_emod k _).symm
    conv_rhs => rw [hdec]
    rw [add_smul, mul_smul, hNa, smul_zero, zero_add]
  exact (Set.infinite_univ (α := M)) (Set.Finite.subset (Set.finite_range _) (fun m _ => hsurj m))

/-- **A cyclic `ℤ`-module with an infinite carrier has no 2-torsion.** The algebraic engine of the
reduction: `2 • m = 0` with `m = k • a` gives `(2k) • a = 0`, so `2k = 0` by
`infinite_order_of_cyclic`, so `k = 0`. -/
theorem eq_zero_of_two_smul_of_cyclic {M : Type*} [AddCommGroup M] [Infinite M] {a : M}
    (hgen : ∀ m : M, ∃ k : ℤ, m = k • a) {m : M} (hm : (2 : ℤ) • m = 0) : m = 0 := by
  obtain ⟨k, rfl⟩ := hgen m
  have h2 : ((2 : ℤ) * k) • a = 0 := by rw [mul_smul]; exact hm
  have hk : (2 : ℤ) * k = 0 := infinite_order_of_cyclic hgen h2
  have : k = 0 := by omega
  rw [this, zero_smul]

/-! ## §2. `M = H₂(E, {fiberNorm ≥ 1/2}; ℤ)` is infinite, unconditionally -/

/-- **`PairH2` is infinite** — `H₂(eImage;ℤ) ≅ ℤ¹⁶` embeds into it (`pairProj_injective`). -/
theorem infinite_pairH2 : Infinite PairH2 := by
  haveI : Infinite (EIndex → ℤ) := by
    haveI : Nonempty EIndex :=
      Fintype.card_pos_iff.mp (by rw [SKEFTHawking.KummerWeld.eIndex_card]; norm_num)
    exact Infinite.of_injective (fun n : ℤ => Function.const EIndex n)
      (fun _ _ h => congrFun h (Classical.arbitrary EIndex))
  haveI : Infinite (Homology ESub 2) :=
    Infinite.of_injective _
      (SKEFTHawking.KummerK7MVAssembly.eImageH2EquivInt.symm.injective)
  exact Infinite.of_injective pairProj pairProj_injective

/-- **The concrete per-piece group is infinite** — with `PairH2 ≅ (EIndex → M)` over the finite index
`EIndex`, a finite `M` would make `PairH2` finite. Unconditional: it uses only the already-landed
pair short exact sequence, no new geometry. -/
theorem infinite_outerH2 : Infinite (RelHomologyInt (X := ResEtop) outerE 2) := by
  haveI := infinite_pairH2
  rw [← not_finite_iff_infinite]
  intro hfin
  haveI : Finite (EIndex → RelHomologyInt (X := ResEtop) outerE 2) := Pi.finite
  haveI : Finite PairH2 := Finite.of_equiv _ pairH2SplitOuter.symm.toEquiv
  exact (not_finite PairH2)

/-! ## §3. The reduction: cyclicity ⟺ the `b₂` residual -/

/-- **The resharpened residual** — `H₂(E, {fiberNorm ≥ 1/2}; ℤ)` is generated by one element. -/
def OuterECyclic : Prop :=
  ∃ a : RelHomologyInt (X := ResEtop) outerE 2,
    ∀ m : RelHomologyInt (X := ResEtop) outerE 2, ∃ k : ℤ, m = k • a

/-- **Cyclicity supplies the `b₂` residual.** §1 (cyclic + infinite ⟹ no 2-torsion) applied to the
unconditional §2, then `pairH2TwoTorsionFree_iff_outerE`. -/
theorem pairH2TwoTorsionFree_of_outerE_cyclic (h : OuterECyclic) : PairH2TwoTorsionFree := by
  obtain ⟨a, hgen⟩ := h
  haveI := infinite_outerH2
  exact pairH2TwoTorsionFree_iff_outerE.mpr fun m hm => eq_zero_of_two_smul_of_cyclic hgen hm

/-- **The headline consumer** — cyclicity of the single concrete group closes
`kummerK3_b2_target` (`H₂(K3;ℤ) ≅ ℤ²²`) through
`KummerPairHalving.pairH2TwoTorsionFree_iff_exceptional_halvable` and
`kummerK3_b2_target_of_exceptional_halvable`. -/
theorem kummerK3_b2_target_of_outerE_cyclic (h : OuterECyclic) :
    SKEFTHawking.KummerK7Opener.kummerK3_b2_target :=
  SKEFTHawking.KummerPairHalving.kummerK3_b2_target_of_exceptional_halvable
    (SKEFTHawking.KummerPairHalving.pairH2TwoTorsionFree_iff_exceptional_halvable.mp
      (pairH2TwoTorsionFree_of_outerE_cyclic h))

/-! ## §4. The converse — the residual forces cyclicity (the equivalence certificate) -/

/-- The diagonal embedding `M ↪ PairH2` supplied by the concrete splitting (all sixteen coordinates
equal). Injective because `EIndex` is nonempty; no `DecidableEq EIndex` needed. -/
def outerDiag : RelHomologyInt (X := ResEtop) outerE 2 →ₗ[ℤ] PairH2 :=
  pairH2SplitOuter.symm.toLinearMap.comp
    (LinearMap.pi fun _ : EIndex => LinearMap.id
      (R := ℤ) (M := RelHomologyInt (X := ResEtop) outerE 2))

theorem outerDiag_injective : Function.Injective outerDiag := by
  haveI : Nonempty EIndex :=
    Fintype.card_pos_iff.mp (by rw [SKEFTHawking.KummerWeld.eIndex_card]; norm_num)
  intro s t hst
  have h1 : (fun _ : EIndex => s) = (fun _ : EIndex => t) :=
    pairH2SplitOuter.symm.injective hst
  exact congrFun h1 (Classical.arbitrary EIndex)

/-- The `c`-th coordinate projection `PairH2 ↠ M`. -/
def outerProj (c : EIndex) : PairH2 →ₗ[ℤ] RelHomologyInt (X := ResEtop) outerE 2 :=
  (LinearMap.proj (R := ℤ) (φ := fun _ : EIndex => RelHomologyInt (X := ResEtop) outerE 2)
    c).comp pairH2SplitOuter.toLinearMap

theorem outerProj_surjective (c : EIndex) : Function.Surjective (outerProj c) := fun m =>
  ⟨pairH2SplitOuter.symm (Function.const EIndex m), by
    simp [outerProj, LinearEquiv.apply_symm_apply]⟩

instance instOuterFinite : Module.Finite ℤ (RelHomologyInt (X := ResEtop) outerE 2) := by
  haveI : Nonempty EIndex :=
    Fintype.card_pos_iff.mp (by rw [SKEFTHawking.KummerWeld.eIndex_card]; norm_num)
  exact Module.Finite.of_surjective (outerProj (Classical.arbitrary EIndex))
    (outerProj_surjective (Classical.arbitrary EIndex))

/-- **The concrete per-piece group is torsion-free once the residual holds** — it embeds `ℤ`-linearly
into `PairH2`, whose torsion is `⊥`. -/
theorem outer_torsion_eq_bot (h : PairH2TwoTorsionFree) :
    Submodule.torsion ℤ (RelHomologyInt (X := ResEtop) outerE 2) = ⊥ := by
  have hPair : Submodule.torsion ℤ PairH2 = ⊥ := pairH2TwoTorsionFree_iff_torsion_eq_bot.mp h
  rw [Submodule.eq_bot_iff]
  intro t ht
  obtain ⟨⟨n, hn⟩, hsmul⟩ := (Submodule.mem_torsion_iff _).mp ht
  have h1 : n • outerDiag t = 0 := by rw [← map_smul]; simpa using congrArg outerDiag hsmul
  have h2 : outerDiag t ∈ Submodule.torsion ℤ PairH2 :=
    (Submodule.mem_torsion_iff _).mpr ⟨⟨n, hn⟩, h1⟩
  rw [hPair, Submodule.mem_bot] at h2
  exact outerDiag_injective (by rw [h2, map_zero])

/-- **The residual forces `M ≅ ℤ`**, hence cyclicity: `PairH2 ≅ ℤ¹⁶` and `PairH2 ≅ M¹⁶`, so the
sixteen equal free factors each have rank `1`. -/
theorem outerE_cyclic_of_pairH2TwoTorsionFree (h : PairH2TwoTorsionFree) : OuterECyclic := by
  classical
  haveI : Module.IsTorsionFree ℤ (RelHomologyInt (X := ResEtop) outerE 2) :=
    Submodule.isTorsionFree_iff_torsion_eq_bot.mpr (outer_torsion_eq_bot h)
  haveI : Module.Free ℤ (RelHomologyInt (X := ResEtop) outerE 2) :=
    Module.free_of_finite_type_torsion_free'
  obtain ⟨e⟩ := SKEFTHawking.KummerPairTubeSeparation.pairH2_equiv_of_twoTorsionFree h
  have hPair : Module.finrank ℤ PairH2 = 16 := by
    rw [e.finrank_eq, SKEFTHawking.KummerPairTubeSeparation.finrank_pairH2_source]
  have hsplit : Module.finrank ℤ PairH2
      = 16 * Module.finrank ℤ (RelHomologyInt (X := ResEtop) outerE 2) := by
    rw [pairH2SplitOuter.finrank_eq, Module.finrank_pi_fintype,
      Finset.sum_const, Finset.card_univ, SKEFTHawking.KummerWeld.eIndex_card, smul_eq_mul]
  have hone : Module.finrank ℤ (RelHomologyInt (X := ResEtop) outerE 2) = 1 := by
    rw [hPair] at hsplit; omega
  have hcards : Fintype.card (Fin 1)
      = Fintype.card (Module.Free.ChooseBasisIndex ℤ (RelHomologyInt (X := ResEtop) outerE 2)) := by
    rw [Fintype.card_fin, ← Module.finrank_eq_card_chooseBasisIndex, hone]
  set eM : RelHomologyInt (X := ResEtop) outerE 2 ≃ₗ[ℤ] (Fin 1 → ℤ) :=
    (Module.Free.chooseBasis ℤ (RelHomologyInt (X := ResEtop) outerE 2)).equivFun.trans
      (LinearEquiv.funCongrLeft ℤ ℤ (Fintype.equivOfCardEq hcards)) with heM
  refine ⟨eM.symm (fun _ => 1), fun m => ⟨eM m 0, ?_⟩⟩
  have : eM m = (eM m 0) • (fun _ : Fin 1 => (1 : ℤ)) := by
    funext j
    have : j = 0 := Subsingleton.elim _ _
    subst this
    simp
  calc m = eM.symm (eM m) := (eM.symm_apply_apply m).symm
    _ = eM.symm ((eM m 0) • (fun _ : Fin 1 => (1 : ℤ))) := by rw [← this]
    _ = (eM m 0) • eM.symm (fun _ : Fin 1 => (1 : ℤ)) := by rw [map_smul]

/-- **The equivalence certificate.** The substituted obligation `OuterECyclic` — "`H₂(E, {fiberNorm ≥
1/2}; ℤ)` is generated by one element" — is *equivalent* to the `b₂` residual
`PairH2TwoTorsionFree`, not merely sufficient for it. So aiming the remaining geometry at cyclicity
loses nothing. -/
theorem pairH2TwoTorsionFree_iff_outerE_cyclic : PairH2TwoTorsionFree ↔ OuterECyclic :=
  ⟨outerE_cyclic_of_pairH2TwoTorsionFree, pairH2TwoTorsionFree_of_outerE_cyclic⟩

end

end SKEFTHawking.KummerPieceCollarCyclicInt
