/-
# Phase 5q.H — input (C0) of the `b₂` residual, DISCHARGED

`KummerCollarPairSplitInt` / `KummerChartNbhdInt` reduced the last open input to
`H₂(K3;ℤ) ≅ ℤ²²` to two statements about the pair `(E, splitBOpen r)`:

* **(C0)** `H₂(E, splitBOpen r; ℤ) = 0`, and
* **(C1)** `H₂(splitBOpen r, outerE; ℤ)` cyclic.

This module **proves (C0) outright**, at the ambient level, for every `0 ≤ r < 1`.

## The observation

`splitBOpen r = outerE ∪ (deepChart0 r)ᶜ`, so its complement is

> `coreE r = chart0 '' {(z, w) | ‖z‖ ≤ r ∧ ‖w‖ < 1/2}`

— a **`D² × D̊²` core inside the chart-0 bidisk**, sitting entirely away from the weld
(`r < 1`). (C0) is therefore a *local-homology* statement `H₂(E | coreE r) = 0`, and
`SingularStarComplementRetractInt.relHomology_compl_eq_zero` kills exactly that: the complement of a
star-shaped body strictly inside the unit ball of `ℝ⁴` has the homology of `S³`, which vanishes in
degree `1`, so the pair group vanishes in degree `2`.

Two things had to be arranged to fire it:

1. **The core is half-open** (`‖w‖ < 1/2`, inherited from the *complement* of the closed collar
   `outerE = {fiberNorm ≥ 1/2}`), so the on-main
   `SingularFlatDiskChartVanishInt.relHomology_chartStar_eq_zero` — which asks for `IsClosed K` —
   does not apply. `SingularChartStarClosureVanishInt` relaxes that to `closure K ⊆ U`, which is all
   the excision cover ever needed; `StarInBall` itself never asked for closedness.
2. **A chart around the core.** The core lies in the *open chart-0 bidisk*
   `U0 = chart0 '' {‖z‖ < 1 ∧ ‖w‖ < 1}`, which is open in `E` (no weld can reach it: a weld forces
   `‖z‖ = 1`) and is carried homeomorphically onto the open `ℝ⁴` box `V0` by halving the two complex
   coordinates. The halving is what puts the core inside the unit ball, as `StarInBall` demands.
   This is a much smaller chart than `KummerHemisphereChartInt`'s weld-crossing `F`: the core never
   meets the equator, so no continuation across the clutch is needed.

## What is left

Only **(C1)**. `outerECyclic_of_cyclic` / `kummerK3_b2_target_of_cyclic` state the headline with
(C0) discharged: `H₂(K3;ℤ) ≅ ℤ²²` now rests on the single hypothesis that
`H₂(splitBOpen r, outerE; ℤ)` is generated by one element. Note this also makes
`KummerChartNbhdInt`'s chart-0 excision route (`relHomologyInt_splitBOpen_eq_zero_of_chart0`, whose
purpose was to reduce (C0) to a chart-local (C0′)) unnecessary: (C0) is proved directly, which is
strictly stronger than assuming (C0′).

§4 records that the reduction is **not vacuous**: `splitBOpen r ≠ univ` (banked) and — the sharp
statement — (C0) *fails* at the smallest admissible subspace `B = outerE`
(`KummerCollarPairSplitInt.not_relHomologyInt_outerE_eq_zero`), so the enlargement really is doing
work and (C1) is not a restatement of the residual.

Kernel-pure (`{propext, Classical.choice, Quot.sound}`); no `sorry`, no new axiom, no
`native_decide`, no `maxHeartbeats`.
-/
import Mathlib
import SKEFTHawking.SingularChartStarClosureVanishInt
import SKEFTHawking.KummerChartNbhdInt
import SKEFTHawking.KummerHemisphereChartInt

open SKEFTHawking.SingularRelHomologyInt (RelHomologyInt)
open SKEFTHawking.SingularEuclideanAcyclic (Eucl)
open SKEFTHawking.SingularStarComplementRetractInt (StarInBall)
open SKEFTHawking.SingularChartStarClosureVanishInt (relHomology_chartStar_closure_eq_zero)
open SKEFTHawking.KummerResolutionPiece (ResE ResChart Disk resSetoid chart0 chart1
  chart0_inj_iff chart0_eq_chart1_iff continuous_chart0)
open SKEFTHawking.KummerPairTransportInt (ResEtop)
open SKEFTHawking.KummerPieceCollarInt (outerE)
open SKEFTHawking.KummerPieceCollarCyclicInt (OuterECyclic kummerK3_b2_target_of_outerE_cyclic)
open SKEFTHawking.KummerChartNbhdInt (deepChartSet deepChart0 chartNbhd1 splitBOpen
  outerE_subset_splitBOpen splitBOpen_ne_univ)
open SKEFTHawking.KummerHemisphereChartInt (zc uc mk4 zc_mk4 uc_mk4 ext4 zc_smul uc_smul
  norm_sq_split)
open SKEFTHawking.SingularRelativeTripleSurjInt (relHomologyInt_cyclic_of_triple)
open SKEFTHawking.SingularExcisionIso (restr)

namespace SKEFTHawking.KummerSplitBCoreVanishInt

noncomputable section

/-! ## §1. The open chart-0 bidisk is a chart of `E` -/

/-- The **open bidisk** of a chart: both coordinates of norm `< 1`. -/
def bidiskOpen : Set ResChart := {p | ‖(p.1 : ℂ)‖ < 1 ∧ ‖(p.2 : ℂ)‖ < 1}

theorem isOpen_bidiskOpen : IsOpen bidiskOpen :=
  (isOpen_lt (continuous_norm.comp (continuous_subtype_val.comp continuous_fst))
    continuous_const).inter
    (isOpen_lt (continuous_norm.comp (continuous_subtype_val.comp continuous_snd))
      continuous_const)

/-- **The open chart-0 region** `U0 ⊆ E` — the image of the open bidisk. It contains no weld: a weld
forces base norm `1`. -/
def U0 : Set ↑ResEtop := chart0 '' bidiskOpen

theorem chart0_injective : Function.Injective chart0 := fun _ _ h => chart0_inj_iff.mp h

/-- No chart-1 point lies in `U0`: a weld would force `‖z‖ = 1` on the chart-0 side. -/
theorem chart1_notMem_U0 (q : ResChart) : chart1 q ∉ U0 := by
  rintro ⟨p, hp, hmk⟩
  obtain ⟨hseam, -, -⟩ := chart0_eq_chart1_iff.mp hmk
  exact absurd hseam (ne_of_lt hp.1)

theorem isOpen_U0 : IsOpen U0 := by
  refine (isQuotientMap_quotient_mk' (s := resSetoid)).isOpen_preimage.mp ?_
  rw [isOpen_sum_iff]
  constructor
  · show IsOpen {p : ResChart | chart0 p ∈ U0}
    have h : {p : ResChart | chart0 p ∈ U0} = bidiskOpen := by
      ext p
      constructor
      · rintro ⟨q, hq, hmk⟩
        rwa [chart0_inj_iff.mp hmk] at hq
      · intro hp; exact ⟨p, hp, rfl⟩
    rw [h]; exact isOpen_bidiskOpen
  · show IsOpen {p : ResChart | chart1 p ∈ U0}
    have h : {p : ResChart | chart1 p ∈ U0} = (∅ : Set ResChart) := by
      ext p; exact ⟨fun hp => (chart1_notMem_U0 p hp).elim, fun hp => hp.elim⟩
    rw [h]; exact isOpen_empty

theorem isEmbedding_chart0 : Topology.IsEmbedding (chart0 : ResChart → ResE) :=
  (Continuous.isClosedEmbedding continuous_chart0 chart0_injective).isEmbedding

theorem isEmbedding_chart0_bidisk :
    Topology.IsEmbedding (fun x : ↥bidiskOpen => chart0 ↑x) :=
  isEmbedding_chart0.comp Topology.IsEmbedding.subtypeVal

/-- **The chart-0 bidisk chart** `bidiskOpen ≃ₜ U0`. -/
def bidiskHomeo : ↥bidiskOpen ≃ₜ ↥U0 :=
  isEmbedding_chart0_bidisk.toHomeomorph.trans
    (Homeomorph.setCongr (by rw [U0, Set.image_eq_range]))

@[simp] theorem bidiskHomeo_coe (x : ↥bidiskOpen) : ((bidiskHomeo x : ↥U0) : ResE) = chart0 ↑x :=
  rfl

/-! ## §2. The Euclidean model: halve both complex coordinates -/

/-- The **halved coordinate map** `D² × D² → ℝ⁴`. Halving is what puts the whole bidisk inside the
unit ball of `ℝ⁴`, which is what `StarInBall` requires of the core. -/
def coord (p : ResChart) : EuclideanSpace ℝ (Fin 4) := mk4 ((p.1 : ℂ) / 2) ((p.2 : ℂ) / 2)

@[simp] theorem zc_coord (p : ResChart) : zc (coord p) = (p.1 : ℂ) / 2 := rfl
@[simp] theorem uc_coord (p : ResChart) : uc (coord p) = (p.2 : ℂ) / 2 := rfl

/-- The Euclidean image of the open bidisk: the open box of half-radius `1/2` in each factor. -/
def V0 : Set (EuclideanSpace ℝ (Fin 4)) := {q | ‖zc q‖ < 1 / 2 ∧ ‖uc q‖ < 1 / 2}

theorem isOpen_V0 : IsOpen V0 :=
  (isOpen_lt (continuous_norm.comp SKEFTHawking.KummerHemisphereChartInt.continuous_zc)
      continuous_const).inter
    (isOpen_lt (continuous_norm.comp SKEFTHawking.KummerHemisphereChartInt.continuous_uc)
      continuous_const)

theorem continuous_mk4 : Continuous (fun q : ℂ × ℂ => mk4 q.1 q.2) := by
  have h : Continuous (fun q : ℂ × ℂ => (![q.1.re, q.1.im, q.2.re, q.2.im] : Fin 4 → ℝ)) := by
    refine continuous_pi fun i => ?_
    fin_cases i
    · exact Complex.continuous_re.comp continuous_fst
    · exact Complex.continuous_im.comp continuous_fst
    · exact Complex.continuous_re.comp continuous_snd
    · exact Complex.continuous_im.comp continuous_snd
  exact (EuclideanSpace.equiv (Fin 4) ℝ).symm.continuous.comp h

theorem continuous_coord : Continuous coord :=
  continuous_mk4.comp
    (((continuous_subtype_val.comp continuous_fst).div_const 2).prodMk
      ((continuous_subtype_val.comp continuous_snd).div_const 2))

/-- The Euclidean-to-chart direction: double the two complex coordinates. -/
def uncoord (q : ↥V0) : ResChart :=
  (⟨2 * zc (q : ↑(Eucl 4)), by
      rw [norm_mul]
      have := q.2.1
      simp only [Complex.norm_ofNat]
      linarith⟩,
   ⟨2 * uc (q : ↑(Eucl 4)), by
      rw [norm_mul]
      have := q.2.2
      simp only [Complex.norm_ofNat]
      linarith⟩)

theorem uncoord_mem (q : ↥V0) : uncoord q ∈ bidiskOpen := by
  refine ⟨?_, ?_⟩
  · show ‖2 * zc (q : ↑(Eucl 4))‖ < 1
    rw [norm_mul]
    have := q.2.1
    simp only [Complex.norm_ofNat]
    linarith
  · show ‖2 * uc (q : ↑(Eucl 4))‖ < 1
    rw [norm_mul]
    have := q.2.2
    simp only [Complex.norm_ofNat]
    linarith

theorem coord_mem (x : ↥bidiskOpen) : coord ↑x ∈ V0 := by
  refine ⟨?_, ?_⟩
  · show ‖((x : ResChart).1 : ℂ) / 2‖ < 1 / 2
    rw [norm_div]
    have := x.2.1
    simp only [Complex.norm_ofNat]
    linarith
  · show ‖((x : ResChart).2 : ℂ) / 2‖ < 1 / 2
    rw [norm_div]
    have := x.2.2
    simp only [Complex.norm_ofNat]
    linarith

/-- **The Euclidean chart** `bidiskOpen ≃ₜ V0`. -/
def coordHomeo : ↥bidiskOpen ≃ₜ ↥V0 where
  toFun x := ⟨coord ↑x, coord_mem x⟩
  invFun q := ⟨uncoord q, uncoord_mem q⟩
  left_inv x := by
    refine Subtype.ext (Prod.ext (Subtype.ext ?_) (Subtype.ext ?_))
    · show 2 * (((x : ResChart).1 : ℂ) / 2) = ((x : ResChart).1 : ℂ)
      ring
    · show 2 * (((x : ResChart).2 : ℂ) / 2) = ((x : ResChart).2 : ℂ)
      ring
  right_inv q := by
    refine Subtype.ext (ext4 ?_ ?_)
    · show 2 * zc (q : ↑(Eucl 4)) / 2 = zc (q : ↑(Eucl 4))
      ring
    · show 2 * uc (q : ↑(Eucl 4)) / 2 = uc (q : ↑(Eucl 4))
      ring
  continuous_toFun := by
    refine Continuous.subtype_mk ?_ _
    exact continuous_coord.comp continuous_subtype_val
  continuous_invFun := by
    refine Continuous.subtype_mk ?_ _
    refine Continuous.prodMk (Continuous.subtype_mk ?_ _) (Continuous.subtype_mk ?_ _)
    · exact (continuous_const.mul
        (SKEFTHawking.KummerHemisphereChartInt.continuous_zc.comp continuous_subtype_val))
    · exact (continuous_const.mul
        (SKEFTHawking.KummerHemisphereChartInt.continuous_uc.comp continuous_subtype_val))

/-- **The chart of `E` around the chart-0 core**: `U0 ≃ₜ V0`. -/
def chartE : ↥U0 ≃ₜ ↥V0 := bidiskHomeo.symm.trans coordHomeo

theorem chartE_chart0 (x : ↥bidiskOpen) :
    ((chartE (bidiskHomeo x) : ↥V0) : ↑(Eucl 4)) = coord ↑x := by
  show ((coordHomeo (bidiskHomeo.symm (bidiskHomeo x)) : ↥V0) : ↑(Eucl 4)) = coord ↑x
  rw [bidiskHomeo.symm_apply_apply]
  rfl

/-! ## §3. The core, and (C0) -/

/-- **The core** of the splitting: the chart-0 points below the collar over the deep base disk. -/
def coreSet (r : ℝ) : Set ResChart := {p | ‖(p.1 : ℂ)‖ ≤ r ∧ ‖(p.2 : ℂ)‖ < 1 / 2}

/-- The closed body containing the core — its closure is trapped in here. -/
def coreSetCl (r : ℝ) : Set ResChart := {p | ‖(p.1 : ℂ)‖ ≤ r ∧ ‖(p.2 : ℂ)‖ ≤ 1 / 2}

def coreE (r : ℝ) : Set ↑ResEtop := chart0 '' coreSet r

/-- **The core is the complement of `splitBOpen r`.** `splitBOpen r = outerE ∪ (deepChart0 r)ᶜ`, so
missing it means being simultaneously below the collar and deep in chart 0. -/
theorem coreE_eq_compl (r : ℝ) : coreE r = (splitBOpen r)ᶜ := by
  ext y
  constructor
  · rintro ⟨p, hp, rfl⟩ hmem
    rcases hmem with hout | hnb
    · have : (1 : ℝ) / 2 ≤ ‖(p.2 : ℂ)‖ := hout
      linarith [hp.2]
    · exact hnb ⟨p, hp.1, rfl⟩
  · intro hy
    have hnot : y ∉ outerE ∧ y ∉ chartNbhd1 r := by
      constructor
      · exact fun h => hy (Or.inl h)
      · exact fun h => hy (Or.inr h)
    obtain ⟨p, hp, rfl⟩ : y ∈ deepChart0 r := by
      by_contra hcon
      exact hnot.2 hcon
    refine ⟨p, ⟨hp, ?_⟩, rfl⟩
    by_contra hcon
    exact hnot.1 (le_of_not_gt hcon)

theorem coreSet_subset_cl (r : ℝ) : coreSet r ⊆ coreSetCl r :=
  fun _ hp => ⟨hp.1, le_of_lt hp.2⟩

theorem isCompact_coreSetCl (r : ℝ) : IsCompact (coreSetCl r) := by
  refine IsCompact.of_isClosed_subset isCompact_univ ?_ (Set.subset_univ _)
  exact (isClosed_le (continuous_norm.comp (continuous_subtype_val.comp continuous_fst))
    continuous_const).inter
    (isClosed_le (continuous_norm.comp (continuous_subtype_val.comp continuous_snd))
      continuous_const)

theorem isClosed_coreECl (r : ℝ) : IsClosed (chart0 '' coreSetCl r) :=
  ((isCompact_coreSetCl r).image continuous_chart0).isClosed

theorem coreSetCl_subset_bidisk {r : ℝ} (hr : r < 1) : coreSetCl r ⊆ bidiskOpen := by
  rintro p ⟨h1, h2⟩
  exact ⟨lt_of_le_of_lt h1 hr, lt_of_le_of_lt h2 (by norm_num)⟩

theorem closure_coreE_subset {r : ℝ} (hr : r < 1) : closure (coreE r) ⊆ U0 := by
  refine (closure_minimal ?_ (isClosed_coreECl r)).trans ?_
  · exact Set.image_mono (coreSet_subset_cl r)
  · exact Set.image_mono (coreSetCl_subset_bidisk hr)

/-- The Euclidean model of the core: the halved box. -/
def coreC (r : ℝ) : Set (EuclideanSpace ℝ (Fin 4)) := {q | ‖zc q‖ ≤ r / 2 ∧ ‖uc q‖ < 1 / 4}

def coreCCl (r : ℝ) : Set (EuclideanSpace ℝ (Fin 4)) := {q | ‖zc q‖ ≤ r / 2 ∧ ‖uc q‖ ≤ 1 / 4}

theorem isClosed_coreCCl (r : ℝ) : IsClosed (coreCCl r) :=
  (isClosed_le (continuous_norm.comp SKEFTHawking.KummerHemisphereChartInt.continuous_zc)
      continuous_const).inter
    (isClosed_le (continuous_norm.comp SKEFTHawking.KummerHemisphereChartInt.continuous_uc)
      continuous_const)

theorem coreC_subset_coreCCl (r : ℝ) : coreC r ⊆ coreCCl r := by
  rintro q ⟨h1, h2⟩
  show ‖zc q‖ ≤ r / 2 ∧ ‖uc q‖ ≤ 1 / 4
  exact ⟨h1, le_of_lt h2⟩

theorem closure_coreC_subset {r : ℝ} (hr : r < 1) : closure (coreC r) ⊆ V0 := by
  refine (closure_minimal (coreC_subset_coreCCl r) (isClosed_coreCCl r)).trans ?_
  rintro q ⟨h1, h2⟩
  exact ⟨lt_of_le_of_lt h1 (by linarith), lt_of_le_of_lt h2 (by norm_num)⟩

/-- **The core is star-shaped strictly inside the unit ball** of `ℝ⁴` — the one geometric input the
star-complement retraction needs. Halving the coordinates is what makes the norm bound hold. -/
theorem starInBall_coreC {r : ℝ} (hr0 : 0 ≤ r) (hr1 : r < 1) : StarInBall (coreC r) where
  zero_mem := by
    show ‖zc (0 : EuclideanSpace ℝ (Fin 4))‖ ≤ r / 2
      ∧ ‖uc (0 : EuclideanSpace ℝ (Fin 4))‖ < 1 / 4
    have hz : zc (0 : EuclideanSpace ℝ (Fin 4)) = 0 := by
      apply Complex.ext <;> simp [SKEFTHawking.KummerHemisphereChartInt.zc]
    have hu : uc (0 : EuclideanSpace ℝ (Fin 4)) = 0 := by
      apply Complex.ext <;> simp [SKEFTHawking.KummerHemisphereChartInt.uc]
    rw [hz, hu, norm_zero]
    constructor
    · linarith
    · norm_num
  smul_mem := by
    rintro p ⟨h1, h2⟩ s hs0 hs1
    refine ⟨?_, ?_⟩
    · show ‖zc (s • p)‖ ≤ r / 2
      rw [zc_smul, norm_mul, Complex.norm_real, Real.norm_eq_abs, abs_of_nonneg hs0]
      nlinarith [norm_nonneg (zc p)]
    · show ‖uc (s • p)‖ < 1 / 4
      rw [uc_smul, norm_mul, Complex.norm_real, Real.norm_eq_abs, abs_of_nonneg hs0]
      nlinarith [norm_nonneg (uc p)]
  norm_lt := by
    rintro p ⟨h1, h2⟩
    have hsplit := norm_sq_split p
    nlinarith [norm_nonneg p, norm_nonneg (zc p), norm_nonneg (uc p)]

/-- The chart matches the core with its Euclidean model. -/
theorem chartE_compat {r : ℝ} (u : ↥U0) :
    ((chartE u : ↥V0) : ↑(Eucl 4)) ∈ coreC r ↔ (u : ↑ResEtop) ∈ coreE r := by
  obtain ⟨x, rfl⟩ := bidiskHomeo.surjective u
  rw [chartE_chart0 x]
  constructor
  · rintro ⟨h1, h2⟩
    have hh1 : ‖((x : ResChart).1 : ℂ) / 2‖ ≤ r / 2 := h1
    have hh2 : ‖((x : ResChart).2 : ℂ) / 2‖ < 1 / 4 := h2
    rw [norm_div] at hh1 hh2
    simp only [Complex.norm_ofNat] at hh1 hh2
    exact ⟨↑x, ⟨by linarith, by linarith⟩, rfl⟩
  · rintro ⟨p, hp, hmk⟩
    have hpx : p = (x : ResChart) := chart0_inj_iff.mp hmk
    rw [hpx] at hp
    refine ⟨?_, ?_⟩
    · show ‖((x : ResChart).1 : ℂ) / 2‖ ≤ r / 2
      rw [norm_div]
      simp only [Complex.norm_ofNat]
      linarith [hp.1]
    · show ‖((x : ResChart).2 : ℂ) / 2‖ < 1 / 4
      rw [norm_div]
      simp only [Complex.norm_ofNat]
      linarith [hp.2]

/-- **Input (C0), DISCHARGED.** `H₂(E, splitBOpen r; ℤ) = 0` for every `0 ≤ r < 1` — no hypothesis.

The complement of `splitBOpen r` is a `D² × D̊²` core inside the open chart-0 bidisk; the chart
`chartE` carries it onto a star-shaped body strictly inside the unit ball of `ℝ⁴`, whose complement
has the homology of `S³`. -/
theorem relHomologyInt_splitBOpen_eq_zero {r : ℝ} (hr0 : 0 ≤ r) (hr1 : r < 1) :
    ∀ x : RelHomologyInt (X := ResEtop) (splitBOpen r) 2, x = 0 := by
  have hcore : (coreE r)ᶜ = splitBOpen r := by rw [coreE_eq_compl, compl_compl]
  rw [← hcore]
  intro y
  exact relHomology_chartStar_closure_eq_zero (m := 3) isOpen_U0 (closure_coreE_subset hr1)
    isOpen_V0 (closure_coreC_subset hr1) chartE (fun u => chartE_compat u)
    (starInBall_coreC hr0 hr1) 0 (by norm_num) y

/-! ## §4. The `b₂` residual on ONE remaining input -/

/-- **The `b₂` residual, with (C0) discharged.** Only (C1) — cyclicity of
`H₂(splitBOpen r, outerE; ℤ)` — is left. -/
theorem outerECyclic_of_cyclic {r : ℝ} (hr0 : 0 ≤ r) (hr1 : r < 1)
    (hcyc : ∃ a : RelHomologyInt (restr outerE (splitBOpen r)) 2,
      ∀ x : RelHomologyInt (restr outerE (splitBOpen r)) 2, ∃ k : ℤ, x = k • a) :
    OuterECyclic :=
  relHomologyInt_cyclic_of_triple outerE (splitBOpen r) (outerE_subset_splitBOpen r) 2
    (relHomologyInt_splitBOpen_eq_zero hr0 hr1) hcyc

/-- **The zero-section class is halvable from (C1) alone.** -/
theorem zeroSectionClass_halved_of_cyclic {r : ℝ} (hr0 : 0 ≤ r) (hr1 : r < 1)
    (hcyc : ∃ a : RelHomologyInt (restr outerE (splitBOpen r)) 2,
      ∀ x : RelHomologyInt (restr outerE (splitBOpen r)) 2, ∃ k : ℤ, x = k • a) :
    ∃ x : SKEFTHawking.KummerCollarPairLESInt.CollarH2,
      (2 : ℤ) • x = SKEFTHawking.KummerCollarPairLESInt.zeroSectionClass :=
  SKEFTHawking.KummerCollarPairLESInt.outerECyclic_iff_zeroSectionClass_halved.mp
    (outerECyclic_of_cyclic hr0 hr1 hcyc)

/-- **The headline, on one input.** `H₂(K3;ℤ) ≅ ℤ²²` now rests solely on (C1). -/
theorem kummerK3_b2_target_of_cyclic {r : ℝ} (hr0 : 0 ≤ r) (hr1 : r < 1)
    (hcyc : ∃ a : RelHomologyInt (restr outerE (splitBOpen r)) 2,
      ∀ x : RelHomologyInt (restr outerE (splitBOpen r)) 2, ∃ k : ℤ, x = k • a) :
    SKEFTHawking.KummerK7Opener.kummerK3_b2_target :=
  kummerK3_b2_target_of_outerE_cyclic (outerECyclic_of_cyclic hr0 hr1 hcyc)

/-! ## §5. Non-degeneracy

`splitBOpen r ≠ univ` (`KummerChartNbhdInt.splitBOpen_ne_univ`, for `0 ≤ r`) and (C0) *fails* at the
smallest admissible subspace `B = outerE`
(`KummerCollarPairSplitInt.not_relHomologyInt_outerE_eq_zero`). So the enlargement to `splitBOpen r`
is load-bearing: (C0) is a genuine theorem about a proper subspace strictly between `outerE` and
`E`, not a degenerate `B = univ` statement, and the surviving (C1) is not a restatement of the
residual. -/

/-- **The discharged (C0) is a statement about a proper subspace** — not the vacuous `B = univ`
case. -/
theorem splitBOpen_proper {r : ℝ} (hr : 0 ≤ r) : splitBOpen r ≠ (Set.univ : Set ↑ResEtop) :=
  splitBOpen_ne_univ hr

/-- **(C0) is sharp**: it is false at `B = outerE`, so no smaller `B` will do. -/
theorem not_relHomologyInt_outerE_eq_zero :
    ¬ (∀ y : RelHomologyInt (X := ResEtop) outerE 2, y = 0) :=
  SKEFTHawking.KummerCollarPairSplitInt.not_relHomologyInt_outerE_eq_zero

end

end SKEFTHawking.KummerSplitBCoreVanishInt
