import Mathlib

/-!
# Phase 5q.H — the Kirby–Taylor §5 exact-sequence assembly (`Ω₄^{Pin⁺} ≅ ℤ/16`)

Pure group-theory core of Kirby–Taylor LMS-151 **Theorem 5.2**
(`Lit-Search/Phase-5qH/KT_LMS_Section5_completeness_proof_extracted.md`): from the short exact sequence

  `0 → ℤ/2 → Ω₄^{Pin⁺} →^{[∩w₁²]} Ω₂^{Pin⁻} ≅ ℤ/8 → 0`

(the characteristic-surface map onto `ℤ/8`, kernel = the Spin image `ℤ/2` by Lemma 5.3) **plus** the
ψ-witness (KT p.218: `ψ(ℝP⁴,ℝP³)=2`, so `8·[ℝP⁴]` = the nonzero kernel element), the extension is
non-split and `Ω₄^{Pin⁺} ≅ ℤ/16`, generated by `[ℝP⁴]` of order 16.

This module is the ALGEBRA of that argument, abstracted from geometry: given an `AddCommGroup G`, a
surjection `p : G →+ ZMod 8` with `Nat.card (ker p) = 2`, and `g : G` with `p g = 1` and `8•g ≠ 0`, we
derive `Nat.card G = 16`, `addOrderOf g = 16`, and `Nonempty (G ≃+ ZMod 16)`. Kernel-pure. The geometric
inputs (`p` onto, `ker p = ℤ/2`, the ψ-witness) are the KT §5 disclosed facts, each traced to a page.
-/

namespace SKEFTHawking.PinPlusExactSequence

open scoped Classical

variable {G : Type*} [AddCommGroup G]

/-- `G ⧸ ker p ≃+ ZMod 8` when `p : G →+ ZMod 8` is surjective (first isomorphism theorem). -/
noncomputable def quotKerEquiv (p : G →+ ZMod 8) (hp : Function.Surjective p) :
    (G ⧸ p.ker) ≃+ ZMod 8 :=
  QuotientAddGroup.quotientKerEquivOfSurjective p hp

/-- **The quotient by `ker p` has 8 elements.** -/
theorem card_quot_ker (p : G →+ ZMod 8) (hp : Function.Surjective p) :
    Nat.card (G ⧸ p.ker) = 8 := by
  rw [Nat.card_congr (quotKerEquiv p hp).toEquiv]
  simp

/-- **`Nat.card G = 16`** — Lagrange on the exact sequence: `|G| = |G ⧸ ker p| · |ker p| = 8 · 2`.
The `|ker p| = 2` is KT Lemma 5.3 (the Spin image); `|G ⧸ ker p| = 8` is `[∩w₁²]` onto `Ω₂^{Pin⁻}=ℤ/8`. -/
theorem card_G_eq_16 (p : G →+ ZMod 8) (hp : Function.Surjective p) (hker : Nat.card p.ker = 2) :
    Nat.card G = 16 := by
  rw [AddSubgroup.card_eq_card_quotient_mul_card_addSubgroup p.ker, card_quot_ker p hp, hker]

/-- **`addOrderOf g = 16`** — the ψ-witness (KT p.218, `ψ(ℝP⁴)=2`): `8•g` is the nonzero order-2 kernel
element, so `16•g = 0` but `8•g ≠ 0`, forcing order exactly 16 (the divisor of 16 not dividing 8). -/
theorem order_g_eq_16 (p : G →+ ZMod 8) (g : G) (hpg : p g = 1) (hg8 : (8 : ℕ) • g ≠ 0)
    (hker : Nat.card p.ker = 2) : addOrderOf g = 16 := by
  have hmem : (8 : ℕ) • g ∈ p.ker := by
    rw [AddMonoidHom.mem_ker, map_nsmul, hpg]; decide
  have h16 : (16 : ℕ) • g = 0 := by
    haveI : Finite p.ker := Nat.finite_of_card_ne_zero (by omega)
    have hx : (2 : ℕ) • (⟨(8 : ℕ) • g, hmem⟩ : p.ker) = 0 :=
      addOrderOf_dvd_iff_nsmul_eq_zero.mp (by rw [← hker]; exact addOrderOf_dvd_natCard _)
    have hx' : (2 : ℕ) • ((8 : ℕ) • g) = 0 := by
      simpa using congrArg (Subtype.val (p := fun x => x ∈ p.ker)) hx
    rw [show (16 : ℕ) = 2 * 8 from rfl, mul_smul]
    exact hx'
  have hdvd : addOrderOf g ∣ 16 := addOrderOf_dvd_of_nsmul_eq_zero h16
  have hne : ¬ addOrderOf g ∣ 8 := fun h => hg8 (addOrderOf_dvd_iff_nsmul_eq_zero.mp h)
  have hle : addOrderOf g ≤ 16 := Nat.le_of_dvd (by norm_num) hdvd
  set n := addOrderOf g with hn
  interval_cases n <;> revert hdvd hne <;> decide

/-- **The Kirby–Taylor §5 completeness assembly (KT Theorem 5.2), as pure group theory.** From the exact
sequence `0 → ℤ/2 → G →ᵖ ℤ/8 → 0` (`p` = `[∩w₁²]` onto `Ω₂^{Pin⁻}=ℤ/8`, `Nat.card (ker p) = 2` = the Spin
image, Lemma 5.3) together with the ψ-witness element `g = [ℝP⁴]` (`p g = 1` a `ℤ/8`-generator, `8•g ≠ 0`
the nonzero kernel class, KT p.218 `ψ(ℝP⁴)=2`), the group is `≃+ ZMod 16`. Kernel-pure; the hypotheses are
exactly the KT §5 disclosed geometric facts, each page-traced in
`Lit-Search/Phase-5qH/KT_LMS_Section5_completeness_proof_extracted.md`. -/
theorem zmod16_of_kt_exact_sequence (p : G →+ ZMod 8) (hp : Function.Surjective p)
    (hker : Nat.card p.ker = 2) (g : G) (hpg : p g = 1) (hg8 : (8 : ℕ) • g ≠ 0) :
    Nonempty (G ≃+ ZMod 16) := by
  have hcard : Nat.card G = 16 := card_G_eq_16 p hp hker
  have hord : addOrderOf g = 16 := order_g_eq_16 p g hpg hg8 hker
  haveI : Finite G := Nat.finite_of_card_ne_zero (by omega)
  haveI : IsAddCyclic G := isAddCyclic_of_addOrderOf_eq_card g (by rw [hord, hcard])
  have hc : Nat.card G = Nat.card (ZMod 16) := by rw [hcard, Nat.card_zmod]
  exact ⟨addEquivOfAddCyclicCardEq hc⟩

end SKEFTHawking.PinPlusExactSequence
