/-
Phase 5b: Standard Model Fermion Data — Representation-Theoretic Content

Formalizes the Standard Model's fermion content as algebraic data:
  - SM fermion enumeration (quarks, leptons, neutrinos) as an inductive type
  - ℤ₄ charge computation: X = 5(B-L) - 4Y (from discrete symmetry)
  - Verification that all SM fermions have odd ℤ₄ charge
  - Component counting per fermion type (color × weak isospin)

The ℤ₄ symmetry generated by X = 5(B-L) - 4Y is the discrete remnant of
B-L after electroweak symmetry breaking. Its global anomaly is classified
by Ω₅^{Spin^{ℤ₄}} ≅ ℤ₁₆ (Dai-Freed theorem).

References:
  García-Etxebarria & Montero, JHEP 08, 003 (2019) [arXiv:1808.00009]
  Dai & Freed, J. Diff. Geom. 35, 471 (1994)
-/

import Mathlib

open Finset

namespace SKEFTHawking

/-! ## 1. SM Fermion Enumeration -/

/--
Standard Model fermion representations (one generation, left-handed Weyl basis).
Each constructor represents a distinct Weyl fermion multiplet.
-/
inductive SMFermion : Type where
  | Q_L       -- quark doublet (u_L, d_L): (3, 2, 1/6)
  | u_R_bar   -- up antiquark: (3̄, 1, -2/3)
  | d_R_bar   -- down antiquark: (3̄, 1, 1/3)
  | L         -- lepton doublet (ν_L, e_L): (1, 2, -1/2)
  | e_R_bar   -- positron: (1, 1, 1)
  | nu_R_bar  -- right-handed neutrino: (1, 1, 0)
  deriving DecidableEq, Fintype

/--
The SM has exactly 6 Weyl fermion multiplets per generation.
-/
theorem sm_fermion_count : Fintype.card SMFermion = 6 := by decide

/--
The SM without ν_R has exactly 5 Weyl fermion multiplets.
-/
def SMFermionNoNuR : Finset SMFermion :=
  {SMFermion.Q_L, SMFermion.u_R_bar, SMFermion.d_R_bar, SMFermion.L, SMFermion.e_R_bar}

theorem sm_fermion_no_nu_R_count : SMFermionNoNuR.card = 5 := by decide

/-! ## 2. Quantum Numbers -/

/--
Baryon number minus lepton number (B-L) for each SM fermion.
Values are rational to handle 1/3 for quarks.
-/
def bMinusL : SMFermion → ℚ
  | .Q_L => 1/3
  | .u_R_bar => -1/3
  | .d_R_bar => -1/3
  | .L => -1
  | .e_R_bar => 1
  | .nu_R_bar => 1

/--
Weak hypercharge Y (convention Q = T₃ + Y).
-/
def hyperchargeY : SMFermion → ℚ
  | .Q_L => 1/6
  | .u_R_bar => -2/3
  | .d_R_bar => 1/3
  | .L => -1/2
  | .e_R_bar => 1
  | .nu_R_bar => 0

/--
Number of components (SU(3)_c × SU(2)_L degrees of freedom) per fermion.
-/
def components : SMFermion → ℕ
  | .Q_L => 6       -- 3 color × 2 weak
  | .u_R_bar => 3   -- 3 color
  | .d_R_bar => 3   -- 3 color
  | .L => 2         -- 2 weak
  | .e_R_bar => 1
  | .nu_R_bar => 1

/-! ## 3. ℤ₄ Charge Computation -/

/--
The ℤ₄ charge X = 5(B-L) - 4Y (rational, before mod reduction).

This generates the discrete ℤ₄ symmetry whose global anomaly
is classified by Ω₅^{Spin^{ℤ₄}} ≅ ℤ₁₆.

PROVIDED SOLUTION
Direct computation from the definitions of bMinusL and hyperchargeY.
-/
def z4ChargeRaw (f : SMFermion) : ℚ := 5 * bMinusL f - 4 * hyperchargeY f

/--
Q_L: X = 5(1/3) - 4(1/6) = 5/3 - 2/3 = 1.
-/
theorem z4_Q_L : z4ChargeRaw .Q_L = 1 := by
  simp [z4ChargeRaw, bMinusL, hyperchargeY]; ring

/--
ū_R: X = 5(-1/3) - 4(-2/3) = -5/3 + 8/3 = 1.
-/
theorem z4_u_R_bar : z4ChargeRaw .u_R_bar = 1 := by
  simp [z4ChargeRaw, bMinusL, hyperchargeY]; ring

/--
d̄_R: X = 5(-1/3) - 4(1/3) = -5/3 - 4/3 = -3.
-/
theorem z4_d_R_bar : z4ChargeRaw .d_R_bar = -3 := by
  simp [z4ChargeRaw, bMinusL, hyperchargeY]; ring

/--
L: X = 5(-1) - 4(-1/2) = -5 + 2 = -3.
-/
theorem z4_L : z4ChargeRaw .L = -3 := by
  simp [z4ChargeRaw, bMinusL, hyperchargeY]; ring

/--
ē_R: X = 5(1) - 4(1) = 1.
-/
theorem z4_e_R_bar : z4ChargeRaw .e_R_bar = 1 := by
  simp [z4ChargeRaw, bMinusL, hyperchargeY]; ring

/--
ν̄_R: X = 5(1) - 4(0) = 5.
-/
theorem z4_nu_R_bar : z4ChargeRaw .nu_R_bar = 5 := by
  simp [z4ChargeRaw, bMinusL, hyperchargeY]

/-! ## 4. All ℤ₄ Charges Are Odd -/

/--
The ℤ₄ charge is always an integer (crucial: 5(B-L) - 4Y ∈ ℤ for all SM fermions).

PROVIDED SOLUTION
Exhaustive check over all 6 constructors.
-/
theorem z4_charge_is_integer (f : SMFermion) : ∃ n : ℤ, z4ChargeRaw f = ↑n := by
  cases f
  · exact ⟨1, by simp [z4ChargeRaw, bMinusL, hyperchargeY]; ring⟩
  · exact ⟨1, by simp [z4ChargeRaw, bMinusL, hyperchargeY]; ring⟩
  · exact ⟨-3, by simp [z4ChargeRaw, bMinusL, hyperchargeY]; ring⟩
  · exact ⟨-3, by simp [z4ChargeRaw, bMinusL, hyperchargeY]; ring⟩
  · exact ⟨1, by simp [z4ChargeRaw, bMinusL, hyperchargeY]; ring⟩
  · exact ⟨5, by simp [z4ChargeRaw, bMinusL, hyperchargeY]⟩

/--
All SM fermion ℤ₄ charges are odd (mod 4 ∈ {1, 3}).
This is the key property: odd charge → each component contributes ±1 to the ℤ₁₆ anomaly.

PROVIDED SOLUTION
Exhaustive: X values are {1, 1, -3, -3, 1, 5}. Modulo 4: {1, 1, 1, 1, 1, 1}. All odd.
-/
theorem sm_z4_all_odd (f : SMFermion) : ∃ k : ℤ, z4ChargeRaw f = 2 * k + 1 := by
  cases f
  · exact ⟨0, by simp [z4ChargeRaw, bMinusL, hyperchargeY]; ring⟩
  · exact ⟨0, by simp [z4ChargeRaw, bMinusL, hyperchargeY]; ring⟩
  · exact ⟨-2, by simp [z4ChargeRaw, bMinusL, hyperchargeY]; ring⟩
  · exact ⟨-2, by simp [z4ChargeRaw, bMinusL, hyperchargeY]; ring⟩
  · exact ⟨0, by simp [z4ChargeRaw, bMinusL, hyperchargeY]; ring⟩
  · exact ⟨2, by simp [z4ChargeRaw, bMinusL, hyperchargeY]; ring⟩

/-! ## 5. Component Counting -/

/--
Total components with ν_R: 6+3+3+2+1+1 = 16.
-/
theorem total_components_with_nu_R :
    components .Q_L + components .u_R_bar + components .d_R_bar +
    components .L + components .e_R_bar + components .nu_R_bar = 16 := by
  simp [components]

/--
Total components without ν_R: 6+3+3+2+1 = 15.
-/
theorem total_components_without_nu_R :
    components .Q_L + components .u_R_bar + components .d_R_bar +
    components .L + components .e_R_bar = 15 := by
  simp [components]

/--
Q_L has the most components (6) among all SM fermions.
-/
theorem Q_L_largest_multiplet (f : SMFermion) : components f ≤ 6 := by
  cases f <;> simp [components]

/--
Every SM fermion has at least 1 component.
-/
theorem components_positive (f : SMFermion) : 0 < components f := by
  cases f <;> simp [components]

/-! ## 6. Anomaly Contribution Per Fermion -/

/--
Each SM fermion's contribution to the anomaly index = its component count
(since all ℤ₄ charges are odd, each Weyl fermion contributes +1).
-/
def anomalyContribution (f : SMFermion) : ℕ := components f

/--
The anomaly contribution equals the component count for all SM fermions.
-/
theorem anomaly_eq_components (f : SMFermion) :
    anomalyContribution f = components f := rfl

/--
The sum of all anomaly contributions (with ν_R) is 16.
-/
theorem total_anomaly_with_nu_R :
    anomalyContribution .Q_L + anomalyContribution .u_R_bar +
    anomalyContribution .d_R_bar + anomalyContribution .L +
    anomalyContribution .e_R_bar + anomalyContribution .nu_R_bar = 16 := by
  simp [anomalyContribution, components]

/--
The sum of anomaly contributions without ν_R is 15.
-/
theorem total_anomaly_without_nu_R :
    anomalyContribution .Q_L + anomalyContribution .u_R_bar +
    anomalyContribution .d_R_bar + anomalyContribution .L +
    anomalyContribution .e_R_bar = 15 := by
  simp [anomalyContribution, components]

/-! ## 7. Bridge to Z16Classification -/

/--
The total 16 (with ν_R) matches the ℤ₁₆ anomaly cancellation unit.
This is the first connection: 16 Weyl fermions = 0 mod 16 = anomaly-free.
-/
theorem components_match_z16_unit :
    components .Q_L + components .u_R_bar + components .d_R_bar +
    components .L + components .e_R_bar + components .nu_R_bar = 16 ∧
    16 % 16 = 0 := by
  constructor
  · simp [components]
  · norm_num

/--
The Kähler-Dirac interpretation: 16 Weyl = 8 Dirac = 4 Kähler-Dirac = 2 KD flavors.
This matches z16_classification's kahler_dirac_counting: 2×4×2 = 16.
-/
theorem kahler_dirac_decomposition :
    (16 : ℕ) = 2 * 8 ∧ 8 = 4 * 2 ∧ 4 = 2 * 2 := by
  constructor <;> [norm_num; constructor <;> norm_num]

end SKEFTHawking
