/-
# Phase 5q.H — the residual `homIncl sphereDiskBoundarySet 2 ≠ 0` closing P23 `dimeq`

`SphereProdP23.sphereDiskDimeq23_of_homIncl_ne_zero` banks the full `(2,3)` `dimeq` field CONDITIONAL
on the single geometric fact `homIncl sphereDiskBoundarySet 2 ≠ 0` — the boundary inclusion
`∂W = S²×S² ↪ W = S²×D³` induces a NONZERO map on `H₂(·;ℤ/2)` (the surviving `S²` area class).

This module discharges that residual GENUINELY (not a vacuous discharge) and wires the resulting
UNCONDITIONAL `dimeq`:

* **`sphereDisk_homIncl_two_ne_zero`** — `homIncl sphereDiskBoundarySet 2 ≠ 0`.
* **`sphereDiskDimeq23`** — the full `(2,3)` `dimeq`, unconditional.

## Route

The first projection realizes the collapse and the inclusion as induced maps:
`sphereDiskCollapse 1 = Homology.map prodFst` (its forward map IS `Homology.map (prodFst …)`,
`prodContractibleHomologyEquiv := LinearEquiv.ofBijective (Homology.map (prodFst …)) …`), and
`homIncl S 2 = Homology.map (ambIncl S)` (`Homology.map_ambIncl`), and
`homeoHomologyEquiv h 2 = Homology.map ⟨h,…⟩` (`homeoHomologyEquiv_apply`). Composing (functoriality)
the transport `H₂(S²×S²) → H₂(∂W) → H₂(W) → H₂(S²)` collapses to `Homology.map prodFst` of the
FIRST-factor projection `S²×S² → S²`, because `prodFst ∘ ambIncl ∘ sphereDiskInclHomeo = Prod.fst`
(the disk coordinate is discarded). Feeding the mod-2 first-factor generator `gen0 = redHomology [S²×pt]`
through it lands on `redHomology (topSphereIsoInt 1).symm 1`, the reduction of the integral
`H₂(S²;ℤ)` generator — nonzero because `redHomology (Sph 2) 2` is SURJECTIVE onto the nontrivial
`H₂(S²;ℤ/2) ≅ ℤ/2` and `H₂(S²;ℤ) ≅ ℤ` is generated by that class (a killed generator would kill the
whole surjection). Since `sphereDiskCollapse 1` and `homeoHomologyEquiv … 2` are equivs, the composite
being nonzero forces `homIncl S 2 ≠ 0`.

Kernel-pure (`{propext, Classical.choice, Quot.sound}`); no `sorry`/`native_decide`/`maxHeartbeats`/axiom.
-/
import Mathlib
import SKEFTHawking.SphereProdP23
import SKEFTHawking.SphereProdHTwoInt
import SKEFTHawking.SingularSphereGenReducesInt
import SKEFTHawking.SingularSphereMiddleInt

open SKEFTHawking.SingularHomologyMod2 SKEFTHawking.SingularCohomologyMod2
open SKEFTHawking.SingularRelativeHomologyMod2 SKEFTHawking.SingularRelativeCohomologyMod2
open SKEFTHawking.SpinSigmaRoute
open SKEFTHawking.SingularFunctoriality (Homology.map)
open SKEFTHawking.SingularFunctorialityInt (Homology.mapInt)
open SKEFTHawking.SingularHomologyInt (redHomology)
open SKEFTHawking.PinPlusKTSphereProdRelFundWuRoots
open SKEFTHawking.PinPlusCharPairRealizationTied (homeoHomologyEquiv homeoHomologyEquiv_apply)
open SKEFTHawking.SingularLineMinusPoint (topSphereIso)
open SKEFTHawking.SingularLineMinusPointInt (topSphereIsoInt)
open SKEFTHawking.SingularSphereAcyclic (Sph)
open SKEFTHawking.SingularDiskAcyclic (Disk)
open SKEFTHawking.SingularSphereBottom (basePoint)
open SKEFTHawking.SingularProdContractibleInt (prodFst)
open SKEFTHawking.SingularLocalHomologyRedCompatInt (redHomology_homologyMapInt)
open SKEFTHawking.SingularMayerVietorisLES (ambIncl)
open SKEFTHawking.SingularPairLES (homIncl)

namespace SKEFTHawking.SphereProdP23Hincl

noncomputable section

/-! ## §1. The reduction of the integral `H₂(S²;ℤ)` generator is nonzero. -/

/-- **The ℤ→ℤ/2 reduction of the integral `H₂(S²;ℤ)` generator `(topSphereIsoInt 1).symm 1` is
nonzero in `H₂(S²;ℤ/2)`.** `redHomology (Sph 2) 2` is surjective (`redHomology_surjective`, using
`H₁(S²;ℤ) = 0` hence 2-torsion-free) onto the nontrivial `H₂(S²;ℤ/2) ≅ ℤ/2` (`topSphereIso 1`); and
`H₂(S²;ℤ) ≅ ℤ` (`topSphereIsoInt 1`) is cyclic on that generator, so a vanishing reduction would kill
the whole surjection. -/
theorem redHomology_topSphere_gen_ne_zero :
    redHomology (Sph 2) 2 ((topSphereIsoInt 1).symm 1) ≠ 0 := by
  intro hzero
  have hsurj := SphereProdHTwoMod2.redHomology_surjective (X := Sph 2) 1
    (fun x _ => SingularSphereMiddleInt.sphere_homology_oneInt (le_refl 2) x)
  have hy₀ : (topSphereIso 1).symm (1 : ZMod 2) ≠ 0 := by
    rw [ne_eq, ← map_zero (topSphereIso 1).symm, (topSphereIso 1).symm.injective.eq_iff]
    exact one_ne_zero
  obtain ⟨x, hx⟩ := hsurj ((topSphereIso 1).symm (1 : ZMod 2))
  have hdecomp : x = (topSphereIsoInt 1 x) • ((topSphereIsoInt 1).symm (1 : ℤ)) := by
    rw [← map_smul, smul_eq_mul, mul_one, (topSphereIsoInt 1).symm_apply_apply]
  apply hy₀
  rw [← hx, hdecomp, map_zsmul, hzero, smul_zero]

/-! ## §2. The first-factor projection sends `gen0` to that generator's reduction (nonzero). -/

/-- **The mod-2 first-factor projection `Homology.map prodFst 2` is nonzero on the surviving
generator `gen0 = redHomology [S²×pt]`**: it lands on `redHomology (topSphereIsoInt 1).symm 1` via the
reduction naturality `redHomology_homologyMapInt` and the integral first-projection `sumInto_prodFst`. -/
theorem homology_map_prodFst_gen0_ne_zero :
    Homology.map (prodFst (Sph 2) (Sph 2)) 2 SphereProdHTwoMod2.gen0 ≠ 0 := by
  have hA : SphereProdHTwoInt.sphereProdHTwoEquivInt.symm ((1 : ℤ), (0 : ℤ))
      = SphereProdHTwoInt.sumInto (basePoint 2) 1 := by
    rw [SphereProdHTwoInt.sphereProdHTwoEquivInt_symm_apply, zero_smul, add_zero]
  have hmap : Homology.map (prodFst (Sph 2) (Sph 2)) 2 SphereProdHTwoMod2.gen0
      = redHomology (Sph 2) 2 ((topSphereIsoInt 1).symm 1) := by
    show Homology.map (prodFst (Sph 2) (Sph 2)) 2
        (redHomology (TopCat.of SphereProd) 2
          (SphereProdHTwoInt.sphereProdHTwoEquivInt.symm ((1 : ℤ), (0 : ℤ)))) = _
    rw [← redHomology_homologyMapInt, hA, SphereProdHTwoInt.sumInto_prodFst]
  rw [hmap]
  exact redHomology_topSphere_gen_ne_zero

/-! ## §3. The residual `homIncl S 2 ≠ 0` and the wired `dimeq`. -/

/-- The collapse realized as an induced map: `sphereDiskCollapse 1 = Homology.map prodFst 2`
(`prodContractibleHomologyEquiv := LinearEquiv.ofBijective (Homology.map (prodFst …)) …`, and the
`sphereDisk_eq_prodSp ▸` transport is along a `rfl`-equation). -/
theorem sphereDiskCollapse_one_apply (z : Homology (TopCat.of SphereDisk) 2) :
    sphereDiskCollapse 1 z
      = Homology.map (prodFst (TopCat.of TwoSphere) (Disk 3)) 2 z := rfl

/-- **`homIncl sphereDiskBoundarySet 2 ≠ 0`** — the boundary inclusion `S²×S² ↪ S²×D³` induces a
nonzero map on `H₂(·;ℤ/2)`. Route: `sphereDiskCollapse 1 (homIncl S 2 (homeoHomologyEquiv … gen0))`
collapses (functoriality of the three realized induced maps) to `Homology.map prodFst 2 gen0`, the
first-factor projection of the surviving generator — nonzero (`homology_map_prodFst_gen0_ne_zero`). A
zero `homIncl` would send it through `sphereDiskCollapse 1 0 = 0`. -/
theorem sphereDisk_homIncl_two_ne_zero :
    homIncl (X := TopCat.of SphereDisk) sphereDiskBoundarySet 2 ≠ 0 := by
  intro hIncl
  apply homology_map_prodFst_gen0_ne_zero
  have mca : ∀ {A B C : TopCat} (g : C(↑B, ↑C)) (f : C(↑A, ↑B)) (w : Homology A 2),
      Homology.map g 2 (Homology.map f 2 w) = Homology.map (g.comp f) 2 w := by
    intro A B C g f w
    rw [SKEFTHawking.SingularFunctoriality.Homology.map_comp, LinearMap.comp_apply]
  have key : Homology.map (prodFst (Sph 2) (Sph 2)) 2 SphereProdHTwoMod2.gen0
      = sphereDiskCollapse 1
          (homIncl (X := TopCat.of SphereDisk) sphereDiskBoundarySet 2
            (homeoHomologyEquiv sphereDiskInclHomeo 2 SphereProdHTwoMod2.gen0)) := by
    rw [homeoHomologyEquiv_apply, ← SKEFTHawking.SingularMayerVietorisLES.Homology.map_ambIncl,
      sphereDiskCollapse_one_apply, mca, mca]
    rfl
  rw [key, hIncl, LinearMap.zero_apply, map_zero]

/-- **`dimeq` for the `(2,3)` leg — UNCONDITIONAL.** `dim H²(S²×D³;ℤ/2) = dim H³(S²×D³,S²×S²;ℤ/2)`,
the Betti equality the `LefschetzWuDatum.ofRelFund23` `dimeq` field needs, now that the boundary
inclusion is discharged nonzero. -/
theorem sphereDiskDimeq23 :
    Module.finrank (ZMod 2) (Cohomology (TopCat.of SphereDisk) 2)
      = Module.finrank (ZMod 2)
        (RelativeCohomology (X := TopCat.of SphereDisk) sphereDiskBoundarySet 3) :=
  SphereProdP23.sphereDiskDimeq23_of_homIncl_ne_zero sphereDisk_homIncl_two_ne_zero

end

end SKEFTHawking.SphereProdP23Hincl
