/-
# Phase 5q.H (N1a) — the `Ω₄^{Spin} ≅ ℤ` σ-route: statement freezes + route-complete conditional

The N1a layer of the KT §5 completeness key (gap map
`docs/dev-loops/Phase5qH/E4_GenuineCarrier_Assembly/ASSEMBLY_GAP_MAP_20260712.md` row N1a;
DR route `Lit-Search/Phase-5qH/Omega4Spin_Z_formalization_route_20260706.md`). The route:

    σ = 0 spin ⟹ even-indefinite intersection form ≅ n·H   (lattice algebra — DONE in-tree,
                                                             `exists_hyperbolic_congr`)
              ⟹ M realizes the n·H form by q = n/2 copies of S²×S²   (handle-trading —
                     Benedetti arXiv:1907.10297 Prop 20.16 + Lemma 20.17; Kirby–Taylor
                     arXiv:math/9803101 pp.6–7: bordisms "built from 2- and 3-handles")
              ⟹ M bounds, since S²×S² = ∂(S²×D³)   (the 3-handle bounding — DR sub-piece (1))

This module freezes the two GEOMETRIC steps as named Props on a data-level carrier
(`CharSurfaceBounding` pattern: structures carry the data, literature-verbatim Props freeze the
geometry, theorems compose), and proves the route COMPLETE modulo the freezes:

* `SpinSigmaPresentation ξ` — a σ-presentation of a tangential carrier `ξ` (the genuine
  `TangentialData` machinery of `TangentialDataBordism.lean`, same substrate as the tied Pin⁺
  carrier): the bordism-invariant signature hom `sig : DataBordismGrp ξ →+ ℤ` (Thom), a per-manifold
  even-unimodular integral intersection-form presentation (`rank`/`form`/`even_unimod`/`sig_eq` —
  discharged at instantiation by E1's `interMatrix` substrate: evenness = Wu
  `interMatrix_even_of_closed`, unimodularity = PD `interMatrix_isUnimodular_of_intPD`), and the
  distinguished `S²×S²` structured manifold pinned by its rank-2 hyperbolic form.
* `RealizesSphereProducts` — **statement freeze** (Benedetti Prop 20.16/Lemma 20.17 handle-trading):
  a structured manifold whose form is congruent to a hyperbolic-standard form is bordant to
  `rank/2` copies of the distinguished `S²×S²`.
* `SphereProductBounds` — **statement freeze** (DR sub-piece (1), `S²×S² = ∂(S²×D³)` by a 3-handle):
  the distinguished `S²×S²` class is zero.
* `sig_injective` — **the injective direction of `Ω₄^{Spin} ≅ ℤ`, route-complete modulo the two
  freezes**: wired through `exists_hyperbolic_congr` (the in-tree lattice half).
* `generates` / `dataBordismGrp_equiv_int` — the full `Ω₄^{Spin} ≅ ℤ` (the `hyp:spin_bordism_iso_Z`
  consumer shape, `constants.py:2814`: "≅ ℤ, generated by K3 with σ(K3) = −16"), with the two
  remaining geometric inputs as binders: `hdvd` (Rokhlin `16 ∣ σ` — N2, E2's program) and the
  generator witness `g` with `σ(g) = −16` (K3 — abstract per the DR: no hand-built K3 needed).
* `gen_zsmul_eq_zero_iff` / `thirtytwo_dvd_sig_iff` — the N1c-facing arithmetic (KT Lemma 5.3's
  `÷32` half): the generator has infinite order, and `32 ∣ σ(x) ⟺ x` is an EVEN multiple of the
  generator — exactly the algebra the forgetful `s : ℤ →+ Ω₄^{Pin⁺}` kernel computation consumes
  (`PinPlusExactSequence.spin_image_card_two`), leaving only "2·K3 bounds Pin⁺" geometric.

NO Rokhlin-only shortcut exists around the full iso (settled-fork caveat 2026-07-06b); this module
does not attempt one — Rokhlin (`hdvd`) enters only as the surjectivity-normalization binder.

Kernel-pure (`{propext, Classical.choice, Quot.sound}`); no `sorry`/`native_decide`/`maxHeartbeats`/axiom.
-/
import Mathlib
import SKEFTHawking.HyperbolicNormalForm
import SKEFTHawking.TangentialDataBordism

namespace SKEFTHawking.SpinSigmaRoute

open SKEFTHawking.TangentialDataBordism SKEFTHawking.BordismTheory

variable {X : Type*} [TopologicalSpace X] {k : WithTop ℕ∞}
  {E H : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E] [FiniteDimensional ℝ E]
  [TopologicalSpace H] {I : ModelWithCorners ℝ E H} [I.Boundaryless]

universe u

/-- **A σ-presentation of a tangential carrier**: the data through which the KT injective-direction
route speaks about `Ω^ξ` (for ξ = the genuine Spin structure data, `DataBordismGrp ξ = Ω₄^{Spin}`).
Carried as disclosed data (each field is a named theorem of the literature, discharged at
instantiation):

* `sig` — the signature descends to a bordism-invariant additive hom (Thom: `σ` is additive under
  disjoint union and vanishes on boundaries);
* `rank`/`form`/`even_unimod`/`sig_eq` — every structured manifold carries an integral
  intersection-form presentation, even (Wu, spin) unimodular (Poincaré duality), computing its
  signature (E1's `interMatrix` substrate: `interMatrix_even_of_closed`,
  `interMatrix_isUnimodular_of_intPD`, `latticeSig ∘ interMatrix`);
* `s2s2` — the distinguished `S²×S²`, pinned falsifiably by its rank-2 hyperbolic intersection
  form (`II(S²×S²) = H`). -/
structure SpinSigmaPresentation (ξ : TangentialData X k I) where
  /-- The bordism-invariant signature homomorphism (Thom). -/
  sig : DataBordismGrp ξ →+ ℤ
  /-- Rank of the intersection-form presentation of each structured manifold. -/
  rank : StrMfd ξ → ℕ
  /-- The integral intersection-form presentation (E1: the `interMatrix` Gram matrix). -/
  form : (p : StrMfd ξ) → Matrix (Fin (rank p)) (Fin (rank p)) ℤ
  /-- Spin ⟹ even (Wu) + unimodular (Poincaré duality). -/
  even_unimod : ∀ p, IsEvenUnimodular (form p)
  /-- The presentation computes the signature: `sig [p] = σ(form p)`. -/
  sig_eq : ∀ p, sig (DataBordismGrp.mk ξ p) = latticeSig (form p)
  /-- The distinguished `S²×S²` structured manifold. -/
  s2s2 : StrMfd ξ
  /-- `S²×S²` has `b₂ = 2`. -/
  s2s2_rank : rank s2s2 = 2
  /-- `II(S²×S²)` is the (rank-2) hyperbolic form `H` — the falsifiable identity pin. -/
  s2s2_hyp : ∃ N, IsHyperbolicForm N ∧ IntCongr (form s2s2) N

namespace SpinSigmaPresentation

variable {ξ : TangentialData X k I}

/-- **Statement freeze — the `n(S²×S²)` realization** (Benedetti arXiv:1907.10297 Prop 20.16 +
Lemma 20.17 handle-trading; Kirby–Taylor arXiv:math/9803101 pp.6–7, bordisms "built from 2- and
3-handles"): a structured manifold whose intersection form is congruent to a hyperbolic-standard
form (`n·H`) is bordant to `q = n/2` copies of the distinguished `S²×S²`. This is the ONE
genuinely Mathlib-absent manifold-topology step of the route (DR sizing verdict row (2')); its
Benedetti-elementary proof (attaching-circle standardization in a chart) is the discharge plan. -/
def RealizesSphereProducts (R : SpinSigmaPresentation ξ) : Prop :=
  ∀ p : StrMfd ξ, (∃ N, IsHyperbolicForm N ∧ IntCongr (R.form p) N) →
    DataBordismGrp.mk ξ p = (R.rank p / 2) • DataBordismGrp.mk ξ R.s2s2

/-- **Statement freeze — the 3-handle bounding** (DR route sub-piece (1)): the distinguished
`S²×S²` bounds — `S²×S² = ∂(S²×D³)`, a single 3-handle; hence its class is `0`. The trivial
geometric sub-piece of the route, frozen separately so the realization freeze stays
literature-exact. -/
def SphereProductBounds (R : SpinSigmaPresentation ξ) : Prop :=
  DataBordismGrp.mk ξ R.s2s2 = 0

/-- **The injective direction of `Ω₄^{Spin} ≅ ℤ` — route-complete modulo the two freezes**
(Benedetti Thm 20.14, spin refinement): `σ` is injective on `Ω^ξ`. The lattice half is the in-tree
`exists_hyperbolic_congr` (`σ=0` even unimodular ⟹ congruent to `n·H`); the geometric half is
exactly the two frozen statements. -/
theorem sig_injective (R : SpinSigmaPresentation ξ) (hA : R.RealizesSphereProducts)
    (hB : R.SphereProductBounds) : Function.Injective R.sig := by
  rw [injective_iff_map_eq_zero]
  intro x hx
  induction x using Quot.ind with | _ p =>
  have hsig0 : latticeSig (R.form p) = 0 := by rw [← R.sig_eq p]; exact hx
  obtain ⟨N, hN, hcong⟩ := exists_hyperbolic_congr (R.form p) (R.even_unimod p) hsig0
  show DataBordismGrp.mk ξ p = 0
  rw [hA p ⟨N, hN, hcong⟩, hB, smul_zero]

/-- **`Ω^ξ` is generated by any `σ = −16` witness** (modulo the freezes + Rokhlin): with `16 ∣ σ`
(N2, E2's Rokhlin program) and a generator `g` of signature `−16` (K3, abstract — no hand-built
K3 needed per the DR), every class is an integer multiple of `[g]`. -/
theorem generates (R : SpinSigmaPresentation ξ) (hA : R.RealizesSphereProducts)
    (hB : R.SphereProductBounds) (g : StrMfd ξ)
    (hg : R.sig (DataBordismGrp.mk ξ g) = -16) (hdvd : ∀ x, (16 : ℤ) ∣ R.sig x)
    (x : DataBordismGrp ξ) : ∃ n : ℤ, x = n • DataBordismGrp.mk ξ g := by
  obtain ⟨c, hc⟩ := hdvd x
  refine ⟨-c, R.sig_injective hA hB ?_⟩
  rw [map_zsmul, hg, smul_eq_mul, hc]
  ring

/-- **`Ω₄^{Spin} ≅ ℤ` — the N1a headline, route-complete modulo the freezes** (the
`hyp:spin_bordism_iso_Z` consumer shape: "≅ ℤ, generated by K3 with σ(K3) = −16"). Modulo the two
frozen geometric statements, given Rokhlin `16 ∣ σ` (N2) and a `σ = −16` generator witness (K3),
the carrier is `≃+ ℤ` with the iso the normalized signature: `σ = −16·e`, `e [g] = 1`. -/
theorem dataBordismGrp_equiv_int (R : SpinSigmaPresentation ξ)
    (hA : R.RealizesSphereProducts) (hB : R.SphereProductBounds) (g : StrMfd ξ)
    (hg : R.sig (DataBordismGrp.mk ξ g) = -16) (hdvd : ∀ x, (16 : ℤ) ∣ R.sig x) :
    ∃ e : DataBordismGrp ξ ≃+ ℤ,
      (∀ x, R.sig x = -16 * e x) ∧ e (DataBordismGrp.mk ξ g) = 1 := by
  have hinj := R.sig_injective hA hB
  let ψ : ℤ →+ DataBordismGrp ξ :=
    AddMonoidHom.mk' (fun n => n • DataBordismGrp.mk ξ g) (fun a b => add_zsmul _ a b)
  have hsigψ : ∀ n : ℤ, R.sig (ψ n) = -16 * n := by
    intro n
    show R.sig (n • DataBordismGrp.mk ξ g) = -16 * n
    rw [map_zsmul, hg, smul_eq_mul]; ring
  have hψbij : Function.Bijective ψ := by
    constructor
    · intro a b hab
      have h := congrArg R.sig hab
      rw [hsigψ, hsigψ] at h
      exact mul_left_cancel₀ (by norm_num : (-16 : ℤ) ≠ 0) h
    · intro x
      obtain ⟨n, hn⟩ := R.generates hA hB g hg hdvd x
      exact ⟨n, hn.symm⟩
  let E : ℤ ≃+ DataBordismGrp ξ := AddEquiv.ofBijective ψ hψbij
  refine ⟨E.symm, fun x => ?_, ?_⟩
  · have hx : ψ (E.symm x) = x := E.apply_symm_apply x
    have hs := hsigψ (E.symm x)
    rw [hx] at hs
    exact hs
  · have h1 : E 1 = DataBordismGrp.mk ξ g := by
      show ψ 1 = DataBordismGrp.mk ξ g
      show (1 : ℤ) • DataBordismGrp.mk ξ g = DataBordismGrp.mk ξ g
      rw [one_smul]
    rw [← h1, AddEquiv.symm_apply_apply]

/-- **The generator has infinite order**: `n • [g] = 0 ⟺ n = 0`. Needs NO freeze — a nonzero
signature already detects torsion-freeness of the cyclic subgroup (σ(n·g) = −16n). The N1c-facing
torsion-freeness that the forgetful `s : ℤ →+ Ω₄^{Pin⁺}` construction rides on. -/
theorem gen_zsmul_eq_zero_iff (R : SpinSigmaPresentation ξ) (g : StrMfd ξ)
    (hg : R.sig (DataBordismGrp.mk ξ g) = -16) (n : ℤ) :
    n • DataBordismGrp.mk ξ g = 0 ↔ n = 0 := by
  constructor
  · intro h
    have hs := congrArg R.sig h
    rw [map_zsmul, hg, map_zero, smul_eq_mul] at hs
    omega
  · rintro rfl
    exact zero_smul ℤ _

/-- **The `÷32` bridge — KT Lemma 5.3's arithmetic half at the `Ω₄^{Spin}` apex** (Kirby–Taylor
§5, Lemma 5.3: a spin 4-manifold Pin⁺-bounds iff `32 ∣ σ`): modulo the freezes + Rokhlin +
generator, `32 ∣ σ(x) ⟺ x` is an **even** multiple of the generator. Composed with the (open,
N1c-geometric) "2·K3 bounds Pin⁺" this computes `ker(Ω₄^{Spin} → Ω₄^{Pin⁺}) = 2ℤ`, i.e. the
`s`/`hs` input of `omega4PinPlusGMTied_equiv_zmod16_via_kt_lemma53` via
`PinPlusExactSequence.spin_image_card_two`. -/
theorem thirtytwo_dvd_sig_iff (R : SpinSigmaPresentation ξ) (hA : R.RealizesSphereProducts)
    (hB : R.SphereProductBounds) (g : StrMfd ξ)
    (hg : R.sig (DataBordismGrp.mk ξ g) = -16) (hdvd : ∀ x, (16 : ℤ) ∣ R.sig x)
    (x : DataBordismGrp ξ) :
    (32 : ℤ) ∣ R.sig x ↔ ∃ m : ℤ, x = (2 * m) • DataBordismGrp.mk ξ g := by
  constructor
  · intro h32
    obtain ⟨n, rfl⟩ := R.generates hA hB g hg hdvd x
    rw [map_zsmul, hg, smul_eq_mul] at h32
    obtain ⟨m, hm⟩ : ∃ m : ℤ, n = 2 * m := by
      obtain ⟨c, hc⟩ := h32
      exact ⟨-c, by omega⟩
    exact ⟨m, by rw [hm]⟩
  · rintro ⟨m, rfl⟩
    rw [map_zsmul, hg, smul_eq_mul]
    exact ⟨-m, by ring⟩

end SpinSigmaPresentation

end SKEFTHawking.SpinSigmaRoute
