"""Paper tables framework (Phase 5v).

Single rendering engine for all paper tables. Each paper declares its
tables in `papers/<paper_key>/tables.py` as a dict of specs:

    from scripts.paper_tables import Col
    from scripts.paper_tables.sources import platform_rows

    TABLES = {
        'table1_platforms': {
            'description': 'Parameters at the sonic horizon',
            'rows': lambda: platform_rows(['Steinhauer', 'Heidelberg', 'Trento']),
            'columns': [
                Col('parameter',  'Parameter', align='l'),
                Col('unit',       'Units'),
                Col('Steinhauer', 'Steinhauer ($^{87}$Rb)'),
                Col('Heidelberg', 'Heidelberg ($^{39}$K)'),
                Col('Trento',     'Trento ($^{23}$Na)'),
            ],
        },
    }

The renderer emits a complete `\\begin{tabular}...\\end{tabular}` block
per spec to `papers/<paper_key>/tables/<spec_id>.tex`, ready to be
\\input{} from the paper's main .tex. Paper .tex keeps the `\\begin{table}`
envelope (caption, label, layout) but offloads data content to the
autogenerated file.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Callable


@dataclass
class Col:
    """Column specification for a paper table.

    field   — key to extract from each row dict.
    header  — LaTeX-formatted header cell (no escaping; authors' job).
    align   — LaTeX column alignment ('l', 'c', 'r'). Defaults to 'c'.
    """
    field: str
    header: str
    align: str = 'c'

    def cell(self, row: dict) -> str:
        """Extract the cell value from a row dict. Values should already
        be formatted strings from the source function (precision, units,
        etc. are the source's responsibility so each physics quantity
        can choose its natural formatting)."""
        v = row.get(self.field)
        if v is None:
            return '---'
        if isinstance(v, Span):
            # Caller should handle Span explicitly; falling through to
            # str(v) would emit the dataclass repr, not the LaTeX form.
            return v.latex()
        return str(v)


@dataclass
class Span:
    """Sentinel for a ``\\multicolumn`` cell spanning multiple columns.

    Used as a row-dict value to span the table's natural column grid.
    The anchor field (``cols[0]``) is where the span renders; remaining
    fields in ``cols`` are skipped during that row's rendering.

    Example (two adjacent columns merged into one centered cell):

        rows = [
            {'param': '$c_s$',
             'smooth': Span('4.0 m/s', cols=('smooth', 'steep'), align='c'),
             'source': 'Falque 2025'},
        ]

    The anchor column determines where the span appears in row order;
    the spanned columns MUST be contiguous in the ``columns`` list
    (LaTeX requirement).
    """
    content: str
    cols: tuple[str, ...]
    align: str = 'c'

    def __post_init__(self) -> None:
        if len(self.cols) < 2:
            raise ValueError(
                f"Span needs >=2 cols; got {self.cols!r}. Use a plain "
                "string for single-cell values."
            )

    def latex(self) -> str:
        n = len(self.cols)
        return fr'\multicolumn{{{n}}}{{{self.align}}}{{{self.content}}}'


def render_table(spec: dict) -> str:
    """Render a single table spec to a LaTeX tabular block.

    Returns a string ending in a newline, suitable for writing to a
    `.tex` snippet the paper can `\\input{}`.
    """
    rows_fn: Callable[[], list[dict]] = spec['rows']
    columns: list[Col] = spec['columns']
    rows = rows_fn()

    align_spec = ''.join(c.align for c in columns)
    lines: list[str] = []
    lines.append('% AUTOGENERATED by scripts/render_paper_tables.py — do not edit by hand.')
    lines.append('% Regenerate via `uv run python scripts/render_paper_tables.py` after')
    lines.append('% changing any source data or the paper\'s tables.py spec.')
    desc = spec.get('description')
    if desc:
        lines.append(f'% Description: {desc}')
    lines.append(r'\begin{tabular}{' + align_spec + '}')
    lines.append(r'\hline')
    lines.append(' & '.join(c.header for c in columns) + r' \\')
    lines.append(r'\hline')
    for row in rows:
        cells: list[str] = []
        skip: set[str] = set()
        for col in columns:
            if col.field in skip:
                continue
            value = row.get(col.field)
            if isinstance(value, Span):
                # Validate: anchor field must be first in the span's cols
                if value.cols[0] != col.field:
                    raise ValueError(
                        f"Span anchor mismatch: row for column {col.field!r} "
                        f"holds a Span whose cols[0] is {value.cols[0]!r}. "
                        "Spans must be keyed by their first column field."
                    )
                # Validate: spanned columns must be contiguous in the
                # columns list (LaTeX requirement).
                col_fields = [c.field for c in columns]
                anchor_idx = col_fields.index(col.field)
                expected = tuple(col_fields[anchor_idx:anchor_idx + len(value.cols)])
                if expected != tuple(value.cols):
                    raise ValueError(
                        f"Span {value.cols!r} is not contiguous in the column "
                        f"list {col_fields!r}. LaTeX \\multicolumn requires "
                        "adjacent columns."
                    )
                cells.append(value.latex())
                for f in value.cols[1:]:
                    skip.add(f)
            else:
                cells.append(col.cell(row))
        lines.append(' & '.join(cells) + r' \\')
    lines.append(r'\hline')
    lines.append(r'\end{tabular}')
    return '\n'.join(lines) + '\n'
