/-
Phase 6EE Wave 1: Rotating-wave reduction with an explicit remainder.

The rotating-wave *approximation* is folklore; the deliverable here is the
*inequality*. The exact interaction-picture generator is split, as an exact
algebraic identity, into a time-independent co-rotating part (`rwaGenerator`)
and a purely oscillatory counter-rotating remainder (`counterRotating`). The
remainder admits a CLOSED-FORM antiderivative (`bsAntiderivative`) whose norm is
bounded by `C · Ω / ω` — the Bloch-Siegert scale. That bound is the whole content:
a naive Duhamel/Gronwall estimate on the same system yields only `Ω·T/2`, which
grows without bound in `T` and carries no `1/ω`, and is therefore NOT of
Bloch-Siegert scale.

No theorem in this file asserts the co-rotating reduction as an equality.

Conventions (all explicit, none implicit):
  * Lab-frame Hamiltonian  `H(t) = (ω₀/2)·σ_z + Ω·cos(ω t + φ)·O`.
  * Drive operator `O` is Hermitian, given in the Pauli basis by REAL
    coefficients `a b c d` (`driveOp`). Every Hermitian 2×2 complex matrix
    arises this way, so no generality is lost for a physical drive.
  * Rotating frame at the drive frequency `ω`, generated by `+i(ω t/2)σ_z`
    (`rotFrame`), with detuning `Δ = ω₀ - ω`.
  * Matrix norm: the `ℓ^∞` operator norm (max row sum), matching the
    convention of `MatrixBCHCubic` and the rest of the matrix-analysis corpus.

References:
  Bloch & Siegert, Phys. Rev. 57, 522 (1940) — the counter-rotating shift.
-/

import Mathlib
import SKEFTHawking.PauliMatrices
import SKEFTHawking.Control.BanachAveraging

set_option autoImplicit false

namespace SKEFTHawking.Control

open Matrix Complex

attribute [local instance] Matrix.linftyOpNormedAddCommGroup
  Matrix.linftyOpNormedRing
  Matrix.linftyOpNormedAlgebra

noncomputable section

/-! ## 1. The driven two-level Hamiltonian -/

/-- A Hermitian drive operator in the Pauli basis, `O = a·1 + b·σ_x + c·σ_y + d·σ_z`
with `a b c d : ℝ`.

Every Hermitian `2×2` complex matrix has exactly this form, so restricting to real
coefficients loses no generality for a physical (Hermitian) drive. -/
def driveOp (a b c d : ℝ) : Matrix (Fin 2) (Fin 2) ℂ :=
  (a : ℂ) • (1 : Matrix (Fin 2) (Fin 2) ℂ) + (b : ℂ) • σ_x + (c : ℂ) • σ_y + (d : ℂ) • σ_z

/-- The lab-frame driven two-level Hamiltonian
`H(t) = (ω₀/2)·σ_z + Ω·cos(ω t + φ)·O`. -/
def drivenHamiltonian (ω₀ ω Ω φ a b c d : ℝ) (t : ℝ) : Matrix (Fin 2) (Fin 2) ℂ :=
  ((ω₀ / 2 : ℝ) : ℂ) • σ_z + ((Ω * Real.cos (ω * t + φ) : ℝ) : ℂ) • driveOp a b c d

/-- The rotating frame at the drive frequency, `R(t) = cos(ωt/2)·1 + i·sin(ωt/2)·σ_z`.

This is the closed form of `exp(i(ω t/2)·σ_z)`; it is pinned as that exponential by
`rotFrame_hasDerivAt` (it solves the defining ODE with `R(0) = 1`), so the closed form
is a definition of convenience, not an additional assumption. -/
def rotFrame (ω : ℝ) (t : ℝ) : Matrix (Fin 2) (Fin 2) ℂ :=
  ((Real.cos (ω * t / 2) : ℝ) : ℂ) • (1 : Matrix (Fin 2) (Fin 2) ℂ)
    + (Complex.I * ((Real.sin (ω * t / 2) : ℝ) : ℂ)) • σ_z

/-! ## 2. The exact split: co-rotating generator + counter-rotating remainder -/

/-- The co-rotating (rotating-wave) generator — time-INDEPENDENT:
`H_RWA = (Δ/2)·σ_z + (Ω/2)·[(b cos φ - c sin φ)·σ_x + (b sin φ + c cos φ)·σ_y]`,
with detuning `Δ = ω₀ - ω`.

Note the longitudinal drive components `a` and `d` are absent: a drive along `1` or
`σ_z` is purely counter-rotating and averages away entirely. -/
def rwaGenerator (ω₀ ω Ω φ b c : ℝ) : Matrix (Fin 2) (Fin 2) ℂ :=
  (((ω₀ - ω) / 2 : ℝ) : ℂ) • σ_z
    + ((Ω / 2 * (b * Real.cos φ - c * Real.sin φ) : ℝ) : ℂ) • σ_x
    + ((Ω / 2 * (b * Real.sin φ + c * Real.cos φ) : ℝ) : ℂ) • σ_y

/-- The counter-rotating remainder: the longitudinal piece oscillating at `ω`, plus
the transverse piece oscillating at `2ω`. Its time average vanishes; that is what
makes `bsAntiderivative` bounded uniformly in `t`. -/
def counterRotating (ω Ω φ a b c d : ℝ) (t : ℝ) : Matrix (Fin 2) (Fin 2) ℂ :=
  ((Ω * Real.cos (ω * t + φ) : ℝ) : ℂ) •
      ((a : ℂ) • (1 : Matrix (Fin 2) (Fin 2) ℂ) + (d : ℂ) • σ_z)
    + ((Ω / 2 * (b * Real.cos (2 * ω * t + φ) + c * Real.sin (2 * ω * t + φ)) : ℝ) : ℂ) • σ_x
    + ((Ω / 2 * (-b * Real.sin (2 * ω * t + φ) + c * Real.cos (2 * ω * t + φ)) : ℝ) : ℂ) • σ_y

/-- The exact interaction-picture generator,
`H_I(t) = R(t) H(t) R(t)† - (ω/2)·σ_z`. -/
def interactionHamiltonian (ω₀ ω Ω φ a b c d : ℝ) (t : ℝ) : Matrix (Fin 2) (Fin 2) ℂ :=
  rotFrame ω t * drivenHamiltonian ω₀ ω Ω φ a b c d t * (rotFrame ω t)ᴴ
    - ((ω / 2 : ℝ) : ℂ) • σ_z

/-! ### 2.1 The rotating frame is unitary and acts on the Pauli basis as a rotation -/

-- Entry-level computation idiom shared by every conjugation lemma below: expand the
-- `2×2` product, then discharge the resulting real-trigonometric identity.
-- `Complex.ofReal_cos`/`ofReal_sin` are suppressed so that `↑(Real.cos x)` is not
-- rewritten into `Complex.cos ↑x`, which would put the goal outside `ring_nf`'s reach.

/-- `R(t)` is unitary. -/
theorem rotFrame_mul_conjTranspose (ω t : ℝ) :
    rotFrame ω t * (rotFrame ω t)ᴴ = 1 := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [rotFrame, σ_z, Matrix.mul_apply, Fin.sum_univ_two, Matrix.one_apply,
      Matrix.conjTranspose_apply, Complex.conj_ofReal,
      -Complex.ofReal_cos, -Complex.ofReal_sin, Complex.ext_iff] <;>
    ring_nf <;> simp

/-- Conjugating `σ_z` by the rotating frame leaves it fixed: the frame is generated by `σ_z`. -/
theorem rotFrame_conj_sz (ω t : ℝ) :
    rotFrame ω t * σ_z * (rotFrame ω t)ᴴ = σ_z := by
  have hpy := Real.sin_sq_add_cos_sq (ω * t / 2)
  ring_nf at hpy
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [rotFrame, σ_z, Matrix.mul_apply, Fin.sum_univ_two, Matrix.one_apply,
      Matrix.conjTranspose_apply, Complex.conj_ofReal,
      -Complex.ofReal_cos, -Complex.ofReal_sin, Complex.ext_iff] <;>
    ring_nf <;> refine ⟨by linarith [hpy], trivial⟩

/-- Conjugating the identity leaves it fixed (unitarity, restated for the drive expansion). -/
theorem rotFrame_conj_one (ω t : ℝ) :
    rotFrame ω t * 1 * (rotFrame ω t)ᴴ = 1 := by
  rw [mul_one]
  exact rotFrame_mul_conjTranspose ω t

/-- `R(t) σ_x R(t)† = cos(ωt)·σ_x - sin(ωt)·σ_y`. -/
theorem rotFrame_conj_sx (ω t : ℝ) :
    rotFrame ω t * σ_x * (rotFrame ω t)ᴴ
      = ((Real.cos (ω * t) : ℝ) : ℂ) • σ_x - ((Real.sin (ω * t) : ℝ) : ℂ) • σ_y := by
  have hpy := Real.sin_sq_add_cos_sq (ω * t / 2)
  have h2 : 2 * (ω * t / 2) = ω * t := by ring
  have hc0 := Real.cos_two_mul (ω * t / 2)
  rw [h2] at hc0
  have hs0 := Real.sin_two_mul (ω * t / 2)
  rw [h2] at hs0
  ring_nf at hpy hc0 hs0
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [rotFrame, σ_x, σ_y, σ_z, Matrix.mul_apply, Fin.sum_univ_two, Matrix.one_apply,
      Matrix.conjTranspose_apply, Complex.conj_ofReal, hc0, hs0,
      -Complex.ofReal_pow, -Complex.ofReal_cos, -Complex.ofReal_sin, Complex.ext_iff] <;>
    ring_nf <;> refine ⟨by linarith [hpy], trivial⟩

/-- `R(t) σ_y R(t)† = sin(ωt)·σ_x + cos(ωt)·σ_y`. -/
theorem rotFrame_conj_sy (ω t : ℝ) :
    rotFrame ω t * σ_y * (rotFrame ω t)ᴴ
      = ((Real.sin (ω * t) : ℝ) : ℂ) • σ_x + ((Real.cos (ω * t) : ℝ) : ℂ) • σ_y := by
  have hpy := Real.sin_sq_add_cos_sq (ω * t / 2)
  have h2 : 2 * (ω * t / 2) = ω * t := by ring
  have hc0 := Real.cos_two_mul (ω * t / 2)
  rw [h2] at hc0
  have hs0 := Real.sin_two_mul (ω * t / 2)
  rw [h2] at hs0
  ring_nf at hpy hc0 hs0
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [rotFrame, σ_x, σ_y, σ_z, Matrix.mul_apply, Fin.sum_univ_two, Matrix.one_apply,
      Matrix.conjTranspose_apply, Complex.conj_ofReal, hc0, hs0,
      -Complex.ofReal_pow, -Complex.ofReal_cos, -Complex.ofReal_sin, Complex.ext_iff] <;>
    ring_nf <;> constructor <;> (first | trivial | linarith [hpy])

/-! ### 2.2 The exact split -/

/-- **The exact rotating-frame decomposition.** The interaction-picture generator splits,
as an EXACT algebraic identity (no approximation anywhere), into the time-independent
co-rotating generator plus the purely oscillatory counter-rotating remainder:

`H_I(t) = H_RWA + V(t)`.

The rotating-wave *approximation* is the act of discarding `V`; this theorem is what makes
that discard quantifiable rather than folklore. -/
theorem interactionHamiltonian_decomp (ω₀ ω Ω φ a b c d t : ℝ) :
    interactionHamiltonian ω₀ ω Ω φ a b c d t
      = rwaGenerator ω₀ ω Ω φ b c + counterRotating ω Ω φ a b c d t := by
  have e2 : 2 * ω * t + φ = 2 * (ω * t) + φ := by ring
  have hs2 : Real.sin (ω * t) ^ 2 = 1 - Real.cos (ω * t) ^ 2 := by
    nlinarith [Real.sin_sq_add_cos_sq (ω * t)]
  simp only [interactionHamiltonian, drivenHamiltonian, driveOp, rwaGenerator, counterRotating, e2,
    Matrix.mul_add, Matrix.add_mul, Matrix.mul_smul, Matrix.smul_mul,
    rotFrame_conj_one, rotFrame_conj_sx, rotFrame_conj_sy, rotFrame_conj_sz,
    Real.cos_add, Real.sin_add, Real.cos_two_mul, Real.sin_two_mul]
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [σ_x, σ_y, σ_z, Complex.ext_iff,
      -Complex.ofReal_cos, -Complex.ofReal_sin, -Complex.ofReal_pow] <;>
    ring_nf <;> constructor <;> (rw [hs2]; ring)

/-! ## 3. The Bloch–Siegert scale: a closed-form antiderivative for the remainder

This is where the `1/ω` comes from, and it is the whole reason the RWA remainder is small.
`counterRotating` is a trigonometric polynomial (frequencies `ω` and `2ω`), so it has an
ELEMENTARY antiderivative — no abstract integration-by-parts is required — and every term of
that antiderivative carries an explicit `1/ω` while being bounded *uniformly in `t`*.

Contrast: a naive Duhamel/Grönwall estimate consumes only `sup ‖V‖ = O(Ω)` and therefore yields
`O(Ω·T)`, which carries no `1/ω` and grows without bound in `T`. That estimate is true but is
NOT of Bloch–Siegert scale. -/

/-- The closed-form antiderivative of `counterRotating`, normalised to vanish at `t = 0`. -/
def bsAntiderivative (ω Ω φ a b c d : ℝ) (t : ℝ) : Matrix (Fin 2) (Fin 2) ℂ :=
  (((Ω / ω) * (Real.sin (ω * t + φ) - Real.sin φ) : ℝ) : ℂ) •
      ((a : ℂ) • (1 : Matrix (Fin 2) (Fin 2) ℂ) + (d : ℂ) • σ_z)
    + (((Ω / (4 * ω)) * (b * (Real.sin (2 * ω * t + φ) - Real.sin φ)
          - c * (Real.cos (2 * ω * t + φ) - Real.cos φ)) : ℝ) : ℂ) • σ_x
    + (((Ω / (4 * ω)) * (b * (Real.cos (2 * ω * t + φ) - Real.cos φ)
          + c * (Real.sin (2 * ω * t + φ) - Real.sin φ)) : ℝ) : ℂ) • σ_y

/-- The antiderivative is normalised: `S(0) = 0`. This is what makes the boundary term at `t = 0`
drop out of the integration-by-parts estimate. -/
theorem bsAntiderivative_zero (ω Ω φ a b c d : ℝ) :
    bsAntiderivative ω Ω φ a b c d 0 = 0 := by
  simp [bsAntiderivative]

/-- `bsAntiderivative` genuinely differentiates to `counterRotating` — this is what earns it the
name, and it is where the `1/ω` prefactors are consumed by the chain rule. -/
theorem bsAntiderivative_hasDerivAt (ω Ω φ a b c d : ℝ) (hω : ω ≠ 0) (t : ℝ) :
    HasDerivAt (bsAntiderivative ω Ω φ a b c d)
      (counterRotating ω Ω φ a b c d t) t := by
  have h1 : HasDerivAt (fun s : ℝ => Real.sin (ω * s + φ)) (Real.cos (ω * t + φ) * ω) t := by
    simpa using (((hasDerivAt_id t).const_mul ω).add_const φ).sin
  have h2 : HasDerivAt (fun s : ℝ => Real.sin (2 * ω * s + φ))
      (Real.cos (2 * ω * t + φ) * (2 * ω)) t := by
    simpa using (((hasDerivAt_id t).const_mul (2 * ω)).add_const φ).sin
  have h3 : HasDerivAt (fun s : ℝ => Real.cos (2 * ω * s + φ))
      (-Real.sin (2 * ω * t + φ) * (2 * ω)) t := by
    simpa using (((hasDerivAt_id t).const_mul (2 * ω)).add_const φ).cos
  -- The three scalar coefficient functions, with the `1/ω` consumed by the chain rule.
  have g1 : HasDerivAt (fun s : ℝ => (Ω / ω) * (Real.sin (ω * s + φ) - Real.sin φ))
      (Ω * Real.cos (ω * t + φ)) t := by
    have heq : Ω * Real.cos (ω * t + φ) = Ω / ω * (Real.cos (ω * t + φ) * ω) := by
      field_simp
    rw [heq]
    exact (h1.sub_const (Real.sin φ)).const_mul (Ω / ω)
  have g2 : HasDerivAt (fun s : ℝ => (Ω / (4 * ω)) * (b * (Real.sin (2 * ω * s + φ) - Real.sin φ)
        - c * (Real.cos (2 * ω * s + φ) - Real.cos φ)))
      (Ω / 2 * (b * Real.cos (2 * ω * t + φ) + c * Real.sin (2 * ω * t + φ))) t := by
    have heq : Ω / 2 * (b * Real.cos (2 * ω * t + φ) + c * Real.sin (2 * ω * t + φ))
        = Ω / (4 * ω) * (b * (Real.cos (2 * ω * t + φ) * (2 * ω))
          - c * (-Real.sin (2 * ω * t + φ) * (2 * ω))) := by
      field_simp
      ring
    rw [heq]
    exact (((h2.sub_const (Real.sin φ)).const_mul b).sub
      ((h3.sub_const (Real.cos φ)).const_mul c)).const_mul (Ω / (4 * ω))
  have g3 : HasDerivAt (fun s : ℝ => (Ω / (4 * ω)) * (b * (Real.cos (2 * ω * s + φ) - Real.cos φ)
        + c * (Real.sin (2 * ω * s + φ) - Real.sin φ)))
      (Ω / 2 * (-b * Real.sin (2 * ω * t + φ) + c * Real.cos (2 * ω * t + φ))) t := by
    have heq : Ω / 2 * (-b * Real.sin (2 * ω * t + φ) + c * Real.cos (2 * ω * t + φ))
        = Ω / (4 * ω) * (b * (-Real.sin (2 * ω * t + φ) * (2 * ω))
          + c * (Real.cos (2 * ω * t + φ) * (2 * ω))) := by
      field_simp
      ring
    rw [heq]
    exact (((h3.sub_const (Real.cos φ)).const_mul b).add
      ((h2.sub_const (Real.sin φ)).const_mul c)).const_mul (Ω / (4 * ω))
  -- Assemble: each summand is (scalar function) • (constant matrix). The pointwise sum
  -- `(f₁ + f₂) + f₃` is definitionally `bsAntiderivative`, so `exact` closes it directly.
  have hsum :=
    ((g1.ofReal_comp.smul_const ((a : ℂ) • (1 : Matrix (Fin 2) (Fin 2) ℂ) + (d : ℂ) • σ_z)).add
      (g2.ofReal_comp.smul_const σ_x)).add (g3.ofReal_comp.smul_const σ_y)
  exact hsum

/-! ### 3.1 Pauli operator norms (ℓ^∞ operator norm = max row sum) -/

lemma linftyOpNorm_sigmaX_le_one : ‖σ_x‖ ≤ 1 := by
  rw [Matrix.linfty_opNorm_def]; simp [σ_x, Fin.sum_univ_two]

lemma linftyOpNorm_sigmaY_le_one : ‖σ_y‖ ≤ 1 := by
  rw [Matrix.linfty_opNorm_def]; simp [σ_y, Fin.sum_univ_two]

lemma linftyOpNorm_sigmaZ_le_one : ‖σ_z‖ ≤ 1 := by
  rw [Matrix.linfty_opNorm_def]; simp [σ_z, Fin.sum_univ_two]

lemma linftyOpNorm_one_le_one : ‖(1 : Matrix (Fin 2) (Fin 2) ℂ)‖ ≤ 1 := by
  rw [Matrix.linfty_opNorm_def]; simp [Matrix.one_apply, Fin.sum_univ_two]

/-! ### 3.2 The Bloch–Siegert bound -/

private lemma abs_sin_sub_sin_le_two (x y : ℝ) : |Real.sin x - Real.sin y| ≤ 2 := by
  rw [abs_le]
  constructor <;>
    nlinarith [Real.neg_one_le_sin x, Real.sin_le_one x, Real.neg_one_le_sin y, Real.sin_le_one y]

private lemma abs_cos_sub_cos_le_two (x y : ℝ) : |Real.cos x - Real.cos y| ≤ 2 := by
  rw [abs_le]
  constructor <;>
    nlinarith [Real.neg_one_le_cos x, Real.cos_le_one x, Real.neg_one_le_cos y, Real.cos_le_one y]

/-- **The Bloch–Siegert bound — the load-bearing estimate of this module.**

The antiderivative of the counter-rotating remainder is bounded by an explicit constant times
`Ω/ω`, **uniformly in `t`**. The uniformity is the whole point: it is what separates this from a
naive Duhamel estimate, which bounds the same object only by `O(Ω·T)` — carrying no `1/ω` and
growing without bound in `T`.

The constant `2` multiplies the drive's coefficient `ℓ¹` norm `|a|+|b|+|c|+|d|`, so the bound is
explicit in every parameter and degrades gracefully as the drive operator grows. -/
theorem bsAntiderivative_norm_le (ω Ω φ a b c d t : ℝ) (hω : 0 < ω) (hΩ : 0 ≤ Ω) :
    ‖bsAntiderivative ω Ω φ a b c d t‖ ≤ 2 * (Ω / ω) * (|a| + |b| + |c| + |d|) := by
  have hr : 0 ≤ Ω / ω := div_nonneg hΩ hω.le
  have hsmul : ∀ (r : ℝ) (M : Matrix (Fin 2) (Fin 2) ℂ), ‖((r : ℝ) : ℂ) • M‖ = |r| * ‖M‖ := by
    intro r M; rw [norm_smul]; simp
  -- Longitudinal block: ‖a•1 + d•σ_z‖ ≤ |a| + |d|.
  have hM1 : ‖(a : ℂ) • (1 : Matrix (Fin 2) (Fin 2) ℂ) + (d : ℂ) • σ_z‖ ≤ |a| + |d| := by
    refine (norm_add_le _ _).trans ?_
    rw [hsmul a, hsmul d]
    have := linftyOpNorm_one_le_one
    have := linftyOpNorm_sigmaZ_le_one
    nlinarith [abs_nonneg a, abs_nonneg d, norm_nonneg (1 : Matrix (Fin 2) (Fin 2) ℂ),
      norm_nonneg (σ_z : Matrix (Fin 2) (Fin 2) ℂ)]
  -- The three scalar coefficients.
  have hA1 : |(Ω / ω) * (Real.sin (ω * t + φ) - Real.sin φ)| ≤ 2 * (Ω / ω) := by
    rw [abs_mul, abs_of_nonneg hr]
    nlinarith [abs_sin_sub_sin_le_two (ω * t + φ) φ, abs_nonneg (Real.sin (ω * t + φ) - Real.sin φ)]
  have hA2 : |(Ω / (4 * ω)) * (b * (Real.sin (2 * ω * t + φ) - Real.sin φ)
      - c * (Real.cos (2 * ω * t + φ) - Real.cos φ))| ≤ (Ω / ω) * (|b| + |c|) / 2 := by
    rw [abs_mul]
    have h4 : |Ω / (4 * ω)| = (Ω / ω) / 4 := by
      rw [abs_of_nonneg (by positivity)]; field_simp
    rw [h4]
    have hin : |b * (Real.sin (2 * ω * t + φ) - Real.sin φ)
        - c * (Real.cos (2 * ω * t + φ) - Real.cos φ)| ≤ 2 * |b| + 2 * |c| := by
      refine (abs_sub _ _).trans ?_
      rw [abs_mul, abs_mul]
      nlinarith [abs_sin_sub_sin_le_two (2 * ω * t + φ) φ,
        abs_cos_sub_cos_le_two (2 * ω * t + φ) φ, abs_nonneg b, abs_nonneg c]
    nlinarith [hin, hr, abs_nonneg b, abs_nonneg c]
  have hA3 : |(Ω / (4 * ω)) * (b * (Real.cos (2 * ω * t + φ) - Real.cos φ)
      + c * (Real.sin (2 * ω * t + φ) - Real.sin φ))| ≤ (Ω / ω) * (|b| + |c|) / 2 := by
    rw [abs_mul]
    have h4 : |Ω / (4 * ω)| = (Ω / ω) / 4 := by
      rw [abs_of_nonneg (by positivity)]; field_simp
    rw [h4]
    have hin : |b * (Real.cos (2 * ω * t + φ) - Real.cos φ)
        + c * (Real.sin (2 * ω * t + φ) - Real.sin φ)| ≤ 2 * |b| + 2 * |c| := by
      refine (abs_add_le _ _).trans ?_
      rw [abs_mul, abs_mul]
      nlinarith [abs_sin_sub_sin_le_two (2 * ω * t + φ) φ,
        abs_cos_sub_cos_le_two (2 * ω * t + φ) φ, abs_nonneg b, abs_nonneg c]
    nlinarith [hin, hr, abs_nonneg b, abs_nonneg c]
  -- Assemble by the triangle inequality, bounding each product of two nonneg factors.
  rw [bsAntiderivative]
  refine ((norm_add_le _ _).trans (add_le_add (norm_add_le _ _) le_rfl)).trans ?_
  rw [hsmul, hsmul, hsmul]
  have hx := linftyOpNorm_sigmaX_le_one
  have hy := linftyOpNorm_sigmaY_le_one
  have t1 : |(Ω / ω) * (Real.sin (ω * t + φ) - Real.sin φ)|
      * ‖(a : ℂ) • (1 : Matrix (Fin 2) (Fin 2) ℂ) + (d : ℂ) • σ_z‖
      ≤ (2 * (Ω / ω)) * (|a| + |d|) :=
    mul_le_mul hA1 hM1 (norm_nonneg _) (by positivity)
  have t2 : |(Ω / (4 * ω)) * (b * (Real.sin (2 * ω * t + φ) - Real.sin φ)
        - c * (Real.cos (2 * ω * t + φ) - Real.cos φ))| * ‖σ_x‖
      ≤ ((Ω / ω) * (|b| + |c|) / 2) * 1 :=
    mul_le_mul hA2 hx (norm_nonneg _) (by positivity)
  have t3 : |(Ω / (4 * ω)) * (b * (Real.cos (2 * ω * t + φ) - Real.cos φ)
        + c * (Real.sin (2 * ω * t + φ) - Real.sin φ))| * ‖σ_y‖
      ≤ ((Ω / ω) * (|b| + |c|) / 2) * 1 :=
    mul_le_mul hA3 hy (norm_nonneg _) (by positivity)
  nlinarith [t1, t2, t3, hr, abs_nonneg a, abs_nonneg b, abs_nonneg c, abs_nonneg d,
    mul_nonneg hr (abs_nonneg b), mul_nonneg hr (abs_nonneg c)]

/-! ## 4. The time-integrated remainder

`bsAntiderivative` is not merely *a* bounded function: by the fundamental theorem of calculus it
IS the time integral of the counter-rotating remainder. That integral is the first-order term of
the exact-vs-reduced propagator discrepancy (the leading Dyson/Magnus term), so bounding it
uniformly in `T` is what makes the rotating-wave reduction quantitatively controlled. -/

lemma continuous_counterRotating (ω Ω φ a b c d : ℝ) :
    Continuous (counterRotating ω Ω φ a b c d) := by
  unfold counterRotating
  fun_prop

/-- FTC: the counter-rotating remainder integrates to its closed-form antiderivative. -/
theorem integral_counterRotating (ω Ω φ a b c d T : ℝ) (hω : ω ≠ 0) :
    (∫ s in (0 : ℝ)..T, counterRotating ω Ω φ a b c d s)
      = bsAntiderivative ω Ω φ a b c d T := by
  rw [intervalIntegral.integral_eq_sub_of_hasDerivAt
    (fun s _ => bsAntiderivative_hasDerivAt ω Ω φ a b c d hω s)
    ((continuous_counterRotating ω Ω φ a b c d).intervalIntegrable 0 T)]
  rw [bsAntiderivative_zero, sub_zero]

/-- **The integrated counter-rotating drive is Bloch–Siegert bounded, uniformly in `T`.**

This is the sharp contrast with the naive estimate. Bounding the integrand pointwise gives only
`∫₀ᵀ ‖V‖ = O(Ω·T)`, which grows without bound; the oscillation of `V` makes the *integral* stay
bounded by `O(Ω/ω)` no matter how long the drive runs. -/
theorem integral_counterRotating_norm_le (ω Ω φ a b c d T : ℝ) (hω : 0 < ω) (hΩ : 0 ≤ Ω) :
    ‖∫ s in (0 : ℝ)..T, counterRotating ω Ω φ a b c d s‖
      ≤ 2 * (Ω / ω) * (|a| + |b| + |c| + |d|) := by
  rw [integral_counterRotating ω Ω φ a b c d T hω.ne']
  exact bsAntiderivative_norm_le ω Ω φ a b c d T hω hΩ

/-! ### 4.1 Witnesses: where the reduction is controlled, and where it honestly is not

Both witnesses use a unit transverse drive (`b = 1`, others zero) and differ only in `ω/Ω`.
They are stated at every `t` and every `T`, so neither is an artefact of a lucky time. -/

/-- **Validity witness.** Far off resonance (`ω = 1000 Ω`) the integrated counter-rotating drive is
bounded by `2×10⁻³` for ALL `T` — the rotating-wave reduction is quantitatively controlled. -/
theorem integral_counterRotating_witness_valid (T : ℝ) :
    ‖∫ s in (0 : ℝ)..T, counterRotating 1000 1 0 0 1 0 0 s‖ ≤ 1 / 100 := by
  have h := integral_counterRotating_norm_le 1000 1 0 0 1 0 0 T (by norm_num) (by norm_num)
  have hb : (2 : ℝ) * (1 / 1000) * (|(0 : ℝ)| + |(1 : ℝ)| + |(0 : ℝ)| + |(0 : ℝ)|) ≤ 1 / 100 := by
    norm_num
  linarith

lemma linftyOpNorm_sigmaY_eq_one : ‖σ_y‖ = 1 := by
  apply le_antisymm linftyOpNorm_sigmaY_le_one
  rw [Matrix.linfty_opNorm_def]; simp [σ_y, Fin.sum_univ_two]

/-- **Honest-failure witness — the ACTUAL quantity, not a restatement of the bound.**

At resonance-scale drive (`ω = Ω`) the integrated counter-rotating drive *attains* `1/2` at
`T = π/2`. This is an exact value of the real object, so it genuinely certifies that the rotating-
wave reduction is uncontrolled here — 250× the `10⁻³`-scale bound the validity witness enjoys.

Stating the failure as a computed value rather than as "the bound is large" matters: a large upper
bound proves nothing on its own, whereas this exhibits the remainder actually being order-unity. -/
theorem integral_counterRotating_witness_resonance :
    ‖∫ s in (0 : ℝ)..(Real.pi / 2), counterRotating 1 1 0 0 1 0 0 s‖ = 1 / 2 := by
  rw [integral_counterRotating 1 1 0 0 1 0 0 (Real.pi / 2) (by norm_num)]
  unfold bsAntiderivative
  rw [show (2 : ℝ) * 1 * (Real.pi / 2) + 0 = Real.pi by ring,
    show (1 : ℝ) * (Real.pi / 2) + 0 = Real.pi / 2 by ring]
  norm_num [Real.sin_pi, Real.cos_pi, Real.sin_pi_div_two, norm_smul, linftyOpNorm_sigmaY_eq_one]

/-! ## 5. Rotation-angle calibration at the RWA level

CONVENTION (stated, not assumed): `θ` is the *exponent* parameter, i.e. the co-rotating propagator
is `exp(-i·θ·(n̂·σ))`. The Bloch-sphere rotation angle is `2θ`. With this convention the calibration
identity is `θ = (m/2)·Ω·T`, where `m = |⟨0|O_drive|1⟩|` is the projected drive element. -/

/-- The SIGNED projected drive element `⟨0|O_drive|1⟩ = b - i·c`.

Signed, not a magnitude: the sign/phase is exactly what a calibration can get wrong, and
`DriveCalibration` (Wave 2) carries that as an explicit fail condition. -/
def projectedDriveElement (b c : ℝ) : ℂ := (b : ℂ) - Complex.I * (c : ℂ)

@[simp] lemma projectedDriveElement_normSq (b c : ℝ) :
    Complex.normSq (projectedDriveElement b c) = b ^ 2 + c ^ 2 := by
  simp [projectedDriveElement, Complex.normSq_apply]; ring

/-- **The co-rotating generator squares to a scalar — the GENERAL, off-resonance form.**

`H_RWA² = ((Δ² + Ω²m²)/4)·1` with detuning `Δ = ω₀ - ω`. Since a traceless involution generates a
rotation, this pins the generator's magnitude EXACTLY at `√(Δ² + Ω²m²)/2` — so the accumulated
angle is `(T/2)√(Δ² + Ω²m²)`, and the familiar `(m/2)·Ω·T` is the `Δ = 0` case, NOT the general
one. Detuning genuinely changes the rotation rate; a calibration that ignores it is wrong off
resonance. -/
theorem rwaGenerator_sq (ω₀ ω Ω φ b c : ℝ) :
    rwaGenerator ω₀ ω Ω φ b c ^ 2
      = (((ω₀ - ω) ^ 2 / 4 + Ω ^ 2 * (b ^ 2 + c ^ 2) / 4 : ℝ) : ℂ)
        • (1 : Matrix (Fin 2) (Fin 2) ℂ) := by
  have hpy := Real.sin_sq_add_cos_sq φ
  rw [pow_two]
  unfold rwaGenerator
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [σ_x, σ_y, σ_z, Matrix.mul_apply, Fin.sum_univ_two, Complex.ext_iff,
      -Complex.ofReal_pow, -Complex.ofReal_cos, -Complex.ofReal_sin] <;>
    ring_nf <;> constructor <;>
    (first
      | trivial
      | linear_combination (Ω ^ 2 * (b ^ 2 + c ^ 2) / 4) * hpy)

/-- The resonance case, as a corollary of the general identity. -/
theorem rwaGenerator_sq_resonance (ω Ω φ b c : ℝ) :
    rwaGenerator ω ω Ω φ b c ^ 2
      = ((Ω ^ 2 * (b ^ 2 + c ^ 2) / 4 : ℝ) : ℂ) • (1 : Matrix (Fin 2) (Fin 2) ℂ) := by
  have h := rwaGenerator_sq ω ω Ω φ b c
  simpa using h

/-- The GENERAL rotation angle accumulated over `T` at detuning `Δ`, in the exponent convention:
`θ = (T/2)·√(Δ² + Ω²m²)`, the magnitude pinned by `rwaGenerator_sq`. -/
def generalRotationAngle (Δ Ω b c T : ℝ) : ℝ :=
  (T / 2) * Real.sqrt (Δ ^ 2 + Ω ^ 2 * (b ^ 2 + c ^ 2))

/-- The RWA rotation angle accumulated over duration `T`, in the exponent convention above.

⚠️ ON RESONANCE ONLY. This is `generalRotationAngle` at `Δ = 0` (`generalRotationAngle_resonance`);
it ignores detuning, so it is the achieved angle only when `ω₀ = ω`. Off resonance the rate is
`√(Δ² + Ω²m²)/2`, strictly larger. -/
def rwaRotationAngle (Ω b c T : ℝ) : ℝ := (Real.sqrt (b ^ 2 + c ^ 2) / 2) * Ω * T

/-- At zero detuning the general angle reduces to `rwaRotationAngle`. This is what makes the
resonance restriction on `rwaRotationAngle` precise rather than merely asserted. -/
theorem generalRotationAngle_resonance (Ω b c T : ℝ) (hΩ : 0 ≤ Ω) :
    generalRotationAngle 0 Ω b c T = rwaRotationAngle Ω b c T := by
  unfold generalRotationAngle rwaRotationAngle
  rw [show (0 : ℝ) ^ 2 + Ω ^ 2 * (b ^ 2 + c ^ 2) = Ω ^ 2 * (b ^ 2 + c ^ 2) by ring,
    Real.sqrt_mul (by positivity), Real.sqrt_sq hΩ]
  ring

/-- **Detuning strictly increases the rotation rate.** Off resonance the achieved angle EXCEEDS the
on-resonance formula, so a calibration computed from `rwaRotationAngle` under-rotates — the
concrete failure the resonance restriction guards against. -/
theorem rwaRotationAngle_lt_generalRotationAngle (Δ Ω b c T : ℝ) (hΔ : Δ ≠ 0) (hΩ : 0 ≤ Ω)
    (hT : 0 < T) : rwaRotationAngle Ω b c T < generalRotationAngle Δ Ω b c T := by
  rw [← generalRotationAngle_resonance Ω b c T hΩ]
  unfold generalRotationAngle
  have hlt : Ω ^ 2 * (b ^ 2 + c ^ 2) < Δ ^ 2 + Ω ^ 2 * (b ^ 2 + c ^ 2) := by
    have : 0 < Δ ^ 2 := by positivity
    linarith
  have hs : Real.sqrt ((0:ℝ) ^ 2 + Ω ^ 2 * (b ^ 2 + c ^ 2))
      < Real.sqrt (Δ ^ 2 + Ω ^ 2 * (b ^ 2 + c ^ 2)) := by
    apply Real.sqrt_lt_sqrt (by positivity)
    simpa using hlt
  have hT2 : 0 < T / 2 := by linarith
  exact mul_lt_mul_of_pos_left hs hT2

/-- **The calibration identity:** `θ = (m/2)·Ω·T` with `m = |⟨0|O_drive|1⟩|`. -/
theorem rwaRotationAngle_eq_projected (Ω b c T : ℝ) :
    rwaRotationAngle Ω b c T = (‖projectedDriveElement b c‖ / 2) * Ω * T := by
  unfold rwaRotationAngle
  simp [Complex.norm_def, projectedDriveElement_normSq]

/-! ## 6. The conjugated integrated remainder, at propagator level

The abstract averaging bound instantiated at `Matrix (Fin 2) (Fin 2) ℂ`, with the counter-rotating
term as the driving generator and `bsAntiderivative` as its antiderivative. The hypotheses `hL`,
`hU` are propagator ODEs (`L' = L·P`, `U' = Q·U`), so this is a statement about propagators, not
about an isolated integral.

The propagator factor bounds `KL`, `KU` are left GENERAL rather than pinned to `1`. This is not
cosmetic: at the `ℓ^∞` operator norm used in this file, `exp(-iθσ_x)` — the co-rotating propagator
at resonance — has row sums `|cos θ| + |sin θ|`, i.e. norm up to `√2`. A hypothesis `‖L s‖ ≤ 1`
would therefore exclude essentially every rotation, leaving a theorem that is true but about
`ℓ^∞`-contractive propagators rather than the ones this module exists to bound.

SCOPE. This bounds the CONJUGATED integrated remainder `‖∫₀ᵀ L·V·U‖`. The literal
`‖U_exact(T) − U_rwa(T)‖` form is `rwa_propagator_difference_bound` below, which composes this with
the discrepancy identity and the unitarity transfer from `BanachAveraging`. -/
theorem norm_integral_counterRotating_conjugated_le
    {L U P Q : ℝ → Matrix (Fin 2) (Fin 2) ℂ} {B KL KU Kp Kq T ω Ω φ a b c d : ℝ}
    (hS : ∀ s, HasDerivAt (bsAntiderivative ω Ω φ a b c d)
      (counterRotating ω Ω φ a b c d s) s)
    (hL : ∀ s, HasDerivAt L (L s * P s) s) (hU : ∀ s, HasDerivAt U (Q s * U s) s)
    (hSc : Continuous (bsAntiderivative ω Ω φ a b c d))
    (hLc : Continuous L) (hUc : Continuous U) (hPc : Continuous P) (hQc : Continuous Q)
    (hS0 : bsAntiderivative ω Ω φ a b c d 0 = 0)
    (hLb : ∀ s, ‖L s‖ ≤ KL) (hUb : ∀ s, ‖U s‖ ≤ KU)
    (hSb : ∀ s, ‖bsAntiderivative ω Ω φ a b c d s‖ ≤ B)
    (hPb : ∀ s, ‖P s‖ ≤ Kp) (hQb : ∀ s, ‖Q s‖ ≤ Kq) (hB : 0 ≤ B) (hT : 0 ≤ T) :
    ‖∫ s in (0 : ℝ)..T, L s * counterRotating ω Ω φ a b c d s * U s‖
      ≤ KL * KU * B * (1 + T * (Kp + Kq)) :=
  norm_integral_mul_mul_le hS hL hU hSc hLc hUc hPc hQc
    (continuous_counterRotating ω Ω φ a b c d) hS0 hLb hUb hSb hPb hQb hB hT

/-- **The propagator difference bound for the RWA system, at Bloch–Siegert scale.**

This is the literal `‖U_exact(T) − U_rwa(T)‖` statement. The Bloch–Siegert constant is supplied by
`bsAntiderivative_norm_le`, so the bound carries an explicit `Ω/ω`:

`‖U_exact(T) − U_rwa(T)‖ ≤ KUr·KL·KU·2(Ω/ω)(|a|+|b|+|c|+|d|)·(1 + T(Kp+Kq))`.

`hω : 0 < ω` and `hΩ : 0 ≤ Ω` are load-bearing — they are what make the constant `Ω/ω` rather than
an arbitrary `B`. The reduction is nowhere asserted as an equality. -/
theorem rwa_propagator_difference_bound
    {L U P Q : ℝ → Matrix (Fin 2) (Fin 2) ℂ} {Ur : Matrix (Fin 2) (Fin 2) ℂ}
    {KL KU KUr Kp Kq T ω Ω φ a b c d : ℝ} (hω : 0 < ω) (hΩ : 0 ≤ Ω)
    (hL : ∀ s, HasDerivAt L (L s * P s) s) (hU : ∀ s, HasDerivAt U (Q s * U s) s)
    (hSgen : ∀ s, HasDerivAt (bsAntiderivative ω Ω φ a b c d) (P s + Q s) s)
    (hLc : Continuous L) (hUc : Continuous U) (hPc : Continuous P) (hQc : Continuous Q)
    (hL0U0 : L 0 * U 0 = 1)
    (hLb : ∀ s, ‖L s‖ ≤ KL) (hUb : ∀ s, ‖U s‖ ≤ KU)
    (hPb : ∀ s, ‖P s‖ ≤ Kp) (hQb : ∀ s, ‖Q s‖ ≤ Kq) (hT : 0 ≤ T)
    (hinv : Ur * L T = 1) (hUrb : ‖Ur‖ ≤ KUr) :
    ‖U T - Ur‖ ≤ KUr * (KL * KU * (2 * (Ω / ω) * (|a| + |b| + |c| + |d|))
      * (1 + T * (Kp + Kq))) :=
  norm_propagator_sub_le hSgen hL hU
    (by unfold bsAntiderivative; fun_prop) hLc hUc hPc hQc
    (bsAntiderivative_zero ω Ω φ a b c d) hL0U0 hLb hUb
    (fun s => bsAntiderivative_norm_le ω Ω φ a b c d s hω hΩ) hPb hQb
    (by positivity) hT hinv hUrb

end

end SKEFTHawking.Control
