/-
Phase 6EE Wave 1: Rotating-wave reduction with an explicit remainder.

The rotating-wave *approximation* is folklore; the deliverable here is the
*inequality*. The exact interaction-picture generator is split, as an exact
algebraic identity, into a time-independent co-rotating part (`rwaGenerator`)
and a purely oscillatory counter-rotating remainder (`counterRotating`). The
remainder admits a CLOSED-FORM antiderivative (`bsAntiderivative`) whose norm is
bounded by `C · Ω / ω` — the Bloch-Siegert scale. That bound is the whole content:
a naive Duhamel/Gronwall estimate on the same system yields only `Ω·T/2`, which
grows without bound in `T` and carries no `1/ω`, and is therefore NOT of
Bloch-Siegert scale.

No theorem in this file asserts the co-rotating reduction as an equality.

Conventions (all explicit, none implicit):
  * Lab-frame Hamiltonian  `H(t) = (ω₀/2)·σ_z + Ω·cos(ω t + φ)·O`.
  * Drive operator `O` is Hermitian, given in the Pauli basis by REAL
    coefficients `a b c d` (`driveOp`). Every Hermitian 2×2 complex matrix
    arises this way, so no generality is lost for a physical drive.
  * Rotating frame at the drive frequency `ω`, generated by `+i(ω t/2)σ_z`
    (`rotFrame`), with detuning `Δ = ω₀ - ω`.
  * Matrix norm: the `ℓ^∞` operator norm (max row sum), matching the
    convention of `MatrixBCHCubic` and the rest of the matrix-analysis corpus.

References:
  Bloch & Siegert, Phys. Rev. 57, 522 (1940) — the counter-rotating shift.
-/

import Mathlib
import SKEFTHawking.PauliMatrices

set_option autoImplicit false

namespace SKEFTHawking.Control

open Matrix Complex

attribute [local instance] Matrix.linftyOpNormedAddCommGroup
  Matrix.linftyOpNormedRing
  Matrix.linftyOpNormedAlgebra

noncomputable section

/-! ## 1. The driven two-level Hamiltonian -/

/-- A Hermitian drive operator in the Pauli basis, `O = a·1 + b·σ_x + c·σ_y + d·σ_z`
with `a b c d : ℝ`.

Every Hermitian `2×2` complex matrix has exactly this form, so restricting to real
coefficients loses no generality for a physical (Hermitian) drive. -/
def driveOp (a b c d : ℝ) : Matrix (Fin 2) (Fin 2) ℂ :=
  (a : ℂ) • (1 : Matrix (Fin 2) (Fin 2) ℂ) + (b : ℂ) • σ_x + (c : ℂ) • σ_y + (d : ℂ) • σ_z

/-- The lab-frame driven two-level Hamiltonian
`H(t) = (ω₀/2)·σ_z + Ω·cos(ω t + φ)·O`. -/
def drivenHamiltonian (ω₀ ω Ω φ a b c d : ℝ) (t : ℝ) : Matrix (Fin 2) (Fin 2) ℂ :=
  ((ω₀ / 2 : ℝ) : ℂ) • σ_z + ((Ω * Real.cos (ω * t + φ) : ℝ) : ℂ) • driveOp a b c d

/-- The rotating frame at the drive frequency, `R(t) = cos(ωt/2)·1 + i·sin(ωt/2)·σ_z`.

This is the closed form of `exp(i(ω t/2)·σ_z)`; it is pinned as that exponential by
`rotFrame_hasDerivAt` (it solves the defining ODE with `R(0) = 1`), so the closed form
is a definition of convenience, not an additional assumption. -/
def rotFrame (ω : ℝ) (t : ℝ) : Matrix (Fin 2) (Fin 2) ℂ :=
  ((Real.cos (ω * t / 2) : ℝ) : ℂ) • (1 : Matrix (Fin 2) (Fin 2) ℂ)
    + (Complex.I * ((Real.sin (ω * t / 2) : ℝ) : ℂ)) • σ_z

/-! ## 2. The exact split: co-rotating generator + counter-rotating remainder -/

/-- The co-rotating (rotating-wave) generator — time-INDEPENDENT:
`H_RWA = (Δ/2)·σ_z + (Ω/2)·[(b cos φ - c sin φ)·σ_x + (b sin φ + c cos φ)·σ_y]`,
with detuning `Δ = ω₀ - ω`.

Note the longitudinal drive components `a` and `d` are absent: a drive along `1` or
`σ_z` is purely counter-rotating and averages away entirely. -/
def rwaGenerator (ω₀ ω Ω φ b c : ℝ) : Matrix (Fin 2) (Fin 2) ℂ :=
  (((ω₀ - ω) / 2 : ℝ) : ℂ) • σ_z
    + ((Ω / 2 * (b * Real.cos φ - c * Real.sin φ) : ℝ) : ℂ) • σ_x
    + ((Ω / 2 * (b * Real.sin φ + c * Real.cos φ) : ℝ) : ℂ) • σ_y

/-- The counter-rotating remainder: the longitudinal piece oscillating at `ω`, plus
the transverse piece oscillating at `2ω`. Its time average vanishes; that is what
makes `bsAntiderivative` bounded uniformly in `t`. -/
def counterRotating (ω Ω φ a b c d : ℝ) (t : ℝ) : Matrix (Fin 2) (Fin 2) ℂ :=
  ((Ω * Real.cos (ω * t + φ) : ℝ) : ℂ) •
      ((a : ℂ) • (1 : Matrix (Fin 2) (Fin 2) ℂ) + (d : ℂ) • σ_z)
    + ((Ω / 2 * (b * Real.cos (2 * ω * t + φ) + c * Real.sin (2 * ω * t + φ)) : ℝ) : ℂ) • σ_x
    + ((Ω / 2 * (-b * Real.sin (2 * ω * t + φ) + c * Real.cos (2 * ω * t + φ)) : ℝ) : ℂ) • σ_y

/-- The exact interaction-picture generator,
`H_I(t) = R(t) H(t) R(t)† - (ω/2)·σ_z`. -/
def interactionHamiltonian (ω₀ ω Ω φ a b c d : ℝ) (t : ℝ) : Matrix (Fin 2) (Fin 2) ℂ :=
  rotFrame ω t * drivenHamiltonian ω₀ ω Ω φ a b c d t * (rotFrame ω t)ᴴ
    - ((ω / 2 : ℝ) : ℂ) • σ_z

/-! ### 2.1 The rotating frame is unitary and acts on the Pauli basis as a rotation -/

-- Entry-level computation idiom shared by every conjugation lemma below: expand the
-- `2×2` product, then discharge the resulting real-trigonometric identity.
-- `Complex.ofReal_cos`/`ofReal_sin` are suppressed so that `↑(Real.cos x)` is not
-- rewritten into `Complex.cos ↑x`, which would put the goal outside `ring_nf`'s reach.

/-- `R(t)` is unitary. -/
theorem rotFrame_mul_conjTranspose (ω t : ℝ) :
    rotFrame ω t * (rotFrame ω t)ᴴ = 1 := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [rotFrame, σ_z, Matrix.mul_apply, Fin.sum_univ_two, Matrix.one_apply,
      Matrix.conjTranspose_apply, Complex.conj_ofReal,
      -Complex.ofReal_cos, -Complex.ofReal_sin, Complex.ext_iff] <;>
    ring_nf <;> simp

/-- Conjugating `σ_z` by the rotating frame leaves it fixed: the frame is generated by `σ_z`. -/
theorem rotFrame_conj_sz (ω t : ℝ) :
    rotFrame ω t * σ_z * (rotFrame ω t)ᴴ = σ_z := by
  have hpy := Real.sin_sq_add_cos_sq (ω * t / 2)
  ring_nf at hpy
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [rotFrame, σ_z, Matrix.mul_apply, Fin.sum_univ_two, Matrix.one_apply,
      Matrix.conjTranspose_apply, Complex.conj_ofReal,
      -Complex.ofReal_cos, -Complex.ofReal_sin, Complex.ext_iff] <;>
    ring_nf <;> refine ⟨by linarith [hpy], trivial⟩

/-- Conjugating the identity leaves it fixed (unitarity, restated for the drive expansion). -/
theorem rotFrame_conj_one (ω t : ℝ) :
    rotFrame ω t * 1 * (rotFrame ω t)ᴴ = 1 := by
  rw [mul_one]
  exact rotFrame_mul_conjTranspose ω t

/-- `R(t) σ_x R(t)† = cos(ωt)·σ_x - sin(ωt)·σ_y`. -/
theorem rotFrame_conj_sx (ω t : ℝ) :
    rotFrame ω t * σ_x * (rotFrame ω t)ᴴ
      = ((Real.cos (ω * t) : ℝ) : ℂ) • σ_x - ((Real.sin (ω * t) : ℝ) : ℂ) • σ_y := by
  have hpy := Real.sin_sq_add_cos_sq (ω * t / 2)
  have h2 : 2 * (ω * t / 2) = ω * t := by ring
  have hc0 := Real.cos_two_mul (ω * t / 2)
  rw [h2] at hc0
  have hs0 := Real.sin_two_mul (ω * t / 2)
  rw [h2] at hs0
  ring_nf at hpy hc0 hs0
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [rotFrame, σ_x, σ_y, σ_z, Matrix.mul_apply, Fin.sum_univ_two, Matrix.one_apply,
      Matrix.conjTranspose_apply, Complex.conj_ofReal, hc0, hs0,
      -Complex.ofReal_pow, -Complex.ofReal_cos, -Complex.ofReal_sin, Complex.ext_iff] <;>
    ring_nf <;> refine ⟨by linarith [hpy], trivial⟩

/-- `R(t) σ_y R(t)† = sin(ωt)·σ_x + cos(ωt)·σ_y`. -/
theorem rotFrame_conj_sy (ω t : ℝ) :
    rotFrame ω t * σ_y * (rotFrame ω t)ᴴ
      = ((Real.sin (ω * t) : ℝ) : ℂ) • σ_x + ((Real.cos (ω * t) : ℝ) : ℂ) • σ_y := by
  have hpy := Real.sin_sq_add_cos_sq (ω * t / 2)
  have h2 : 2 * (ω * t / 2) = ω * t := by ring
  have hc0 := Real.cos_two_mul (ω * t / 2)
  rw [h2] at hc0
  have hs0 := Real.sin_two_mul (ω * t / 2)
  rw [h2] at hs0
  ring_nf at hpy hc0 hs0
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [rotFrame, σ_x, σ_y, σ_z, Matrix.mul_apply, Fin.sum_univ_two, Matrix.one_apply,
      Matrix.conjTranspose_apply, Complex.conj_ofReal, hc0, hs0,
      -Complex.ofReal_pow, -Complex.ofReal_cos, -Complex.ofReal_sin, Complex.ext_iff] <;>
    ring_nf <;> constructor <;> (first | trivial | linarith [hpy])

/-! ### 2.2 The exact split -/

/-- **The exact rotating-frame decomposition.** The interaction-picture generator splits,
as an EXACT algebraic identity (no approximation anywhere), into the time-independent
co-rotating generator plus the purely oscillatory counter-rotating remainder:

`H_I(t) = H_RWA + V(t)`.

The rotating-wave *approximation* is the act of discarding `V`; this theorem is what makes
that discard quantifiable rather than folklore. -/
theorem interactionHamiltonian_decomp (ω₀ ω Ω φ a b c d t : ℝ) :
    interactionHamiltonian ω₀ ω Ω φ a b c d t
      = rwaGenerator ω₀ ω Ω φ b c + counterRotating ω Ω φ a b c d t := by
  have e2 : 2 * ω * t + φ = 2 * (ω * t) + φ := by ring
  have hs2 : Real.sin (ω * t) ^ 2 = 1 - Real.cos (ω * t) ^ 2 := by
    nlinarith [Real.sin_sq_add_cos_sq (ω * t)]
  simp only [interactionHamiltonian, drivenHamiltonian, driveOp, rwaGenerator, counterRotating, e2,
    Matrix.mul_add, Matrix.add_mul, Matrix.mul_smul, Matrix.smul_mul,
    rotFrame_conj_one, rotFrame_conj_sx, rotFrame_conj_sy, rotFrame_conj_sz,
    Real.cos_add, Real.sin_add, Real.cos_two_mul, Real.sin_two_mul]
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [σ_x, σ_y, σ_z, Complex.ext_iff,
      -Complex.ofReal_cos, -Complex.ofReal_sin, -Complex.ofReal_pow] <;>
    ring_nf <;> constructor <;> (rw [hs2]; ring)

/-! ## 3. The Bloch–Siegert scale: a closed-form antiderivative for the remainder

This is where the `1/ω` comes from, and it is the whole reason the RWA remainder is small.
`counterRotating` is a trigonometric polynomial (frequencies `ω` and `2ω`), so it has an
ELEMENTARY antiderivative — no abstract integration-by-parts is required — and every term of
that antiderivative carries an explicit `1/ω` while being bounded *uniformly in `t`*.

Contrast: a naive Duhamel/Grönwall estimate consumes only `sup ‖V‖ = O(Ω)` and therefore yields
`O(Ω·T)`, which carries no `1/ω` and grows without bound in `T`. That estimate is true but is
NOT of Bloch–Siegert scale. -/

/-- The closed-form antiderivative of `counterRotating`, normalised to vanish at `t = 0`. -/
def bsAntiderivative (ω Ω φ a b c d : ℝ) (t : ℝ) : Matrix (Fin 2) (Fin 2) ℂ :=
  (((Ω / ω) * (Real.sin (ω * t + φ) - Real.sin φ) : ℝ) : ℂ) •
      ((a : ℂ) • (1 : Matrix (Fin 2) (Fin 2) ℂ) + (d : ℂ) • σ_z)
    + (((Ω / (4 * ω)) * (b * (Real.sin (2 * ω * t + φ) - Real.sin φ)
          - c * (Real.cos (2 * ω * t + φ) - Real.cos φ)) : ℝ) : ℂ) • σ_x
    + (((Ω / (4 * ω)) * (b * (Real.cos (2 * ω * t + φ) - Real.cos φ)
          + c * (Real.sin (2 * ω * t + φ) - Real.sin φ)) : ℝ) : ℂ) • σ_y

/-- The antiderivative is normalised: `S(0) = 0`. This is what makes the boundary term at `t = 0`
drop out of the integration-by-parts estimate. -/
theorem bsAntiderivative_zero (ω Ω φ a b c d : ℝ) :
    bsAntiderivative ω Ω φ a b c d 0 = 0 := by
  simp [bsAntiderivative]

/-- `bsAntiderivative` genuinely differentiates to `counterRotating` — this is what earns it the
name, and it is where the `1/ω` prefactors are consumed by the chain rule. -/
theorem bsAntiderivative_hasDerivAt (ω Ω φ a b c d : ℝ) (hω : ω ≠ 0) (t : ℝ) :
    HasDerivAt (bsAntiderivative ω Ω φ a b c d)
      (counterRotating ω Ω φ a b c d t) t := by
  have h1 : HasDerivAt (fun s : ℝ => Real.sin (ω * s + φ)) (Real.cos (ω * t + φ) * ω) t := by
    simpa using (((hasDerivAt_id t).const_mul ω).add_const φ).sin
  have h2 : HasDerivAt (fun s : ℝ => Real.sin (2 * ω * s + φ))
      (Real.cos (2 * ω * t + φ) * (2 * ω)) t := by
    simpa using (((hasDerivAt_id t).const_mul (2 * ω)).add_const φ).sin
  have h3 : HasDerivAt (fun s : ℝ => Real.cos (2 * ω * s + φ))
      (-Real.sin (2 * ω * t + φ) * (2 * ω)) t := by
    simpa using (((hasDerivAt_id t).const_mul (2 * ω)).add_const φ).cos
  -- The three scalar coefficient functions, with the `1/ω` consumed by the chain rule.
  have g1 : HasDerivAt (fun s : ℝ => (Ω / ω) * (Real.sin (ω * s + φ) - Real.sin φ))
      (Ω * Real.cos (ω * t + φ)) t := by
    have heq : Ω * Real.cos (ω * t + φ) = Ω / ω * (Real.cos (ω * t + φ) * ω) := by
      field_simp
    rw [heq]
    exact (h1.sub_const (Real.sin φ)).const_mul (Ω / ω)
  have g2 : HasDerivAt (fun s : ℝ => (Ω / (4 * ω)) * (b * (Real.sin (2 * ω * s + φ) - Real.sin φ)
        - c * (Real.cos (2 * ω * s + φ) - Real.cos φ)))
      (Ω / 2 * (b * Real.cos (2 * ω * t + φ) + c * Real.sin (2 * ω * t + φ))) t := by
    have heq : Ω / 2 * (b * Real.cos (2 * ω * t + φ) + c * Real.sin (2 * ω * t + φ))
        = Ω / (4 * ω) * (b * (Real.cos (2 * ω * t + φ) * (2 * ω))
          - c * (-Real.sin (2 * ω * t + φ) * (2 * ω))) := by
      field_simp
      ring
    rw [heq]
    exact (((h2.sub_const (Real.sin φ)).const_mul b).sub
      ((h3.sub_const (Real.cos φ)).const_mul c)).const_mul (Ω / (4 * ω))
  have g3 : HasDerivAt (fun s : ℝ => (Ω / (4 * ω)) * (b * (Real.cos (2 * ω * s + φ) - Real.cos φ)
        + c * (Real.sin (2 * ω * s + φ) - Real.sin φ)))
      (Ω / 2 * (-b * Real.sin (2 * ω * t + φ) + c * Real.cos (2 * ω * t + φ))) t := by
    have heq : Ω / 2 * (-b * Real.sin (2 * ω * t + φ) + c * Real.cos (2 * ω * t + φ))
        = Ω / (4 * ω) * (b * (-Real.sin (2 * ω * t + φ) * (2 * ω))
          + c * (Real.cos (2 * ω * t + φ) * (2 * ω))) := by
      field_simp
      ring
    rw [heq]
    exact (((h3.sub_const (Real.cos φ)).const_mul b).add
      ((h2.sub_const (Real.sin φ)).const_mul c)).const_mul (Ω / (4 * ω))
  -- Assemble: each summand is (scalar function) • (constant matrix). The pointwise sum
  -- `(f₁ + f₂) + f₃` is definitionally `bsAntiderivative`, so `exact` closes it directly.
  have hsum :=
    ((g1.ofReal_comp.smul_const ((a : ℂ) • (1 : Matrix (Fin 2) (Fin 2) ℂ) + (d : ℂ) • σ_z)).add
      (g2.ofReal_comp.smul_const σ_x)).add (g3.ofReal_comp.smul_const σ_y)
  exact hsum

end

end SKEFTHawking.Control
