/-
Phase 6EE Wave 1: Rotating-wave reduction with an explicit remainder.

The rotating-wave *approximation* is folklore; the deliverable here is the
*inequality*. The exact interaction-picture generator is split, as an exact
algebraic identity, into a time-independent co-rotating part (`rwaGenerator`)
and a purely oscillatory counter-rotating remainder (`counterRotating`). The
remainder admits a CLOSED-FORM antiderivative (`bsAntiderivative`) whose norm is
bounded by `C · Ω / ω` — the Bloch-Siegert scale. That bound is the whole content:
a naive Duhamel estimate on the same system yields only `2Ω·ℓ¹·T` (`integral_counterRotating_naive_bound`), which
grows without bound in `T` and carries no `1/ω`, and is therefore NOT of
Bloch-Siegert scale.

No theorem in this file asserts the co-rotating reduction as an equality.

Conventions (all explicit, none implicit):
  * Lab-frame Hamiltonian  `H(t) = (ω₀/2)·σ_z + Ω·cos(ω t + φ)·O`.
  * Drive operator `O` is Hermitian, given in the Pauli basis by REAL
    coefficients `a b c d` (`driveOp`, Hermitian by `driveOp_isHermitian`). Every
    Hermitian 2×2 complex matrix arises this way — `exists_driveOp_of_isHermitian`,
    a theorem rather than a scope assertion — so no generality is lost for a
    physical drive.
  * Rotating frame at the drive frequency `ω`, generated by `+i(ω t/2)σ_z`
    (`rotFrame`), with detuning `Δ = ω₀ - ω`.
  * Matrix norm: the `ℓ^∞` operator norm (max row sum), matching the
    convention of `MatrixBCHCubic` and the rest of the matrix-analysis corpus.

References:
  Bloch & Siegert, Phys. Rev. 57, 522 (1940) — the counter-rotating shift.
-/

import Mathlib
import SKEFTHawking.PauliMatrices
import SKEFTHawking.Control.BanachAveraging

set_option autoImplicit false

namespace SKEFTHawking.Control

open Matrix Complex

attribute [local instance] Matrix.linftyOpNormedAddCommGroup
  Matrix.linftyOpNormedRing
  Matrix.linftyOpNormedAlgebra

noncomputable section

/-! ## 1. The driven two-level Hamiltonian -/

/-- A Hermitian drive operator in the Pauli basis, `O = a·1 + b·σ_x + c·σ_y + d·σ_z`
with `a b c d : ℝ`.

Hermitian by `driveOp_conjTranspose`. Every Hermitian `2×2` complex matrix has exactly this form
(`exists_driveOp_of_isHermitian`), so restricting to real coefficients loses no generality for a
physical (Hermitian) drive. Both claims are theorems below; neither is asserted here only. -/
def driveOp (a b c d : ℝ) : Matrix (Fin 2) (Fin 2) ℂ :=
  (a : ℂ) • (1 : Matrix (Fin 2) (Fin 2) ℂ) + (b : ℂ) • σ_x + (c : ℂ) • σ_y + (d : ℂ) • σ_z

/-- The lab-frame driven two-level Hamiltonian
`H(t) = (ω₀/2)·σ_z + Ω·cos(ω t + φ)·O`. -/
def drivenHamiltonian (ω₀ ω Ω φ a b c d : ℝ) (t : ℝ) : Matrix (Fin 2) (Fin 2) ℂ :=
  ((ω₀ / 2 : ℝ) : ℂ) • σ_z + ((Ω * Real.cos (ω * t + φ) : ℝ) : ℂ) • driveOp a b c d

/-- The rotating frame at the drive frequency, `R(t) = cos(ωt/2)·1 + i·sin(ωt/2)·σ_z`.

This is the closed form of `exp(i(ω t/2)·σ_z)`. Three theorems below pin it as that exponential,
and it takes all three: `rotFrame_ode` (it solves the defining ODE `R' = i(ω/2)σ_z·R`),
`rotFrame_zero` (`R(0) = 1`), and `rotFrame_unique` (no other solution of that initial-value
problem exists). `rotFrame_hasDerivAt` supplies the raw derivative that `rotFrame_ode` then
identifies; on its own it pins nothing. So the closed form is a definition of convenience, not an
additional assumption. -/
def rotFrame (ω : ℝ) (t : ℝ) : Matrix (Fin 2) (Fin 2) ℂ :=
  ((Real.cos (ω * t / 2) : ℝ) : ℂ) • (1 : Matrix (Fin 2) (Fin 2) ℂ)
    + (Complex.I * ((Real.sin (ω * t / 2) : ℝ) : ℂ)) • σ_z

/-! ## 2. The exact split: co-rotating generator + counter-rotating remainder -/

/-- The co-rotating (rotating-wave) generator — time-INDEPENDENT:
`H_RWA = (Δ/2)·σ_z + (Ω/2)·[(b cos φ - c sin φ)·σ_x + (b sin φ + c cos φ)·σ_y]`,
with detuning `Δ = ω₀ - ω`.

Note the longitudinal drive components `a` and `d` are absent: a drive along `1` or
`σ_z` is purely counter-rotating and averages away entirely. -/
def rwaGenerator (ω₀ ω Ω φ b c : ℝ) : Matrix (Fin 2) (Fin 2) ℂ :=
  (((ω₀ - ω) / 2 : ℝ) : ℂ) • σ_z
    + ((Ω / 2 * (b * Real.cos φ - c * Real.sin φ) : ℝ) : ℂ) • σ_x
    + ((Ω / 2 * (b * Real.sin φ + c * Real.cos φ) : ℝ) : ℂ) • σ_y

/-- The counter-rotating remainder: the longitudinal piece oscillating at `ω`, plus
the transverse piece oscillating at `2ω`. Its time average vanishes — proved as
`integral_counterRotating_period` (the integral over one drive period `2π/ω` is exactly `0`), not
asserted — and that is what lets `bsAntiderivative` be bounded uniformly in `t`
(`bsAntiderivative_norm_le`) instead of growing linearly. -/
def counterRotating (ω Ω φ a b c d : ℝ) (t : ℝ) : Matrix (Fin 2) (Fin 2) ℂ :=
  ((Ω * Real.cos (ω * t + φ) : ℝ) : ℂ) •
      ((a : ℂ) • (1 : Matrix (Fin 2) (Fin 2) ℂ) + (d : ℂ) • σ_z)
    + ((Ω / 2 * (b * Real.cos (2 * ω * t + φ) + c * Real.sin (2 * ω * t + φ)) : ℝ) : ℂ) • σ_x
    + ((Ω / 2 * (-b * Real.sin (2 * ω * t + φ) + c * Real.cos (2 * ω * t + φ)) : ℝ) : ℂ) • σ_y

/-- The exact interaction-picture generator,
`H_I(t) = R(t) H(t) R(t)† - (ω/2)·σ_z`. -/
def interactionHamiltonian (ω₀ ω Ω φ a b c d : ℝ) (t : ℝ) : Matrix (Fin 2) (Fin 2) ℂ :=
  rotFrame ω t * drivenHamiltonian ω₀ ω Ω φ a b c d t * (rotFrame ω t)ᴴ
    - ((ω / 2 : ℝ) : ℂ) • σ_z

/-! ### 2.0 The closed form really is the exponential

`rotFrame` is *defined* by a closed form rather than as `exp(i(ωt/2)σ_z)`. Three theorems in this
section are what make that a definition of convenience rather than an extra modelling assumption:
`rotFrame_zero` (`R(0) = 1`), `rotFrame_ode` (the closed form satisfies the defining ODE
`R' = i(ω/2)σ_z · R`), and `rotFrame_unique` (that initial-value problem has no other solution).
The first two alone would leave "pinned uniquely" as prose; the third is what discharges it. -/

/-- `R(0) = 1`. -/
theorem rotFrame_zero (ω : ℝ) : rotFrame ω 0 = 1 := by
  unfold rotFrame
  simp

/-- The rotating frame differentiates as `exp(i(ω t/2)σ_z)` must. -/
theorem rotFrame_hasDerivAt (ω t : ℝ) :
    HasDerivAt (rotFrame ω)
      (((-(ω / 2) * Real.sin (ω * t / 2) : ℝ) : ℂ) • (1 : Matrix (Fin 2) (Fin 2) ℂ)
        + (Complex.I * (((ω / 2) * Real.cos (ω * t / 2) : ℝ) : ℂ)) • σ_z) t := by
  have hc : HasDerivAt (fun s : ℝ => Real.cos (ω * s / 2))
      (-(ω / 2) * Real.sin (ω * t / 2)) t := by
    have h := (((hasDerivAt_id t).const_mul ω).div_const 2).cos
    simpa [mul_comm, mul_assoc, mul_left_comm] using h
  have hs : HasDerivAt (fun s : ℝ => Real.sin (ω * s / 2))
      ((ω / 2) * Real.cos (ω * t / 2)) t := by
    have h := (((hasDerivAt_id t).const_mul ω).div_const 2).sin
    simpa [mul_comm, mul_assoc, mul_left_comm] using h
  have h1 := hc.ofReal_comp.smul_const (1 : Matrix (Fin 2) (Fin 2) ℂ)
  have h2 := (hs.ofReal_comp.const_mul Complex.I).smul_const σ_z
  exact h1.add h2

/-- **The defining ODE.** `R'(t) = i(ω/2)·σ_z · R(t)` — so `rotFrame` is the unique solution with
`R(0) = 1`, i.e. genuinely `exp(i(ωt/2)σ_z)`. -/
theorem rotFrame_ode (ω t : ℝ) :
    ((-(ω / 2) * Real.sin (ω * t / 2) : ℝ) : ℂ) • (1 : Matrix (Fin 2) (Fin 2) ℂ)
        + (Complex.I * (((ω / 2) * Real.cos (ω * t / 2) : ℝ) : ℂ)) • σ_z
      = (Complex.I * ((ω / 2 : ℝ) : ℂ)) • σ_z * rotFrame ω t := by
  unfold rotFrame
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [σ_z, Matrix.mul_apply, Fin.sum_univ_two, Matrix.one_apply, Complex.ext_iff,
      -Complex.ofReal_cos, -Complex.ofReal_sin]

/-- Left multiplication by a fixed matrix is Lipschitz — the vector field of a linear ODE. -/
theorem lipschitzWith_const_mul (A : Matrix (Fin 2) (Fin 2) ℂ) :
    LipschitzWith ‖A‖₊ (fun X : Matrix (Fin 2) (Fin 2) ℂ => A * X) := by
  apply LipschitzWith.of_dist_le_mul
  intro x y
  simp only [dist_eq_norm, ← mul_sub]
  exact norm_mul_le _ _

/-- **Uniqueness — `rotFrame` really is THE solution, not merely A solution.** Any function
solving the same ODE with the same initial condition agrees with `rotFrame` on `[0, T]`. Together
with `rotFrame_ode` and `rotFrame_zero` this discharges the claim that the closed form *is*
`exp(i(ωt/2)σ_z)`: the characterization is a theorem here, not a docstring assertion. -/
theorem rotFrame_unique (ω T : ℝ) (F : ℝ → Matrix (Fin 2) (Fin 2) ℂ)
    (hFc : ContinuousOn F (Set.Icc 0 T))
    (hF' : ∀ t ∈ Set.Ico (0 : ℝ) T,
      HasDerivWithinAt F ((Complex.I * ((ω / 2 : ℝ) : ℂ)) • σ_z * F t) (Set.Ici t) t)
    (hF0 : F 0 = 1) :
    Set.EqOn F (rotFrame ω) (Set.Icc 0 T) := by
  have hode : ∀ t : ℝ, HasDerivAt (rotFrame ω)
      ((Complex.I * ((ω / 2 : ℝ) : ℂ)) • σ_z * rotFrame ω t) t := fun t =>
    (rotFrame_ode ω t) ▸ rotFrame_hasDerivAt ω t
  exact ODE_solution_unique
    (v := fun _ X => (Complex.I * ((ω / 2 : ℝ) : ℂ)) • σ_z * X)
    (fun _ => lipschitzWith_const_mul _) hFc hF'
    (fun t _ => (hode t).continuousAt.continuousWithinAt)
    (fun t _ => (hode t).hasDerivWithinAt)
    (by rw [hF0, rotFrame_zero])

/-! ### 2.1 The rotating frame is unitary and acts on the Pauli basis as a rotation -/

-- Entry-level computation idiom shared by every conjugation lemma below: expand the
-- `2×2` product, then discharge the resulting real-trigonometric identity.
-- `Complex.ofReal_cos`/`ofReal_sin` are suppressed so that `↑(Real.cos x)` is not
-- rewritten into `Complex.cos ↑x`, which would put the goal outside `ring_nf`'s reach.

/-- `R(t)` is unitary. -/
theorem rotFrame_mul_conjTranspose (ω t : ℝ) :
    rotFrame ω t * (rotFrame ω t)ᴴ = 1 := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [rotFrame, σ_z, Matrix.mul_apply, Fin.sum_univ_two, Matrix.one_apply,
      Matrix.conjTranspose_apply, Complex.conj_ofReal,
      -Complex.ofReal_cos, -Complex.ofReal_sin, Complex.ext_iff] <;>
    ring_nf <;> simp

/-- `R(t)` is unitary in the other order too — needed to cancel `Rᴴ·R` inside the
interaction-picture conjugation. -/
theorem rotFrame_conjTranspose_mul (ω t : ℝ) :
    (rotFrame ω t)ᴴ * rotFrame ω t = 1 := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [rotFrame, σ_z, Matrix.mul_apply, Fin.sum_univ_two, Matrix.one_apply,
      Matrix.conjTranspose_apply, Complex.conj_ofReal,
      -Complex.ofReal_cos, -Complex.ofReal_sin, Complex.ext_iff] <;>
    ring_nf <;> simp

/-- `σ_y` is Hermitian. Proved inline because `PauliMatrices.lean` carries only `σ_x`/`σ_z`
(the `σ_y` entries `±i` need a small ring step). -/
theorem sigmaY_conjTranspose : σ_yᴴ = σ_y := by
  ext i j
  fin_cases i <;> fin_cases j <;> simp [σ_y, Matrix.conjTranspose_apply]

/-- **The drive operator is Hermitian** — the claim its docstring makes, now a declaration. -/
theorem driveOp_conjTranspose (a b c d : ℝ) : (driveOp a b c d)ᴴ = driveOp a b c d := by
  unfold driveOp
  simp [Matrix.conjTranspose_add, Matrix.conjTranspose_smul, σ_x_hermitian, σ_z_hermitian,
    sigmaY_conjTranspose]

/-- **…and every Hermitian 2×2 matrix has that form**, so restricting to real coefficients loses
no generality — the module's scope claim, previously prose only. -/
theorem exists_driveOp_of_isHermitian (M : Matrix (Fin 2) (Fin 2) ℂ) (hM : Mᴴ = M) :
    ∃ a b c d : ℝ, driveOp a b c d = M := by
  refine ⟨((M 0 0).re + (M 1 1).re) / 2, (M 0 1).re, -(M 0 1).im,
    ((M 0 0).re - (M 1 1).re) / 2, ?_⟩
  have h00 := congrFun (congrFun hM 0) 0
  have h11 := congrFun (congrFun hM 1) 1
  have h10 := congrFun (congrFun hM 1) 0
  simp only [Matrix.conjTranspose_apply, Complex.ext_iff, Complex.star_def,
    Complex.conj_re, Complex.conj_im] at h00 h11 h10
  unfold driveOp
  ext i j
  fin_cases i <;> fin_cases j <;>
      simp [σ_x, σ_y, σ_z, Complex.ext_iff] <;>
      constructor <;>
    linarith [h00.1, h00.2, h11.1, h11.2, h10.1, h10.2]

/-- **The drive operator is Hermitian** in Mathlib's bundled form. -/
theorem driveOp_isHermitian (a b c d : ℝ) : (driveOp a b c d).IsHermitian :=
  driveOp_conjTranspose a b c d

/-- Conjugating `σ_z` by the rotating frame leaves it fixed: the frame is generated by `σ_z`. -/
theorem rotFrame_conj_sz (ω t : ℝ) :
    rotFrame ω t * σ_z * (rotFrame ω t)ᴴ = σ_z := by
  have hpy := Real.sin_sq_add_cos_sq (ω * t / 2)
  ring_nf at hpy
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [rotFrame, σ_z, Matrix.mul_apply, Fin.sum_univ_two, Matrix.one_apply,
      Matrix.conjTranspose_apply, Complex.conj_ofReal,
      -Complex.ofReal_cos, -Complex.ofReal_sin, Complex.ext_iff] <;>
    ring_nf <;> refine ⟨by linarith [hpy], trivial⟩

/-- Conjugating the identity leaves it fixed (unitarity, restated for the drive expansion). -/
theorem rotFrame_conj_one (ω t : ℝ) :
    rotFrame ω t * 1 * (rotFrame ω t)ᴴ = 1 := by
  rw [mul_one]
  exact rotFrame_mul_conjTranspose ω t

/-- `R(t) σ_x R(t)† = cos(ωt)·σ_x - sin(ωt)·σ_y`. -/
theorem rotFrame_conj_sx (ω t : ℝ) :
    rotFrame ω t * σ_x * (rotFrame ω t)ᴴ
      = ((Real.cos (ω * t) : ℝ) : ℂ) • σ_x - ((Real.sin (ω * t) : ℝ) : ℂ) • σ_y := by
  have hpy := Real.sin_sq_add_cos_sq (ω * t / 2)
  have h2 : 2 * (ω * t / 2) = ω * t := by ring
  have hc0 := Real.cos_two_mul (ω * t / 2)
  rw [h2] at hc0
  have hs0 := Real.sin_two_mul (ω * t / 2)
  rw [h2] at hs0
  ring_nf at hpy hc0 hs0
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [rotFrame, σ_x, σ_y, σ_z, Matrix.mul_apply, Fin.sum_univ_two, Matrix.one_apply,
      Matrix.conjTranspose_apply, Complex.conj_ofReal, hc0, hs0,
      -Complex.ofReal_pow, -Complex.ofReal_cos, -Complex.ofReal_sin, Complex.ext_iff] <;>
    ring_nf <;> refine ⟨by linarith [hpy], trivial⟩

/-- `R(t) σ_y R(t)† = sin(ωt)·σ_x + cos(ωt)·σ_y`. -/
theorem rotFrame_conj_sy (ω t : ℝ) :
    rotFrame ω t * σ_y * (rotFrame ω t)ᴴ
      = ((Real.sin (ω * t) : ℝ) : ℂ) • σ_x + ((Real.cos (ω * t) : ℝ) : ℂ) • σ_y := by
  have hpy := Real.sin_sq_add_cos_sq (ω * t / 2)
  have h2 : 2 * (ω * t / 2) = ω * t := by ring
  have hc0 := Real.cos_two_mul (ω * t / 2)
  rw [h2] at hc0
  have hs0 := Real.sin_two_mul (ω * t / 2)
  rw [h2] at hs0
  ring_nf at hpy hc0 hs0
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [rotFrame, σ_x, σ_y, σ_z, Matrix.mul_apply, Fin.sum_univ_two, Matrix.one_apply,
      Matrix.conjTranspose_apply, Complex.conj_ofReal, hc0, hs0,
      -Complex.ofReal_pow, -Complex.ofReal_cos, -Complex.ofReal_sin, Complex.ext_iff] <;>
    ring_nf <;> constructor <;> (first | trivial | linarith [hpy])

/-! ### 2.2 The exact split -/

/-- **`interactionHamiltonian` really generates the interaction-picture dynamics.**

`interactionHamiltonian` is *defined* by the frame-change expression `R H Rᴴ − (ω/2)σ_z`. On its own
that is an algebraic definition: nothing in the definition itself forces the subtraction to be
`−(ω/2)σ_z` rather than `+(ω/2)σ_z` or `−(ω₀/2)σ_z`.

`interactionHamiltonian_decomp` does constrain it — its `σ_z` coefficient is `(ω₀−ω)/2`, which
either alternative would break — but only RELATIVE to the definition of `rwaGenerator`, which is
itself a choice made to match. Two definitions edited together leave the decomposition intact and
the physics wrong, so the decomposition alone cannot pin the frame.

This theorem is what pins it against something external to both definitions: if `U` solves the
LAB-frame Schrödinger equation
`U' = −i·H(t)·U`, then `R·U` solves `(R·U)' = −i·H_I(t)·(R·U)`. The `−(ω/2)σ_z` is exactly the
term that makes this true, so the definition is now forced by a declaration rather than by
prose. -/
theorem interactionPicture_ode (ω₀ ω Ω φ a b c d : ℝ) (U : ℝ → Matrix (Fin 2) (Fin 2) ℂ)
    (hU : ∀ s, HasDerivAt U
      ((-Complex.I) • (drivenHamiltonian ω₀ ω Ω φ a b c d s * U s)) s) (t : ℝ) :
    HasDerivAt (fun s => rotFrame ω s * U s)
      ((-Complex.I) • (interactionHamiltonian ω₀ ω Ω φ a b c d t * (rotFrame ω t * U t))) t := by
  have hprod := ((rotFrame_hasDerivAt ω t).mul (hU t))
  rw [rotFrame_ode ω t] at hprod
  have hcancel : rotFrame ω t * drivenHamiltonian ω₀ ω Ω φ a b c d t * (rotFrame ω t)ᴴ
      * (rotFrame ω t * U t)
      = rotFrame ω t * (drivenHamiltonian ω₀ ω Ω φ a b c d t * U t) := by
    rw [Matrix.mul_assoc, Matrix.mul_assoc, ← Matrix.mul_assoc ((rotFrame ω t)ᴴ),
      rotFrame_conjTranspose_mul, Matrix.one_mul]
  have hval :
      (Complex.I * ((ω / 2 : ℝ) : ℂ)) • σ_z * rotFrame ω t * U t
        + rotFrame ω t * ((-Complex.I) • (drivenHamiltonian ω₀ ω Ω φ a b c d t * U t))
      = (-Complex.I) • (interactionHamiltonian ω₀ ω Ω φ a b c d t * (rotFrame ω t * U t)) := by
    unfold interactionHamiltonian
    rw [sub_mul, smul_sub, hcancel, Matrix.mul_smul, Matrix.smul_mul, Matrix.smul_mul,
      Matrix.smul_mul, smul_smul, Matrix.mul_assoc]
    module
  rw [← hval]
  exact hprod

/-- **The exact rotating-frame decomposition.** The interaction-picture generator splits,
as an EXACT algebraic identity (no approximation anywhere), into the time-independent
co-rotating generator plus the purely oscillatory counter-rotating remainder:

`H_I(t) = H_RWA + V(t)`.

The rotating-wave *approximation* is the act of discarding `V`; this theorem is what makes
that discard quantifiable rather than folklore. -/
theorem interactionHamiltonian_decomp (ω₀ ω Ω φ a b c d t : ℝ) :
    interactionHamiltonian ω₀ ω Ω φ a b c d t
      = rwaGenerator ω₀ ω Ω φ b c + counterRotating ω Ω φ a b c d t := by
  have e2 : 2 * ω * t + φ = 2 * (ω * t) + φ := by ring
  have hs2 : Real.sin (ω * t) ^ 2 = 1 - Real.cos (ω * t) ^ 2 := by
    nlinarith [Real.sin_sq_add_cos_sq (ω * t)]
  simp only [interactionHamiltonian, drivenHamiltonian, driveOp, rwaGenerator, counterRotating, e2,
    Matrix.mul_add, Matrix.add_mul, Matrix.mul_smul, Matrix.smul_mul,
    rotFrame_conj_one, rotFrame_conj_sx, rotFrame_conj_sy, rotFrame_conj_sz,
    Real.cos_add, Real.sin_add, Real.cos_two_mul, Real.sin_two_mul]
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [σ_x, σ_y, σ_z, Complex.ext_iff,
      -Complex.ofReal_cos, -Complex.ofReal_sin, -Complex.ofReal_pow] <;>
    ring_nf <;> constructor <;> (rw [hs2]; ring)

/-! ## 3. The Bloch–Siegert scale: a closed-form antiderivative for the remainder

This is where the `1/ω` comes from, and it is the whole reason the RWA remainder is small.
`counterRotating` is a trigonometric polynomial (frequencies `ω` and `2ω`), so it has an
ELEMENTARY antiderivative — no abstract integration-by-parts is required — and every term of
that antiderivative carries an explicit `1/ω` while being bounded *uniformly in `t`*.

Contrast: a naive Duhamel estimate consumes only `sup ‖V‖ ≤ 2Ω·ℓ¹` (`norm_counterRotating_le`)
and therefore yields
`O(Ω·T)`, which carries no `1/ω` and grows without bound in `T`. That estimate is true but is
NOT of Bloch–Siegert scale. -/

/-- The closed-form antiderivative of `counterRotating`, normalised to vanish at `t = 0`. -/
def bsAntiderivative (ω Ω φ a b c d : ℝ) (t : ℝ) : Matrix (Fin 2) (Fin 2) ℂ :=
  (((Ω / ω) * (Real.sin (ω * t + φ) - Real.sin φ) : ℝ) : ℂ) •
      ((a : ℂ) • (1 : Matrix (Fin 2) (Fin 2) ℂ) + (d : ℂ) • σ_z)
    + (((Ω / (4 * ω)) * (b * (Real.sin (2 * ω * t + φ) - Real.sin φ)
          - c * (Real.cos (2 * ω * t + φ) - Real.cos φ)) : ℝ) : ℂ) • σ_x
    + (((Ω / (4 * ω)) * (b * (Real.cos (2 * ω * t + φ) - Real.cos φ)
          + c * (Real.sin (2 * ω * t + φ) - Real.sin φ)) : ℝ) : ℂ) • σ_y

/-- The antiderivative is normalised: `S(0) = 0`. This is what makes the boundary term at `t = 0`
drop out of the integration-by-parts estimate. -/
theorem bsAntiderivative_zero (ω Ω φ a b c d : ℝ) :
    bsAntiderivative ω Ω φ a b c d 0 = 0 := by
  simp [bsAntiderivative]

/-- `bsAntiderivative` genuinely differentiates to `counterRotating` — this is what earns it the
name, and it is where the `1/ω` prefactors are consumed by the chain rule. -/
theorem bsAntiderivative_hasDerivAt (ω Ω φ a b c d : ℝ) (hω : ω ≠ 0) (t : ℝ) :
    HasDerivAt (bsAntiderivative ω Ω φ a b c d)
      (counterRotating ω Ω φ a b c d t) t := by
  have h1 : HasDerivAt (fun s : ℝ => Real.sin (ω * s + φ)) (Real.cos (ω * t + φ) * ω) t := by
    simpa using (((hasDerivAt_id t).const_mul ω).add_const φ).sin
  have h2 : HasDerivAt (fun s : ℝ => Real.sin (2 * ω * s + φ))
      (Real.cos (2 * ω * t + φ) * (2 * ω)) t := by
    simpa using (((hasDerivAt_id t).const_mul (2 * ω)).add_const φ).sin
  have h3 : HasDerivAt (fun s : ℝ => Real.cos (2 * ω * s + φ))
      (-Real.sin (2 * ω * t + φ) * (2 * ω)) t := by
    simpa using (((hasDerivAt_id t).const_mul (2 * ω)).add_const φ).cos
  -- The three scalar coefficient functions, with the `1/ω` consumed by the chain rule.
  have g1 : HasDerivAt (fun s : ℝ => (Ω / ω) * (Real.sin (ω * s + φ) - Real.sin φ))
      (Ω * Real.cos (ω * t + φ)) t := by
    have heq : Ω * Real.cos (ω * t + φ) = Ω / ω * (Real.cos (ω * t + φ) * ω) := by
      field_simp
    rw [heq]
    exact (h1.sub_const (Real.sin φ)).const_mul (Ω / ω)
  have g2 : HasDerivAt (fun s : ℝ => (Ω / (4 * ω)) * (b * (Real.sin (2 * ω * s + φ) - Real.sin φ)
        - c * (Real.cos (2 * ω * s + φ) - Real.cos φ)))
      (Ω / 2 * (b * Real.cos (2 * ω * t + φ) + c * Real.sin (2 * ω * t + φ))) t := by
    have heq : Ω / 2 * (b * Real.cos (2 * ω * t + φ) + c * Real.sin (2 * ω * t + φ))
        = Ω / (4 * ω) * (b * (Real.cos (2 * ω * t + φ) * (2 * ω))
          - c * (-Real.sin (2 * ω * t + φ) * (2 * ω))) := by
      field_simp
      ring
    rw [heq]
    exact (((h2.sub_const (Real.sin φ)).const_mul b).sub
      ((h3.sub_const (Real.cos φ)).const_mul c)).const_mul (Ω / (4 * ω))
  have g3 : HasDerivAt (fun s : ℝ => (Ω / (4 * ω)) * (b * (Real.cos (2 * ω * s + φ) - Real.cos φ)
        + c * (Real.sin (2 * ω * s + φ) - Real.sin φ)))
      (Ω / 2 * (-b * Real.sin (2 * ω * t + φ) + c * Real.cos (2 * ω * t + φ))) t := by
    have heq : Ω / 2 * (-b * Real.sin (2 * ω * t + φ) + c * Real.cos (2 * ω * t + φ))
        = Ω / (4 * ω) * (b * (-Real.sin (2 * ω * t + φ) * (2 * ω))
          + c * (Real.cos (2 * ω * t + φ) * (2 * ω))) := by
      field_simp
      ring
    rw [heq]
    exact (((h3.sub_const (Real.cos φ)).const_mul b).add
      ((h2.sub_const (Real.sin φ)).const_mul c)).const_mul (Ω / (4 * ω))
  -- Assemble: each summand is (scalar function) • (constant matrix). The pointwise sum
  -- `(f₁ + f₂) + f₃` is definitionally `bsAntiderivative`, so `exact` closes it directly.
  have hsum :=
    ((g1.ofReal_comp.smul_const ((a : ℂ) • (1 : Matrix (Fin 2) (Fin 2) ℂ) + (d : ℂ) • σ_z)).add
      (g2.ofReal_comp.smul_const σ_x)).add (g3.ofReal_comp.smul_const σ_y)
  exact hsum

/-! ### 3.1 Pauli operator norms (ℓ^∞ operator norm = max row sum) -/

lemma linftyOpNorm_sigmaX_le_one : ‖σ_x‖ ≤ 1 := by
  rw [Matrix.linfty_opNorm_def]; simp [σ_x, Fin.sum_univ_two]

lemma linftyOpNorm_sigmaY_le_one : ‖σ_y‖ ≤ 1 := by
  rw [Matrix.linfty_opNorm_def]; simp [σ_y, Fin.sum_univ_two]

lemma linftyOpNorm_sigmaZ_le_one : ‖σ_z‖ ≤ 1 := by
  rw [Matrix.linfty_opNorm_def]; simp [σ_z, Fin.sum_univ_two]

lemma linftyOpNorm_one_le_one : ‖(1 : Matrix (Fin 2) (Fin 2) ℂ)‖ ≤ 1 := by
  rw [Matrix.linfty_opNorm_def]; simp [Matrix.one_apply, Fin.sum_univ_two]

/-! ### 3.15 The naive Duhamel bound — the alternative, shipped so the contrast is checkable

The module header and the roadmap justify the whole route by contrast with "a naive Duhamel
estimate". A counterfactual with no declaration behind it cannot be checked, so it is proved here.
Bounding the integrated remainder by the sup of its integrand gives a constant times `Ω·T`:
**linear in `T`, and with no `1/ω` anywhere**. Compare `integral_counterRotating_norm_le` below,
which is `2(Ω/ω)·ℓ¹` *uniformly in `T`*. Both sides of the comparison are now theorems. -/

/-- Pointwise bound on the counter-rotating remainder: `‖V(t)‖ ≤ 2Ω·ℓ¹`, with no `1/ω`. -/
theorem norm_counterRotating_le (ω Ω φ a b c d t : ℝ) (hΩ : 0 ≤ Ω) :
    ‖counterRotating ω Ω φ a b c d t‖ ≤ 2 * Ω * (|a| + |b| + |c| + |d|) := by
  have hsmul : ∀ (r : ℝ) (M : Matrix (Fin 2) (Fin 2) ℂ), ‖((r : ℝ) : ℂ) • M‖ = |r| * ‖M‖ := by
    intro r M; rw [norm_smul]; simp
  have h1 := linftyOpNorm_one_le_one
  have hz := linftyOpNorm_sigmaZ_le_one
  have hx := linftyOpNorm_sigmaX_le_one
  have hy := linftyOpNorm_sigmaY_le_one
  have hM1 : ‖(a : ℂ) • (1 : Matrix (Fin 2) (Fin 2) ℂ) + (d : ℂ) • σ_z‖ ≤ |a| + |d| := by
    refine (norm_add_le _ _).trans ?_
    rw [hsmul a, hsmul d]
    nlinarith [abs_nonneg a, abs_nonneg d, norm_nonneg (1 : Matrix (Fin 2) (Fin 2) ℂ),
      norm_nonneg (σ_z : Matrix (Fin 2) (Fin 2) ℂ)]
  have hc1 : |Ω * Real.cos (ω * t + φ)| ≤ Ω := by
    rw [abs_mul, abs_of_nonneg hΩ]
    nlinarith [Real.abs_cos_le_one (ω * t + φ), abs_nonneg (Real.cos (ω * t + φ))]
  have hc2 : |Ω / 2 * (b * Real.cos (2 * ω * t + φ) + c * Real.sin (2 * ω * t + φ))|
      ≤ Ω / 2 * (|b| + |c|) := by
    rw [abs_mul, abs_of_nonneg (by positivity : (0:ℝ) ≤ Ω / 2)]
    have : |b * Real.cos (2 * ω * t + φ) + c * Real.sin (2 * ω * t + φ)| ≤ |b| + |c| := by
      refine (abs_add_le _ _).trans ?_
      rw [abs_mul, abs_mul]
      nlinarith [Real.abs_cos_le_one (2 * ω * t + φ), Real.abs_sin_le_one (2 * ω * t + φ),
        abs_nonneg b, abs_nonneg c, abs_nonneg (Real.cos (2 * ω * t + φ)),
        abs_nonneg (Real.sin (2 * ω * t + φ))]
    nlinarith [abs_nonneg (b * Real.cos (2 * ω * t + φ) + c * Real.sin (2 * ω * t + φ))]
  have hc3 : |Ω / 2 * (-b * Real.sin (2 * ω * t + φ) + c * Real.cos (2 * ω * t + φ))|
      ≤ Ω / 2 * (|b| + |c|) := by
    rw [abs_mul, abs_of_nonneg (by positivity : (0:ℝ) ≤ Ω / 2)]
    have : |-b * Real.sin (2 * ω * t + φ) + c * Real.cos (2 * ω * t + φ)| ≤ |b| + |c| := by
      refine (abs_add_le _ _).trans ?_
      rw [abs_mul, abs_mul, abs_neg]
      nlinarith [Real.abs_cos_le_one (2 * ω * t + φ), Real.abs_sin_le_one (2 * ω * t + φ),
        abs_nonneg b, abs_nonneg c, abs_nonneg (Real.cos (2 * ω * t + φ)),
        abs_nonneg (Real.sin (2 * ω * t + φ))]
    nlinarith [abs_nonneg (-b * Real.sin (2 * ω * t + φ) + c * Real.cos (2 * ω * t + φ))]
  unfold counterRotating
  have hb1 : ‖((Ω * Real.cos (ω * t + φ) : ℝ) : ℂ)
      • ((a : ℂ) • (1 : Matrix (Fin 2) (Fin 2) ℂ) + (d : ℂ) • σ_z)‖ ≤ Ω * (|a| + |d|) := by
    rw [hsmul]
    exact mul_le_mul hc1 hM1 (by positivity) hΩ
  have hb2 : ‖((Ω / 2 * (b * Real.cos (2 * ω * t + φ) + c * Real.sin (2 * ω * t + φ)) : ℝ) : ℂ)
      • σ_x‖ ≤ Ω / 2 * (|b| + |c|) := by
    rw [hsmul]
    nlinarith [abs_nonneg (Ω / 2 * (b * Real.cos (2 * ω * t + φ)
      + c * Real.sin (2 * ω * t + φ))), norm_nonneg (σ_x : Matrix (Fin 2) (Fin 2) ℂ)]
  have hb3 : ‖((Ω / 2 * (-b * Real.sin (2 * ω * t + φ) + c * Real.cos (2 * ω * t + φ)) : ℝ) : ℂ)
      • σ_y‖ ≤ Ω / 2 * (|b| + |c|) := by
    rw [hsmul]
    nlinarith [abs_nonneg (Ω / 2 * (-b * Real.sin (2 * ω * t + φ)
      + c * Real.cos (2 * ω * t + φ))), norm_nonneg (σ_y : Matrix (Fin 2) (Fin 2) ℂ)]
  have hstep1 := norm_add_le
    (((Ω * Real.cos (ω * t + φ) : ℝ) : ℂ)
        • ((a : ℂ) • (1 : Matrix (Fin 2) (Fin 2) ℂ) + (d : ℂ) • σ_z)
      + ((Ω / 2 * (b * Real.cos (2 * ω * t + φ) + c * Real.sin (2 * ω * t + φ)) : ℝ) : ℂ) • σ_x)
    (((Ω / 2 * (-b * Real.sin (2 * ω * t + φ) + c * Real.cos (2 * ω * t + φ)) : ℝ) : ℂ) • σ_y)
  have hstep2 := norm_add_le
    (((Ω * Real.cos (ω * t + φ) : ℝ) : ℂ)
      • ((a : ℂ) • (1 : Matrix (Fin 2) (Fin 2) ℂ) + (d : ℂ) • σ_z))
    (((Ω / 2 * (b * Real.cos (2 * ω * t + φ) + c * Real.sin (2 * ω * t + φ)) : ℝ) : ℂ) • σ_x)
  nlinarith [abs_nonneg a, abs_nonneg b, abs_nonneg c, abs_nonneg d]

/-- **The naive Duhamel bound.** `‖∫₀ᵀ V‖ ≤ 2Ω·ℓ¹·T` — linear in `T`, no `1/ω`. This is what the
route NOT taken delivers, and why taking it would have been a silent de-scope: it is not of
Bloch–Siegert scale at all. -/
theorem integral_counterRotating_naive_bound (ω Ω φ a b c d T : ℝ) (hΩ : 0 ≤ Ω) (hT : 0 ≤ T) :
    ‖∫ s in (0 : ℝ)..T, counterRotating ω Ω φ a b c d s‖
      ≤ 2 * Ω * (|a| + |b| + |c| + |d|) * T := by
  have h := intervalIntegral.norm_integral_le_of_norm_le_const
    (C := 2 * Ω * (|a| + |b| + |c| + |d|)) (a := (0 : ℝ)) (b := T)
    (f := fun s => counterRotating ω Ω φ a b c d s)
    (fun s _ => norm_counterRotating_le ω Ω φ a b c d s hΩ)
  simpa [abs_of_nonneg hT] using h

/-! ### 3.2 The Bloch–Siegert bound -/

private lemma abs_sin_sub_sin_le_two (x y : ℝ) : |Real.sin x - Real.sin y| ≤ 2 := by
  rw [abs_le]
  constructor <;>
    nlinarith [Real.neg_one_le_sin x, Real.sin_le_one x, Real.neg_one_le_sin y, Real.sin_le_one y]

private lemma abs_cos_sub_cos_le_two (x y : ℝ) : |Real.cos x - Real.cos y| ≤ 2 := by
  rw [abs_le]
  constructor <;>
    nlinarith [Real.neg_one_le_cos x, Real.cos_le_one x, Real.neg_one_le_cos y, Real.cos_le_one y]

/-- **The Bloch–Siegert bound — the load-bearing estimate of this module.**

The antiderivative of the counter-rotating remainder is bounded by an explicit constant times
`Ω/ω`, **uniformly in `t`**. The uniformity is the whole point: it is what separates this from a
naive Duhamel estimate, which bounds the same object only by `2Ω·ℓ¹·T`
(`integral_counterRotating_naive_bound`) — carrying no `1/ω` and growing without bound in `T`. Both
sides of that contrast are shipped theorems, so the justification for this route is checkable.

The constant `2` multiplies the drive's coefficient `ℓ¹` norm `|a|+|b|+|c|+|d|`, so the bound is
explicit in every parameter and degrades gracefully as the drive operator grows. -/
theorem bsAntiderivative_norm_le (ω Ω φ a b c d t : ℝ) (hω : 0 < ω) (hΩ : 0 ≤ Ω) :
    ‖bsAntiderivative ω Ω φ a b c d t‖ ≤ 2 * (Ω / ω) * (|a| + |b| + |c| + |d|) := by
  have hr : 0 ≤ Ω / ω := div_nonneg hΩ hω.le
  have hsmul : ∀ (r : ℝ) (M : Matrix (Fin 2) (Fin 2) ℂ), ‖((r : ℝ) : ℂ) • M‖ = |r| * ‖M‖ := by
    intro r M; rw [norm_smul]; simp
  -- Longitudinal block: ‖a•1 + d•σ_z‖ ≤ |a| + |d|.
  have hM1 : ‖(a : ℂ) • (1 : Matrix (Fin 2) (Fin 2) ℂ) + (d : ℂ) • σ_z‖ ≤ |a| + |d| := by
    refine (norm_add_le _ _).trans ?_
    rw [hsmul a, hsmul d]
    have := linftyOpNorm_one_le_one
    have := linftyOpNorm_sigmaZ_le_one
    nlinarith [abs_nonneg a, abs_nonneg d, norm_nonneg (1 : Matrix (Fin 2) (Fin 2) ℂ),
      norm_nonneg (σ_z : Matrix (Fin 2) (Fin 2) ℂ)]
  -- The three scalar coefficients.
  have hA1 : |(Ω / ω) * (Real.sin (ω * t + φ) - Real.sin φ)| ≤ 2 * (Ω / ω) := by
    rw [abs_mul, abs_of_nonneg hr]
    nlinarith [abs_sin_sub_sin_le_two (ω * t + φ) φ, abs_nonneg (Real.sin (ω * t + φ) - Real.sin φ)]
  have hA2 : |(Ω / (4 * ω)) * (b * (Real.sin (2 * ω * t + φ) - Real.sin φ)
      - c * (Real.cos (2 * ω * t + φ) - Real.cos φ))| ≤ (Ω / ω) * (|b| + |c|) / 2 := by
    rw [abs_mul]
    have h4 : |Ω / (4 * ω)| = (Ω / ω) / 4 := by
      rw [abs_of_nonneg (by positivity)]; field_simp
    rw [h4]
    have hin : |b * (Real.sin (2 * ω * t + φ) - Real.sin φ)
        - c * (Real.cos (2 * ω * t + φ) - Real.cos φ)| ≤ 2 * |b| + 2 * |c| := by
      refine (abs_sub _ _).trans ?_
      rw [abs_mul, abs_mul]
      nlinarith [abs_sin_sub_sin_le_two (2 * ω * t + φ) φ,
        abs_cos_sub_cos_le_two (2 * ω * t + φ) φ, abs_nonneg b, abs_nonneg c]
    nlinarith [hin, hr, abs_nonneg b, abs_nonneg c]
  have hA3 : |(Ω / (4 * ω)) * (b * (Real.cos (2 * ω * t + φ) - Real.cos φ)
      + c * (Real.sin (2 * ω * t + φ) - Real.sin φ))| ≤ (Ω / ω) * (|b| + |c|) / 2 := by
    rw [abs_mul]
    have h4 : |Ω / (4 * ω)| = (Ω / ω) / 4 := by
      rw [abs_of_nonneg (by positivity)]; field_simp
    rw [h4]
    have hin : |b * (Real.cos (2 * ω * t + φ) - Real.cos φ)
        + c * (Real.sin (2 * ω * t + φ) - Real.sin φ)| ≤ 2 * |b| + 2 * |c| := by
      refine (abs_add_le _ _).trans ?_
      rw [abs_mul, abs_mul]
      nlinarith [abs_sin_sub_sin_le_two (2 * ω * t + φ) φ,
        abs_cos_sub_cos_le_two (2 * ω * t + φ) φ, abs_nonneg b, abs_nonneg c]
    nlinarith [hin, hr, abs_nonneg b, abs_nonneg c]
  -- Assemble by the triangle inequality, bounding each product of two nonneg factors.
  rw [bsAntiderivative]
  refine ((norm_add_le _ _).trans (add_le_add (norm_add_le _ _) le_rfl)).trans ?_
  rw [hsmul, hsmul, hsmul]
  have hx := linftyOpNorm_sigmaX_le_one
  have hy := linftyOpNorm_sigmaY_le_one
  have t1 : |(Ω / ω) * (Real.sin (ω * t + φ) - Real.sin φ)|
      * ‖(a : ℂ) • (1 : Matrix (Fin 2) (Fin 2) ℂ) + (d : ℂ) • σ_z‖
      ≤ (2 * (Ω / ω)) * (|a| + |d|) :=
    mul_le_mul hA1 hM1 (norm_nonneg _) (by positivity)
  have t2 : |(Ω / (4 * ω)) * (b * (Real.sin (2 * ω * t + φ) - Real.sin φ)
        - c * (Real.cos (2 * ω * t + φ) - Real.cos φ))| * ‖σ_x‖
      ≤ ((Ω / ω) * (|b| + |c|) / 2) * 1 :=
    mul_le_mul hA2 hx (norm_nonneg _) (by positivity)
  have t3 : |(Ω / (4 * ω)) * (b * (Real.cos (2 * ω * t + φ) - Real.cos φ)
        + c * (Real.sin (2 * ω * t + φ) - Real.sin φ))| * ‖σ_y‖
      ≤ ((Ω / ω) * (|b| + |c|) / 2) * 1 :=
    mul_le_mul hA3 hy (norm_nonneg _) (by positivity)
  nlinarith [t1, t2, t3, hr, abs_nonneg a, abs_nonneg b, abs_nonneg c, abs_nonneg d,
    mul_nonneg hr (abs_nonneg b), mul_nonneg hr (abs_nonneg c)]

/-! ## 4. The time-integrated remainder

`bsAntiderivative` is not merely *a* bounded function: by the fundamental theorem of calculus it
IS the time integral of the counter-rotating remainder. That integral is the first-order term of
the exact-vs-reduced propagator discrepancy (the leading Dyson/Magnus term), so bounding it
uniformly in `T` is what makes the rotating-wave reduction quantitatively controlled. -/

lemma continuous_counterRotating (ω Ω φ a b c d : ℝ) :
    Continuous (counterRotating ω Ω φ a b c d) := by
  unfold counterRotating
  fun_prop

/-- FTC: the counter-rotating remainder integrates to its closed-form antiderivative. -/
theorem integral_counterRotating (ω Ω φ a b c d T : ℝ) (hω : ω ≠ 0) :
    (∫ s in (0 : ℝ)..T, counterRotating ω Ω φ a b c d s)
      = bsAntiderivative ω Ω φ a b c d T := by
  rw [intervalIntegral.integral_eq_sub_of_hasDerivAt
    (fun s _ => bsAntiderivative_hasDerivAt ω Ω φ a b c d hω s)
    ((continuous_counterRotating ω Ω φ a b c d).intervalIntegrable 0 T)]
  rw [bsAntiderivative_zero, sub_zero]

/-- **The counter-rotating remainder has zero time average.** Over one drive period `2π/ω` its
integral vanishes exactly.

This is the `counterRotating` docstring's "its time average vanishes" as a declaration rather than
as motivation, and it is the structural reason the antiderivative stays bounded: a mean-zero
periodic integrand has a periodic — hence bounded — antiderivative, whereas any nonzero mean would
force linear growth in `T` and destroy the uniform bound of
`integral_counterRotating_norm_le` below. -/
theorem integral_counterRotating_period (ω Ω φ a b c d : ℝ) (hω : ω ≠ 0) :
    (∫ s in (0 : ℝ)..(2 * Real.pi / ω), counterRotating ω Ω φ a b c d s) = 0 := by
  rw [integral_counterRotating ω Ω φ a b c d _ hω]
  unfold bsAntiderivative
  have h1 : ω * (2 * Real.pi / ω) + φ = φ + 2 * Real.pi := by field_simp; ring
  have h2 : 2 * ω * (2 * Real.pi / ω) + φ = φ + 2 * Real.pi + 2 * Real.pi := by field_simp; ring
  rw [h1, h2]
  simp

/-- **The integrated counter-rotating drive is Bloch–Siegert bounded, uniformly in `T`.**

This is the sharp contrast with the naive estimate. Bounding the integrand pointwise gives only
`∫₀ᵀ ‖V‖ = O(Ω·T)`, which grows without bound; the oscillation of `V` makes the *integral* stay
bounded by `O(Ω/ω)` no matter how long the drive runs. -/
theorem integral_counterRotating_norm_le (ω Ω φ a b c d T : ℝ) (hω : 0 < ω) (hΩ : 0 ≤ Ω) :
    ‖∫ s in (0 : ℝ)..T, counterRotating ω Ω φ a b c d s‖
      ≤ 2 * (Ω / ω) * (|a| + |b| + |c| + |d|) := by
  rw [integral_counterRotating ω Ω φ a b c d T hω.ne']
  exact bsAntiderivative_norm_le ω Ω φ a b c d T hω hΩ

/-! ### 4.1 Witnesses: where the reduction is controlled, and where it honestly is not

Both witnesses use a unit transverse drive (`b = 1`, others zero) and differ only in `ω/Ω`.
They are stated at every `t` and every `T`, so neither is an artefact of a lucky time. -/

/-- **Validity witness.** Far off resonance (`ω = 1000 Ω`) the integrated counter-rotating drive is
bounded by `2×10⁻³` for ALL `T` — the rotating-wave reduction is quantitatively controlled. -/
theorem integral_counterRotating_witness_valid (T : ℝ) :
    ‖∫ s in (0 : ℝ)..T, counterRotating 1000 1 0 0 1 0 0 s‖ ≤ 1 / 500 := by
  have h := integral_counterRotating_norm_le 1000 1 0 0 1 0 0 T (by norm_num) (by norm_num)
  have hb : (2 : ℝ) * (1 / 1000) * (|(0 : ℝ)| + |(1 : ℝ)| + |(0 : ℝ)| + |(0 : ℝ)|) ≤ 1 / 500 := by
    norm_num
  linarith

lemma linftyOpNorm_sigmaY_eq_one : ‖σ_y‖ = 1 := by
  apply le_antisymm linftyOpNorm_sigmaY_le_one
  rw [Matrix.linfty_opNorm_def]; simp [σ_y, Fin.sum_univ_two]

/-- **Honest-failure witness — the ACTUAL quantity, not a restatement of the bound.**

At resonance-scale drive (`ω = Ω`) the integrated counter-rotating drive *attains* `1/2` at
`T = π/2`. This is an exact value of the real object, so it genuinely certifies that the rotating-
wave reduction is uncontrolled here: `1/2` against the `1/500` that
`integral_counterRotating_witness_valid` gives at `ω = 1000 Ω` for ALL `T` — a factor of `250`,
with both numbers read off shipped statements rather than estimated.

Stating the failure as a computed value rather than as "the bound is large" matters: a large upper
bound proves nothing on its own, whereas this exhibits the remainder actually being order-unity. -/
theorem integral_counterRotating_witness_resonance :
    ‖∫ s in (0 : ℝ)..(Real.pi / 2), counterRotating 1 1 0 0 1 0 0 s‖ = 1 / 2 := by
  rw [integral_counterRotating 1 1 0 0 1 0 0 (Real.pi / 2) (by norm_num)]
  unfold bsAntiderivative
  rw [show (2 : ℝ) * 1 * (Real.pi / 2) + 0 = Real.pi by ring,
    show (1 : ℝ) * (Real.pi / 2) + 0 = Real.pi / 2 by ring]
  norm_num [Real.sin_pi, Real.cos_pi, Real.sin_pi_div_two, norm_smul, linftyOpNorm_sigmaY_eq_one]

/-! ## 5. Rotation-angle calibration at the RWA level

CONVENTION (stated, not assumed): `θ` is the *exponent* parameter, i.e. the co-rotating propagator
is `exp(-i·θ·(n̂·σ))`. The Bloch-sphere rotation angle is `2θ`. With this convention the calibration
identity is `θ = (m/2)·Ω·T`, where `m = |⟨0|O_drive|1⟩|` is the projected drive element. -/

/-- The SIGNED projected drive element `⟨0|O_drive|1⟩ = b - i·c`. That this really is the `(0,1)`
entry of `driveOp a b c d` — rather than a formula named after one — is
`DriveCalibration.transverseElement_driveOp`.

Signed, not a magnitude: the sign/phase is exactly what a calibration can get wrong, and
`DriveCalibration` (Wave 2) carries that as an explicit fail condition. -/
def projectedDriveElement (b c : ℝ) : ℂ := (b : ℂ) - Complex.I * (c : ℂ)

@[simp] lemma projectedDriveElement_normSq (b c : ℝ) :
    Complex.normSq (projectedDriveElement b c) = b ^ 2 + c ^ 2 := by
  simp [projectedDriveElement, Complex.normSq_apply]; ring

/-- **The co-rotating generator squares to a scalar — the GENERAL, off-resonance form.**

`H_RWA² = ((Δ² + Ω²m²)/4)·1` with detuning `Δ = ω₀ - ω`. Since a traceless involution generates a
rotation, this pins the generator's magnitude EXACTLY at `√(Δ² + Ω²m²)/2` — so the accumulated
angle is `(T/2)√(Δ² + Ω²m²)`, and the familiar `(m/2)·Ω·T` is the `Δ = 0` case, NOT the general
one. Detuning genuinely changes the rotation rate; a calibration that ignores it is wrong off
resonance. -/
theorem rwaGenerator_sq (ω₀ ω Ω φ b c : ℝ) :
    rwaGenerator ω₀ ω Ω φ b c ^ 2
      = (((ω₀ - ω) ^ 2 / 4 + Ω ^ 2 * (b ^ 2 + c ^ 2) / 4 : ℝ) : ℂ)
        • (1 : Matrix (Fin 2) (Fin 2) ℂ) := by
  have hpy := Real.sin_sq_add_cos_sq φ
  rw [pow_two]
  unfold rwaGenerator
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [σ_x, σ_y, σ_z, Matrix.mul_apply, Fin.sum_univ_two, Complex.ext_iff,
      -Complex.ofReal_pow, -Complex.ofReal_cos, -Complex.ofReal_sin] <;>
    ring_nf <;> constructor <;>
    (first
      | trivial
      | linear_combination (Ω ^ 2 * (b ^ 2 + c ^ 2) / 4) * hpy)

/-- The resonance case, as a corollary of the general identity. -/
theorem rwaGenerator_sq_resonance (ω Ω φ b c : ℝ) :
    rwaGenerator ω ω Ω φ b c ^ 2
      = ((Ω ^ 2 * (b ^ 2 + c ^ 2) / 4 : ℝ) : ℂ) • (1 : Matrix (Fin 2) (Fin 2) ℂ) := by
  have h := rwaGenerator_sq ω ω Ω φ b c
  simpa using h

/-- The GENERAL rotation angle accumulated over `T` at detuning `Δ`, in the exponent convention:
`θ = (T/2)·√(Δ² + Ω²m²)`, the magnitude pinned by `rwaGenerator_sq`. -/
def generalRotationAngle (Δ Ω b c T : ℝ) : ℝ :=
  (T / 2) * Real.sqrt (Δ ^ 2 + Ω ^ 2 * (b ^ 2 + c ^ 2))

/-- The RWA rotation angle accumulated over duration `T`, in the exponent convention above.

⚠️ ON RESONANCE ONLY. This is `generalRotationAngle` at `Δ = 0` (`generalRotationAngle_resonance`);
it ignores detuning, so it is the achieved angle only when `ω₀ = ω`. Off resonance the rate is
`√(Δ² + Ω²m²)/2`, strictly larger. -/
def rwaRotationAngle (Ω b c T : ℝ) : ℝ := (Real.sqrt (b ^ 2 + c ^ 2) / 2) * Ω * T

/-- At zero detuning the general angle reduces to `rwaRotationAngle`. This is what makes the
resonance restriction on `rwaRotationAngle` precise rather than merely asserted. -/
theorem generalRotationAngle_resonance (Ω b c T : ℝ) (hΩ : 0 ≤ Ω) :
    generalRotationAngle 0 Ω b c T = rwaRotationAngle Ω b c T := by
  unfold generalRotationAngle rwaRotationAngle
  rw [show (0 : ℝ) ^ 2 + Ω ^ 2 * (b ^ 2 + c ^ 2) = Ω ^ 2 * (b ^ 2 + c ^ 2) by ring,
    Real.sqrt_mul (by positivity), Real.sqrt_sq hΩ]
  ring

/-- **Detuning strictly increases the rotation rate.** Off resonance the achieved angle EXCEEDS the
on-resonance formula, so a calibration computed from `rwaRotationAngle` under-rotates — the
concrete failure the resonance restriction guards against. -/
theorem rwaRotationAngle_lt_generalRotationAngle (Δ Ω b c T : ℝ) (hΔ : Δ ≠ 0) (hΩ : 0 ≤ Ω)
    (hT : 0 < T) : rwaRotationAngle Ω b c T < generalRotationAngle Δ Ω b c T := by
  rw [← generalRotationAngle_resonance Ω b c T hΩ]
  unfold generalRotationAngle
  have hlt : Ω ^ 2 * (b ^ 2 + c ^ 2) < Δ ^ 2 + Ω ^ 2 * (b ^ 2 + c ^ 2) := by
    have : 0 < Δ ^ 2 := by positivity
    linarith
  have hs : Real.sqrt ((0:ℝ) ^ 2 + Ω ^ 2 * (b ^ 2 + c ^ 2))
      < Real.sqrt (Δ ^ 2 + Ω ^ 2 * (b ^ 2 + c ^ 2)) := by
    apply Real.sqrt_lt_sqrt (by positivity)
    simpa using hlt
  have hT2 : 0 < T / 2 := by linarith
  exact mul_lt_mul_of_pos_left hs hT2

/-- **The calibration identity:** `θ = (m/2)·Ω·T` with `m = |⟨0|O_drive|1⟩|`. -/
theorem rwaRotationAngle_eq_projected (Ω b c T : ℝ) :
    rwaRotationAngle Ω b c T = (‖projectedDriveElement b c‖ / 2) * Ω * T := by
  unfold rwaRotationAngle
  simp [Complex.norm_def, projectedDriveElement_normSq]

/-! ## 6. The conjugated integrated remainder, at propagator level

The abstract averaging bound instantiated at `Matrix (Fin 2) (Fin 2) ℂ`, with the counter-rotating
term as the driving generator and `bsAntiderivative` as its antiderivative. The hypotheses `hL`,
`hU` are propagator ODEs (`L' = L·P`, `U' = Q·U`), so this is a statement about propagators, not
about an isolated integral.

The propagator factor bounds `KL`, `KU` are left GENERAL rather than pinned to `1`. This is not
cosmetic: at the `ℓ^∞` operator norm used in this file, `exp(-iθσ_x)` — the co-rotating propagator
at resonance — has row sums `|cos θ| + |sin θ|` (`norm_rwaPropagator_transverse`), i.e. norm up to
`√2`. A hypothesis `‖L s‖ ≤ 1` would therefore exclude every rotation whose angle is not a
multiple of `π/2` — proved, not asserted, as `one_lt_norm_rwaPropagator_transverse` in §4.1d —
leaving a theorem that is true but about `ℓ^∞`-contractive propagators rather than the ones this
module exists to bound.

SCOPE. This bounds the CONJUGATED integrated remainder `‖∫₀ᵀ L·V·U‖`. The literal
`‖U-exact(T) − U_rwa(T)‖` form is `rwa_propagator_difference_bound` below, which composes this with
the discrepancy identity and the unitarity transfer from `BanachAveraging`.

The antiderivative's properties (its derivative, continuity, vanishing at `0`, and its bound) are
DISCHARGED here from `hω`/`hΩ` rather than assumed, so the conclusion carries the explicit
Bloch–Siegert constant `2(Ω/ω)·ℓ¹` instead of an arbitrary `B`.

⚠️ SCOPE (6EE item-G BLOCKER 1.1, corrected 2026-08-01). This exclusion is proved for the TRANSVERSE family only — `one_lt_norm_rwaPropagator_transverse` is quantified over `rwaPropagator ω ω Ω 0 1 0 t`. It is FALSE as a universal: `norm_zRotation` gives `‖zRotation θ‖ = 1` at every `θ`, lifted to propagators by `norm_rwaPropagator_diagonal`, and the module's own headline instantiation `diagonal_drive_propagator_bound` calls `rwa_propagator_difference_bound_physical … 1 1 1` — i.e. with `KL = KU = KUr = 1` — and succeeds. The general binders earn their generality on the transverse family, not on every propagator.
-/
theorem norm_integral_counterRotating_conjugated_le
    {L U P Q : ℝ → Matrix (Fin 2) (Fin 2) ℂ} {KL KU Kp Kq T ω Ω φ a b c d : ℝ}
    (hω : 0 < ω) (hΩ : 0 ≤ Ω)
    (hL : ∀ s, HasDerivAt L (L s * P s) s) (hU : ∀ s, HasDerivAt U (Q s * U s) s)
    (hLc : Continuous L) (hUc : Continuous U) (hPc : Continuous P) (hQc : Continuous Q)
    (hLb : ∀ s, ‖L s‖ ≤ KL) (hUb : ∀ s, ‖U s‖ ≤ KU)
    (hPb : ∀ s, ‖P s‖ ≤ Kp) (hQb : ∀ s, ‖Q s‖ ≤ Kq) (hT : 0 ≤ T) :
    ‖∫ s in (0 : ℝ)..T, L s * counterRotating ω Ω φ a b c d s * U s‖
      ≤ KL * KU * (2 * (Ω / ω) * (|a| + |b| + |c| + |d|)) * (1 + T * (Kp + Kq)) :=
  norm_integral_mul_mul_le
    (fun s => bsAntiderivative_hasDerivAt ω Ω φ a b c d hω.ne' s) hL hU
    (by unfold bsAntiderivative; fun_prop) hLc hUc hPc hQc
    (continuous_counterRotating ω Ω φ a b c d) (bsAntiderivative_zero ω Ω φ a b c d) hLb hUb
    (fun s => bsAntiderivative_norm_le ω Ω φ a b c d s hω hΩ) hPb hQb (by positivity) hT

/-! ### 3.5 The co-rotating propagator in closed form — what makes the angle an ANGLE

Everything above treats `generalRotationAngle` as a real number defined by a formula. That is not
yet physics: nothing so far connects it to the operator a drive actually applies. This section
closes that gap by exhibiting the co-rotating propagator in closed form and **pinning it by its
defining ODE**, exactly as `rotFrame_ode` pins the rotating frame.

The closed form works only because `rwaGenerator_sq` says `H_RWA² = rate²·1`; that theorem is
consumed here rather than merely cited, and it is what turns `cos θ·1 − i(sin θ/rate)·H` into a
solution of `U' = −i·H·U`. -/

/-- The co-rotating rotation RATE, `√(Δ² + Ω²m²)/2`.

⚠️ Corrected 2026-08-01 (6EE item-G BLOCKER 3.1). This docstring said the rate is "half the
magnitude of `rwaGenerator`" and then justified it with `H_RWA² = rate²·1` — which says the
magnitude **IS** the rate, not half of it. The justification refuted the claim it was offered for,
in the same sentence, and `DriveCalibration.lean:102` is titled "The rate in the calibration formula
IS the generator magnitude". The `/2` is in the DEFINITION of the rate relative to
`√(Δ² + Ω²m²)`; it is not a factor between the rate and the generator's magnitude.

`rwaRate_sq` read against `rwaGenerator_sq` gives `H_RWA² = rate²·1`, i.e. `‖H_RWA‖ = rate`. -/
noncomputable def rwaRate (Δ Ω b c : ℝ) : ℝ := Real.sqrt (Δ ^ 2 + Ω ^ 2 * (b ^ 2 + c ^ 2)) / 2

/-- The angle is the rate times the duration. -/
theorem generalRotationAngle_eq_rate_mul (Δ Ω b c T : ℝ) :
    generalRotationAngle Δ Ω b c T = rwaRate Δ Ω b c * T := by
  unfold generalRotationAngle rwaRate; ring

theorem rwaRate_sq (Δ Ω b c : ℝ) :
    rwaRate Δ Ω b c ^ 2 = Δ ^ 2 / 4 + Ω ^ 2 * (b ^ 2 + c ^ 2) / 4 := by
  unfold rwaRate
  rw [div_pow, Real.sq_sqrt (by positivity)]
  ring

/-- **The co-rotating propagator**, `U(t) = cos(θ t)·1 − i·(sin(θ t)/rate)·H_RWA`. -/
noncomputable def rwaPropagator (ω₀ ω Ω φ b c : ℝ) (t : ℝ) : Matrix (Fin 2) (Fin 2) ℂ :=
  ((Real.cos (generalRotationAngle (ω₀ - ω) Ω b c t) : ℝ) : ℂ)
      • (1 : Matrix (Fin 2) (Fin 2) ℂ)
    - (Complex.I * ((Real.sin (generalRotationAngle (ω₀ - ω) Ω b c t)
        / rwaRate (ω₀ - ω) Ω b c : ℝ) : ℂ)) • rwaGenerator ω₀ ω Ω φ b c

@[simp] theorem rwaPropagator_zero (ω₀ ω Ω φ b c : ℝ) : rwaPropagator ω₀ ω Ω φ b c 0 = 1 := by
  unfold rwaPropagator generalRotationAngle
  norm_num

/-- **The defining ODE** — `U'(t) = −i·H_RWA·U(t)`. This is what makes `rwaPropagator` *the*
co-rotating propagator rather than an arbitrary matrix-valued formula, and it is where
`rwaGenerator_sq` does its work. Requires a nondegenerate rate (`0 < rate`); at `rate = 0` the
generator vanishes and there is no rotation to speak of. -/
theorem rwaPropagator_ode (ω₀ ω Ω φ b c : ℝ) (hk : 0 < rwaRate (ω₀ - ω) Ω b c) (t : ℝ) :
    HasDerivAt (rwaPropagator ω₀ ω Ω φ b c)
      ((-Complex.I) • (rwaGenerator ω₀ ω Ω φ b c * rwaPropagator ω₀ ω Ω φ b c t)) t := by
  set k := rwaRate (ω₀ - ω) Ω b c with hkdef
  set H := rwaGenerator ω₀ ω Ω φ b c with hHdef
  have hangle : ∀ s : ℝ, generalRotationAngle (ω₀ - ω) Ω b c s = k * s := fun s =>
    generalRotationAngle_eq_rate_mul _ _ _ _ s
  -- the two scalar derivatives
  have hc : HasDerivAt (fun s : ℝ => Real.cos (generalRotationAngle (ω₀ - ω) Ω b c s))
      (-k * Real.sin (k * t)) t := by
    have h := ((hasDerivAt_id t).const_mul k).cos
    simp only [hangle]
    simpa [mul_comm, mul_assoc, mul_left_comm] using h
  have hs : HasDerivAt (fun s : ℝ =>
      Real.sin (generalRotationAngle (ω₀ - ω) Ω b c s) / k) (Real.cos (k * t)) t := by
    have h := (((hasDerivAt_id t).const_mul k).sin).div_const k
    simp only [hangle]
    have hrw : k * Real.cos (k * t) / k = Real.cos (k * t) := by
      field_simp
    rw [← hrw]
    simpa [mul_comm, mul_assoc, mul_left_comm] using h
  have h1 := hc.ofReal_comp.smul_const (1 : Matrix (Fin 2) (Fin 2) ℂ)
  have h2 := (hs.ofReal_comp.const_mul Complex.I).smul_const H
  have hderiv := h1.sub h2
  -- identify the derivative with `-i·H·U` using `H² = k²·1`
  have hsq : H * H = ((k ^ 2 : ℝ) : ℂ) • (1 : Matrix (Fin 2) (Fin 2) ℂ) := by
    have hgen := rwaGenerator_sq ω₀ ω Ω φ b c
    rw [← hHdef, pow_two] at hgen
    rw [hgen, hkdef, rwaRate_sq]
  have hval : ((-(k * Real.sin (k * t)) : ℝ) : ℂ) • (1 : Matrix (Fin 2) (Fin 2) ℂ)
      - (Complex.I * ((Real.cos (k * t) : ℝ) : ℂ)) • H
      = (-Complex.I) • (H * rwaPropagator ω₀ ω Ω φ b c t) := by
    have hexp : rwaPropagator ω₀ ω Ω φ b c t
        = ((Real.cos (k * t) : ℝ) : ℂ) • (1 : Matrix (Fin 2) (Fin 2) ℂ)
          - (Complex.I * ((Real.sin (k * t) / k : ℝ) : ℂ)) • H := by
      unfold rwaPropagator; rw [← hHdef, ← hkdef, hangle t]
    rw [hexp, mul_sub, Matrix.mul_smul, Matrix.mul_smul, mul_one, hsq, smul_smul, smul_sub,
      smul_smul, smul_smul]
    push_cast
    match_scalars <;> (field_simp; try simp [Complex.I_sq])
  rw [← hval]
  have : (-(k * Real.sin (k * t)) : ℝ) = -k * Real.sin (k * t) := by ring
  rw [this]
  exact hderiv

/-- **Uniqueness for the co-rotating propagator** — the same argument as `rotFrame_unique`. Any
solution of `U' = −i·H_RWA·U` with `U(0) = 1` agrees with `rwaPropagator` on `[0, T]`, so the closed
form is THE propagator and the rotation angle read off it below is not an artefact of a choice. -/
theorem rwaPropagator_unique (ω₀ ω Ω φ b c T : ℝ) (hk : 0 < rwaRate (ω₀ - ω) Ω b c)
    (F : ℝ → Matrix (Fin 2) (Fin 2) ℂ) (hFc : ContinuousOn F (Set.Icc 0 T))
    (hF' : ∀ t ∈ Set.Ico (0 : ℝ) T,
      HasDerivWithinAt F ((-Complex.I) • rwaGenerator ω₀ ω Ω φ b c * F t) (Set.Ici t) t)
    (hF0 : F 0 = 1) :
    Set.EqOn F (rwaPropagator ω₀ ω Ω φ b c) (Set.Icc 0 T) := by
  have hode : ∀ t : ℝ, HasDerivAt (rwaPropagator ω₀ ω Ω φ b c)
      ((-Complex.I) • rwaGenerator ω₀ ω Ω φ b c * rwaPropagator ω₀ ω Ω φ b c t) t := fun t => by
    rw [Matrix.smul_mul]
    exact rwaPropagator_ode ω₀ ω Ω φ b c hk t
  exact ODE_solution_unique
    (v := fun _ X => (-Complex.I) • rwaGenerator ω₀ ω Ω φ b c * X)
    (fun _ => lipschitzWith_const_mul _) hFc hF'
    (fun t _ => (hode t).continuousAt.continuousWithinAt)
    (fun t _ => (hode t).hasDerivWithinAt)
    (by rw [hF0, rwaPropagator_zero])

/-- The co-rotating generator is Hermitian. -/
theorem rwaGenerator_conjTranspose (ω₀ ω Ω φ b c : ℝ) :
    (rwaGenerator ω₀ ω Ω φ b c)ᴴ = rwaGenerator ω₀ ω Ω φ b c := by
  unfold rwaGenerator
  simp [Matrix.conjTranspose_add, Matrix.conjTranspose_smul, σ_x_hermitian, σ_z_hermitian,
    sigmaY_conjTranspose, Complex.conj_ofReal, -Complex.ofReal_cos, -Complex.ofReal_sin]

theorem generalRotationAngle_neg (Δ Ω b c t : ℝ) :
    generalRotationAngle Δ Ω b c (-t) = -generalRotationAngle Δ Ω b c t := by
  unfold generalRotationAngle; ring

/-- The propagator commutes with its own generator (it is a polynomial in it). -/
theorem rwaGenerator_comm_rwaPropagator (ω₀ ω Ω φ b c t : ℝ) :
    rwaGenerator ω₀ ω Ω φ b c * rwaPropagator ω₀ ω Ω φ b c t
      = rwaPropagator ω₀ ω Ω φ b c t * rwaGenerator ω₀ ω Ω φ b c := by
  unfold rwaPropagator
  rw [Matrix.mul_sub, Matrix.sub_mul, Matrix.mul_smul, Matrix.smul_mul, Matrix.mul_smul,
    Matrix.smul_mul, Matrix.mul_one, Matrix.one_mul]

/-- **Time reversal is the adjoint.** `U(−t) = U(t)ᴴ`, because `cos` is even and `sin` odd. -/
theorem rwaPropagator_neg_eq_conjTranspose (ω₀ ω Ω φ b c t : ℝ) :
    rwaPropagator ω₀ ω Ω φ b c (-t) = (rwaPropagator ω₀ ω Ω φ b c t)ᴴ := by
  unfold rwaPropagator
  rw [Matrix.conjTranspose_sub, Matrix.conjTranspose_smul, Matrix.conjTranspose_smul,
    Matrix.conjTranspose_one, rwaGenerator_conjTranspose,
    generalRotationAngle_neg, Real.cos_neg, Real.sin_neg]
  simp only [Complex.star_def, map_mul, Complex.conj_I, Complex.conj_ofReal]
  congr 2
  push_cast
  ring

/-- **The co-rotating propagator is unitary.** Needed to instantiate the difference bound at the
physical pair, where the left factor is `U_rwa⁻¹`. -/
theorem rwaPropagator_mul_neg (ω₀ ω Ω φ b c t : ℝ) (hk : 0 < rwaRate (ω₀ - ω) Ω b c) :
    rwaPropagator ω₀ ω Ω φ b c t * rwaPropagator ω₀ ω Ω φ b c (-t) = 1 := by
  set k := rwaRate (ω₀ - ω) Ω b c with hkdef
  set H := rwaGenerator ω₀ ω Ω φ b c with hHdef
  set θ := generalRotationAngle (ω₀ - ω) Ω b c t with hθ
  have hsq : H * H = ((k ^ 2 : ℝ) : ℂ) • (1 : Matrix (Fin 2) (Fin 2) ℂ) := by
    have hgen := rwaGenerator_sq ω₀ ω Ω φ b c
    rw [← hHdef, pow_two] at hgen
    rw [hgen, hkdef, rwaRate_sq]
  have hpy := Real.sin_sq_add_cos_sq θ
  unfold rwaPropagator
  rw [← hHdef, ← hkdef, ← hθ, generalRotationAngle_neg, ← hθ, Real.cos_neg, Real.sin_neg]
  simp only [Matrix.sub_mul, Matrix.mul_sub, Matrix.smul_mul, Matrix.mul_smul,
    Matrix.one_mul, Matrix.mul_one, smul_smul, hsq]
  have hk' : (k : ℝ) ≠ 0 := ne_of_gt hk
  have hkC : ((k : ℝ) : ℂ) ≠ 0 := Complex.ofReal_ne_zero.mpr hk'
  match_scalars
  · field_simp
    linear_combination Complex.sin_sq_add_cos_sq ((θ : ℝ) : ℂ)
      - (Complex.sin ((θ : ℝ) : ℂ)) ^ 2 * Complex.I_sq
  · ring

/-- **The rotation angle is read off the actual propagator.** `rwaGenerator` is traceless, so the
propagator's trace is `2·cos θ` — i.e. `generalRotationAngle` is the rotation angle of the operator
the drive applies, not merely a number named "angle". This is the bridge the calibration identities
in `DriveCalibration` stand on. -/
theorem rwaPropagator_trace (ω₀ ω Ω φ b c t : ℝ) :
    rwaPropagator ω₀ ω Ω φ b c t 0 0 + rwaPropagator ω₀ ω Ω φ b c t 1 1
      = 2 * ((Real.cos (generalRotationAngle (ω₀ - ω) Ω b c t) : ℝ) : ℂ) := by
  unfold rwaPropagator rwaGenerator
  simp [σ_x, σ_y, σ_z, Complex.ext_iff]
  ring

/-! ### 4.1 The Schrödinger-picture antiderivative

A propagator solves `dU/dt = −i·H·U`, so for a propagator PAIR the generator difference `P + Q`
carries a factor `−i` relative to the Hamiltonian remainder `V`: with `L = U_rwa⁻¹` and
`U = U-exact` one gets `P = i·H_RWA`, `Q = −i·H_I`, hence `P + Q = −i·V`. The object whose
derivative is `P + Q` is therefore `−i·S`, **not** `S`.

This matters: stating the propagator bound against `S` itself would force
`P + Q = counterRotating` by uniqueness of the derivative, which no Schrödinger propagator pair
with a nonvanishing remainder satisfies (`P + Q` is anti-Hermitian, `V` is Hermitian, so they agree
only where both are zero) — the theorem would be true but instantiable only at systems whose
generator difference is the Hermitian `V`, never at the physical ones it is named for. Since `‖-i • S‖ = ‖S‖`, the
Bloch–Siegert constant survives the correction untouched. -/

/-- The `−i`-scaled Bloch–Siegert antiderivative differentiates to the Schrödinger generator
difference `−i·V`. -/
theorem schrodingerAntiderivative_hasDerivAt (ω Ω φ a b c d : ℝ) (hω : ω ≠ 0) (t : ℝ) :
    HasDerivAt (fun s => (-Complex.I) • bsAntiderivative ω Ω φ a b c d s)
      ((-Complex.I) • counterRotating ω Ω φ a b c d t) t :=
  ((bsAntiderivative_hasDerivAt ω Ω φ a b c d hω t).const_smul (-Complex.I) :)

@[simp] theorem schrodingerAntiderivative_zero (ω Ω φ a b c d : ℝ) :
    (-Complex.I) • bsAntiderivative ω Ω φ a b c d 0 = 0 := by
  rw [bsAntiderivative_zero]; simp

/-- Scaling by the unit phase `−i` leaves the Bloch–Siegert bound unchanged. -/
theorem schrodingerAntiderivative_norm_le (ω Ω φ a b c d t : ℝ) (hω : 0 < ω) (hΩ : 0 ≤ Ω) :
    ‖(-Complex.I) • bsAntiderivative ω Ω φ a b c d t‖
      ≤ 2 * (Ω / ω) * (|a| + |b| + |c| + |d|) := by
  rw [norm_smul]
  simpa using bsAntiderivative_norm_le ω Ω φ a b c d t hω hΩ

/-- **The propagator difference bound for the RWA system, at Bloch–Siegert scale.**

This is the literal `‖U-exact(T) − U_rwa(T)‖` statement. The Bloch–Siegert constant originates in
`bsAntiderivative_norm_le` and reaches this proof through the `−i`-scaled
`schrodingerAntiderivative_norm_le` (§4.1), which is the theorem actually called; the scaling is by
a unit phase, so the constant is unchanged. Hence the bound carries an explicit `Ω/ω`:

`‖U-exact(T) − U_rwa(T)‖ ≤ KUr·KL·KU·2(Ω/ω)(|a|+|b|+|c|+|d|)·(1 + T(Kp+Kq))`.

`hω : 0 < ω` and `hΩ : 0 ≤ Ω` are load-bearing — they are what make the constant `Ω/ω` rather than
an arbitrary `B`. The reduction is nowhere asserted as an equality.

`hSgen` is stated on the `−i`-scaled antiderivative (§4.1): that is the form an actual propagator
pair satisfies, and `rwa_propagator_difference_bound_inhabited` below exhibits one. -/
theorem rwa_propagator_difference_bound
    {L U P Q : ℝ → Matrix (Fin 2) (Fin 2) ℂ} {Ur : Matrix (Fin 2) (Fin 2) ℂ}
    {KL KU KUr Kp Kq T ω Ω φ a b c d : ℝ} (hω : 0 < ω) (hΩ : 0 ≤ Ω)
    (hL : ∀ s, HasDerivAt L (L s * P s) s) (hU : ∀ s, HasDerivAt U (Q s * U s) s)
    (hSgen : ∀ s, HasDerivAt (fun r => (-Complex.I) • bsAntiderivative ω Ω φ a b c d r)
      (P s + Q s) s)
    (hLc : Continuous L) (hUc : Continuous U) (hPc : Continuous P) (hQc : Continuous Q)
    (hL0U0 : L 0 * U 0 = 1)
    (hLb : ∀ s, ‖L s‖ ≤ KL) (hUb : ∀ s, ‖U s‖ ≤ KU)
    (hPb : ∀ s, ‖P s‖ ≤ Kp) (hQb : ∀ s, ‖Q s‖ ≤ Kq) (hT : 0 ≤ T)
    (hinv : Ur * L T = 1) (hUrb : ‖Ur‖ ≤ KUr) :
    ‖U T - Ur‖ ≤ KUr * (KL * KU * (2 * (Ω / ω) * (|a| + |b| + |c| + |d|))
      * (1 + T * (Kp + Kq))) :=
  norm_propagator_sub_le hSgen hL hU
    (by unfold bsAntiderivative; fun_prop) hLc hUc hPc hQc
    (schrodingerAntiderivative_zero ω Ω φ a b c d) hL0U0 hLb hUb
    (fun s => schrodingerAntiderivative_norm_le ω Ω φ a b c d s hω hΩ) hPb hQb
    (by positivity) hT hinv hUrb

/-! ### 4.1b The bound AT THE PHYSICAL PAIR — U_exact against U_rwa

§4.1's theorem is stated over abstract `L`, `U`, `P`, `Q`; the identification
`L = U_rwa⁻¹`, `U = U-exact`, `P = i·H_RWA`, `Q = −i·H_I` lived only in its docstring. This
section performs that identification as a declaration, so the bound is *about* the exact and
co-rotating propagators rather than about a binder pattern they are said to fit.

`U` is quantified over ANY solution of the exact interaction-picture Schrödinger equation — no
existence theorem is needed, and none is claimed: whatever the exact propagator is, it is within
`O(Ω/ω)` of the co-rotating one. -/

theorem continuous_rwaPropagator (ω₀ ω Ω φ b c : ℝ) (hk : 0 < rwaRate (ω₀ - ω) Ω b c) :
    Continuous (rwaPropagator ω₀ ω Ω φ b c) :=
  continuous_iff_continuousAt.mpr fun t => (rwaPropagator_ode ω₀ ω Ω φ b c hk t).continuousAt

/-- The inverse co-rotating propagator `U_rwa(s)⁻¹ = U_rwa(−s)` solves `L' = L·(i·H_RWA)`. -/
theorem rwaPropagatorInv_hasDerivAt (ω₀ ω Ω φ b c : ℝ) (hk : 0 < rwaRate (ω₀ - ω) Ω b c) (s : ℝ) :
    HasDerivAt (fun r => rwaPropagator ω₀ ω Ω φ b c (-r))
      (rwaPropagator ω₀ ω Ω φ b c (-s) * (Complex.I • rwaGenerator ω₀ ω Ω φ b c)) s := by
  have hneg : HasDerivAt (fun r : ℝ => -r) (-1 : ℝ) s := hasDerivAt_neg s
  have h := (rwaPropagator_ode ω₀ ω Ω φ b c hk (-s)).scomp s hneg
  have hval : (-1 : ℝ) • ((-Complex.I) • (rwaGenerator ω₀ ω Ω φ b c
        * rwaPropagator ω₀ ω Ω φ b c (-s)))
      = rwaPropagator ω₀ ω Ω φ b c (-s) * (Complex.I • rwaGenerator ω₀ ω Ω φ b c) := by
    rw [rwaGenerator_comm_rwaPropagator, Matrix.mul_smul]
    module
  rw [← hval]
  exact h

/-- **The propagator difference bound at the physical pair.** For ANY solution `U` of the exact
interaction-picture equation `U' = −i·H_I(t)·U` with `U(0) = 1`, the difference from the co-rotating
propagator at time `T` is bounded at Bloch–Siegert scale:

`‖U(T) − U_rwa(T)‖ ≤ KUr·KL·KU·2(Ω/ω)(|a|+|b|+|c|+|d|)·(1 + T(Kp+Kq))`.

Every *structural* binder of `rwa_propagator_difference_bound` is discharged from the physical data:
`hSgen` from `interactionHamiltonian_decomp`, `hinv` from the propagator's unitarity, `hL` from the
inverse propagator's own ODE, plus the continuity and `L 0 * U 0 = 1` conditions. The five NORM
constants (`KL`, `KU`, `KUr`, `Kp`, `Kq`) remain general here by design — they are computed at the
instantiation site, `diagonal_drive_propagator_bound`.

SCOPE of `b`, `c` (stated precisely, because the honest answer is narrower than "nothing is
degenerate"). The binders place no constraint on the transverse drive components beyond
`0 < rate`, so nothing in the hypothesis set excludes them. That is a fact about the BINDERS, not
a witnessed instantiation. The only exact propagator this file exhibits in closed form is the
diagonal one (`diagonalExactPropagator`, `b = c = 0`), because once `b` or `c` is nonzero `H_I(t)`
no longer commutes with itself at different times and its propagator is not elementary. So `hU` is
discharged from physical data only at `b = c = 0` (`diagonal_drive_propagator_bound`); at `b ≠ 0`
the theorem applies to whatever exact propagator the reader supplies, and no such object is
shipped here. The transverse content this file DOES ship concerns the co-rotating propagator alone
(`rwaPropagator_transverse`, `one_lt_norm_rwaPropagator_transverse`). -/
theorem rwa_propagator_difference_bound_physical
    (ω₀ ω Ω φ a b c d T KL KU KUr Kp Kq : ℝ) (hω : 0 < ω) (hΩ : 0 ≤ Ω) (hT : 0 ≤ T)
    (hk : 0 < rwaRate (ω₀ - ω) Ω b c)
    (U : ℝ → Matrix (Fin 2) (Fin 2) ℂ)
    (hU : ∀ s, HasDerivAt U
      (((-Complex.I) • interactionHamiltonian ω₀ ω Ω φ a b c d s) * U s) s)
    (hU0 : U 0 = 1) (hUc : Continuous U)
    (hLb : ∀ s, ‖rwaPropagator ω₀ ω Ω φ b c (-s)‖ ≤ KL) (hUb : ∀ s, ‖U s‖ ≤ KU)
    (hPb : ‖Complex.I • rwaGenerator ω₀ ω Ω φ b c‖ ≤ Kp)
    (hQb : ∀ s, ‖(-Complex.I) • interactionHamiltonian ω₀ ω Ω φ a b c d s‖ ≤ Kq)
    (hUrb : ‖rwaPropagator ω₀ ω Ω φ b c T‖ ≤ KUr) :
    ‖U T - rwaPropagator ω₀ ω Ω φ b c T‖
      ≤ KUr * (KL * KU * (2 * (Ω / ω) * (|a| + |b| + |c| + |d|)) * (1 + T * (Kp + Kq))) := by
  have hgen : ∀ s : ℝ, Complex.I • rwaGenerator ω₀ ω Ω φ b c
      + (-Complex.I) • interactionHamiltonian ω₀ ω Ω φ a b c d s
      = (-Complex.I) • counterRotating ω Ω φ a b c d s := by
    intro s
    rw [interactionHamiltonian_decomp, smul_add]
    module
  refine rwa_propagator_difference_bound
    (L := fun s => rwaPropagator ω₀ ω Ω φ b c (-s)) (U := U)
    (P := fun _ => Complex.I • rwaGenerator ω₀ ω Ω φ b c)
    (Q := fun s => (-Complex.I) • interactionHamiltonian ω₀ ω Ω φ a b c d s)
    (Ur := rwaPropagator ω₀ ω Ω φ b c T) hω hΩ
    (fun s => rwaPropagatorInv_hasDerivAt ω₀ ω Ω φ b c hk s) hU
    (fun s => by rw [hgen s]; exact schrodingerAntiderivative_hasDerivAt ω Ω φ a b c d hω.ne' s)
    ((continuous_rwaPropagator ω₀ ω Ω φ b c hk).comp continuous_neg) hUc continuous_const ?_
    (by simp [hU0])
    hLb hUb (fun _ => hPb) hQb hT ?_ hUrb
  · unfold interactionHamiltonian drivenHamiltonian driveOp rotFrame
    fun_prop
  · have := rwaPropagator_mul_neg ω₀ ω Ω φ b c T hk
    simpa using this

/-! ### 4.1d Why the factor bounds are general — the satisfiability claim, shipped

Two docstrings assert that pinning `KL`, `KU` to `1` would make the hypotheses *unsatisfiable for
every rotation* — `BanachAveraging.norm_integral_mul_mul_le` and the §6 header above. That is a
satisfiability assertion about a hypothesis set — exactly the category in which review 2 found a
BLOCKER — so it is proved here rather than asserted.

A quarter-turn `σ_x` rotation has `ℓ^∞` operator norm `√2 > 1`
(`one_lt_norm_rwaPropagator_quarter_turn`). The "every rotation" quantifier is discharged too, and
separately: `one_lt_norm_rwaPropagator_transverse` gives `‖U_rwa(t)‖ > 1` at EVERY `t` whose angle
avoids the multiples of `π/2`, so the claim is a theorem rather than a generalisation from one
lucky time. -/

/-- **The transverse co-rotating propagator in closed form** — a rotation about `σ_x` through the
exponent angle `Ω t / 2`, at every `t`. The quarter turn below is its special case. -/
theorem rwaPropagator_transverse (ω Ω t : ℝ) (hΩ : 0 < Ω) :
    rwaPropagator ω ω Ω 0 1 0 t
      = ((Real.cos (Ω * t / 2) : ℝ) : ℂ) • (1 : Matrix (Fin 2) (Fin 2) ℂ)
        - (Complex.I * ((Real.sin (Ω * t / 2) : ℝ) : ℂ)) • σ_x := by
  have hrate : rwaRate (ω - ω) Ω 1 0 = Ω / 2 := by
    unfold rwaRate
    rw [show (ω - ω) ^ 2 + Ω ^ 2 * ((1:ℝ) ^ 2 + (0:ℝ) ^ 2) = Ω ^ 2 by ring, Real.sqrt_sq hΩ.le]
  have hangle : generalRotationAngle (ω - ω) Ω 1 0 t = Ω * t / 2 := by
    rw [generalRotationAngle_eq_rate_mul, hrate]
    ring
  have hgen : rwaGenerator ω ω Ω 0 1 0 = ((Ω / 2 : ℝ) : ℂ) • σ_x := by
    unfold rwaGenerator
    ext i j
    fin_cases i <;> fin_cases j <;> simp [σ_x, σ_y, σ_z]
  have hΩC : ((Ω : ℝ) : ℂ) ≠ 0 := Complex.ofReal_ne_zero.mpr hΩ.ne'
  unfold rwaPropagator
  rw [hangle, hrate, hgen, smul_smul]
  congr 2
  push_cast
  field_simp

/-- The quarter-turn co-rotating propagator, written out — `rwaPropagator_transverse` at
`t = π/(2Ω)`. -/
theorem rwaPropagator_quarter_turn (ω Ω : ℝ) (hΩ : 0 < Ω) :
    rwaPropagator ω ω Ω 0 1 0 (Real.pi / (2 * Ω))
      = ((Real.cos (Real.pi / 4) : ℝ) : ℂ) • (1 : Matrix (Fin 2) (Fin 2) ℂ)
        - (Complex.I * ((Real.sin (Real.pi / 4) : ℝ) : ℂ)) • σ_x := by
  have h : Ω * (Real.pi / (2 * Ω)) / 2 = Real.pi / 4 := by
    field_simp
    ring
  rw [rwaPropagator_transverse ω Ω _ hΩ, h]

/-- `‖1 − i·σ_x‖ = 2` in the `ℓ^∞` operator norm — entries `1, ∓i`, so each row sums to `2`. -/
theorem linftyOpNorm_one_sub_I_sigmaX :
    ‖(1 : Matrix (Fin 2) (Fin 2) ℂ) - Complex.I • σ_x‖ = 2 := by
  rw [Matrix.linfty_opNorm_def, show (Finset.univ : Finset (Fin 2)) = {0, 1} from rfl,
    Finset.sup_insert, Finset.sup_singleton]
  simp [σ_x, Matrix.one_apply]
  norm_num

/-- **`‖U_rwa‖ = √2` at the quarter turn** — so a hypothesis `‖L s‖ ≤ 1` in the `ℓ^∞` operator norm
would exclude this rotation outright. The general `KL`/`KU` binders in `BanachAveraging` are
load-bearing, and this is the proof rather than the assertion.

⚠️ SCOPE (6EE item-G BLOCKER 1.1, corrected 2026-08-01). This exclusion is proved for the TRANSVERSE family only — `one_lt_norm_rwaPropagator_transverse` is quantified over `rwaPropagator ω ω Ω 0 1 0 t`. It is FALSE as a universal: `norm_zRotation` gives `‖zRotation θ‖ = 1` at every `θ`, lifted to propagators by `norm_rwaPropagator_diagonal`, and the module's own headline instantiation `diagonal_drive_propagator_bound` calls `rwa_propagator_difference_bound_physical … 1 1 1` — i.e. with `KL = KU = KUr = 1` — and succeeds. The general binders earn their generality on the transverse family, not on every propagator.
-/
theorem norm_rwaPropagator_quarter_turn (ω Ω : ℝ) (hΩ : 0 < Ω) :
    ‖rwaPropagator ω ω Ω 0 1 0 (Real.pi / (2 * Ω))‖ = Real.sqrt 2 := by
  have hfac : rwaPropagator ω ω Ω 0 1 0 (Real.pi / (2 * Ω))
      = ((Real.sqrt 2 / 2 : ℝ) : ℂ) • ((1 : Matrix (Fin 2) (Fin 2) ℂ) - Complex.I • σ_x) := by
    rw [rwaPropagator_quarter_turn ω Ω hΩ, Real.cos_pi_div_four, Real.sin_pi_div_four]
    push_cast
    module
  rw [hfac, norm_smul, linftyOpNorm_one_sub_I_sigmaX, Complex.norm_real, Real.norm_eq_abs,
    abs_of_nonneg (by positivity : (0:ℝ) ≤ Real.sqrt 2 / 2)]
  ring

/-- …and `√2 > 1`, so the exclusion is real: pinning the factor bounds to `1` would have made the
averaging hypotheses unsatisfiable for the very propagators the module exists to bound. -/
theorem one_lt_norm_rwaPropagator_quarter_turn (ω Ω : ℝ) (hΩ : 0 < Ω) :
    1 < ‖rwaPropagator ω ω Ω 0 1 0 (Real.pi / (2 * Ω))‖ := by
  rw [norm_rwaPropagator_quarter_turn ω Ω hΩ]
  nlinarith [Real.sq_sqrt (by norm_num : (0:ℝ) ≤ 2), Real.sqrt_nonneg 2]

/-- `‖x·1 − i y·σ_x‖ = |x| + |y|` in the `ℓ^∞` operator norm: both rows carry the entries `x`
and `∓i y`, so both row sums are `|x| + |y|`. -/
theorem linftyOpNorm_smul_one_sub_I_smul_sigmaX (x y : ℝ) :
    ‖((x : ℝ) : ℂ) • (1 : Matrix (Fin 2) (Fin 2) ℂ)
      - (Complex.I * ((y : ℝ) : ℂ)) • σ_x‖ = |x| + |y| := by
  rw [Matrix.linfty_opNorm_def, show (Finset.univ : Finset (Fin 2)) = {0, 1} from rfl,
    Finset.sup_insert, Finset.sup_singleton]
  simp [σ_x, Matrix.one_apply]
  linarith [abs_nonneg x, abs_nonneg y]

/-- The `ℓ^∞` norm of the transverse co-rotating propagator at EVERY time: `|cos θ| + |sin θ|`
with `θ = Ω t / 2`. -/
theorem norm_rwaPropagator_transverse (ω Ω t : ℝ) (hΩ : 0 < Ω) :
    ‖rwaPropagator ω ω Ω 0 1 0 t‖
      = |Real.cos (Ω * t / 2)| + |Real.sin (Ω * t / 2)| := by
  rw [rwaPropagator_transverse ω Ω t hΩ, linftyOpNorm_smul_one_sub_I_smul_sigmaX]

/-- **The exclusion is not one lucky time — it is every transverse rotation whose angle is not a
multiple of `π/2`.** For any such `t`, `‖U_rwa(t)‖ > 1`, so a hypothesis `‖L s‖ ≤ 1` in the `ℓ^∞`
operator norm would exclude the whole family, not merely the quarter turn.

This is the general form of the satisfiability claim that `BanachAveraging`'s
`norm_integral_mul_mul_le` docstring makes when it says pinning `KL`, `KU` to `1` would exclude
essentially every rotation; `one_lt_norm_rwaPropagator_quarter_turn` above is the `θ = π/4`
instance.

⚠️ SCOPE (6EE item-G BLOCKER 1.1, corrected 2026-08-01). This exclusion is proved for the TRANSVERSE family only — `one_lt_norm_rwaPropagator_transverse` is quantified over `rwaPropagator ω ω Ω 0 1 0 t`. It is FALSE as a universal: `norm_zRotation` gives `‖zRotation θ‖ = 1` at every `θ`, lifted to propagators by `norm_rwaPropagator_diagonal`, and the module's own headline instantiation `diagonal_drive_propagator_bound` calls `rwa_propagator_difference_bound_physical … 1 1 1` — i.e. with `KL = KU = KUr = 1` — and succeeds. The general binders earn their generality on the transverse family, not on every propagator.
-/
theorem one_lt_norm_rwaPropagator_transverse (ω Ω t : ℝ) (hΩ : 0 < Ω)
    (hc : Real.cos (Ω * t / 2) ≠ 0) (hs : Real.sin (Ω * t / 2) ≠ 0) :
    1 < ‖rwaPropagator ω ω Ω 0 1 0 t‖ := by
  rw [norm_rwaPropagator_transverse ω Ω t hΩ]
  have hpy := Real.sin_sq_add_cos_sq (Ω * t / 2)
  have hac : 0 < |Real.cos (Ω * t / 2)| := abs_pos.mpr hc
  have has : 0 < |Real.sin (Ω * t / 2)| := abs_pos.mpr hs
  nlinarith [sq_abs (Real.cos (Ω * t / 2)), sq_abs (Real.sin (Ω * t / 2)), hac, has]

/-! ### 4.2 The bound's hypothesis set is inhabited at an actual propagator pair

`rwa_propagator_difference_bound` is only worth its name if some genuine Schrödinger propagator pair
satisfies every binder. We exhibit one. Take a drive along the identity (`b = c = d = 0`) at
resonance (`ω₀ = ω`): then `rwaGenerator = 0`, so `U_rwa ≡ 1`, while `H_I(t) = Ω·cos(ωt+φ)·a·1`
commutes with itself at all times and its propagator is available in closed form. Everything is a
scalar multiple of the identity, so the pair is genuinely a pair of unitary propagators — not a
formal solution of a rewritten equation.

⚠️ **This witness is DEGENERATE and must not be cited as more.** At `ω₀ = ω` with `b = c = 0` the
co-rotating generator VANISHES, so `U_rwa ≡ 1` and the entire bounded difference is unobservable
global phase. It establishes only that the binder set is inhabited at *some* Schrödinger pair. The
NONdegenerate statement — nonzero generator, nonzero counter-rotating remainder, closed-form exact
propagator, and an OBSERVABLE error — is `diagonal_drive_propagator_bound` in §4.1c. -/

/-- The accumulated phase of the commuting identity-drive, `∫₀ᵗ Ω·a·cos(ωs+φ) ds`. -/
noncomputable def commutingDrivePhase (ω Ω φ a : ℝ) (t : ℝ) : ℝ :=
  (Ω * a / ω) * (Real.sin (ω * t + φ) - Real.sin φ)

/-- The exact propagator of the commuting identity-drive: `exp(-i·phase(t))·1`. -/
noncomputable def commutingDrivePropagator (ω Ω φ a : ℝ) (t : ℝ) : Matrix (Fin 2) (Fin 2) ℂ :=
  Complex.exp (-Complex.I * (commutingDrivePhase ω Ω φ a t : ℂ)) • (1 : Matrix (Fin 2) (Fin 2) ℂ)

theorem commutingDrivePhase_hasDerivAt (ω Ω φ a : ℝ) (hω : ω ≠ 0) (t : ℝ) :
    HasDerivAt (commutingDrivePhase ω Ω φ a) (Ω * a * Real.cos (ω * t + φ)) t := by
  have hinner : HasDerivAt (fun s : ℝ => ω * s + φ) ω t := by
    simpa using ((hasDerivAt_id t).const_mul ω).add_const φ
  have h := (((Real.hasDerivAt_sin (ω * t + φ)).comp t hinner).sub_const
    (Real.sin φ)).const_mul (Ω * a / ω)
  have hval : Ω * a / ω * (Real.cos (ω * t + φ) * ω) = Ω * a * Real.cos (ω * t + φ) := by
    field_simp
  rw [← hval]
  exact h

theorem commutingDrivePropagator_zero (ω Ω φ a : ℝ) :
    commutingDrivePropagator ω Ω φ a 0 = 1 := by
  unfold commutingDrivePropagator commutingDrivePhase
  norm_num

theorem norm_commutingDrivePropagator (ω Ω φ a t : ℝ) :
    ‖commutingDrivePropagator ω Ω φ a t‖ = 1 := by
  unfold commutingDrivePropagator
  rw [norm_smul, norm_one, Complex.norm_exp]
  simp

theorem commutingDrivePropagator_hasDerivAt (ω Ω φ a : ℝ) (hω : ω ≠ 0) (t : ℝ) :
    HasDerivAt (commutingDrivePropagator ω Ω φ a)
      (((-Complex.I * ((Ω * a * Real.cos (ω * t + φ) : ℝ) : ℂ)) • (1 : Matrix (Fin 2) (Fin 2) ℂ))
        * commutingDrivePropagator ω Ω φ a t) t := by
  have hg := (commutingDrivePhase_hasDerivAt ω Ω φ a hω t).ofReal_comp
  have hexp := ((hg.const_mul (-Complex.I)).cexp).smul_const
    (1 : Matrix (Fin 2) (Fin 2) ℂ)
  have hval :
      ((-Complex.I * ((Ω * a * Real.cos (ω * t + φ) : ℝ) : ℂ))
          • (1 : Matrix (Fin 2) (Fin 2) ℂ)) * commutingDrivePropagator ω Ω φ a t
      = (Complex.exp (-Complex.I * (commutingDrivePhase ω Ω φ a t : ℂ))
          * (-Complex.I * ((Ω * a * Real.cos (ω * t + φ) : ℝ) : ℂ)))
        • (1 : Matrix (Fin 2) (Fin 2) ℂ) := by
    unfold commutingDrivePropagator
    rw [Matrix.smul_mul, Matrix.mul_smul, one_mul, smul_smul, mul_comm]
  rw [hval]
  exact hexp

/-- **The propagator-difference bound is inhabited.** Every binder of
`rwa_propagator_difference_bound` is satisfied by the commuting identity-drive at resonance, with
`U` its exact propagator, `L = U_rwa⁻¹ = 1`, and `Ur = 1`. So the theorem is a statement about real
Schrödinger propagator pairs, not one whose hypotheses silently exclude them.

⚠️ DEGENERATE (see the section header): `rwaGenerator = 0` here, so this shows inhabitation only.
For the nondegenerate case see `diagonal_drive_propagator_bound`. -/
theorem rwa_propagator_difference_bound_inhabited (ω Ω φ a T : ℝ)
    (hω : 0 < ω) (hΩ : 0 ≤ Ω) (hT : 0 ≤ T) :
    ‖commutingDrivePropagator ω Ω φ a T - 1‖
      ≤ 1 * (1 * 1 * (2 * (Ω / ω) * (|a| + |0| + |0| + |0|))
        * (1 + T * (0 + Ω * |a|))) := by
  have hQeq : ∀ s : ℝ,
      (0 : Matrix (Fin 2) (Fin 2) ℂ)
        + (-Complex.I * ((Ω * a * Real.cos (ω * s + φ) : ℝ) : ℂ))
            • (1 : Matrix (Fin 2) (Fin 2) ℂ)
      = (-Complex.I) • counterRotating ω Ω φ a 0 0 0 s := by
    intro s
    unfold counterRotating
    ext i j
    fin_cases i <;> fin_cases j <;>
      simp [σ_x, σ_y, σ_z, Complex.ext_iff] <;> constructor <;> ring
  refine rwa_propagator_difference_bound (L := fun _ => 1)
    (U := commutingDrivePropagator ω Ω φ a) (P := fun _ => 0)
    (Q := fun s => (-Complex.I * ((Ω * a * Real.cos (ω * s + φ) : ℝ) : ℂ))
      • (1 : Matrix (Fin 2) (Fin 2) ℂ))
    (Ur := 1) hω hΩ (fun s => by simp only [mul_zero]; exact hasDerivAt_const s _)
    (fun s => commutingDrivePropagator_hasDerivAt ω Ω φ a hω.ne' s)
    (fun s => by
      rw [hQeq s]
      exact schrodingerAntiderivative_hasDerivAt ω Ω φ a 0 0 0 hω.ne' s)
    continuous_const
    (by
      unfold commutingDrivePropagator commutingDrivePhase
      fun_prop)
    continuous_const
    (by fun_prop)
    (by simp [commutingDrivePropagator_zero]) (fun s => by simp)
    (fun s => (norm_commutingDrivePropagator ω Ω φ a s).le)
    (fun s => by simp) (fun s => ?_) hT (by simp) (by simp)
  rw [norm_smul, norm_one, mul_one, norm_mul, norm_neg, Complex.norm_I, one_mul,
    Complex.norm_real, Real.norm_eq_abs, abs_mul, abs_mul]
  calc |Ω| * |a| * |Real.cos (ω * s + φ)| ≤ |Ω| * |a| * 1 := by
        gcongr; exact Real.abs_cos_le_one _
    _ = Ω * |a| := by rw [mul_one, abs_of_nonneg hΩ]

/-! ### 4.1c A GENUINELY nondegenerate inhabitation — an OBSERVABLE RWA error

§4.2's witness is a pure identity drive: `rwaGenerator = 0`, `U_rwa ≡ 1`, and the bounded difference
is unobservable global phase. An earlier version of this section merely added detuning to that same
identity drive — which fixes the generator but leaves the *discrepancy* a global phase, since
`driveOp a 0 0 0 = a·1` commutes with everything. That was degenerate in a second way and is
corrected here.

The witness now carries a **`σ_z` drive component** (`d ≠ 0`) alongside the identity component:

* `driveOp a 0 0 d = a·1 + d·σ_z` is **not** a multiple of the identity;
* `H_RWA = (Δ/2)·σ_z ≠ 0` at nonzero detuning;
* `V(t) = Ω·cos(ωt+φ)·(a·1 + d·σ_z) ≠ 0`;
* `V` still commutes with `H_RWA` (both are diagonal), so the EXACT propagator remains available in
  closed form — but the `d` component now shifts the accumulated **`σ_z` rotation angle**, so
  U_exact and U_rwa differ by a genuine relative rotation, not a phase.

That last point is what makes this a real exercise of the bound: the discrepancy it bounds is
physically observable.

⚠️ Naming: this is a *longitudinal* drive in the `σ_z` sense (`longitudinalElement (driveOp a 0 0 d)
= d ≠ 0`, by `longitudinalElement_driveOp`), unlike the earlier `a`-only version whose longitudinal
element was zero. -/

theorem rwaRate_longitudinal (Δ Ω : ℝ) : rwaRate Δ Ω 0 0 = |Δ| / 2 := by
  unfold rwaRate
  rw [show Δ ^ 2 + Ω ^ 2 * ((0:ℝ) ^ 2 + (0:ℝ) ^ 2) = Δ ^ 2 by ring, Real.sqrt_sq_eq_abs]

theorem rwaGenerator_longitudinal_ne_zero (ω₀ ω Ω φ : ℝ) (hdet : ω₀ ≠ ω) :
    rwaGenerator ω₀ ω Ω φ 0 0 ≠ 0 := by
  intro hz
  have h := congrFun (congrFun hz 0) 0
  unfold rwaGenerator at h
  simp [σ_x, σ_y, σ_z, Complex.ext_iff] at h
  exact hdet (by linarith [h])

/-- For a purely diagonal drive the counter-rotating remainder is `Ω·cos(ωt+φ)·(a·1 + d·σ_z)`. -/
theorem counterRotating_diagonal (ω Ω φ a d t : ℝ) :
    counterRotating ω Ω φ a 0 0 d t
      = ((Ω * Real.cos (ω * t + φ) : ℝ) : ℂ)
        • ((a : ℂ) • (1 : Matrix (Fin 2) (Fin 2) ℂ) + (d : ℂ) • σ_z) := by
  unfold counterRotating
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [σ_x, σ_y, σ_z, Complex.ext_iff] <;> constructor <;> ring

/-- The accumulated `σ_z` rotation angle of the exact dynamics: the co-rotating part `(Δ/2)·t` plus
the counter-rotating `σ_z` contribution `(Ωd/ω)(sin(ωt+φ) − sin φ)`. The second term is the
observable error the RWA discards. -/
noncomputable def longitudinalExactAngle (ω₀ ω Ω φ d : ℝ) (t : ℝ) : ℝ :=
  (ω₀ - ω) / 2 * t + commutingDrivePhase ω Ω φ d t

/-- A `σ_z` rotation by angle `θ`, i.e. `exp(−i·θ·σ_z)`. -/
noncomputable def zRotation (θ : ℝ) : Matrix (Fin 2) (Fin 2) ℂ :=
  ((Real.cos θ : ℝ) : ℂ) • (1 : Matrix (Fin 2) (Fin 2) ℂ)
    - (Complex.I * ((Real.sin θ : ℝ) : ℂ)) • σ_z

/-- **The exact propagator for a diagonal drive at detuning**, in closed form: a global phase from
the identity component times a `σ_z` rotation whose angle carries the counter-rotating correction. -/
noncomputable def diagonalExactPropagator (ω₀ ω Ω φ a d : ℝ) (t : ℝ) :
    Matrix (Fin 2) (Fin 2) ℂ :=
  Complex.exp (-Complex.I * (commutingDrivePhase ω Ω φ a t : ℂ))
    • zRotation (longitudinalExactAngle ω₀ ω Ω φ d t)

@[simp] theorem zRotation_zero : zRotation 0 = 1 := by
  unfold zRotation; norm_num

@[simp] theorem diagonalExactPropagator_zero (ω₀ ω Ω φ a d : ℝ) :
    diagonalExactPropagator ω₀ ω Ω φ a d 0 = 1 := by
  unfold diagonalExactPropagator longitudinalExactAngle commutingDrivePhase
  norm_num

theorem longitudinalExactAngle_hasDerivAt (ω₀ ω Ω φ d : ℝ) (hω : ω ≠ 0) (t : ℝ) :
    HasDerivAt (longitudinalExactAngle ω₀ ω Ω φ d)
      ((ω₀ - ω) / 2 + Ω * d * Real.cos (ω * t + φ)) t := by
  have h1 : HasDerivAt (fun s : ℝ => (ω₀ - ω) / 2 * s) ((ω₀ - ω) / 2) t := by
    simpa using (hasDerivAt_id t).const_mul ((ω₀ - ω) / 2)
  exact h1.add (commutingDrivePhase_hasDerivAt ω Ω φ d hω t)

theorem zRotation_hasDerivAt (θ : ℝ → ℝ) (θ' : ℝ) (t : ℝ) (hθ : HasDerivAt θ θ' t) :
    HasDerivAt (fun s => zRotation (θ s))
      (((-Complex.I) * ((θ' : ℝ) : ℂ)) • (σ_z * zRotation (θ t))) t := by
  have hc : HasDerivAt (fun s : ℝ => Real.cos (θ s)) (-Real.sin (θ t) * θ') t :=
    (Real.hasDerivAt_cos (θ t)).comp t hθ
  have hs : HasDerivAt (fun s : ℝ => Real.sin (θ s)) (Real.cos (θ t) * θ') t :=
    (Real.hasDerivAt_sin (θ t)).comp t hθ
  have h1 := hc.ofReal_comp.smul_const (1 : Matrix (Fin 2) (Fin 2) ℂ)
  have h2 := (hs.ofReal_comp.const_mul Complex.I).smul_const σ_z
  have hval :
      ((-Real.sin (θ t) * θ' : ℝ) : ℂ) • (1 : Matrix (Fin 2) (Fin 2) ℂ)
        - (Complex.I * ((Real.cos (θ t) * θ' : ℝ) : ℂ)) • σ_z
      = ((-Complex.I) * ((θ' : ℝ) : ℂ)) • (σ_z * zRotation (θ t)) := by
    unfold zRotation
    have hzz : σ_z * σ_z = (1 : Matrix (Fin 2) (Fin 2) ℂ) := by
      ext i j
      fin_cases i <;> fin_cases j <;>
        simp [σ_z, Matrix.mul_apply, Fin.sum_univ_two]
    simp only [Matrix.mul_sub, Matrix.mul_smul, Matrix.mul_one, hzz, smul_sub, smul_smul]
    push_cast
    match_scalars <;> (ring_nf; try simp [Complex.I_sq])
  rw [← hval]
  exact h1.sub h2

/-- **The closed form solves the EXACT equation**, counter-rotating term included. -/
theorem diagonalExactPropagator_ode (ω₀ ω Ω φ a d : ℝ) (hω : ω ≠ 0) (t : ℝ) :
    HasDerivAt (diagonalExactPropagator ω₀ ω Ω φ a d)
      (((-Complex.I) • interactionHamiltonian ω₀ ω Ω φ a 0 0 d t)
        * diagonalExactPropagator ω₀ ω Ω φ a d t) t := by
  have hg := (commutingDrivePhase_hasDerivAt ω Ω φ a hω t).ofReal_comp
  have hph := (hg.const_mul (-Complex.I)).cexp
  have hz := zRotation_hasDerivAt (longitudinalExactAngle ω₀ ω Ω φ d)
    ((ω₀ - ω) / 2 + Ω * d * Real.cos (ω * t + φ)) t
    (longitudinalExactAngle_hasDerivAt ω₀ ω Ω φ d hω t)
  have hprod := hph.smul hz
  have hcr := counterRotating_diagonal ω Ω φ a d t
  have hrwa : rwaGenerator ω₀ ω Ω φ 0 0 = (((ω₀ - ω) / 2 : ℝ) : ℂ) • σ_z := by
    unfold rwaGenerator
    ext i j
    fin_cases i <;> fin_cases j <;> simp [σ_x, σ_y, σ_z]
  have hval :
      Complex.exp (-Complex.I * ((commutingDrivePhase ω Ω φ a t : ℝ) : ℂ))
          • (((-Complex.I) * (((ω₀ - ω) / 2 + Ω * d * Real.cos (ω * t + φ) : ℝ) : ℂ))
            • (σ_z * zRotation (longitudinalExactAngle ω₀ ω Ω φ d t)))
        + (Complex.exp (-Complex.I * ((commutingDrivePhase ω Ω φ a t : ℝ) : ℂ))
            * (-Complex.I * ((Ω * a * Real.cos (ω * t + φ) : ℝ) : ℂ)))
          • zRotation (longitudinalExactAngle ω₀ ω Ω φ d t)
      = ((-Complex.I) • interactionHamiltonian ω₀ ω Ω φ a 0 0 d t)
        * diagonalExactPropagator ω₀ ω Ω φ a d t := by
    unfold diagonalExactPropagator
    simp only [interactionHamiltonian_decomp, hcr, hrwa, smul_add, add_mul, Matrix.smul_mul,
      Matrix.mul_smul, Matrix.one_mul, smul_smul]
    push_cast
    module
  rw [← hval]
  exact hprod

/-- A `σ_z` rotation is unitary in the `ℓ^∞` operator norm: it is diagonal with unimodular
entries, so every row sums to `1`. -/
theorem norm_zRotation (θ : ℝ) : ‖zRotation θ‖ = 1 := by
  have hplus : ‖Complex.cos (θ : ℂ) + Complex.I * Complex.sin (θ : ℂ)‖ = 1 := by
    rw [show Complex.cos (θ : ℂ) + Complex.I * Complex.sin (θ : ℂ)
        = Complex.exp ((θ : ℂ) * Complex.I) by rw [Complex.exp_mul_I]; ring]
    simp [Complex.norm_exp]
  have hminus : ‖Complex.cos (θ : ℂ) - Complex.I * Complex.sin (θ : ℂ)‖ = 1 := by
    rw [show Complex.cos (θ : ℂ) - Complex.I * Complex.sin (θ : ℂ)
        = Complex.exp ((-θ : ℝ) * Complex.I) by
      push_cast; rw [Complex.exp_mul_I, Complex.cos_neg, Complex.sin_neg]; ring]
    simp [Complex.norm_exp]
  rw [zRotation, Matrix.linfty_opNorm_def,
    show (Finset.univ : Finset (Fin 2)) = {0, 1} from rfl, Finset.sup_insert,
    Finset.sup_singleton]
  simp [σ_z, Matrix.one_apply, hplus, hminus]

/-- For a purely diagonal drive the co-rotating propagator IS a `σ_z` rotation by `(Δ/2)·t`. -/
theorem rwaPropagator_diagonal (ω₀ ω Ω φ t : ℝ) (hdet : ω₀ ≠ ω) :
    rwaPropagator ω₀ ω Ω φ 0 0 t = zRotation ((ω₀ - ω) / 2 * t) := by
  have hk : rwaRate (ω₀ - ω) Ω 0 0 = |ω₀ - ω| / 2 := rwaRate_longitudinal _ _
  have hne : |ω₀ - ω| ≠ 0 := abs_ne_zero.mpr (sub_ne_zero.mpr hdet)
  have hΔC : ((ω₀ : ℂ) - (ω : ℂ)) ≠ 0 := by
    intro h
    exact hdet (by exact_mod_cast sub_eq_zero.mp h)
  have hgen : rwaGenerator ω₀ ω Ω φ 0 0 = (((ω₀ - ω) / 2 : ℝ) : ℂ) • σ_z := by
    unfold rwaGenerator
    ext i j
    fin_cases i <;> fin_cases j <;> simp [σ_x, σ_y, σ_z]
  have hangle : generalRotationAngle (ω₀ - ω) Ω 0 0 t = |ω₀ - ω| / 2 * t := by
    rw [generalRotationAngle_eq_rate_mul, hk]
  unfold rwaPropagator zRotation
  rw [hangle, hk, hgen, smul_smul]
  rcases abs_cases (ω₀ - ω) with ⟨habs, hsgn⟩ | ⟨habs, hsgn⟩
  · rw [habs]
    congr 2
    push_cast
    field_simp
  · rw [habs, show -(ω₀ - ω) / 2 * t = -((ω₀ - ω) / 2 * t) by ring,
      Real.cos_neg, Real.sin_neg]
    congr 2
    push_cast
    field_simp

theorem norm_rwaPropagator_diagonal (ω₀ ω Ω φ t : ℝ) (hdet : ω₀ ≠ ω) :
    ‖rwaPropagator ω₀ ω Ω φ 0 0 t‖ = 1 := by
  rw [rwaPropagator_diagonal ω₀ ω Ω φ t hdet, norm_zRotation]

theorem norm_diagonalExactPropagator (ω₀ ω Ω φ a d t : ℝ) :
    ‖diagonalExactPropagator ω₀ ω Ω φ a d t‖ = 1 := by
  unfold diagonalExactPropagator
  rw [norm_smul, norm_zRotation, Complex.norm_exp]
  simp

/-- `zRotation` is additive in the angle — `exp(−iθσ_z)` is a one-parameter group. -/
theorem zRotation_add (θ ψ : ℝ) : zRotation (θ + ψ) = zRotation θ * zRotation ψ := by
  have hzz : σ_z * σ_z = (1 : Matrix (Fin 2) (Fin 2) ℂ) := by
    ext i j
    fin_cases i <;> fin_cases j <;> simp [σ_z, Matrix.mul_apply, Fin.sum_univ_two]
  unfold zRotation
  rw [Real.cos_add, Real.sin_add]
  simp only [Matrix.sub_mul, Matrix.mul_sub, Matrix.smul_mul, Matrix.mul_smul, Matrix.one_mul,
    Matrix.mul_one, hzz]
  push_cast
  match_scalars <;> (ring_nf; try simp [Complex.I_sq]; try ring)

/-- **The exact propagator factors as `phase × extra σ_z rotation × U_rwa`.** The extra rotation
`zRotation (Φ_d t)` is the RWA error: it is what the co-rotating reduction discards, and unlike the
identity-drive case it is NOT a scalar. -/
theorem diagonalExactPropagator_factor (ω₀ ω Ω φ a d t : ℝ) (hdet : ω₀ ≠ ω) :
    diagonalExactPropagator ω₀ ω Ω φ a d t
      = Complex.exp (-Complex.I * ((commutingDrivePhase ω Ω φ a t : ℝ) : ℂ))
        • (zRotation (commutingDrivePhase ω Ω φ d t) * rwaPropagator ω₀ ω Ω φ 0 0 t) := by
  unfold diagonalExactPropagator longitudinalExactAngle
  rw [rwaPropagator_diagonal ω₀ ω Ω φ t hdet, ← zRotation_add, add_comm]

/-- With no `σ_z` drive component the counter-rotating phase is identically zero. -/
@[simp] theorem commutingDrivePhase_zero_coeff (ω Ω φ t : ℝ) :
    commutingDrivePhase ω Ω φ 0 t = 0 := by
  unfold commutingDrivePhase; ring

/-- **Observability forces a genuine `σ_z` drive.** So the applied bound below cannot be read at the
identity drive: `d = 0` makes the discarded factor identically `1`. -/
theorem d_ne_zero_of_observable (ω Ω φ d T : ℝ)
    (hobs : Real.sin (commutingDrivePhase ω Ω φ d T) ≠ 0) : d ≠ 0 := by
  intro h
  apply hobs
  rw [h, commutingDrivePhase_zero_coeff]
  simp

/-- **A `σ_z` rotation is not a global phase unless its angle is a multiple of `π`.** -/
theorem zRotation_not_scalar (θ : ℝ) (hsin : Real.sin θ ≠ 0) :
    ∀ c : ℂ, zRotation θ ≠ c • (1 : Matrix (Fin 2) (Fin 2) ℂ) := by
  intro c hcon
  apply hsin
  have h00 := congrFun (congrFun hcon 0) 0
  have h11 := congrFun (congrFun hcon 1) 1
  simp [zRotation, σ_z, Complex.ext_iff,
    -Complex.ofReal_cos, -Complex.ofReal_sin] at h00 h11
  linarith [h00.2, h11.2]

/-- **Bound on the exact interaction-picture generator** — `‖H_I‖ ≤ ‖H_RWA‖ + 2Ω·ℓ¹`. This is what
discharges the `Kq` constant of the propagator bound instead of exporting it. -/
theorem norm_interactionHamiltonian_le (ω₀ ω Ω φ a b c d s : ℝ) (hΩ : 0 ≤ Ω) :
    ‖(-Complex.I) • interactionHamiltonian ω₀ ω Ω φ a b c d s‖
      ≤ ‖Complex.I • rwaGenerator ω₀ ω Ω φ b c‖ + 2 * Ω * (|a| + |b| + |c| + |d|) := by
  have hI : ‖(-Complex.I) • interactionHamiltonian ω₀ ω Ω φ a b c d s‖
      = ‖interactionHamiltonian ω₀ ω Ω φ a b c d s‖ := by rw [norm_smul]; simp
  have hG : ‖Complex.I • rwaGenerator ω₀ ω Ω φ b c‖ = ‖rwaGenerator ω₀ ω Ω φ b c‖ := by
    rw [norm_smul]; simp
  have hsplit : ‖interactionHamiltonian ω₀ ω Ω φ a b c d s‖
      ≤ ‖rwaGenerator ω₀ ω Ω φ b c‖ + ‖counterRotating ω Ω φ a b c d s‖ := by
    rw [interactionHamiltonian_decomp]
    exact norm_add_le _ _
  have hV := norm_counterRotating_le ω Ω φ a b c d s hΩ
  rw [hI, hG]
  linarith

/-- **THE BOUND, APPLIED — every constant discharged, at an observably nondegenerate drive.**

The Bloch–Siegert propagator bound at the diagonal drive `a·1 + d·σ_z` with `d ≠ 0`:

* U_exact is `diagonalExactPropagator`, the closed-form solution of the EXACT equation
  (`diagonalExactPropagator_ode`, counter-rotating term included);
* **all five constants are computed, none exported**: the three propagator norms are exactly `1`
  (diagonal unitaries), `Kp = ‖i·H_RWA‖`, and `Kq` is discharged by
  `norm_interactionHamiltonian_le`;
* the **second** conjunct identifies the discarded RWA factor as `zRotation (Φ_d T)`
  (`diagonalExactPropagator_factor`) and the **third** says that factor is **not a global phase**
  — so unlike the identity-drive witness, the bounded error is an observable relative rotation.
  The identification is a conjunct rather than a docstring remark precisely so the two facts
  compose inside the statement. With `d = 0` that factor is identically `1`, which is the
  degeneracy this replaces. -/
theorem diagonal_drive_propagator_bound (ω₀ ω Ω φ a d T : ℝ)
    (hω : 0 < ω) (hΩ : 0 ≤ Ω) (hT : 0 ≤ T) (hdet : ω₀ ≠ ω)
    (hobs : Real.sin (commutingDrivePhase ω Ω φ d T) ≠ 0) :
    d ≠ 0
      ∧ diagonalExactPropagator ω₀ ω Ω φ a d T
          = Complex.exp (-Complex.I * ((commutingDrivePhase ω Ω φ a T : ℝ) : ℂ))
            • (zRotation (commutingDrivePhase ω Ω φ d T) * rwaPropagator ω₀ ω Ω φ 0 0 T)
      ∧ (∀ z : ℂ, zRotation (commutingDrivePhase ω Ω φ d T)
        ≠ z • (1 : Matrix (Fin 2) (Fin 2) ℂ))
      ∧ ‖diagonalExactPropagator ω₀ ω Ω φ a d T - rwaPropagator ω₀ ω Ω φ 0 0 T‖
        ≤ 1 * (1 * 1 * (2 * (Ω / ω) * (|a| + |0| + |0| + |d|))
          * (1 + T * (‖Complex.I • rwaGenerator ω₀ ω Ω φ 0 0‖
              + (‖Complex.I • rwaGenerator ω₀ ω Ω φ 0 0‖
                + 2 * Ω * (|a| + |0| + |0| + |d|))))) := by
  have hk : 0 < rwaRate (ω₀ - ω) Ω 0 0 := by
    rw [rwaRate_longitudinal]
    have : (0:ℝ) < |ω₀ - ω| := abs_pos.mpr (sub_ne_zero.mpr hdet)
    linarith
  refine ⟨d_ne_zero_of_observable ω Ω φ d T hobs,
    diagonalExactPropagator_factor ω₀ ω Ω φ a d T hdet,
    zRotation_not_scalar _ hobs, ?_⟩
  exact rwa_propagator_difference_bound_physical ω₀ ω Ω φ a 0 0 d T 1 1 1
    ‖Complex.I • rwaGenerator ω₀ ω Ω φ 0 0‖
    (‖Complex.I • rwaGenerator ω₀ ω Ω φ 0 0‖ + 2 * Ω * (|a| + |0| + |0| + |d|))
    hω hΩ hT hk (diagonalExactPropagator ω₀ ω Ω φ a d)
    (fun s => diagonalExactPropagator_ode ω₀ ω Ω φ a d hω.ne' s)
    (diagonalExactPropagator_zero ω₀ ω Ω φ a d)
    (by unfold diagonalExactPropagator zRotation longitudinalExactAngle commutingDrivePhase
        fun_prop)
    (fun s => (norm_rwaPropagator_diagonal ω₀ ω Ω φ (-s) hdet).le)
    (fun s => (norm_diagonalExactPropagator ω₀ ω Ω φ a d s).le)
    le_rfl (fun s => norm_interactionHamiltonian_le ω₀ ω Ω φ a 0 0 d s hΩ)
    (norm_rwaPropagator_diagonal ω₀ ω Ω φ T hdet).le

/-- **The nondegeneracy conditions, collected.** At nonzero detuning with a `σ_z` drive component,
all SEVEN conjuncts hold at once, and an exact solution exists in closed form:

1. the co-rotating rate is positive;
2. the co-rotating generator is nonzero (so `U_rwa` genuinely rotates);
3. the drive operator is **not** a multiple of the identity (so the drive is not a global phase);
4. the counter-rotating remainder is nonzero as a FUNCTION;
5. `U-exact(0) = 1`;
6. `U-exact` solves the EXACT interaction-picture equation, counter-rotating term included;
7. `U-exact` factors as `phase · zRotation (Φ_d t) · U_rwa(t)` at every `t`
   (`diagonalExactPropagator_factor`).

Conjunct 7 is what makes the RWA error a **relative rotation rather than a phase**: the discarded
factor is the `σ_z` rotation `zRotation (Φ_d t)`, which `commutingDrivePhase_zero_coeff` collapses
to `1` exactly when `d = 0`. Whether that rotation is itself observable at a GIVEN time is a
further condition (`sin (Φ_d T) ≠ 0`) and is NOT asserted here — it cannot be, since `Φ_d T` may
land on a multiple of `π` for particular `Ω`, `d`, `ω`, `φ`. It is carried as the explicit `hobs`
hypothesis of `diagonal_drive_propagator_bound`, which is where observability is established.

Contrast `rwa_propagator_difference_bound_inhabited`, whose difference is pure global phase.

⚠️ This theorem collects the *nondegeneracy facts*; it does **not** itself apply the bound (and its
binders `ω ≠ 0`, `Ω ≠ 0` are deliberately weaker than the bound's `0 < ω`, `0 ≤ Ω`). The bound is
actually applied in `diagonal_drive_propagator_bound` above, which discharges every constant. An
earlier version of this docstring claimed "every precondition of
`rwa_propagator_difference_bound_physical` is met" while calling nothing — corrected 2026-07-30; a
later version listed an observability bullet that was not among the conjuncts — corrected by adding
conjunct 7 and by naming where observability actually lives. -/
theorem diagonal_drive_nondegenerate_instantiation (ω₀ ω Ω φ a d : ℝ)
    (hω : ω ≠ 0) (hdet : ω₀ ≠ ω) (hΩ : Ω ≠ 0) (hd : d ≠ 0) :
    0 < rwaRate (ω₀ - ω) Ω 0 0
      ∧ rwaGenerator ω₀ ω Ω φ 0 0 ≠ 0
      ∧ driveOp a 0 0 d ≠ (a : ℂ) • (1 : Matrix (Fin 2) (Fin 2) ℂ)
      ∧ counterRotating ω Ω φ a 0 0 d ≠ 0
      ∧ diagonalExactPropagator ω₀ ω Ω φ a d 0 = 1
      ∧ (∀ t, HasDerivAt (diagonalExactPropagator ω₀ ω Ω φ a d)
          (((-Complex.I) • interactionHamiltonian ω₀ ω Ω φ a 0 0 d t)
            * diagonalExactPropagator ω₀ ω Ω φ a d t) t)
      ∧ ∀ t, diagonalExactPropagator ω₀ ω Ω φ a d t
          = Complex.exp (-Complex.I * ((commutingDrivePhase ω Ω φ a t : ℝ) : ℂ))
            • (zRotation (commutingDrivePhase ω Ω φ d t) * rwaPropagator ω₀ ω Ω φ 0 0 t) := by
  have hk : 0 < rwaRate (ω₀ - ω) Ω 0 0 := by
    rw [rwaRate_longitudinal]
    have : (0:ℝ) < |ω₀ - ω| := abs_pos.mpr (sub_ne_zero.mpr hdet)
    linarith
  refine ⟨hk, rwaGenerator_longitudinal_ne_zero ω₀ ω Ω φ hdet, ?_, ?_,
    diagonalExactPropagator_zero ω₀ ω Ω φ a d,
    fun t => diagonalExactPropagator_ode ω₀ ω Ω φ a d hω t,
    fun t => diagonalExactPropagator_factor ω₀ ω Ω φ a d t hdet⟩
  · intro hz
    have h := congrFun (congrFun hz 1) 1
    unfold driveOp at h
    simp [σ_x, σ_y, σ_z, Complex.ext_iff] at h
    exact hd h
  · -- function-level: evaluate at `t = −φ/ω`, where `cos(ωt+φ) = 1`. No hypothesis on `φ`.
    intro hz
    have hpt := congrFun hz (-φ / ω)
    rw [counterRotating_diagonal] at hpt
    have hcos : ω * (-φ / ω) + φ = 0 := by field_simp; ring
    rw [hcos, Real.cos_zero, mul_one] at hpt
    simp only [Pi.zero_apply] at hpt
    rcases smul_eq_zero.mp hpt with h | h
    · exact hΩ (by exact_mod_cast h)
    · have h00 := congrFun (congrFun h 0) 0
      have h11 := congrFun (congrFun h 1) 1
      simp [σ_z, Complex.ext_iff] at h00 h11
      exact hd (by linarith [h00, h11])


end

end SKEFTHawking.Control
