#!/usr/bin/env python3
"""
aristotle_usage_by_bundle.py — register-driven Aristotle-clause applicability
=============================================================================

Deterministically derives, for each of the 18 publication bundles
(`F`, `D1`–`D9`, `L1`–`L3`, `I1`–`I3`, `E1`, `E2`), whether the bundle's
content used Aristotle-proved theorems. The result selects which AI-disclosure
variant each bundle carries (see `docs/DISCLOSURE_TEXT.md`): bundles with
`aristotle_used = yes` include the conditional Aristotle sentence; bundles
with `no` omit it. User decision 2026-06-10: "the register differentiates."

Registers consumed (all canonical, no free parameters):

1. `ARISTOTLE_THEOREMS` (`src/core/constants.py`) — theorem name → Aristotle
   run id. Pipeline Invariant #2: constants.py is the only place the Aristotle
   registry lives.
2. `PAPER_DEPENDENCIES` (`src/core/provenance.py`) — per-paper declared Lean
   modules (short names, e.g. 'AcousticMetric').
3. `docs/PAPER_DRAFT_MAPPING.md` — per-paper → bundle assignment (Pipeline
   Invariant #14), parsed via the existing `scripts/bundle_migration.py`
   `parse_mapping` (reused, not reimplemented).
4. `lean/lean_deps.json` — declaration → module resolution (regenerated by
   ExtractDeps; used to map each ARISTOTLE_THEOREMS key to its Lean module).

Algorithm
---------
For each bundle B, two deterministic register-driven signals:

S1 (declared-module intersection):
  modules(B) = union over source papers P of B (per PAPER_DRAFT_MAPPING.md)
               of PAPER_DEPENDENCIES[P]['lean_modules'],
               + BUNDLE_EXTRA_LEAN_MODULES[B] (bundle-level declarations;
               empty today — checked 2026-06-10: neither PAPER_DEPENDENCIES,
               bundle_metadata.json, nor source_manifest.md declares
               bundle-level Lean modules).
  aristotle_modules = { module(t) : t in ARISTOTLE_THEOREMS }
  S1(B) = modules(B) ∩ aristotle_modules ≠ ∅

S2 (draft names an Aristotle-proved theorem):
  S2(B) = the bundle's papers/<B>/paper_draft.tex (TeX comments stripped,
          TeX-escaped underscores normalized) contains ≥1 ARISTOTLE_THEOREMS
          key as a whole word.

  aristotle_used(B) = S1(B) or S2(B)

S2 exists because PAPER_DEPENDENCIES declares Lean modules for only a
subset of mapped source papers (16 of 72 mapping rows as of 2026-06-10);
bundle drafts are themselves first-class content artifacts, and a draft
that names an Aristotle-proved theorem uses it regardless of what its
source papers declared (live examples: I1 discusses `firstOrder_uniqueness`
as methodology subject matter; I2 names 8 Aristotle-closed estimator/fusion
theorems). Both signals are computed purely from the ARISTOTLE_THEOREMS
register — no judgment calls enter the verdict.

Theorem → module resolution (3 tiers, all deterministic):
  T1: exact match on the last dotted component of a lean_deps declaration
      name (e.g. 'acousticMetric_det' → SKEFTHawking.AcousticMetric).
  T2: underscore-flattened prefix match for instance-obligation registry
      names (e.g. 'DG_instRing_left_distrib' ← SKEFTHawking.DG.instRing in
      SKEFTHawking.DrinfeldDoubleRing). Longest flattened prefix wins.
  T3: literal source grep over lean/SKEFTHawking/**/*.lean (catches names
      that were absorbed/renamed but remain documented in their module,
      e.g. 'fock_space_finite_dim' in GoltermanShamir.lean).
Unresolved names (none as of 2026-06-10) are reported and treated as
non-witnessing.

Advisory column
---------------
`draft_mentions` counts non-comment occurrences of "Aristotle" in
`papers/<bundle>/paper_draft.tex`. It does NOT enter the canonical
`aristotle_used` decision; it exists so the attribution-content sweep's
per-bundle visit can spot prose that discusses the Aristotle layer in a
bundle whose register-derived flag is `no` (e.g. I1, the methodology
bundle, describes the Aristotle integration as subject matter). The sweep
visit resolves such cases per the applicability rule in
`docs/DISCLOSURE_TEXT.md` §2.

Usage
-----
    uv run python scripts/aristotle_usage_by_bundle.py            # text table
    uv run python scripts/aristotle_usage_by_bundle.py --json     # JSON
    uv run python scripts/aristotle_usage_by_bundle.py --verbose  # + witnesses
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from collections import defaultdict
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))
sys.path.insert(0, str(PROJECT_ROOT / "scripts"))

from src.core.constants import ARISTOTLE_THEOREMS          # noqa: E402
from src.core.provenance import PAPER_DEPENDENCIES          # noqa: E402
from bundle_migration import parse_mapping, MAPPING_DOC     # noqa: E402

LEAN_DEPS_PATH = PROJECT_ROOT / "lean" / "lean_deps.json"
LEAN_SRC_DIR = PROJECT_ROOT / "lean" / "SKEFTHawking"
PAPERS_DIR = PROJECT_ROOT / "papers"

ALL_BUNDLES = [
    "F", "D1", "D2", "D3", "D4", "D5", "D6", "D7", "D8", "D9",
    "L1", "L2", "L3", "I1", "I2", "I3", "E1", "E2",
]

# Bundle-level Lean-module declarations beyond what source papers declare via
# PAPER_DEPENDENCIES. Empty as of 2026-06-10 (no register carries bundle-level
# Lean dependency declarations; this is the documented extension point — add
# entries here if a future bundle declares Lean modules with no per-paper
# source, and record the authority in the entry's comment).
BUNDLE_EXTRA_LEAN_MODULES: dict[str, list[str]] = {}


# ────────────────────────────────────────────────────────────────────────────
# Theorem → module resolution
# ────────────────────────────────────────────────────────────────────────────

def load_lean_deps() -> list[dict]:
    with open(LEAN_DEPS_PATH, encoding="utf-8") as f:
        return json.load(f)


def resolve_theorem_modules(
    lean_deps: list[dict],
) -> tuple[dict[str, set[str]], list[str]]:
    """Map every ARISTOTLE_THEOREMS key to the set of Lean modules declaring it.

    Returns (theorem → set of full module names, unresolved theorem names).
    """
    # T1 index: last dotted component → [(full name, module)]
    last_comp: dict[str, list[tuple[str, str]]] = defaultdict(list)
    # T2 index: flattened (dots→underscores, SKEFTHawking. prefix stripped)
    #           declaration name → module
    flattened: dict[str, str] = {}
    for e in lean_deps:
        name, module = e["name"], e["module"]
        last_comp[name.split(".")[-1]].append((name, module))
        short = name.removeprefix("SKEFTHawking.")
        flattened[short.replace(".", "_")] = module

    resolved: dict[str, set[str]] = {}
    unresolved: list[str] = []
    for thm in ARISTOTLE_THEOREMS:
        mods: set[str] = set()
        # T1 — exact last-component match
        for _full, module in last_comp.get(thm, []):
            mods.add(module)
        # T2 — longest flattened-prefix match (instance-obligation names)
        if not mods:
            best: tuple[int, str] | None = None
            for flat, module in flattened.items():
                if thm == flat or thm.startswith(flat + "_"):
                    if best is None or len(flat) > best[0]:
                        best = (len(flat), module)
            if best is not None:
                mods.add(best[1])
        # T3 — literal source grep fallback
        if not mods:
            token = re.compile(rf"\b{re.escape(thm)}\b")
            for lean_file in sorted(LEAN_SRC_DIR.rglob("*.lean")):
                if token.search(lean_file.read_text(encoding="utf-8",
                                                    errors="replace")):
                    rel = lean_file.relative_to(LEAN_SRC_DIR.parent)
                    mods.add(str(rel.with_suffix("")).replace("/", "."))
        if mods:
            resolved[thm] = mods
        else:
            unresolved.append(thm)
    return resolved, unresolved


# ────────────────────────────────────────────────────────────────────────────
# Bundle module sets
# ────────────────────────────────────────────────────────────────────────────

def bundle_source_papers() -> dict[str, list[str]]:
    """bundle → sorted list of source paper keys (from PAPER_DRAFT_MAPPING)."""
    mapping = parse_mapping(MAPPING_DOC.read_text(encoding="utf-8"))
    out: dict[str, list[str]] = {b: [] for b in ALL_BUNDLES}
    for paper, info in sorted(mapping.items()):
        for b in info["bundle_destinations"]:
            if b in out:
                out[b].append(paper)
    return out


def bundle_declared_modules(
    sources: dict[str, list[str]],
) -> dict[str, set[str]]:
    """bundle → set of declared Lean module SHORT names (papers + extras)."""
    out: dict[str, set[str]] = {b: set() for b in ALL_BUNDLES}
    for b, papers in sources.items():
        for p in papers:
            dep = PAPER_DEPENDENCIES.get(p)
            if dep:
                out[b].update(dep.get("lean_modules", []))
        out[b].update(BUNDLE_EXTRA_LEAN_MODULES.get(b, []))
    return out


def expand_short_modules(
    short_names: set[str], lean_deps: list[dict]
) -> set[str]:
    """Short module names → full module names (match on last component)."""
    by_last: dict[str, set[str]] = defaultdict(set)
    for e in lean_deps:
        m = e["module"]
        by_last[m.split(".")[-1]].add(m)
    full: set[str] = set()
    for s in short_names:
        full.update(by_last.get(s, set()))
    return full


def _draft_text(bundle: str) -> str:
    """Bundle draft with TeX comments stripped; '' if no draft exists."""
    tex = PAPERS_DIR / bundle / "paper_draft.tex"
    if not tex.exists():
        return ""
    raw = tex.read_text(encoding="utf-8", errors="replace")
    return "\n".join(line.split("%", 1)[0] for line in raw.splitlines())


def draft_mention_count(text: str) -> int:
    """Non-comment 'Aristotle' occurrences in the bundle's draft (advisory)."""
    return len(re.findall(r"aristotle", text, flags=re.IGNORECASE))


def draft_named_theorems(text: str) -> list[str]:
    """S2: ARISTOTLE_THEOREMS keys named (whole-word) in the bundle draft."""
    norm = text.replace("\\_", "_")
    return sorted(
        t for t in ARISTOTLE_THEOREMS
        if re.search(rf"\b{re.escape(t)}\b", norm)
    )


# ────────────────────────────────────────────────────────────────────────────
# Main derivation
# ────────────────────────────────────────────────────────────────────────────

def derive() -> dict:
    lean_deps = load_lean_deps()
    thm_modules, unresolved = resolve_theorem_modules(lean_deps)
    aristotle_modules: set[str] = set()
    for mods in thm_modules.values():
        aristotle_modules.update(mods)

    sources = bundle_source_papers()
    declared_short = bundle_declared_modules(sources)

    bundles: dict[str, dict] = {}
    for b in ALL_BUNDLES:
        full = expand_short_modules(declared_short[b], lean_deps)
        witnesses = sorted(full & aristotle_modules)
        wit_thms = sorted(
            t for t, mods in thm_modules.items() if mods & set(witnesses)
        )
        text = _draft_text(b)
        named = draft_named_theorems(text)
        bundles[b] = {
            "aristotle_used": bool(witnesses) or bool(named),
            "s1_module_intersection": bool(witnesses),
            "s2_draft_names_theorem": bool(named),
            "witness_modules": witnesses,
            "witness_theorem_count": len(wit_thms),
            "witness_theorems": wit_thms,
            "draft_named_theorems": named,
            "declared_modules": sorted(declared_short[b]),
            "source_papers": sources[b],
            "draft_mentions": draft_mention_count(text),
        }

    return {
        "registers": {
            "aristotle_theorems": len(ARISTOTLE_THEOREMS),
            "aristotle_theorems_resolved": len(thm_modules),
            "aristotle_theorems_unresolved": sorted(unresolved),
            "aristotle_modules": sorted(aristotle_modules),
            "paper_dependencies_entries": len(PAPER_DEPENDENCIES),
            "mapping_doc": str(MAPPING_DOC.relative_to(PROJECT_ROOT)),
        },
        "bundles": bundles,
    }


def print_table(result: dict, verbose: bool = False) -> None:
    reg = result["registers"]
    print("Aristotle-clause applicability by bundle (register-derived)")
    print(f"  ARISTOTLE_THEOREMS: {reg['aristotle_theorems']} "
          f"({reg['aristotle_theorems_resolved']} resolved to "
          f"{len(reg['aristotle_modules'])} modules; "
          f"unresolved: {reg['aristotle_theorems_unresolved'] or 'none'})")
    print(f"  Mapping: {reg['mapping_doc']} | "
          f"PAPER_DEPENDENCIES: {reg['paper_dependencies_entries']} papers")
    print()
    hdr = (f"{'bundle':<7} {'aristotle_used':<15} {'S1_modules':<11} "
           f"{'S2_named':<9} {'witness_modules':<16} "
           f"{'witness_theorems':<17} {'draft_mentions':<14}")
    print(hdr)
    print("-" * len(hdr))
    for b in ALL_BUNDLES:
        info = result["bundles"][b]
        print(f"{b:<7} {'yes' if info['aristotle_used'] else 'no':<15} "
              f"{'yes' if info['s1_module_intersection'] else 'no':<11} "
              f"{'yes' if info['s2_draft_names_theorem'] else 'no':<9} "
              f"{len(info['witness_modules']):<16} "
              f"{info['witness_theorem_count']:<17} "
              f"{info['draft_mentions']:<14}")
    print()
    n_yes = sum(1 for b in ALL_BUNDLES
                if result["bundles"][b]["aristotle_used"])
    print(f"Summary: {n_yes}/{len(ALL_BUNDLES)} bundles carry the Aristotle "
          f"clause (variant A of docs/DISCLOSURE_TEXT.md); "
          f"{len(ALL_BUNDLES) - n_yes} carry variant B.")
    advisory = [b for b in ALL_BUNDLES
                if not result["bundles"][b]["aristotle_used"]
                and result["bundles"][b]["draft_mentions"] > 0]
    if advisory:
        print(f"Advisory: verdict 'no' but draft mentions Aristotle "
              f"(stale ad-hoc blurb to normalize during the sweep visit): "
              f"{', '.join(advisory)} — see DISCLOSURE_TEXT.md §3.")
    if verbose:
        print()
        for b in ALL_BUNDLES:
            info = result["bundles"][b]
            if info["witness_modules"]:
                print(f"{b}: S1 witnesses {info['witness_modules']}")
            if info["draft_named_theorems"]:
                print(f"{b}: S2 named {info['draft_named_theorems']}")


def main() -> int:
    ap = argparse.ArgumentParser(
        description="Register-driven Aristotle-clause applicability per bundle"
    )
    ap.add_argument("--json", action="store_true",
                    help="emit machine-readable JSON instead of the table")
    ap.add_argument("--verbose", action="store_true",
                    help="also print witnessing modules per bundle")
    args = ap.parse_args()

    result = derive()
    if args.json:
        # witness_theorems can be long; keep full fidelity in JSON mode.
        print(json.dumps(result, indent=2, sort_keys=True))
    else:
        print_table(result, verbose=args.verbose)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
