#!/usr/bin/env python3
"""
bundle_readiness.py — Phase 6i Wave 7.4 per-bundle Stage-13 readiness summary
=============================================================================

Aggregates the existing per-paper Stage-13 review findings (extracted by
`scripts/build_graph.py:extract_review_finding_nodes`) by bundle, using
the per-paper → per-bundle assignment from
`docs/PAPER_DRAFT_MAPPING.md`. Produces:

  1. `papers/AutomatedReviews/<DATE>-bundle-stage13/<bundle>.md` per
     bundle — a readiness summary aggregating per-paper findings,
     classifying each finding by bundle scope (intra-bundle vs cross-
     bundle), and listing the bundle's anchor coverage.
  2. `docs/BUNDLE_READINESS_HEATMAP.md` — the N-gate × 21-bundle
     heatmap (the bundle-aware analog of the pre-existing
     `READINESS_GATES.md`).

This script does NOT run a fresh-context LLM-driven Stage-13 review —
that is a user-triggered downstream step per memory
`feedback_stages_11_13_reflexive.md`. The aggregation here lifts the
already-existing per-paper review findings into per-bundle summaries
so the user can see at a glance which bundles are submission-ready.

S5 closure (2026-06-10, user-authorized)
----------------------------------------
The 2026-06-05 external review flagged failure class S5: the heatmap
rendered GREEN for bundles that had never received a fresh-context
Stage-13 review — "no findings recorded" is not "reviewed and passed".
Semantics now enforced here:

  * GREEN requires 0 blockers AND ≤5 open advisories AND a RECORDED
    fresh-context Stage-13 review for the bundle.
  * 0-blockers-but-never-reviewed renders as "YELLOW (unreviewed)".
  * Review-recordedness resolution order:
      (a) `papers/<X>/bundle_metadata.json` `last_stage13_review`
          (ISO timestamp, non-null);
      (b) else DERIVED from on-disk review evidence — the newest dated
          genuine fresh-context review document for the bundle under
          `papers/AutomatedReviews/` (or a full-bundle audit doc
          `docs/audits/stage13_<X>_fullbundle_<date>.md`) — and
          BACKFILLED into the metadata together with a
          `last_stage13_review_source` audit-trail note. Evidence-based
          backfill only — never fabricated. Files generated by THIS
          script (aggregation summaries) carry a footer marker and are
          excluded from evidence; so are stage-9/10 artifacts
          (`*figures*`/`*claims*`) and section-/phase-scoped audit docs
          (`docs/audits/stage13_phase6XX_*.md` — a section-level review
          is NOT a full-bundle fresh review).
      (c) else the bundle is unreviewed → YELLOW (unreviewed).
  * Review dates are surfaced in the heatmap to expose staleness;
    re-review obligations after substantive edits are governed by the
    Stage-13 re-invocation rule (WAVE_EXECUTION_PIPELINE.md Stage 13)
    and the late-absorption Stage-F re-review mandate
    (LATE_PHASE6_ABSORPTION_PROTOCOL.md). No edit-date comparison is
    performed here.

Usage
-----
    uv run python scripts/bundle_readiness.py             # generate everything
    uv run python scripts/bundle_readiness.py --bundle L1 # one bundle only
    uv run python scripts/bundle_readiness.py --heatmap   # only heatmap
    uv run python scripts/bundle_readiness.py --json      # read-only dump
                                                          # (no backfill)
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from collections import Counter, defaultdict
from datetime import datetime, timezone
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
PAPERS_DIR = PROJECT_ROOT / "papers"
REVIEWS_DIR = PAPERS_DIR / "AutomatedReviews"
AUDITS_DIR = PROJECT_ROOT / "docs" / "audits"
HEATMAP_PATH = PROJECT_ROOT / "docs" / "BUNDLE_READINESS_HEATMAP.md"

# Footer marker present in every aggregation file THIS script writes.
# Files carrying it are not fresh-context reviews and never count as
# review-recordedness evidence.
AGGREGATION_MARKER = "Generated by `scripts/bundle_readiness.py`"

# Directory-name date prefix: 2026-05-01, 2026-05-01-1345, 2026-05-01-T1830
_DIR_DATE_RE = re.compile(r"^(\d{4}-\d{2}-\d{2})(?:-T?(\d{3,4}))?")

# Plain full-bundle stage13_status enum values per BUNDLE_DIRECTORY_SCHEMA.md.
# Anything else (e.g. D6's "green_phase6AA_section (...)") is a freeform
# caveat string and is surfaced verbatim in the heatmap.
_PLAIN_STAGE13_STATUSES = {"pending", "green", "yellow", "red", ""}

sys.path.insert(0, str(PROJECT_ROOT / "scripts"))
from bundle_migration import parse_mapping, MAPPING_DOC  # noqa: E402
from sentence_state import _VALID_BUNDLE_TARGETS  # noqa: E402

# Roster metadata from THE source of truth (scripts/bundle_registry.py).
# Until the 2026-07-30 consolidation `write_heatmap()` carried its OWN
# `bundle_order` + `tier_map` literals — which stopped at D9 while this module
# already imported the full roster three lines up. The heatmap therefore
# rendered 19 of 21 bundles while looking complete: the omitted codes were
# skipped by `by_bundle.get(b, {})`, so nothing errored.
from bundle_registry import (  # noqa: E402
    BUNDLE_CODES as _BUNDLE_ORDER,
    TIER_OF as _TIER_OF,
)


def load_findings_by_paper() -> dict[str, list[dict]]:
    """Pull current ReviewFinding nodes via build_graph and partition
    by paper."""
    from build_graph import extract_review_finding_nodes
    from qi_register import classify_finding

    findings = extract_review_finding_nodes()
    by_paper: dict[str, list[dict]] = defaultdict(list)
    for f in findings:
        m = f.get("meta", {}) or {}
        # ⚠️ FALLBACK ADDED 2026-07-31 (D11 Stage-13 round-5 BLOCKER 4.1, second
        # layer). Bundle-era reviews are named after their bundle code, carry
        # `inferred_bundle`, and have NO `inferred_paper`. Partitioning on
        # `inferred_paper` alone therefore dropped every bundle-era finding on
        # the floor, and the heatmap reported `Blockers 0 / GREEN` for bundles
        # holding dozens of open criticals — a FALSE GREEN, strictly worse than
        # the "YELLOW (unreviewed)" it replaced. D11 alone had 40 findings
        # (6 critical, 11 major) invisible here.
        paper = m.get("inferred_paper") or m.get("inferred_bundle")
        if not paper:
            continue
        by_paper[paper].append({
            "id": f["id"],
            "label": f["label"],
            "gate": classify_finding(f),
            "severity": m.get("severity", "advisory"),
            "status": m.get("status", "open"),
            "review_date": m.get("review_date", ""),
            "review_file": m.get("review_file", ""),
        })
    return dict(by_paper)


def _bundle_metadata_path(bundle: str) -> Path:
    return PAPERS_DIR / bundle / "bundle_metadata.json"


def find_stage13_review_evidence(bundle: str) -> tuple[str, str] | None:
    """Newest genuine fresh-context Stage-13 review evidence for a bundle.

    Returns ``(date "YYYY-MM-DD", path-relative-to-project)`` or ``None``.

    Evidence sources (S5-closure resolution-order step (b)):

    1. ``papers/AutomatedReviews/<dated dir>/<bundle>[-_suffix].md`` where
       the directory name contains ``bundle-stage13`` or
       ``internal-adversarial``. Excluded: files written by this script
       (``AGGREGATION_MARKER`` footer) and stage-9/10 artifacts (filename
       contains ``figure``/``claims``).
    2. ``docs/audits/stage13_<bundle>_fullbundle_<date>.md`` — the
       Phase-6AA-era location for consolidated full-bundle paper-layer
       Stage-13 reviews. Section-/phase-scoped audit docs
       (``stage13_phase6XX_*.md``) deliberately do NOT match: a
       section-level review is not a full-bundle fresh review.
    """
    file_re = re.compile(rf"^{re.escape(bundle)}([-_][A-Za-z0-9-]+)?\.md$")
    candidates: list[tuple[tuple[str, str, str, str], str, str]] = []

    if REVIEWS_DIR.is_dir():
        for d in REVIEWS_DIR.iterdir():
            if not d.is_dir():
                continue
            name = d.name
            if "bundle-stage13" not in name and "internal-adversarial" not in name:
                continue
            m = _DIR_DATE_RE.match(name)
            if not m:
                continue
            date, hhmm = m.group(1), (m.group(2) or "0000")
            for f in sorted(d.iterdir()):
                if not f.is_file() or not file_re.match(f.name):
                    continue
                low = f.name.lower()
                if "figure" in low or "claims" in low:
                    continue  # stage-9/10 artifact, not a Stage-13 review
                try:
                    if AGGREGATION_MARKER in f.read_text(errors="replace"):
                        continue  # this script's own aggregation output
                except OSError:
                    continue
                rel = str(f.relative_to(PROJECT_ROOT))
                candidates.append(((date, hhmm, name, f.name), date, rel))

    audit_re = re.compile(
        rf"^stage13_{re.escape(bundle)}_fullbundle_(\d{{4}}-\d{{2}}-\d{{2}})\.md$"
    )
    if AUDITS_DIR.is_dir():
        for f in AUDITS_DIR.iterdir():
            m = audit_re.match(f.name)
            if not m:
                continue
            date = m.group(1)
            rel = str(f.relative_to(PROJECT_ROOT))
            candidates.append(((date, "0000", "docs-audits", f.name), date, rel))

    if not candidates:
        return None
    _, date, rel = max(candidates, key=lambda c: c[0])
    return date, rel


def resolve_stage13_reviews(*, backfill: bool) -> dict[str, dict]:
    """Resolve per-bundle Stage-13 review-recordedness (S5 closure).

    Resolution order per bundle:
      (a) ``bundle_metadata.json.last_stage13_review`` non-null → recorded;
      (b) else newest on-disk genuine review evidence
          (``find_stage13_review_evidence``) → recorded; when
          ``backfill=True`` the date is written back into the metadata
          together with a ``last_stage13_review_source`` audit note
          (evidence-based backfill only — never fabricated);
      (c) else unreviewed (``date`` stays ``None``).

    Returns ``{bundle: {"date", "source", "backfilled", "status_caveat",
    "backfilled_this_run"}}``.
    """
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    out: dict[str, dict] = {}
    for b in sorted(_VALID_BUNDLE_TARGETS):
        rec = {
            "date": None,
            "source": None,
            "backfilled": False,
            "backfilled_this_run": False,
            "status_caveat": None,
        }
        md_path = _bundle_metadata_path(b)
        md: dict | None = None
        if md_path.is_file():
            try:
                md = json.loads(md_path.read_text())
            except (OSError, json.JSONDecodeError):
                md = None
        if md is not None:
            raw_status = str(md.get("stage13_status") or "")
            if raw_status not in _PLAIN_STAGE13_STATUSES:
                rec["status_caveat"] = raw_status

        if md is not None and md.get("last_stage13_review"):
            rec["date"] = str(md["last_stage13_review"])[:10]
            src = md.get("last_stage13_review_source")
            rec["source"] = src or "bundle_metadata"
            rec["backfilled"] = bool(src) and str(src).startswith("backfilled")
        else:
            ev = find_stage13_review_evidence(b)
            if ev is not None:
                date, rel = ev
                origin = (
                    "backfilled-from-AutomatedReviews"
                    if rel.startswith("papers/AutomatedReviews")
                    else "backfilled-from-audit-doc"
                )
                note = f"{origin} {rel} {today}"
                rec.update({"date": date, "source": note, "backfilled": True})
                if backfill and md is not None:
                    md["last_stage13_review"] = date
                    md["last_stage13_review_source"] = note
                    md_path.write_text(json.dumps(md, indent=2) + "\n")
                    rec["backfilled_this_run"] = True
        out[b] = rec
    return out


def _blocked_p1_gates_by_paper() -> dict[str, list[str]]:
    """Bundle/paper key -> names of its BLOCKED priority-1 ReadinessGates.

    Added 2026-07-31 (self-audit, corroborated by D12 Stage-13 round-7 finding 8.2).
    This module's verdict is computed from review findings ONLY, so it cannot see the
    gates that are not finding-derived (NarrativeGrounding, ComputationCorrectness,
    CitationIntegrity, …). It was therefore issuing 🟢 GREEN — the verdict a reader
    takes as "ready" — for bundles whose P1 gates were blocked: D6 and D10 were both
    live instances. Neither subsystem was lying about its own inputs; the heatmap
    simply had no obligation to agree with the gate, which is exactly the shape of the
    round-6 8.1 defect one layer over.

    Returns an empty mapping (never raises) if the graph is unavailable, and callers
    treat that as "no downgrade" — the graph is already a hard dependency of
    `load_findings_by_paper`, so an outage there fails loudly upstream.
    """
    try:
        from readiness_gates import evaluate_all_gates
        from build_graph import build_graph_json
        out: dict[str, list[str]] = {}
        for r in evaluate_all_gates(build_graph_json()):
            if r.state == "blocked" and r.priority == 1:
                out.setdefault(r.paper, []).append(r.gate)
        return out
    except Exception:
        return {}


def aggregate_by_bundle(
    assignments: dict[str, dict],
    findings_by_paper: dict[str, list[dict]],
    review_info: dict[str, dict] | None = None,
) -> dict[str, dict]:
    """For each bundle code, aggregate all findings from its source
    papers + collect bundle-level statistics.

    ``review_info`` is the output of :func:`resolve_stage13_reviews`;
    when omitted it is resolved read-only (no metadata backfill), so
    external callers (``scripts/datastar_bundles.py``) keep the original
    two-argument signature and still get S5-closure verdict semantics.
    """
    if review_info is None:
        review_info = resolve_stage13_reviews(backfill=False)

    blocked_p1 = _blocked_p1_gates_by_paper()

    by_bundle: dict[str, dict] = {}
    for b in _VALID_BUNDLE_TARGETS:
        sources = [p for p, a in assignments.items()
                   if b in a["bundle_destinations"]]
        all_findings = []
        # ⚠️ The bundle's OWN key must be included alongside its source papers
        # (added 2026-07-31, D11 Stage-13 round-5 BLOCKER 4.1, third layer).
        # Bundle-era Stage-13 findings are keyed by the bundle code, not by any
        # source paper — and for bundles whose only mapping sources are synthesis
        # stubs there are no source papers at all. Iterating `sources` alone
        # therefore collected ZERO findings and rendered 🟢 GREEN / Blockers 0
        # for bundles carrying dozens of open criticals.
        for p in ([b] + list(sources)):
            for f in findings_by_paper.get(p, []):
                f_copy = dict(f)
                f_copy["paper"] = p
                all_findings.append(f_copy)

        # Open findings only (closed via supersession ledger no longer count)
        open_findings = [f for f in all_findings if f.get("status") == "open"]

        # Severity breakdown of open findings
        sev_counter = Counter(f["severity"] for f in open_findings)
        # Gate breakdown
        gate_counter = Counter(f["gate"] for f in open_findings)

        # Critical / blocker count = severity in {critical, major}
        n_blockers = sum(sev_counter[s] for s in ("critical", "major"))

        rev = review_info.get(b, {}) or {}
        review_recorded = bool(rev.get("date"))

        # Stage-13 readiness verdict (S5 closure 2026-06-10): GREEN
        # additionally requires a RECORDED fresh-context Stage-13 review.
        # "No findings recorded" != "reviewed and passed".
        if n_blockers > 0:
            readiness, readiness_display = "RED", "RED"
        elif not review_recorded:
            readiness, readiness_display = "YELLOW", "YELLOW (unreviewed)"
        elif len(open_findings) > 5:
            readiness, readiness_display = "YELLOW", "YELLOW"
        else:
            readiness, readiness_display = "GREEN", "GREEN"

        # GREEN must survive every P1 gate, not only the finding-derived ones.
        gate_block = sorted(blocked_p1.get(b, []))
        if readiness == "GREEN" and gate_block:
            readiness = "YELLOW"
            readiness_display = f"YELLOW (P1 gate blocked: {', '.join(gate_block)})"

        by_bundle[b] = {
            "sources": sorted(sources),
            "source_count": len(sources),
            "total_findings": len(all_findings),
            "open_findings": len(open_findings),
            "severity_mix": dict(sev_counter),
            "gate_mix": dict(gate_counter),
            "blocker_count": n_blockers,
            "readiness": readiness,
            "readiness_display": readiness_display,
            "review_recorded": review_recorded,
            "stage13_review_date": rev.get("date"),
            "stage13_review_source": rev.get("source"),
            "stage13_review_backfilled": bool(rev.get("backfilled")),
            "stage13_status_caveat": rev.get("status_caveat"),
            "blocked_p1_gates": gate_block,
            "open_finding_ids": [f["id"] for f in open_findings[:10]],
        }
    return by_bundle


def write_bundle_review_doc(
    bundle: str,
    info: dict,
    out_dir: Path,
) -> Path:
    """Write papers/AutomatedReviews/<DATE>-bundle-stage13/<bundle>.md."""
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / f"{bundle}.md"

    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    sources_lines = (
        "\n".join(f"- `papers/{s}/paper_draft.tex`" for s in info["sources"])
        or "_(no source papers assigned)_"
    )

    sev_lines = ", ".join(f"{v} {k}" for k, v in
                          sorted(info["severity_mix"].items())) or "_(none)_"
    gate_lines = ", ".join(f"{v} {k}" for k, v in
                           sorted(info["gate_mix"].items())) or "_(none)_"

    open_ids_block = (
        "\n".join(f"- `{i}`" for i in info["open_finding_ids"])
        or "_(no open findings)_"
    )

    if info.get("stage13_review_date"):
        review_line = (
            f"**{info['stage13_review_date']}** "
            f"(source: `{info.get('stage13_review_source') or 'bundle_metadata'}`)"
        )
    else:
        review_line = "**NONE recorded** — bundle is unreviewed at full-bundle level"

    content = f"""# Bundle {bundle} — Stage-13 readiness summary

**Date:** {today}
**Tool:** `scripts/bundle_readiness.py`
**Source mapping:** `docs/PAPER_DRAFT_MAPPING.md`
**Anchor list:** `docs/agents/claims-reviewer-bundle-prompts.md` §`{bundle}`

This is an *aggregation* of the existing per-paper Stage-13 review
findings, partitioned by the per-paper → per-bundle assignment. It is
NOT a fresh-context LLM Stage-13 review — that is user-triggered per
memory `feedback_stages_11_13_reflexive.md`.

## Source papers ({info['source_count']})

{sources_lines}

## Aggregated finding counts

- **Total findings (lifetime):** {info['total_findings']}
- **Open findings (post-supersession):** {info['open_findings']}
- **Blocker-class (critical + major):** {info['blocker_count']}
- **Severity mix:** {sev_lines}
- **Gate mix:** {gate_lines}

## Fresh-context Stage-13 review recorded

{review_line}

## Readiness verdict

**{info.get('readiness_display', info['readiness'])}**

- GREEN: 0 blockers, ≤5 open advisories, AND a recorded fresh-context
  Stage-13 review (S5 closure 2026-06-10)
- YELLOW (unreviewed): 0 blockers, but no recorded fresh-context
  full-bundle Stage-13 review — "no findings recorded" ≠ "reviewed and
  passed"
- YELLOW: 0 blockers, reviewed, >5 open advisories
- RED: ≥1 blocker (critical or major severity)

## Sample open finding IDs (first 10)

{open_ids_block}

## Next actions

- **GREEN:** reviewed and clean; re-review obligations after substantive
  edits are governed by Stage-13's re-invocation rule
  (`docs/WAVE_EXECUTION_PIPELINE.md`) and the Stage-F re-review mandate
  (`docs/LATE_PHASE6_ABSORPTION_PROTOCOL.md`); pair with
  `validate.py --check bundle_consistency` to ensure cross-bundle
  cross-bridges (anchor table in
  `docs/agents/claims-reviewer-bundle-prompts.md`) hold.
- **YELLOW (unreviewed):** schedule the bundle's fresh-context Stage-13
  LLM sweep (user-triggered); the verdict cannot reach GREEN without a
  recorded review.
- **YELLOW:** review the open advisory list; decide per-finding whether
  to fix-in-place or supersede via `docs/review_finding_supersessions.json`.
- **RED:** address blocker findings before promoting to Stage-13
  fresh-context review. Walk each open critical/major finding via
  `scripts/build_graph.py:extract_review_finding_nodes` filtered by
  `inferred_paper` ∈ {{bundle source set}}.

---

*Generated by `scripts/bundle_readiness.py` (Phase 6i Wave 7.4).*
"""
    out_path.write_text(content)
    return out_path


def write_heatmap(
    by_bundle: dict[str, dict],
) -> Path:
    """Write docs/BUNDLE_READINESS_HEATMAP.md with the N-gate × 21-bundle
    summary."""
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")

    # Collect all gate names that appear across bundles
    all_gates: set[str] = set()
    for info in by_bundle.values():
        all_gates.update(info["gate_mix"].keys())
    gate_order = sorted(all_gates)

    # Header row: bundles in canonical tier order (from bundle_registry).
    bundle_order = _BUNDLE_ORDER

    lines = [
        "# Bundle Readiness Heatmap",
        "",
        f"**Auto-generated:** {today}",
        f"**Tool:** `scripts/bundle_readiness.py --heatmap`",
        "",
        "**Companion to:** `docs/READINESS_GATES.md` (per-paper) — the "
        "per-bundle analog. Phase 6i Wave 7.4 deliverable; GREEN semantics "
        "tightened 2026-06-10 (S5 closure — see legend).",
        "",
        "## Verdict legend",
        "",
        "- 🟢 **GREEN** — 0 blockers, ≤5 open advisories, **and** a "
        "fresh-context Stage-13 review is RECORDED for the bundle",
        "- 🟡 **YELLOW (unreviewed)** — 0 blockers, but **no recorded "
        "fresh-context full-bundle Stage-13 review**. \"No findings "
        "recorded\" ≠ \"reviewed and passed\" (S5 closure, 2026-06-10, "
        "from the 2026-06-05 external review)",
        "- 🟡 **YELLOW** — 0 blockers, reviewed, >5 open advisories",
        "- 🔴 **RED** — ≥1 blocker (critical / major severity)",
        "",
        "**Review-recordedness resolution order:** (a) "
        "`papers/<X>/bundle_metadata.json` `last_stage13_review` "
        "(non-null); (b) else the newest dated genuine fresh-context "
        "review document on disk (`papers/AutomatedReviews/<dated>-"
        "{bundle-stage13,internal-adversarial}/<X>*.md`, excluding this "
        "script's own aggregation summaries and stage-9/10 artifacts, or "
        "`docs/audits/stage13_<X>_fullbundle_<date>.md`), backfilled into "
        "the metadata with a `last_stage13_review_source` audit note "
        "(evidence-based only — never fabricated); (c) else unreviewed.",
        "",
        "**Section-level rule:** a section-/phase-scoped Stage-13 audit "
        "(e.g. `docs/audits/stage13_phase6AA_*.md`) is NOT a full-bundle "
        "fresh review and does not satisfy the recordedness requirement; "
        "a bundle with only section-level evidence renders "
        "🟡 YELLOW (unreviewed) with a \"§-level only\" marker in the "
        "Stage-13 review column.",
        "",
        "## Bundle summary",
        "",
        "| Bundle | Tier | Sources | Open | Blockers | Severity mix | "
        "Stage-13 review | Verdict |",
        "|---|---:|---:|---:|---:|---|:---:|:---:|",
    ]

    tier_map = _TIER_OF
    icon = {"GREEN": "🟢", "YELLOW": "🟡", "RED": "🔴"}

    caveat_lines: list[str] = []
    any_backfilled = False
    for b in bundle_order:
        info = by_bundle.get(b, {})
        if not info:
            continue
        sev = ", ".join(f"{v} {k}" for k, v in
                        sorted(info["severity_mix"].items()))
        if not sev:
            sev = "_(none)_"
        if info.get("stage13_review_date"):
            review_cell = info["stage13_review_date"]
            if info.get("stage13_review_backfilled"):
                review_cell += " †"
                any_backfilled = True
        elif info.get("stage13_status_caveat") and \
                "section" in str(info["stage13_status_caveat"]).lower():
            review_cell = "— §-level only"
        else:
            review_cell = "— none recorded"
        verdict_display = info.get("readiness_display", info["readiness"])
        lines.append(
            f"| **{b}** | {tier_map[b]} | {info['source_count']} | "
            f"{info['open_findings']} | {info['blocker_count']} | "
            f"{sev} | {review_cell} | "
            f"{icon.get(info['readiness'], '?')} {verdict_display} |"
        )
        if info.get("stage13_status_caveat"):
            caveat_lines.append(
                f"- **{b}** — non-enum `stage13_status` in "
                f"`papers/{b}/bundle_metadata.json` (surfaced verbatim): "
                f"\"{info['stage13_status_caveat']}\""
            )

    if any_backfilled:
        lines.extend([
            "",
            "† review date backfilled from on-disk review evidence; the "
            "evidence path is recorded in the bundle's "
            "`bundle_metadata.json` `last_stage13_review_source` field.",
        ])

    if caveat_lines:
        lines.extend([
            "",
            "### Per-bundle caveats",
            "",
        ])
        lines.extend(caveat_lines)

    lines.extend([
        "",
        "## Gate × Bundle distribution (open findings)",
        "",
        "| Bundle | " + " | ".join(g[:18] for g in gate_order) + " |",
        "|---|" + "|".join(["---:"] * len(gate_order)) + "|",
    ])
    for b in bundle_order:
        info = by_bundle.get(b, {})
        if not info:
            continue
        row_cells = [str(info["gate_mix"].get(g, 0)) for g in gate_order]
        lines.append(f"| **{b}** | " + " | ".join(row_cells) + " |")

    lines.extend([
        "",
        "## Notes",
        "",
        "- This heatmap aggregates *existing* per-paper Stage-13 review "
        "findings via `build_graph.extract_review_finding_nodes()` "
        "(post-supersession). It does NOT include findings from a fresh-"
        "context Stage-13 sweep on the bundle (those are user-triggered) "
        "— but since 2026-06-10 the GREEN verdict additionally REQUIRES "
        "that such a sweep is recorded for the bundle (S5 closure).",
        "- 'Open' means `meta.status == 'open'` after applying "
        "`docs/review_finding_supersessions.json` overrides.",
        "- 'Blockers' = findings with severity `critical` or `major`. "
        "RED bundles must close blockers before promoting to a fresh-"
        "context Stage-13 LLM review.",
        "- **Staleness footnote:** the Stage-13 review column surfaces "
        "review dates so staleness is visible, but this heatmap does NOT "
        "compare edit dates against review dates. Re-review obligations "
        "after substantive edits are governed by Stage-13's re-invocation "
        "rule (`docs/WAVE_EXECUTION_PIPELINE.md` Stage 13: findings "
        "marked fixed must pass a re-invocation — \"the re-run is "
        "evidence\") and, for late absorptions into already-drafted "
        "bundles, the Stage-F re-review mandate "
        "(`docs/LATE_PHASE6_ABSORPTION_PROTOCOL.md`). A re-review sweep "
        "is separately scheduled.",
        "- Cross-bundle consistency between bundle siblings is verified "
        "by `validate.py --check bundle_consistency` (Wave 7.3); see "
        "`papers/cluster_bundle_index.json` for the cross-bundle cluster "
        "registry.",
        "",
        "---",
        "",
        "*Generated by `scripts/bundle_readiness.py` (Phase 6i Wave 7.4; "
        "S5-closure semantics 2026-06-10).*",
    ])

    HEATMAP_PATH.parent.mkdir(parents=True, exist_ok=True)
    HEATMAP_PATH.write_text("\n".join(lines))
    return HEATMAP_PATH


def write_metadata_counts(by_bundle: dict[str, dict]) -> list[str]:
    """Write the live finding counts back into each `bundle_metadata.json`.

    Added 2026-07-31 (D12 Stage-13 round-7 findings 7.2 and 8.3, D11 4.2 — three
    findings, one root cause). `bundle_source_manifest.py` initialises
    `blockers_open` / `advisories_open` to 0 at bundle creation and nothing ever
    updates them, while this module computes the live numbers on every run and
    discards them. So the metadata asserted `blockers_open: 0` for bundles carrying
    a dozen open blockers, and `freshness_stale: false` rested on that zero. The
    numbers are now written where they are computed rather than maintained by hand.

    Returns the list of bundles whose metadata actually changed.
    """
    changed: list[str] = []
    for bundle, agg in sorted(by_bundle.items()):
        meta_path = _bundle_metadata_path(bundle)
        if not meta_path.is_file():
            continue
        try:
            meta = json.loads(meta_path.read_text())
        except (json.JSONDecodeError, OSError):
            continue
        n_adv = sum(v for k, v in (agg.get("severity_mix") or {}).items()
                    if k in ("minor", "advisory"))
        # ⚠️ `freshness_stale` is deliberately NOT written here. It is owned by
        # `scripts/check_bundle_source_freshness.py`, where it means "a source paper was
        # modified after this bundle's last_lift" — a statement about content currency,
        # NOT about blockers. A first version of this function derived it from the
        # absorption protocol's line "freshness_stale cleared once blockers_open == 0 and
        # all three statuses GREEN", reading that workflow step as the field's definition.
        # It is not: two writers then disagreed on every run, `validate.py` became
        # non-idempotent (pass, then fail, then pass), and the guard built on top of it was
        # unstable. Blocker-clearance is reported by `blockers_open` and `readiness`, which
        # this function does own.
        n_blockers = agg.get("blocker_count", 0)
        updates = {
            "blockers_open": n_blockers,
            "advisories_open": n_adv,
            "open_findings": agg.get("open_findings", 0),
            "blocked_p1_gates": agg.get("blocked_p1_gates", []),
            "readiness": agg.get("readiness"),
            "readiness_last_computed": datetime.now(timezone.utc).strftime("%Y-%m-%d"),
        }
        if all(meta.get(k) == v for k, v in updates.items()
               if k != "readiness_last_computed"):
            continue
        meta.update(updates)
        meta_path.write_text(json.dumps(meta, indent=2, ensure_ascii=False) + "\n")
        changed.append(bundle)
    return changed


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Phase 6i Wave 7.4 per-bundle readiness summary"
    )
    parser.add_argument(
        "--bundle", help="produce readiness doc for one bundle only",
    )
    parser.add_argument(
        "--heatmap", action="store_true",
        help="produce only the heatmap (skip per-bundle docs)",
    )
    parser.add_argument(
        "--json", action="store_true",
        help="emit aggregated dict as JSON, no files written (no backfill)",
    )
    args = parser.parse_args()

    mapping_text = MAPPING_DOC.read_text()
    assignments = parse_mapping(mapping_text)
    findings_by_paper = load_findings_by_paper()
    # Backfill only in file-writing modes; --json stays read-only.
    review_info = resolve_stage13_reviews(backfill=not args.json)
    for b, rec in sorted(review_info.items()):
        if rec.get("backfilled_this_run"):
            print(f"[BACKFILL] {b}: last_stage13_review={rec['date']} "
                  f"({rec['source']})")
    by_bundle = aggregate_by_bundle(assignments, findings_by_paper,
                                    review_info)

    if args.json:
        print(json.dumps(by_bundle, indent=2))
        return 0

    changed_meta = write_metadata_counts(by_bundle)
    for b in changed_meta:
        agg = by_bundle[b]
        print(f"[METADATA] {b}: blockers_open={agg.get('blocker_count', 0)} "
              f"readiness={agg.get('readiness')}")

    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    out_dir = REVIEWS_DIR / f"{today}-bundle-stage13"

    if not args.heatmap:
        target_bundles = (
            [args.bundle] if args.bundle else sorted(_VALID_BUNDLE_TARGETS)
        )
        for b in target_bundles:
            info = by_bundle.get(b)
            if info is None:
                print(f"[SKIP] {b} — not in valid bundle set")
                continue
            path = write_bundle_review_doc(b, info, out_dir)
            verdict = info.get("readiness_display", info["readiness"])
            n_open = info["open_findings"]
            n_blk = info["blocker_count"]
            print(f"  [{verdict:20s}] {b}: {path.relative_to(PROJECT_ROOT)}"
                  f"  open={n_open}, blockers={n_blk}")

    # Always emit the heatmap unless single-bundle mode
    if not args.bundle:
        heatmap_path = write_heatmap(by_bundle)
        print(f"\nHeatmap written to {heatmap_path.relative_to(PROJECT_ROOT)}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
