#!/usr/bin/env python3
"""
bundle_readiness.py — Phase 6i Wave 7.4 per-bundle Stage-13 readiness summary
=============================================================================

Aggregates the existing per-paper Stage-13 review findings (extracted by
`scripts/build_graph.py:extract_review_finding_nodes`) by bundle, using
the per-paper → per-bundle assignment from
`docs/PAPER_DRAFT_MAPPING.md`. Produces:

  1. `papers/AutomatedReviews/<DATE>-bundle-stage13/<bundle>.md` per
     bundle — a readiness summary aggregating per-paper findings,
     classifying each finding by bundle scope (intra-bundle vs cross-
     bundle), and listing the bundle's anchor coverage.
  2. `docs/BUNDLE_READINESS_HEATMAP.md` — the N-gate × 21-bundle
     heatmap (the bundle-aware analog of the pre-existing
     `READINESS_GATES.md`).

This script does NOT run a fresh-context LLM-driven Stage-13 review; it
lifts the already-existing per-paper review findings into per-bundle
summaries so the operator can see at a glance which bundles are
submission-ready.

⚠️ That is a statement about THIS SCRIPT's scope, not about a gate.
**Stage 13 is a reflexive pipeline stage, not user-triggered** — it runs
once the preliminary work and checks are done, like every other stage.
This file previously said the opposite and cited
`feedback_stages_11_13_reflexive.md` as its authority, which is the
memory recording that Stages 11 and 13 are reflexive. The generated
summaries carried that inverted sentence into every dated directory.
The real user-authorization gates are Stage 4 Aristotle submissions and
any stage a roadmap explicitly labels as user-gated.

S5 closure (2026-06-10, user-authorized)
----------------------------------------
The 2026-06-05 external review flagged failure class S5: the heatmap
rendered GREEN for bundles that had never received a fresh-context
Stage-13 review — "no findings recorded" is not "reviewed and passed".
Semantics now enforced here:

  * GREEN requires 0 blockers AND ≤5 open advisories AND a RECORDED
    fresh-context Stage-13 review for the bundle.
  * 0-blockers-but-never-reviewed renders as "YELLOW (unreviewed)".
  * Review-recordedness resolution order:
      (a) `papers/<X>/bundle_metadata.json` `last_stage13_review`
          (ISO timestamp, non-null);
      (b) else DERIVED from on-disk review evidence — the newest dated
          genuine fresh-context review document for the bundle under
          `papers/AutomatedReviews/` (or a full-bundle audit doc
          `docs/audits/stage13_<X>_fullbundle_<date>.md`) — and
          BACKFILLED into the metadata together with a
          `last_stage13_review_source` audit-trail note. Evidence-based
          backfill only — never fabricated. Files generated by THIS
          script (aggregation summaries) carry a footer marker and are
          excluded from evidence; so are stage-9/10 artifacts
          (`*figures*`/`*claims*`) and section-/phase-scoped audit docs
          (`docs/audits/stage13_phase6XX_*.md` — a section-level review
          is NOT a full-bundle fresh review).
      (c) else the bundle is unreviewed → YELLOW (unreviewed).
  * Review dates are surfaced in the heatmap to expose staleness;
    re-review obligations after substantive edits are governed by the
    Stage-13 re-invocation rule (WAVE_EXECUTION_PIPELINE.md Stage 13)
    and the late-absorption Stage-F re-review mandate
    (LATE_PHASE6_ABSORPTION_PROTOCOL.md). No edit-date comparison is
    performed here.

Usage
-----
    uv run python scripts/bundle_readiness.py             # generate everything
    uv run python scripts/bundle_readiness.py --bundle L1 # one bundle only
    uv run python scripts/bundle_readiness.py --heatmap   # only heatmap
    uv run python scripts/bundle_readiness.py --json      # read-only dump
                                                          # (no backfill)
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from collections import Counter, defaultdict
from datetime import datetime, timezone
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
PAPERS_DIR = PROJECT_ROOT / "papers"
REVIEWS_DIR = PAPERS_DIR / "AutomatedReviews"
AUDITS_DIR = PROJECT_ROOT / "docs" / "audits"
HEATMAP_PATH = PROJECT_ROOT / "docs" / "BUNDLE_READINESS_HEATMAP.md"

# Footer marker present in every aggregation file THIS script writes.
# Files carrying it are not fresh-context reviews and never count as
# review-recordedness evidence.
AGGREGATION_MARKER = "Generated by `scripts/bundle_readiness.py`"

# Directory-name date prefix: 2026-05-01, 2026-05-01-1345, 2026-05-01-T1830
_DIR_DATE_RE = re.compile(r"^(\d{4}-\d{2}-\d{2})(?:-T?(\d{3,4}))?")

# Plain full-bundle stage13_status enum values per BUNDLE_DIRECTORY_SCHEMA.md.
# Anything else (e.g. D6's "green_phase6AA_section (...)") is a freeform
# caveat string and is surfaced verbatim in the heatmap.
#: Declared `stage*_status` vocabulary. ⚠️ EXTENDED 2026-08-09 (TODO-D5): the set
#: below covered stage13 ONLY, and three values live in the corpus were undeclared —
#: measured `not_started` (2), `skeleton` (1), `pending-redo` (1), all of them on
#: stage9/stage10, which had NO enum guard at all. An undeclared value on an
#: unguarded stage is indistinguishable from a typo, and both read as "not green".
_PLAIN_STAGE13_STATUSES = {"pending", "green", "yellow", "red", ""}
#: The full live vocabulary, per stage. `not_started` and `skeleton` are legitimate
#: pre-review states; `pending-redo` marks a stage invalidated by a later append.
_STAGE_STATUS_ENUM = frozenset({
    "pending", "green", "yellow", "red", "",
    "not_started", "skeleton", "pending-redo",
})
_GUARDED_STAGE_FIELDS = ("stage9_status", "stage10_status", "stage13_status")

sys.path.insert(0, str(PROJECT_ROOT / "scripts"))
from bundle_migration import parse_mapping, MAPPING_DOC  # noqa: E402
from sentence_state import _VALID_BUNDLE_TARGETS  # noqa: E402

# Roster metadata from THE source of truth (scripts/bundle_registry.py).
# Until the 2026-07-30 consolidation `write_heatmap()` carried its OWN
# `bundle_order` + `tier_map` literals — which stopped at D9 while this module
# already imported the full roster three lines up. The heatmap therefore
# rendered 19 of 21 bundles while looking complete: the omitted codes were
# skipped by `by_bundle.get(b, {})`, so nothing errored.
from bundle_registry import (  # noqa: E402
    BUNDLE_CODES as _BUNDLE_ORDER,
    TIER_OF as _TIER_OF,
)
from bundle_json import write_bundle_json  # noqa: E402


def load_findings_by_paper() -> dict[str, list[dict]]:
    """Pull current ReviewFinding nodes via build_graph and partition
    by paper."""
    from build_graph import extract_review_finding_nodes
    from qi_register import classify_finding

    findings = extract_review_finding_nodes()
    by_paper: dict[str, list[dict]] = defaultdict(list)
    for f in findings:
        m = f.get("meta", {}) or {}
        # ⚠️ FALLBACK ADDED 2026-07-31 (D11 Stage-13 round-5 BLOCKER 4.1, second
        # layer). Bundle-era reviews are named after their bundle code, carry
        # `inferred_bundle`, and have NO `inferred_paper`. Partitioning on
        # `inferred_paper` alone therefore dropped every bundle-era finding on
        # the floor, and the heatmap reported `Blockers 0 / GREEN` for bundles
        # holding dozens of open criticals — a FALSE GREEN, strictly worse than
        # the "YELLOW (unreviewed)" it replaced. D11 alone had 40 findings
        # (6 critical, 11 major) invisible here.
        paper = m.get("inferred_paper") or m.get("inferred_bundle")
        if not paper:
            continue
        by_paper[paper].append({
            "id": f["id"],
            "label": f["label"],
            "gate": classify_finding(f),
            "severity": m.get("severity", "advisory"),
            "status": m.get("status", "open"),
            "review_date": m.get("review_date", ""),
            "review_file": m.get("review_file", ""),
        })
    return dict(by_paper)


def _bundle_metadata_path(bundle: str) -> Path:
    return PAPERS_DIR / bundle / "bundle_metadata.json"


#: Kinds that make a document FULL-BUNDLE review evidence — i.e. eligible to set a bundle's
#: "last reviewed" date. Deliberately WIDER than `_KINDS_SUFFICIENT_FOR_GREEN`: an
#: `internal-adversarial` pass is a review and dates the bundle, but only `full-adversarial`
#: earns green. Kinds outside this set (`adjudication`, `targeted-infra`,
#: `citation-integrity`, `targeted`) are real documents about real work and are simply not
#: full-bundle reviews; admitting one would date a bundle from a pass that never swept it.
_FULL_BUNDLE_EVIDENCE_KINDS = frozenset({"full-adversarial", "internal-adversarial"})


def _declared_kind_of(path: Path) -> str | None:
    """The `kind:` a single evidence document declares about itself, or `None`.

    Verbatim, never coerced — see `_declared_review_kind`, which resolves the newest
    evidence for a bundle and shares this reader.
    """
    try:
        head = path.read_text(errors="replace")[:1200]
    except OSError:
        return None
    m = _DECLARED_KIND_RE.search(head)
    return m.group(1) if m else None


def find_stage13_review_evidence(bundle: str) -> tuple[str, str] | None:
    """Newest genuine fresh-context Stage-13 review evidence for a bundle.

    Returns ``(date "YYYY-MM-DD", path-relative-to-project)`` or ``None``.

    Evidence sources (S5-closure resolution-order step (b)):

    1. ``papers/AutomatedReviews/<dated dir>/<bundle>[-_suffix].md`` where
       the directory name contains ``bundle-stage13`` or
       ``internal-adversarial``. Excluded: files written by this script
       (``AGGREGATION_MARKER`` footer) and stage-9/10 artifacts (filename
       contains ``figure``/``claims``).
    2. ``docs/audits/stage13_<bundle>_fullbundle_<date>.md`` — the
       Phase-6AA-era location for consolidated full-bundle paper-layer
       Stage-13 reviews. Section-/phase-scoped audit docs
       (``stage13_phase6XX_*.md``) deliberately do NOT match: a
       section-level review is not a full-bundle fresh review.
    """
    file_re = re.compile(rf"^{re.escape(bundle)}([-_][A-Za-z0-9-]+)?\.md$")
    candidates: list[tuple[tuple[str, str, str, str], str, str]] = []

    if REVIEWS_DIR.is_dir():
        for d in REVIEWS_DIR.iterdir():
            if not d.is_dir():
                continue
            name = d.name
            m = _DIR_DATE_RE.match(name)
            if not m:
                continue
            by_convention = ("bundle-stage13" in name or "internal-adversarial" in name)
            date, hhmm = m.group(1), (m.group(2) or "0000")
            for f in sorted(d.iterdir()):
                if not f.is_file() or not file_re.match(f.name):
                    continue
                low = f.name.lower()
                if "figure" in low or "claims" in low:
                    continue  # stage-9/10 artifact, not a Stage-13 review
                try:
                    if AGGREGATION_MARKER in f.read_text(errors="replace"):
                        continue  # this script's own aggregation output
                except OSError:
                    continue
                # ⚠️ DISCOVERY ASKS THE DOCUMENT FIRST, THE FOLDER ONLY IF IT IS SILENT.
                # The sibling rule below — a directory name is not a KIND — was already
                # right, but it was enforced on a candidate set the folder name alone
                # selected, so a document that DECLARED its kind correctly was unreachable
                # whenever it sat outside the naming convention. Measured 2026-08-15, both
                # directions were live:
                #   * FALSE NEGATIVE — `2026-08-14-l1-stage13/L1.md` declares
                #     `kind: full-adversarial`; the folder matched neither token, so the one
                #     genuine adversarial pass of that day's loop was invisible and L1 kept
                #     reporting a review date from June.
                #   * FALSE POSITIVE — two `…-internal-adversarial/D12.md` declare
                #     `kind: adjudication`. The folder admitted them as full-bundle review
                #     evidence while the document says otherwise.
                # This changes only what is FINDABLE. A convention-named folder still yields
                # no kind, so it resolves to `reviewed-kind-unrecorded` and cannot reach
                # green — the 389 legacy documents that declare nothing are unaffected, and
                # switching wholesale to declared-kind would have blinded the resolver to
                # all of them.
                declared = _declared_kind_of(f)
                if declared is not None:
                    if declared not in _FULL_BUNDLE_EVIDENCE_KINDS:
                        continue      # the document says it is not a full-bundle review
                elif not by_convention:
                    continue          # silent document outside the convention: not evidence
                rel = str(f.relative_to(PROJECT_ROOT))
                candidates.append(((date, hhmm, name, f.name), date, rel))

    audit_re = re.compile(
        rf"^stage13_{re.escape(bundle)}_fullbundle_(\d{{4}}-\d{{2}}-\d{{2}})\.md$"
    )
    if AUDITS_DIR.is_dir():
        for f in AUDITS_DIR.iterdir():
            m = audit_re.match(f.name)
            if not m:
                continue
            date = m.group(1)
            rel = str(f.relative_to(PROJECT_ROOT))
            candidates.append(((date, "0000", "docs-audits", f.name), date, rel))

    if not candidates:
        return None
    _, date, rel = max(candidates, key=lambda c: c[0])
    return date, rel


def resolve_stage13_reviews(*, backfill: bool) -> dict[str, dict]:
    """Resolve per-bundle Stage-13 review-recordedness (S5 closure).

    Resolution order per bundle:
      (a) ``bundle_metadata.json.last_stage13_review`` non-null → recorded;
      (b) else newest on-disk genuine review evidence
          (``find_stage13_review_evidence``) → recorded; when
          ``backfill=True`` the date is written back into the metadata
          together with a ``last_stage13_review_source`` audit note
          (evidence-based backfill only — never fabricated);
      (c) else unreviewed (``date`` stays ``None``).

    Returns ``{bundle: {"date", "source", "backfilled", "status_caveat",
    "backfilled_this_run"}}``.
    """
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    out: dict[str, dict] = {}
    for b in sorted(_VALID_BUNDLE_TARGETS):
        rec = {
            "date": None,
            "kind": None,
            "source": None,
            "backfilled": False,
            "backfilled_this_run": False,
            "status_caveat": None,
        }
        md_path = _bundle_metadata_path(b)
        md: dict | None = None
        if md_path.is_file():
            try:
                md = json.loads(md_path.read_text())
            except (OSError, json.JSONDecodeError):
                md = None
        if md is not None:
            raw_status = str(md.get("stage13_status") or "")
            if raw_status not in _PLAIN_STAGE13_STATUSES:
                rec["status_caveat"] = raw_status
            # TODO-D5: stage9/stage10 were unguarded entirely. A value outside the
            # declared vocabulary on ANY stage is recorded, not silently accepted.
            off = [f"{f}={md.get(f)!r}" for f in _GUARDED_STAGE_FIELDS
                   if str(md.get(f) or "") not in _STAGE_STATUS_ENUM]
            if off:
                rec["stage_status_undeclared"] = off

        if md is not None:
            rec["kind"] = md.get("stage13_review_kind")
        if rec["kind"]:
            rec["kind_source"] = "bundle_metadata"
        if md is not None and md.get("last_stage13_review"):
            rec["date"] = str(md["last_stage13_review"])[:10]
            # ⚠️ RECORDED WINS, BUT A NEWER REVIEW ON DISK MUST NOT VANISH (2026-08-15).
            # Step (a) is authoritative by design — the metadata is the record, and on-disk
            # evidence is backfill for bundles that have none. But preferring it SILENTLY
            # means a review that ran and was never recorded through `record_review.py` is
            # indistinguishable from one that never ran. Measured: L1's 2026-08-14
            # `full-adversarial` pass sat on disk while the heatmap reported 2026-06-10, so
            # the single genuine adversarial review of that day's loop was invisible on the
            # surface built to show exactly that. Surfaced, never auto-adopted: the remedy is
            # to record it through the writer, and quietly overwriting the record here would
            # replace one unverified date with another.
            ev_newer = find_stage13_review_evidence(b)
            if ev_newer and ev_newer[0] > rec["date"]:
                rec["unrecorded_newer_evidence"] = {
                    "date": ev_newer[0], "path": ev_newer[1],
                    "kind": _declared_kind_of(PROJECT_ROOT / ev_newer[1]),
                }
            src = md.get("last_stage13_review_source")
            rec["source"] = src or "bundle_metadata"
            rec["backfilled"] = bool(src) and str(src).startswith("backfilled")
        else:
            ev = find_stage13_review_evidence(b)
            if ev is not None:
                date, rel = ev
                origin = (
                    "backfilled-from-AutomatedReviews"
                    if rel.startswith("papers/AutomatedReviews")
                    else "backfilled-from-audit-doc"
                )
                note = f"{origin} {rel} {today}"
                rec.update({"date": date, "source": note, "backfilled": True})
                if backfill and md is not None:
                    md["last_stage13_review"] = date
                    md["last_stage13_review_source"] = note
                    write_bundle_json(md_path, md)
                    rec["backfilled_this_run"] = True
        # ⚠️ THE KIND GETS THE EVIDENCE PATH ITS SIBLING DATE ALREADY HAD (2026-08-13).
        # `rec["kind"]` was read from metadata and from NOWHERE ELSE, while the date three
        # lines above resolves through `find_stage13_review_evidence` with a documented
        # "evidence-based backfill only — never fabricated" note. Consequence, measured:
        # `stage13_review_kind` was absent from all 21 bundles, only `full-adversarial`
        # earns green, so NO bundle could reach Stage-13 green regardless of its status —
        # and 20 of the 21 had genuine review evidence sitting on disk.
        #
        # ⚠️ A DIRECTORY NAME IS NOT A KIND, and this is the line the fix must not cross.
        # `…-bundle-stage13/` says the pass was bundle-level; it does not say whether it was
        # full-adversarial or a scoped sweep. Inferring the kind from the path would
        # manufacture, for 18 bundles at once, exactly the evidence the P1 gate exists to
        # demand. Only a kind the document DECLARES about itself is used.
        if not rec["kind"]:
            declared = _declared_review_kind(b)
            if declared:
                rec["kind"], rec["kind_source"] = declared, "evidence-document"
        # Three states, not two: `unreviewed` and `reviewed, kind unrecorded` are different
        # facts with different remedies — one needs a review, the other needs a record —
        # and collapsing them is what made every S13 cell read the same.
        rec["kind_state"] = (
            "declared" if rec["kind"]
            else ("reviewed-kind-unrecorded" if rec["date"] else "unreviewed"))
        out[b] = rec
    return out


#: `kind: <token>` in an evidence document's own front matter. The ONLY evidence-side source
#: of a review kind — see the warning in `resolve_stage13_reviews`.
_DECLARED_KIND_RE = re.compile(r"^kind:\s*([A-Za-z][A-Za-z0-9-]*)\s*$", re.MULTILINE)


def _declared_review_kind(bundle: str) -> str | None:
    """The kind a bundle's newest Stage-13 evidence declares about ITSELF, or `None`.

    ⚠️ An unrecognised token is returned VERBATIM, never coerced to the nearest accepted
    kind and never dropped. One document on disk declares `adjudication`, which is not one
    of the four accepted kinds; mapping it to a neighbour would lose the fact that a
    reviewer used a word the system does not know, and dropping it would read as "no kind
    declared". It simply will not satisfy `_KINDS_SUFFICIENT_FOR_GREEN`, which is correct.
    """
    ev = find_stage13_review_evidence(bundle)
    if ev is None:
        return None
    return _declared_kind_of(PROJECT_ROOT / ev[1])


#: Stage-13 evidence kinds that earn a GREEN readiness verdict. Mirrors
#: `record_review.KINDS_SUFFICIENT_FOR_GREEN`; kept as a literal rather than imported so
#: the readiness layer does not take a dependency on the writer CLI, and asserted equal
#: to it by `tests/test_record_review.py`.
_KINDS_SUFFICIENT_FOR_GREEN = frozenset({"full-adversarial"})


def _blocked_p1_gates_by_paper() -> dict[str, list[str]] | None:
    """Bundle/paper key -> names of its BLOCKED priority-1 ReadinessGates, or None.

    Added 2026-07-31 (self-audit, corroborated by D12 Stage-13 round-7 finding 8.2).
    This module's verdict is computed from review findings ONLY, so it cannot see the
    gates that are not finding-derived (NarrativeGrounding, ComputationCorrectness,
    CitationIntegrity, …). It was therefore issuing 🟢 GREEN — the verdict a reader
    takes as "ready" — for bundles whose P1 gates were blocked: D6 and D10 were both
    live instances. Neither subsystem was lying about its own inputs; the heatmap
    simply had no obligation to agree with the gate, which is exactly the shape of the
    round-6 8.1 defect one layer over.

    Returns ``None`` — NOT ``{}`` — when the gates could not be computed, and
    `aggregate_by_bundle` refuses to issue GREEN in that case.

    ⚠️ **CORRECTED 2026-08-04.** This returned ``{}`` on ANY exception, documented as
    *"callers treat that as 'no downgrade'"*, justified by "the graph is already a hard
    dependency of `load_findings_by_paper`, so an outage there fails loudly upstream".
    That reasoning does not hold: `load_findings_by_paper` calls
    `extract_review_finding_nodes`, **not** `build_graph_json`, so a failure *inside*
    `build_graph_json` or a NEW evaluator bug in `evaluate_all_gates` was swallowed
    here and nowhere else. The P1-gate downgrade then silently vanished and a bundle
    could render 🟢 GREEN — through the error path of the very function added to stop
    that (D6 and D10 were the live instances it was written for).

    `{}` and "could not compute" are different facts and must not share a value; that
    is the same `UNEVALUATED`-vs-`clear` conflation `QA_QI_INFRASTRUCTURE_MAP` §7
    names as the systemic pattern.
    """
    try:
        from readiness_gates import evaluate_all_gates
        from build_graph import build_graph_json
        out: dict[str, list[str]] = {}
        for r in evaluate_all_gates(build_graph_json()):
            if r.state == "blocked" and r.priority == 1:
                out.setdefault(r.paper, []).append(r.gate)
        return out
    except Exception as exc:  # noqa: BLE001 — reported, never silently absorbed
        print(f"[WARN] P1-gate downgrade could not be computed "
              f"({type(exc).__name__}: {exc}) — GREEN will be withheld", file=sys.stderr)
        return None


def aggregate_by_bundle(
    assignments: dict[str, dict],
    findings_by_paper: dict[str, list[dict]],
    review_info: dict[str, dict] | None = None,
) -> dict[str, dict]:
    """For each bundle code, aggregate all findings from its source
    papers + collect bundle-level statistics.

    ``review_info`` is the output of :func:`resolve_stage13_reviews`;
    when omitted it is resolved read-only (no metadata backfill), so
    external callers (``scripts/datastar_bundles.py``) keep the original
    two-argument signature and still get S5-closure verdict semantics.
    """
    if review_info is None:
        review_info = resolve_stage13_reviews(backfill=False)

    blocked_p1 = _blocked_p1_gates_by_paper()

    by_bundle: dict[str, dict] = {}
    for b in _VALID_BUNDLE_TARGETS:
        sources = [p for p, a in assignments.items()
                   if b in a["bundle_destinations"]]
        all_findings = []
        # ⚠️ The bundle's OWN key must be included alongside its source papers
        # (added 2026-07-31, D11 Stage-13 round-5 BLOCKER 4.1, third layer).
        # Bundle-era Stage-13 findings are keyed by the bundle code, not by any
        # source paper — and for bundles whose only mapping sources are synthesis
        # stubs there are no source papers at all. Iterating `sources` alone
        # therefore collected ZERO findings and rendered 🟢 GREEN / Blockers 0
        # for bundles carrying dozens of open criticals.
        for p in ([b] + list(sources)):
            for f in findings_by_paper.get(p, []):
                f_copy = dict(f)
                f_copy["paper"] = p
                all_findings.append(f_copy)

        # Open findings only (closed via supersession ledger no longer count)
        open_findings = [f for f in all_findings if f.get("status") == "open"]

        # Severity breakdown of open findings
        sev_counter = Counter(f["severity"] for f in open_findings)
        # Gate breakdown
        gate_counter = Counter(f["gate"] for f in open_findings)

        # Critical / blocker count = severity in {critical, major}
        n_blockers = sum(sev_counter[s] for s in ("critical", "major"))

        rev = review_info.get(b, {}) or {}
        review_recorded = bool(rev.get("date"))
        review_kind = rev.get("kind")

        # Stage-13 readiness verdict (S5 closure 2026-06-10): GREEN
        # additionally requires a RECORDED fresh-context Stage-13 review.
        # "No findings recorded" != "reviewed and passed".
        if n_blockers > 0:
            readiness, readiness_display = "RED", "RED"
        elif not review_recorded:
            readiness, readiness_display = "YELLOW", "YELLOW (unreviewed)"
        elif len(open_findings) > 5:
            readiness, readiness_display = "YELLOW", "YELLOW"
        else:
            readiness, readiness_display = "GREEN", "GREEN"

        # GREEN must survive every P1 gate, not only the finding-derived ones.
        # `blocked_p1 is None` means the gates could NOT be computed — which is not
        # the same as "no gate is blocked", so GREEN is withheld rather than granted
        # by default (2026-08-04; see `_blocked_p1_gates_by_paper`).
        if blocked_p1 is None:
            gate_block = []
            if readiness == "GREEN":
                readiness = "YELLOW"
                readiness_display = "YELLOW (P1 gates UNVERIFIED — could not be computed)"
        else:
            gate_block = sorted(blocked_p1.get(b, []))
            if readiness == "GREEN" and gate_block:
                readiness = "YELLOW"
                readiness_display = f"YELLOW (P1 gate blocked: {', '.join(gate_block)})"

        # ── ADR-011 Phase 2d: two more ways GREEN is WITHHELD rather than granted ──
        # Both follow the pattern this layer already uses twice (`blocked_p1 is None`
        # above; `evaluate_all_gates`' crash handling): a thing that was NOT MEASURED
        # must not render as a thing that was measured and found fine.
        if readiness == "GREEN" and review_kind not in _KINDS_SUFFICIENT_FOR_GREEN:
            # A recorded review is not necessarily a review of the right SCOPE. Any
            # document referenced by `stage13_review_doc` satisfies `review_recorded`,
            # so a targeted 16-anchor attribution sweep counted exactly as a full
            # fresh-context adversarial pass — which is how D9, the portfolio's only
            # GREEN, reached GREEN with its Stage 10 never run.
            readiness = "UNMEASURED"
            readiness_display = (
                f"UNMEASURED (Stage-13 evidence kind="
                f"{review_kind or 'unrecorded'}; only "
                f"{'/'.join(sorted(_KINDS_SUFFICIENT_FOR_GREEN))} earns GREEN)")
        elif readiness == "GREEN" and not (
                _bundle_metadata_path(b).parent / "claims_review.json").is_file():
            # No Stage-10 artifact at all. `chain_canonicalize --report` measured this
            # directly on 2026-08-01: D6 and D9 have no `claims_review.json`, and F and
            # I3 have one carrying ZERO chain links.
            readiness = "UNMEASURED"
            readiness_display = "UNMEASURED (Stage 10 never run — no claims_review.json)"

        by_bundle[b] = {
            "sources": sorted(sources),
            "source_count": len(sources),
            "total_findings": len(all_findings),
            "open_findings": len(open_findings),
            "severity_mix": dict(sev_counter),
            "gate_mix": dict(gate_counter),
            "blocker_count": n_blockers,
            "readiness": readiness,
            "readiness_display": readiness_display,
            "review_recorded": review_recorded,
            "stage13_review_date": rev.get("date"),
            "stage13_review_source": rev.get("source"),
            "stage13_review_backfilled": bool(rev.get("backfilled")),
            "stage13_status_caveat": rev.get("status_caveat"),
            "unrecorded_newer_evidence": rev.get("unrecorded_newer_evidence"),
            "blocked_p1_gates": gate_block,
            # ⚠️ COMPLETE, not a sample. This was `open_findings[:10]` — a silent cap on
            # the only field that records WHICH findings this aggregation reached. Its one
            # consumer renders a sample, so the cap now lives at the render site where it
            # discloses itself; a truncated list here would make the coverage complement
            # below report every 11th-and-later finding as unattributed.
            "open_finding_ids": [f["id"] for f in open_findings],
        }
    return by_bundle


def write_bundle_review_doc(
    bundle: str,
    info: dict,
    out_dir: Path,
) -> Path:
    """Write papers/AutomatedReviews/<DATE>-bundle-stage13/<bundle>.md."""
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / f"{bundle}.md"

    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    sources_lines = (
        "\n".join(f"- `papers/{s}/paper_draft.tex`" for s in info["sources"])
        or "_(no source papers assigned)_"
    )

    sev_lines = ", ".join(f"{v} {k}" for k, v in
                          sorted(info["severity_mix"].items())) or "_(none)_"
    gate_lines = ", ".join(f"{v} {k}" for k, v in
                           sorted(info["gate_mix"].items())) or "_(none)_"

    # A SAMPLE, and it says so. The cap used to sit in `aggregate_by_bundle`, where the
    # reader of the dict had no way to tell ten findings from a hundred.
    _open_ids = list(info["open_finding_ids"])
    open_ids_block = (
        "\n".join(f"- `{i}`" for i in _open_ids[:10])
        + (f"\n- _…and {len(_open_ids) - 10} more (showing 10 of {len(_open_ids)})_"
           if len(_open_ids) > 10 else "")
    ) or "_(no open findings)_"

    if info.get("stage13_review_date"):
        review_line = (
            f"**{info['stage13_review_date']}** "
            f"(source: `{info.get('stage13_review_source') or 'bundle_metadata'}`)"
        )
    else:
        review_line = "**NONE recorded** — bundle is unreviewed at full-bundle level"

    content = f"""# Bundle {bundle} — Stage-13 readiness summary

**Date:** {today}
**Tool:** `scripts/bundle_readiness.py`
**Source mapping:** `docs/PAPER_DRAFT_MAPPING.md`
**Anchor list:** `docs/agents/claims-reviewer-bundle-prompts.md` §`{bundle}`

This is an *aggregation* of the existing per-paper Stage-13 review
findings, partitioned by the per-paper → per-bundle assignment. It is
NOT a fresh-context LLM Stage-13 review.

⚠️ That is this document's scope, not a gate: **Stage 13 is a reflexive
pipeline stage.** It runs once the preliminary work and checks are done.

## Source papers ({info['source_count']})

{sources_lines}

## Aggregated finding counts

- **Total findings (lifetime):** {info['total_findings']}
- **Open findings (post-supersession):** {info['open_findings']}
- **Blocking (critical + major):** {info['blocker_count']}
- **Critical (\U0001F534 BLOCKER only):** {info['severity_mix'].get('critical', 0)}
- **Severity mix:** {sev_lines}
- **Gate mix:** {gate_lines}

## Fresh-context Stage-13 review recorded

{review_line}

## Readiness verdict

**{info.get('readiness_display', info['readiness'])}**

- GREEN: 0 blockers, ≤5 open advisories, AND a recorded fresh-context
  Stage-13 review (S5 closure 2026-06-10)
- YELLOW (unreviewed): 0 blockers, but no recorded fresh-context
  full-bundle Stage-13 review — "no findings recorded" ≠ "reviewed and
  passed"
- YELLOW: 0 blockers, reviewed, >5 open advisories
- RED: ≥1 blocker (critical or major severity)

## Sample open finding IDs (first 10)

{open_ids_block}

## Next actions

- **GREEN:** reviewed and clean; re-review obligations after substantive
  edits are governed by Stage-13's re-invocation rule
  (`docs/WAVE_EXECUTION_PIPELINE.md`) and the Stage-F re-review mandate
  (`docs/LATE_PHASE6_ABSORPTION_PROTOCOL.md`); pair with
  `validate.py --check bundle_consistency` to ensure cross-bundle
  cross-bridges (anchor table in
  `docs/agents/claims-reviewer-bundle-prompts.md`) hold.
- **YELLOW (unreviewed):** run the bundle's fresh-context Stage-13 sweep —
  a reflexive pipeline stage, not something to wait on; the verdict cannot
  reach GREEN without a recorded review.
- **YELLOW:** review the open advisory list; decide per-finding whether
  to fix-in-place or supersede via `docs/review_finding_supersessions.json`.
- **RED:** address blocker findings before promoting to Stage-13
  fresh-context review. Walk each open critical/major finding via
  `scripts/build_graph.py:extract_review_finding_nodes` filtered by
  `inferred_paper` ∈ {{bundle source set}}.

---

*Generated by `scripts/bundle_readiness.py` (Phase 6i Wave 7.4).*
"""
    out_path.write_text(content)
    return out_path


def write_heatmap(
    by_bundle: dict[str, dict],
) -> Path:
    """Write docs/BUNDLE_READINESS_HEATMAP.md with the N-gate × 21-bundle
    summary."""
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")

    # Collect all gate names that appear across bundles
    all_gates: set[str] = set()
    for info in by_bundle.values():
        all_gates.update(info["gate_mix"].keys())
    gate_order = sorted(all_gates)

    # Header row: bundles in canonical tier order (from bundle_registry).
    bundle_order = _BUNDLE_ORDER

    lines = [
        "# Bundle Readiness Heatmap",
        "",
        f"**Auto-generated:** {today}",
        f"**Tool:** `scripts/bundle_readiness.py --heatmap`",
        "",
        "**Companion to:** `docs/READINESS_GATES.md` (per-paper) — the "
        "per-bundle analog. Phase 6i Wave 7.4 deliverable; GREEN semantics "
        "tightened 2026-06-10 (S5 closure — see legend).",
        "",
        "## Verdict legend",
        "",
        "- 🟢 **GREEN** — 0 blockers, ≤5 open advisories, **and** a "
        "fresh-context Stage-13 review is RECORDED for the bundle",
        "- 🟡 **YELLOW (unreviewed)** — 0 blockers, but **no recorded "
        "fresh-context full-bundle Stage-13 review**. \"No findings "
        "recorded\" ≠ \"reviewed and passed\" (S5 closure, 2026-06-10, "
        "from the 2026-06-05 external review)",
        "- 🟡 **YELLOW** — 0 blockers, reviewed, >5 open advisories",
        "- 🔴 **RED** — ≥1 blocker (critical / major severity)",
        "",
        "**Review-recordedness resolution order:** (a) "
        "`papers/<X>/bundle_metadata.json` `last_stage13_review` "
        "(non-null); (b) else the newest dated genuine fresh-context "
        "review document on disk (`papers/AutomatedReviews/<dated>-"
        "{bundle-stage13,internal-adversarial}/<X>*.md`, excluding this "
        "script's own aggregation summaries and stage-9/10 artifacts, or "
        "`docs/audits/stage13_<X>_fullbundle_<date>.md`), backfilled into "
        "the metadata with a `last_stage13_review_source` audit note "
        "(evidence-based only — never fabricated); (c) else unreviewed.",
        "",
        "**Section-level rule:** a section-/phase-scoped Stage-13 audit "
        "(e.g. `docs/audits/stage13_phase6AA_*.md`) is NOT a full-bundle "
        "fresh review and does not satisfy the recordedness requirement; "
        "a bundle with only section-level evidence renders "
        "🟡 YELLOW (unreviewed) with a \"§-level only\" marker in the "
        "Stage-13 review column.",
        "",
        "## Bundle summary",
        "",
        "| Bundle | Tier | Sources | Open | Blockers | Severity mix | "
        "Stage-13 review | Verdict |",
        "|---|---:|---:|---:|---:|---|:---:|:---:|",
    ]

    tier_map = _TIER_OF
    # ⚪ for UNMEASURED, deliberately not 🟡: a bundle nobody measured is a
    # different fact from a bundle measured and found short, and rendering both
    # amber is what let an unmeasured bundle read as a merely-cautious one.
    icon = {"GREEN": "🟢", "YELLOW": "🟡", "RED": "🔴", "UNMEASURED": "⚪"}

    caveat_lines: list[str] = []
    any_backfilled = False
    for b in bundle_order:
        info = by_bundle.get(b, {})
        if not info:
            continue
        sev = ", ".join(f"{v} {k}" for k, v in
                        sorted(info["severity_mix"].items()))
        if not sev:
            sev = "_(none)_"
        if info.get("stage13_review_date"):
            review_cell = info["stage13_review_date"]
            if info.get("stage13_review_backfilled"):
                review_cell += " †"
                any_backfilled = True
        elif info.get("stage13_status_caveat") and \
                "section" in str(info["stage13_status_caveat"]).lower():
            review_cell = "— §-level only"
        else:
            review_cell = "— none recorded"
        verdict_display = info.get("readiness_display", info["readiness"])
        lines.append(
            f"| **{b}** | {tier_map[b]} | {info['source_count']} | "
            f"{info['open_findings']} | {info['blocker_count']} | "
            f"{sev} | {review_cell} | "
            f"{icon.get(info['readiness'], '?')} {verdict_display} |"
        )
        if info.get("stage13_status_caveat"):
            caveat_lines.append(
                f"- **{b}** — non-enum `stage13_status` in "
                f"`papers/{b}/bundle_metadata.json` (surfaced verbatim): "
                f"\"{info['stage13_status_caveat']}\""
            )
        une = info.get("unrecorded_newer_evidence")
        if une:
            kind = une.get("kind") or "kind not declared"
            caveat_lines.append(
                f"- **{b}** — ⚠️ **a NEWER review sits on disk and is not recorded.** "
                f"The column above shows the recorded date; `{une['path']}` is dated "
                f"{une['date']} ({kind}). The recorded value wins here by design, so this "
                f"review is invisible to every consumer of that column until it is written "
                f"through `scripts/record_review.py`. Not auto-adopted: a review's verdict "
                f"is a judgement the writer exists to capture, and silently promoting a "
                f"date would swap one unverified record for another."
            )

    if any_backfilled:
        lines.extend([
            "",
            "† review date backfilled from on-disk review evidence; the "
            "evidence path is recorded in the bundle's "
            "`bundle_metadata.json` `last_stage13_review_source` field.",
        ])

    if caveat_lines:
        lines.extend([
            "",
            "### Per-bundle caveats",
            "",
        ])
        lines.extend(caveat_lines)

    lines.extend([
        "",
        "## Gate × Bundle distribution (open findings)",
        "",
        "| Bundle | " + " | ".join(g[:18] for g in gate_order) + " |",
        "|---|" + "|".join(["---:"] * len(gate_order)) + "|",
    ])
    for b in bundle_order:
        info = by_bundle.get(b, {})
        if not info:
            continue
        row_cells = [str(info["gate_mix"].get(g, 0)) for g in gate_order]
        lines.append(f"| **{b}** | " + " | ".join(row_cells) + " |")

    lines.extend([
        "",
        "## Notes",
        "",
        "- This heatmap aggregates *existing* per-paper Stage-13 review "
        "findings via `build_graph.extract_review_finding_nodes()` "
        "(post-supersession). It does NOT include findings from a fresh-"
        "context Stage-13 sweep on the bundle — that sweep is a reflexive "
        "pipeline stage this script does not run, NOT a user-gated one — "
        "and since 2026-06-10 the GREEN verdict additionally REQUIRES "
        "that such a sweep is recorded for the bundle (S5 closure).",
        "- 'Open' means `meta.status == 'open'` after applying "
        "`docs/review_finding_supersessions.json` overrides.",
        "- 'Blockers' = findings with severity `critical` or `major`. "
        "RED bundles must close blockers before promoting to a fresh-"
        "context Stage-13 LLM review.",
        "- **Staleness footnote:** the Stage-13 review column surfaces "
        "review dates so staleness is visible, but this heatmap does NOT "
        "compare edit dates against review dates. Re-review obligations "
        "after substantive edits are governed by Stage-13's re-invocation "
        "rule (`docs/WAVE_EXECUTION_PIPELINE.md` Stage 13: findings "
        "marked fixed must pass a re-invocation — \"the re-run is "
        "evidence\") and, for late absorptions into already-drafted "
        "bundles, the Stage-F re-review mandate "
        "(`docs/LATE_PHASE6_ABSORPTION_PROTOCOL.md`). A re-review sweep "
        "is separately scheduled.",
        "- Cross-bundle consistency between bundle siblings is verified "
        "by `validate.py --check bundle_consistency` (Wave 7.3); see "
        "`papers/cluster_bundle_index.json` for the cross-bundle cluster "
        "registry.",
        "",
        "---",
        "",
        "*Generated by `scripts/bundle_readiness.py` (Phase 6i Wave 7.4; "
        "S5-closure semantics 2026-06-10).*",
    ])

    HEATMAP_PATH.parent.mkdir(parents=True, exist_ok=True)
    HEATMAP_PATH.write_text("\n".join(lines))
    return HEATMAP_PATH


def write_metadata_counts(by_bundle: dict[str, dict]) -> list[str]:
    """Write the live finding counts back into each `bundle_metadata.json`.

    Added 2026-07-31 (D12 Stage-13 round-7 findings 7.2 and 8.3, D11 4.2 — three
    findings, one root cause). `bundle_source_manifest.py` initialises
    `blockers_open` / `advisories_open` to 0 at bundle creation and nothing ever
    updates them, while this module computes the live numbers on every run and
    discards them. So the metadata asserted `blockers_open: 0` for bundles carrying
    a dozen open blockers, and `freshness_stale: false` rested on that zero. The
    numbers are now written where they are computed rather than maintained by hand.

    Returns the list of bundles whose metadata actually changed.
    """
    changed: list[str] = []
    for bundle, agg in sorted(by_bundle.items()):
        meta_path = _bundle_metadata_path(bundle)
        if not meta_path.is_file():
            continue
        try:
            meta = json.loads(meta_path.read_text())
        except (json.JSONDecodeError, OSError):
            continue
        n_adv = sum(v for k, v in (agg.get("severity_mix") or {}).items()
                    if k in ("minor", "advisory"))
        # ⚠️ `freshness_stale` is deliberately NOT written here. It is owned by
        # `scripts/check_bundle_source_freshness.py`, where it means "a source paper was
        # modified after this bundle's last_lift" — a statement about content currency,
        # NOT about blockers. A first version of this function derived it from the
        # absorption protocol's line "freshness_stale cleared once blockers_open == 0 and
        # all three statuses GREEN", reading that workflow step as the field's definition.
        # It is not: two writers then disagreed on every run, `validate.py` became
        # non-idempotent (pass, then fail, then pass), and the guard built on top of it was
        # unstable. Blocker-clearance is reported by `blockers_open` and `readiness`, which
        # this function does own.
        n_blockers = agg.get("blocker_count", 0)
        # ⚠️ `blockers_open` counts BLOCKING findings — `critical` + `major`, i.e.
        # 🔴 BLOCKER *and* 🟡 REQUIRED. The name says only the first, and a D11 reviewer
        # measured the consequence: a bundle with exactly ONE open 🔴 read, to the
        # heatmap, the metadata blob and the readiness gate, as carrying eighteen
        # blockers (D11 Stage-13 round-9 finding 4.4). The field is not renamed — every
        # consumer and every blob keys on it — so the count is SPLIT instead:
        # `critical_open` carries the 🔴-only figure beside it, and the two together say
        # what one misnamed number could not.
        n_critical = (agg.get("severity_mix") or {}).get("critical", 0)
        updates = {
            "blockers_open": n_blockers,
            "critical_open": n_critical,
            "advisories_open": n_adv,
            "open_findings": agg.get("open_findings", 0),
            "blocked_p1_gates": agg.get("blocked_p1_gates", []),
            "readiness": agg.get("readiness"),
            "readiness_last_computed": datetime.now(timezone.utc).strftime("%Y-%m-%d"),
        }
        if all(meta.get(k) == v for k, v in updates.items()
               if k != "readiness_last_computed"):
            continue
        meta.update(updates)
        write_bundle_json(meta_path, meta)
        changed.append(bundle)
    return changed


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Phase 6i Wave 7.4 per-bundle readiness summary"
    )
    parser.add_argument(
        "--bundle", help="produce readiness doc for one bundle only",
    )
    parser.add_argument(
        "--heatmap", action="store_true",
        help="produce only the heatmap (skip per-bundle docs)",
    )
    parser.add_argument(
        "--json", action="store_true",
        help="emit aggregated dict as JSON, no files written (no backfill)",
    )
    args = parser.parse_args()

    mapping_text = MAPPING_DOC.read_text()
    assignments = parse_mapping(mapping_text)
    findings_by_paper = load_findings_by_paper()
    # Backfill only in file-writing modes; --json stays read-only.
    review_info = resolve_stage13_reviews(backfill=not args.json)
    for b, rec in sorted(review_info.items()):
        if rec.get("backfilled_this_run"):
            print(f"[BACKFILL] {b}: last_stage13_review={rec['date']} "
                  f"({rec['source']})")
    by_bundle = aggregate_by_bundle(assignments, findings_by_paper,
                                    review_info)

    if args.json:
        print(json.dumps(by_bundle, indent=2))
        return 0

    changed_meta = write_metadata_counts(by_bundle)
    for b in changed_meta:
        agg = by_bundle[b]
        print(f"[METADATA] {b}: blocking(critical+major)="
              f"{agg.get('blocker_count', 0)} "
              f"critical={(agg.get('severity_mix') or {}).get('critical', 0)} "
              f"readiness={agg.get('readiness')}")

    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    out_dir = REVIEWS_DIR / f"{today}-bundle-stage13"

    if not args.heatmap:
        target_bundles = (
            [args.bundle] if args.bundle else sorted(_VALID_BUNDLE_TARGETS)
        )
        for b in target_bundles:
            info = by_bundle.get(b)
            if info is None:
                print(f"[SKIP] {b} — not in valid bundle set")
                continue
            path = write_bundle_review_doc(b, info, out_dir)
            verdict = info.get("readiness_display", info["readiness"])
            n_open = info["open_findings"]
            n_blk = info["blocker_count"]
            print(f"  [{verdict:20s}] {b}: {path.relative_to(PROJECT_ROOT)}"
                  f"  open={n_open}, blockers={n_blk}")

    # Always emit the heatmap unless single-bundle mode
    if not args.bundle:
        heatmap_path = write_heatmap(by_bundle)
        print(f"\nHeatmap written to {heatmap_path.relative_to(PROJECT_ROOT)}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
