#!/usr/bin/env python3
"""Attention — the operator's four feeds, side by side and NOT merged (ADR-012 D15 S3).

THE QUESTION THIS ANSWERS
-------------------------
*"What needs me, and what can I decide well right now?"*

⚠️ **FOUR FEEDS, SURFACED TOGETHER AND NEVER FLATTENED** (operator ruling 2026-08-12, quoted
in D12: *"could be the same page, separate pages — not forcing aggregation/combination is
fine"*). They have different stores, different semantics and different actions:

===  ==========  =====================================================================
A    publication `needs_operator` `ReviewFinding`s + `docs/QI_REGISTER.md`
B    process     `.claude/dev-harness/active_issues.json` — the System-2 open issues
C    decisions   `.claude/dev-harness/blocked_questions.jsonl` + `needs_operator: now`
D    parked      `parked_items.collect()` with each release condition RE-EVALUATED
===  ==========  =====================================================================

Each list keeps its own vocabulary. There is **no common schema and no `attention_item`
type**, because the property that makes each feed legible is precisely the one a shared
schema destroys: a blocked question has options and a latency; a parked item has a release
condition and three-valued state; a QI item has a recurrence window and an occurrence count.
Coerced into one row shape, all three become "a thing with a title".

WHAT THIS MODULE REFUSES TO DO
------------------------------
**It refuses to render an absent or gitignored store as an empty feed.** All three harness
stores are local-only — measured, not assumed::

    .gitignore:101  /.claude/dev-harness/     → active_issues.json, blocked_questions.jsonl
    .gitignore:116  docs/dev-loops/SYSTEM2_REGISTER.md

On a fresh clone feeds B and C therefore have *nothing to read*, and a pane that draws that
as a calm empty list tells the operator "nothing needs you" when the truth is "this machine
cannot see the store". `coverage()` returns the availability of every source, `caveats()`
turns it into sentences the pane must render, and both are returned by `attention()` so a
caller cannot get the items without them.

⚠️ **FEED B IS READ-ONLY, PERMANENTLY.** `/skeft-qa:debrief` is the sole governor of the
System-2 register, and `system2_register._clamp_tier` guarantees that no other writer can
promote a finding past `agent-reviewed`. A second writer here would break that clamp. This
module opens `active_issues.json` for reading and never for writing.

⚠️ **FEED B'S STORE IS A TOP-N VIEW, NOT A POPULATION.** `system2_register.write_active_issues`
caps its output at `ACTIVE_ISSUES_MAX` (8 today) sorted by tier then tally. So feed B's count
is a **floor**, the register's true open count is not recoverable from this store, and
`coverage()` says so rather than letting a full-looking pane imply exhaustiveness. Re-parsing
the 840 KB register to recover the total is what D12 explicitly routes away from.

⚠️ **`None` IS NOT `False` FOR A RELEASE CONDITION** (feed D). `parked_items.release_condition_met`
returns three values; rendering `None` as unmet parks released work forever, rendering it as met
releases work on no evidence. `run:` is `None` **by design** until a run registry exists, which
is the single most common token, so this is the normal path and not an edge case.
"""
from __future__ import annotations

import json
import re
import sys
import time
from collections import Counter
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
SCRIPT_DIR = PROJECT_ROOT / "scripts"
if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

ACTIVE_ISSUES_PATH = PROJECT_ROOT / ".claude" / "dev-harness" / "active_issues.json"
BLOCKED_QUESTIONS_PATH = (
    PROJECT_ROOT / ".claude" / "dev-harness" / "blocked_questions.jsonl")
SYSTEM2_REGISTER_PATH = PROJECT_ROOT / "docs" / "dev-loops" / "SYSTEM2_REGISTER.md"
PRE_DECISIONS_PATH = PROJECT_ROOT / "docs" / "dev-loops" / "PRE_DECISIONS.md"
QI_REGISTER_PATH = PROJECT_ROOT / "docs" / "QI_REGISTER.md"

#: Stores that git does not carry. Verified with `git check-ignore -v` rather than inferred
#: from a `.gitignore` read, because the pane's whole honesty claim rests on this being right.
LOCAL_ONLY_SOURCES = {
    str(ACTIVE_ISSUES_PATH.relative_to(PROJECT_ROOT)),
    str(BLOCKED_QUESTIONS_PATH.relative_to(PROJECT_ROOT)),
    str(SYSTEM2_REGISTER_PATH.relative_to(PROJECT_ROOT)),
}

#: The five components D11 requires before a finding is *routed* rather than *deferred*.
#: Only the first is derivable from the finding store; see `_decision_package`.
DECISION_PACKAGE_COMPONENTS = (
    "orientation",          # D11.1 — generated by `review_runner.py --finding <id>` (D17)
    "ground_truth_vs_best_case",
    "substrate_delta",
    "research_done_or_dispatched",
    "options_with_recommendation",
)


# ─────────────────────────────────────────────────────────────────────────────
# source availability — the part that must never be silently empty
# ─────────────────────────────────────────────────────────────────────────────
def _source_state(path: Path, *, error: str | None = None) -> dict:
    """Whether a store can be read here, and why not when it cannot.

    ⚠️ `exists=False` is a **reported state**, never a reason to return `[]` quietly. The
    three harness stores are gitignored, so on a fresh clone this is the normal answer and
    the pane must say "no store on this machine" instead of drawing a calm empty list.
    """
    rel = str(path.relative_to(PROJECT_ROOT)) if path.is_absolute() and str(
        path).startswith(str(PROJECT_ROOT)) else str(path)
    exists = path.exists()
    return {
        "path": rel,
        "exists": exists,
        "local_only": rel in LOCAL_ONLY_SOURCES,
        "mtime": path.stat().st_mtime if exists else None,
        "error": error,
    }


def _age_days(ts: float | None, now: float | None = None) -> float | None:
    if not isinstance(ts, (int, float)):
        return None
    return round(((now if now is not None else time.time()) - float(ts)) / 86400.0, 2)


# ─────────────────────────────────────────────────────────────────────────────
# feed A — publication
# ─────────────────────────────────────────────────────────────────────────────
def _open_findings(nodes: list[dict] | None = None) -> list[dict]:
    if nodes is None:
        from build_graph import extract_review_finding_nodes
        nodes = extract_review_finding_nodes()
    return [n for n in nodes if (n.get("meta") or {}).get("status") == "open"]


def _needs_operator_bucket(value) -> str:
    """The ONE coverage bucket an open finding's `needs_operator` value falls in.

    ⚠️ An unrecognised value gets its own bucket rather than joining `no_needs_operator`.
    D12 declares two values (`now`, `queue`); a third would be a finding that *is* routed to
    the operator and would render as unrouted, which is the invisible-item failure the S2
    board's status column has the same rule about. The enum is surfaced, never coerced.
    """
    if not value:
        return "no_needs_operator"
    if value == "now":
        return "needs_operator_now"
    if value == "queue":
        return "needs_operator_queue"
    return "needs_operator_unrecognised_value"


def _decision_package(meta: dict) -> dict:
    """What D11's five components can and cannot be checked from the finding store.

    ⚠️ **ONLY ONE OF THE FIVE IS MACHINE-CHECKABLE, AND THIS SAYS SO.** D11.1 (orientation)
    is generated on demand from the finding's `target` (D17, `review_runner.py --finding`),
    so a target's presence tells us the brief can be produced. D11.2–D11.5 — ground truth vs
    best case, substrate delta, the research ladder, options with a recommendation — are
    prose judgements with **no field anywhere in the store**. Reporting them as satisfied
    because nothing contradicts them would convert "deferred" into "routed" by omission,
    which is exactly the substitution D11 exists to forbid.
    """
    return {
        "orientation_available": bool(meta.get("target")),
        "orientation_command": (
            f"uv run python scripts/review_runner.py --finding {meta['_id']}"
            if meta.get("target") else None),
        "not_machine_checkable": [c for c in DECISION_PACKAGE_COMPONENTS
                                  if c != "orientation"],
    }


def publication(nodes: list[dict] | None = None,
                qi_items: list[dict] | None = None,
                qi_error: str | None = None) -> list[dict]:
    """Feed A — publication calls waiting on the operator.

    Two vocabularies in one feed, discriminated by `source`, because D12 names two stores for
    feed A and they are not the same kind of object:

    * `source='review_finding'` — a `needs_operator` finding, with severity/lane/target/verify
      and its D11 decision-package assessment.
    * `source='qi_derived'` — a QI recurrence pattern from the (repaired) `qi_register`
      derivation: a gate, a window, an occurrence count, the papers it spans.
    * `source='qi_register_open'` — a hand-curated `## Open Items` entry that predates the
      derivation. `qi_id_for` cannot reproduce these ids (they were never derived), so they
      are surfaced verbatim rather than reconciled.
    """
    out: list[dict] = []
    for n in _open_findings(nodes):
        m = dict(n.get("meta") or {})
        if not m.get("needs_operator"):
            continue
        m["_id"] = n["id"]
        out.append({
            "source": "review_finding",
            "id": n["id"],
            "label": str(n.get("label", ""))[:160],
            "urgency": m.get("needs_operator"),
            "severity": m.get("severity"),
            "lane": m.get("lane") or "unclassified",
            "target": m.get("target"),
            "verify": m.get("verify"),
            "blocks": m.get("blocks"),
            "blocked_by": m.get("blocked_by") or [],
            "review_file": m.get("review_file"),
            "review_date": m.get("review_date"),
            "decision_package": _decision_package(m),
        })
    out.sort(key=lambda r: (r["urgency"] != "now", str(r["id"])))

    if qi_items is None and qi_error is None:
        qi_items, qi_error = _load_qi_items()
    for it in (qi_items or []):
        out.append({
            "source": "qi_derived",
            "id": it.get("id"),
            "pattern_summary": it.get("pattern_summary"),
            "gate_affected": it.get("gate_affected"),
            "window": it.get("window"),
            "occurrences": it.get("occurrences"),
            "affected_papers": it.get("affected_papers") or [],
            "severity_mix": it.get("severity_mix") or {},
            "first_observed": it.get("first_observed"),
            "last_observed": it.get("last_observed"),
        })
    for qi_id, heading in _qi_register_open_items():
        out.append({
            "source": "qi_register_open",
            "id": qi_id,
            "heading": heading,
            "store": str(QI_REGISTER_PATH.relative_to(PROJECT_ROOT)),
        })
    return out


def _load_qi_items() -> tuple[list[dict], str | None]:
    """Open items from the QI derivation, or `(…, error)` when it cannot run.

    ⚠️ The derivation emitted **zero** items until it was repaired (D15's first prerequisite),
    and a zero here used to be indistinguishable from a clean corpus. A failure is reported as
    an error string, never as an empty feed.
    """
    try:
        import qi_register
        stats = qi_register.derive_stats()
    except Exception as exc:                       # pragma: no cover — defensive
        return [], f"{type(exc).__name__}: {exc}"
    items = stats.get("items") or []
    return [i for i in items if i.get("status", "open") == "open"], None


_QI_OPEN_HEADING_RE = re.compile(r"^### (qi-[A-Za-z0-9_-]+)([^\n]*)$", re.MULTILINE)


def _qi_register_open_items() -> list[tuple[str, str]]:
    """`(id, heading-remainder)` for each `## Open Items` entry on disk. Empty when absent."""
    if not QI_REGISTER_PATH.exists():
        return []
    text = QI_REGISTER_PATH.read_text(encoding="utf-8", errors="replace")
    m = re.search(r"^## Open Items\b", text, re.MULTILINE)
    if not m:
        return []
    section = text[m.end():]
    nxt = re.search(r"^## ", section, re.MULTILINE)
    if nxt:
        section = section[: nxt.start()]
    return [(g.group(1), g.group(2).strip(" —-")) for g in
            _QI_OPEN_HEADING_RE.finditer(section)]


# ─────────────────────────────────────────────────────────────────────────────
# feed B — process (READ-ONLY)
# ─────────────────────────────────────────────────────────────────────────────
def _read_active_issues(path: Path | None = None) -> tuple[list[dict] | None, dict]:
    """`(issues, state)` — `issues is None` means the store could not be read.

    Shape measured on this machine: `{"generated": <epoch float>, "issues": [{"title",
    "tier", "tally", "kind"}]}`. Both the `{"issues": [...]}` wrapper and a bare list are
    accepted, matching `harness_common._read_active_issues`, so the two readers cannot
    disagree about what a valid file is.
    """
    p = path or ACTIVE_ISSUES_PATH
    st = _source_state(p)
    st.update({"writer": "scripts/system2_register.py::write_active_issues",
               "read_only": True, "generated": None, "generated_age_days": None,
               "writer_cap": _active_issues_cap(), "register_present": SYSTEM2_REGISTER_PATH.exists()})
    if not st["exists"]:
        return None, st
    try:
        data = json.loads(p.read_text(encoding="utf-8"))
    except Exception as exc:
        st["error"] = f"{type(exc).__name__}: {exc}"
        return None, st
    items = data.get("issues", data) if isinstance(data, dict) else data
    if not isinstance(items, list):
        st["error"] = "no `issues` list in the store"
        return None, st
    if isinstance(data, dict):
        st["generated"] = data.get("generated")
        st["generated_age_days"] = _age_days(data.get("generated"))
    return [i for i in items if isinstance(i, dict)], st


def _active_issues_cap() -> int | None:
    """`ACTIVE_ISSUES_MAX` from the writer — imported, never restated (it is one vocabulary)."""
    try:
        from system2_register import ACTIVE_ISSUES_MAX
        return int(ACTIVE_ISSUES_MAX)
    except Exception:                              # pragma: no cover — defensive
        return None


def process(path: Path | None = None) -> list[dict]:
    """Feed B — System-2 dev-loop/harness issues at their tier. **Read-only.**

    Vocabulary is the store's own (`title`, `tier`, `tally`), passed through rather than
    renamed. An unrecognised tier renders as itself: coercing it to the nearest known value
    is how a board hides an enum drift (the same rule S2's status column follows).
    """
    issues, _ = _read_active_issues(path)
    if not issues:
        return []
    order = {"human-reviewed": 0, "agent-reviewed": 1, "automatic": 2}
    rows = [{
        "source": "system2_active_issues",
        "title": str(i.get("title") or "").strip(),
        "tier": i.get("tier"),
        "tally": i.get("tally"),
        "kind": i.get("kind"),
        "governor": "/skeft-qa:debrief",
    } for i in issues]
    rows.sort(key=lambda r: (order.get(str(r["tier"]), 3),
                             -(r["tally"] if isinstance(r["tally"], int) else 0)))
    return rows


# ─────────────────────────────────────────────────────────────────────────────
# feed C — decisions
# ─────────────────────────────────────────────────────────────────────────────
def _read_blocked_questions(path: Path | None = None) -> tuple[list[dict] | None, dict]:
    """`(rows, state)` from the JSONL log. Malformed lines are COUNTED, never skipped silently.

    Shape measured on this machine: one object per ask —
    `{"ts": <epoch float>, "session_id": str, "questions": [{"question", "header",
    "options": [{"label", "description"}], "multiSelect": bool}]}`.
    """
    p = path or BLOCKED_QUESTIONS_PATH
    st = _source_state(p)
    st.update({"writer": "PreToolUse(AskUserQuestion) guard",
               "consumers": ["skeft-qa:coach (in-time)",
                             "skeft-qa:harvest-extractor (asynchronous)"],
               "lines": 0, "malformed_lines": 0})
    if not st["exists"]:
        return None, st
    rows: list[dict] = []
    try:
        text = p.read_text(encoding="utf-8", errors="replace")
    except Exception as exc:                       # pragma: no cover — defensive
        st["error"] = f"{type(exc).__name__}: {exc}"
        return None, st
    for line in text.splitlines():
        if not line.strip():
            continue
        st["lines"] += 1
        try:
            obj = json.loads(line)
        except json.JSONDecodeError:
            st["malformed_lines"] += 1
            continue
        if isinstance(obj, dict):
            rows.append(obj)
        else:
            st["malformed_lines"] += 1
    return rows, st


def _question_class(q: dict) -> str:
    """The class key an ask is counted under: its `header`, normalised.

    ⚠️ The header is the asker's own category label and is the ONLY class signal in the
    store. It is a weak key — two different questions can share one header, and one class can
    be worded two ways — and `graduation_signal()` reports that rather than implying the
    partition is authoritative.
    """
    return (str(q.get("header") or "").strip().lower() or "(no header)")


def decisions(nodes: list[dict] | None = None,
              path: Path | None = None,
              now: float | None = None) -> list[dict]:
    """Feed C — operator-only calls: blocked questions, plus `needs_operator: now` findings.

    Two vocabularies again, by `source`:

    * `source='blocked_question'` — the ask itself with its options, its session, and its
      **age**. D12's diagnosis is that feed C lacks *"an operator-facing surface and a latency
      floor"*, not a reader — the log already has two live consumers (`coach`,
      `harvest-extractor`), so age is the load-bearing new field here.
    * `source='review_finding'` — a finding whose `needs_operator` is `now`. ⚠️ These also
      appear in feed A, which lists every `needs_operator` finding: D15 places `now` in both
      panes deliberately, so each carries `also_in` to make the overlap visible rather than
      look like a double count.
    """
    rows, _ = _read_blocked_questions(path)
    out: list[dict] = []
    for r in (rows or []):
        ts = r.get("ts")
        for idx, q in enumerate(r.get("questions") or []):
            if not isinstance(q, dict):
                continue
            out.append({
                "source": "blocked_question",
                "id": f"bq:{ts}:{idx}",
                "ts": ts,
                "age_days": _age_days(ts, now),
                "session_id": r.get("session_id"),
                "header": q.get("header"),
                "question": q.get("question"),
                "options": [{"label": o.get("label"), "description": o.get("description")}
                            for o in (q.get("options") or []) if isinstance(o, dict)],
                "multi_select": q.get("multiSelect"),
                "class": _question_class(q),
                # ⚠️ UNKNOWN, AND NOT DERIVABLE. The log records asks; nothing records that an
                # ask was answered — not the coach, not `/debrief`. `False` would claim every
                # historical question is still waiting; `True` would clear them on no evidence.
                "resolved": None,
                "graduation_affordance": {
                    "route": "/skeft-qa:debrief",
                    "action": "graduate this decision into a standing pre-decision",
                    "store": str(PRE_DECISIONS_PATH.relative_to(PROJECT_ROOT)),
                },
            })
    out.sort(key=lambda r: (-(r["ts"] if isinstance(r["ts"], (int, float)) else 0)))

    for n in _open_findings(nodes):
        m = n.get("meta") or {}
        if (m.get("needs_operator") or "") != "now":
            continue
        out.append({
            "source": "review_finding",
            "id": n["id"],
            "label": str(n.get("label", ""))[:160],
            "urgency": "now",
            "severity": m.get("severity"),
            "lane": m.get("lane") or "unclassified",
            "target": m.get("target"),
            "also_in": "publication",
        })
    return out


def _graduated_pre_decisions(path: Path | None = None) -> tuple[int | None, str]:
    """`(count, basis)` for the `### Graduated pre-decisions` section, or `(None, why)`.

    ⚠️ `None` when the section is absent — unknown, not zero. Zero graduations and an
    unreadable store produce the same-looking pane otherwise, and the whole point of the
    signal is that a zero is meaningful.
    """
    p = path or PRE_DECISIONS_PATH
    if not p.exists():
        return None, f"{p.name} not present"
    text = p.read_text(encoding="utf-8", errors="replace")
    m = re.search(r"^#+ Graduated pre-decisions\b[^\n]*$", text, re.MULTILINE)
    if not m:
        return None, "no `Graduated pre-decisions` section in the store"
    section = text[m.end():]
    nxt = re.search(r"^#{2,3} ", section, re.MULTILINE)
    if nxt:
        section = section[: nxt.start()]
    n = len([ln for ln in section.splitlines()
             if re.match(r"^\s*(?:[-*]\s+\S|#{4,}\s+\S)", ln)])
    return n, "bullet or h4+ entries under `### Graduated pre-decisions`"


def graduation_signal(path: Path | None = None,
                      pre_decisions_path: Path | None = None) -> dict:
    """Ask-rate against graduation-rate (D12's process-defect detector).

    *"A class asked more than once with no graduated pre-decision behind it is a **process
    defect**"* — and this emits what is computable plus an explicit account of what is not.

    ⚠️ **THE ATTRIBUTION IS NOT COMPUTABLE AND IS NOT FAKED.** Nothing links a graduated
    pre-decision back to the question class that motivated it: `PRE_DECISIONS.md` carries no
    source-question id and `blocked_questions.jsonl` carries no outcome. So per-class
    graduation is reported as `None`, and `repeat_classes` is the honest observable — a class
    asked twice, which is *a candidate defect pending that attribution*, not a proven one.
    """
    rows, st = _read_blocked_questions(path)
    classes: dict[str, dict] = {}
    asks = 0
    for r in (rows or []):
        for q in (r.get("questions") or []):
            if not isinstance(q, dict):
                continue
            asks += 1
            k = _question_class(q)
            c = classes.setdefault(k, {"asks": 0, "sessions": set(),
                                       "first_ts": None, "last_ts": None,
                                       "graduated_pre_decision": None})
            c["asks"] += 1
            if r.get("session_id"):
                c["sessions"].add(r["session_id"])
            ts = r.get("ts")
            if isinstance(ts, (int, float)):
                c["first_ts"] = ts if c["first_ts"] is None else min(c["first_ts"], ts)
                c["last_ts"] = ts if c["last_ts"] is None else max(c["last_ts"], ts)
    for c in classes.values():
        c["sessions"] = len(c["sessions"])
    graduated, basis = _graduated_pre_decisions(pre_decisions_path)
    return {
        "source_available": rows is not None,
        "asks_total": asks if rows is not None else None,
        "classes": classes,
        "repeat_classes": sorted(k for k, c in classes.items() if c["asks"] > 1),
        "graduated_pre_decisions": graduated,
        "graduated_basis": basis,
        "class_key": "the ask's `header`, lowercased",
        "not_computable": [
            "which graduated pre-decision (if any) answers a given question class — "
            "no back-link exists in either store",
            "whether any logged question was ever resolved — asks are logged, outcomes "
            "are not",
        ],
        "store": st,
    }


# ─────────────────────────────────────────────────────────────────────────────
# feed D — parked
# ─────────────────────────────────────────────────────────────────────────────
def _release_state(conditions: list[dict]) -> str:
    """`released` / `parked` / `unknown` — three-valued, with `unknown` DOMINANT.

    ⚠️ Order matters and is the whole point. One unresolvable token makes the item's state
    unknown even when every other token is satisfied: releasing on partial evidence is the
    failure the three-valued contract exists to prevent. An item with no conditions at all
    cannot reach `released` either — `parked_items` rejects that shape at parse time, and
    treating "no evidence" as "all conditions met" is the same bug by another route.
    """
    if not conditions:
        return "unknown"
    if any(c["met"] is None for c in conditions):
        return "unknown"
    return "released" if all(c["met"] is True for c in conditions) else "parked"


def parked(items: list[dict] | None = None) -> list[dict]:
    """Feed D — parked work with each release condition re-evaluated NOW.

    Every condition carries `met: True | False | None`. **`None` is not `False`** — see
    `parked_items.release_condition_met`; `run:` is `None` by design until a run registry
    exists, and it is the most common token in the corpus.
    """
    import parked_items
    src = parked_items.collect() if items is None else items
    out: list[dict] = []
    for it in src:
        m = it.get("meta") or {}
        conds = []
        for tok in (m.get("blocked_by") or []):
            try:
                met = parked_items.release_condition_met(tok)
            except Exception as exc:               # pragma: no cover — defensive
                conds.append({"token": tok, "met": None,
                              "why": f"{type(exc).__name__}: {exc}"})
                continue
            conds.append({
                "token": tok,
                "met": met,
                "why": ("cannot be determined from any store that exists today"
                        if met is None else None),
            })
        out.append({
            "source": "parked_item",
            "id": it.get("id"),
            "lane": m.get("lane"),
            "target": m.get("target"),
            "reason": m.get("reason"),
            "declared_in": m.get("source"),
            "conditions": conds,
            "state": _release_state(conds),
        })
    out.sort(key=lambda r: ({"released": 0, "unknown": 1, "parked": 2}.get(r["state"], 3),
                            str(r["id"])))
    return out


# ─────────────────────────────────────────────────────────────────────────────
# coverage + caveats
# ─────────────────────────────────────────────────────────────────────────────
def coverage(nodes: list[dict] | None = None,
             active_issues_path: Path | None = None,
             blocked_questions_path: Path | None = None,
             parked_source: list[dict] | None = None,
             qi_items: list[dict] | None = None,
             qi_error: str | None = None) -> dict:
    """What each feed CAN and CANNOT see. Per feed, always, in one call.

    Every bucket set here **partitions** its population and asserts it, for the same reason
    `sentence_findings.coverage` does: a partition asserted in prose is one that drifts, and
    the failure is silent — a feed that quietly drops a bucket looks exactly like a feed with
    nothing in that bucket.
    """
    findings = _open_findings(nodes)
    buckets = Counter(_needs_operator_bucket((n.get("meta") or {}).get("needs_operator"))
                      for n in findings)
    now_ct = buckets["needs_operator_now"]
    queue_ct = buckets["needs_operator_queue"]
    other_ct = buckets["needs_operator_unrecognised_value"]
    none_ct = buckets["no_needs_operator"]
    assert now_ct + queue_ct + other_ct + none_ct == len(findings), (
        "the needs_operator buckets do not partition the open finding population")

    if qi_items is None and qi_error is None:
        qi_items, qi_error = _load_qi_items()

    issues, b_state = _read_active_issues(active_issues_path)
    rows, c_state = _read_blocked_questions(blocked_questions_path)

    import parked_items
    roadmaps = PROJECT_ROOT / "docs" / "roadmaps"
    park_rows = parked(parked_source)
    released = sum(1 for r in park_rows if r["state"] == "released")
    still = sum(1 for r in park_rows if r["state"] == "parked")
    unknown = sum(1 for r in park_rows if r["state"] == "unknown")
    assert released + still + unknown == len(park_rows), (
        "the parked release-state buckets do not partition the parked population")
    unresolvable_tokens = sum(1 for r in park_rows for c in r["conditions"]
                              if c["met"] is None)

    return {
        "publication": {
            "open_findings": len(findings),
            "needs_operator_now": now_ct,
            "needs_operator_queue": queue_ct,
            "needs_operator_unrecognised_value": other_ct,
            "no_needs_operator": none_ct,
            "qi_items_open": len(qi_items or []),
            "qi_error": qi_error,
            "qi_register_open_items_on_disk": len(_qi_register_open_items()),
            "decision_package_components_machine_checkable": 1,
            "decision_package_components_total": len(DECISION_PACKAGE_COMPONENTS),
        },
        "process": dict(b_state, items=(len(issues) if issues is not None else None),
                        population_recoverable=False),
        "decisions": dict(
            c_state,
            questions=(sum(len(r.get("questions") or []) for r in rows)
                       if rows is not None else None),
            needs_operator_now=now_ct,
            oldest_pending_days=max(
                [d for d in (_age_days(r.get("ts")) for r in (rows or []))
                 if d is not None], default=None),
            resolution_recorded=False),
        "parked": {
            "roadmap_files_scanned": (len(list(roadmaps.glob("*.md")))
                                      if roadmaps.is_dir() else 0),
            "roadmaps_dir_present": roadmaps.is_dir(),
            "declared_blocks": len(park_rows),
            "released": released,
            "parked": still,
            "unknown": unknown,
            "unresolvable_conditions": unresolvable_tokens,
            "release_schemes": list(parked_items.RELEASE_SCHEMES),
            "opt_in": True,
        },
    }


def caveats(cov: dict) -> list[str]:
    """The sentences the pane MUST render beside the feeds. Not optional, never empty.

    A reader who sees a short feed concludes little needs them. That conclusion is only
    warranted for the part of each store this layer can actually see — and for three of the
    four feeds, the store is gitignored and local-only.
    """
    out: list[str] = []

    p = cov["publication"]
    out.append(
        f"Publication shows the {p['needs_operator_now'] + p['needs_operator_queue']} open "
        f"findings that declare `needs_operator`; {p['no_needs_operator']} open findings "
        f"declare nothing and are NOT shown — the field is forward-only, so an absent value "
        f"means unrouted, not resolved.")
    out.append(
        f"Only {p['decision_package_components_machine_checkable']} of "
        f"{p['decision_package_components_total']} D11 decision-package components is "
        f"machine-checkable (orientation, via the finding's target). The other four are "
        f"prose judgements with no field in any store — an item here may still be deferred "
        f"rather than routed.")
    if p["qi_error"]:
        out.append(f"The QI derivation did not run: {p['qi_error']}. Its items are MISSING "
                   f"from this pane, not absent from the corpus.")

    b = cov["process"]
    if not b["exists"]:
        out.append(
            f"Process has NO STORE on this machine: `{b['path']}` is absent"
            + (" and is gitignored (local-only), so a fresh clone never has it"
               if b["local_only"] else "")
            + ". This pane is blank because it cannot see, not because nothing is open.")
    else:
        cap = b.get("writer_cap")
        age = b.get("generated_age_days")
        out.append(
            f"Process reads `{b['path']}` — gitignored and local-only, written by "
            f"{b['writer']}, read-only here (/skeft-qa:debrief is the sole governor). It is "
            f"a top-{cap} view by tier then tally, so {b['items']} is a FLOOR: the register's "
            f"true open count is not recoverable from this store"
            + (f", and the view was generated {age} days ago." if age is not None else "."))
        if b.get("error"):
            out.append(f"Process store unreadable: {b['error']}.")

    c = cov["decisions"]
    if not c["exists"]:
        out.append(
            f"Decisions has NO STORE on this machine: `{c['path']}` is absent"
            + (" and is gitignored (local-only)" if c["local_only"] else "")
            + " — blocked questions asked on another machine cannot be seen from here.")
    else:
        oldest = c.get("oldest_pending_days")
        out.append(
            f"Decisions reads `{c['path']}` ({c['questions']} question(s) across "
            f"{c['lines']} logged asks"
            + (f", oldest {oldest} days old" if oldest is not None else "")
            + f"). The log records asks, NOT outcomes: no store says whether any of these "
            f"was ever answered, so none can be shown as resolved.")
        if c.get("malformed_lines"):
            out.append(f"{c['malformed_lines']} line(s) in the blocked-question log did not "
                       f"parse and are counted, not shown.")
    if c["needs_operator_now"]:
        out.append(f"{c['needs_operator_now']} `needs_operator: now` finding(s) appear in "
                   f"BOTH Decisions and Publication by design (D15); they carry `also_in`.")

    d = cov["parked"]
    if not d["roadmaps_dir_present"]:
        out.append("Parked found no `docs/roadmaps/` directory — the feed is unreadable "
                   "here, not empty.")
    else:
        out.append(
            f"Parked scanned {d['roadmap_files_scanned']} roadmap file(s) and found "
            f"{d['declared_blocks']} declared `<!-- PARKED -->` block(s). Declaration is "
            f"opt-in: work parked in prose but never declared is INVISIBLE to this pane.")
    if d["unresolvable_conditions"]:
        out.append(
            f"{d['unresolvable_conditions']} release condition(s) cannot be evaluated and "
            f"are UNKNOWN, not unmet — `run:` is unresolvable by design until a run registry "
            f"exists. {d['unknown']} item(s) are in the unknown state as a result.")
    return out


# ─────────────────────────────────────────────────────────────────────────────
# aggregator
# ─────────────────────────────────────────────────────────────────────────────
def attention() -> dict:
    """The whole surface: four unmerged feeds, their coverage, and their caveats.

    ⚠️ The caller cannot obtain the items without `coverage` and `caveats` — they are keys of
    the one return value, not a second call an implementer can forget. That is deliberate: a
    pane that renders four lists and drops the sentences explaining what the lists cannot see
    is the exact defect this module was built to avoid, one level up.
    """
    from build_graph import extract_review_finding_nodes
    nodes = extract_review_finding_nodes()
    qi_items, qi_error = _load_qi_items()
    import parked_items
    park_src = parked_items.collect()
    cov = coverage(nodes, parked_source=park_src, qi_items=qi_items, qi_error=qi_error)
    return {
        "publication": publication(nodes, qi_items=qi_items, qi_error=qi_error),
        "process": process(),
        "decisions": decisions(nodes),
        "parked": parked(park_src),
        "graduation": graduation_signal(),
        "coverage": cov,
        "caveats": caveats(cov),
    }


if __name__ == "__main__":  # pragma: no cover — operator convenience
    a = attention()
    for feed in ("publication", "process", "decisions", "parked"):
        print(f"{feed:12} {len(a[feed])} item(s)")
    print(json.dumps(a["coverage"], indent=2, default=str))
    print(json.dumps(a["graduation"], indent=2, default=str))
    for line in a["caveats"]:
        print(f"⚠️  {line}")
