#!/usr/bin/env python3
"""Per-bundle substrate counts, derived from the declared-apex closure.

Why this exists
---------------
`docs/counts.tex` defines `\\substantivetheorems`, a **project-wide** figure (tens of
thousands). Six manuscript sites used it as if it were **paper-scoped** — E2's
verification-chain parenthetical, E1's twice, D1's *"End-to-end"* sentence, D5's
*"organises all N substantive Phase 6m theorems"*, and F's *"in this sector"* — so each
stated the whole library's theorem count as its own. Measured 2026-08-09 the gap is not
marginal: E2 claimed 26 329 against a verified chain of **6** theorems, and E1 against
**11**.

⚠️ **The anti-drift mechanism was the overclaim's source, which is why the fix is another
generated macro rather than a hand-typed number.** `\\substantivetheorems` exists so nobody
hand-maintains a count, and `count_literals` *rewards* a draft for using it. It also grows
with the library, so the overclaim inflates on its own with every unrelated wave.

What it emits
-------------
`papers/<CODE>/bundle_counts.tex` for every bundle in the roster, defining:

* `\\bundleTheorems` — author-written `theorem`-kind declarations in the bundle's apex
  closure. Compiler-generated equation lemmas are excluded, the same convention
  `update_counts.py` applies project-wide, so the two figures are comparable.
* `\\bundleDecls` — every declaration in the closure, theorem or not.
* `\\bundleModules` — modules those declarations live in.

A bundle that declares no apexes gets **no file**: its substrate is UNKNOWN, not zero, and
emitting `0` would let a draft print a confident wrong number. Its absence is loud, because
the `\\input` fails the compile.

⚠️ **These are closure figures, so they inherit the closure's caveat**: a walk stops at a
`private` declaration (`ExtractDeps` omits them), so the count is a lower bound. Report it
as such wherever the exact value carries weight.

Usage
-----
    uv run python scripts/render_bundle_counts.py            # write
    uv run python scripts/render_bundle_counts.py --check    # exit 1 if any file is stale
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

_HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(_HERE))
sys.path.insert(0, str(_HERE.parent))

import bundle_closure as bc  # noqa: E402
from bundle_registry import BUNDLE_CODES, bundle_sort_key  # noqa: E402

PAPERS = _HERE.parent / "papers"

_HEADER = (
    "%% GENERATED by scripts/render_bundle_counts.py — do not edit.\n"
    "%% Per-bundle substrate counts, derived from this bundle's declared apex closure\n"
    "%% (papers/<CODE>/bundle_metadata.json -> apex_theorems -> lean_deps.json).\n"
    "%% Use these for any statement about THIS paper's verified content.\n"
    "%% \\substantivetheorems in docs/counts.tex is PROJECT-wide; using it for a\n"
    "%% paper-scoped claim overstates by orders of magnitude (TODO-D9).\n"
    "%% Closure walks stop at `private` declarations, so these are lower bounds.\n"
)


def render(code: str, closures, by_name) -> str | None:
    """The LaTeX body for one bundle, or `None` when its substrate is unmeasurable."""
    c = closures.get(code)
    if c is None or not c.measurable:
        return None
    theorems = sum(
        1 for n in c.closure
        if by_name[n].get("kind") == "theorem" and not by_name[n].get("autogen"))
    return (
        _HEADER
        + f"\\newcommand{{\\bundleTheorems}}{{{theorems}}}\n"
        + f"\\newcommand{{\\bundleDecls}}{{{len(c.closure)}}}\n"
        + f"\\newcommand{{\\bundleModules}}{{{len(c.modules)}}}\n")


def build() -> dict[str, str | None]:
    recs = bc.load_records()
    by_name = {r["name"]: r for r in recs}
    closures = bc.build_closures(recs, bc.load_apex_declarations(PAPERS))
    return {code: render(code, closures, by_name)
            for code in sorted(BUNDLE_CODES, key=bundle_sort_key)}


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if any tracked file differs from a fresh render")
    args = ap.parse_args(argv)

    stale, written, skipped = [], [], []
    for code, body in build().items():
        target = PAPERS / code / "bundle_counts.tex"
        if body is None:
            skipped.append(code)
            continue
        current = target.read_text() if target.is_file() else None
        if current == body:
            continue
        if args.check:
            stale.append(code)
        else:
            target.write_text(body)
            written.append(code)

    if skipped:
        print(f"no apexes declared, no file emitted (substrate UNKNOWN): {', '.join(skipped)}")
    if args.check:
        if stale:
            print(f"STALE: {', '.join(stale)} — run scripts/render_bundle_counts.py")
            return 1
        print("every bundle_counts.tex matches a fresh render")
        return 0
    print(f"wrote {len(written)} file(s)" + (f": {', '.join(written)}" if written else ""))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
