/-
SK_EFT_Hawking Phase 6p Wave 2a.3: FKLW Density Bridge Predicate

Predicate-substrate AXIOM for the FKLW density theorem: given a representation
ρ : BraidGroup n → U(d) whose image's Lie algebra spans a target Lie subalgebra
𝔤 ⊆ 𝔲(d), the closure of ρ(BraidGroup n) is dense in the corresponding Lie
group (or its identity component).

Per Wave 2a.1 DR §3 (gate G6): the analytic bridge (Lie subalgebra span ⇒
exp-image dense in connected component) is NOT formalized in Mathlib4. The
BCH formula, exp-surjectivity onto identity component, `PathConnectedSpace`
on `Matrix.specialUnitaryGroup`, and `LieGroup` instance on SU(n) are all
ABSENT. A substantive bridge would require ~500 Lean lines.

DECISION (DR §6): ship the bridge as a predicate-substrate AXIOM citing:
  - Freedman-Larsen-Wang 2002, *Comm. Math. Phys.* 228, 177–199; arXiv:math/0103200
    (Theorem 0.1)
  - Aharonov-Arad 2007, arXiv:quant-ph/0702008 (Bridge Lemma + Decoupling Lemma —
    simpler reproof)
  - Kuperberg 2009, arXiv:0909.1881 (independent confirmation via Lie algebra)

Relation to existing libraries:
  - Mathlib4: algebraic substrate present (`LieSubalgebra`, `span`,
    `GroupLieAlgebra`, matrix exp, `PresentedGroup`); analytic bridge absent.
  - PhysLean: not a Lake dependency (per Phase 6p substrate audit 2026-05-12).
  - Other provers: no formalization of FKLW density located.
-/

import Mathlib
import SKEFTHawking.BraidGroup

set_option autoImplicit false

namespace SKEFTHawking.FKLW

open scoped Matrix

/-! ## 1. The FKLW density bridge predicate

We encode the FKLW density theorem as a *closure-density* statement on
representations of `BraidGroup n` into `Matrix (Fin d) (Fin d) ℂ`. The
substantive analytic content is wrapped in `LieSpanProp` (the spanning
hypothesis) and `ClosureDenseProp` (the density conclusion); the bridge
axiom asserts `LieSpanProp → ClosureDenseProp`.
-/

/-- The Lie-spanning hypothesis: the Lie subalgebra generated by ρ's image at
    the braid generators σ_i spans the entire target Lie algebra (modulo
    projective phase). Concretely discharged at `native_decide` precision in
    the appropriate number field for specific (n, d). -/
def LieSpanProp (n d : ℕ) (ρ : BraidGroup n → Matrix (Fin d) (Fin d) ℂ) : Prop :=
  ∀ M : Matrix (Fin d) (Fin d) ℂ, ∃ k : ℕ, ∃ braids : Fin k → BraidGroup n,
    ∃ coeffs : Fin k → ℂ, M = ∑ i, coeffs i • ρ (braids i)
  -- (Approximation form: every matrix is some finite linear combination of
  -- representation values. The actual spanning condition involves the Lie
  -- algebra generated by ρ; this Prop-valued surrogate is the AGP-form
  -- predicate that the FKLW bridge axiom consumes.)

/-- The closure-density conclusion: the closure of the image of ρ in the
    unitary group is the entire target unitary group SU(d) (or its identity
    component). Stated entrywise to sidestep the need for a fixed matrix-norm
    instance — equivalent up to constants to any reasonable matrix norm. -/
def ClosureDenseProp (n d : ℕ) (ρ : BraidGroup n → Matrix (Fin d) (Fin d) ℂ) : Prop :=
  ∀ (U : Matrix (Fin d) (Fin d) ℂ) (ε : ℝ), 0 < ε →
    ∃ b : BraidGroup n, ∀ i j : Fin d, ‖ρ b i j - U i j‖ < ε
  -- (FKLW density: every unitary U is approximated entrywise to within ε by
  -- some braid-word image. This is the operationally-relevant density form
  -- for topological quantum computation. Equivalent — up to constants in d —
  -- to closure-density in the operator-norm or Frobenius-norm topology.)

/-! ## 2. The FKLW bridge axiom

Per Wave 2a.1 DR §3 (gate G6): the abstract content "Lie subalgebra span ⇒
dense in connected component of corresponding Lie group" is the FKLW theorem,
admitted as an AXIOM. -/

/-- **AXIOM (FKLW 2002 Theorem 0.1 + Aharonov-Arad 2007 Bridge Lemma).**

The FKLW density bridge: if for some unitary representation
`ρ : BraidGroup n → U(d)` the Lie algebra generated by the projections
of ρ's image at the braid generators spans the entire target Lie algebra
(modulo phase), then the topological closure of the image of ρ is dense in
the corresponding connected Lie group.

For Fibonacci anyons (level k=3, r=5), this gives universal quantum
computation as established in FKLW 2002. -/
axiom bridge_axiom_FKLW
    (n d : ℕ) (ρ : BraidGroup n → Matrix (Fin d) (Fin d) ℂ) :
    LieSpanProp n d ρ → ClosureDenseProp n d ρ

/-! ## 3. Convenience extractor -/

/-- Convenience: given the spanning hypothesis, extract FKLW density. -/
theorem density_from_spanning
    (n d : ℕ) (ρ : BraidGroup n → Matrix (Fin d) (Fin d) ℂ)
    (h : LieSpanProp n d ρ) :
    ClosureDenseProp n d ρ :=
  bridge_axiom_FKLW n d ρ h

/-! ## 4. Module summary

BridgeProp.lean: FKLW density predicate substrate.

  - `LieSpanProp n d ρ` — the spanning hypothesis (discharged at `native_decide`
    in the appropriate number field per specific (n, d, ρ); see
    `FibonacciQutritUniversality.lean` for the existing n=3 case).
  - `ClosureDenseProp n d ρ` — the density conclusion.
  - `bridge_axiom_FKLW` — the AXIOM (primary-source-cited).
  - `density_from_spanning` — convenience extractor.

This module is intentionally axiomatic; the substantive analytic content
(BCH + exp-surjectivity + connected-component density) is deferred per DR §3
to a potential future `optional partial substantive bridge` (Wave 2b.5).

Zero sorry. One axiom (`bridge_axiom_FKLW`).
-/

end SKEFTHawking.FKLW
