/-
Copyright (c) 2026 John Roehm. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: John Roehm

# Phase 6y Track S.1 — Generic SU(d) generating-set framework

Generalizes the Phase 6u `GenericSU2.GeneratingSet` (carrier
`ρ_hom : W →* specialUnitaryGroup (Fin 2) ℂ`) to arbitrary matrix
dimension `d : ℕ` (carrier `ρ_hom : W →* specialUnitaryGroup (Fin d) ℂ`).
This is the substrate **keystone** for the Phase 6y SU(d) extension
chain (S.2 Cartan v4 at SU(d), S.3 Dawson-Nielsen at 𝔰𝔲(d), S.4
d-dependent Lipschitz, S.5 generic discharge, S.6 generic bundled-
strict headline).

## Design

A `GeneratingSet d` bundles:

  * `W : Type` — abstract word type, with a `Group W` instance;
  * `ρ_hom : W →* ↥(specialUnitaryGroup (Fin d) ℂ)` — the representation;
  * `gens : Finset W` — explicit finite generating set;
  * `gens_nonempty : gens.Nonempty`;
  * `gens_generate : Subgroup.closure (gens : Set W) = ⊤`.

The closed subgroup of SU(d) generated by `gs` is
  `H_of_G gs := gs.ρ_hom.range.topologicalClosure : Subgroup ↥(SU(d))`.

For Phase 6y Track T-A1′ (trapped-ion full SU(4) instance, d = 4):
the generators are MS(θ) at rational-π/N grid + per-ion 1Q rotations.

For Phase 6y Track T-A2′ (full SU(8) Clifford+CCZ instance, d = 8):
the generators are per-qubit Hadamard (3) plus CCZ.

The d = 2 specialization is bridged to the Phase 6u
`GenericSU2.GeneratingSet` in §3 (`ofGenericSU2`), preserving `H_of_G`
on the nose.

## Pipeline invariants

  * **#10** (no `maxHeartbeats`): respected.
  * **#15** (no new project-local axioms): respected. Phase 6y Track S
    composes only Mathlib4 v4.29.1 primitives.
  * Preemptive-strengthening 5-question checklist: each public lemma
    is load-bearing (consumed by S.2-S.6 + T-A1′ + T-A2′); no
    P3/P4/P5 tautologies.

## Phase 6y Track S provenance

Phase 6y Roadmap §"Track S detail" sub-wave S.1.

-/

import Mathlib.LinearAlgebra.UnitaryGroup
import Mathlib.Topology.Algebra.Group.Basic
import SKEFTHawking.FKLW.GenericSU2GeneratingSet

set_option autoImplicit false

namespace SKEFTHawking.FKLW.GenericSUd

open Matrix
open scoped Classical

/-! ## 1. The `GeneratingSet d` framework

The fundamental Phase 6y abstraction underlying every Track S+ wave:
a finite-rank SU(d) generating set with its abstract word-group source
and the representation homomorphism. The dimension `d` is a structure
parameter so that multiple instances at different dimensions (d = 4
for T-A1′, d = 8 for T-A2′, d = 2 for the SU(2) bridge) can coexist. -/

/-- **A generic SU(d) generating-set framework.**

Carries the abstract word type `W` (a group), the representation
`ρ_hom : W →* ↥(specialUnitaryGroup (Fin d) ℂ)`, and an explicit finite
generating set `gens : Finset W` that generates `W` as a group.

For Phase 6y Track T-A1′ (trapped-ion full SU(4)):
- `d = 4`
- `W = FreeGroup (...)` with MS(θ) tokens at rational-π/N grid + per-ion 1Q tokens
- `ρ_hom` = the obvious word-evaluation map into `specialUnitaryGroup (Fin 4) ℂ`

For Phase 6y Track T-A2′ (full SU(8) Clifford+CCZ):
- `d = 8`
- `W = FreeGroup (Fin 4)` encoding `{H₁, H₂, H₃, CCZ}`
- `ρ_hom` = the 3-qubit gate evaluation into `specialUnitaryGroup (Fin 8) ℂ`

The `gens_generate` field is structurally load-bearing for the
constructive ε₀-net per-alphabet (`finite-Finset` cover per
Phase 6x failure-mode-#5 fix, not `Classical.choose` existential). -/
structure GeneratingSet (d : ℕ) where
  /-- Abstract word type. -/
  W : Type
  /-- `W` is a group. -/
  [Wgroup : Group W]
  /-- Representation as a group homomorphism into SU(d). -/
  ρ_hom : W →* ↥(Matrix.specialUnitaryGroup (Fin d) ℂ)
  /-- Explicit finite generator set. -/
  gens : Finset W
  /-- The generator set is non-empty. -/
  gens_nonempty : gens.Nonempty
  /-- `gens` generates `W` as a group. -/
  gens_generate : Subgroup.closure (gens : Set W) = (⊤ : Subgroup W)

attribute [instance] GeneratingSet.Wgroup

/-! ## 2. The closed subgroup `H_of_G`

The closed subgroup of SU(d) generated by the representation's range,
topologized via `Subgroup.topologicalClosure`. Mirrors the Phase 6u
SU(2) construction at arbitrary d. -/

/-- **The closed subgroup of SU(d) generated by `gs`'s representation.**

By definition this equals `topologicalClosure (range gs.ρ_hom)`. The
Phase 6y Track S.2 Cartan-final-step v4 at SU(d) discharges
`H_of_G gs = ⊤` from a closure-density witness at SU(d). -/
noncomputable def H_of_G {d : ℕ} (gs : GeneratingSet d) :
    Subgroup ↥(Matrix.specialUnitaryGroup (Fin d) ℂ) :=
  gs.ρ_hom.range.topologicalClosure

/-- `H_of_G gs` is closed (`Subgroup.isClosed_topologicalClosure`). -/
theorem H_of_G_isClosed {d : ℕ} (gs : GeneratingSet d) :
    IsClosed (H_of_G gs : Set ↥(Matrix.specialUnitaryGroup (Fin d) ℂ)) :=
  Subgroup.isClosed_topologicalClosure _

/-- Every image `gs.ρ_hom w` is in `H_of_G gs`. -/
theorem H_of_G_ρ_mem {d : ℕ} (gs : GeneratingSet d) (w : gs.W) :
    gs.ρ_hom w ∈ H_of_G gs := by
  apply Subgroup.le_topologicalClosure
  exact ⟨w, rfl⟩

/-- The full range of `gs.ρ_hom` is contained in `H_of_G gs`. -/
theorem range_subset_H_of_G {d : ℕ} (gs : GeneratingSet d) :
    (gs.ρ_hom.range : Subgroup _) ≤ H_of_G gs :=
  Subgroup.le_topologicalClosure _

/-! ## 3. SU(2) ↔ `GeneratingSet 2` bridge

Allows every existing Phase 6u `GenericSU2.GeneratingSet` instance
(Fibonacci, Clifford+T) to be threaded through the Phase 6y SU(d)
framework at d = 2. Useful for cross-track work that needs to specialize
the SU(d) chain at d = 2 (e.g., to validate that the SU(d) substrate
recovers the SU(2) substrate definitionally on `H_of_G`). -/

/-- **Bridge: every Phase 6u `GenericSU2.GeneratingSet` is a `GeneratingSet 2`.**

The field-for-field correspondence is mechanical: `W`, `Wgroup`,
`ρ_hom`, `gens`, `gens_nonempty`, `gens_generate` all transfer
verbatim. The only formal difference is the universally quantified
dimension parameter `d`, here instantiated at `2`. -/
def ofGenericSU2 (gs : GenericSU2.GeneratingSet) : GeneratingSet 2 where
  W := gs.W
  Wgroup := gs.Wgroup
  ρ_hom := gs.ρ_hom
  gens := gs.gens
  gens_nonempty := gs.gens_nonempty
  gens_generate := gs.gens_generate

/-- **The bridge preserves `H_of_G`** definitionally. -/
theorem H_of_G_ofGenericSU2 (gs : GenericSU2.GeneratingSet) :
    H_of_G (ofGenericSU2 gs) = GenericSU2.H_of_G gs := rfl

/-! ## 4. Smoke-test examples at the Phase 6y target dimensions

Validate that the framework type-checks at the two Phase 6y target
dimensions (d = 4 for T-A1′, d = 8 for T-A2′). These are placeholder
checks; the substantive instances ship in `TrappedIonGeneratingSetSU4.lean`
(T-A1′.1) and `CliffordCCZGeneratingSetSU8.lean` (T-A2′.1). -/

/-- **Example at d = 4** (Phase 6y Track T-A1′ target dimension): the
generic SU(4) framework type-checks. -/
example (gs : GeneratingSet 4) :
    IsClosed (H_of_G gs : Set ↥(Matrix.specialUnitaryGroup (Fin 4) ℂ)) :=
  H_of_G_isClosed gs

/-- **Example at d = 8** (Phase 6y Track T-A2′ target dimension): the
generic SU(8) framework type-checks. -/
example (gs : GeneratingSet 8) :
    IsClosed (H_of_G gs : Set ↥(Matrix.specialUnitaryGroup (Fin 8) ℂ)) :=
  H_of_G_isClosed gs

end SKEFTHawking.FKLW.GenericSUd
