/-
Copyright (c) 2026 John Roehm. All rights reserved.

# Phase 6u Wave 1 — Generic SU(2) generating-set framework

Abstracts the Phase 6t Fibonacci-specific `H_Fib` substrate over a generic
word-type `W` (a group) plus a representation `ρ_hom : W →* SU(2)`. This is
the substrate refactor that lets Track T-S (Clifford+T) reuse the entire
Phase 6t Cartan + BCH + SK-recursion + length-bound machinery without
re-deriving the Lie-algebraic core.

## Design

A `GeneratingSet` bundles:
  - `W : Type` — abstract word type, with a `Group W` instance (so `W` is
    closed under inverses);
  - `ρ_hom : W →* ↥(SU(2))` — the representation as a group homomorphism;
  - `gens : Finset W` — explicit finite generating set (used downstream by
    the ε₀-net enumeration in Wave 3);
  - `gens_generate : Subgroup.closure (gens : Set W) = ⊤` — `gens` generates
    `W` as a group.

The closed subgroup of SU(2) generated by `gs` is
  `H_of_G gs := gs.ρ_hom.range.topologicalClosure : Subgroup ↥(SU(2))`.

For the Fibonacci instance:
  - `W := BraidGroup 3`;
  - `ρ_hom := ρ_Fib_SU2`;
  - `gens := {BraidGroup.σ 0, BraidGroup.σ 1}`;
  - `gens_generate` discharged via `PresentedGroup.closure_range_of`.

By definition `H_of_G fibonacciGeneratingSet = H_Fib`, so all downstream
H_Fib-specific facts (H_Fib_isClosed, σ_Fib_i_SU ∈ H_Fib, etc.) transfer
automatically.

## Pipeline invariants

- **#10** (no `maxHeartbeats`): respected — all proofs are constructive
  and decomposed via small `have` sub-lemmas.
- **#15** (no new axioms): respected — zero new project-local axioms.
- **Preemptive-strengthening discipline**: each public lemma is either
  load-bearing (used in Wave 2+ as the Fibonacci-↔-generic bridge) or a
  generator-membership convenience that downstream proofs need. No
  trivial-discharge or self-defining-conclusion theorems.

## Module status

Phase 6u Wave 1 — ships the abstract framework + Fibonacci instance.
Zero new axioms. Zero sorries. Standard kernel only.

-/

import SKEFTHawking.FKLW.FibSU2Density
import SKEFTHawking.FKLW.AharonovAradBridgeIteration
import SKEFTHawking.BraidGroup

set_option autoImplicit false

namespace SKEFTHawking.FKLW.GenericSU2

open Matrix
open scoped Classical

/-! ## 1. The `GeneratingSet` framework

The fundamental abstraction underlying every Phase 6u wave: a finite-rank
SU(2) generating set with its abstract word-group source and the
representation homomorphism. -/

/-- **A generic SU(2) generating-set framework.**

Carries the abstract word type `W` (a group), the representation
`ρ_hom : W →* SU(2)`, and an explicit finite generating set `gens : Finset W`
that generates `W` as a group.

For the Fibonacci instance:
- `W = BraidGroup 3`
- `ρ_hom = ρ_Fib_SU2`
- `gens = {BraidGroup.σ 0, BraidGroup.σ 1}`

For Clifford+T (Phase 6u Track T-S):
- `W = FreeGroup (Fin 3)` (or a quotient encoding Clifford+T relations)
- `ρ_hom = the obvious word-evaluation map`
- `gens = {of 0, of 1, of 2}` (encoding H, T, S)

The `gens_generate` field is load-bearing for Wave 3's ε₀-net enumeration:
without it, generator-words could miss elements of `ρ_hom.range`. -/
structure GeneratingSet where
  /-- Abstract word type. -/
  W : Type
  /-- `W` is a group. -/
  [Wgroup : Group W]
  /-- Representation as a group homomorphism into SU(2). -/
  ρ_hom : W →* ↥(Matrix.specialUnitaryGroup (Fin 2) ℂ)
  /-- Explicit finite generator set.

  **Status (Phase 6u Session 1):** the `gens` field is NOT consumed by
  the shipped Wave 3 existential ε₀-net (which uses `Classical.choose`
  directly from Wave 2's density). It IS consumed at instantiation
  sites (Fibonacci, Clifford+T) to provide the structural
  finitely-generated constraint via `gens_generate`. The field is
  forward-looking substrate for the constructive ε₀-net (per-alphabet
  enumeration), which is per-alphabet Track work. CP1 RC1 audit
  acknowledged: this is **anticipatory abstraction** rather than dead
  code, since the constructive-net path will need it. -/
  gens : Finset W
  /-- The generator set is non-empty. -/
  gens_nonempty : gens.Nonempty
  /-- `gens` generates `W` as a group. Load-bearing for the structural
  constraint that `W` is finitely generated and `gens` is a complete
  generating set; consumed by future constructive ε₀-net work. -/
  gens_generate : Subgroup.closure (gens : Set W) = (⊤ : Subgroup W)

attribute [instance] GeneratingSet.Wgroup

/-! ## 2. The closed subgroup `H_of_G`

The closed subgroup of SU(2) generated by the representation's range,
topologized via `Subgroup.topologicalClosure`. -/

/-- **The closed subgroup of SU(2) generated by `gs`'s representation.**

By definition this equals `topologicalClosure (range gs.ρ_hom)`. For the
Fibonacci instance this is exactly `H_Fib`. -/
noncomputable def H_of_G (gs : GeneratingSet) :
    Subgroup ↥(Matrix.specialUnitaryGroup (Fin 2) ℂ) :=
  gs.ρ_hom.range.topologicalClosure

/-- `H_of_G gs` is closed (Subgroup.isClosed_topologicalClosure). -/
theorem H_of_G_isClosed (gs : GeneratingSet) :
    IsClosed (H_of_G gs : Set ↥(Matrix.specialUnitaryGroup (Fin 2) ℂ)) :=
  Subgroup.isClosed_topologicalClosure _

/-- Every image `gs.ρ_hom w` is in `H_of_G gs`. -/
theorem H_of_G_ρ_mem (gs : GeneratingSet) (w : gs.W) :
    gs.ρ_hom w ∈ H_of_G gs := by
  apply Subgroup.le_topologicalClosure
  exact ⟨w, rfl⟩

/-- The full range of `gs.ρ_hom` is contained in `H_of_G gs`. -/
theorem range_subset_H_of_G (gs : GeneratingSet) :
    (gs.ρ_hom.range : Subgroup _) ≤ H_of_G gs :=
  Subgroup.le_topologicalClosure _

/-! ## 3. Fibonacci instance

Validates the abstraction by exhibiting `H_Fib` as the Fibonacci
specialization of `H_of_G`. -/

/-- The Fibonacci generator pair as a `Finset (BraidGroup 3)`.

Uses the Classical `DecidableEq` (since BraidGroup 3 is a presented group
quotient without a constructive decision algorithm in scope). -/
noncomputable def fibonacciGens : Finset (BraidGroup 3) :=
  {(SKEFTHawking.BraidGroup.σ (n := 3) ⟨0, by decide⟩),
    (SKEFTHawking.BraidGroup.σ (n := 3) ⟨1, by decide⟩)}

/-- The Fibonacci generator set is non-empty. -/
theorem fibonacciGens_nonempty : fibonacciGens.Nonempty := by
  refine ⟨SKEFTHawking.BraidGroup.σ (n := 3) ⟨0, by decide⟩, ?_⟩
  simp [fibonacciGens]

/-- The Fibonacci generators generate `BraidGroup 3` as a group.

`BraidGroup 3 = PresentedGroup (artinRelations 3)`, so it is generated as
a group by `PresentedGroup.of : Fin 2 → BraidGroup 3`, which equals
`BraidGroup.σ`. Since `Fin 2 = {0, 1}`, the range of `BraidGroup.σ` is
exactly `{σ 0, σ 1}`. Composing with `PresentedGroup.closure_range_of`
gives `closure {σ 0, σ 1} = ⊤`. -/
theorem fibonacciGens_generate :
    Subgroup.closure (fibonacciGens : Set (BraidGroup 3)) = (⊤ : Subgroup (BraidGroup 3)) := by
  -- Step 1: rewrite fibonacciGens as the image (Set.range) of BraidGroup.σ.
  have h_eq : (fibonacciGens : Set (BraidGroup 3))
              = Set.range (SKEFTHawking.BraidGroup.σ (n := 3)) := by
    ext x
    constructor
    · -- x ∈ {σ 0, σ 1} → x ∈ Set.range σ
      intro hx
      simp [fibonacciGens] at hx
      rcases hx with hx0 | hx1
      · exact ⟨⟨0, by decide⟩, hx0.symm⟩
      · exact ⟨⟨1, by decide⟩, hx1.symm⟩
    · -- x ∈ Set.range σ → x ∈ {σ 0, σ 1}
      rintro ⟨i, hi⟩
      simp [fibonacciGens]
      -- i : Fin 2; case-split on its value
      fin_cases i
      · left; exact hi.symm
      · right; exact hi.symm
  -- Step 2: closure of Set.range σ = ⊤ via PresentedGroup.closure_range_of.
  rw [h_eq]
  -- BraidGroup.σ = PresentedGroup.of unfolded
  show Subgroup.closure
        (Set.range (fun i : Fin (3 - 1) =>
          PresentedGroup.of (rels := SKEFTHawking.artinRelations 3) i)) = ⊤
  exact PresentedGroup.closure_range_of _

/-- **The Fibonacci generating-set instance.**

Validates the abstraction by exhibiting the Fibonacci Solovay-Kitaev
substrate as a `GeneratingSet`. By definition,
`H_of_G fibonacciGeneratingSet = H_Fib`. -/
noncomputable def fibonacciGeneratingSet : GeneratingSet where
  W := BraidGroup 3
  Wgroup := inferInstance
  ρ_hom := SKEFTHawking.FKLW.ρ_Fib_SU2
  gens := fibonacciGens
  gens_nonempty := fibonacciGens_nonempty
  gens_generate := fibonacciGens_generate

/-- **Validation: H_of_G specializes to H_Fib.**

By definition both are `ρ_Fib_SU2.range.topologicalClosure`, so the
equality is reflexive. This is the load-bearing bridge that lets every
H_Fib-specific Phase 6t theorem (H_Fib_isClosed, σ_Fib_i_SU ∈ H_Fib,
H_Fib_v4_witness_unconditional, etc.) transfer to the generic framework
without rework. -/
theorem H_of_G_specialize_Fib :
    H_of_G fibonacciGeneratingSet = SKEFTHawking.FKLW.H_Fib :=
  rfl

/-! ## 4. Generator membership convenience

A direct consequence of `H_of_G_ρ_mem`: for the Fibonacci instance, both
σ_Fib_1_SU and σ_Fib_2_SU are in `H_of_G fibonacciGeneratingSet` (since
they are the images of `BraidGroup.σ 0` and `BraidGroup.σ 1` under
ρ_Fib_SU2). This recovers `σ_Fib_1_SU_mem_H_Fib` / `σ_Fib_2_SU_mem_H_Fib`
through the generic framework. -/

/-- The Fibonacci generator σ_Fib_1_SU is in `H_of_G fibonacciGeneratingSet`
(equivalently, in `H_Fib` per `H_of_G_specialize_Fib`). -/
theorem fibonacci_σ_1_mem :
    SKEFTHawking.FKLW.σ_Fib_1_SU ∈ H_of_G fibonacciGeneratingSet := by
  rw [H_of_G_specialize_Fib]
  exact SKEFTHawking.FKLW.σ_Fib_1_SU_mem_H_Fib

/-- The Fibonacci generator σ_Fib_2_SU is in `H_of_G fibonacciGeneratingSet`. -/
theorem fibonacci_σ_2_mem :
    SKEFTHawking.FKLW.σ_Fib_2_SU ∈ H_of_G fibonacciGeneratingSet := by
  rw [H_of_G_specialize_Fib]
  exact SKEFTHawking.FKLW.σ_Fib_2_SU_mem_H_Fib

end SKEFTHawking.FKLW.GenericSU2
