/-
Copyright (c) 2026 John Roehm. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: John Roehm

# Phase 6y Track T-A1′.1-partial — `trappedIonGeneratingSetSU4_1Q` (4-generator instance)

A `GeneratingSet 4` instance for the trapped-ion alphabet restricted to
**single-qubit gates only** (H_SU on each ion + T_SU on each ion).
Uses Phase 6y T-A1′.1-substrate's packaged SU(4) subtype elements.

This is the **1Q-only sub-alphabet** — a substantive intermediate
ship toward the full T-A1′.1 (which adds MS(θ) at rational-π/N grid
once `MSGateMat_mem_specialUnitaryGroup` ships). The 1Q-only alphabet
generates the Clifford+T subgroup of SU(4) (acting per-ion); the full
trapped-ion alphabet adds the entangling MS gate for SU(4)-density.

## Pipeline invariants

  * **#10** (no `maxHeartbeats`): respected.
  * **#15** (no new project-local axioms): respected.

## Phase 6y Track T-A1′ provenance

Phase 6y Roadmap §"Track T-A1′ detail" sub-wave T-A1′.1 partial
(1Q-only sub-alphabet). Full alphabet (with MS) ships in T-A1′.1
proper once MSGate SU(4) membership is verified.

-/

import Mathlib
import SKEFTHawking.FKLW.GenericSUdGeneratingSet
import SKEFTHawking.FKLW.TrappedIonSU4Substrate

set_option autoImplicit false

namespace SKEFTHawking.FKLW.TrappedIonSU4

open Matrix

attribute [local instance] Matrix.linftyOpNormedAddCommGroup
  Matrix.linftyOpNormedRing
  Matrix.linftyOpNormedAlgebra

/-! ## 1. The 4-generator word type and representation

We use `FreeGroup (Fin 4)` as the word type, with each of the 4
free generators mapped to one of `{H_SU_on_ion1_SU4, T_SU_on_ion1_SU4,
H_SU_on_ion2_SU4, T_SU_on_ion2_SU4}`. -/

/-- The 4-element generator-token map: tokens 0,1,2,3 ↦ packaged SU(4)
gates `{H_1, T_1, H_2, T_2}`. -/
noncomputable def trappedIonGenMap_1Q :
    Fin 4 → ↥(Matrix.specialUnitaryGroup (Fin 4) ℂ)
  | ⟨0, _⟩ => H_SU_on_ion1_SU4
  | ⟨1, _⟩ => T_SU_on_ion1_SU4
  | ⟨2, _⟩ => H_SU_on_ion2_SU4
  | ⟨3, _⟩ => T_SU_on_ion2_SU4

/-- The trapped-ion 1Q-only representation: `FreeGroup (Fin 4) →* ↥(SU(4))`
lifted from `trappedIonGenMap_1Q`. -/
noncomputable def trappedIonRho_1Q :
    FreeGroup (Fin 4) →* ↥(Matrix.specialUnitaryGroup (Fin 4) ℂ) :=
  FreeGroup.lift trappedIonGenMap_1Q

/-! ## 2. The finite generator Finset

`gens := {FreeGroup.of 0, FreeGroup.of 1, FreeGroup.of 2, FreeGroup.of 3}`
— the 4 free generators of `FreeGroup (Fin 4)` as a Finset. -/

/-- The 4 free-group generators as a Finset. -/
noncomputable def trappedIonGens_1Q : Finset (FreeGroup (Fin 4)) :=
  (Finset.univ : Finset (Fin 4)).image FreeGroup.of

theorem trappedIonGens_1Q_nonempty : trappedIonGens_1Q.Nonempty := by
  unfold trappedIonGens_1Q
  refine ⟨FreeGroup.of ⟨0, by decide⟩, ?_⟩
  rw [Finset.mem_image]
  exact ⟨⟨0, by decide⟩, Finset.mem_univ _, rfl⟩

theorem trappedIonGens_1Q_generate :
    Subgroup.closure (trappedIonGens_1Q : Set (FreeGroup (Fin 4))) =
      (⊤ : Subgroup (FreeGroup (Fin 4))) := by
  -- FreeGroup is generated by FreeGroup.of, and trappedIonGens_1Q is the image of
  -- the universal set under FreeGroup.of.
  unfold trappedIonGens_1Q
  -- trappedIonGens_1Q as Set = Set.range FreeGroup.of
  have h_eq : (((Finset.univ : Finset (Fin 4)).image FreeGroup.of :
                Finset (FreeGroup (Fin 4))) : Set (FreeGroup (Fin 4))) =
              Set.range (FreeGroup.of : Fin 4 → FreeGroup (Fin 4)) := by
    ext x
    simp only [Finset.coe_image, Finset.coe_univ, Set.image_univ]
  rw [h_eq]
  exact FreeGroup.closure_range_of _

/-! ## 3. The 1Q-only trapped-ion GeneratingSet 4 instance -/

/-- **Trapped-ion 1Q-only `GeneratingSet 4` instance** (substantive
intermediate ship toward T-A1′.1 proper).

Alphabet = {H_SU on ion 1, T_SU on ion 1, H_SU on ion 2, T_SU on ion 2}.
4 packaged SU(4) generators via Phase 6y T-A1′.1-substrate's
`kronSU4_mem_specialUnitaryGroup`. Word type `FreeGroup (Fin 4)`. -/
noncomputable def trappedIonGeneratingSetSU4_1Q :
    SKEFTHawking.FKLW.GenericSUd.GeneratingSet 4 where
  W := FreeGroup (Fin 4)
  Wgroup := inferInstance
  ρ_hom := trappedIonRho_1Q
  gens := trappedIonGens_1Q
  gens_nonempty := trappedIonGens_1Q_nonempty
  gens_generate := trappedIonGens_1Q_generate

end SKEFTHawking.FKLW.TrappedIonSU4
