import SKEFTHawking.BlochBundle

/-!
# Honeycomb tight-binding and the Dirac points (Phase 6ED, Wave 1)

The repo formalizes graphene as a *Dirac fluid* (Phase 5w: analog metric, Hawking spectrum, noise
PSD) and formalizes *abstract* two-band Chern machinery (Phase 6CA: `blochPauli` d·σ models, FHS
lattice Chern number). What both sides implicitly cite — and neither builds — is graphene's actual
electronic structure. This wave supplies it: the nearest-neighbour honeycomb Bloch Hamiltonian as
a `blochPauli` instance, its band energies, and the **exact** zero set of the structure factor,
which is the pair of inequivalent Dirac points.

## Coordinates: Bloch phases, and *which* chart they may come from

The structure factor is written as a function of the two **Bloch phases**
`θ = (θ₁, θ₂)`:

    f(θ) = 1 + exp(i·θ₁) + exp(i·θ₂)

rather than of a momentum `k` against a fixed pair of lattice vectors. Every theorem below is
therefore literally a statement about `θ ∈ ℝ²`; the honeycomb enters only where a consumer
declares `θᵢ = ⟨k, aᵢ⟩`, in the same two-layer style `BlochBundle` uses for `d(k)`.

**That declaration is not free, and this file does not pretend otherwise.** `f` above is the
honeycomb structure factor precisely for the primitive pair `(a₁, a₂) = (δ₁ − δ₃, δ₂ − δ₃)` built
from the three nearest-neighbour vectors — equal length, **60° apart** — and for the six
relabelings of it generated by `θ ↦ (θ₂, θ₁)` and `θ ↦ (−θ₁, θ₂ − θ₁)`
(`structureFactor_norm_swap`, `structureFactor_norm_rotate`). It is emphatically **not**
`GL₂(ℤ)`-invariant: `structureFactor_zero_set_not_shear_invariant` exhibits a genuine Dirac point
at which the *equally primitive* sheared pair `(a₁, a₁ + a₂)` gives `f ≠ 0`, so under that chart
`structureFactor_eq_zero_iff` would misidentify the Dirac set outright.

The admissible chart is therefore shipped as a nameable hypothesis, `IsHoneycombChart`, rather than
as prose; `isHoneycombChart_of_neighbours` proves the honeycomb's own 120° neighbour geometry
*forces* it, and `norm_neighbourSum_eq` is the bridge identifying `‖f‖` with the physical
three-neighbour hopping sum `Σⱼ exp(i⟨k, δⱼ⟩)`.

## The zero set, and why it is stated without `mod 2π`

The roadmap's AC asked for `f k = 0 ↔ (k ≡ K ∨ k ≡ K')` modulo the reciprocal lattice. What ships
is the equivalent **quotient-free** characterization

    f(θ) = 0  ↔  cos θ₁ = −1/2  ∧  cos θ₂ = −1/2  ∧  sin θ₁ + sin θ₂ = 0

(`structureFactor_eq_zero_iff`). It is *exactly* the same set — periodicity is automatic in `cos`
and `sin`, so no `mod` bookkeeping is needed and none is smuggled — and it is strictly easier for a
consumer to discharge, since it is three real equations rather than a statement about a quotient by
the reciprocal lattice. The `K`/`K'` reading is recovered by
`structureFactor_eq_zero_iff_dirac_branch`: the two solutions of the phase constraints are exactly
`sin θ₁ = +√3/2` (the `K` branch) and `sin θ₁ = −√3/2` (the `K'` branch).

## Layout

* **Definitions** — `structureFactor`, `honeycombD` (the `blochPauli` d-vector), `diracK`/`diracK'`,
  and the high-symmetry points `gammaPoint`/`mPoint`.
* **The phase chart** — `planeDot`, `IsHoneycombChart`, `IsHoneycombNeighbours`,
  `isHoneycombChart_of_neighbours`, the neighbour-sum bridge, the admissible relabelings, and the
  shear refutation.
* **Real/imaginary parts** — `structureFactor_re`/`_im`, the computational core everything else
  reduces to.
* **Band structure** — `dNormSq_honeycombD` (`‖d‖² = |f|²`), `honeycomb_energy_eq` (half-gap
  `‖d‖ = |f|`) and `honeycomb_band_secular` (the *eigenvalues* are `±|f|`, via
  `blochPauli_band_secular`), all routed through `BlochBundle`'s spectral core rather than
  re-deriving 2×2 algebra.
* **The Dirac points** — the quotient-free zero-set characterization, its two-branch form, the
  `mod 2πℤ²` orbit form, gaplessness at `K`/`K'`, the `K`/`K'` inequivalence, and
  `honeycomb_gapped_away_of_phase` off the zero set (via `blochPauli_gap_pos`).
* **Hopping scale** — `structureFactorT`/`honeycombDT`, the `t`-parametrized family, so statements
  "in units of the hopping `t`" have a `t` to refer to.
* **Witnesses** — evaluations at Γ (`|f| = 3`) and M (`|f| = 1`).

**⚠ Guardrail (inherited).** Every statement is about the *stated* nearest-neighbour honeycomb
tight-binding model. Identifying its parameters with a physical sample (hopping energies, measured
`v_F`, gap sizes) is consumer-side. No claim about devices, transport, or fabrication.

**Publication target:** bundle **D11** — *Kernel-Verified Topological Band Theory & Metamaterial
Substrate* (this phase's thread; its `6E*` siblings route to D12).
-/

namespace SKEFTHawking.GrapheneBand

open Complex Real SKEFTHawking.Topological

/-! ## Definitions -/

/-- **The nearest-neighbour honeycomb structure factor**, in Bloch-phase coordinates:

    f(θ) = 1 + exp(i·θ₁) + exp(i·θ₂).

The three terms are the three nearest-neighbour hoppings from an A site to its B neighbours, with
the common phase `exp(i⟨k, δ₃⟩)` factored out (`neighbourSum_eq_structureFactor`). Writing it in
the phases rather than in `k` keeps every theorem a statement about `θ ∈ ℝ²`; the honeycomb reading
requires `θᵢ = ⟨k, aᵢ⟩` for an **`IsHoneycombChart`** pair — equal length, 60° apart — and is
*false* for a general primitive pair (`structureFactor_zero_set_not_shear_invariant`). The hopping
amplitude is normalized to `t = 1` here; `structureFactorT` carries a general `t`. -/
noncomputable def structureFactor (θ : ℝ × ℝ) : ℂ :=
  1 + Complex.exp (θ.1 * Complex.I) + Complex.exp (θ.2 * Complex.I)

/-- **The honeycomb `d`-vector**, `d(θ) = (Re f, −Im f, 0)`.

The third component vanishes: nearest-neighbour honeycomb hopping is **sublattice-off-diagonal**,
which is exactly the chiral symmetry that pins the bands symmetrically at `±|f|` and permits the
gapless Dirac points. A nonzero `d₃` is the *mass* term, which Wave 2 adds. -/
noncomputable def honeycombD (θ : ℝ × ℝ) : Fin 3 → ℝ :=
  ![(structureFactor θ).re, -(structureFactor θ).im, 0]

/-- The honeycomb Bloch Hamiltonian as a `blochPauli` instance — so the whole 2×2 spectral core
(`blochPauli_sq`, `blochPauli_secular_det`, `blochPauli_gap_pos`) applies without re-derivation. -/
noncomputable def honeycombBloch (θ : ℝ × ℝ) : Matrix (Fin 2) (Fin 2) ℂ :=
  blochPauli (honeycombD θ)

/-- The `K` Dirac point in phase coordinates: `θ = (2π/3, 4π/3)`. -/
noncomputable def diracK : ℝ × ℝ := (2 * π / 3, 4 * π / 3)

/-- The inequivalent `K'` Dirac point: the coordinate swap of `K`. -/
noncomputable def diracK' : ℝ × ℝ := (4 * π / 3, 2 * π / 3)

/-- The Brillouin-zone centre Γ, `θ = (0, 0)`. -/
def gammaPoint : ℝ × ℝ := (0, 0)

/-- An `M` point (edge midpoint), `θ = (π, 0)`. -/
noncomputable def mPoint : ℝ × ℝ := (π, 0)

/-! ## The phase chart — which primitive pair `θ` may come from

`structureFactor` is a function of `θ ∈ ℝ²`. This section supplies the consumer-side hypothesis
that turns it into *the honeycomb's* structure factor, as a named `Prop` rather than prose, and
refutes the over-claim that any primitive-vector pair would serve. -/

/-- The Euclidean inner product on the plane, written concretely — no `InnerProductSpace` instance
is needed for the two-line bilinearity this section uses. -/
def planeDot (u v : ℝ × ℝ) : ℝ := u.1 * v.1 + u.2 * v.2

lemma planeDot_comm (u v : ℝ × ℝ) : planeDot u v = planeDot v u := by unfold planeDot; ring

lemma planeDot_sub_right (u v w : ℝ × ℝ) :
    planeDot u (v - w) = planeDot u v - planeDot u w := by
  unfold planeDot; simp only [Prod.fst_sub, Prod.snd_sub]; ring

lemma planeDot_self_eq_zero_iff {u : ℝ × ℝ} : planeDot u u = 0 ↔ u = 0 := by
  unfold planeDot
  constructor
  · intro h
    have h1 : u.1 = 0 := by nlinarith [sq_nonneg u.1, sq_nonneg u.2]
    have h2 : u.2 = 0 := by nlinarith [sq_nonneg u.1, sq_nonneg u.2]
    exact Prod.ext h1 h2
  · intro h; rw [h]; simp

lemma planeDot_self_nonneg (u : ℝ × ℝ) : 0 ≤ planeDot u u := by
  unfold planeDot; nlinarith [mul_self_nonneg u.1, mul_self_nonneg u.2]

lemma planeDot_self_pos {u : ℝ × ℝ} (h : u ≠ 0) : 0 < planeDot u u := by
  rcases lt_or_eq_of_le (planeDot_self_nonneg u) with hlt | heq
  · exact hlt
  · exact absurd (planeDot_self_eq_zero_iff.mp heq.symm) h

/-- **The admissible phase chart.** `f(⟨k, a₁⟩, ⟨k, a₂⟩)` is the honeycomb structure factor (up to
the unimodular prefactor of `neighbourSum_eq_structureFactor`) exactly when `(a₁, a₂)` is the
primitive pair the honeycomb's nearest-neighbour differences produce: **equal length, 60° apart**.
The two conditions below are `‖a₂‖ = ‖a₁‖` and `⟨a₁, a₂⟩ = ‖a₁‖‖a₂‖ · cos 60°`, written without
square roots.

This is the hypothesis a consumer must *declare*; it is not automatic for a primitive pair, and
`structureFactor_zero_set_not_shear_invariant` shows what breaks when it fails. -/
structure IsHoneycombChart (a₁ a₂ : ℝ × ℝ) : Prop where
  /-- The chart is nondegenerate. -/
  ne_zero : a₁ ≠ 0
  /-- The two primitive vectors have equal length. -/
  len_eq : planeDot a₂ a₂ = planeDot a₁ a₁
  /-- They subtend 60°: `2⟨a₁, a₂⟩ = ‖a₁‖²`. -/
  angle_sixty : 2 * planeDot a₁ a₂ = planeDot a₁ a₁

/-- **The honeycomb's nearest-neighbour geometry**: three vectors of equal length pairwise 120°
apart (`2⟨δᵢ, δⱼ⟩ = −‖δ‖²` is `cos 120° = −1/2`). This is the *physical* input; the chart is
derived from it. -/
structure IsHoneycombNeighbours (δ : Fin 3 → ℝ × ℝ) : Prop where
  /-- Nondegenerate: the bond length is nonzero. -/
  ne_zero : δ 0 ≠ 0
  /-- All three bonds have the same length. -/
  len_one : planeDot (δ 1) (δ 1) = planeDot (δ 0) (δ 0)
  /-- All three bonds have the same length. -/
  len_two : planeDot (δ 2) (δ 2) = planeDot (δ 0) (δ 0)
  /-- `δ₀` and `δ₁` subtend 120°. -/
  angle_01 : 2 * planeDot (δ 0) (δ 1) = -planeDot (δ 0) (δ 0)
  /-- `δ₀` and `δ₂` subtend 120°. -/
  angle_02 : 2 * planeDot (δ 0) (δ 2) = -planeDot (δ 0) (δ 0)
  /-- `δ₁` and `δ₂` subtend 120°. -/
  angle_12 : 2 * planeDot (δ 1) (δ 2) = -planeDot (δ 0) (δ 0)

/-- **The honeycomb forces the 60° chart.** Given the three 120°-separated nearest-neighbour
vectors, the primitive pair `(δ₀ − δ₂, δ₁ − δ₂)` — the pair `structureFactor` is written against —
is an `IsHoneycombChart`, with `‖a₁‖² = 3‖δ‖²` (so `‖a₁‖ = √3 · a_CC`: the lattice constant is
`√3` times the nearest-neighbour distance, the conversion `dispersion_slope_of_chart` needs).

This is the theorem that makes the chart hypothesis *derived physics* rather than a stipulation. -/
theorem isHoneycombChart_of_neighbours {δ : Fin 3 → ℝ × ℝ} (h : IsHoneycombNeighbours δ) :
    IsHoneycombChart (δ 0 - δ 2) (δ 1 - δ 2) := by
  obtain ⟨hne, h1, h2, h01, h02, h12⟩ := h
  have hL : 0 < planeDot (δ 0) (δ 0) := planeDot_self_pos hne
  have hlen : planeDot (δ 0 - δ 2) (δ 0 - δ 2) = 3 * planeDot (δ 0) (δ 0) := by
    simp only [planeDot, Prod.fst_sub, Prod.snd_sub] at h2 h02 ⊢; nlinarith [h2, h02]
  refine ⟨?_, ?_, ?_⟩
  · intro hz
    have hzero : planeDot (δ 0 - δ 2) (δ 0 - δ 2) = 0 := by rw [hz]; simp [planeDot]
    rw [hlen] at hzero
    linarith
  · simp only [planeDot, Prod.fst_sub, Prod.snd_sub] at h1 h2 h02 h12 ⊢; nlinarith [h1, h2, h02, h12]
  · simp only [planeDot, Prod.fst_sub, Prod.snd_sub] at h2 h01 h02 h12 ⊢
    nlinarith [h2, h01, h02, h12]

/-- **`‖a₁‖² = 3‖δ‖²`** — the `√3` between the nearest-neighbour distance `a_CC` and the lattice
constant, stated as its own fact because downstream prose repeatedly conflates the two. -/
theorem chart_len_sq_of_neighbours {δ : Fin 3 → ℝ × ℝ} (h : IsHoneycombNeighbours δ) :
    planeDot (δ 0 - δ 2) (δ 0 - δ 2) = 3 * planeDot (δ 0) (δ 0) := by
  obtain ⟨_, _, h2, _, h02, _⟩ := h
  simp only [planeDot, Prod.fst_sub, Prod.snd_sub] at h2 h02 ⊢
  nlinarith [h2, h02]

/-- **The canonical graphene bond geometry** — three unit vectors at 120°, the standard
`δ₁ = (1,0)`, `δ₂ = (−1/2, √3/2)`, `δ₃ = (−1/2, −√3/2)` (bond length `a_CC = 1`). Non-vacuity of
`IsHoneycombNeighbours`, so `isHoneycombChart_of_neighbours` is not an empty implication. -/
theorem isHoneycombNeighbours_canonical :
    IsHoneycombNeighbours
      ![((1 : ℝ), (0 : ℝ)), ((-1/2 : ℝ), Real.sqrt 3 / 2), ((-1/2 : ℝ), -(Real.sqrt 3 / 2))] := by
  have hs3 : Real.sqrt 3 ^ 2 = 3 := Real.sq_sqrt (by norm_num)
  refine ⟨by simp, ?_, ?_, ?_, ?_, ?_⟩ <;>
    simp only [planeDot, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.head_cons,
      Matrix.cons_val_two, Matrix.tail_cons] <;>
    nlinarith [hs3]

/-- The chart derived from the canonical bond geometry has `‖a₁‖² = 3` — i.e. `‖a₁‖ = √3 · a_CC`,
the lattice constant. A worked instance of `chart_len_sq_of_neighbours`. -/
theorem chart_len_sq_canonical :
    planeDot
        (![((1 : ℝ), (0 : ℝ)), ((-1/2 : ℝ), Real.sqrt 3 / 2), ((-1/2 : ℝ), -(Real.sqrt 3 / 2))] 0 -
          ![((1 : ℝ), (0 : ℝ)), ((-1/2 : ℝ), Real.sqrt 3 / 2), ((-1/2 : ℝ), -(Real.sqrt 3 / 2))] 2)
        (![((1 : ℝ), (0 : ℝ)), ((-1/2 : ℝ), Real.sqrt 3 / 2), ((-1/2 : ℝ), -(Real.sqrt 3 / 2))] 0 -
          ![((1 : ℝ), (0 : ℝ)), ((-1/2 : ℝ), Real.sqrt 3 / 2), ((-1/2 : ℝ), -(Real.sqrt 3 / 2))] 2)
      = 3 := by
  have hs3 : Real.sqrt 3 ^ 2 = 3 := Real.sq_sqrt (by norm_num)
  simp only [planeDot, Matrix.cons_val_zero, Matrix.cons_val_two, Matrix.tail_cons,
    Matrix.head_cons, Prod.fst_sub, Prod.snd_sub]
  nlinarith [hs3]

/-- Non-vacuity of `IsHoneycombChart`: the canonical unit pair at 60°. -/
theorem isHoneycombChart_canonical :
    IsHoneycombChart ((1 : ℝ), (0 : ℝ)) ((1/2 : ℝ), Real.sqrt 3 / 2) := by
  have hs3 : Real.sqrt 3 ^ 2 = 3 := Real.sq_sqrt (by norm_num)
  refine ⟨by simp, ?_, ?_⟩ <;> simp only [planeDot] <;> nlinarith [hs3]

/-- **A primitive pair is not automatically a chart.** `(a₁, a₁ + a₂)` is `GL₂(ℤ)`-equivalent to
`(a₁, a₂)` — equally a basis of the same lattice — yet fails `IsHoneycombChart`: the two vectors
have different lengths (`3‖a₁‖²` vs `‖a₁‖²`). -/
theorem not_isHoneycombChart_shear :
    ¬ IsHoneycombChart ((1 : ℝ), (0 : ℝ))
        (((1 : ℝ), (0 : ℝ)) + ((1/2 : ℝ), Real.sqrt 3 / 2)) := by
  have hs3 : Real.sqrt 3 ^ 2 = 3 := Real.sq_sqrt (by norm_num)
  intro h
  have := h.len_eq
  simp only [planeDot, Prod.fst_add, Prod.snd_add] at this
  nlinarith [hs3]

/-- **The physical hopping sum**: `Σⱼ exp(i⟨k, δⱼ⟩)` over the three nearest-neighbour vectors. This
is the object the tight-binding Hamiltonian's off-diagonal entry actually is; `structureFactor` is
its phase-coordinate form. -/
noncomputable def neighbourSum (δ : Fin 3 → ℝ × ℝ) (k : ℝ × ℝ) : ℂ :=
  ∑ j : Fin 3, Complex.exp ((planeDot k (δ j) : ℝ) * Complex.I)

/-- **The bridge.** The three-neighbour hopping sum equals `structureFactor` at the phases of the
derived chart, times the unimodular prefactor `exp(i⟨k, δ₃⟩)`. This is where `structureFactor`'s
specific `1 + e^{iθ₁} + e^{iθ₂}` shape comes from, and it holds for the pair
`(δ₀ − δ₂, δ₁ − δ₂)` — *not* for an arbitrary primitive pair. -/
theorem neighbourSum_eq_structureFactor (δ : Fin 3 → ℝ × ℝ) (k : ℝ × ℝ) :
    neighbourSum δ k
      = Complex.exp ((planeDot k (δ 2) : ℝ) * Complex.I)
        * structureFactor (planeDot k (δ 0 - δ 2), planeDot k (δ 1 - δ 2)) := by
  have key : ∀ a c : ℝ, Complex.exp ((c : ℝ) * Complex.I) * Complex.exp (((a - c : ℝ)) * Complex.I)
      = Complex.exp ((a : ℝ) * Complex.I) := by
    intro a c
    rw [← Complex.exp_add]
    congr 1
    push_cast
    ring
  simp only [neighbourSum, Fin.sum_univ_three, structureFactor, planeDot_sub_right, mul_add,
    mul_one, key]
  ring

/-- `‖Σⱼ exp(i⟨k, δⱼ⟩)‖ = ‖f‖` — the prefactor is unimodular, so every `‖f‖` statement in this file
is a statement about the physical hopping sum, provided the chart is the derived one. -/
theorem norm_neighbourSum_eq (δ : Fin 3 → ℝ × ℝ) (k : ℝ × ℝ) :
    ‖neighbourSum δ k‖
      = ‖structureFactor (planeDot k (δ 0 - δ 2), planeDot k (δ 1 - δ 2))‖ := by
  rw [neighbourSum_eq_structureFactor, norm_mul, Complex.norm_exp_ofReal_mul_I, one_mul]

/-! ### The admissible relabelings

`‖f‖` *is* invariant under a six-element group — the relabelings of the three neighbour vectors,
generated by the coordinate swap and by re-factoring a different `δ` out of the sum. These are the
only chart changes the file's theorems survive. -/

/-- Swapping the two phases (relabelling `δ₀ ↔ δ₁`) preserves `‖f‖`. -/
theorem structureFactor_norm_swap (θ : ℝ × ℝ) :
    ‖structureFactor (θ.2, θ.1)‖ = ‖structureFactor θ‖ := by
  unfold structureFactor
  simp only []
  ring_nf

/-- Re-factoring `δ₀` out of the hopping sum instead of `δ₂` sends `θ ↦ (−θ₁, θ₂ − θ₁)` and
preserves `‖f‖`, because `f(−θ₁, θ₂ − θ₁) = exp(−iθ₁) · f(θ)`. Together with
`structureFactor_norm_swap` this generates all six admissible relabelings. -/
theorem structureFactor_norm_rotate (θ : ℝ × ℝ) :
    ‖structureFactor (-θ.1, θ.2 - θ.1)‖ = ‖structureFactor θ‖ := by
  have e1 : Complex.exp ((-θ.1 : ℝ) * Complex.I) * Complex.exp ((θ.1 : ℝ) * Complex.I) = 1 := by
    rw [← Complex.exp_add,
      show ((-θ.1 : ℝ) : ℂ) * Complex.I + ((θ.1 : ℝ) : ℂ) * Complex.I = 0 by push_cast; ring,
      Complex.exp_zero]
  have e2 : Complex.exp ((-θ.1 : ℝ) * Complex.I) * Complex.exp ((θ.2 : ℝ) * Complex.I)
      = Complex.exp ((θ.2 - θ.1 : ℝ) * Complex.I) := by
    rw [← Complex.exp_add]; congr 1; push_cast; ring
  have hfac : structureFactor (-θ.1, θ.2 - θ.1)
      = Complex.exp ((-θ.1 : ℝ) * Complex.I) * structureFactor θ := by
    unfold structureFactor
    simp only []
    rw [mul_add, mul_add, mul_one, e1, e2]
    ring
  rw [hfac, norm_mul, Complex.norm_exp_ofReal_mul_I, one_mul]

/-! ## Real and imaginary parts — the computational core -/

/-- `Re f(θ) = 1 + cos θ₁ + cos θ₂`. -/
theorem structureFactor_re (θ : ℝ × ℝ) :
    (structureFactor θ).re = 1 + Real.cos θ.1 + Real.cos θ.2 := by
  unfold structureFactor
  simp [Complex.exp_mul_I, Complex.add_re, Complex.cos_ofReal_re, Complex.sin_ofReal_re]

/-- `Im f(θ) = sin θ₁ + sin θ₂`. -/
theorem structureFactor_im (θ : ℝ × ℝ) :
    (structureFactor θ).im = Real.sin θ.1 + Real.sin θ.2 := by
  unfold structureFactor
  simp [Complex.exp_mul_I, Complex.add_im, Complex.sin_ofReal_re]

/-! ## Band structure — routed through `BlochBundle` -/

/-- **`‖d‖² = |f|²`.** The honeycomb `d`-vector's squared norm is exactly the squared modulus of
the structure factor — the identity that turns `BlochBundle`'s abstract `±‖d‖` bands into the
honeycomb bands `±|f|`. -/
theorem dNormSq_honeycombD (θ : ℝ × ℝ) :
    dNormSq (honeycombD θ) = Complex.normSq (structureFactor θ) := by
  unfold dNormSq honeycombD Complex.normSq
  simp only [Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.head_cons, Matrix.cons_val_two,
    Matrix.tail_cons, MonoidWithZeroHom.coe_mk, ZeroHom.coe_mk]
  ring

/-- **The half-gap is `|f(θ)|`.** The abstract two-band model's `‖d‖` evaluates to the modulus of
the structure factor. This is the *norm* identity; the statement that `±|f|` are the actual
**eigenvalues** of the Hamiltonian is `honeycomb_band_secular`, which consumes this one. -/
theorem honeycomb_energy_eq (θ : ℝ × ℝ) :
    Real.sqrt (dNormSq (honeycombD θ)) = ‖structureFactor θ‖ := by
  rw [Complex.norm_def, dNormSq_honeycombD]

/-- **The honeycomb bands are `±|f(θ)|`** — as eigenvalues, not merely as a norm.

Both `+‖f θ‖` and `−‖f θ‖` annihilate the secular determinant `det(H(θ) − λ·I)` of the honeycomb
Bloch Hamiltonian. This is the wave's headline spectral statement, and it is obtained by *citing*
`BlochBundle`'s `blochPauli_band_secular` (itself routed through `blochPauli_secular_det`) at the
honeycomb `d`-vector and rewriting `‖d‖` to `|f|` — no 2×2 algebra is re-derived here. It is also
what makes the `honeycombBloch` instantiation load-bearing. -/
theorem honeycomb_band_secular (θ : ℝ × ℝ) :
    (honeycombBloch θ - ((‖structureFactor θ‖ : ℝ) : ℂ) • 1).det = 0 ∧
      (honeycombBloch θ - ((-‖structureFactor θ‖ : ℝ) : ℂ) • 1).det = 0 := by
  have h := blochPauli_band_secular (honeycombD θ)
  rw [honeycomb_energy_eq] at h
  exact h

/-- **The honeycomb Pauli identity** `H(θ)² = |f(θ)|²·I` — `blochPauli_sq` with the honeycomb
`‖d‖²` evaluated. This is the algebraic fact underlying `honeycomb_band_secular`: `H² = |f|²·I`
leaves `±|f|` as the only possible eigenvalues. -/
theorem honeycombBloch_sq (θ : ℝ × ℝ) :
    honeycombBloch θ * honeycombBloch θ
      = (Complex.normSq (structureFactor θ) : ℂ) • (1 : Matrix (Fin 2) (Fin 2) ℂ) := by
  unfold honeycombBloch
  rw [blochPauli_sq, dNormSq_honeycombD]

/-! ## The Dirac points -/

/-- **The exact zero set of the structure factor**, quotient-free.

    f(θ) = 0  ↔  cos θ₁ = −1/2  ∧  cos θ₂ = −1/2  ∧  sin θ₁ + sin θ₂ = 0

The forward direction is the delicate step: vanishing of `Re f` and `Im f` gives
`1 + cos θ₁ + cos θ₂ = 0` and `sin θ₂ = −sin θ₁`, and squaring the latter with
`sin² + cos² = 1` forces `cos²θ₂ = cos²θ₁`. The branch `cos θ₂ = −cos θ₁` contradicts the first
equation (it would need `1 = 0`), so `cos θ₂ = cos θ₁` and both equal `−1/2`.

No `mod 2π` bookkeeping appears because none is needed — `cos` and `sin` are already periodic, so
this characterizes the full reciprocal-lattice orbit of `K` and `K'` at once. -/
theorem structureFactor_eq_zero_iff (θ : ℝ × ℝ) :
    structureFactor θ = 0 ↔
      Real.cos θ.1 = -(1/2) ∧ Real.cos θ.2 = -(1/2) ∧ Real.sin θ.1 + Real.sin θ.2 = 0 := by
  rw [Complex.ext_iff, Complex.zero_re, Complex.zero_im, structureFactor_re, structureFactor_im]
  constructor
  · rintro ⟨hre, him⟩
    have hp1 := Real.sin_sq_add_cos_sq θ.1
    have hp2 := Real.sin_sq_add_cos_sq θ.2
    -- `sin θ₂ = −sin θ₁`, so the two `sin²` agree, hence so do the two `cos²`.
    have hsneg : Real.sin θ.2 = -Real.sin θ.1 := by linarith
    have hs2 : Real.sin θ.2 ^ 2 = Real.sin θ.1 ^ 2 := by rw [hsneg]; ring
    have hfac : (Real.cos θ.1 - Real.cos θ.2) * (Real.cos θ.1 + Real.cos θ.2) = 0 := by
      nlinarith [hp1, hp2, hs2]
    -- the `cos θ₁ = −cos θ₂` branch would force `1 = 0` in `hre`, so the sum branch is dead
    have hcos : Real.cos θ.1 = Real.cos θ.2 := by
      rcases mul_eq_zero.mp hfac with h | h
      · linarith
      · linarith
    refine ⟨by linarith, by linarith, him⟩
  · rintro ⟨h1, h2, h3⟩
    exact ⟨by rw [h1, h2]; ring, h3⟩

/-- **The two Dirac branches.** The phase constraints of `structureFactor_eq_zero_iff` have exactly
two solution branches, distinguished by the sign of `sin θ₁`: the `K` branch
(`sin θ₁ = +√3/2`, `sin θ₂ = −√3/2`) and the `K'` branch (the reverse). This is the `K`/`K'`
reading the AC's `mod`-quotient phrasing was after, recovered without the quotient. -/
theorem structureFactor_eq_zero_iff_dirac_branch (θ : ℝ × ℝ) :
    structureFactor θ = 0 ↔
      Real.cos θ.1 = -(1/2) ∧ Real.cos θ.2 = -(1/2) ∧
        ((Real.sin θ.1 = Real.sqrt 3 / 2 ∧ Real.sin θ.2 = -(Real.sqrt 3 / 2)) ∨
         (Real.sin θ.1 = -(Real.sqrt 3 / 2) ∧ Real.sin θ.2 = Real.sqrt 3 / 2)) := by
  rw [structureFactor_eq_zero_iff]
  constructor
  · rintro ⟨h1, h2, h3⟩
    have hs3 : Real.sqrt 3 ^ 2 = 3 := Real.sq_sqrt (by norm_num)
    have hp1 := Real.sin_sq_add_cos_sq θ.1
    have hsq : Real.sin θ.1 ^ 2 = (Real.sqrt 3 / 2) ^ 2 := by
      rw [div_pow, hs3]; nlinarith [hp1, h1]
    refine ⟨h1, h2, ?_⟩
    rcases sq_eq_sq_iff_eq_or_eq_neg.mp hsq with h | h
    · exact Or.inl ⟨h, by linarith⟩
    · exact Or.inr ⟨h, by linarith⟩
  · rintro ⟨h1, h2, h | h⟩
    · exact ⟨h1, h2, by rw [h.1, h.2]; ring⟩
    · exact ⟨h1, h2, by rw [h.1, h.2]; ring⟩

/-- **The model is gapless exactly on the Dirac set.** At `K` the structure factor vanishes, so the
two bands touch at zero energy. -/
theorem honeycomb_gapless_at_diracK : structureFactor diracK = 0 := by
  rw [structureFactor_eq_zero_iff]
  refine ⟨?_, ?_, ?_⟩
  · show Real.cos (2 * π / 3) = -(1/2)
    rw [show (2 * π / 3 : ℝ) = π - π / 3 by ring, Real.cos_pi_sub, Real.cos_pi_div_three]
  · show Real.cos (4 * π / 3) = -(1/2)
    rw [show (4 * π / 3 : ℝ) = π / 3 + π by ring, Real.cos_add_pi, Real.cos_pi_div_three]
  · show Real.sin (2 * π / 3) + Real.sin (4 * π / 3) = 0
    rw [show (2 * π / 3 : ℝ) = π - π / 3 by ring, show (4 * π / 3 : ℝ) = π / 3 + π by ring,
      Real.sin_pi_sub, Real.sin_add_pi]
    ring

/-- `K'` is likewise a Dirac point. That the two are genuinely *inequivalent* — not the same point
modulo the reciprocal lattice, which is why graphene has *two* cones — is
`diracK'_ne_recip_translate_diracK`, proved rather than asserted. -/
theorem honeycomb_gapless_at_diracK' : structureFactor diracK' = 0 := by
  rw [structureFactor_eq_zero_iff]
  refine ⟨?_, ?_, ?_⟩
  · show Real.cos (4 * π / 3) = -(1/2)
    rw [show (4 * π / 3 : ℝ) = π / 3 + π by ring, Real.cos_add_pi, Real.cos_pi_div_three]
  · show Real.cos (2 * π / 3) = -(1/2)
    rw [show (2 * π / 3 : ℝ) = π - π / 3 by ring, Real.cos_pi_sub, Real.cos_pi_div_three]
  · show Real.sin (4 * π / 3) + Real.sin (2 * π / 3) = 0
    rw [show (2 * π / 3 : ℝ) = π - π / 3 by ring, show (4 * π / 3 : ℝ) = π / 3 + π by ring,
      Real.sin_pi_sub, Real.sin_add_pi]
    ring

/-! ### The zero set as the reciprocal-lattice orbit of `K` and `K'`

The quotient-free `structureFactor_eq_zero_iff` is the working form, but the AC's original
`mod`-reciprocal-lattice phrasing is also *provable* rather than merely equivalent-in-spirit, and
is what a reader expects to see. In phase coordinates the reciprocal lattice is exactly `2πℤ²`. -/

/-- Two real phases agree in `(cos, sin)` iff they differ by an integer multiple of `2π` — the
one-variable content of "modulo the reciprocal lattice". -/
theorem cos_sin_eq_iff_add_int_mul_two_pi (c t : ℝ) :
    (Real.cos t = Real.cos c ∧ Real.sin t = Real.sin c) ↔ ∃ n : ℤ, t = c + 2 * π * n := by
  constructor
  · rintro ⟨hc, hs⟩
    have hexp : Complex.exp ((t : ℝ) * Complex.I) = Complex.exp ((c : ℝ) * Complex.I) := by
      rw [Complex.exp_mul_I, Complex.exp_mul_I,
        show (Complex.cos (t : ℂ)) = ((Real.cos t : ℝ) : ℂ) from (Complex.ofReal_cos t).symm,
        show (Complex.sin (t : ℂ)) = ((Real.sin t : ℝ) : ℂ) from (Complex.ofReal_sin t).symm,
        show (Complex.cos (c : ℂ)) = ((Real.cos c : ℝ) : ℂ) from (Complex.ofReal_cos c).symm,
        show (Complex.sin (c : ℂ)) = ((Real.sin c : ℝ) : ℂ) from (Complex.ofReal_sin c).symm,
        hc, hs]
    obtain ⟨n, hn⟩ := Complex.exp_eq_exp_iff_exists_int.mp hexp
    refine ⟨n, ?_⟩
    have hcast : ((t : ℝ) : ℂ) = ((c : ℝ) : ℂ) + (n : ℂ) * (2 * π) := by
      apply mul_right_cancel₀ Complex.I_ne_zero
      field_simp at hn
      rw [hn]; ring
    have hr : t = c + (n : ℝ) * (2 * π) := by exact_mod_cast congrArg Complex.re hcast
    rw [hr]; ring
  · rintro ⟨n, rfl⟩
    refine ⟨?_, ?_⟩
    · rw [show c + 2 * π * (n : ℝ) = c + (n : ℝ) * (2 * π) by ring, Real.cos_add_int_mul_two_pi]
    · rw [show c + 2 * π * (n : ℝ) = c + (n : ℝ) * (2 * π) by ring, Real.sin_add_int_mul_two_pi]

private theorem cos_sin_diracK_fst :
    Real.cos (2 * π / 3) = -(1/2) ∧ Real.sin (2 * π / 3) = Real.sqrt 3 / 2 := by
  constructor
  · rw [show (2 * π / 3 : ℝ) = π - π / 3 by ring, Real.cos_pi_sub, Real.cos_pi_div_three]
  · rw [show (2 * π / 3 : ℝ) = π - π / 3 by ring, Real.sin_pi_sub, Real.sin_pi_div_three]

private theorem cos_sin_diracK_snd :
    Real.cos (4 * π / 3) = -(1/2) ∧ Real.sin (4 * π / 3) = -(Real.sqrt 3 / 2) := by
  constructor
  · rw [show (4 * π / 3 : ℝ) = π / 3 + π by ring, Real.cos_add_pi, Real.cos_pi_div_three]
  · rw [show (4 * π / 3 : ℝ) = π / 3 + π by ring, Real.sin_add_pi, Real.sin_pi_div_three]

/-- **The zero set is exactly the reciprocal-lattice orbit of `K` together with that of `K'`** —
the AC's original `f k = 0 ↔ (k ≡ K ∨ k ≡ K') [mod reciprocal lattice]`, discharged rather than
replaced. In Bloch-phase coordinates the reciprocal lattice is `2πℤ²`, so "≡" is componentwise
`+ 2πℤ`. Proved from the quotient-free characterization plus
`cos_sin_eq_iff_add_int_mul_two_pi`. -/
theorem structureFactor_eq_zero_iff_orbit (θ : ℝ × ℝ) :
    structureFactor θ = 0 ↔
      ((∃ n : ℤ, θ.1 = 2 * π / 3 + 2 * π * n) ∧ (∃ m : ℤ, θ.2 = 4 * π / 3 + 2 * π * m)) ∨
      ((∃ n : ℤ, θ.1 = 4 * π / 3 + 2 * π * n) ∧ (∃ m : ℤ, θ.2 = 2 * π / 3 + 2 * π * m)) := by
  rw [structureFactor_eq_zero_iff_dirac_branch]
  obtain ⟨hc1, hs1⟩ := cos_sin_diracK_fst
  obtain ⟨hc2, hs2⟩ := cos_sin_diracK_snd
  constructor
  · rintro ⟨h1, h2, hbr | hbr⟩
    · exact Or.inl ⟨(cos_sin_eq_iff_add_int_mul_two_pi (2 * π / 3) θ.1).mp
          ⟨by rw [h1, hc1], by rw [hbr.1, hs1]⟩,
        (cos_sin_eq_iff_add_int_mul_two_pi (4 * π / 3) θ.2).mp ⟨by rw [h2, hc2], by rw [hbr.2, hs2]⟩⟩
    · exact Or.inr ⟨(cos_sin_eq_iff_add_int_mul_two_pi (4 * π / 3) θ.1).mp
          ⟨by rw [h1, hc2], by rw [hbr.1, hs2]⟩,
        (cos_sin_eq_iff_add_int_mul_two_pi (2 * π / 3) θ.2).mp ⟨by rw [h2, hc1], by rw [hbr.2, hs1]⟩⟩
  · rintro (⟨ha, hb⟩ | ⟨ha, hb⟩)
    · obtain ⟨p1, q1⟩ := (cos_sin_eq_iff_add_int_mul_two_pi (2 * π / 3) θ.1).mpr ha
      obtain ⟨p2, q2⟩ := (cos_sin_eq_iff_add_int_mul_two_pi (4 * π / 3) θ.2).mpr hb
      exact ⟨by rw [p1, hc1], by rw [p2, hc2], Or.inl ⟨by rw [q1, hs1], by rw [q2, hs2]⟩⟩
    · obtain ⟨p1, q1⟩ := (cos_sin_eq_iff_add_int_mul_two_pi (4 * π / 3) θ.1).mpr ha
      obtain ⟨p2, q2⟩ := (cos_sin_eq_iff_add_int_mul_two_pi (2 * π / 3) θ.2).mpr hb
      exact ⟨by rw [p1, hc2], by rw [p2, hc1], Or.inr ⟨by rw [q1, hs2], by rw [q2, hs1]⟩⟩

/-- **`K` and `K'` are inequivalent — graphene really has two cones.** `K'` is not a
reciprocal-lattice translate of `K`: no `(n, m) ∈ ℤ²` satisfies `K' = K + 2π(n, m)`, because the
first coordinate would need `3n = 1`. Previously asserted in a docstring; now a theorem. -/
theorem diracK'_ne_recip_translate_diracK (n m : ℤ) :
    diracK' ≠ (diracK.1 + 2 * π * n, diracK.2 + 2 * π * m) := by
  unfold diracK diracK'
  simp only [ne_eq, Prod.mk.injEq, not_and]
  intro h _
  have hz : π * (2 - 6 * (n : ℝ)) = 0 := by linarith
  have h3 : (3 : ℝ) * (n : ℝ) = 1 := by
    rcases mul_eq_zero.mp hz with h1 | h1
    · exact absurd h1 Real.pi_ne_zero
    · linarith
  have hi : (3 : ℤ) * n = 1 := by exact_mod_cast h3
  omega

/-- **⛔ The chart hypothesis is load-bearing: `f` is NOT `GL₂(ℤ)`-invariant.**

`(a₁, a₁ + a₂)` is a primitive pair for the *same* lattice — equally legitimate as a
"primitive-vector choice" — and it sends `θ ↦ (θ₁, θ₁ + θ₂)`. At the genuine Dirac point `K` the
honeycomb chart gives `f = 0` while the sheared chart gives `f = 3/2 + i·√3/2 ≠ 0`. So under a
general primitive-vector choice `structureFactor_eq_zero_iff` does not characterize the Dirac set
at all: it misses `K` outright.

This is the kernel-checked refutation of the claim that this file's theorems hold for *any*
primitive-vector choice; only `IsHoneycombChart` pairs and their six relabelings work. -/
theorem structureFactor_zero_set_not_shear_invariant :
    structureFactor diracK = 0 ∧ structureFactor (diracK.1, diracK.1 + diracK.2) ≠ 0 := by
  refine ⟨honeycomb_gapless_at_diracK, ?_⟩
  intro hf
  obtain ⟨-, h2, -⟩ := (structureFactor_eq_zero_iff _).mp hf
  rw [show ((diracK.1, diracK.1 + diracK.2) : ℝ × ℝ).2 = 2 * π by
    unfold diracK; simp only []; ring] at h2
  rw [Real.cos_two_pi] at h2
  norm_num at h2

/-- **The model is gapped away from the Dirac set** — via `BlochBundle`'s `blochPauli_gap_pos`,
not a fresh argument. Off the zero set of `f` the half-gap `‖d‖` is strictly positive.

Note this is the *`f`-shaped* hypothesis; the contentful "`θ` is not a Dirac phase" form the AC
asked for is `honeycomb_gapped_away_of_phase`, which takes the negation of the three phase
equations and is what a consumer holding a concrete `θ` can actually discharge. -/
theorem honeycomb_gapped_away {θ : ℝ × ℝ} (h : structureFactor θ ≠ 0) :
    0 < Real.sqrt (dNormSq (honeycombD θ)) := by
  refine blochPauli_gap_pos _ ?_
  intro hd
  apply h
  have hre : (structureFactor θ).re = 0 := by
    have := congrFun hd 0
    simpa [honeycombD] using this
  have him : (structureFactor θ).im = 0 := by
    have := congrFun hd 1
    simpa [honeycombD] using this
  exact Complex.ext hre him

/-- **The model is gapped at every phase that is not a Dirac phase.** This is the AC's
`k ∉ {K, K'} → 0 < gap` in its usable form: the hypothesis is the negation of the three explicit
phase equations, so a consumer holding a concrete `θ` discharges it by arithmetic — no reasoning
about `f` and no quotient by the reciprocal lattice. Combined with
`structureFactor_eq_zero_iff_orbit`, the hypothesis is literally "`θ` is in neither the `K` nor the
`K'` reciprocal-lattice orbit". -/
theorem honeycomb_gapped_away_of_phase {θ : ℝ × ℝ}
    (h : ¬(Real.cos θ.1 = -(1/2) ∧ Real.cos θ.2 = -(1/2) ∧ Real.sin θ.1 + Real.sin θ.2 = 0)) :
    0 < Real.sqrt (dNormSq (honeycombD θ)) :=
  honeycomb_gapped_away (fun hf => h ((structureFactor_eq_zero_iff θ).mp hf))

/-! ## The hopping scale

Everything above normalizes the nearest-neighbour hopping amplitude to `t = 1`. The physical band
energies carry a factor `|t|`; this section supplies it, so that statements "in units of the
hopping `t`" have a `t` to refer to. -/

/-- The structure factor at a general hopping amplitude `t`: `f_t(θ) = t · f(θ)`. -/
noncomputable def structureFactorT (t : ℝ) (θ : ℝ × ℝ) : ℂ := (t : ℂ) * structureFactor θ

/-- The `d`-vector of the `t`-scaled honeycomb model. -/
noncomputable def honeycombDT (t : ℝ) (θ : ℝ × ℝ) : Fin 3 → ℝ :=
  ![(structureFactorT t θ).re, -(structureFactorT t θ).im, 0]

/-- **The band energies scale linearly in the hopping**: the half-gap is `|t|·|f(θ)|`. This is what
licenses reading the `t = 1` numbers below "in units of the hopping". -/
theorem honeycombT_energy_eq (t : ℝ) (θ : ℝ × ℝ) :
    Real.sqrt (dNormSq (honeycombDT t θ)) = |t| * ‖structureFactor θ‖ := by
  have hd : dNormSq (honeycombDT t θ) = t ^ 2 * Complex.normSq (structureFactor θ) := by
    unfold dNormSq honeycombDT structureFactorT Complex.normSq
    simp only [Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.head_cons, Matrix.cons_val_two,
      Matrix.tail_cons, MonoidWithZeroHom.coe_mk, ZeroHom.coe_mk, Complex.mul_re, Complex.mul_im,
      Complex.ofReal_re, Complex.ofReal_im]
    ring
  rw [hd, Real.sqrt_mul (sq_nonneg t), Real.sqrt_sq_eq_abs, Complex.norm_def]

/-- **The `t`-scaled bands are `±|t|·|f(θ)|`** as eigenvalues — the hopping-carrying form of
`honeycomb_band_secular`. -/
theorem honeycombT_band_secular (t : ℝ) (θ : ℝ × ℝ) :
    (blochPauli (honeycombDT t θ) - ((|t| * ‖structureFactor θ‖ : ℝ) : ℂ) • 1).det = 0 ∧
      (blochPauli (honeycombDT t θ) - ((-(|t| * ‖structureFactor θ‖) : ℝ) : ℂ) • 1).det = 0 := by
  have h := blochPauli_band_secular (honeycombDT t θ)
  rw [honeycombT_energy_eq] at h
  exact h

/-! ## High-symmetry witnesses -/

/-- **Γ point: `|f| = 3`.** All three hoppings add in phase — the band extremum. The evaluation is
`norm_num`-level, pinning the abstract band formula to an arithmetic fact at a named point. -/
theorem structureFactor_gamma : structureFactor gammaPoint = 3 := by
  unfold structureFactor gammaPoint
  norm_num

/-- The Γ-point band energy is `3` at `t = 1`; at general hopping it is `3|t|`
(`honeycombT_energy_gamma`). -/
theorem honeycomb_energy_gamma : Real.sqrt (dNormSq (honeycombD gammaPoint)) = 3 := by
  rw [honeycomb_energy_eq, structureFactor_gamma]
  norm_num

/-- **The Γ-point band energy in units of the hopping**: `3|t|`. This is the statement the phrase
"in units of the hopping `t`" refers to — the `t = 1` number above is its specialization. -/
theorem honeycombT_energy_gamma (t : ℝ) :
    Real.sqrt (dNormSq (honeycombDT t gammaPoint)) = 3 * |t| := by
  rw [honeycombT_energy_eq, structureFactor_gamma]
  norm_num [mul_comm]

/-- **M point: `|f| = 1`.** One hopping cancels against another, leaving a single unit — the
saddle-point value between Γ and the Dirac points. -/
theorem structureFactor_mPoint : structureFactor mPoint = 1 := by
  unfold structureFactor mPoint
  rw [Complex.exp_mul_I, Complex.exp_mul_I]
  simp

/-- The M-point band energy is `1`. Together with `honeycomb_energy_gamma` (`3`) and gaplessness at
`K` (`0`), the three named points give the band's full range as checkable numbers. -/
theorem honeycomb_energy_mPoint : Real.sqrt (dNormSq (honeycombD mPoint)) = 1 := by
  rw [honeycomb_energy_eq, structureFactor_mPoint]
  norm_num

/-- **The three high-symmetry values are pairwise distinct** — so the band is genuinely dispersive,
not a flat band the formulas would also permit. All three comparisons are stated (`Γ ≠ M`,
`M ≠ K`, `Γ ≠ K`): the first two alone would leave a two-valued band unexcluded. The non-vacuity
witness for the whole wave. -/
theorem honeycomb_band_dispersive :
    Real.sqrt (dNormSq (honeycombD gammaPoint)) ≠ Real.sqrt (dNormSq (honeycombD mPoint)) ∧
      Real.sqrt (dNormSq (honeycombD mPoint)) ≠ Real.sqrt (dNormSq (honeycombD diracK)) ∧
      Real.sqrt (dNormSq (honeycombD gammaPoint)) ≠ Real.sqrt (dNormSq (honeycombD diracK)) := by
  have hK : Real.sqrt (dNormSq (honeycombD diracK)) = 0 := by
    rw [honeycomb_energy_eq, honeycomb_gapless_at_diracK, norm_zero]
  refine ⟨?_, ?_, ?_⟩
  · rw [honeycomb_energy_gamma, honeycomb_energy_mPoint]; norm_num
  · rw [honeycomb_energy_mPoint, hK]; norm_num
  · rw [honeycomb_energy_gamma, hK]; norm_num

end SKEFTHawking.GrapheneBand
