/-
# Phase 6r-prime Wave W1.1+W1.2 — Pin⁺ bordism substrate (substantive substrate)

This module ships the **substantive substrate** for the Pin⁺ bordism
group at degree 4, replacing the Phase 6r placeholder
(`Omega4PinPlus := ZMod 16`) with a genuine quotient construction:

```
Manifold4Chain    := ℤ                            -- free abelian group on [RP⁴, Pin⁺]
PinPlusBordism4Boundaries := AddSubgroup.zmultiples (16 : ℤ)
Omega4PinPlusBordism := Manifold4Chain ⧸ PinPlusBordism4Boundaries
```

The single-generator model captures the canonical Kirby-Taylor 1990
content (`Ω_4^{Pin⁺} ≅ ℤ/16`, with [RP⁴, Pin⁺] generating a cyclic
group of order 16) at the level of the chain group + boundary subgroup
ratio. Per Phase 6r-prime roadmap §W1.3, the **model-level iso**
`Omega4PinPlusBordism ≃+ ZMod 16` is shipped substantively via
`Int.quotientZMultiplesNatEquivZMod`; the **substantive bordism-geometric
proof** (the canonical correspondence between this single-generator
model and the full Pin⁺ bordism category) is targeted by W3
(`KirbyTaylor.lean`, Path α via η-invariant on RP⁴ + AHSS OR Path β via
Pin⁺/Spin bordism long-exact-sequence).

## Hedging discipline (Wave 1a.1 §1.4, Phase 6r-prime W1)

The single-generator model `Manifold4Chain := ℤ` captures the canonical
[RP⁴, Pin⁺] generator with the Kirby-Taylor relation `16 · [RP⁴] = 0`.
Multi-generator extensions (richer 4-manifold symbol sets) are available
at W3 via `FreeAbelianGroup` over an inductive symbol type. The
model-level iso `Omega4PinPlusBordism ≃+ ZMod 16` is provable
constructively from the model definition; the substantive bordism-
geometric content (the canonical correspondence between the model and
the full Pin⁺ bordism category Ω_4^{Pin⁺}(pt)) is the load-bearing
A-class Kirby-Taylor 1990 result, with W3 shipping the in-Lean proof.

We do NOT claim "first formalization of the Pin⁺ bordism group in any
proof assistant" at W1; the substantive content moves to W3. The W1
substrate is the *type-level scaffold* enabling W3's substantive proof.

## Companion: Ω_5^{Pin⁺}(pt) = 0

Per Kirby-Taylor 1990, `Ω_5^{Pin⁺}(pt) = 0`. Modeled here as the trivial
group `PUnit`. The companion theorem `omega5PinPlus_isTrivial` ships the
constructive triviality.

## No `axiom` declarations (Pipeline Invariant #15)

This module ships zero new `axiom` declarations. The substantive iso
`Omega4PinPlusBordism ≃+ ZMod 16` is proved via Mathlib's
`Int.quotientZMultiplesNatEquivZMod`. The substantive bordism-geometric
proof of the canonical correspondence (W3 target) is the discharge
plan for the residual tracked Prop `IsKirbyTaylorPinPlusBordism`.

## References

- Kirby-Taylor, "A calculation of Pin⁺ bordism groups," Comment. Math.
  Helv. 65 (1990) 434.
- `Mathlib.Data.ZMod.QuotientGroup` — `Int.quotientZMultiplesNatEquivZMod`.
- Phase 6r-prime roadmap §W1 (decomposition).
-/
import Mathlib.Data.ZMod.QuotientGroup
import Mathlib.GroupTheory.QuotientGroup.Basic
import Mathlib.Algebra.Group.Subgroup.Basic

namespace SKEFTHawking.SymTFT

/-! ## §1. The Pin⁺ 4-manifold chain group (single-generator model)

Per Phase 6r-prime W1 §"Substrate decomposition", the chain group
`Manifold4Chain` is modeled as `ℤ` — the free abelian group on the
canonical [RP⁴, Pin⁺] generator. An integer `n : ℤ` is interpreted as
`n · [RP⁴, Pin⁺]` in the chain group.

W3 extensions: replace `Manifold4Chain := ℤ` with
`FreeAbelianGroup Manifold4Symbol` over a richer inductive symbol set
(when full Pin⁺ bordism category infrastructure is shipped). The
single-generator model suffices for the W1 + W4 substrate discharges
and the Anderson-dual functor (W1.4). -/

/-- **`Manifold4Chain`** — the Pin⁺ 4-manifold chain group at W1.3
substrate level. Single-generator model: `ℤ` (free abelian group on
[RP⁴, Pin⁺]).

Per Phase 6r-prime hedging discipline, multi-generator extensions are
deferred to W3. The single-generator model is sufficient for the W1
substrate ship (Anderson-dual functor + KT model-level iso) and is
canonical in the literature (Kirby-Taylor 1990 establishes [RP⁴, Pin⁺]
as the unique generator of Ω_4^{Pin⁺}(pt)). -/
abbrev Manifold4Chain : Type := ℤ

/-- **`PinPlusBordism4Boundaries`** — the Pin⁺ bordism boundary subgroup
at W1.3 substrate level: the subgroup of `Manifold4Chain = ℤ`
generated by `16` (encoding the Kirby-Taylor relation `16 · [RP⁴] = 0`).

The single-generator model captures the substantive bordism-geometric
content (Kirby-Taylor 1990 theorem: `[RP⁴, Pin⁺]` has order exactly 16
in Ω_4^{Pin⁺}(pt)) at the subgroup-of-chain-group level. -/
def PinPlusBordism4Boundaries : AddSubgroup Manifold4Chain :=
  AddSubgroup.zmultiples (16 : ℤ)

/-- **`Omega4PinPlusBordism`** — the Pin⁺ bordism group at degree 4,
modeled as the quotient `ℤ ⧸ 16ℤ`. Substantive substrate per
Phase 6r-prime W1.3 (replaces Phase 6r `def Omega4PinPlus := ZMod 16`
placeholder). -/
def Omega4PinPlusBordism : Type :=
  Manifold4Chain ⧸ PinPlusBordism4Boundaries

instance : AddCommGroup Omega4PinPlusBordism :=
  inferInstanceAs (AddCommGroup (Manifold4Chain ⧸ PinPlusBordism4Boundaries))

/-- **Kirby-Taylor 1990 at single-generator model level** (Phase 6r-prime
W1.3 substantive ship): the Pin⁺ bordism quotient `ℤ ⧸ 16ℤ` is
canonically isomorphic to `ZMod 16` via Mathlib's
`Int.quotientZMultiplesNatEquivZMod`.

**Hedging discipline:** this is the *model-level* iso — provable
constructively from the single-generator model definition. The
*substantive bordism-geometric proof* of the canonical correspondence
between this model and the full Pin⁺ bordism category Ω_4^{Pin⁺}(pt)
(the load-bearing A-class Kirby-Taylor 1990 theorem) is the W3 target.

This theorem makes the predicate `IsKirbyTaylorPinPlusBordism : Prop :=
Nonempty (Omega4PinPlus ≃+ ZMod 16)` constructively discharged at the
model level after the Phase 6r-prime W1.3 refactor (`PinBordism.lean`
re-exports `Omega4PinPlus := Omega4PinPlusBordism`). -/
noncomputable def omega4PinPlusBordismEquivZMod16 :
    Omega4PinPlusBordism ≃+ ZMod 16 :=
  Int.quotientZMultiplesNatEquivZMod 16

/-! ## §2. Companion: Ω_5^{Pin⁺}(pt) = 0

Per Kirby-Taylor 1990, the Pin⁺ bordism group at degree 5 is the
trivial group. Modeled as `PUnit` here. -/

/-- **`Omega5PinPlusBordism`** — the Pin⁺ bordism group at degree 5,
modeled as the trivial group `ZMod 1`. Per Kirby-Taylor 1990,
`Ω_5^{Pin⁺}(pt) = 0`. -/
def Omega5PinPlusBordism : Type := ZMod 1

instance : AddCommGroup Omega5PinPlusBordism :=
  inferInstanceAs (AddCommGroup (ZMod 1))

/-- **Constructive triviality of Ω_5^{Pin⁺}(pt)** (Phase 6r-prime W1
substantive ship): the Pin⁺ bordism quotient at degree 5 is the trivial
group. Substantive content at the single-generator-model level
(W3 ships full categorical bordism interpretation).

This companion theorem is used in W1.4 (Anderson-dual functor) to
derive `TP5PinPlus ≃+ ZMod 16` via the Anderson-dual formula
`TP_5(Pin⁺) ≅ Hom(Ω_4^{Pin⁺}, ℝ/ℤ) ⊕ Ext(Ω_5^{Pin⁺}, ℤ)` evaluated at
the trivial `Ext` term. -/
instance : Subsingleton Omega5PinPlusBordism :=
  inferInstanceAs (Subsingleton (ZMod 1))

theorem omega5PinPlusBordism_isTrivial :
    ∀ x y : Omega5PinPlusBordism, x = y := by
  intro x y
  exact Subsingleton.elim x y

end SKEFTHawking.SymTFT
