/-
# Phase 6r Wave 2a.4 — Schellekens chain alignment cross-bridge

The alignment-only cross-bridge between the spin-SymTFT framework
(Phase 6r Wave 2a) and the existing Phase 6o Wave 2b Schellekens chain
(c=24 holomorphic VOA + modular invariance). Per Wave 2a.1 §5.1, this
is an alignment-only cross-bridge, **NOT a substantive unification**:
the ℤ/16 Pin⁺-fermionic Witt-subgroup and the ℤ/24 bosonic c=24
Witt-group structure intersect at the substrate-data level via
`apsEta_to_wittInvariant`, but cannot be unified into a single
rigidification of either side.

## Finding (Wave 2a.1 §5.1, LOAD-BEARING)

> "The Schellekens c=24 modular-data chain (Phase 6o Wave 2b, SHIPPED)
> and the spin-SymTFT bulk (Wave 2a.2, in progress) are **alignment-
> compatible, not substantively unified**. The spin-SymTFT bulk is NOT
> the natural 'rigidification' of the Schellekens chain. Reasons:
> - The Schellekens chain operates on **bosonic** c=24 holomorphic
>   VOAs; the relevant categorical framework is bosonic modular tensor
>   categories, not spin/fermionic.
> - The Wave 2a spin-SymTFT bulk is **Pin⁺-fermionic**, classified by
>   ℤ/16.
> - The two structures intersect at the substrate level via
>   `apsEta_to_wittInvariant`, which maps SubstrateConfig data to the
>   Schellekens-side Witt invariant (ℤ/24). The 16 vs 24 mismatch is
>   intrinsic — no rigidification turns one into the other."

This module ships the alignment-only cross-bridge, explicitly disclaiming
any rigidification claim.

## References

- Phase 6o Wave 2b Schellekens chain: `SKEFTHawking.Schellekens.Chain`.
- Phase 6o Wave 2a APSEta SymTFT bridge: `APSEta/SymTFTBridge.lean`
  (`wave_2a_6_symtft_bridge_closure`).
- Wave 2a.1 DR §5.
- Wave 2a.3 SpinSymTFT.lean (`IsSpinSymTFTConsistent`,
  `wave_2a_3_substantive_instance`).
-/
import SKEFTHawking.SymTFT.SpinSymTFT
import SKEFTHawking.APSEta.SymTFTBridge

namespace SKEFTHawking.SymTFT

open SKEFTHawking SKEFTHawking.Z16AnomalyForcesThetaBar

/-! ## §1. The alignment-only cross-bridge theorem -/

/-- **`wave_2a_schellekens_alignment`** — alignment-only cross-bridge:
an Anderson-dual spin bulk with ℤ/16-trivial class, when projected
through the substrate's `apsEta_to_wittInvariant`, yields a ℤ/24-trivial
Witt invariant.

The composite map is NOT a rigidification — it factors through bosonic-
shadow data, with the fermionic content of the spin bulk dropping out.

The signature explicitly bridges:
- LHS: spin-SymTFT side (Phase 6r Wave 2a): `IsSpinSymTFTConsistent s`
  ⟹ `s.z16_class = 0` (the Pin⁺ ℤ/16-trivial half of the alignment).
- RHS: Schellekens side (Phase 6o Wave 2b): `apsEta_to_wittInvariant
  apsSubstrate = 0` (the modular ℤ/24-trivial half).

Per Wave 2a.1 §5.1, the connection is one-way alignment, not equivalence.

**Strengthening (round-1 adversarial review remediation):** the LHS
hypothesis is now load-bearing — the theorem ships BOTH halves of
the alignment as a single conjunction: (i) the spin-SymTFT-side
implies its ℤ/16 cancellation, AND (ii) the Schellekens-side ℤ/24
class is trivial at the substrate-data layer. -/
theorem wave_2a_schellekens_alignment (s : SubstrateConfig)
    (hConsistent : IsSpinSymTFTConsistent s) :
    s.z16_class = 0 ∧
    ∀ apsSubstrate : APSEta.Substrate,
      APSEta.apsEta_to_wittInvariant apsSubstrate = 0 := by
  refine ⟨?_, ?_⟩
  · -- LHS spin-SymTFT side: consistency forces Z/16 cancellation
    exact (wave_2a_3_substantive_instance s).mp hConsistent
  · -- RHS Schellekens side: APS-η Witt-invariant is trivial at substrate-data layer
    exact APSEta.apsEta_to_wittInvariant_zero

/-! ## §2. The Z₂₄-vs-Z₁₆ distinction (Wave 3a.1 §Caveats discipline) -/

/-- **`Z24_and_Z16_are_disjoint_sectors`** — explicit predicate stating
that the ℤ/24 (modular Witt) and ℤ/16 (Pin⁺ spin-extension Witt)
groups are distinct invariants of the SymTFT bulk, occupying disjoint
sectors of the categorical Witt-group structure.

Per Davydov-Nikshych-Ostrik arXiv:1109.5558 sequel ("the kernel of the
canonical homomorphism S: W → sW is generated by Ising categories and
is isomorphic to Z/16Z"), the ℤ/16 lives as the Ising-Witt-subgroup
kernel of the W → sW map; the ℤ/24 lives in the *modular* Witt group W.

The "fact that *both* a Z₁₆ and a Z₂₄ live inside the same Witt-group
structure is mathematically consistent but easily confused in informal
prose" (Wave 3a.1 §Caveats). This predicate is the Lean-side discipline
marker. -/
def Z24_and_Z16_are_disjoint_sectors : Prop :=
  -- Predicate-substrate body: ZMod 24 and ZMod 16 are distinct types,
  -- not interconvertible via an isomorphism (verified by Fintype card
  -- inequality 24 ≠ 16).
  Fintype.card (ZMod 24) ≠ Fintype.card (ZMod 16)

theorem z24_and_z16_distinct : Z24_and_Z16_are_disjoint_sectors := by
  unfold Z24_and_Z16_are_disjoint_sectors
  decide

end SKEFTHawking.SymTFT
