/-
# Phase 6r-prime Wave C1.1 — Lagrangian-algebra anyon-set substantive content

Substantively ships the Kitaev-Kong 2012 Lagrangian-algebra criterion
at the anyon-set (Finset ToricAnyon) level, leveraging the existing
ToricCodeCenter.lean substrate (toricFusion + braidingPhase +
toric_global_dim_sq).

## Substantive content

Per Kitaev-Kong arXiv:1104.5047 §3 ("Models for gapped boundaries and
domain walls"), a Lagrangian algebra in an abelian MTC is equivalently
characterized as a subset S of simples satisfying:

1. **Contains the unit**: `vacuum ∈ S` (the algebra has a unit object).
2. **Closed under fusion**: `∀ a, b ∈ S, a × b ∈ S` (the algebra is closed
   under the multiplication operation).
3. **Trivial mutual braiding**: `∀ a, b ∈ S, braidingPhase a b = 1` (the
   subcategory generated by S is symmetric, i.e., the Müger center
   condition for boundary condensation).
4. **Maximum dimension**: `Σ_{a ∈ S} |d_a|² = D` (= `√(total D²)`), where
   D² is the total quantum dimension squared (= 4 for toric code, so
   D = 2 and sum of dims = 2). For abelian MTC with all qdim = 1,
   condition 4 simplifies to `|S| = D = 2`.

For toric code MTC = Z(Vec_{Z₂}):
- D² = 4 (Fintype.card ToricAnyon = 4, all qdims = 1 ⇒ Σ |d_a|² = 4)
- D = √4 = 2 ⇒ |S| = 2

The TWO Lagrangian algebras (per Bombin-Martín-Delgado 0803.5046 +
Kitaev-Kong) are:
- `lagrangianElectricSet = {vacuum, electric}` (condenses `e` anyon)
- `lagrangianMagneticSet = {vacuum, magnetic}` (condenses `m` anyon)

The third candidate `{vacuum, fermion}` is RULED OUT because the
fermion has self-braiding `-1 ≠ 1` (per `fermion_self_braiding` in
`ToricCodeCenter.lean`), violating condition 3.

## Honest scope

This ships the substantive C1.1 content at the **anyon-set level**:
the predicate `IsLagrangianAnyonSet` + two distinct witnesses + the
distinctness proof. The Frobenius-algebra structure on the corresponding
categorical objects `𝟙 ⊕ e` and `𝟙 ⊕ m` — which is the *direct-sum
construction* in `Center (Discrete (ZMod 2))` requiring direct-sum
structure on Drinfeld centers absent from Mathlib v4.29.1 at the right
typeclass level — is deferred. The substantive content shipped here is
sound for the SymTFT-boundary classification: the two distinct anyon
sets correspond bijectively to the two gapped boundary conditions
(Kitaev-Kong 2012 Theorem 5.4).

## C1 sequencing

- 🔄 **C1.1** (this file): Lagrangian-anyon-set predicate + two witnesses
- ⏳ **C1.2**: Classification — exactly these two satisfy the criterion
- ⏳ **C1.3**: Discharge `IsToricCodeTwoLagrangianAlgebraStructure` to
  reference the substantive content

## References

- Kitaev-Kong, "Models for gapped boundaries and domain walls," Commun.
  Math. Phys. 313 (2012) 351; arXiv:1104.5047 (§3, Theorem 5.4).
- Bombin-Martín-Delgado, "Family of non-Abelian Kitaev models on a
  lattice: Topological condensation and confinement," Phys. Rev. B 78
  (2008) 115421; arXiv:0803.5046.
- Kong, "Anyon condensation and tensor categories," Nucl. Phys. B 886
  (2014) 436; arXiv:1307.8244.
- Substrate: `lean/SKEFTHawking/ToricCodeCenter.lean` (ToricAnyon,
  toricFusion, braidingPhase, toric_global_dim_sq).
-/
import Mathlib
import SKEFTHawking.ToricCodeCenter

namespace SKEFTHawking.SymTFT

open SKEFTHawking

/-! ## §1. Lagrangian-anyon-set predicate -/

/-- **`IsLagrangianAnyonSet S`** — the predicate characterizing
Lagrangian-algebra anyon subsets of toric code per Kitaev-Kong
arXiv:1104.5047 §3. Combines four conditions:

1. `vacuum_mem`: `.vacuum ∈ S` (algebra has a unit)
2. `fusion_closed`: `∀ a, b ∈ S, toricFusion a b ∈ S`
3. `braiding_trivial`: `∀ a, b ∈ S, braidingPhase a b = 1`
4. `correct_dimension`: `S.card = 2` (for toric code D = √4 = 2,
   abelian MTC so all qdims = 1; the dimension condition reduces
   to cardinality)

The substantive content is the conjunction; downstream theorems
will show that the two distinct Lagrangian-algebra-anyon-sets
`{vacuum, electric}` and `{vacuum, magnetic}` satisfy all 4
conditions, and no other subset does. -/
structure IsLagrangianAnyonSet (S : Finset ToricAnyon) : Prop where
  vacuum_mem : ToricAnyon.vacuum ∈ S
  fusion_closed : ∀ a ∈ S, ∀ b ∈ S, toricFusion a b ∈ S
  braiding_trivial : ∀ a ∈ S, ∀ b ∈ S, braidingPhase a b = 1
  correct_dimension : S.card = 2

/-! ## §2. Concrete Lagrangian-algebra-anyon-set witnesses -/

/-- **`lagrangianElectricSet`** — the electric Lagrangian-algebra anyon
set `{vacuum, electric}`. Per Bombin-Martín-Delgado 0803.5046 + Kitaev-
Kong, this is the boundary condensation that condenses the `e` anyon. -/
def lagrangianElectricSet : Finset ToricAnyon :=
  {ToricAnyon.vacuum, ToricAnyon.electric}

/-- **`lagrangianMagneticSet`** — the magnetic Lagrangian-algebra anyon
set `{vacuum, magnetic}`. Symmetric counterpart to electric: condenses
the `m` anyon. -/
def lagrangianMagneticSet : Finset ToricAnyon :=
  {ToricAnyon.vacuum, ToricAnyon.magnetic}

/-! ## §3. Substantive witness: electric set is Lagrangian -/

/-- **C1.1 electric witness**: `lagrangianElectricSet = {vacuum, electric}`
is a Lagrangian-algebra anyon set. The proof verifies all 4 Kitaev-Kong
criteria via `decide` on the concrete 4-element ToricAnyon inductive. -/
theorem isLagrangianAnyonSet_electric :
    IsLagrangianAnyonSet lagrangianElectricSet := by
  refine ⟨?_, ?_, ?_, ?_⟩
  · -- vacuum_mem
    decide
  · -- fusion_closed: ∀ a, b ∈ S, toricFusion a b ∈ S
    intro a ha b hb
    fin_cases ha <;> fin_cases hb <;> decide
  · -- braiding_trivial: all pairs braid to +1
    intro a ha b hb
    fin_cases ha <;> fin_cases hb <;> rfl
  · -- correct_dimension: card = 2
    decide

/-! ## §4. Substantive witness: magnetic set is Lagrangian -/

/-- **C1.1 magnetic witness**: `lagrangianMagneticSet = {vacuum, magnetic}`
is a Lagrangian-algebra anyon set. Symmetric to the electric case;
proof uses the same `decide`-based verification on the 4 Kitaev-Kong
criteria. -/
theorem isLagrangianAnyonSet_magnetic :
    IsLagrangianAnyonSet lagrangianMagneticSet := by
  refine ⟨?_, ?_, ?_, ?_⟩
  · decide
  · intro a ha b hb
    fin_cases ha <;> fin_cases hb <;> decide
  · intro a ha b hb
    fin_cases ha <;> fin_cases hb <;> rfl
  · decide

/-! ## §5. Substantive distinctness: electric ≠ magnetic -/

/-- **C1.1 distinctness**: the two Lagrangian-algebra anyon sets are
distinct. This is the *substantive* electric/magnetic distinction at
the anyon-set level (not just inductive-label distinctness). -/
theorem lagrangianElectricSet_ne_magneticSet :
    lagrangianElectricSet ≠ lagrangianMagneticSet := by
  decide

/-! ## §6. Falsifier: fermion set fails braiding triviality -/

/-- **`brokenFermionSet`** — the candidate `{vacuum, fermion}` anyon
set. This satisfies conditions 1, 2, 4 (contains unit, closed under
fusion since `fermion² = vacuum`, cardinality 2) but FAILS condition 3
(fermion has self-braiding `-1 ≠ 1` per `fermion_self_braiding`).

This is the C1.1 falsifier: not every 2-element subset containing the
vacuum is a Lagrangian algebra — the braiding-triviality condition is
load-bearing. -/
def brokenFermionSet : Finset ToricAnyon :=
  {ToricAnyon.vacuum, ToricAnyon.fermion}

/-- **C1.1 falsifier**: the fermion set is NOT a Lagrangian-algebra
anyon set, because the fermion self-braiding is -1, not +1. This
substantively confirms that condition 3 (braiding triviality) is
non-vacuous. -/
theorem not_isLagrangianAnyonSet_brokenFermion :
    ¬ IsLagrangianAnyonSet brokenFermionSet := by
  intro h
  have hmem : ToricAnyon.fermion ∈ brokenFermionSet := by decide
  have hbraid : braidingPhase ToricAnyon.fermion ToricAnyon.fermion = 1 :=
    h.braiding_trivial _ hmem _ hmem
  have : (-1 : ℤ) = 1 := by
    rw [← fermion_self_braiding]; exact hbraid
  exact absurd this (by decide)

/-! ## §7. C1.1 closure theorem -/

/-- **C1.1 closure**: the substantive content shipped by C1.1.

(a) Two distinct anyon sets both satisfy the Kitaev-Kong Lagrangian
    criterion.
(b) The two sets are not equal (substantive distinctness).
(c) The fermion-based candidate is NOT a Lagrangian algebra (showing
    condition 3 is load-bearing).

This is the substantive C1.1 deliverable. The C1.2 classification
(exactly these two satisfy the criterion) is shipped below in §8. -/
theorem c1_1_closure :
    IsLagrangianAnyonSet lagrangianElectricSet ∧
    IsLagrangianAnyonSet lagrangianMagneticSet ∧
    lagrangianElectricSet ≠ lagrangianMagneticSet ∧
    ¬ IsLagrangianAnyonSet brokenFermionSet :=
  ⟨isLagrangianAnyonSet_electric,
   isLagrangianAnyonSet_magnetic,
   lagrangianElectricSet_ne_magneticSet,
   not_isLagrangianAnyonSet_brokenFermion⟩

/-! ## §8. C1.2 classification theorem -/

/-- **C1.2 enumeration lemma**: every 2-element subset of `ToricAnyon`
containing `vacuum` is one of `{vacuum, electric}`, `{vacuum, magnetic}`,
or `{vacuum, fermion}`. Discharged via finite case analysis on the
3 non-vacuum anyons (the 2-element set with vacuum is uniquely
determined by its other element). -/
theorem twoElementSetContainingVacuum_classification
    (S : Finset ToricAnyon) (hvac : ToricAnyon.vacuum ∈ S)
    (hcard : S.card = 2) :
    S = lagrangianElectricSet ∨
    S = lagrangianMagneticSet ∨
    S = brokenFermionSet := by
  -- Since |S| = 2 and vacuum ∈ S, S = {vacuum, x} for unique x ≠ vacuum.
  -- The other element x must be in {electric, magnetic, fermion}.
  -- Enumerate via the membership of each non-vacuum anyon.
  by_cases he : ToricAnyon.electric ∈ S
  · -- S contains vacuum and electric, |S| = 2 ⇒ S = {vacuum, electric}
    left
    apply Finset.eq_of_subset_of_card_le
    · intro a ha
      fin_cases a
      · exact (by decide : ToricAnyon.vacuum ∈ lagrangianElectricSet)
      · exact (by decide : ToricAnyon.electric ∈ lagrangianElectricSet)
      · -- magnetic ∈ S would force |S| ≥ 3
        exfalso
        have : ({ToricAnyon.vacuum, ToricAnyon.electric, ToricAnyon.magnetic} : Finset _) ⊆ S := by
          intro b hb; fin_cases hb <;> first | exact hvac | exact he | exact ha
        have h3 : S.card ≥ 3 := by
          have : ({ToricAnyon.vacuum, ToricAnyon.electric, ToricAnyon.magnetic} : Finset _).card = 3 := by decide
          calc S.card ≥ ({ToricAnyon.vacuum, ToricAnyon.electric, ToricAnyon.magnetic} : Finset _).card :=
                Finset.card_le_card ‹_›
            _ = 3 := this
        omega
      · -- fermion ∈ S would force |S| ≥ 3
        exfalso
        have : ({ToricAnyon.vacuum, ToricAnyon.electric, ToricAnyon.fermion} : Finset _) ⊆ S := by
          intro b hb; fin_cases hb <;> first | exact hvac | exact he | exact ha
        have h3 : S.card ≥ 3 := by
          have : ({ToricAnyon.vacuum, ToricAnyon.electric, ToricAnyon.fermion} : Finset _).card = 3 := by decide
          calc S.card ≥ ({ToricAnyon.vacuum, ToricAnyon.electric, ToricAnyon.fermion} : Finset _).card :=
                Finset.card_le_card ‹_›
            _ = 3 := this
        omega
    · rw [hcard]; decide
  · -- electric ∉ S; check magnetic
    by_cases hm : ToricAnyon.magnetic ∈ S
    · -- S contains vacuum and magnetic, |S| = 2 ⇒ S = {vacuum, magnetic}
      right; left
      apply Finset.eq_of_subset_of_card_le
      · intro a ha
        fin_cases a
        · decide
        · exact absurd ha he
        · decide
        · exfalso
          have : ({ToricAnyon.vacuum, ToricAnyon.magnetic, ToricAnyon.fermion} : Finset _) ⊆ S := by
            intro b hb; fin_cases hb <;> first | exact hvac | exact hm | exact ha
          have h3 : S.card ≥ 3 := by
            have : ({ToricAnyon.vacuum, ToricAnyon.magnetic, ToricAnyon.fermion} : Finset _).card = 3 := by decide
            calc S.card ≥ ({ToricAnyon.vacuum, ToricAnyon.magnetic, ToricAnyon.fermion} : Finset _).card :=
                  Finset.card_le_card ‹_›
              _ = 3 := this
          omega
      · rw [hcard]; decide
    · -- electric ∉ S, magnetic ∉ S; the only other element is fermion
      by_cases hf : ToricAnyon.fermion ∈ S
      · right; right
        apply Finset.eq_of_subset_of_card_le
        · intro a ha
          fin_cases a
          · decide
          · exact absurd ha he
          · exact absurd ha hm
          · decide
        · rw [hcard]; decide
      · -- All non-vacuum anyons not in S ⇒ S = {vacuum} ⇒ |S| = 1, contradiction
        exfalso
        have : S = {ToricAnyon.vacuum} := by
          apply Finset.eq_of_subset_of_card_le
          · intro a ha
            fin_cases a
            · decide
            · exact absurd ha he
            · exact absurd ha hm
            · exact absurd ha hf
          · have : ({ToricAnyon.vacuum} : Finset _).card = 1 := by decide
            rw [this]; omega
        rw [this] at hcard
        simp at hcard

/-- **C1.2 main classification theorem**: every Lagrangian-algebra
anyon set in toric code MTC equals either `lagrangianElectricSet`
or `lagrangianMagneticSet`.

Per Kitaev-Kong arXiv:1104.5047 Theorem 5.4: the toric code has
*exactly two* Lagrangian algebras up to equivalence. This theorem
makes that classification explicit at the substantive anyon-set level.

The proof composes: (a) the cardinality-2 + vacuum-membership
constraint reduces S to one of three candidates ({vac,e}, {vac,m},
{vac,fermion}); (b) the braiding-triviality condition rules out
the fermion candidate (via `not_isLagrangianAnyonSet_brokenFermion`).

This is the substantive C1.2 deliverable: the "exactly two" classification
content backing the Phase 6r tracked Prop
`IsToricCodeTwoLagrangianAlgebraStructure`. -/
theorem isLagrangianAnyonSet_classification (S : Finset ToricAnyon)
    (h : IsLagrangianAnyonSet S) :
    S = lagrangianElectricSet ∨ S = lagrangianMagneticSet := by
  rcases twoElementSetContainingVacuum_classification S h.vacuum_mem h.correct_dimension with
    helec | hmag | hfer
  · left; exact helec
  · right; exact hmag
  · -- The fermion case is ruled out by braiding triviality
    exfalso
    apply not_isLagrangianAnyonSet_brokenFermion
    rw [← hfer]
    exact h

/-- **C1.2 closure**: bundles the C1.1 + C1.2 substantive content into
a single statement. The substantive deliverable: toric code has
EXACTLY two Lagrangian-algebra anyon sets, both distinct. -/
theorem c1_classification_closure :
    IsLagrangianAnyonSet lagrangianElectricSet ∧
    IsLagrangianAnyonSet lagrangianMagneticSet ∧
    lagrangianElectricSet ≠ lagrangianMagneticSet ∧
    (∀ S : Finset ToricAnyon, IsLagrangianAnyonSet S →
      S = lagrangianElectricSet ∨ S = lagrangianMagneticSet) :=
  ⟨isLagrangianAnyonSet_electric,
   isLagrangianAnyonSet_magnetic,
   lagrangianElectricSet_ne_magneticSet,
   isLagrangianAnyonSet_classification⟩

end SKEFTHawking.SymTFT
